### ISSUE TITLE
Sensitivity of ner_crf with prepositions and adjectives

### ISSUE THREAD

**Issue by ctrado18** [RasaHQ/rasa_nlu#1003]
Hey! :-)

the crf ner often detects two words as an entity if the sentence structure is equal( that is not strange of course). I train my NLU with those examples of adjectives. Which feature I can tune to avoid this? Example:

`how much costs a bike?` and
`how much costs a broken bike?`

here in the first case `bike` is an entity and in the second case `broken bike` is the entity. Sometimes it detects those as two entitties `broken` and `bike`. I use ner_crf for the german language.

Default ner_crf just uses the word before and after, right? Can you change this to use more words preceeding?

**Comment by akelad** [comment]
Yeah so ner_crf just uses the before/after word the way we've implemented it. What you can do though is add those examples without entity labels and that should improve performance

**Comment by akelad** [comment]
sorry, actually you can. you just need to add the `features` configuration of `ner_crf` to the config file to contain 2 words before/after. so something like this:

```
- name: "ner_crf"
   features: [
            ["low", "title", "upper", "pos", "pos2"],
            ["low", "title", "upper", "pos", "pos2"],
            ["bias", "low", "word3", "word2", "upper",
             "title", "digit", "pos", "pos2", "pattern"],
            ["low", "title", "upper", "pos", "pos2"],
            ["low", "title", "upper", "pos", "pos2"]]
```

**Comment by ctrado18** [comment]
@akelad  
>  What you can do though is add those examples without entity labels and that should improve performance

Why does this improve the performance? why not just adding examples with `broken bike`? So you mean adding text with part `broken bike` but not label any entity? can you explain this behaviour?

**Comment by akelad** [comment]
i'm not sure what you mean? I thought your problem was that it was recognising `broken bike` as an entity when you didn't want to do? Adding the sentence `how much costs a broken bike?` to your training without an entity label would teach NER that `broken bike` is not an entity.

Though, what version of NLU were you using previously? because if it was before 0.11.5, it's possible that that entity was being extracted due to a bug in ner_crf

**Comment by ctrado18** [comment]
For a sentence with broken bike I want that bike is recognized as an entity. But broken bike as a whole is recognized as an entity. And yes I used version 11.4 so this stems from the bug?

**Comment by wrathagom** [comment]
@ctrado18 problem solved?
