### ISSUE TITLE
Spacy lower case needs to be configurable

### ISSUE THREAD

**Issue by r-wheeler** [RasaHQ/rasa_nlu#1007]
[here](https://github.com/RasaHQ/rasa_nlu/blob/master/rasa_nlu/utils/spacy_utils.py#L91)

```
for example in training_data.training_examples:
            example.set("spacy_doc", self.nlp(example.text.lower()))
```
That kind of feature needs to be configurable in the pipeline{yml|json}. Word embeddings and character embeddings are both very sensitive to case

**Comment by amn41** [comment]
for context https://github.com/RasaHQ/rasa_nlu/pull/729

**Comment by tmbo** [comment]
Due to our new config separation, this was a quick one :)

**Comment by tmbo** [comment]
parameter is called `case_sensitive`:

**Comment by r-wheeler** [comment]
ha, 💯thanks.
