### ISSUE TITLE
Any way to plot the SVM model object?

### ISSUE THREAD

**Issue by kuriakinzeng** [RasaHQ/rasa_nlu#1008]
Thank you for the great work in creating an open source NLU! 👍 

I understand that the intent classifier is multiclass SVM model. Is there a way that I can plot the model like the following one? https://mlr-org.github.io/figures/2015-07-28-Visualisation-of-predictions/linear-svm-1.svg

**Comment by tmbo** [comment]
Sure, in general it is possible to plot it, but it is questionable if it is helpful. The input dimensionality of the vectors passed to the SVM are > 300 dimensions so you'd need to reduce that to 2 dims (e.g. using t-SNE). But as said, I don't think this will help debug or reason about the model.

**Comment by kuriakinzeng** [comment]
Thank you. I have a follow-up question but to prevent off-topic discussion, I will start a new thread.
