### ISSUE TITLE
Set num_threads for sklearn in yaml does not work

### ISSUE THREAD

**Issue by r-wheeler** [RasaHQ/rasa_nlu#1009]
[here](https://github.com/RasaHQ/rasa_nlu/blob/f6b3d1b49e4cf4c644292f5f8ca61ac232b4b8c8/rasa_nlu/classifiers/sklearn_intent_classifier.py#L114)

setting 
`num_threads` in the yaml appears to be ignored.

Maybe something like: 
```
n_threads = self.component_config["n_threads"]
```
seems like only the CLI can enable currently. 

Suggest making the default to `-1` as well. 

Also suggest adding `verbose` flags to the yaml. Similar to the CountVectorizer, any sklearn kwarg should be able to be set in the yaml

**Comment by akelad** [comment]
yeah so `num_threads` should be passed as an argument to the train script. the yml now really only applies to the configuration of the pipeline components.

**Comment by r-wheeler** [comment]
Correct. Any argument available to the CLI trainer should be exposed to all interfaces of training. num_threads is just being set as n_jobs for the scikit SVM component. No reason to have the python based interface limited to a single core.

**Comment by wrathagom** [comment]
@tmbo @akelad I believe @r-wheeler is suggesting that since the `num_threads` only applies to the spacy intent classifier it belongs on that pipeline component rather than the global config.

**Comment by akelad** [comment]
@r-wheeler is this still relevant? if yes, would you be willing to submit a PR?
