### ISSUE TITLE
Encoding error on training

### ISSUE THREAD

**Issue by marcoaleixo** [RasaHQ/rasa_nlu#1018]
**Rasa NLU version**:
rasa-nlu==0.12.1

**Operating system** (windows, osx, ...):
ubuntu16.04
**Content of model configuration file**:
```yml

language: "pt"

pipeline:
# this is using the spacy sklearn pipeline, adding duckling
# all components will use their default values
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "intent_featurizer_spacy"
- name: "ner_crf"
- name: "ner_synonyms"
- name: "intent_classifier_sklearn"
- name: "ner_duckling"
```

**Issue**:
```
/srv/ambientes_virtuais/blabla/lib/python3.5/site-packages/rasa_nlu/training_data/training_data.py:194: UserWarning: Entity 'seguro-habitacional' has only 1 training examples! minimum is 2, training may fail.
  self.MIN_EXAMPLES_PER_ENTITY))
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/srv/ambientes_virtuais/blabla/lib/python3.5/site-packages/rasa_nlu/train.py", line 163, in <module>
    num_threads=cmdline_args.num_threads)
  File "/srv/ambientes_virtuais/blabla/lib/python3.5/site-packages/rasa_nlu/train.py", line 138, in do_train
    training_data = load_data(data, cfg.language)
  File "/srv/ambientes_virtuais/blabla/lib/python3.5/site-packages/rasa_nlu/training_data/loading.py", line 53, in load_data
    data_sets = [_load(f, language) for f in files]
  File "/srv/ambientes_virtuais/blabla/lib/python3.5/site-packages/rasa_nlu/training_data/loading.py", line 53, in <listcomp>
    data_sets = [_load(f, language) for f in files]
  File "/srv/ambientes_virtuais/blabla/lib/python3.5/site-packages/rasa_nlu/training_data/loading.py", line 82, in _load
    fformat = _guess_format(filename)
  File "/srv/ambientes_virtuais/blabla/lib/python3.5/site-packages/rasa_nlu/training_data/loading.py", line 99, in _guess_format
    content = utils.read_file(filename)
  File "/srv/ambientes_virtuais/blabla/lib/python3.5/site-packages/rasa_nlu/utils/__init__.py", line 202, in read_file
    return f.read()
  File "/srv/ambientes_virtuais/blabla/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
  File "/srv/ambientes_virtuais/blabla/lib/python3.5/encodings/utf_8_sig.py", line 69, in _buffer_decode
    return codecs.utf_8_decode(input, errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
```
I'm running with:

python -m rasa_nlu.train --config ./config_spacy_duckling.yml --data /srv/sites/blabla/algorithms/rasa_nlu/models/blabla/model_pt --path .

My data contains words like:  não, é, já era

**Comment by tmbo** [comment]
Do you mind sharing your training data as well so we can try to reproduce this?

**Comment by marcoaleixo** [comment]
It's private, can I send to you on another local?

**Comment by marcoaleixo** [comment]
Well, today I run a pip --upgrade rasa-nlu and worked like a charm. 
Strange..
But, solved, thank you for the attention.

**Comment by wrathagom** [comment]
Great! I'll close, but we can open again if it re-presents itself.

**Comment by dgotbaum** [comment]
I ran into this issue. I had another file that wasnt part of the data downloaded from DiagramFlow in the data folder (the zipped folder), it tried to parse this and caused the error.

**Comment by sona-user-369** [comment]
Me i have same issue. here is my data.json:
`{
  "rasa_nlu_data": {
    "common_examples": [
      {
        "text": "Hello",
        "intent": "greeting",
        "entities": [
          {
            "start": 0,
            "end": 5,
            "value": "Hello",
            "entity": "Politesse"
          }
        ]
      },
      {
        "text": "Hi",
        "intent": "greeting",
        "entities": [
          {
            "start": 0,
            "end": 2,
            "value": "Hi",
            "entity": "Politesse"
          }
        ]
      },
      {
        "text": "Salut",
        "intent": "greeting",
        "entities": [
          {
            "start": 0,
            "end": 5,
            "value": "Salut",
            "entity": "Politesse"
          }
        ]
      },
      {
        "text": "Bonsoir",
        "intent": "greeting",
        "entities": [
          {
            "start": 0,
            "end": 7,
            "value": "Bonsoir",
            "entity": "Politesse"
          }
        ]
      },
      {
        "text": "Bonjour",
        "intent": "greeting",
        "entities": [
          {
            "start": 0,
            "end": 7,
            "value": "Bonjour",
            "entity": "Politesse"
          }
        ]
      },
      {
        "text": "Je veux rendre ma maison propre",
        "intent": "book_room_washing",
        "entities": []
      },
      {
        "text": "Je veux réserver une agent d'entretien",
        "intent": "book_room_washing",
        "entities": [
          {
            "start": 20,
            "end": 38,
            "value": " agent d'entretien",
            "entity": "Personel"
          },
          {
            "start": 8,
            "end": 16,
            "value": "réserver",
            "entity": "Verbe de service"
          }
        ]
      },
      {
        "text": "je veux entretenir ma maison",
        "intent": "book_room_washing",
        "entities": [
          {
            "start": 8,
            "end": 18,
            "value": "entretenir",
            "entity": "Verbe de service"
          }
        ]
      },
      {
        "text": "Je veux me souscrire au service",
        "intent": "get_subscribe",
        "entities": [
          {
            "start": 10,
            "end": 20,
            "value": " souscrire",
            "entity": "Verbe de service"
          }
        ]
      },
      {
        "text": "je veux un agent d'entretien régulièrement",
        "intent": "get_subscribe",
        "entities": [
          {
            "start": 29,
            "end": 42,
            "value": "régulièrement",
            "entity": "Fréquence"
          },
          {
            "start": 11,
            "end": 28,
            "value": "agent d'entretien",
            "entity": "Personel"
          }
        ]
      },
      {
        "text": "Au revoir",
        "intent": "get_back",
        "entities": [
          {
            "start": 0,
            "end": 9,
            "value": "Au revoir",
            "entity": "Formule de retour"
          }
        ]
      }
    ],
    "regex_features": [],
    "entity_synonyms": []
  }
}`
