### ISSUE TITLE
download.py imports the deleted RasaNLUConfig class

### ISSUE THREAD

**Issue by lisongshan** [RasaHQ/rasa_nlu#1020]
**Rasa NLU version**:0.1.2.1, current master

**Operating system** (windows, osx, ...):

**Content of model configuration file**:
```yml

```

**Issue**:
download.py imports the deleted RasaNLUConfig class. It should import RasaNLUModelConfig
this bug breaks download of  mitie dat file.

**Comment by tmbo** [comment]
We will remove it in #1032 (it is a simple wget & untar as described in the docs anyways).

**Comment by wrathagom** [comment]
#1032 is merged so I am closing this.
