### ISSUE TITLE
ner_mitie training error with Chinese

### ISSUE THREAD

**Issue by fangd123** [RasaHQ/rasa_nlu#1024]
**Rasa NLU version**:0.12.1

**Operating system** (windows, osx, ...):ubuntu 16.04

**Content of model configuration file**:
```yml
language: "zh"

pipeline:
- name: "nlp_mitie"
- name: "tokenizer_jieba"
- name: "ner_mitie"
- name: "ner_synonyms"
- name: "intent_entity_featurizer_regex"
- name: "intent_featurizer_mitie"
- name: "intent_classifier_sklearn"
```

**Issue**:

The first problem is the format of the config file `config_jieba_mitie_sklearn.yml` in the sample config folder, I have changed it as above and removed some unnecessary punctuation. It now looks right.

And when I fixed the config file, It still got problems when I tried to train my data.

```bash
2018-04-19 17:19:33 INFO     rasa_nlu.model - Starting to train component ner_mitie
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mnt/e/rasa_nlu/rasa_nlu/train.py", line 163, in <module>
    num_threads=cmdline_args.num_threads)
  File "/mnt/e/rasa_nlu/rasa_nlu/train.py", line 139, in do_train
    interpreter = trainer.train(training_data, **kwargs)
  File "/mnt/e/rasa_nlu/rasa_nlu/model.py", line 190, in train
    **context)
  File "/mnt/e/rasa_nlu/rasa_nlu/extractors/mitie_entity_extractor.py", line 85, in train
    trainer.num_threads = kwargs.get("num_threads", 1)
  File "/usr/local/lib/python3.5/dist-packages/mitie/mitie.py", line 518, in num_threads
    _f.mitie_ner_trainer_set_num_threads(self.__obj, value)
ctypes.ArgumentError: argument 2: <class 'TypeError'>: wrong type
```
Can anyone tell me what's the problem and how to fix it? Thanks.

**Comment by howl-anderson** [comment]
Can you provide the whole config file? It seems `num_threads` get a wrong type value.

**Comment by fangd123** [comment]
I have provided the whole config file in the description of my issue. And when I tried to changed the code of  the file "rasa_nlu/rasa_nlu/extractors/mitie_entity_extractor.py", line 85, in train
```python
trainer.num_threads = kwargs.get("num_threads", 1)
```
to
```python
trainer.num_threads = 1
```
It works. So strange.

And my version of Python is 3.5

**Comment by tmbo** [comment]
@fangd123 can you create a PR with the config change you made to the sample config?

**Comment by howl-anderson** [comment]
It takes more time than I think because of  my laptop with an old CPU that not supported by tensorflow 1.6 which required by RASA NLU v0.12.1. I am still working on this issue.

**Comment by howl-anderson** [comment]
this issue is caused by default value of 'num_threads' is None which is setting by function `create_argument_parser` in `train.py`. **I will make a PR for this**.

**Comment by tmbo** [comment]
Thanks :+1:
