### ISSUE TITLE
rasa_nlu.server slow to start

### ISSUE THREAD

**Issue by kuriakinzeng** [RasaHQ/rasa_nlu#1027]
Thanks again for the great work! 

The server seems to be slow to start (it takes 15-30 min to start, even with a small model). I wonder if anyone has experienced the same, or know what might be the issue?

**Comment by tmbo** [comment]
That doesn't sound right. What does your server look like (e.g. how much mem does it have)?

**Comment by wrathagom** [comment]
@kuriakinzeng still experiencing this? Maybe worth trying it on 0.12.3 and seeing if the problem persists.

**Comment by keskarshreesh** [comment]
I'm facing the same issue, it's taking a long time for startup
