### ISSUE TITLE
ImportError: No module named 'rasa_nlu.converters'

### ISSUE THREAD

**Issue by NicoLivesey** [RasaHQ/rasa_nlu#1028]
**Rasa NLU version**: 0.12.1
**Operating system** (windows, osx, ...): Rasbian

**Content of model configuration file**: 
```yml
{
    "pipeline" : [ "nlp_spacy",
                   "tokenizer_spacy",
                    "ner_crf",
                    "ner_spacy",
                    "intent_featurizer_spacy",
                    "intent_classifier_sklearn"],
    "language" : "en",
    "path" : "./models/nlu",
    "data" : "./data/training_data.json"
}
```

**Issue**:

Trying to import the `load_data` function from `rasa_nlu.converters` but i get this:

`ImportError: No module named 'rasa_nlu.converters'`

All the other imports work well.

**Comment by NicoLivesey** [comment]
Ok I think my code is outdated. I refreshed it according to https://nlu.rasa.com/master/config.html but I still get an error because of the format of my config file:

`AttributeError: 'str' object has no attribute 'get'`

Here's my code.

```
from rasa_nlu.training_data import load_data
from rasa_nlu.config import RasaNLUModelConfig
from rasa_nlu.model import Trainer, Metadata, Interpreter
from rasa_nlu import config
 
def train (data, conf, model_dir):
    training_data = load_data(data)
    trainer = Trainer(config.load(conf))
    trainer.train(training_data)
    model_directory = trainer.persist(model_dir, fixed_model_name = 'chat')

def run():
   interpreter = Interpreter.load('./models/nlu/default/chat')
   print(interpreter.parse('some string'))

if __name__ == '__main__':
    train('./data/training_data.json', './config/config.json', './models/nlu')
    run()
```

Is this because `config.load()` doesn't support json file ?

**Comment by tmbo** [comment]
Yes, you need to use a yml configuration with the new version.

**Comment by NicoLivesey** [comment]
Ok that's what I thought I was doing the conversion. Thank you very much for your help !
