### ISSUE TITLE
using duckling to parse french langage

### ISSUE THREAD

**Issue by mega-coder** [RasaHQ/rasa_nlu#1039]
**Rasa NLU version**:

**Operating system** (windows, osx, ...):

**Content of model configuration file**:
```yml

```

**Issue**:

**Comment by mega-coder** [comment]
i'm trying to use  ner_duckling with rasa it works pretty well  with english phrases but french expressions dosen't work

**Comment by souvikg10** [comment]
How are you using the duckling version? Duckling version of the python wrapper may not contain all the dimensions as some dimensions were added recently for FR.

**Comment by znat** [comment]
I'm using the http one. The wrapped one makes the jre sometimes so it can't be used in a prod env where models can be trained.
Mostly using time and amount of money. The original wit.ai team is entirely French so I guess they maintain it well

**Comment by souvikg10** [comment]
@znat can you maybe create an issue at duckling? what rules are not able to detect? I have vested interest in FR and NL, so maybe I can add them :)

**Comment by souvikg10** [comment]
Oh okay great.. @mega-coder I think it is best if you can move to new_duckling_http

**Comment by mega-coder** [comment]
hi ,sorry for the late answer but i changed the language to fr in the configuration file  and it worked fine  so thank you @znat  !!

**Comment by akelad** [comment]
going to close this then, let us know if you have any other issues
