### ISSUE TITLE
Evaluation failed with 0 entities

### ISSUE THREAD

**Issue by AbdurRub** [RasaHQ/rasa_nlu#1045]
**Rasa NLU version**: 0.12.2

**Operating system** (windows, osx, ...): Ubuntu 17.10

**Content of model configuration file**:
```yml

```

**Issue**:
I have no entities in my data , evaluation script failed with this error.

line 424, in get_entity_predictions
    tokens.append(res["tokens"])
KeyError: u'tokens'

**Comment by tmbo** [comment]
What's the configuration you are using? .e.g are there any entity recognizers in there?

**Comment by AbdurRub** [comment]
language: "en"

pipeline:
- name: "intent_featurizer_count_vectors"
- name: "intent_classifier_tensorflow_embedding"
  intent_tokenization_flag: true
  intent_split_symbol: "_"

**Comment by tmbo** [comment]
Can you post the whole stacktrace please. Because there is actually a try n catch around that statement that catches exactly that error: https://github.com/RasaHQ/rasa_nlu/blob/0.12.2/rasa_nlu/evaluate.py#L422

**Comment by AbdurRub** [comment]
You mean this? 

https://gist.github.com/AbdurRub/f44aad8df64ab05a3b26be4930afaa8d

**Comment by tmbo** [comment]
Does the `No tokens present, which is fine if you don't have a tokenizer in your pipeline` show up in the log as well?

**Comment by AbdurRub** [comment]
No. It doesn't. 

https://gist.github.com/AbdurRub/557bde58ba0741fce56d71fbba0e8a6f

**Comment by akelad** [comment]
it looks to me like you might be using an old version of a branch or something? because that line number doesn't correspond to the right line in 0.12.2. And as Tom said, the exception should be caught. Can you try pulling from 0.12.2 and run it again?

**Comment by AbdurRub** [comment]
Resolve with 0.12.2 pulling.
