### ISSUE TITLE
Tensor flow Pipeline identify training example wrongly. 

### ISSUE THREAD

**Issue by AbdurRub** [RasaHQ/rasa_nlu#1046]
**Rasa NLU version**: 0.12.2

**Operating system** (windows, osx, ...): Ubuntu 17.10

**Content of model configuration file**:

**Issue**:
Getting this warning having 20+ None sceaniors in None.json file. 

rasa_nlu/training_data/training_data.py:186: UserWarning: Intent 'None' has only 1 training examples! Minimum is 2, training may fail.

I want to ask if there is any threshold of traning examples in tensorflow pipeline or it gives this warning with the intent having least examples.

**Comment by AbdurRub** [comment]
No, I have separate file of None intent and I have double checked that file there is only 1 intent None with 20+ examples.

**Comment by AbdurRub** [comment]
{
  "rasa_nlu_data": {
    "regex_features": [],
    "entity_synonyms": [],
    "common_examples": [
      {
        "text": "I really like you I wish I can live with you",
        "intent": "None",
        "entities": []
      },
      {
        "text": "hows weather in kashmir",
        "intent": "None",
        "entities": []
      },
      {
        "text": "I need clothes for my baby",
        "intent": "None",
        "entities": []
      },
      {
        "text": "I need food I am hungry since last friday",
        "intent": "None",
        "entities": []
      },
      {
        "text": "I hate you go away",
        "intent": "None",
        "entities": []
      },
      {
        "text": "how can I book my flight",
        "intent": "None",
        "entities": []
      },
      {
        "text": "hshwhaa ahwhswhza qhsh2w",
        "intent": "None",
        "entities": []
      },
      {
        "text": "deqsxsswsazaxc",
        "intent": "None",
        "entities": []
      },
      {
        "text": "I need books for science",
        "intent": "None",
        "entities": []
      },
      {
        "text": "I want to play games on playstation",
        "intent": "None",
        "entities": []
      },
      {
        "text": "fuck you bastard",
        "intent": "None",
        "entities": []
      },
      {
        "text": "need a gym , I put on alot of weight",
        "intent": "None",
        "entities": []
      },
      {
        "text": "shopping centers in the city",
        "intent": "None",
        "entities": []
      },
      {
        "text": "Want to go out for tea",
        "intent": "None",
        "entities": []
      },
      {
        "text": "Do you sell remote control airplanes ",
        "intent": "None",
        "entities": []
      },
      {
        "text": "How's the weather ",
        "intent": "None",
        "entities": []
      },
      {
        "text": "I want to play games ",
        "intent": "None",
        "entities": []
      },
      {
        "text": "I want a food, I am hungry ",
        "intent": "None",
        "entities": []
      },
      {
        "text": "Looking for medicines ",
        "intent": "None",
        "entities": []
      },
      {
        "text": "I want to drink water ",
        "intent": "None",
        "entities": []
      },
      {
        "text": "What clothes are you wearing ",
        "intent": "None",
        "entities": []
      },
      {
        "text": "looking at the sky",
        "intent": "None",
        "entities": []
      },
      {
        "text": "When are you getting free can we go out for a coffe?",
        "intent": "None",
        "entities": []
      },
      {
        "text": "I need to buy vegetables ",
        "intent": "None",
        "entities": []
      },
      {
        "text": "Do you smoke?",
        "intent": "None",
        "entities": []
      },
      {
        "text": "Drugs are bad for health ",
        "intent": "None",
        "entities": []
      },
      {
        "text": "Which mobile phone is good now a days",
        "intent": "None",
        "entities": []
      },
      {
        "text": "My laptop broke looking for a new one ",
        "intent": "None",
        "entities": []
      },
      {
        "text": "I am going to Africa ",
        "intent": "None",
        "entities": []
      },
      {
        "text": "Do you sell coco?",
        "intent": "None",
        "entities": []
      },
      {
        "text": "Do you sell cigar",
        "intent": "None",
        "entities": []
      },
      {
        "text": "looking for a cat ",
        "intent": "None",
        "entities": []
      }
    ]
  }
}

**Comment by AbdurRub** [comment]
https://gist.github.com/AbdurRub/08cc3dff18cb9f0f3d3f7d9d67e94d72

**Comment by AbdurRub** [comment]
Check out this log , during evaluation. 

https://gist.github.com/AbdurRub/1541021f6c02412a7d841f8511eed430

**Comment by AbdurRub** [comment]
I resolved this error , I just figured out I am having intent :" "  in other intent , but why its showing it None? :D

**Comment by akelad** [comment]
yeah you should probably label your intent something like `out_of_scope`. an empty string is equivalent to `None`, that's why you were getting that warning. I'll close this for now, as you seem to have fixed the issue
