### ISSUE TITLE
Add examples to error of overlapping entities during evaluation

### ISSUE THREAD

**Issue by AbdurRub** [RasaHQ/rasa_nlu#1048]
**Rasa NLU version**: 0.12.2

**Operating system** (windows, osx, ...): 17.10

**Content of model configuration file**:
```yml

```

**Issue**:
How can we identify which entities are overlapping because evaluation is giving me overlapping error. I have around 36 Entities.

**Comment by akelad** [comment]
upload it to something like https://rasahq.github.io/rasa-nlu-trainer/ this will show you your labeled entities

**Comment by wrathagom** [comment]
@AbdurRub did you find out if you had a problem with your training data?

**Comment by AbdurRub** [comment]
Its very hard to find out overlapping between 36 entities. rasa should point out which entity is overlapping with which sentence like they did in miss aligned entities warning.

**Comment by tmbo** [comment]
Yes that is a very good point :+1:

**Comment by akelad** [comment]
i belive this has been fixed
