### ISSUE TITLE
Load training data from folder via HTTP API

### ISSUE THREAD

**Issue by atotalnoob** [RasaHQ/rasa_nlu#1050]
**Rasa NLU version**: 0.12.0a1

**Operating system** (windows, osx, ...): Windows Server 2012

**Content of model configuration file**:
```
{
  "project": "chatbotDefault",
  "response_log": "C:/chatbot/App_Data/rasa/logs/",
  "port": 5006,
  "pipeline": "spacy_sklearn",
  "path": "C:/chatbot/App_Data/rasa/projects/",
  "data": "C:/chatbot/App_Data/rasa/data/chatbotDefault/"
}
```

**Issue**:
Similar to issue #650.

Training Rasa NLU via http POST. 

Using c# (restsharp) to make the post request:

```
public static void Train()
        {
            string project = "chatbotDefault";
            string config = "C:/chatbot/App_Data/rasa/configs/config_default.json";
            string data = "C:/chatbot/App_Data/rasa/data/chatbotDefault/";
            string url = @"http://ServerName:5006/train?project="+project;
            IRestResponse response;
            try
            {
                IRestRequest request = new RestRequest(Method.POST);

                request.AddParameter("-d", config);

                RestClient client = new RestClient(url);
                response = client.Execute(request);
               if (response.StatusCode != System.Net.HttpStatusCode.OK)
                {
                    throw new Exception("Error connecting" + response.StatusCode.ToString());
                }


            }
            catch (Exception e)
            {

                throw e;
            }
        }
```

I've also tried sending the post request to http://ServerName:5006/train?project="+project + "&d="+data;
As well as use -c and the config string in place of -d and data respectively. And just 'd', tried targetting a single .json training data file, instead of folder. 

The server returns with internal server error, with content as: 
`"{\n  \"error\": \"Unknown data format for file C:\\\\Users\\\\userName\\\\AppData\\\\Local\\\\Temp\\\\2\\\\tmpo5yso2fr_training_data\"\n}"`

That file is a 0 byte empty file. I double checked folder permissions and Rasa can write to that folder.

Rasa can also train if I do it locally, so my files are in correct format.

The rasa server outputs nothing useful or I would include it. Is there a way to have it print out more verbosely?

Please help!

**Comment by souvikg10** [comment]
I think in version 0.12, the config in moved to yaml file format.
see migration guide http://nlu.rasa.com/master/migrations.html

**Comment by souvikg10** [comment]
i also would suggest to move to version 0.12.2 as there are more bug fixes

**Comment by wrathagom** [comment]
@atotalnoob were you able to get it up and running?

**Comment by atotalnoob** [comment]
I moved to V12.2, problem still persisted. 

Issue was in my POST. I was using a relative path for the server. The path had to be relative to the POST requester's computer. So you can stream the file.

**Comment by atotalnoob** [comment]
Another question: 

Can I use /train and use a data directory? Rather than having the config with data in it?

**Comment by atotalnoob** [comment]
If anyone else comes across this, this is my c# class, using restsharp:

```
 public static string Train(string pathToTrain)
        {
            
            string project = "chatbotDefault";
            string url = @"serverUSL:5006/train?project=" + project;



            IRestResponse response;
            try
            {
                if (!pathToTrain.Contains(".yml")) 
                {
                    throw new Exception("Error - Invalid file path. File path must end in .yml");
                }

                IRestRequest request = new RestRequest(Method.POST);

                request.AddHeader("Content-Type", "Application/x-yml");
                var byteData = System.IO.File.ReadAllText(pathToTrain);
                request.AddParameter("data", byteData, ParameterType.RequestBody);


                RestClient client = new RestClient(url);
                response = client.Execute(request);
                if (response.StatusCode != System.Net.HttpStatusCode.OK)
                {
                    return "Error - " + response.StatusCode.ToString();
                }
                else
                {
                    //process returned JSON
                    return response.Content;
                }
                
            }
            catch (Exception e)
            {

                return e.ToString();
            }
```

**Comment by wrathagom** [comment]
why not create a wrapper script that walks a directory assembles a file and POST's all at once? Or is the payload too large?

**Comment by atotalnoob** [comment]
I disagree its strange. If I am trying to build something that end users can build their own chatbot model, it seems like training new models would be essential. 

I've build directories with multiple json files in them, having to traverse them, load them all into a new JSON object takes a while and would just be easier to give the server a directory and the server load them all. 

This is how it does it when training locally? 

@wrathagom Thats basically when I am doing, but its slow and I haven't tested the largest data set, so idk if it will be too large.

**Comment by wrathagom** [comment]
@atotalnoob I think you've tried Articulate, but in that case, we store the end users data in a database, then at training time we assemble training data and make the POST request. The assembly of data from the database takes less than a second, the training... takes as long as it takes.

How would the end user get their files onto the server running the HTTP API?

**Comment by atotalnoob** [comment]
Yeah, I tried articulate on my home PC.

We are using mongoDB and my company's MaaS. Its not slow, but its not fast. It is currently the slowest part of our process, so avoiding it as much as possible. As much as I despise Mongo, its excellent for our logging, but we have gone too far down this path to change and I'd rather not manage two databases at this stage or completely uproot our database and move to something else. We don't have a lot of bandwidth for this. 

The users build their training data directly in our UI, the server caches it locally on disk and then sends it to the DB async on a background thread. After it finishes saving, and confirms the save, it deletes the data from the cache. 

The same server has rasa on it. How we were training is manually, (yay tech debt, we only had one use case which we managed ourselves, so it wasn't a big deal and we only had 5 models) but now we are facing having multiple use cases coming down the pipeline so we are focusing on streamlining.

So we can either grab it from the mongoDB, or we can not delete it from the cache and load it from there (faster). We aren't hurting for disk space, and I'd rather have speed. 

Rasa already has the capability of using a data directory when training locally, so it shouldn't be much of an effort to change. I'll do it, if someone points me to where the relevant code is?

**Comment by atotalnoob** [comment]
Sorry for the wall of text, I get carried away

**Comment by wrathagom** [comment]
sorry, @atotalnoob got distracted and never replied. I wasn't necessarily using Articulate, just mentioning how we solve the problem. We're building agents with 10-20k examples and POSTing them direct to the train endpoint.

The code is [here](https://github.com/RasaHQ/rasa_nlu/blob/master/rasa_nlu/server.py#L280): obviously would be up to the rasa team @tmbo @amn41 if it would get merged.
