### ISSUE TITLE
Error when importing a Dialogflow standard/add-on Smalltalk intent

### ISSUE THREAD

**Issue by miande-acxiom** [RasaHQ/rasa_nlu#1051]
-> python -m rasa_nlu.train --config sample_configs/config_spacy.yml --data data/chatbot --path projects
/Users/me/anaconda2/lib/python2.7/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "/Users/me/anaconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Users/me/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/me/Documents/workspace/git/rasa_nlu/rasa_nlu/train.py", line 174, in <module>
    num_threads=cmdline_args.num_threads)
  File "/Users/me/Documents/workspace/git/rasa_nlu/rasa_nlu/train.py", line 148, in do_train
    training_data = load_data(data, cfg.language)
  File "rasa_nlu/training_data/loading.py", line 54, in load_data
    data_sets = [_load(f, language) for f in files]
  File "rasa_nlu/training_data/loading.py", line 101, in _load
    raise ValueError("Unknown data format for file {}".format(filename))
ValueError: Unknown data format for file data/chatbot/customSmalltalkResponses_en.json

sample_configs/config_spacy.yml:
language: "en"

pipeline: "spacy_sklearn"

**Comment by rithwikjc** [comment]
Seems like an issue with the format of the data provided in `customSmalltalkResponses_en.json`.

Open and take a look at the file and see that there is no deviation from Rasa's specified training data format. If you can make a gist containing the data, I can take a look at it.

**Comment by akelad** [comment]
So this isn't NLU training data - these are custom responses (equivalent to templates in rasa core). Therefore loading it as NLU training data won't work, the format of dialogflow nlu data is something like this https://github.com/RasaHQ/rasa_nlu/blob/master/data/examples/dialogflow/intents/hi.json

**Comment by wrathagom** [comment]
@miande-acxiom were you able to import the correct Dialog flow file?

**Comment by miande-acxiom** [comment]
I removed the problem file from the directory and all is working correctly.

**Comment by tmbo** [comment]
I'll close this for now, please let us know if you have any further questions.
