### ISSUE TITLE
Response generation

### ISSUE THREAD

**Issue by vijaykumarnadal** [RasaHQ/rasa_nlu#1054]
I am new to building chatbots with nlp platforms I have a query normally we have to provide intent and entities in building our app but is it possible to integrate the output automatic response generation models like example seq2seq,end to end memory networks with rasa

**Comment by amn41** [comment]
Rasa NLU only interprets messages, for generating responses you want to look at [Rasa Core](https://github.com/RasaHQ/rasa_core)
