### ISSUE TITLE
UTF-8 encoding leads to entity missing from the nlu model

### ISSUE THREAD

**Issue by NicoLivesey** [RasaHQ/rasa_nlu#1056]
**Rasa NLU version**: 0.8.6

**Operating system** (windows, osx, ...): Raspbian

**Content of model configuration file**:
```json
{
    "pipeline" : [ "nlp_spacy",
                   "tokenizer_spacy",
                    "ner_crf",
                    "ner_spacy",
                    "intent_featurizer_spacy",
                    "intent_classifier_sklearn"],
    "language" : "fr",
    "path" : "./models/nlu",
    "data" : "./data/training_data.json"
}
```

**Issue**:
Hi all, I am using the http server from rasa_core on an ec2 instance and I want to query it from my raspberry. The connexion works fine but since I need utf-8 encoding to pass parameters in the requests library, words that contain special character like `é` or others doesn't get recognized anymore as entities. Is there a way to make the nlu model utf-8 sensitive or add a decoder at the beginning of the pipeline?

Thanks for the help !

**Comment by wrathagom** [comment]
Related to #719 

@tmbo @amn41

**Comment by NicoLivesey** [comment]
Thanks for the reply but not completely since my problem is not the exactly same. In #719 specific characters lead to decoding error whereas I don't get any error but there is a loss of information with the utf-8 encoding and some entities don't get recognized anymore.

**Comment by tmbo** [comment]
The model itself is using Unicode to pass the message along to e.g. Spacy. Can you give me an example when the special character influences the NER. Best would be a small training data set and a request that doesn't work - hard to reproduce and fix otherwise as there is no error.

**Comment by wrathagom** [comment]
@NicoLivesey were you able to get past this issue?

**Comment by NicoLivesey** [comment]
Some sample from the training data
```json
{
        "text": "J'aimerais des conseils écologiques?",
        "intent": "tips_conso",
        "entities": [
          {
            "start": 24,
            "end": 35,
            "value": "écologique",
            "entity": "type"
          }
        ]
      }
```


Response from the http server:
```json
{
  "next_action": "utter_ask_tips_type",
  "tracker": {
    "events": null,
    "latest_event_time": 1525420659.1484578,
    "latest_message": {
      "entities": [],
      "intent": {
        "confidence": 0.5367467725845247,
        "name": "tips_conso"
      },
      "intent_ranking": [
SOME_INTENT_RANKING
      ],
      "text": "j'aimerais des conseils \u00e9cologiques"
    },
    "paused": false,
    "sender_id": "default",
    "slots": {
      "type": null,
      "who": null
    }
  }
}
```

**Comment by nabti** [comment]
I have the same Issue with french language any help, I looked to all other related issues bur nothing work for me

**Comment by akelad** [comment]
i'm quite certain we've since fixed this. let me know if you're still experiencing issues
