### ISSUE TITLE
What is a good way to handle single words from user input for Entity Extraction?

### ISSUE THREAD

**Issue by ctrado18** [RasaHQ/rasa_nlu#1057]
Since most user would write just single entities as input for the chatbot, how can those be recognized as entities? I would guess this happens very often and a chatbot should handle those occassions. How is this solved in practice? Would training the NER like CRF with just single words as examples work? My feeling is that in practice you use a phrase matcher. But in the form it exists right now this is not a good choice since it overwrites the NER entity and you wouldn't need any NER at all since you have all entities in a list which are recognized in every context. 
So you woud let run first the NER comonent and then you check if an entitiy is found - if not you run the phrase matcher. So you need a conditionally running of a component. Is that possible?

Any advices for this?

Thanks. :)

**Comment by wrathagom** [comment]
Have you tested the CRF for this? Do you have an example that you can't get to work?

**Comment by akelad** [comment]
yes you need to provide example sentences with just single words, i answered that question here #1010 before seeing this 😄 let me know if you need more explanation

**Comment by ctrado18** [comment]
@wrathagom So you mean if I would train the CRF wih sentences together with single words this will work?

Like ``How much is the fish?` together with just `fish` :)

**Comment by wrathagom** [comment]
that would be my suggestion, have you tried it yet?

**Comment by ctrado18** [comment]
i am on it right now.

**Comment by ctrado18** [comment]
I tried it now. It works actually for unknown words, but again for others and complicated words like `arbeitsshuhe`, in english `working shoes` it fails. 
Doesn't this correlate now again to how the CRF is working? CRF gets the word and postags as input. Is the word itself used as a vector representation? Or how does the CRF uses the word itself as a feature? When it comes as a vector, then this is a problem when this word is not inside the spacy model? I am really confused right now. 
What is the postag for a single word? I want to really know that because I use german model and need to knwo how this model influences my NLU. For sentences this might be not an issue for unknown german words in the spacy model beacuse CRF  uses also postags. And postags are still possible though the word  has no representation, right?

**Comment by AbdurRub** [comment]
I must give input there , I have tried with single word entity training , It disturbs intent classification as far I observed , whenever I enter one word other than domain then it detects the intent which is having more single word examples.

**Comment by wrathagom** [comment]
@ctrado18 the CRF is all about features of the word and the sentence around it, it doesn't use the spacy vectors at all. Did you train any examples that were two words separated by a space like `working shoes` as the structure of that is different from a single word with no spaces?

@AbdurRub have you tried only labeling the single word responses as entities, but not as intents? That way you can train the entity classifier without impacting intent?

**Comment by ctrado18** [comment]
@wrathagom working shoues is a single word in german. I trained some single words as entities. That were also trained in sentence. But as you said it nis ot suitable with CRF for single words. How do you handle then the case for a chatbot if user type just the name? I mean, that is a problem that everyone has and there should be a solution. Is CRF for your custom domain working so good? How many single words are you training?
 I found that CRF recognises jst single custom word if they were trained in couple of sentences before! Just adding unknown single words as text is not working good. Since CRF uses context this might be not a good idea at all unless you train all custom words?

**Comment by AbdurRub** [comment]
@wrathagom you mean new intent " " ?

**Comment by ctrado18** [comment]
What came in my mind is the following: use the phrase matcher but only if the message has length of just one token and conditionally check if CRF just find an entity. If all conditions are made then use phrase matcher? right now you can just use a component. But can apply this component conditionally such that CRF and phrase matcher entities are not mixed up?

**Comment by akelad** [comment]
you can use ner_duckling to extract numbers, and then you should store these numbers into seperate slots using a custom action
