### ISSUE TITLE
curl post parse Special character &

### ISSUE THREAD

**Issue by mylarr** [RasaHQ/rasa_nlu#1059]
**Rasa NLU version**:0.11.4

**Operating system** : Windows 7
**Used backend / pipeline **: spacy_sklearn
**what iam running**: curl -X POST "http://localhost:5000/parse" -d "{\"q\":\"Show me the average claims denied for NYU and Segment is M&R for Rolling 12 Months\"}" | python -m json.tool

**Issue**: Special character &

(base) C:\Users\vmyla1>curl -X POST "http://localhost:5000/parse" -H "Content-Ty
pe: application/json" -d "{\"q\":\"Show me the average claims denied for NYU and
 Segment is M\&R for Rolling 12 Months\"}" | python -m json.tool
<html><head><title>web.Server Traceback (most recent call last)</title></head><b
ody><b>web.Server Traceback (most recent call last):</b>

<div>
  <style type="text/css">
    div.error {
      color: red;
      font-family: Verdana, Arial, helvetica, sans-serif;
      font-weight: bold;
    }

    div {
      font-family: Verdana, Arial, helvetica, sans-serif;
    }

    div.stackTrace {
    }

    div.frame {
      padding: 1em;
      background: white;
      border-bottom: thin black dashed;
    }

    div.frame:first-child {
      padding: 1em;
      background: white;
      border-top: thin black dashed;
      border-bottom: thin black dashed;
    }

    div.location {
    }

    span.function {
      font-weight: bold;
      font-family: "Courier New", courier, monospace;
    }

    div.snippet {
      margin-bottom: 0.5em;
      margin-left: 1em;
      background: #FFFFDD;
    }

    div.snippetHighlightLine {
      color: red;
    }

    span.code {
      font-family: "Courier New", courier, monospace;
    }
  </style>

  <div class="error">
    <span>simplejson.errors.JSONDecodeError</span>: <span>Unterminated string st
arting at: line 1 column 6 (char 5)</span>
  </div>
  <div class="stackTrace">
    <div class="frame">
      <div class="location">
        <span>C:\Users\vmyla1\AppData\Local\Continuum\anaconda3\lib\site-package
s\twisted\internet\defer.py</span>:<span>1386</span> in
        <span class="function">_inlineCallbacks</span>
      </div>
      <div class="snippet">
        <div class="snippetLine">
          <span class="lineno">1385</span>
          <code class="code"> &#160; &#160; &#160; &#160; &#160; &#160;else:</co
de>
        </div><div class="snippetHighlightLine">
          <span class="lineno">1386</span>
          <code class="code"> &#160; &#160; &#160; &#160; &#160; &#160; &#160; &
#160;result = g.send(result)</code>
        </div><div class="snippetLine">
          <span class="lineno">1387</span>
          <code class="code"> &#160; &#160; &#160; &#160;except StopIteration as
 e:</code>
        </div>
      </div>
    </div><div class="frame">
      <div class="location">
        <span>C:\Users\vmyla1\AppData\Local\Continuum\anaconda3\lib\site-package
s\rasa_nlu\server.py</span>:<span>143</span> in
        <span class="function">parse_get</span>
      </div>
      <div class="snippet">
        <div class="snippetLine">
          <span class="lineno">142</span>
          <code class="code"> &#160; &#160; &#160; &#160; &#160; &#160;request_p
arams = simplejson.loads(</code>
        </div><div class="snippetHighlightLine">
          <span class="lineno">143</span>
          <code class="code"> &#160; &#160; &#160; &#160; &#160; &#160; &#160; &
#160; &#160; &#160;request.content.read().decode('utf-8', 'strict'))</code>
        </div><div class="snippetLine">
          <span class="lineno">144</span>
          <code class="code"></code>
        </div>
      </div>
    </div><div class="frame">
      <div class="location">
        <span>C:\Users\vmyla1\AppData\Local\Continuum\anaconda3\lib\site-package
s\simplejson\__init__.py</span>:<span>518</span> in
        <span class="function">loads</span>
      </div>
      <div class="snippet">
        <div class="snippetLine">
          <span class="lineno">517</span>
          <code class="code"> &#160; &#160; &#160; &#160; &#160; &#160;and not u
se_decimal and not kw):</code>
        </div><div class="snippetHighlightLine">
          <span class="lineno">518</span>
          <code class="code"> &#160; &#160; &#160; &#160;return _default_decoder
.decode(s)</code>
        </div><div class="snippetLine">
          <span class="lineno">519</span>
          <code class="code"> &#160; &#160;if cls is None:</code>
        </div>
      </div>
    </div><div class="frame">
      <div class="location">
        <span>C:\Users\vmyla1\AppData\Local\Continuum\anaconda3\lib\site-package
s\simplejson\decoder.py</span>:<span>370</span> in
        <span class="function">decode</span>
      </div>
      <div class="snippet">
        <div class="snippetLine">
          <span class="lineno">369</span>
          <code class="code"> &#160; &#160; &#160; &#160; &#160; &#160;s = s.dec
ode(self.encoding)</code>
        </div><div class="snippetHighlightLine">
          <span class="lineno">370</span>
          <code class="code"> &#160; &#160; &#160; &#160;obj, end = self.raw_dec
ode(s)</code>
        </div><div class="snippetLine">
          <span class="lineno">371</span>
          <code class="code"> &#160; &#160; &#160; &#160;end = _w(s, end).end()<
/code>
        </div>
      </div>
    </div><div class="frame">
      <div class="location">
        <span>C:\Users\vmyla1\AppData\Local\Continuum\anaconda3\lib\site-package
s\simplejson\decoder.py</span>:<span>400</span> in
        <span class="function">raw_decode</span>
      </div>
      <div class="snippet">
        <div class="snippetLine">
          <span class="lineno">399</span>
          <code class="code"> &#160; &#160; &#160; &#160; &#160; &#160; &#160; &
#160;idx += 3</code>
        </div><div class="snippetHighlightLine">
          <span class="lineno">400</span>
          <code class="code"> &#160; &#160; &#160; &#160;return self.scan_once(s
, idx=_w(s, idx).end())</code>
        </div><div class="snippetLine">
          <span class="lineno">401</span>
          <code class="code"></code>
        </div>
      </div>
    </div>
  </div>
  <div class="error">
    <span>simplejson.errors.JSONDecodeError</span>: <span>Unterminated string st
arting at: line 1 column 6 (char 5)</span>
  </div>
</div>

</body></html>
'R' is not recognized as an internal or external command,
operable program or batch file.

(base) C:\Users\vmyla1>

**Comment by wrathagom** [comment]
Have you tried:

```
curl -X POST "http://localhost:5000/parse" -d "{\"q\":\"Show me the average claims denied for NYU and Segment is M&R for Rolling 12 Months\"}" | python -m json.tool
```

I think you need to escape the inner quotes. According to the docs that is how you need to run the command. Can't verify as I am not a Windows user.

**Comment by wrathagom** [comment]
@mylarr any luck?

**Comment by mylarr** [comment]
@wrathagom : Thanks for reply . 

In M&R ,iam trying to escape & like this m\&R. However it is not working.

curl -X POST "http://localhost:5000/parse" -d "{\"q\":\"Show me the average claims denied for NYU and Segment is M\&R for Rolling 12 Months\"}" | python -m json.tool

**Comment by tmbo** [comment]
What is the error with that? I agree with @wrathagom, from the above error message, you are running into issues with `"` not with the ampersand.

**Comment by wrathagom** [comment]
Just to be clear I would imagine the below should work fine:

```
curl -X POST "http://localhost:5000/parse" -d "{\"q\":\"Show me the average claims denied for NYU and Segment is M&R for Rolling 12 Months\"}" | python -m json.tool
```

Closing, but let us know if the problem persists.
