### ISSUE TITLE
NLU training does not terminate

### ISSUE THREAD

**Issue by tkalfigo** [RasaHQ/rasa_nlu#1060]
**Rasa NLU version**: 0.12.0a1

**Operating system**: Ubuntu 16.04.4 

**Content of model configuration file**:
```json
{
    "fixed_model_name": "latest",
    "project": "foobar",
    "num_threads": 6,
    "pipeline": [
        "nlp_spacy",
        "tokenizer_spacy",
        "intent_entity_featurizer_regex",
        "intent_featurizer_spacy",
        "ner_crf",
        "ner_synonyms",
        "ner_duckling",
        "intent_classifier_sklearn"
    ],
    "duckling_dimensions": ["time", "duration", "amount-of-money"],
    "path": "models/",
    "data": "data/"
}
```

**Issue**: 
Execution of NLU training does not finish. 

```
/usr/bin/python -m rasa_nlu.train -c nlu_model_config.json
```

Spawns several python processes. CPU load is high initially but eventually drops to zero even though several python processes remain around. 

Screenshots:

   * nlu training output: https://i.imgur.com/ZEKfSV0.png
   * initial CPU activity of spawned python procs: https://i.imgur.com/zMGA2KA.png
   * left over python procs even though training does not terminate: https://i.imgur.com/SQDq4rX.png

**Comment by akelad** [comment]
can you try upgrading to 0.12.3 and see if this still happens?

**Comment by tkalfigo** [comment]
Upgraded to 0.12.3 and problem seems to no longer be there. Thank you.
