### ISSUE TITLE
server.py: error: the following arguments are required: --path

### ISSUE THREAD

**Issue by rajnishe** [RasaHQ/rasa_nlu#1061]
I pulled  "latest-full" from following  docker repo:
https://hub.docker.com/r/rasa/rasa_nlu/

Following is output of "docker images"
-------------------------------------------------
REPOSITORY                         TAG                
docker.io/rasa/rasa_nlu            latest-full    
-------------------------------------------------

**Operating system** (windows, osx, ...): Linux

**Issue**:
On executing following command :
docker run -p 5000:5000 rasa/rasa_nlu:latest-full start
**Error is as :**
usage: server.py [-h] [-e {wit,luis,dialogflow}] [-P PORT]
                 [--pre_load PRE_LOAD [PRE_LOAD ...]] [-t TOKEN] [-w WRITE]
                 --path PATH [--cors [CORS [CORS ...]]]
                 [--max_training_processes MAX_TRAINING_PROCESSES]
                 [--num_threads NUM_THREADS] [--response_log RESPONSE_LOG]
                 [--storage STORAGE] [-c CONFIG] [--debug] [-v]
server.py: error: the following arguments are required: --path

**Comment by wrathagom** [comment]
why are you specifying a custom command?

`docker run -p 5000:5000 rasa/rasa_nlu:latest-full` is all you need

**Comment by rajnishe** [comment]
thanks @wrathagom , no error when I remove "start".
But after that also docker image is not listed as running mode
**docker container ls -a** has following ouput
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS                       PORTS               NAMES
f92ee2812b7e        rasa/rasa_nlu:latest-full   "./entrypoint.sh s..."   9 seconds ago       Exited (132) 6 seconds ago                       thirsty_jennings
--------------------------------------------------------------
curl http://localhost:5000/status also not working 
any idea on this . thanks

**Comment by wrathagom** [comment]
I"m assuming you left the window open, didn't `Ctrl-C` or anything like that. I just pulled the image to make sure all was well and it worked for me. 

What was the console output while running mine is:

```
2018-05-02 12:23:41+0000 [-] Log opened.
2018-05-02 12:23:41+0000 [-] Site starting on 5000
2018-05-02 12:23:41+0000 [-] Starting factory <twisted.web.server.Site object at 0x7f4d06b8bd68>
2018-05-02 12:24:30+0000 [-] "172.17.0.1" - - [02/May/2018:12:24:30 +0000] "GET /status HTTP/1.1" 200 189 "-" "curl/7.52.1"
```

**Comment by wrathagom** [comment]
@rajnishe where you able to get it running?

**Comment by wrathagom** [comment]
@rajnishe closing, but feel free to open another issue/comment on this one if the issue persists.

**Comment by fabiordrig** [comment]
@wrathagom same problem with me https://imgur.com/a/bdAlXF4 look, rasa doesn't start, but another docker start on my ubuntu 18.04 LTS, can you help me?

**Comment by akelad** [comment]
please create a new issue :)
