### ISSUE TITLE
Tensorflow embedding in RASA NLU doubt

### ISSUE THREAD

**Issue by Griffintaur** [RasaHQ/rasa_nlu#1062]
What does tensor flow embedding actually do for the different language other than English?

when I run the cross-validation it only gives the train and test accuracy only for the intent classification and not for the entity extraction?

but while querying it gives the output for both the intent classification and entity extraction.

**Comment by akelad** [comment]
It does the same thing for all languages - i guess you're asking about word embeddings, they're trained from scratch.

Crossvalidation doesn't actually persist your model, so I assume you're loading up an old model. The tensorflow_embedding pipeline doesn't perform entity extraction in itself, you need to add an entity extraction module to the pipeline for that.

**Comment by Griffintaur** [comment]
Thanks @akelad

**Comment by wrathagom** [comment]
@Griffintaur please feel free to create another issue if you need more assistance. Sounds like this one can be closed.
