### ISSUE TITLE
trainer.train(training_data) > SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by keyloguer** [RasaHQ/rasa_nlu#1063]
**Rasa NLU version**:  0.12.3

**Operating system**: windows

**Content of model configuration file**:
```
from rasa_nlu.training_data import load_data
from rasa_nlu.config import RasaNLUModelConfig
from rasa_nlu.model import Trainer
from rasa_nlu.model import Metadata, Interpreter
from rasa_nlu import config

def train_nlu(model_dir):
    training_data = load_data('.\data\data.json')
    trainer = Trainer(RasaNLUConfig('config_spacy.yml')
    trainer.train(training_data)
    model_directory = trainer.persist(model_dir,fixed_name = "megaImagemBotNLU")
if __name__ == '__main__':
    train_nlu('.\models\\nlu')
```

**Issue**: I can't understand why this error ocurreded. Can anyone help me?

File "nlu_model.py", line 10

trainer.train(training_data)
-------^
SyntaxError: invalid syntax

**Comment by wrathagom** [comment]
You'r missing the second `)` on the `trainer = Trainer(RasaNLUConfig('config_spacy.yml')` line.

**Comment by wrathagom** [comment]
@keyloguer did the above help? I'll close this issue before too long unless I hear that your problem wasn't solved.

**Comment by wrathagom** [comment]
@keyloguer let us know if you're still struggling. Closing for now.
