### ISSUE TITLE
How to host Rasa on a server

### ISSUE THREAD

**Issue by rithwikjc** [RasaHQ/rasa_nlu#1067]
Hello,

I wanted to host the NLU model on a server (dreamhost) and I don't know how to go about it.

I want to host and run the NLU on the server so that I can send requests to the server with the user input and get the NLU output back from the server.

**Comment by wrathagom** [comment]
@rithwikjc in part 3 of my Rasa tutorial I walk through a basic (non-secure) cloud deployment. Maybe that can help get you started. 

https://blog.spg.ai/build-a-chatbot-was-rasa-nlu-part-3-b53c61954e86

But in general hosting on a cloud server is no different than installing and running locally. With the exception that you should be worried about security and access.

**Comment by wrathagom** [comment]
@rithwikjc closing, let us know if you need more assistance.

**Comment by rithwikjc** [comment]
I am trying to get it up and running. Your tutorial definitely helps. 
I will let you know if I run into more roadblocks. Thank you.
