### ISSUE TITLE
Drop python 2.7 support

### ISSUE THREAD

**Issue by tmbo** [RasaHQ/rasa_nlu#1068]
The remaining livetime of python 2.7 isn't that long anymore and supporting it takes more and more effort especially with respect to unicode and support for special characters in languages.

What are your thoughts, are you relying on python 2.7? If so, why is it you haven't switched to py3?

**Comment by wrathagom** [comment]
No objection here granted that being all Docker is a bit of a cheat.

**Comment by mandar1010** [comment]
Isn't python 2.7 required to run MITIE related configs?

**Comment by mvollrath** [comment]
Still writing 2/3 compatible and running 2.7 because ROS (1.0) requires it.  Porting to ROS 2 when it's mature enough, then we will run 3.

**Comment by akelad** [comment]
it's been dropped :D
