### ISSUE TITLE
Issue with Tensorflow Pipeline Multi Intent Feature

### ISSUE THREAD

**Issue by AbdurRub** [RasaHQ/rasa_nlu#1072]
**Rasa NLU version**: 0.12.3

**Operating system** (windows, osx, ...):  17.10

**Content of model configuration file**:
language: "en"

pipeline:
- name: "nlp_spacy"
  model: "en"
- name: "tokenizer_spacy"
- name: "ner_synonyms"
- name: "ner_crf"
  BILOU_flag: true
  features:
    - ["low","pos", "pos2"]
    - ["bias", "low", "word3", "word2","digit", "pos", "pos2", "pattern"]
    - ["low", "pos", "pos2"]
  max_iterations: 50
  L1_c: 1
  L2_c: 1e-3
- name: "intent_featurizer_count_vectors"
- name: "intent_classifier_tensorflow_embedding"
  intent_tokenization_flag: true
  intent_split_symbol: "_"

**Issue**:
Tensorflow is treating my multi intent thing as a separate intents. Why is this happening. Am I doing any mistake?

![multi intents](https://user-images.githubusercontent.com/29856813/39739447-56da38e6-52aa-11e8-9bb3-5bc9e5a985f2.png)

**Comment by AbdurRub** [comment]
Same happening with +

![multi](https://user-images.githubusercontent.com/29856813/39741589-f900d61c-52b3-11e8-8055-b0bae80e709d.png)

**Comment by amn41** [comment]
this looks correct, "sales+parts" is still a separate intent, but it can now share information with the "sales" and "parts" intents.

**Comment by AbdurRub** [comment]
Oh you mean. It will only detect those combination which we define with "+"  and will display them as separate intents.

**Comment by amn41** [comment]
that's right. The tf model is able to predict "sales+parts", "sales", and "parts" as separate intents, even if they are overlapping. The sklearn model would get confused by that

**Comment by AbdurRub** [comment]
Cool. Thanks

**Comment by Egalite123** [comment]
Is there any detailed example available for this? 
Going by the above example - do we need to train for all the intents (sales, parts and sales+parts) separately?

**Comment by AbdurRub** [comment]
Yes @Egalite123.
