### ISSUE TITLE
Support custom tokenizer in tensorflow_embedding pipeline

### ISSUE THREAD

**Issue by Jasmin25** [RasaHQ/rasa_nlu#1073]
For languages like Japanese, the tokenisation can not be done by spaces. Is it possible to plug another tokenizer (like [Janome](http://mocobeta.github.io/janome/en/)) so that we can use this pipeline for more languages?

**Comment by akelad** [comment]
You should be able to add a custom tokenizer to the pipeline, you just have to build a component for it in rasa nlu

**Comment by Jasmin25** [comment]
Can you please add more information or links to show me how do we add component (do you mean the config yml file?) and choose which tokenizer will be used in Rasa NLU?

**Comment by wrathagom** [comment]
You would need to add a custom python component and then also include it in your pipeline. For example, the current tensorflow pipeline uses this featurizer: https://github.com/RasaHQ/rasa_nlu/blob/master/rasa_nlu/featurizers/count_vectors_featurizer.py

Examples of other tokenizers can be found here: https://github.com/RasaHQ/rasa_nlu/tree/master/rasa_nlu/tokenizers

**Comment by howl-anderson** [comment]
@Jasmin25 Technologically, feature `text_features` is the only thing that `intent_classifier_tensorflow_embedding` needed. There are several components can provide `text_features`, you may interested in some of them:  `intent_featurizer_spacy`, `intent_featurizer_mitie`. `intent_featurizer_spacy` using built-in spacy tokenizer, it support Japanese language, but it seems currently no language model released. `intent_featurizer_mitie` using feature `tokens` which should provided by other component, as @wrathagom said, there are several other tokenizers, you can see if one of those tokenizers works for Japanese, I suggest you check if `tokenizer_spacy` works, as I said before, spacy support Japanese, it should working in version 2.1.0.*. if no one works, you have to build your own Japanese tokenizers.

**Comment by howl-anderson** [comment]
Update: `intent_featurizer_count_vectors` count on blank char to split words, but if feature `spacy_doc` is provided which generated by component `nlp_spacy`, It will regenerate text by re-combine token together with blank char among them. So, for those languages that it's tokenizer is supported by SpaCy it's safe to using `intent_featurizer_count_vectors` after `nlp_spacy` component.

**Comment by amn41** [comment]
we use scikit-learn's counting featurizer, and I think you can pass a custom tokenizer to it: http://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html (check the tokenizer argument)

**Comment by howl-anderson** [comment]
Update: #1115 try to fix this issue. @Jasmin25

**Comment by howl-anderson** [comment]
Update: #1115 already merged into master branch. @Jasmin25
