### ISSUE TITLE
Rasa-core is not generate logs.

### ISSUE THREAD

**Issue by nileshgarg** [RasaHQ/rasa_nlu#1075]
**Rasa NLU version**: Master branch

**Operating system** (windows, osx, ...): windows 10 64 bit

**Content of model configuration file**:
```yml

```

**Issue**:
what are the settings I have to do to get chat and other logs

**Comment by akelad** [comment]
There's a parameter here: https://github.com/RasaHQ/rasa_core/blob/master/rasa_core/run.py#L45 where you can store logs.

**Comment by nileshgarg** [comment]
Where exactly I should be adding these parameter ?
while running the code from commandline : i.e. 
python server.py -o --abc.log

or this should be added in config.yml file. I have following entries in it:
language: "en"
response_log: "logs/"
log_level: "INFO"
log_file: "/logs"

**Comment by nileshgarg** [comment]
I am using custom webhook code to run my code .. mentioned in one of the issues.

**Comment by nileshgarg** [comment]
I have to run my script like 
python server.py 

is there any workaround ?

**Comment by akelad** [comment]
I'm not sure what your code in `server.py` is but this is where the response_log arg is called: https://github.com/RasaHQ/rasa_nlu/blob/master/rasa_nlu/server.py#L380

**Comment by nileshgarg** [comment]
This is my code...
def run(serve_forever=True):
    logger.debug("testing logs")
    #http api endpoint for responses
    #input_channel = WebhookInputChannel("localhost")    # enable debug mode for underlying fb library)
    input_channel = SimpleWebBot()
    #path to your NLU model
    interpreter = RasaNLUInterpreter("models/nlu/default/current")
    # path to your dialogues models
    agent = Agent.load("models/dialogue", interpreter=interpreter)
    
    if serve_forever:
        agent.handle_channel(HttpInputChannel(5004, "/chat", input_channel))       
    return agent


if __name__ == '__main__':
    utils.configure_colored_logging(loglevel="INFO")
    logging.basicConfig(level="INFO")   
    run()

**Comment by akelad** [comment]
you can add some code similar to _configure_logging in the `server.py` script in rasa_core https://github.com/RasaHQ/rasa_core/blob/master/rasa_core/server.py#L71

**Comment by wrathagom** [comment]
@nileshgarg let us know if you still have more questions or join in on the Rasa Core as well.
