### ISSUE TITLE
NER Synonyms not working properly?

### ISSUE THREAD

**Issue by ctrado18** [RasaHQ/rasa_nlu#1079]
**Rasa NLU version**: 12.2

**Operating system** (windows, osx, ...):

**Content of model configuration file**:
```language: "de_core_news_sm"

pipeline:
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "intent_featurizer_spacy"
- name: "ner_crf"
  BILOU_flag: false
  features:
    # features for word before token
    - ["low", "title", "upper", "pos", "pos2"]
    # features of token itself
    - ["bias", "low", "word3", "word2", "upper", "title", "digit", "pos", "pos2", "pattern"]
    # features for word after the token we want to tag
    - ["low", "title", "upper", "pos", "pos2"]
  max_iterations: 50
  L1_c: 1
  L2_c: 1e-3
- name: "intent_classifier_sklearn"
  C: [1, 2, 5, 10, 20, 100]
  kernel: "linear"
- name: "ner_synonyms"
- name: "intent_classifier_sklearn"

```

**Issue**:

I have the issue that my entity is recognized properly, but ths value is not replaced with the synonym afterwards! I trained sentences with this entity with the original value and not the synonym. In `entity_synonyms` I mapped this value to its synonym. Is this influencing each other when you not directly map the value of the synonym in the training sentences?

**Comment by wrathagom** [comment]
Can you provide your training data (at least the synonym piece of it) and the parse request/response?

**Comment by ctrado18** [comment]
It is not possible and it is german. But I think I can describe what exactly happens:

I trained sentences with an original entity value. Then I put a synonym for this value. My NLU detects the entiy but with the value typed as in the input text (which is the original value). Though NLU didn't mapped it to the synonym!

**Comment by ctrado18** [comment]
I found the reason:

`UserWarning: Found conflicting synonym definitions for 'value'. Overwriting target 'synonym' with 'heilpvaluelan'. Check your training data and remove conflicting synonym definitions to prevent this from happening.`

**Comment by akelad** [comment]
Ah yes that looks like it! It might be easiest to just have a list of synonyms in your file rather than adding the synonym value to each training example. Easier to avoid mistakes like that. I'll close this issue for now anyways, let us know if you encounter any other problems though.
