### ISSUE TITLE
No module named converters

### ISSUE THREAD

**Issue by badasshumor** [RasaHQ/rasa_nlu#1080]
**Rasa NLU version**:
0.12.3

**Operating system** (windows, osx, ...):
Windows

**Content of model configuration file**:
```yml

```

**Issue**:
I am running the following code buut it is showing the no module found error, although i have updated the rasa_nlu module

from rasa_nlu.converters import load_data
from rasa_nlu.config import RasaNLUConfig
from rasa_nlu.model import Trainer

**ERROR:**

Traceback (most recent call last):
  File "chatbot.py", line 1, in <module>
    from rasa_nlu.converters import load_data
ImportError: No module named converters

**Comment by stacybot123** [comment]
Change this line : 

from rasa_nlu.converters import load_data

To 

from rasa_nlu.training_data import load_data

This worked for me.

**Comment by wrathagom** [comment]
Yeah since you are running 0.12.3 make sure you are looking at the docs that correlate with that version: https://nlu.rasa.com/python.html

**Comment by badasshumor** [comment]
ImportError                               Traceback (most recent call last)
<ipython-input-6-c38ad7755948> in <module>()
      1 # Import necessary modules
      2 from rasa_nlu.training_data import load_data
----> 3 from rasa_nlu.config import RasaNLUConfig
      4 from rasa_nlu.model import Trainer
      5 

ImportError: cannot import name RasaNLUConfig

**Comment by akelad** [comment]
yes this has changed to RasaNLUModelConfig in the latest version

**Comment by badasshumor** [comment]
Thanks a lot for the help. It worked. Closing

**Comment by Brijeshlakkad** [comment]
I have upgraded to version 11.5 and problem solved:

pip install rasa-nlu==0.11.5

**Comment by lohitk27** [comment]
> yes this has changed to RasaNLUModelConfig in the latest version

Thanks @akelad  for support
