### ISSUE TITLE
Can not extract any words for entity

### ISSUE THREAD

**Issue by linanzhu** [RasaHQ/rasa_nlu#1088]
**Rasa NLU version**: 0.12.2
**Operating system** (windows, osx, ...): Ubuntu 16.04
**Content of model configuration file**:
```
language: "en"

pipeline:
# this is using the spacy sklearn pipeline, adding duckling
# all components will use their default values
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "intent_featurizer_spacy"
- name: "ner_crf"
- name: "ner_synonyms"
- name: "intent_classifier_sklearn"
- name: "ner_duckling"
```

**Traingset JSON**:
```
     .......
     ....... 
     {
        "text": "what is potato",
        "intent": "get_knowledge",
        "entities": [
          {
            "start": 8,
            "end": 14,
            "value": "potato",
            "entity": "object_to_know"
          }
        ]
      },
      {
        "text": "tell me what is computer",
        "intent": "get_knowledge",
        "entities": [
          {
            "start": 16,
            "end": 24,
            "value": "computer",
            "entity": "object_to_know"
          }
        ]
      },
     .......
     .......
```
**Issue**:
Using RASA NLU & Core,  when I ask "what is computer", then NLU will extract entity "computer". And my custom action will query to wikipedia about "computer".  And will give me back the definition of word. Actually it works. But not every words.  
"what is a computer"  -->  extract "computer"
"what is a potato" -->  can not extract
"what is locker"  -->  extract "locker"
"what is lion"   --> can not extract

When I install spacy,  I followed this...
```
pip install rasa_nlu[spacy]
python -m spacy download en_core_web_md
python -m spacy link en_core_web_md en
```
How can I resolve this?

**Comment by auzair92** [comment]
Does it recognize the intent correctly? It might simply be an issue of adding more training phrases. You may try [Chatito](https://rodrigopivi.github.io/Chatito/) to generate a dataset with large number of training examples using placeholders.

**Comment by linanzhu** [comment]
@auzair92  Yes. it recognize intent correctly. But can't extract entity sometime, some words.

**Comment by akelad** [comment]
yeah my guess is also that you don't have enough training data yet. how many examples do you have of intents/entities?
