### ISSUE TITLE
Model is not generating after i updated rasa nlu to 0.12

### ISSUE THREAD

**Issue by ashwinbiyani** [RasaHQ/rasa_nlu#1089]
**Rasa NLU version**: 0.12

**Operating system** (windows, osx, ...): Windows

**Content of model configuration file**:
```yml
{
  "pipeline": "spacy_sklearn",
  "path" : "./models",
  "project": "nlu",
  "data" : "./data/MAYA_Original/"
}

```

**Issue**:
Model is not generating after i updated rasa nlu to 0.12. Here are the commands i ran
train:
(base) E:\projects\rasa\rasa_core-master\examples\remotebot>python -m rasa_nlu.train -c nlu_model_config.json -d data\MAYA_Original
http server:
python -m rasa_nlu.server -e dialogflow -c nlu_model_config.json --path ./models

Observed: models folder is empty and no logs generated in the logs folder.

**Comment by auzair92** [comment]
Have you updated your configuration file according to the new format according to instructions mentioned [here](https://nlu.rasa.com/0.12.3/tutorial.html)?

**Comment by ashwinbiyani** [comment]
followed the steps. it's working now. thanks very much. is nlu 0.12 enough to be sure that it using latest word vector enhancements(StarSpace)?

**Comment by auzair92** [comment]
@ashwinbiyani I haven't looked into it in detail, but I think you'll have to add the `intent_classifier_tensorflow_embedding` pipeline in the configuration for using StarSpace algorithm enhancement. You can find more help on this in the documentation [here](https://nlu.rasa.com/pipeline.html#intent-classifier-tensorflow-embedding), with all the parameters that you can adjust.

**Comment by Graziella-Husson** [comment]
Is there a method to know which parameter we have to adjust and how, according to our dataset and purpose? I find neural network parameters quite hard to understand and manipulate :(

**Comment by wrathagom** [comment]
Does it not work with the default parameters? I could see training custom embedding to take more data than spacy would with pre-trained ones. Do you have enough training data?

**Comment by Graziella-Husson** [comment]
Actually it worked with default parameters but with the same dataset tensorflow seems to be less effective than spacy. I thought it was due to default parameters but you're saying that tensorflow would need more training data to be as efficient as spacy? (f1 score)
Or changing parameters is still a way to improve model performance?

**Comment by wrathagom** [comment]
I'm sure changing parameters can help - if you know how to use them - but in general, the easiest way to get better performance is just more training data.

**Comment by Graziella-Husson** [comment]
That's the hard part - knowing how to use them -, but thanks for your response!

**Comment by wrathagom** [comment]
@amn41 What do you think about a blog post from one of "you" brainiacs on situations that may require tweaking of the different parameters and how to use them?

**Comment by akelad** [comment]
So I'm not sure whether you guys have read the docs about the parameters yet?
https://nlu.rasa.com/pipeline.html?highlight=tensorflow#intent-featurizer-count-vectors
https://nlu.rasa.com/pipeline.html?highlight=tensorflow#intent-classifier-tensorflow-embedding

I'm just wondering if those make it any clearer for you what to tweak? I guess some knowledge of ML makes it a lot easier to understand. I'll def bring up the blog post idea to the team though @wrathagom
