### ISSUE TITLE
AttributeError: 'str' object has no attribute 'load'

### ISSUE THREAD

**Issue by nahidalam** [RasaHQ/rasa_nlu#1093]
**Rasa NLU version**:0.12.3

**Operating system** (windows, osx, ...): OSx

**Content of model configuration file**:
```yml
language: "en"

pipeline: "spacy_sklearn"

```

**Issue**:

I am using below code to train the model

```
from rasa_nlu.training_data import load_data
from rasa_nlu.config import RasaNLUModelConfig
from rasa_nlu.model import Trainer
from rasa_nlu import config
from rasa_nlu.model import Metadata, Interpreter

def train_nlu(data, config, model_dir):
	training_data = load_data(data)
	trainer = Trainer(config.load("./config_spacy.yml"))
	trainer.train(training_data)
	model_directory = trainer.persist(model_dir, fixed_model_name = 'customernlu')
if __name__ == '__main__':
	train_nlu('./data/data.json', 'config_spacy.yml', './models/nlu')
```

When I run this, I am getting error

```
trainer = Trainer(config.load("./config_spacy.yml"))
AttributeError: 'str' object has no attribute 'load'
```

**Comment by rithwikjc** [comment]
It's a simple coding mistake. 
`config` is a module imported from `rasa_nlu`. Hence the keyword shouldn't be used for variable names.
In you function `train_nlu` you have used `config` variable to store a string. Hence within the function it points to a string not `rasa_nlu.config`.
