### ISSUE TITLE
How to use Persian language (not supported) with Rasa?

### ISSUE THREAD

**Issue by reza-ebrahimi** [RasaHQ/rasa_nlu#1094]
Persian is not officially supported language by Rasa NLU and I cannot find any documentation that present usage of unsupported languages.

**Comment by Shehzad777** [comment]
https://nlu.rasa.com/languages.html

Rasa NLU supports a number of different languages. Exactly which ones depends on the backend you are using, and the features you require.

Firstly, the tensorflow_embedding pipeline in principle supports any language, but only performs intent classification. In addition, with the spaCy backend you can now load fastText vectors, which are available for hundreds of languages.
Persian is listed here: https://github.com/facebookresearch/fastText/blob/master/pretrained-vectors.md

**Comment by akelad** [comment]
You can use fastText, or you can use the tensorflow_embedding pipeline https://nlu.rasa.com/pipeline.html#tensorflow-embedding

**Comment by reza-ebrahimi** [comment]
@akelad For using `fastText` we should add `spacy` to pipeline which does not support `NER` component for `Persian`, Based on merged PR #1095 both `intent classification` and `NER` supported with `tensorflow-embedding` pipeline, that was great!

We also need to use pre-trained models like `fastText` in NLP side, is it possible to load it with `tensorflow-embedding` pipeline?

**Comment by reza-ebrahimi** [comment]
@akelad For using `fastText` we should add `spacy` to pipeline which does not support `NER` component for `Persian`, Based on merged PR #1095 both `intent classification` and `NER` supported with `tensorflow-embedding` pipeline, that was great!

We also need to use pre-trained models like `fastText` in NLU side, is it possible to load it with `tensorflow-embedding` pipeline?

**Comment by akelad** [comment]
You don't need pre-trained models with the tensorflow embedding pipeline. You can train purely on your training data. 
So loading pre-trained models with the tensorflow embedding pipeline is currenlty not supported
