### ISSUE TITLE
How to use hierarchical intents with tensorflow pipeline

### ISSUE THREAD

**Issue by rithwikjc** [RasaHQ/rasa_nlu#1096]
**Rasa NLU version**:  0.12.3
**Operating system** (windows, osx, ...): Windows

**Issue**:
I read the blog by Alan and am planning to use hierarchical intents. How do you make use of the hierarchical intents using the tensorflow pipeline?
I understand the flags to be provided. But I am asking how to practically implement it. What kind of training data does one have to provide?
Like, should it include examples of each `intent1`, `intent2`, and `intent1+intent2`?

**Comment by amn41** [comment]
yes, that's exactly right. though you can take a first guess by inventing examples for `intent1+intent2`, this should really come from users. I would only add these multi-intents if they actually happen.

**Comment by rithwikjc** [comment]
All right. Thanks.
So does that mean adding examples by just joining together examples of `intent1` and `intent2` and putting them under `intent1+intent2` isn't really useful? (or maybe should not be done?)

So what exactly happens in the `tensorflow` pipeline training?. The `tensorflow` pipeline splits the `intent1+intent2` into tokens and trains the examples for `intent1+intent2` using both the obtained tokens and also using at the examples provided separately for `intent1` and `intent2`?
And how is this different from training using examples for `intent1`, `intent2` and `intent1+intent2` in the `spacy_sklearn` pipeline?

**Comment by rithwikjc** [comment]
Okay. That made it a bit more clear.
One more question.
Suppose I have a use case and I'm using the `tensorflow`pipeline for `intent1+intent2`. What if I cannot have examples for `intent1` alone? Is it still useful to use this?
Like in the example in Alan's blog, there is a hierarchical intent, `question+product+warranty`, there wont be any examples with just the intent `question` right? There could be `question+product` and `question+warranty`. But not a `question` intent, I think.?

**Comment by amn41** [comment]
@RAJAT--PALIWAL - have you looked at this already? https://blog.rasa.com/how-to-handle-multiple-intents-per-input-using-rasa-nlu-tensorflow-pipeline/

**Comment by RAJAT--PALIWAL** [comment]
@amn41 I went through the blog. It explains how to get multiple intents as response and I went through tutorial too.
I was interested in your blog on medium(https://medium.com/rasa-blog/supervised-word-vectors-from-scratch-in-rasa-nlu-6daf794efcd8 ); where you wrote, " **you can train a model that knows that some intents are more similar than others**." How does this happen?
**So, if I give similar text during training for two different intents. When testing both of them will have similar ranking or something entirely different will happen.**
