### ISSUE TITLE
RASA chat flow diagram is correct but not behaving accordingly

### ISSUE THREAD

**Issue by nelashj** [RasaHQ/rasa_nlu#1099]
I have created rasa flow diagram and its as expected but when I integrate it with my chat box, it show any random flow.

I am using RASA with http server where my action text is fetched from DB.

Any Idea what could be the possible reason for this.

I am running it with below commands:-

1. python -m rasa_nlu.train -c nlu_model_config.json --fixed_model_name current 
2. python -m rasa_core.train -s data/stories.md -d domain.yml -o models/dialogue --epochs 5000 
3. python -m rasa_core.server -d models/dialogue -u models/nlu/default/current --port 5999

**Comment by akelad** [comment]
can I ask what version of rasa_core you're using? Also can you share your story files?

**Comment by nelashj** [comment]
I am using Rasa core version 0.8.5.

Here is my stories files
[stories11.txt](https://github.com/RasaHQ/rasa_nlu/files/2038150/stories11.txt)

**Comment by akelad** [comment]
your stories file looks fine to me. My best guess is your nlu model isn't identifying the intents correctly? try running rasa_core in debug mode and see whether that's the case

**Comment by nelashj** [comment]
I tried as suggested by you but I am gettign some user warning like below:-

_**/home/ops/anaconda2/lib/python2.7/site-packages/rasa_nlu/extractors/entity_synonyms.py:113: UserWarning: Found conflicting synonym definitions for u'how_t'. Overwriting target 'manual_repair' with 'how_to_correct_the_validation_error_counter_or_organizational_bp_role_does_not_exist_for_the_counter_bic'. Check your training data and remove conflicting synonym definitions to prevent this from happening.**_

Could you please guide on it.

**Comment by akelad** [comment]
this might mean your entities aren't single words. But you can usually ignore that warning. Though, why is does your sentence not contain spaces, and instead "_" as a seperator: 'i_cant_understand_why_a_business_would_go_into__to_be_repair_status'?

**Comment by nelashj** [comment]
I used _ to make to more unique as i have multiple options with similar words. 

I am not sure why but I am not getting expected output. I am training data with json format. I have multiple entities having diff value for diff user text but its not working...

**Comment by akelad** [comment]
Ok but this is going to make nlu training fail, you need to have proper sentences in your training data. A user is never going to talk to your bot with a sentence like that. Also can you please describe your exact issue of what is not working?

**Comment by nelashj** [comment]
We are currently not giving user an option to type but it will be mostly flow based where user will only select from the options available. It will have something like button kind of thing which user have to click and at the backend we are handling this _ cases.

Whats is not working is like I have multiple flows defined in stories.md, but it will reply random from any flow. Like I am expecting data from flow 1 based on intent, but it will reply from flow 3 or 4 or 5 where even that intent is not applicable. Also When i try to draw a flow diagram, its very much as expected.

 I can upload my project if you can give me some option as it will be bit unseccured uploading whole project here.

**Comment by ashukrishna100** [comment]
I have provided a detailed solution.
Kindly check.

https://forum.rasa.com/t/solved-predicted-action-not-following-the-story/3364
