### ISSUE TITLE
How to populate / catch an entity value from a one word message? 

### ISSUE THREAD

**Issue by Shehzad777** [RasaHQ/rasa_nlu#1103]
**Rasa NLU version**:
0.12.3

**Operating system** (windows, osx, ...):
Closed Container Env (Docker) on top of Ubuntu 18.04

**Content of model configuration file**:
```
* not sure if that's needed. I can provide it if asked for.
```
**Issue**:

So imagine i have a template that asks for seat reservation,

Template # 1: "How many people would be visiting?"
Response: "12"

Then, in a second example, the customer needs to book a room,

Template # 2: "For how many days, do you intend to stay?"
Response: "2"

In both the responses, we only have a number, first,

How to get this one word data (i.e. "12", or "2" in the above examples) into an entity to be later stored in a slot? and also to make sure that both the responses are caught in different entities.?

I would highly appreciate a response. Thanks.

**Comment by Shehzad777** [comment]
@akelad any particular reason why this issue was closed??

**Comment by akelad** [comment]
you posted the exact same question on another issue, which I already answered there #1057

**Comment by Shehzad777** [comment]
Thanks
