### ISSUE TITLE
Once an entity is not found, the subsequent request are responded with the last entity found

### ISSUE THREAD

**Issue by prohan86** [RasaHQ/rasa_nlu#1104]
**Version** 0.12.3
**Operating system** (windows, osx, ...): Windows

**Issue**:
Hi All,

I tried to extend the Restaurant Bot example by adding my own intents and entities. 
I am observing that if Bot is unable to extract the entities, it is uttering the last extracted entity and is not updating the entity after that even if a question it is known to extract correctly is posted.

Could you please help me understand the reason for this and if I need to hack the code in any file.

Thanks in advance.

**Comment by akelad** [comment]
Could you provide some more details of your problem? e.g. the data you added, or an example conversation

**Comment by prohan86** [comment]
Hi,

I added approximately 100 examples containing only 1 intent. The Bot is supposed to extact 4 kinds of entities.

For testing purpose, if I input a random sentence which does not convey the intent and also no entities, i think it is going into a bad state and returning the same entity even if a proper sentence is given as an input after going into the bad state.

Is there any place where i need to set the slots as NULL after I am done with a dialog?

**Comment by prohan86** [comment]
Hi,

We have over come the problem with tracker.update(slotset).

Thanks.
