### ISSUE TITLE
Training fails midway for large training sets

### ISSUE THREAD

**Issue by manaschaturvedi** [RasaHQ/rasa_nlu#1105]
**Rasa NLU version**: 0.11.4

**Operating system**: Ubuntu 14.04

**Content of model configuration file**:
```
{
  "pipeline": "spacy_sklearn",
  "path" : "models/",
  "data" : "data_new/training_data_order_model.json",
  "emulate" : "luis",
  "num_threads":5
}

```
**Issue**:
 I've been trying to train a model on my 16 GB Ubuntu server with the following numbers:
- intent examples: 446289 (2 distinct intents)
- entity examples: 446289 (5 distinct entities)

However, the training process fails midway with the following traceback:

> INFO:rasa_nlu.model:Starting to train component nlp_spacy
> INFO:rasa_nlu.model:Finished training component.
> INFO:rasa_nlu.model:Starting to train component tokenizer_spacy
> INFO:rasa_nlu.model:Finished training component.
> INFO:rasa_nlu.model:Starting to train component intent_featurizer_spacy
> INFO:rasa_nlu.model:Finished training component.
> INFO:rasa_nlu.model:Starting to train component intent_entity_featurizer_regex
> INFO:rasa_nlu.model:Finished training component.
> INFO:rasa_nlu.model:Starting to train component ner_crf
> Killed

When the training set is comparatively smaller in size, the model gets trained without any issues.

My guess is that the training fails because the training process for larger training sets requires more RAM than what my current server settings can allocate (using `top` while training verifies that the process gradually ends up taking more and more RAM, eventually reaching full usage).

My question is, what is the ideal server configuration that could support training of a Rasa NLU model for a large training dataset? What kind of server configurations do people usually use for training scalable chatbot trained models in production?

**Comment by akelad** [comment]
Well the easiest thing is to increase the memory of your server
