### ISSUE TITLE
RASA NLU sample configuration file

### ISSUE THREAD

**Issue by harirehm** [RasaHQ/rasa_nlu#1108]
**Rasa NLU version**: 0.12.3

**Operating system** (windows, osx, ...): Linux RedHat 7.5 (ec2-user instance @AWS)

Can someone give us the sample configuration for RASA NLU 0.12.3?

We have used RASA NLU. Not sure about the version. (might be 0.10.x). Now, it is upgraded to 0.12.3.

Below is the configuration file that we currently have. We want it to be migrated for v 0.12.3

`
#config_spacy.json
{
  "pipeline": "spacy_sklearn",
  "path" : "./models",
  "data" : "./data/examples/rasa/bot-intents.json",
  "server_model_dirs": {
    "default" : "./model_default2/",
    "main-intents" : "./model_main/",
    "ineff" : "./model_ineff/",
    "intro" : "./model_intro",
    "intro2": "./model_intro2",
    "bot" : "./model_bot"
   }
}
`

When I run `sudo python -m rasa_nlu.train -c config_spacy.json`, it states `error: one of the arguments -d/--data -u/--url is required
`.
I also found out the configuration file of current RASA version is in yml format. And I can't find a sample configuration file with the details. Would be great if you can redirect me to a page where it contains the necessary details of the config file.

**Comment by Ghostvv** [comment]
Please take a look at the docs:
- https://nlu.rasa.com/config.html for configuration description;
- https://nlu.rasa.com/dataformat.html#train-a-model for description of the training parameters,

**Comment by harirehm** [comment]
And what about the `"server_model_dirs"`, where we will have the mapping of the model name and its location?

**Comment by harirehm** [comment]
According to the server configurations [here](https://nlu.rasa.com/http.html#server-parameters) (at the bottom of the page), we have to give the location of the models in `path`. But when I do so, and run the command, it is again stating that `--path is required`.

Eventhough, I have the **path** specified inside the configuration file, it is not picking it up!

**Comment by Ghostvv** [comment]
You should specify a path to your data, when you call `python -m rasa_nlu.train`. `path` is not read from config file.

**Comment by harirehm** [comment]
So, is it the change that's made with the update? Previously, we were specifying the path in the config file and it worked well.

And the same goes with specifying the location of the data file while training as well.

**Comment by Ghostvv** [comment]
yes, it was changed

**Comment by harirehm** [comment]
Alright! One last question.

What about the `-c CONFIG, --config CONFIG` in [https://nlu.rasa.com/dataformat.html#train-a-model](https://nlu.rasa.com/dataformat.html#train-a-model)?
I need the format of that RASA NLU configuration file & the list of stuffs that can be specified in that configuration file.

**Comment by Ghostvv** [comment]
Here is the description of what you can put into config file: https://nlu.rasa.com/pipeline.html

**Comment by harirehm** [comment]
Man! There seems to be a lot of changes. How would I parse different models??

I have 6 models trained, and those 6 are mapped with 6 different model names in the configuration file. But, whatever I query, it is only using one of the model (which is the one that is trained at last).

Below is the configuration file.

> {
  "pipeline": "spacy_sklearn",
  "path" : "./models",
  "data" : "./data/examples/rasa/bot-intents.json",
  "server_model_dirs": {
    "default" : "./model_20180525-070626/",
    "main-intents" : "./ model_20180525-071145/",
    "ineff" : "./model_20180525-071251/",
    "intro" : "./model_20180525-071340",
    "intro2": "./model_20180525-071425",
    "bot" : "./model_20180525-071511"
   }
}

Below is the response from `/status`

> {
  "available_projects": {
    "default": {
      "status": "ready",
      "available_models": [
        "model_20180525-071425",
        "model_20180525-071251",
        "model_20180525-071145",
        "model_20180525-071340",
        "model_20180525-071511",
        "model_20180525-070626"
      ],
      "loaded_models": [
        "model_20180525-071511"
      ]
    }}}

Below is my curl command

> curl -XPOST localhost:5000/parse -d '{"q":"I am interested in knowing more about the bot","model":"main-intents"
}'


Why is only one model loaded? Whatever model name I give while querying, it only goes for `model_20180525-071511`, which is the only loaded model (I could see that with the results of the query). If `server_model_dirs` is not allowed inside configuration file, then where & how would I have the mapping?

**Note:** I am not specifying project anywhere. As I have only one project, I don't mind it creating a default project for me. And I've also tried `--pre_load all` while bringing up the server. Nothing helped.

**Comment by akelad** [comment]
Please refer to the documentation of all changes here (i guess both 0.10 to 0.11 and 0.11 to 0.12 is relevant for you):
https://nlu.rasa.com/changelog.html#id9
https://nlu.rasa.com/migrations.html#x-to-0-12-0

There are also links in there to the server parameters: 
https://nlu.rasa.com/http.html#server-parameters

Also the config file you just posted is the old one, so i'm not sure how you're using version 0.12 with that?

**Comment by reza-ebrahimi** [comment]
@akelad What is the difference between spacy train and rasa_nlu train? I know rasa_nlu is high level API that wraps libraries like spacy, but I'm not understand what is the difference, its because rasa_nlu got additional options to train like input data, how it can feed that data format to spacy to tell it train such data? if it can be passed to spacy, it means it can be independently pass to spacy with python -m spacy train command! am I wrong?
