### ISSUE TITLE
entity prediction

### ISSUE THREAD

**Issue by avinexus7** [RasaHQ/rasa_nlu#1109]
**0.12.3**:

Currently the entity prediction works on the position and the length of the words which is alright for a limited set of words that the nlu has to identify. 

But in a scenario where we are trying to identify a word which has not been trained yet (like a new name of a product) or which does not have the same length of the trained entities, it becomes time consuming to re train all the existing utterances with the new word. In addition to this, in a system where the bot has to identify new words which are being added regularly, training the model for each new word becomes unproductive.

A feature where one can add a list of words which become the domain specific for that particular entity would be super useful so that the nlu can directly access that list and if available and assign the value to the entity (like phrase list in LUIS)

**Comment by AbdurRub** [comment]
Duplicates  https://github.com/RasaHQ/rasa_nlu/pull/822
