### ISSUE TITLE
Bahasa

### ISSUE THREAD

**Issue by Primtek** [RasaHQ/rasa_nlu#1112]
**Rasa NLU version**:

**Operating system** (windows, osx, ...):

**Content of model configuration file**:
```yml

```

**Issue**:

Any body already implement rasa_nlu in Bahasa?
I didnot find any article or ref that saying bahasa is supported. 
Need info
Thanks

**Comment by souvikg10** [comment]
There are few ways, you can support a custom language as such.

1. Use Tensorflow pipeline and create word vectors from scratch refer to this post from Alan this might be useful
https://medium.com/rasa-blog/supervised-word-vectors-from-scratch-in-rasa-nlu-6daf794efcd8 

I tried the same with a non-latin language using latin characters, Results were good for me but was just an experiment.
https://medium.com/@souvikghosh_14630/building-a-rasa-chatbot-in-bengali-using-supervised-word-vectors-from-scratch-740ebede51ee

2. You can also use FastText from Facebook that has support for over 170 languages #869 , follow this thread to see how you can add FastText to Spacy's language model and then use it with Rasa's Spacy pipeline.

3. If you have raw language data, you can also train your vectors with SpaCy and then incorporate same as above.
https://spacy.io/usage/training#section-basics

**Comment by saqibahmed515** [comment]
Just to add in the above comment, there's also [this](https://github.com/RasaHQ/rasa_nlu/pull/1095) PR which, when gets merged, will give language agnostic NER too (intent classification is also there with tensorflow embedding). So you can use the following pipeline for intents and entity recognition for any language:

```
pipeline:
- name: "tokenizer_whitespace"
- name: "ner_crf"
- name: "intent_featurizer_count_vectors"
- name: "intent_classifier_tensorflow_embedding"
``` 

You can also try it before it gets merged. The code is in the [lean-CRF](https://github.com/RasaHQ/rasa_nlu/tree/lean-CRF) branch.

**Comment by Primtek** [comment]
thanks everyone! .. will try
