### ISSUE TITLE
How to get Entity Recognition with Tensorflow pipeline

### ISSUE THREAD

**Issue by SaiPoojithaDubba** [RasaHQ/rasa_nlu#1117]
I am using recent rasa-nlu version on windows system.When I am using tensorflow embeddings pipeline only intents are being extracted how to extract entities using this pipeline? I have attached the configuration file below which I used .Thanks in advance.

 

**Rasa NLU version**:

**Operating system** (windows, osx, ...):

**Content of model configuration file**:
```yml

```

**Issue**:

[config_embeddings.txt](https://github.com/RasaHQ/rasa_nlu/files/2046988/config_embeddings.txt)

**Comment by wrathagom** [comment]
@SaiPoojithaDubba You will either need to add in the [spacy pipeline components](https://nlu.rasa.com/pipeline.html#spacy-sklearn) to your pipeline or wait for this PR https://github.com/RasaHQ/rasa_nlu/pull/1095.

If you go the spacy route your pipeline could look something like this:
```
language: "en"

pipeline:
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "intent_entity_featurizer_regex"
- name: "intent_featurizer_spacy"
- name: "ner_crf"
- name: "ner_synonyms"
- name: "intent_featurizer_count_vectors"
- name: "intent_classifier_tensorflow_embedding"
```

**Comment by SaiPoojithaDubba** [comment]
when used the above pipeline  intents are not getting classified correctly.Should we use large training data for "intent_classifier_ tensorflow _embedding" pipeline.How to improve intent parsing using above pipeline? Thanks in advance

**Comment by jekirl** [comment]
Did you try cross validating to see the F1?

**Comment by SaiPoojithaDubba** [comment]
I am new to this field.How to cross_validate.?

**Comment by jekirl** [comment]
try this:
```
python -m rasa_nlu.evaluate \
    --data YOUR_TRAINING_DATA.json \
    --config YOUR_CONFIG.yml \
    --mode crossvalidation
```

**Comment by Ghostvv** [comment]
PR https://github.com/RasaHQ/rasa_nlu/pull/1095, that contains `new_crf` without spacy is merged

**Comment by DeRigeour** [comment]
i don't get entity extraction for below pipeline configuration:

pipeline:
- name: "intent_featurizer_count_vectors"
- name: "intent_classifier_tensorflow_embedding"
  intent_tokenization_flag: true
  intent_split_symbol: "+"

but for below i get
pipeline:
    - name: "nlp_spacy"
    - name: "tokenizer_spacy"
    - name: "intent_entity_featurizer_regex"
    - name: "intent_featurizer_spacy"
    - name: "ner_crf"
    - name: "ner_synonyms"
    - name: "intent_classifier_tensorflow_embedding"
    - name: "intent_featurizer_count_vectors"
      intent_tokenization_flag: true
      intent_split_symbol: "+"


my question is , 
1> is there a way to get entity extraction using tensorflow_embedding without using spacy...???


2> Also, i tried multiple intent, hoping tensorflow works, but i dont' find multiple intents like how we see multiple entities for a statement.

I have tensorflow version-  1.9  and anaconda 3.6+ version


Please provide some inputs

**Comment by Ghostvv** [comment]
```
pipeline:
- name: "tokenizer_whitespace"
- name: "intent_entity_featurizer_regex"
- name: "ner_crf"
- name: "ner_synonyms"
- name: "intent_featurizer_count_vectors"
- name: "intent_classifier_tensorflow_embedding"
   intent_tokenization_flag: true
   intent_split_symbol: "+"
```
With this pipeline `ner` should work without spacy

**Comment by DeRigeour** [comment]
No Luck. I get below error after adding the same .

        - intent examples: 42 (4 distinct intents)
        - Found intents: 'affirm', 'restaurant_search', 'greet', 'goodbye'
        - entity examples: 11 (2 distinct entities)
        - found entities: 'cuisine', 'location'

Traceback (most recent call last):
  File "C:\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\lib\site-packages\rasa_nlu\train.py", line 174, in <module>
    num_threads=cmdline_args.num_threads)
  File "C:\Anaconda3\lib\site-packages\rasa_nlu\train.py", line 149, in do_train
    interpreter = trainer.train(training_data, **kwargs)
  File "C:\Anaconda3\lib\site-packages\rasa_nlu\model.py", line 180, in train
    components.validate_arguments(self.pipeline, context)
  File "C:\Anaconda3\lib\site-packages\rasa_nlu\components.py", line 86, in validate_arguments
    "".format(component.name, r))
Exception: Failed to validate at component 'ner_crf'. Missing property: 'spacy_doc'

**Comment by Ghostvv** [comment]
which version of `rasa_nlu` do you use? `ner_crf` without `spacy` was introduced in last master version

**Comment by DeRigeour** [comment]
I have tensorflow version- 1.9 and anaconda 3.6+ versio

**Comment by DeRigeour** [comment]
i get this version  on python console   >>>
>>> tf.VERSION
'1.9.0'
>>> Out[37]: '1.2.1'

**Comment by jgutta** [comment]
when you import rasa_nlu to your console, run `rasa_nlu.__version__`and paste the output here please

**Comment by DeRigeour** [comment]
yes, it's   1.9.0


(base) C:\rake>python
Python 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
C:\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
>>>
>>> tf.VERSION
'1.9.0'

**Comment by Ghostvv** [comment]
`1.9.0` is the version of `tensorflow` and not `rasa_nlu`

**Comment by DeRigeour** [comment]
umm... 
>>> import rasa_nlu; print(rasa_nlu.__version__);
0.12.3

**Comment by Ghostvv** [comment]
@DeRigeour yes, it is the last released version, that does not support `ner_crf` without spacy

**Comment by DeRigeour** [comment]
ok.. got it.

**Comment by akelad** [comment]
cool, do you need any more help or can we close this issue?

**Comment by DeRigeour** [comment]
Hi..Thankx much.  We can close this.

**Comment by rohetoric** [comment]
> @DeRigeour yes, it is the last released version, that does not support `ner_crf` without spacy

So what was the last rasa version this worked for?
