### ISSUE TITLE
intent_featurizer_count_vector ERROR: Expected 2D array, got 1D array instead

### ISSUE THREAD

**Issue by AMPXIII** [RasaHQ/rasa_nlu#1125]
**Rasa NLU version**: 0.12.3

**Operating system** : Windows 10

**Content of model configuration file**:
pipeline:
- name: "intent_featurizer_count_vectors"
  "token_pattern": r'(?u)\b\w\w+\b'
  "strip_accents": 'ascii'
  "stop_words": null
  "min_df": 1
  "max_df": 1.0
  "min_ngram": 1
  "max_ngram": 5
  "max_features": null  
- name: "intent_classifier_sklearn"

**Issue**:
I've been trying to use the intent_featurizer_count_vectors featurizer since it has more useful config. options than the spacy one, however the training always fails giving the same error message:

"Expected 2D array, got 1D array instead:
array=[nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample."

No matter what training data is used (demo-rasa.json from the rasa tutorial or any other custom data).
This is a typical issue with sklearn classifiers that comes up when training data hasn't the right shape, but I don't know how to modify this while implementing these methods in the rasa nlu context.

If some of you have come across this issue, it would be nice if you could provide some feedback.

**Comment by Ghostvv** [comment]
@AMPXIII could you please try the branch from this PR: https://github.com/RasaHQ/rasa_nlu/pull/1092

**Comment by Ghostvv** [comment]
@AMPXIII The PR above is merged, I tried this pipeline and it worked. I'll close the issue for now. Please reopen it if you still experience problems
