### ISSUE TITLE
How to use Rasa NLU to build an iOS app

### ISSUE THREAD

**Issue by nahidalam** [RasaHQ/rasa_nlu#1127]
**Rasa NLU version**:0.12.3

**Operating system** (windows, osx, ...): OSx

**Content of model configuration file**:
```
language: "en"

pipeline: "spacy_sklearn"
```

**Issue**:

How can I use Rasa NLU to build an iOS chatbot? Is there any example?

**Comment by wrathagom** [comment]
You could consume the Rasa NLU HTTP API by hosting in on a public server. Then you're iOS app would interact with it just like any other API.

**Comment by wrathagom** [comment]
@nahidalam let me know if you have any further questions. Hope my reply was helpful.
