### ISSUE TITLE
Extracting multiple entities in a single user message

### ISSUE THREAD

**Issue by kpdang94** [RasaHQ/rasa_nlu#1140]
I want to extract multiple entities from a single user message. Example:
user: Please fix my meeting with Mahesh on Monday.

then, rasanlu should be able to detect meeting entity of "event"  type and  Monday as entity of "day" type.

I have tried training using following 2 formats: (None of them seems to work. RasaNLU is able to identify only one entity and not both.)

Training format1:

 ```
{
  "text":"Please fix my meeting with Mahesh on Monday",
  "intent":"setupmeeting",
  "entities":[
    {
      "start":14,
      "end":21,
      "value":"meeting",
      "entity":"event"
    }
  ]
},
{
  "text":"Please fix my meeting with Mahesh on Monday,
  "  intent":"setupmeeting",
  "entities":[
    {
      "start":37,
      "end":43,
      "value":"Monday",
      "entity":"day"
    }
  ]
},
```

Training format2:
```
{
  "text":"Please fix my meeting with Mahesh on Monday",
  "intent":"setupmeeting",
  "entities":[
    {
      "start":14,
      "end":21,
      "value":"meeting",
      "entity":"event"
    },
    {
      "start":37,
      "end":43,
      "value":"Monday",
      "entity":"day"
    }
  ]
},
```

Please tell which format is correct: 1st one or 2nd one or if none of the above is correct then how to train cases where we are having multiple entities in a single message.

**Comment by MinhMinnie** [comment]
@kpdang94 : hey, message me on fb: https://www.facebook.com/minh.minnie.catlover

**Comment by kpdang94** [comment]
Hey could you please resolve the issue here.  It will help other people as well. Thanks

**Comment by MinhMinnie** [comment]
@kpdang94  I am still dealing with this issue. sorry I thought You were one of my friends

**Comment by wrathagom** [comment]
The second option is correct. How much training data do you have? Entity recognition can take quite a few examples to get good results.

**Comment by kpdang94** [comment]
Thanks . It resolved my issue

**Comment by kpdang94** [comment]
@wrathagom

**Comment by wrathagom** [comment]
Great,let us know if you have more troubles.
