### ISSUE TITLE
Option to save Confusion Matrix during evaluation

### ISSUE THREAD

**Issue by naoko** [RasaHQ/rasa_nlu#1147]
**Rasa NLU version**: master

**Operating system** (windows, osx, ...): osx

**Issue**:
We wanted to automate evaluation report generation with rasa_nlu.evaluation module.
The report includes posting confusion matrix generated by matplotlib.
It looked me that best option is to be able to provide optional arg/option to evaluation module otherwise I will have to duplicate many lines of code.

If this is acceptable concept I like to propose this changes (https://github.com/RasaHQ/rasa_nlu/compare/master...naoko:option_to_save_cm_out?expand=1)

Please let me know if I can submit PR

**Comment by azarezade** [comment]
I'm looking forward this option as well.

**Comment by akelad** [comment]
feel free to always submit a PR! (sorry for the late response)

**Comment by naoko** [comment]
Thank you @akelad , will do in the future. I was about to make PR but as I rebasing my branch I noticed that this was already implemented as `--confmat` option thus closing this ticket.
