### ISSUE TITLE
Capturing 'confidence' value in RASA NLU

### ISSUE THREAD

**Issue by MinhMinnie** [RasaHQ/rasa_nlu#1148]
**Rasa NLU version**: 0.12.3

**Operating system** (windows, osx, ...): OSX 10.11.6

**Content of model configuration file**:

language: "fr"

pipeline:
- name: "nlp_spacy"
- name: "tokenizer_whitespace"
- name: "ner_crf"
- name: "ner_synonyms"
- name: "intent_featurizer_count_vectors"
- name: "intent_classifier_tensorflow_embedding"
  intent_tokenization_flag: true
  intent_split_symbol: "+"

**Issue**:
I wan to handle out_of scope messages using confidence threshold but I don't know how to capture this value. Could anyone help me?

**Comment by MinhMinnie** [comment]
Anyone knows how to capture confidence in rasa core?

**Comment by akelad** [comment]
You can do this with the fallback action https://core.rasa.com/patterns.html?highlight=fallback#fallback-default-actions
