### ISSUE TITLE
Add endpoint for downloading spaCy language models.

### ISSUE THREAD

**Issue by wrathagom** [RasaHQ/rasa_nlu#1150]
At the moment there is a manual way of downloading models, and a command line way of downloading models spaCy models. It would be ideal if this functionality was exposed to the API as well. 

## Proposal:
I am proposing that we add a `/languages` endpoint that keeps track of the available language models and can we used to download new ones/delete existing ones.

## Use Case
This one is geared more for the different platforms building on top of Rasa NLU. And will allow tighter integration of UIs and ease language management. But it also has a practical implication in reducing Docker image sizes by eliminating baked in models. Now we can leave the images lean and just add a simple curl to load a language model during setup.

## Specifics

```
GET /languages

{
  "en": {
    SPACY META INFO
  },
  "de": {
    SPACY META INFO
  }
}
```

We can get a list of installed spacy models with the `python -m spacy info` command:

```
bash-4.4# python -m spacy info

    Info about spaCy

    Python version     2.7.14
    Platform           Linux-4.9.87-linuxkit-aufs-x86_64-with
    spaCy version      2.0.5
    Location           /usr/lib/python2.7/site-packages/spacy
    Models             pt, es, fr, de, en
```

Where the spacy meta info is the information available in the `python -m spacy info en` command:

```
bash-4.4# python -m spacy info en

    Info about model en

    lang               en
    pipeline           [u'tagger', u'parser', u'ner']
    name               core_web_md
    license            CC BY-SA 3.0
    author             Explosion AI
    url                https://explosion.ai
    description        English multi-task CNN trained on OntoNotes, with GloVe vectors trained on Common Crawl. Assigns word vectors, context-specific token vectors, POS tags, dependency parse and named entities.
    vectors            {u'keys': 684830, u'width': 300, u'vectors': 20000}
    sources            [u'OntoNotes 5', u'Common Crawl']
    version            2.0.0
    link               /usr/lib/python2.7/site-packages/spacy/data/en
    source             /usr/lib/python2.7/site-packages/en_core_web_md
    spacy_version      >=2.0.0
    parent_package     spacy
    speed              {u'gpu': None, u'nwords': 291344, u'cpu': 4532.930431222}
    email              contact@explosion.ai
    accuracy           {u'token_acc': 99.8609203297, u'ents_p': 85.6222222222, u'ents_r': 86.1342424412, u'uas': 91.7226238412, u'tags_acc': 97.1103903351, u'ents_f': 85.8774691444, u'las': 89.838878402}
```

then we can download new models with something similar to the below:

```
POST /languages

{
  "link": "en",
  "model": "en_core_web_md"
}
```

**Comment by akelad** [comment]
@wrathagom is this still something you would need? and also why? i'm not sure i quite understand the use case/how this would work
