### ISSUE TITLE
No-intent example with Markdown format

### ISSUE THREAD

**Issue by ghostdogpr** [RasaHQ/rasa_nlu#1159]
**Rasa NLU version**: 0.12.3

**Issue**:
The documentation says that "intent" is optional in the common_examples section of the training data. How do you express a missing intent using the Markdown format?

I tried the following:
```yml
## intent:
- [happy](mood)
```
But this doesn't create the proper object in the JSON generated format.

**Comment by akelad** [comment]
So in general we don't really support specifying just examples of entities. Rasa NLU will always identify an intent in an utterance, so it's advised that you label intents on all utterances in your training data. In fact in the markdown format specifying entity training data only is not possible
