### ISSUE TITLE
Error when training a spacy model for the first time

### ISSUE THREAD

**Issue by aitzolete** [RasaHQ/rasa_nlu#1160]
**Rasa NLU version: 0.12.3**:

**Operating system** (windows, osx, ...) Ubuntu 18.04:

**Content of model configuration file**:
```yml
language: "en"

pipeline: "spacy_sklearn"
```

**Issue**:
FFollowing the tutorial I installed rasa NLU + spacy + scikit-learn using pip. But when I try the restaurant search example 'python -m rasa_nlu.train --config config_spacy.yml --data demo-rasa.json' I got the following error:

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/aitzolete/.local/lib/python2.7/site-packages/rasa_nlu/train.py", line 165, in <module>
    utils.configure_colored_logging(cmdline_args.loglevel)
  File "/home/aitzolete/.local/lib/python2.7/site-packages/rasa_nlu/utils/__init__.py", line 299, in configure_colored_logging
    import coloredlogs
ImportError: No module named coloredlogs

I don't know what I'm doing wrong. Any hint will be welcome.

**Comment by Ghostvv** [comment]
you need to run `pip install coloredlogs` to install `coloredlogs`

**Comment by aitzolete** [comment]
Thank you very much, it works fine now.

**Comment by svonia** [comment]
hi, Im trying to do the same thing and I already have coloredlogs but I'm getting this error:
rasa-core 0.9.6 has requirement coloredlogs~=10.0, but you'll have coloredlogs 9.0 which is incompatible.

I tried to get install colored logs 10 by "pip install coloredlogs 10"  and got this: 
Requirement already satisfied: coloredlogs in /usr/local/lib/python2.7/site-packages (9.0)
Collecting 10
  Could not find a version that satisfies the requirement 10 (from versions: )
No matching distribution found for 10

any help with starting rasa would be great. thanks

**Comment by Ghostvv** [comment]
did you try `pip install -U coloredlogs`?
