### ISSUE TITLE
Add regex pipeline for intent extraction and entity detection 

### ISSUE THREAD

**Issue by azarezade** [RasaHQ/rasa_nlu#1162]
I'm thinking about adding regex to rasa pipeline for entity extraction and intent detection. Something like `regex_intent` and `regex_entity`, not just using regex as an extra feature for other intent/entity detection methods.

Because it seem most of usual intent have a small number of fixed forms, like:
-`How is the weather in Paris`
-`How is the weather today`
and it seems to first use regex in the pipeline to detect intent/entity then if no match found then the alternative intent/entity comes and returns the answer.

Actually, this is the main procedure for training skill in Mycroft Adapt parser, which has both intent/entity detection, and if no match found then another module (that named padatuous, I think) triggers. 

Is it possible to add this feature in rasa?

**Comment by HCIS2020** [comment]
I think it's a good idea. We also face this problem.

**Comment by HCIS2020** [comment]
Actually RASA NLU has one keywordsclassifer. but it's an example. you could work on this.

**Comment by nkrot** [comment]
how do two intent classifiers work *together*? Can I have a keyword-based intent classifier and if it outputs nothing then run a ML classifier? I would be interested in such a combination.

**Comment by azarezade** [comment]
@amn41, @akelad, does contributors have any comment on this issue?

**Comment by akelad** [comment]
do the regex features as they currently are not work for you? a few changes were made to that extractor in the past few months, so have you tried with version 0.13?

**Comment by azarezade** [comment]
Thanks @akelad for the reply. That is near the thing that I wanted. I want to user more general pattern for entity recognition, for example does `regex_feature` support entity extraction  based on pattern match like the following one?
```
go from (?P<loc_orig>\w*) to (?P<loc_dest>\w*)
```

**Comment by akelad** [comment]
No but this is something `ner_crf` can easily pick up on if you provide it with training data

**Comment by azarezade** [comment]
hmm..okay thanks @akelad  I will try that, so for now I close the issue.

**Comment by bamba518** [comment]
has anyone made an regex_intent and regex_entity
