### ISSUE TITLE
Can entity extractor enable tensorflow?

### ISSUE THREAD

**Issue by weizhenzhao** [RasaHQ/rasa_nlu#1165]
Hi Dear

After I read some python code , I find that the text classifier can using tensorflow
but the entity extractor doesn't support the tensorflow.
So I think the entity extractor often takes a long time,
If it can be accelerated by the GPU , that would be better

Thanks
WeiZhen

**Comment by Ghostvv** [comment]
in principle, there is tensorflow crf, but we do not use for now. Would you like to create a PR for this?

**Comment by weizhenzhao** [comment]
Hi @Ghostvv 

What do you mean by "PR" , for I 'm not very good at English
Of course I want to see the tensorflow crf version for entity extractor.
But why you don't use it for now? shouldn't it be quicker for trainning?

Thanks
WeiZhen

**Comment by Ghostvv** [comment]
by `PR` I meant GitHub Pull Requests, meaning would you like to make it yourself. The reason, we don't use for now, is because implementation is not a simple thing to do

**Comment by weizhenzhao** [comment]
Hi @Ghostvv 

I think it's a bit difficult for me to implement by PR
Last year I followed a code from cs224d for ner 
[https://github.com/weizhenzhao/cs224d_nlp_problem_set2/blob/master/q2_NER.py](url)
[https://www.cnblogs.com/weizhen/p/7580788.html](url)
and hope it might be useful for you. 
will you support it in the fulture?

Thanks
WeiZhen

**Comment by Ghostvv** [comment]
Thank you for the links, but they are in Chinese 😃
