### ISSUE TITLE
Update sentiment analysis error and make compatible with current version

### ISSUE THREAD

**Issue by AbdurRub** [RasaHQ/rasa_nlu#1168]
This function works fine for me. I just updated 
Line no: 37  in sentiment_analysis.py 
  sentiment += sentence.sentiment.polarity

https://github.com/RasaHQ/rasa_nlu/commit/c3290b1438352875856ab8537054f3c440ee36e8#diff-2a23a3f272b81b641ba931d2b1372069

![screenshot from 2018-06-20 11-49-10](https://user-images.githubusercontent.com/29856813/41641828-fb7b90d8-747f-11e8-94d3-9e6873b361ca.png)

**Comment by akelad** [comment]
this is not something we're planning on merging into rasa_nlu in the near future. If you'd like to use it feel free to add it as a custom component to your pipeline 🙂

**Comment by MinhMinnie** [comment]
@AbdurRub  I am using rasa nlu sentiment branch. Why it doesn't give me polariry and subjectivity when I use curl -X POST localhost:5000/parse -d '{"q":"  "}' to parse the input?
