### ISSUE TITLE
How to call RASA NLU from python function without training the rasa model repeatedly

### ISSUE THREAD

**Issue by ShreyaaJain** [RasaHQ/rasa_nlu#1173]
I am calling the pre trained RASA NLU model from the flask function in python, I want to avoid training the data everytime the function is being called as it is slowing down my application.
When I remove the train command(trainer.train(training_data)) the code does not run at all. 

Is there a way I can call RASA from within python function.
Thanks!

**Comment by RAJAT--PALIWAL** [comment]
**Load model using** 
`interpreter = Interpreter.load(model_directory)`
**Parse message to get result.**
`interpreter.parse(msg)`

Please close issue once done.

**Comment by ShreyaaJain** [comment]
Thanks, got it.
