### ISSUE TITLE
rasa nlu installation issue

### ISSUE THREAD

**Issue by riyajp** [RasaHQ/rasa_nlu#1174]
**Rasa NLU version**: v: 0.9.6

**Operating system** (windows, osx, ...): Windows 10

**Content of model configuration file**:
```yml

```

**Issue**: I cannot install nlu. The error is "failed building twisted wheel" and "require microsoft visual c++" But I already have that on my system. Also tried to download twisted externally. Still not working. Kindly advice.

**Comment by RAJAT--PALIWAL** [comment]
Please Install Visual Studio Build Tools. https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2017
Restart and you will be able to install.
When problem is solved. Please close issue.

**Comment by abhoyar** [comment]
Even I'm facing the same issue. Flowing the steps given in installtion. I also tried with git clone but getting no result. My bad  :-( . 


Using Windows 7 64 bit and Pyhton 3.6 (anaconda ). 
![issue](https://user-images.githubusercontent.com/7037022/42769992-7ac65848-8941-11e8-8bf5-29f958a7412a.PNG)



Attached is the screen shot.

**Comment by akelad** [comment]
can you please post the full trace of your error message?

**Comment by vaatsalya** [comment]
@abhoyar can you please tell me how you resolved it because i got stuck with the same issue as yours

**Comment by abhoyar** [comment]
I'm using anaconda for RASA NLU.  
Please follow this steps :-1s 
Uninstall all python version you have and install anaconda(Recommended by RASA team in there blod also)
 Select the fisrt checkbox(it will place a path in environment variable)

once its installed you restart the system

1) in anaconda prompt type ---> conda install  -c anaconda msgpack -python
2) pip install msgpack( if the abv one failed)
3)conda install twisted

Most important u need to install VC++ 14 version.



Hope it will help you resolve the issue :+1:

**Comment by abhoyar** [comment]
@vaatsalya  

I'm using anaconda for RASA NLU.
Please follow this steps :-1s
Uninstall all python version you have and install anaconda(Recommended by RASA team in there blod also)
Select the fisrt checkbox(it will place a path in environment variable)

once its installed you restart the system

in anaconda prompt type ---> conda install -c anaconda msgpack -python
pip install msgpack( if the abv one failed)
3)conda install twisted
Most important u need to install VC++ 14 version.

Hope it will help you resolve the issue +1

**Comment by vaatsalya** [comment]
@abhoyar 

Thank you It worked.

**Comment by Raj-kishore** [comment]
> @vaatsalya
> 
> I'm using anaconda for RASA NLU.
> Please follow this steps :-1s
> Uninstall all python version you have and install anaconda(Recommended by RASA team in there blod also)
> Select the fisrt checkbox(it will place a path in environment variable)
> 
> once its installed you restart the system
> 
> in anaconda prompt type ---> conda install -c anaconda msgpack -python
> pip install msgpack( if the abv one failed)
> 3)conda install twisted
> Most important u need to install VC++ 14 version.
> 
> Hope it will help you resolve the issue +1

Thanks helped me a lot...

**Comment by Subhashree-hariprashath** [comment]
@abhoyar VC++ 14 version is not available. can u tell me how to solve it 
or do u have any links for the download

**Comment by Arthurgoujon** [comment]
@vaatsalya thanks a lot! that did work
