### ISSUE TITLE
Run NLU server from python

### ISSUE THREAD

**Issue by rithwikjc** [RasaHQ/rasa_nlu#1175]
**Rasa NLU version**: 0.12.3

**Issue**:
Hello.

Is there a function I can call to run the server from python. 
Just like you can train or load a model in python code.
Basically if I want to write a python script that would host and run the project of my choice as a local server instance, without having to type it out in command line every time.

Thanks

**Comment by reza-ebrahimi** [comment]
Yes, rasa_nlu have its own API, have a look here:
https://nlu.rasa.com/python.html

**Comment by reza-ebrahimi** [comment]
Yes, rasa_nlu has its own API, have a look here:
https://nlu.rasa.com/python.html
