### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by macasas** [RasaHQ/rasa_nlu#1178]
I have a fresh installation of Ubuntu with Python 3.6.5 installed.  I am using pip3 to install Rasa, following the instructions on the nlu.rasa.com/installation.html page.

pip3 install rasa_nlu completes without an error
but
pip install rasa_nlu[spacy] completes without an error, but then pops up a Segmentation fault (core dumped) message
(As a side note, pip3 install rasa_core is doing the same thing)

I have cross posted because each fault is related to different repos, apologies if this is wrong.
https://github.com/RasaHQ/rasa_core/issues/651

Here is the end of my log
Collecting toolz>=0.8.0 (from cytoolz<0.9,>=0.8->thinc<6.11.0,>=6.10.1->spacy>2.0; extra == "spacy"->rasa_nlu[spacy])
Installing collected packages: jmespath, six, python-dateutil, docutils, botocore, s3transfer, boto3, werkzeug, incremental, setuptools, zope.interface, constantly, attrs, Automat, idna, hyperlink, Twisted, klein, cycler, pyparsing, numpy, pytz, kiwisolver, matplotlib, tqdm, pathlib, greenlet, gevent, typing, cloudpickle, urllib3, chardet, certifi, requests, simplejson, pyyaml, future, jsonschema, packaging, python-crfsuite, tabulate, sklearn-crfsuite, scikit-learn, scipy, ujson, plac, dill, cymem, preshed, murmurhash, regex, msgpack-python, termcolor, msgpack-numpy, toolz, cytoolz, wrapt, thinc, spacy, rasa-nlu
Successfully installed Automat-0.7.0 Twisted-18.4.0 attrs-18.1.0 boto3-1.7.45 botocore-1.10.45 certifi-2018.4.16 chardet-3.0.4 cloudpickle-0.5.3 constantly-15.1.0 cycler-0.10.0 cymem-1.31.2 cytoolz-0.8.2 dill-0.2.8.2 docutils-0.14 future-0.16.0 gevent-1.3.4 greenlet-0.4.13 hyperlink-18.0.0 idna-2.7 incremental-17.5.0 jmespath-0.9.3 jsonschema-2.6.0 kiwisolver-1.0.1 klein-17.10.0 matplotlib-2.2.2 msgpack-numpy-0.4.1 msgpack-python-0.5.6 murmurhash-0.28.0 numpy-1.14.5 packaging-17.1 pathlib-1.0.1 plac-0.9.6 preshed-1.0.0 pyparsing-2.2.0 python-crfsuite-0.9.5 python-dateutil-2.7.3 pytz-2018.4 pyyaml-3.12 rasa-nlu-0.12.3 regex-2017.4.5 requests-2.19.1 s3transfer-0.1.13 scikit-learn-0.19.1 scipy-1.1.0 setuptools-39.2.0 simplejson-3.15.0 six-1.11.0 sklearn-crfsuite-0.3.6 spacy-2.0.11 tabulate-0.8.2 termcolor-1.1.0 thinc-6.10.2 toolz-0.9.0 tqdm-4.23.4 typing-3.6.4 ujson-1.35 urllib3-1.23 werkzeug-0.14.1 wrapt-1.10.11 zope.interface-4.5.0
Segmentation fault (core dumped)

**Comment by macasas** [comment]
Hi, thanks for your response. Neither core nor nlu would work.  I ended up reinstalling Ubuntu from scratch, with the same options, and it is now installing without problems. Another mystery!

**Comment by reza-ebrahimi** [comment]
**Segmentation fault (core dumped)** is an error raised from OS, it means one the C extensions (Python modules) have problems and crashed. so I think one the reasons that leads to this error is installed dependencies, Currently some of dependencies in rasa_core ad rasa_nlu doesn't have same version, please install in order below:
- install rasa_nlu dependencies
- install rasa_core dependencies
- install rasa_core
- install rasa_nlu

**Comment by reza-ebrahimi** [comment]
**Segmentation fault (core dumped)** is an error raised from OS, it means one the C extensions (Python modules) has problems and crashed. so I think one the reasons that leads to this error is installed dependencies, Currently some of dependencies in rasa_core ad rasa_nlu doesn't have same version, please install in order below:
- install rasa_nlu dependencies
- install rasa_core dependencies
- install rasa_core
- install rasa_nlu

**Comment by akelad** [comment]
sounds like you've solved your issue, so i'll close this for now :)

**Comment by jeffreynghm** [comment]
I have the similar problem. I am using ubuntu 16.04 LTS, installing the rasa_nlu stable version with python 3.5....
I followed @reza-ebrahimi but still faced the same issue of having segmentation fault
