### ISSUE TITLE
TensorFlow version

### ISSUE THREAD

**Issue by sipvoip** [RasaHQ/rasa_nlu#1179]
**Rasa NLU version**: latest git 
**Operating system** (windows, osx, ...): linux - centos7
**Issue**: The requirements_tensorflow_sklearn.txt shows tensorflow==1.6.0, however when you install that you get:

rasa-core 0.10.0a2 has requirement coloredlogs~=10.0, but you'll have coloredlogs 9.0 which is incompatible.
rasa-core 0.10.0a2 has requirement tensorflow<1.9,>=1.7, but you'll have tensorflow 1.6.0 which is incompatible.

Should that be updated to 1.8.0?

**Comment by Ghostvv** [comment]
yes, do you mind making a PR?
