### ISSUE TITLE
Rasa nlu - Multiple intents

### ISSUE THREAD

**Issue by rishikesh1205** [RasaHQ/rasa_nlu#1182]
Rasa NLU version: 0.12.3
Operating system : linux
Issue:
i'm not able to classify the conversations with multiple intents while training in Rasa-nlu and is it even possible??
the config file:
pipeline:

name: "intent_featurizer_count_vectors"
name: "intent_classifier_tensorflow_embedding"
intent_tokenization_flag: true
intent_split_symbol: "+"

**Comment by AbdurRub** [comment]
Please post how you define your multi intent? and how many examples you have for multi intent.

**Comment by wrathagom** [comment]
If that is your entire pipeline you are missing a tokenizer like `tokenizer_whitespace`, which should come at the beginning of your pipeline.

**Comment by Ghostvv** [comment]
@wrathagom if you don't use `ner` tokenizer is optional

**Comment by rishikesh1205** [comment]
@AbdurRub  thank you for the reply. here i don't want to define multi intents. if i have seperate intents like greet and question and when i parse a sentence say "hello walter, do you know about java?" the intent should be like greet + question.  so is there any pipeline or components that can be included so that i can get multi intents without training the data in that way

**Comment by AbdurRub** [comment]
No you have to train it with new intent having greet+question
https://github.com/RasaHQ/rasa_nlu/issues/1072

**Comment by mzq20180601** [comment]
@AbdurRub   i have the same issue raised by @prasgaut

**Comment by akelad** [comment]
The benefit is that you can handle multi intents differently, you can take a look at the blogpost from Juste here: https://blog.rasa.com/how-to-handle-multiple-intents-per-input-using-rasa-nlu-tensorflow-pipeline/
I'll close this issue now as it's more of a discussion than an issue with rasa_nlu. If you would like to discuss this further, please create a post on our [forum](forum.rasa.com)
