### ISSUE TITLE
Defining the NLU pipeline in python

### ISSUE THREAD

**Issue by prat-degwekar** [RasaHQ/rasa_nlu#1184]
How can I set some parameters like "intent_tokenization_flag" while defining the pipeline inside the python training script?

Thanks in advance.

**Comment by wrathagom** [comment]
According to the docs you specify a config file when creating an instance of the Trainer. So each time you want a custom pipeline you could create a new instance of the trainer?

```
from rasa_nlu.training_data import load_data
from rasa_nlu.config import RasaNLUModelConfig
from rasa_nlu.model import Trainer
from rasa_nlu import config

training_data = load_data('data/examples/rasa/demo-rasa.json')
trainer = Trainer(config.load("sample_configs/config_spacy.yml"))
trainer.train(training_data)
model_directory = trainer.persist('./projects/default/')  # Returns the directory the model is stored in
```

I would look at this file for an example: https://github.com/RasaHQ/rasa_nlu/blob/master/rasa_nlu/train.py#L127

**Comment by prat-degwekar** [comment]
Yeah, But in the colab example and the restaurant bot code, the pipeline is defined inside of python like : 
pipeline = [{"name": "nlp_spacy"}, 
            {"name": "tokenizer_spacy"}, 
            {"name": "intent_featurizer_spacy"},  
            {"name": "intent_classifier_sklearn"}]

So, in this scenario, how does one define the parameters?

**Comment by wrathagom** [comment]
I would recommend that you load the config file like in the example I provided and inspect the results of `config.load`.

Though given that yaml is json I would imagine that the parameters are just extra keys on the component objects:

```
pipeline = [
  {
    "name": "nlp_spacy",
    "model": "en_core_web_md"
  },
  {"name": "tokenizer_spacy"},
  {"name": "intent_featurizer_spacy"},
  {"name": "intent_classifier_sklearn"}
]
```

**Comment by prat-degwekar** [comment]
Yeah, that actually worked out. Thanks!
