### ISSUE TITLE
How to make stories and domain file dynamic

### ISSUE THREAD

**Issue by Ujjwalsas9** [RasaHQ/rasa_nlu#1185]
**Rasa NLU version**: 0.12.3

**Operating system** (windows, osx, ...): windows 7

**Content of model configuration file**:
```yml

```
**Issue**: My conversation is changing everyday. So, to accommodate it, I keep changing the stories and domain.yml file everyday. So is it possible to make it easier or dynamic. 
Thanks!

**Comment by wrathagom** [comment]
@Ujjwalsas9 you may have better luck asking this question on the Rasa Core repo instead of the NLU one. https://github.com/RasaHQ/rasa_core

**Comment by akelad** [comment]
I will close this since it's been asked in https://github.com/RasaHQ/rasa_core/issues/667
