### ISSUE TITLE
Unable to train NLU over HTTP

### ISSUE THREAD

**Issue by krgy45** [RasaHQ/rasa_nlu#1186]
**Rasa NLU version**: 0.12.3

**Operating system** (windows, osx, ...): Ubuntu v16.04

**Content of model configuration file**:
nlu_config.yml
```
language: "en"

pipeline:
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "intent_entity_featurizer_regex"
- name: "intent_featurizer_count_vectors"
- name: "ner_crf"
- name: "ner_synonyms"
- name: "intent_classifier_tensorflow_embedding"
  ## network structure
  "num_hidden_layers_a": 2
  "hidden_layer_size_a": [256, 128]
  "num_hidden_layers_b": 1
  "hidden_layer_size_b": [95]
  "batch_size": 20
  "epochs" : 500
  "C2": 0.002
  "droprate" : 0.2
  "embed_dim": 8
  "intent_tokenization_flag": true
  "intent_split_symbol": "_"
```

**Issue**:
When Rasa NLU is ran as a HTTP server on port 5000, the request 
`curl -XPOST localhost:5000/train?project=my_project -d nlu_config.yml` 
returns the error 
`{  "error": "Unknown data format for file /tmp/tmpjgzyk_7q_training_data" }`
Closest issue I can find that is similar to my case is #1050 but I have no idea how to fix this. Can anyone help me? Thanks in advance.

**Comment by krgy45** [comment]
Is it possible to pass the training data in a separate file? I would like to keep my pipeline and data files separate if possible since they are in different formats...

**Comment by wrathagom** [comment]
I'll agree with you it is very odd to pass the data in as two seperate formats. There is a PR here to make  a pure JSON payload work: https://github.com/RasaHQ/rasa_nlu/pull/1149

Another thing I would try is including the x-yml header to tell Rasa you are sending it with the mixed datatype. From the docs:

```
curl -XPOST -H "Content-Type: application/x-yml" localhost:5000/train?project=my_project \
    -d @sample_configs/config_train_server_md.yml
```

**Comment by krgy45** [comment]
Thanks for the help. I found out that I wasn't passing in the filepath properly. Instead of 
`curl -XPOST localhost:5000/train?project=TEST4 -d sample_train.json`
I should have done 
`curl -XPOST localhost:5000/train?project=TEST4 -d @sample_train.json`

I'll go ahead and close the issue now.

**Comment by karthikhadoop** [comment]
hi,
it is not working in my env.
can you please tell me the path of @sample_train.json file.

and i got an error like below, could you please help me on this.
D:\realdata5>curl -XPOST localhost:5000/train?project=my_project -d @realdata5/data/demo-rasarow.json
Warning: Couldn't read data from file "realdata5/data/demo-rasarow.json", this
Warning: makes an empty POST.
{
  "error": "Unknown data format for file C:\\Users\\Karthik\\AppData\\Local\\Temp\\tmp95dwt8fe_training_data"
}
my json file is in my dir path(D:\realdata5\data\demo-rasarow.json)

**Comment by krgy45** [comment]
@karthikhadoop try
`curl -XPOST localhost:5000/train?project=my_project -d @./data/demo-rasarow.json`
from D:\realdata5 instead. Hope it helps

**Comment by karthikhadoop** [comment]
@krgy45 
Hi,i tried with below but it shows an error.
D:\realdata5>curl -XPOST localhost:5000/train?project=my_traindata -d @./data/demo-rasarow.json
{
  "error": "Unknown data format for file C:\\Users\\Karthik\\AppData\\Local\\Temp\\tmpjldsc6et_training_data"
}
D:\realdata5>

**Comment by karthikhadoop** [comment]
and the error file look like an empty  file .

**Comment by krgy45** [comment]
@karthikhadoop have you tried training with the example provided? Maybe your data file is not structured properly.

**Comment by karthikhadoop** [comment]
@krgy45 
hi , my data file look like.
{
"rasa_nlu_data":{
"common_examples":[{
"text":"Book a Movie Ticket on tomorrow",
"intent":"Movie",
"entities":[
{
"start":23,
"end":31,
"value":"tomorrow",
"entity":"Booking"
}]
},
{
"text":"Book a Hotel Ticket On Friday",
"intent":"Movie",
"entities":[
{
"start":23,
"end":31,
"value":"tomorrow",
"entity":"Booking"
}]
},
{
"text":"How are you?",
"intent":"Greetings",
"entities":[]
},
{
"text":"Hi",
"intent":"Greetings",
"entities":[]
},
{
"text":"do you have brochur?",
"intent":"General Information",
"entities":[]
},
{
"text":"do you provide insurance for any accident?",
"intent":"General Information",
"entities":[]
},
{
"text":"can you give me more information?",
"intent":"General Information",
"entities":[]
},
{
"text":"do you have swimming pool?",
"intent":"General Information",
"entities":[]
},
{
"text":"Are you Married?",
"intent":"General Information",
"entities":[]
},
{
"text":"is there any own house for you?",
"intent":"General Information",
"entities":[]
},
{
"text":"Is there any Special Offers>",
"intent":"Services",
"entities":[]
},
{
"text":"Is there any Summer Special Offers?",
"intent":"Services",
"entities":[]
},
{
"text":"Do you have summer camp for Kids?",
"intent":"Services",
"entities":[]
},
{
"text":"What type of Products you sell?",
"intent":"Services",
"entities":[]
},
{
"text":"What are the Products you offer?",
"intent":"Services",
"entities":[]
},
{
"text":"Can i see your horse?",
"intent":"Services",
"entities":[]
},
{
"text":"What type of Services you offer?",
"intent":"Services",
"entities":[]
},
{
"text":"book me a flight to goa",
"intent":"booking",
"entities":[
{
"start":23,
"end":31,
"value":"tomorrow",
"entity":"Booking"
}]
},
{
"text":"Can I See your dogs?",
"intent":"Location",
"entities":[]
},
{
"text":"Where is your location?",
"intent":"Location",
"entities":[]
},
{
"text":"How many dogs are there in your place?",
"intent":"Location",
"entities":[
{
"start":23,
"end":31,
"value":"tomorrow",
"entity":"Booking"
},
{
"start":23,
"end":29,
"value":"Friday",
"entity":"Booking"
}]
},
{
"text":"Can i see your place?",
"intent":"Location",
"entities":[]
},
{
"text":"Can I come to your Location?",
"intent":"Location",
"entities":[]
},
{
"text":"Can you please give me Pen?",
"intent":"Uses",
"entities":[
{
"start":23,
"end":31,
"value":"tomorrow",
"entity":"Booking"
}]
},
{
"text":"Can you please Provide 24 hours Service?",
"intent":"Uses",
"entities":[
{
"start":23,
"end":31,
"value":"tomorrow",
"entity":"Booking"
}]
},
{
"text":"What are the benifits if i use your RPA?",
"intent":"Uses",
"entities":[]
},
{
"text":"Is there any job openings?",
"intent":"Uses",
"entities":[
{
"start":23,
"end":31,
"value":"tomorrow",
"entity":"Booking"
}]
}
]
}
}

**Comment by karthikhadoop** [comment]
now it is showing some different error like below.
D:\realdata5>curl -XPOST localhost:5000/train?project=my_project -d @./data/demo-rasarow.json
{
  "error": "Can not train an empty pipeline. Make sure to specify a proper pipeline in the configuration using the `pipeline` key.The `backend` configuration key is NOT supported anymore."
}

**Comment by karthikhadoop** [comment]
And my config file is:
language: "en"

pipeline: "spacy_sklearn"

**Comment by krgy45** [comment]
@karthikhadoop when you started the RASA NLU server, did you specify a default configuration with the --config parameters? If not, you need to pass the config file together with the data file into the system as a single file, just like the example below: 
```
language: "en"

pipeline: "spacy_sklearn"

# data contains the same json, as described in the training data section
data: {
  "rasa_nlu_data": {
    "common_examples": [
      {
        "text": "hey",
        "intent": "greet",
        "entities": []
      }
    ]
  }
}
```

**Comment by karthikhadoop** [comment]
The Model Was Created Successfully...


D:\realdata5>curl -XPOST localhost:5000/train?project=default -d @./data/demo-rasa.json
{
  "info": "new model trained: model_20180628-145137"
}

Thanks.And I Have One More Issue With me..
Can I pass the Json Data Directly through Url 
curl -XPOST localhost:5000/train?project=default -d @./data/demo-rasa.json
i want to change  data location instead of @./data/demo-rasa.json with {json data}

**Comment by karthikhadoop** [comment]
localhost:5000/train?project=default -d @./data/demo-rasa.json
Is there Any Possibility to set Direct Json data instead of this(@./data/demo-rasa.json)
localhost:5000/train?project=default -d ({--Json Data--})

**Comment by karthikhadoop** [comment]
TQ @krgy45,  My problem is solved.
