### ISSUE TITLE
AWS Lambda function for RASA Server

### ISSUE THREAD

**Issue by AbdurRub** [RasaHQ/rasa_nlu#1187]
I was wondering how can I write AWS lambda function for RASA-NLU. 

Like how can I train my model through python script with using S3 Bucket and then start my server and can able to parse it. 

Initially I uploaded rasa-nlu-master folder in AWS lambda environment and now no clue what to do.

**Comment by vbankov** [comment]
Unfortunately rasa_nlu cannot be run in Lambda due to the size of the final deployment package. Rasa uses spacy by default, which will not fit into a lambda, due to the lambda deployment size limits (https://docs.aws.amazon.com/lambda/latest/dg/limits.html). I would suggest trying with an EC2 server or ECS container.

**Comment by AbdurRub** [comment]
@vbankov can you guide me about ECS container? have you used this?

**Comment by vbankov** [comment]
@AbdurRub yes I have used ECS. I am not in the position to guide you as it depends on what you want to achieve. There is plenty of documentation online, you could start here : https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ECS_GetStarted.html

**Comment by existeundelta** [comment]
could make sense now?

**Comment by mfekadu** [comment]
@existeundelta probably not, sadly... https://forum.rasa.com/t/rasa-aws-lambda/17879/3

**Comment by jpizarrom** [comment]
Hi, would it be possible to deploy rasa(rasa nlu) in aws lamba as a docker container?

the container image code package size is 10 GB.

https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-limits.html
https://docs.aws.amazon.com/lambda/latest/dg/lambda-images.html
