### ISSUE TITLE
Unable to train NLU over HTTP every time is shows an error

### ISSUE THREAD

**Issue by karthikhadoop** [RasaHQ/rasa_nlu#1192]
**Rasa NLU version**:

**Operating system** (windows, osx, ...):

**Content of model configuration file**:
```yml

```

**Issue**:

Hi,i tried with below but it shows an error.
D:\realdata5>curl -XPOST localhost:5000/train?project=my_traindata -d @./data/demo-rasarow.json
{
"error": "Unknown data format for file C:\Users\Karthik\AppData\Local\Temp\tmpjldsc6et_training_data"
}
D:\realdata5>

**Comment by karthikhadoop** [comment]
every time it shows an error as empty file

**Comment by wrathagom** [comment]
Can you try

```
D:\realdata5>curl -XPOST localhost:5000/train?project=my_traindata -d @data/demo-rasarow.json
```

or

```
D:\realdata5>curl -XPOST localhost:5000/train?project=my_traindata -d @data\demo-rasarow.json
```

Also in your curl command you show your data as behind called `demo-rasarow.json` but then in your follow up comment you said `demo-rasaroe.json`, obviously make sure you're spelling everything in the path correctly.

**Comment by wrathagom** [comment]
@karthikhadoop any luck? I think you and I may have gone back and forth on this one in Gitter too?
