### ISSUE TITLE
Preloading projects doesn't seem to work

### ISSUE THREAD

**Issue by parthsharma1996** [RasaHQ/rasa_nlu#1193]
**Rasa NLU version**: 0.12.3

**Operating system** (windows, osx, ...): Arch Linux

**Content of model configuration file**:
```yml
language: "en"

pipeline:
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "intent_featurizer_spacy"
- name: "ner_crf"
- name: "ner_duckling"
  dimensions: ["time"]
- name: "intent_classifier_sklearn"


```

**Issue**: `--pre_load` option for `rasa_nlu.server` doesn't seem to work. Although this has already been raised in #1122 and #1166, I'm raising the issue again (hopefully in a more comprehensive manner) due to the lack of adequate and helpful responses to the aforementioned issues.

1. When I pass the argument `all` to `--pre_load`, it throws the following error. 
```bash
(rasa_env) ❯ python -m rasa_nlu.server --path nlu_models --pre_load all           
2018-06-28 16:28:08 WARNING  rasa_nlu.project  - Using default interpreter, couldn't fetch model: Unable to initialize persistor
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/parth/rasa_env/lib/python3.6/site-packages/rasa_nlu/server.py", line 389, in <module>
    router._pre_load(pre_load)
  File "/home/parth/rasa_env/lib/python3.6/site-packages/rasa_nlu/data_router.py", line 176, in _pre_load
    self.project_store[project].load_model()
  File "/home/parth/rasa_env/lib/python3.6/site-packages/rasa_nlu/project.py", line 140, in load_model
    interpreter = self._interpreter_for_model(model_name)
  File "/home/parth/rasa_env/lib/python3.6/site-packages/rasa_nlu/project.py", line 197, in _interpreter_for_model
    metadata = self._read_model_metadata(model_name)
  File "/home/parth/rasa_env/lib/python3.6/site-packages/rasa_nlu/project.py", line 212, in _read_model_metadata
    self._load_model_from_cloud(model_name, path)
  File "/home/parth/rasa_env/lib/python3.6/site-packages/rasa_nlu/project.py", line 250, in _load_model_from_cloud
    raise RuntimeError("Unable to initialize persistor")
RuntimeError: Unable to initialize persistor
```

2. When I pass a list of projects it does nothing. In fact, I can even pass a list of non-existing projects and it throws no error. 
```
(rasa_env) ❯ python -m rasa_nlu.server --path nlu_models --pre_load non_existing_proj another_non_existing_project 
2018-06-28 16:31:38+0530 [-] Log opened.
2018-06-28 16:31:38+0530 [-] Site starting on 5000
2018-06-28 16:31:38+0530 [-] Starting factory <twisted.web.server.Site object at 0x7f5a183e6b70>
```
3. The [documentation ](https://nlu.rasa.com/http.html#section-http) (and also the [help message](https://github.com/RasaHQ/rasa_nlu/blob/master/rasa_nlu/server.py) of the `rasa_nlu.server` script)  regarding the `--pre_load` argument is outdated/wrong. Specifically this,

> `Eg: python -m rasa_nlu.server -p project1 project2 --path projects`

The argument `-p` doesn't exist.

Perhaps the #1022 PR was buggy.

**Comment by RitwikGopi** [comment]
@parthsharma1996 
1. Can you try running with python 2 and see if same error is produced?
2. I hadn't added the check for non-existing project.
3. This needs to be corrected.

**Comment by reza-ebrahimi** [comment]
`Eg: python -m rasa_nlu.server -p project1 project2 --path projects`
Yes, it is outdated, I have created a PR #1163 before.

**Comment by parthsharma1996** [comment]
@RitwikGopi 
I'm currently set up on python 3. Ideally it should work on both, right? I'll set up and check on python 2 if really helps?

Regarding the 2nd point. I would again like to point out that it's not pre-loading an existing project either.

**Comment by Jcragons** [comment]
Same here, just tested with python 2, exactly same reaction, impossible to pre_load project, even with 'all'.

**Comment by parthsharma1996** [comment]
@RitwikGopi Are you able to get it working for yourself

**Comment by Jcragons** [comment]
On my side, the only method i've got now is it to send a small curl post mentioning the project / model forcing to load it by the server right after start ...

**Comment by RitwikGopi** [comment]
Yeah. For me I didn't had any issue. With both python3 and 2. I gave path
as sklearn model in test model folder of project. Can you try with that

**Comment by RitwikGopi** [comment]
@Jcragons @parthsharma1996 Are you guys still facing any issues? I couldn't follow this up
