### ISSUE TITLE
rasa-nlu flask api

### ISSUE THREAD

**Issue by rishikesh1205** [RasaHQ/rasa_nlu#1194]
can anyone please show  me the python flask file to train the data in nlu and after parse a question to get the intents and entities accordingly

**Comment by Mukund0007** [comment]
Hi Rishikesh,
You can refer this link 
[](https://www.analyticsvidhya.com/blog/2018/01/faq-chatbots-the-future-of-information-searching/)

Here intent-entity classifier is created as HTTP service. Each user request is directed to this service. This HTTP service generally hosted on 5000 port on a localhost, takes user input and returns a jason file with intent and entity for that particular user input. 
Based on intent-entity identified by HTTP service, required response is generated and displayed on flask app's front-end.

I hope it will be helpful in resolving your query. In case need some assistance write me back.

Thanks and Regards,
Mukund

**Comment by Mukund0007** [comment]
[](https://www.analyticsvidhya.com/blog/2018/01/faq-chatbots-the-future-of-information-searching/)

**Comment by Mukund0007** [comment]
https://www.analyticsvidhya.com/blog/2018/01/faq-chatbots-the-future-of-information-searching/

**Comment by wrathagom** [comment]
@rishikesh1205 have you worked through your questions? I'm not entirely certain I understand what you are asking. Rasa NLU doesn't use flask, but rather a library called twisted. Most of the server/twisted code can be found here https://github.com/RasaHQ/rasa_nlu/blob/master/rasa_nlu/data_router.py
