### ISSUE TITLE
Unable to build docs

### ISSUE THREAD

**Issue by parthsharma1996** [RasaHQ/rasa_nlu#1198]
**Rasa NLU version**: master

**Operating system** (windows, osx, ...): Arch Linux

**Content of model configuration file**: - 
**Issue**:
While trying to build the developer docs I'm getting the following error:

```
(rasa_env) ❯ make html
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.7.5

Configuration error:
There is a programable error in your configuration file:

Traceback (most recent call last):
  File "/home/parth/rasa_env/lib/python3.6/site-packages/sphinx/config.py", line 161, in __init__
    execfile_(filename, config)
  File "/home/parth/rasa_env/lib/python3.6/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "conf.py", line 22, in <module>
    import rasabaster
ModuleNotFoundError: No module named 'rasabaster'

```
Does anyone know how to resolve this? I followed the instructions correctly and have re-installed `sphinx` and the `sphinx_rtd_theme` again to no avail.

**Comment by yeahren** [comment]
same issue, and it looks like rasabaster is for private use.

in rasa_core/.travis.yml, it shows:

```bash
35| - pip install git+https://${GITHUB_TOKEN}:x-oauth-basic@github.com/RasaHQ/rasabaster.git#egg=rasabaster
```

**Comment by amn41** [comment]
yes sorry about that, I'll make sure there is a way to build the docs locally.

**Comment by ntoshev** [comment]
I'm getting the same error trying to build documentation with current master.

**Comment by amn41** [comment]
you can build it by downloading a package and instalilng it:
```
curl -sSL "https://storage.googleapis.com/docs-theme/rasabaster-0.7.18.tar.gz"
pip install rasabaster-0.7.18.tar.gz
```

**Comment by ntoshev** [comment]
Thanks, this worked. I also needed to `pip install sphinxcontrib-programoutput sphinxcontrib-programoutput` and build was successful.
