### ISSUE TITLE
Entity extraction for date value using Spacy or Duckling

### ISSUE THREAD

**Issue by jahid-ict** [RasaHQ/rasa_nlu#1203]
**Rasa NLU version**: 0.12.3

**Operating system** (windows, osx, ...): Windows 10 

**Content of model configuration file**:
```
{
  "pipeline": "spacy_sklearn",
  "path" : "./models/nlu",
  "data" : "./data/nlu.json"
}

```

**Issue**:
Suppose, **date** is an entity name which store date value.
"**I want to go to Bangladesh on 12/10/2015**". From the above text **the value for date entity is 12/10/2015**. I have heard Spacy and Duckling has feature which can easily extract this.
**Can anyone please help me on how to do this?** Where to write anything? Where to include anything?
Any help will be appreciated.

**Comment by sipvoip** [comment]
- name: "ner_duckling"
  dimensions: ["amount-of-money", "distance", "duration", "email", "number", "ordinal", "phone-number", "quantity", "temperature", "time", "unit", "unit-of-duration", "url", "volume"]


Is what I use.

**Comment by akelad** [comment]
@jahid-ict can we close this issue, or do you have more questions?

**Comment by jahid-ict** [comment]
@sipvoip @wrathagom  Thanks for your help. Date is now working. For "ner_spacy", when I try for "GPE" then spacy can identify country name started with capital letter for some countries. Can you please share your experience on that?

**Comment by wrathagom** [comment]
I may recommend moving to a larger spacy model (if you're currently just trying the medium model), but for the most part no there is no easy way to improve spacy. If spacy isn't working for you I would suggest trying to train your own entity model using `ner_crf`

**Comment by jahid-ict** [comment]
I am actually now doing this using `ner_crf`. I didn't know about larger spacy model. Thank you for sharing. I'll try this.

**Comment by akelad** [comment]
I'll close this issue for now then - let us know if there's any more issues/questions
