### ISSUE TITLE
Installation Issue in Windows 8.1 (Please install tensorflow)

### ISSUE THREAD

**Issue by AbdurRub** [RasaHQ/rasa_nlu#1205]
**Rasa NLU version**:  stable version 

**Operating system** (windows, osx, ...): windows

**Issue**:
I have tensorflow installed first I installed 1.6.0 then again tested with reinstalling 1.8.0. it keeps on showing Please install tensorflow.

**Comment by wrathagom** [comment]
Are you installing using pip/requirements.txt or the instructions on the tensorflow website?

**Comment by AbdurRub** [comment]
I am doing just this.

1.  pip install rasa_nlu
2.  pip install rasa_nlu[spacy]
3.  pip install coloredlogs (it gives error of this)
4.  pip install tensorflow

**Comment by AbdurRub** [comment]
there is some issue with installing tensorflow in windows 8.1.  please check it out.

**Comment by akelad** [comment]
I'm afraid we can't do anything about installation problems of tensorflow in windows 8.1 - have you followed the official instructions on the tensorflow website for installing on windows?
