### ISSUE TITLE
logs are not generating

### ISSUE THREAD

**Issue by prabhupant** [RasaHQ/rasa_nlu#1206]
I can't find the logs directory after using RASA NLU in python

**Comment by wrathagom** [comment]
The logs are only generated when running Rasa NLU as a server.

**Comment by prabhupant** [comment]
So is there any way that RASA will improve itself by feedback?

**Comment by sandeepsuvit** [comment]
Hope this helps someone. If you run the server using the following command the logs file will be generated under the project root `logs` folder

```
python -m rasa_nlu.server --path projects --response_log logs
```
