### ISSUE TITLE
How do I load model from S3?

### ISSUE THREAD

**Issue by r4sn4** [RasaHQ/rasa_nlu#1209]
I saved model in S3 using AWSPersistor. How do I load model from there? Is there any function analogous to this AWSPersistor for loading model?

**Comment by r4sn4** [comment]
Is it possible or not....no response on this from any one.

**Comment by naoko** [comment]
Are you looking for this? https://github.com/RasaHQ/rasa_nlu/blob/master/rasa_nlu/persistor.py#L28

**Comment by r4sn4** [comment]
I am looking for a way to retrieve... how do I use this?

**Comment by sum0mer** [comment]
have same question

**Comment by akelad** [comment]
Thanks for raising this issue, @amn41 will get back to you about it soon.

**Comment by amn41** [comment]
@sum0mer the docs for that are here https://rasa.com/docs/nlu/persist/ 

you need to pass `--storage aws` to the rasa server when you start it. See all params [here](https://rasa.com/docs/nlu/config/#server-parameters)

**Comment by sum0mer** [comment]
@amn41 Hi, thank you for the reply. I do use this to start server. But my use case is a little different. I want to have two rasa server, one do query, another do training, and i use the same aws storage for both servers. But when the training server creates a new model, the query server is not able to retrieve the new one.
Do you have tips about how to do this? Thanks!

**Comment by gauravbrills** [comment]
> @sum0mer the docs for that are here https://rasa.com/docs/nlu/persist/
> 
> you need to pass `--storage aws` to the rasa server when you start it. See all params [here](https://rasa.com/docs/nlu/config/#server-parameters)
@akelad 
Model persistence to s3  is happening correctly but will the same also load models from the bucket when say the container or instance is restarted and it has lost its local model copy ?

**Comment by sum0mer** [comment]
@gauravbrills  I think i have figured it out.
When instance restart, it will reload models from s3. 
in addition, after upgrade rasa, now a server can also access a new model trained by another server as long as they use the same s3.

**Comment by gauravbrills** [comment]
Ahh great ya saw in code it retrieves. Will be great for deployment. Also do you know if nlu server gives ability to download models

**Comment by sum0mer** [comment]
@gauravbrills I don't know, but you can download it from s3.

**Comment by gauravbrills** [comment]
yup was thinking if they give functionality to expose from rasa nlu will be great as we can then use it as a model server for the core module. Else you need to expose it yourself or yes download from s3 .
