### ISSUE TITLE
Latest Docker image issue

### ISSUE THREAD

**Issue by waqark3389** [RasaHQ/rasa_nlu#1211]
**Rasa NLU version**: 0.12.3-full

**Operating system** (windows, osx, ...): Linux 

**Issue**:

These are the steps I took,

1: docker pull rasa/rasa_nlu
2: docker run -p 5000:5000 rasa/rasa_nlu:latest-full

This exits straight away with error code 132. I have no other logs as there arent any.

If I revert back to a previous version, for example, 0.11.2-full - this works perfectly fine.

**Comment by wu-tao** [comment]
Hi, I have the same issue, do you have some suggestion? Thanks

**Comment by wrathagom** [comment]
Hey all, I made a PR to update the images that just got merged. Can you try pulling down `latest-full` once more?

**Comment by waqark3389** [comment]
@wrathagom - Exactly the same issue, exists with 132. 
I have seen that on newer CPU's this isnt a problem and runs fine. My CPU is older than 3 years which may be the reason I cant run it? 
However the odd thing is that I can run the python module and the server starts up fine. Just with Docker it doesnt work.

**Comment by waqark3389** [comment]
This may be related:

https://github.com/tensorflow/tensorflow/issues/19584

https://github.com/tensorflow/tensorflow/releases?after=v1.6.0

**Comment by wrathagom** [comment]
@waqark3389 are you trying to use the tensorflow dockerfile? Can you provide the full text of the error code? Have you tried cleaning all of the docker images and re-pulling?

@wu-tao I pulled latest full and everything is working fine on my end. I am running 18.03, can you provide more info about your operating system etc, and copy/paste the full error message?

**Comment by waqark3389** [comment]
@wrathagom I am not trying to use the tensorflow dockerfile, I am saying that the version of tensorflow used is >1.6 and as per https://github.com/tensorflow/tensorflow/releases?after=v1.6.0 - this isnt compatible with older CPU. Quoting from above link "Prebuilt binaries will use AVX instructions. This may break TF on older CPUs." 

This is why rasa 12.3-full works for me on new machines but not on older machines without AVX support. 

I have tried cleaning all images and containers, even ran on a different machine with same issue. 
There isnt an error message when running the container but there is a exit code of 132, which is no help :(

**Comment by waqark3389** [comment]
@wrathagom Did you manage to replicate this?
