### ISSUE TITLE
Entities having underscores

### ISSUE THREAD

**Issue by anupam20sep** [RasaHQ/rasa_nlu#1214]
I have a specific requirement where entities contains underscores for eg "more_than_$175". These kind of entities are not extracted while if I give hyphens eg more-than-$175 it gets extracted. Is there any special treatment for underscores?

**Comment by wrathagom** [comment]
@angadn can you tell us which pipeline you are using. As the tokenization is different for each of them.

**Comment by anupam20sep** [comment]
following is the pipeline
  pipeline:
  - name: "nlp_spacy"
  - name: "tokenizer_spacy"
  - name: "intent_featurizer_spacy"
  - name: "intent_classifier_sklearn"
  - name: "ner_crf"
  - name: "ner_synonyms"
