### ISSUE TITLE
Custom input channel for RASA

### ISSUE THREAD

**Issue by Sakshicharaya10** [RasaHQ/rasa_nlu#1216]
How to use a custom input channel like a web service for providing user input to RASA. Could someone please provide an example for that

**Comment by wrathagom** [comment]
Is this for Rasa NLU or Core? For Rasa NLU I would look at making http requests from your web service. Specifically the [`/parse`](https://nlu.rasa.com/http.html#post-parse-no-emulation) endpoint.

**Comment by djuelg** [comment]
I think @Sakshicharaya10 is talking about an Rasa Core InputChannel.
Take a look at this example:

**Comment by akelad** [comment]
@Sakshicharaya10 does that answer your question or do you need more help? :)
