### ISSUE TITLE
Custom entity extractor example

### ISSUE THREAD

**Issue by tstreamDOTh** [RasaHQ/rasa_nlu#1218]
Hi can you provide an example on how to write a custom entity extractor which can be added to the pipeline? Very less documentation is provided regarding this. 

Example - An entity extractor based on rules for a fixed set of items like names of shoe brands

**Comment by wrathagom** [comment]
There is no documentation for this type of request, the best I can offer is a suggestion to review the code for the [current extractors](https://github.com/RasaHQ/rasa_nlu/tree/master/rasa_nlu/extractors)

**Comment by wrathagom** [comment]
@JustinaPetr do you have a post/code stream coming up where you create a custom extractor?

**Comment by tstreamDOTh** [comment]
@wrathagom @JustinaPetr It will be really helpful if you can add some documentation & example for this. Our team is planning to use rasa_nlu but this is a necessity in order to do so. Thanks in advance.

**Comment by tstreamDOTh** [comment]
@akelad I guess yes. #822 would help

**Comment by akelad** [comment]
have you had a chance to try out the PR yet?
