### ISSUE TITLE
How does classifiers work to make results?

### ISSUE THREAD

**Issue by eagle705** [RasaHQ/rasa_nlu#1219]
I just want to know How does classifiers work to make results?

I saw keyword, sklearn, tensorflow based classifers are in pipleline. 

However I still can not find out how they ensemble or co-work to make result.

where can I figure it out to know that? let me know plz

**Comment by wrathagom** [comment]
Read the code for each of the pipeline components is probably the best way to see exactly what they are doing. The components of the pre-configured pipelines are [here](https://nlu.rasa.com/pipeline.html#pre-configured-pipelines) and as an example the classifier code is [here](https://github.com/RasaHQ/rasa_nlu/tree/master/rasa_nlu/classifiers)

You can also find more general information posted to the [Rasa blog](https://blog.rasa.com)
