### ISSUE TITLE
Does rasa tensorflow now support GPU training?

### ISSUE THREAD

**Issue by tushar1328** [RasaHQ/rasa_nlu#1220]
Can Training of RASA be done on GPU? If yes please let me knw. @akelad @wrathagom

**Comment by wrathagom** [comment]
@Ghostvv is the expert here. I would imagine if you have installed the gpu enabled tensorflow though that yes it would take advantage of your GPU.

**Comment by JoeyFaulkner** [comment]
@wrathagom is correct! It should just automatically use your GPU if you follow https://www.tensorflow.org/install/ with GPU support. If you have any issues with rasa nlu/core after 
following this installation then let us know as that would be useful information, but it should work just fine.

**Comment by tushar1328** [comment]
@wrathagom @JoeyFaulkner  will sure let you knw if there is any issue for the same. will try in 2 days and let you knw. Thank you @wrathagom @JoeyFaulkner

**Comment by saxh** [comment]
@JoeyFaulkner @wrathagom I am sure of using tensorflow-GPU=1.11.0. But it's not used when training, can you help me?Thanks a lot.

**Comment by dvigneshwer** [comment]
For some reason, the rasa-nlu model training command is not utilizing my GPU memory (using a Tesla V-100 in an aws instance) - Is there any argument that I need to pass in specific for the code to use the GPU resources?  I tried running the training command with just tensorflow-gpu package but that didn't work as well.

**Comment by kdesai2** [comment]
Hey I'm also facing this same issue, didn't find a solution anywhere on forum too

**Comment by akelad** [comment]
@Ghostvv any ideas?

**Comment by Ghostvv** [comment]
do other tf models use GPU on your computer?

**Comment by saxh** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    Yes.I reinstalled tensorflow-gpu and it working on rasa model
    
        
            
        
    
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                ilshine
                            
                    
                        
                            
                                    ilshine@foxmail.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    On 12/12/2018 19:09，Vladimir Vlasov<notifications@github.com> wrote： 


do other tf models use GPU on your computer?

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by dvigneshwer** [comment]
@Ghostvv - yes other tf models are able to utilize the GPU resources

@saxh  - Reinstalling tensorflow-gpu did not work for me 

Training 55K strings take around 11 hours to complete in CPU.

**Comment by dvigneshwer** [comment]
@Ghostvv  - It will be great if you can suggest any debugging techniques.

**Comment by Ghostvv** [comment]
@dvigneshwer can you check whether you use the same python environment for rasa, where you have reinstalled tensorflow-gpu

**Comment by saxh** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    Yes , it is. Or you can create a new environment for rasa and install tensorflow_gpu rather than tensorflow.
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                ilshine
                            
                    
                        
                            
                                    ilshine@foxmail.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    On 01/2/2019 17:43，Vladimir Vlasov<notifications@github.com> wrote： 


@dvigneshwer can you check whether you use the same python environment for rasa, where you have reinstalled tensorflow-gpu

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by dvigneshwer** [comment]
@Ghostvv Yes it is the same environment where both rasa_nlu and tensorflow_gpu exist 

@saxh  - Created a separate conda environment for rasa training where I had installed rasa_nlu, tensorflow_gpu and other required packages - even that didn't consume the GPU resources while running training command

**Comment by Ghostvv** [comment]
@veliander from the logs it seems that it uses the gpu

**Comment by Ghostvv** [comment]
@veliander about the performance gain, please see this discussion: https://github.com/RasaHQ/rasa_nlu/issues/1398
