### ISSUE TITLE
Rasa input file

### ISSUE THREAD

**Issue by waleedkaimkhani** [RasaHQ/rasa_nlu#1221]
**Rasa NLU version**:

**Operating system** windows:

**Content of model configuration file**:
```yml

```

**Issue**:  does rasa work on other then json formate

**Comment by wrathagom** [comment]
Yes, per the docs it can support [JSON](https://nlu.rasa.com/dataformat.html#data-format) and [Markdown](https://nlu.rasa.com/dataformat.html#markdown-format).
