### ISSUE TITLE
Wrong intent classification

### ISSUE THREAD

**Issue by Ujjwalsas9** [RasaHQ/rasa_nlu#1222]
**Rasa NLU version**: 0.12.3

**Operating system** (windows, osx, ...): windows 7

**Content of model configuration file**:
```yml

```

**Issue**:
I am getting wrong confidence value for intent classification. It is producing same confidence scores for right and and wrong intents both.
For example, if I write, "Hello", I get a confidence score for 0.7827775 and if I write "jdkjfkd skjdksjd skjskjd" then also, it produces a confidence score of 0.7827775.
So, could you please let me know if there is any easier way to rectify this issue.

Thanks in advance!

**Comment by wrathagom** [comment]
Can you tell us which pipeline you are using?

**Comment by Ujjwalsas9** [comment]
I am using "pipeline":"spacy_sklearn".

**Comment by Ujjwalsas9** [comment]
I have 8 intents and 3-4 examples per intent. Thanks!

**Comment by akelad** [comment]
I'd recommend adding ~20 examples per intent to get consistent results. Apart from that, having an `out_of_scope` intent that deals with requests irrelevant to your use case

**Comment by wrathagom** [comment]
@Ujjwalsas9 were you able to get past this problem? I am closing since we haven't heard from you in awhile. But I wanted to make sure you succeeded.
