### ISSUE TITLE
Synonyms for non-entities possible?

### ISSUE THREAD

**Issue by nkrot** [RasaHQ/rasa_nlu#1223]
Hi .*

I receive different intents for the same sentence that differs only in on word: _latest_ vs _recent_. I wonder **if there is a component in rasa nlu that would turn both of the words into one, a la synonyms**, and I will then ensure that my training data contains only one of them. I know that there is a possibility to define synonyms for entities extracted by NER, but I am not speaking about entities now.

The solution that I am thinking of trying is to duplicate/triplicate/multiplicate/zillionicate my training data so that all synonyms are there. But honestly, I do not like this (pseudo)solution because it will skew training as the counts for other words will be artificially increased.

I am using Rasa NLU version: 0.12

Thanks in advance and thank you for cool Rasa

**Comment by wrathagom** [comment]
No there is no such component, though you could pre-process if you have a list of known synonyms.

I would suggest that perhaps you have two intents. For example if you were creating a bot for getting news articles you could have `getLatest` vs `getArticles` where both latest and recent trigger the first intent and other article searches trigger the latter.

**Comment by nkrot** [comment]
@wrathagom , what do you mean by preprocessing?

I dont understand how having two intents `getLatest` and `getArticles` will help me solve the problem. Actually, I see a problem at training dataset creation time: both intents will have very similar training samples. Anyway, thanks for the idea.

**Comment by amn41** [comment]
yes in general it's better to have training data which includes more ways of saying the same thing rather than a pre-defined list of synonyms

**Comment by nkrot** [comment]
@amn41,

Thank you for your answer. Can you maybe shed some light on what happens if I expand my training data by multiplying examples so that they include all possible synonyms? For example, if I initially have 

`Where can I find the latest documents`

and artificially add

`Where can I find most recent documents`

will it skew the dataset resulting in a model that will want to assign this very intent to any sentence containing the word `documents` and disregard other intents that also deal with with documents, because those other intents were not enriched (they dont need `latest`/`recent` synonyms)?

Thanks in advance,

**Comment by amn41** [comment]
It sounds like you don't have very much training data yet. I would suggest you use a word-vector based pipeline (e.g. spacy_sklearn) and then give it to people as soon as possible to collect more data. Augmenting this way can work, but it quickly leads to overfitting if you're not careful. So I'd really strongly suggest that you collect real user input as soon as possible.

**Comment by akelad** [comment]
@nkrot do you need any more help or can we close this issue?

**Comment by nkrot** [comment]
Hi @akelad,

Yes, I guess, I received answer to my question. If this is sufficient to close the issue, it should be done so.

I am still experimenting and of course collecting data. I chose to experiment with a custom preprocessor that replaces synonyms with one word. Let see if it gives some benefit.

**Comment by shrutich91** [comment]
@nkrot 
I am facing the same challenge where I have multiple words that mean the same and they are not entities.
Did you find a way to do that in RASA NLU?
Thanks in advance
