### ISSUE TITLE
Invalid luis data schema version

### ISSUE THREAD

**Issue by harirehm** [RasaHQ/rasa_nlu#1228]
**Rasa NLU version**: 0.13.0a2

**Operating system**: AWS Linux Box

**Issue**:

```
{
  "error": "Invalid luis data schema version 3.0.0, should be 2.x.x. Make sure to use the latest luis version (e.g. by downloading your data again)."
}
```

I'm trying to import LUIS data and then train RASA NLU in that. Seems like, there is a version conflict. Is there any specific RASA NLU version that I have to use? Or is it like, you have stopped supporting LUIS applications that are >= 3.0.0?

**Comment by amn41** [comment]
sounds like LUIS have updated their format and we haven't added support for that yet. Does LUIS provide a changelog somewhere? this would make a great first issue for a new contributor

**Comment by harirehm** [comment]
I'm not sure about what has changed from 2.x.x to 3.0.0. But, when I manually change the version in the training data file to 2.0.0, it trained my model successfully. But, I am yet to test how accurate the model is.

**Comment by akelad** [comment]
Do you have any updates on whether it still gives good accuracy?

**Comment by baumanab** [comment]
I also ran into this issue.  I'll repost here if/when I get an understanding of any performance impact.
