### ISSUE TITLE
Automatic fallback to latest model should be configurable

### ISSUE THREAD

**Issue by antoinesauray** [RasaHQ/rasa_nlu#1232]
When specifying a model in the POST /parse request, if the model is not found it automatically falls back to the latest model.
```
{
    "intent": {
        "name": "greet",
        "confidence": 1
    },
    "entities": [],
    "text": "Hello",
    "project": "default",
    "model": "fallback"
}
```
I think an option to specify the behavior would be nice. In my use case, I would like to reject the query if the model does not exist.

**Comment by Ghostvv** [comment]
Thanks for creating this issue, @ricwo will get back to you about it soon.

**Comment by antoinesauray** [comment]
My case is a little bit different. I don't consider my latest model to be the best. I would like to keep the previous model as default while sending queries specifying a model sometimes to do some a/b testing.

I would rather like to do this in rasa directly than in my client application as changes can occur rapidly, for instance if my new model does not work as good as the previous one.

**Comment by ricwo** [comment]
@antoinesauray do you have any updates on this issue?

**Comment by antoinesauray** [comment]
Yes the PR is nearly ready but it went out of scope compared to the original problem. It's tagged as requires dicussion https://github.com/RasaHQ/rasa_nlu/pull/1410
