### ISSUE TITLE
encoding problem in synonyms implementation in the NLU file

### ISSUE THREAD

**Issue by Cheramy** [RasaHQ/rasa_nlu#1233]
Hi everyone,

I wrote a script to write automatically synonyms in the NLU file from JSON file to the markdown format (seen on the rasa-nlu documentation: https://nlu.rasa.com/dataformat.html).
I got a problem when I train the NLU model and I got this error: 

> `UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 3: ordinal not in range(128)
`

I know that the problem is in the NLU file because I wrote:
\#\# synonym:dément
The problem is the "é" wich must be a "e" to be accepted. Why? 
Everything is encoded in UTF-8.
Do you have an idea to resolve that or an another solution to implement synonyms from JSON file like this: [["maison", "habitat", "demeure", "immeuble", "foyer"],...]?
The pipeline is well configured with the "fr" spacy model.

Thank you in advance!

Cheramy

**Comment by Cheramy** [comment]
I'm on rasa-nlu 0.11.3

**Comment by akelad** [comment]
Can you try either 0.12 or master and see if that's still a problem?

**Comment by Cheramy** [comment]
On rasa-core 0.9 and rasa-nlu 0.12.3 I got this:

ImportError: cannot import name 'RasaNLUConfig'

I also tried with the master version and I got the same problem. I saw in an another issue that the problem is already known but I do not understand how to fix it. 
Thank you in advance!

PS: on rasa-nlu 0.11 and to avoid the encoding problem, I wrote the name of the synonyms without the accentuated letters and that worked but, in french, that can be ambiguous ("sûr" and "sur" wich have very different meaning).

**Comment by akelad** [comment]
Yes, a few things have changed since that version, please refer to the migration guide: http://rasa.com/docs/nlu/master/migrations/
RasaNLUConfig has changed to RasaNLUModelConfig.

**Comment by Cheramy** [comment]
Doesn't work. I got the same issue on the master version:
ImportError: cannot import name 'RasaNLUConfig'
I tried to edit the code to fix it but I got an other error: 

`/usr/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
/usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
2018-07-26 10:05:33.193078: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/gandalf/rasa_core/rasa_core/run.py", line 151, in <module>
    cmdline_args.credentials)
  File "/home/gandalf/rasa_core/rasa_core/run.py", line 130, in main
    agent = Agent.load(model_directory, nlu_model)
  File "/home/gandalf/rasa_core/rasa_core/agent.py", line 62, in load
    _interpreter = NaturalLanguageInterpreter.create(interpreter)
  File "/home/gandalf/rasa_core/rasa_core/interpreter.py", line 31, in create
    return RasaNLUInterpreter(model_directory=obj)
  File "/home/gandalf/rasa_core/rasa_core/interpreter.py", line 221, in __init__
    self._load_interpreter()
  File "/home/gandalf/rasa_core/rasa_core/interpreter.py", line 240, in _load_interpreter
    os.environ))
TypeError: __init__() takes from 1 to 2 positional arguments but 3 were given

`
I don't understand how to fix it. Is-it possible to downgrade rasa-nlu? 
Thanks

**Comment by akelad** [comment]
Can you post the code you're using to train the NLU model please? `python -m rasa_nlu.train -d training_data.md -c config.yml -o models/` for example will work

**Comment by Cheramy** [comment]
I used this:
python -m rasa_nlu.train -c nlu_config.yml --data data/nlu_data.md -o models --fixed_model_name nlu

and it works. 
Your line works too.
The problem with "RasaNLUConfig" appears when I try to start the bot, after the training.

**Comment by Cheramy** [comment]
I removed rasa_core and I installed it again, that works now. 
Thanks for your help!
