### ISSUE TITLE
Building docker container using Dockerfile

### ISSUE THREAD

**Issue by hammond756** [RasaHQ/rasa_nlu#1235]
**Rasa NLU version**: 0.12.3

**Operating system** (windows, osx, ...): Ubuntu

**Content of model configuration file**:
```json
{
  "language": "nl",
  "pipeline": "spacy_sklearn",
  "path" : "./models"
}

```

**Issue**: I have problems building a docker container using docker/Dockerfile_spacy_sklearn.

Because of some modifications to the rasa_nlu code my project requires me to build a container that uses this custom code. I run the commant `docker build -f docker/Dockerfile_spacy_sklearn -t rasa_nlu .` from the project root. Output of the command is large so here is a pastebin: https://pastebin.com/hs4mLFk7. The most notable parts are:

``` 
+ '[' '!' -d /usr/share/man/man1 ']'
+ mkdir -p /usr/share/man/man1
+ apt-get update
```
which looks like an error (it's red) and

```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
 
The following packages have unmet dependencies:
 ca-certificates-java : Depends: openjdk-7-jre-headless but it is not installable or
                                 java7-runtime-headless
 openjdk-8-jdk : Depends: openjdk-8-jre (= 8u171-b11-1~bpo8+1) but it is not going to be installed
                 Depends: openjdk-8-jdk-headless (= 8u171-b11-1~bpo8+1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
The command '/bin/sh -c set -ex;        if [ ! -d /usr/share/man/man1 ]; then       mkdir -p /usr/share/man/man1;   fi;         apt-get update; apt-get install -y -t jessie-backports      openjdk-8-jdk       ca-certificates-java    ;   rm -rf /var/lib/apt/lists/*;        [ "$(readlink -f "$JAVA_HOME")" = "$(docker-java-home)" ];      update-alternatives --get-selections | awk -v home="$(readlink -f "$JAVA_HOME")" 'index($3, home) == 1 { $2 = "manual"; print | "update-alternatives --set-selections" }';  update-alternatives --query java | grep -q 'Status: manual'' returned a non-zero code: 100
```

I have also tried modifying the Dockerfile by removing everything to do with the java installation. This takes care of the problem above but then I run in to the following:

`Double requirement given: spacy==2.0.5 (from -r alt_requirements/requirements_spacy_sklearn.txt (line 4)) (already in spacy==1.9.0 (from -r alt_requirements/requirements_bare.txt (line 19)), name='spacy')`.

The double requirement errors could be prevented by removing lines from requirements_bare.txt that conflicted with that of requirements_spacy_sklearn.txt.
The fact that I had to make these changes suggest to me that I might be doing something wrong. I have looked for guides w.r.t. docker and rasa_nlu but can't find anything on the Dockerfile. Could you point me in the right direction?

**Comment by wrathagom** [comment]
@hammond756 looks like all of these issues have been addressed by recent pull requests. let us know if you have any more troubles by creating a new issue. Thanks.
