### ISSUE TITLE
Entity Extraction with Spacy and Duckling -> Linking to Custom Made Entities

### ISSUE THREAD

**Issue by ptchomakovmoneylion** [RasaHQ/rasa_nlu#1236]
**Rasa NLU version**: 0.12.3

**Operating system** OSX

**Content of model configuration file**:
language: "en"
pipeline:
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "intent_entity_featurizer_regex"
- name: "intent_featurizer_spacy"
- name: "intent_classifier_sklearn"  
- name: "ner_synonyms"
- name: "ner_crf"
- name: "ner_spacy"
- name: "ner_duckling"
  dimensions: ["number"]

P.S. I've done tests with different combinations of the entity extractors

**Issue**:
Hi everyone,

I have two issues in one, but the first is the more important. For an application I'm creating, I need to verify the last 4 digits of the ssn of users. When using ner_duckling, the entity extractor finds the 4 digits (xxxx), but returns entity u"number". In my data set, I've defined the entity as "ssn" and the same thing for the entities and slots in my rasa_core project. My issue is that while the NLU detects perfectly the intent and entities, it doesn't make the linkage between u"number" and the actually entity named ssn thus cannot be used in rasa_core. The same thing happens with ner_spacy where it detects the 4 digits as "CARDINAL" but doesn't link to ssn. On the flip side, ner_crf does fine.

I still want to use ner_duckling in my project because I need to parse dates and other numbers and it works very well, but this is a big drawback and I can't seem to fix it.

The second issue is that while I specify the extractor in the my dataset for the entities, the NLU doesn't always pick the extractor I've specified for a given entity.

Looking for any help here!

**Comment by akelad** [comment]
As for your first issue: you can link these entities with a custom action like this:
```
class MyCustomAction(Action):
  def name(self):
    return "my_custom_action"

  def run(self, dispatcher, tracker, domain):
    number_to_be_saved = tracker.get_latest_entity_values("number")
    # maybe do some post processing here
    return [SlotSet('ssn',number_to_be_saved)]
```
you can also read more about custom actions here: https://core.rasa.com/domains.html#defining-custom-actions

About your second issue: NLU will always run all extractors you've defined on each input. You can just ignore the parts you don't need though. In the training data you should only define entities for `ner_crf`
