### ISSUE TITLE
Rasa NLU pre-trained models

### ISSUE THREAD

**Issue by manishprasadthapliyal** [RasaHQ/rasa_nlu#1237]
**Rasa NLU version**: 0.12.3

**Operating system** (windows, osx, ...): Ubuntu

**Issue**: Does Rasa NLU provides pre-trained models which can be used for intent or entity extraction, without any training data?

**Comment by akelad** [comment]
there is `ner_duckling`, which works for things like time, email, money etc. Or `ner_spacy` which works for things like locations, names etc. You can read more about them here:  https://nlu.rasa.com/master/pipeline.html
