### ISSUE TITLE
Wit.ai trait equivalent

### ISSUE THREAD

**Issue by Bhilhanan** [RasaHQ/rasa_nlu#124]
I'm trying to imitate the "traits" from the wit.ai. How to entity value when it is not inferred from a keyword or specific phrase in the input sentence? For example,

```
{
    "entities": [
      {
        "value": "status", 
        "entity": "my_command"
      }
    ], 
    "intent": "my_intent", 
    "text": "how is it doing?"
  }
```

If I try to train this, then I get a - `KeyError: 'start'`
Is this feature is not yet implemented?

**Comment by amn41** [comment]
you're correct we don't support this feature currently. Could you provide an example of how you would like to use it?

**Comment by Bhilhanan** [comment]
For example, if you are going to extract the sentiment as an entity from a statement then you may look for words such as "like","good","great" etc.

```
"I found it to be good" : entities["sentiment":"positive"]
"It wasn't good" : entities["sentiment":"negative"]
```

Here, you can see that extracting the word "good" from the statement as entity will not give us the right sentiment. We need to look at the whole statement to come up with the entity

**Comment by amn41** [comment]
Understood. Will have to think about how this could be implemented. Suggestions welcome!

**Comment by amn41** [comment]
The new component-based architecture makes it relatively straightforward to add a sentiment analysis component: see #211

**Comment by tmbo** [comment]
I've created a separate issue for the sentiment analysis, as this is somewhat more specific than the wit.ai trait support. #230

**Comment by akelad** [comment]
@amn41 we should close this too right?
