### ISSUE TITLE
Training API takes forever after first successful call, with a tensorflow error

### ISSUE THREAD

**Issue by sum0mer** [RasaHQ/rasa_nlu#1240]
Rasa NLU version:0.12.3
Operating system: linux

Content of model configuration file:
language: "en"

pipeline:
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "intent_entity_featurizer_regex"
- name: "intent_featurizer_spacy"
- name: "ner_crf"
- name: "ner_duckling"
 dimensions: ["time","duration","number", "amount-of-money", "ordinal","email"]
- name: "ner_synonyms"
- name: "intent_featurizer_count_vectors"
- name: "intent_classifier_tensorflow_embedding"
 intent_tokenization_flag: true
 intent_split_symbol: "_"

Issue:
Hi, above is my configuration. My use case requires frequent model retraining, so i expect to use the training API to retrain the model when necessary. The first training API always success, however if I call the API again later, i can't get response, and noticed an tensorflow error printout in the log:
**E tensorflow/stream_executor/cuda/cuda_driver.cc:1298] could not retrieve CUDA device count: CUDA_ERROR_NOT_INITIALIZED**

i start http server using command: python -m rasa_nlu.server --path radiance_nlp -t XXXXXX -P 8080

What can i do to fix this problem? thanks.

**Comment by akelad** [comment]
Seems something to do with multiprocessing: https://github.com/tensorflow/tensorflow/issues/8220
Are you sure the previous training process has finished?

**Comment by wrathagom** [comment]
@sum0mer were you able to get this running?

Since it's been awhile I am going to assume you got it running, but if not feel free to reply here and we'll re-open or create a new issue.
