### ISSUE TITLE
Rasa nlu not able to handle  case sensitive & fuzzy logic utterances. 

### ISSUE THREAD

**Issue by NikhilBansal21** [RasaHQ/rasa_nlu#1241]
**Rasa NLU version**: 0.12.2

**Operating system** (windows, osx, ...): Windows 10

**Content of model configuration file**:
language: "en"

pipeline:
- name: "intent_featurizer_count_vectors"
- name: "intent_classifier_tensorflow_embedding"
  intent_tokenization_flag: true
  intent_split_symbol: "_"

**Issue**: On entering a query in upper case intent are getting wrongly picked i.e if user types RESET PASSWORD  bot is picking up Welcome intent . I know on training this phrase my issue can be resolved but bot should have understanding for a phrase even if it is in caps on or off and even mis-spelled or written like "resetpassword", but sadly this is not happening in my case is their any possible solution for this?

**Comment by akelad** [comment]
So if you use this oov handling, you only have to add a few sentences like "This is oov" (if you choose `oov` to be your token) and then it should be able to handle it. But yes please post your training data if you can

**Comment by NikhilBansal21** [comment]
Hi, where i have to add sentences like "This is oov"?? and yes sending you the training data 
https://gist.github.com/NikhilBansal21/f1d70c075ee111fc806887afe03f408d

**Comment by akelad** [comment]
Ok so once you've added the `OOV_token` to your config like this:
```
- name: intent_featurizer_count_vectors
  OOV_token: oov
```
You need to provide some example sentences with the word "oov" in it, for example "plz reset my oov" - this means if the user decides to enter some new way of saying password (eg. pw) it's mapped to the oov token.

**Comment by NikhilBansal21** [comment]
thanks i got this one more question in the blog it is written 
"For example, one might create separate intent outofscope in the training data containing messages of different number of OOV_token s and maybe some additional general words. Then an algorithm will likely classify a message with unknown words as this intent outofscope." 

Can i know how this can happen like as discussed earlier i created an intent to handle fallback with large amount of data in it. It is having more than 80 phrases . Most of the unknown messages are getting handled by doing this but i want a more effective way for fallback handling as my bot will handle a lot of request so there may be a great chance for bot to miss!

**Comment by akelad** [comment]
the unknown words basically get mapped to the oov token and that's how it's handled :) as for more effective fallback handling have you taken a look at our fallback policy too? http://rasa.com/docs/core/fallbacks/

**Comment by NikhilBansal21** [comment]
Yes i know this solution but how will this be useful in case a wrong phrase is being picked by an intent with confidence threshold more than 0.3 ?? Here fallback policy will fail to work!

**Comment by NikhilBansal21** [comment]
and @akelad  i am talking about nlu and for nlu i need a dedicated intent which i have created and added till now more than 100 phrases which are working fine with totally out of context messages like my bot handles IT support queries for e.g "i want to know about email encryption" and etc and here if user types like "i want to book an uber" or any sort of message that is handled by the garbage intent cz i have added like these garbage queries to teach bot but if user types like "my email account is not getting mails" which is also an out of scope message in context to my bot's domain. The intent is getting picked up for Email encryption itself only. This is just a small instance to make you clear what i really want my bot to do and where it is getting miss. These things are really questioning my bot's stability. and as concerned of confidence i want to tell you till now i have trained alott with each intent atleast having min 50 phrases still idk it is related to spacy or any pipeline confidence for intent classification is very unstable sometimes it gets near to 0.9 and sometimes it maps intent with 0.234 also. These are the 2 main issues bugging me . I hope this makes some sense of what i getting stuck and i hope you will guide me through this as well!! Thanks in advance!

**Comment by akelad** [comment]
The fallback policy is also for nlu, not just core. And yes of course it will fail to work there, but you can set the threshold to something like 0.8 to make it more robust.
As for your intent confusion problem, have you tried running the evaluate to see which intents get confused? It could be that they overlap too much and so the NLU model can't distinguish them.
I'm going to close this issue now, as it's more of a community forum discussion, so please make a post there if you want to discuss this more :) https://forum.rasa.com
