### ISSUE TITLE
ner_crf with tensorflow word embedding feature

### ISSUE THREAD

**Issue by ctrado18** [RasaHQ/rasa_nlu#1243]
Hey,

wouldn't is be interesting to use the word vectors from tensorflow embedding (or spacy) just as a new feature for ner_crf?

Could you some how acces the the word vectors from tensorflow_embedding when you run this first in the pipeline?
If I would try this, do I have to take care of Rasa specific habits (besides just the standard ML tasks) when I add this vector to the feature list? Until now, I am not so deep into Rasa architecture.

**Comment by Ghostvv** [comment]
This is a good question. Word_vectors are persisted in this tensor: https://github.com/RasaHQ/rasa_nlu/blob/2f31d7b53c9a596b254503c3ad94f8a05dddc7b7/rasa_nlu/classifiers/embedding_intent_classifier.py#L232. In order to get a vector for a word you would need to run `self.session` on `self.word_vectors`

**Comment by ctrado18** [comment]
Thanks. I will have a look on it. 😄

**Comment by jmrf** [comment]
@ctrado18 did you start looking into it?

I am also interested in using the `tf_embedding` + `ner_crf`. If you are interested I could give a hand in bringing this together, evaluate etc

Let me know

**Comment by ctrado18** [comment]
@jmrf No, but I would like to see your results!

**Comment by akelad** [comment]
I'm gonna close this issue for now, as this isn't really an issue, but more of a discussion. The right place for this is our [forum](https://forum.rasa.com). We'd be super interested to see your results there!
