### ISSUE TITLE
multi intent detection with RASA_NLU

### ISSUE THREAD

**Issue by kawtherOuenniche** [RasaHQ/rasa_nlu#1245]
**Rasa NLU version**:

**Operating system** (windows, osx, ...):

**Content of model configuration file**:
```yml

```

**Issue**:
I am trying to detect more than one intent with RASA_NLU 
If I provide a sentence like  "thank you good bye " it will detect only one intent goodbye . I tried to add an intent "thank you + good bye " but the confidence is very small. I am thinking of changing the classifier SVM and choose a multi label classifier but I'm stacked .

**Comment by akelad** [comment]
Which pipeline are you currently using? Have you read this article about multi intents? https://blog.rasa.com/how-to-handle-multiple-intents-per-input-using-rasa-nlu-tensorflow-pipeline/

**Comment by lgrinberg** [comment]
Can you use the tensorflow pipeline to recognize entities as well?  Do you need to specify ner_crf in the pipeline?

**Comment by balinda-1995** [comment]
yes I had the same problem but then I used the tensorflow_embedding classifier and it solved it.

However, I was wondering if having a multi-label classifier instead of SVM would work as well? I haven't tried it yet, any ideas?

**Comment by kawtherOuenniche** [comment]
I am using spacy_sklearn as pipeline. I tried tensorflow and it worked but I wanted to change only the classifier .

**Comment by akelad** [comment]
We don't recommend using the spacy_sklearn pipeline for multi-label intents. But yes you could certainly experiment with multi-label classification, but currently Rasa Core only handles one label.

**Comment by QiuSYang** [comment]
> We don't recommend using the spacy_sklearn pipeline for multi-label intents. But yes you could certainly experiment with multi-label classification, but currently Rasa Core only handles one label.

does the latest rasa core already support multi-intention input for designing conversational systems?
