### ISSUE TITLE
Segmentation fault ( core dumped ) while installing RASA_NLU[spacy]

### ISSUE THREAD

**Issue by kawtherOuenniche** [RasaHQ/rasa_nlu#1246]
I am trying to build a chatbot using RASA stack but I am stacked with the installation of RASA_NLU . 
I am using ubuntu on hp i5

**Comment by akelad** [comment]
Can you post the full trace of the error you're getting please?

**Comment by wrathagom** [comment]
@kawtherOuenniche any luck?

I am going to close since it's been awhile, but can re-open if you're still having trouble. Or feel free to create a new issue.
