### ISSUE TITLE
tensorflow_embedding return a valid intent with `sdjfgfjkash jkghfjkagh aghjgh'

### ISSUE THREAD

**Issue by mfleon** [RasaHQ/rasa_nlu#1251]
**Rasa NLU version**: 0.12.3

**Operating system** (windows, osx, ...): Ubuntu 18.04

**Content of model configuration file**:
```yml
language: "en"

pipeline: 
```
"tensorflow_embedding"

**Issue**:
I am using tensorflow_embedding pipeline. When I try a sentence without previously trained words, I get an valid intent as a result. 
If I try `sdjfgfjkash jkghfjkagh aghjgh' I get a valid intent and high score, I didn't expect any intent and 0 as a score. 
Debugging I've watch 'features' has [0, 0, 0...0] all zeros as value

**Comment by Ghostvv** [comment]
This bug was fixed in the latest version of `rasa_nlu`, could you please try to update?

**Comment by mfleon** [comment]
Sorry, I got mixed up the rasa-core and rasa-nlu versions. I got latest nlu version 0.12.3
The problem is in this version.

**Comment by mfleon** [comment]
Ok. I've saw you have fixed in master branch, we'll have to wait until next release
