### ISSUE TITLE
Arabic chatbot using tensorflow pipeline

### ISSUE THREAD

**Issue by balinda-1995** [RasaHQ/rasa_nlu#1253]
I am trying to create an arabic chatbot. When training the model, I keep on getting the error below. 

```
Exception: Can not access action 'Ø­Ø§Ù„Ø©', as that name is not a registered action for this domain. Available actions are: 
	 - action_listen
	 - action_restart
	 - حالة
	 - رد_السلام
	 - رد_الوداع
```
In my domain file I have defined only 3 actions ( the sentences you did not understand ;p )
I have no idea what he means by `'Ø­Ø§Ù„Ø©'` , any ideas?

**Comment by akelad** [comment]
Your action names should be in english, that is probably the issue. Also you should define them by their module path. e.g. if you have the action `ActionExample` in a file called actions.py, you should list this as `actions.ActionExample` in your domain file (however in your stories you can continue using `action_example` in the stories file)

**Comment by balinda-1995** [comment]
I am sorry for the delay! These are my initial stories that I have started the training with

```
## story 01
* سلام
	- رد_السلام
	
## story 02
* وداع
	- رد_الوداع
	
## story 03
* حال
	- حالة
```

**Comment by balinda-1995** [comment]
@akelad yes that's what I did except for the names of the actions, I will switch them to english and see if it works!

**Comment by balinda-1995** [comment]
Solved! It turned out the problem was with the names of the actions, they needed to be in english, thanks!
