### ISSUE TITLE
How do I deploy a Rasa NLU server using Cloud Foundry?

### ISSUE THREAD

**Issue by fetsko** [RasaHQ/rasa_nlu#1260]
**Rasa NLU version**: 0.12.3

**Operating system** (windows, osx, ...): Windows 10

I have followed the basic tutorial and trained my model and hosted it locally (localhost:5000), but now I am hoping to deploy the application using Cloud Foundry.  Is this possible?  If so, what is the easiest approach to achieve this?

**Comment by vigneshp826** [comment]
@fetsko hi, did you successfully hosted the bot on cloud foundry? if yes, can you please help me
