### ISSUE TITLE
LinearSVC vs. SVC(kernel='linear')

### ISSUE THREAD

**Issue by Dobatymo** [RasaHQ/rasa_nlu#1265]
Not really an issue, but a question.

Is there any reason you don't use `LinearSVC` but `SVC(kernel='linear')` for classification? At least in the default configuration, "linear" is the only kernel used for `GridSearchCV`. I have about 5000 samples and training gets _really_ slow. `LinearSVC` would show much better complexity.

**Comment by amn41** [comment]
Great! It's been in our backlog to test this out, so thanks for that. How big is the performance improvement? I would love to see a PR where we make this configurable, or just default to the linear svc if the kernel is set to linear

**Comment by amn41** [comment]
Provided we can give some score, that's probably OK. The scores provided by the SVC aren't super reliable as confidence scores anyway

**Comment by amn41** [comment]
Closing this for now. For large scale training would recommend the `supervised_embeddings` pipeline in any case.
