### ISSUE TITLE
question 2d layer size

### ISSUE THREAD

**Issue by k-koehler** [RasaHQ/rasa_nlu#1266]
hey just a quick question

for NN architecture for each layer we can specify num_hidden_layers, and hidden layer_size.  my question is what does it mean for hidden_layer_size to be two dimensional? Suppose I specify num_hidden_layers as k and hidden_layer_size as (p,q)--how many layers am I specifying? Am I specifying a nn with depth k and height p (or q?)? am i specifying a nn with depth k*p and height q?

I haven't read too thoroughly about the star-space model, so apologies if I'm missing something obvious

thanks! I've really enjoyed using RASA NLU btw!

**Comment by Ghostvv** [comment]
hidden_layer_size is an array of integers specifying the size of each hidden layer https://nlu.rasa.com/pipeline.html#intent-classifier-tensorflow-embedding. So if you specify:
```
num_hidden_layers=3,
hidden_layer_size=[256, 128, 64]
```
then the first layer will have size `256`, the second - `128` and the third - `64`

**Comment by Ghostvv** [comment]
if the length of `hidden_layer_size` should be equal to `num_hidden_layers`

**Comment by k-koehler** [comment]
Thank you. You can close this.
