### ISSUE TITLE
NLU prediction with spacy

### ISSUE THREAD

**Issue by Egalite123** [RasaHQ/rasa_nlu#1269]
**Rasa NLU version**: 0.13.0.a2

**Operating system** (windows, osx, ...): OSX

**Content of model configuration file**:
```
language: "en"
  
pipeline:
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "intent_entity_featurizer_regex"
- name: "intent_featurizer_spacy"
- name: "ner_crf"
- name: "ner_synonyms"
- name: "intent_classifier_sklearn"
```

**Issue**:
NLU predictions sometimes goes really haywire. Pls see the following pairs.

"i am looking for document" and "looking for document" results in different intents being predicted.
Similarly, "I want to know who can apply for children account" and "want to know who can apply for children account" also result different predictions.

Is this normal behaviour?

**Comment by wrathagom** [comment]
Depends on how much training data you have and how close your intents are to each other. Problems like this can usually be fixed with more training data.

**Comment by bay007** [comment]
I read in Spacy page that the 100 examples can improve the accurasy, for Rasa in web page says arround 20-30 its ok for starting.

**Comment by Priya-ch** [comment]
how much training data is required to get accuracy.. I have around 20 intents and for each intent i have provided around 25+ training data but still I am facing the same issue. Different predictions for almost similar questions

**Comment by akelad** [comment]
hmm which english model are you using? the medium one? and do you maybe have intents that are very similar? If you could share your training data, that would help

**Comment by Egalite123** [comment]
yes, I am using Medium. I have an average of about 40 examples per intent. I will shortly share the scripts for couple of intents where I am having this issue

**Comment by DileepkumarT** [comment]
I have created a config file as below
"language":"en",
"pipeline":"spacy_sklearn"

Do I need to specify any other parameters additionally?
What is the difference between my config file and below one?
language: "en"
  
pipeline:
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "intent_entity_featurizer_regex"
- name: "intent_featurizer_spacy"
- name: "ner_crf"
- name: "ner_synonyms"
- name: "intent_classifier_sklearn"

I was not able to classify my intents as expected. I think issue is with stop words. Can I get some info on this also?

**Comment by amn41** [comment]
please post your question in the [community forum](https://forum.rasa.com) - thanks!

**Comment by akelad** [comment]
I'm going to close this issue since it's been moved over to the forum
