### ISSUE TITLE
Does training data gets converted to lower cases before processing?

### ISSUE THREAD

**Issue by Sramperu** [RasaHQ/rasa_nlu#1276]
Hi... Its more of a question than issue.... Whenever I train my data, does RASA NLU convert these training data to lower case?

If so, is there a way we can turn this feature off? Bcos I do have to process abbreviations which are mostly provided in Upper case.

My config yml file content:

language: "en"

pipeline:
- name: "nlp_spacy"
- name: "ner_spacy"
- name: "tokenizer_whitespace"
- name: "tokenizer_spacy"
- name: "intent_entity_featurizer_regex"
- name: "intent_featurizer_spacy"
- name: "ner_crf"
- name: "ner_synonyms"
- name: "intent_classifier_sklearn"
- name: "intent_featurizer_count_vectors"
- name: "intent_classifier_tensorflow_embedding"
  intent_tokenization_flag: true
  intent_split_symbol: "+"

**Comment by auzair92** [comment]
There's a configuration parameter called `case_sensitive` that you can pass to the `nlp_spacy` component of the pipeline. You could try setting it to `true` and see if it helps.

Docs [here](https://nlu.rasa.com/pipeline.html#nlp-spacy).

**Comment by Ghostvv** [comment]
also `intent_featurizer_count_vectors` has parameter in `master` version, which you can set to `lowercase: false`: https://nlu.rasa.com/master/pipeline.html#intent-featurizer-count-vectors
