### ISSUE TITLE
auto- reload available models when server is running

### ISSUE THREAD

**Issue by amn41** [RasaHQ/rasa_nlu#128]
If you train over the HTTP API, the running server doesn't recognise the existence of the new model until you restart it.

**Comment by tmbo** [comment]
Should have a look at something like http://stackoverflow.com/questions/16366124/share-a-numpy-array-in-gunicorn-processes

Eg. spinning up a "server" which holds a dictionary of the models (won't share the backend but we'd be able to add a model in one process and serve it from others).

**Comment by wrathagom** [comment]
I believe this one is fixed now... well actually I know it is. The only gotcha is if the new model has the same name as an old model that was already loaded it won't be reloaded...
