### ISSUE TITLE
How to leverage ner_spacy?

### ISSUE THREAD

**Issue by MartinGentleman** [RasaHQ/rasa_nlu#1286]
**Rasa NLU version**:
0.12.3
**Operating system** (windows, osx, ...):
OSX

**Issue**:

How do I leverage ner_spacy for entities and slots?

It seems that entity/slot extraction works through ner_crf. If I add ner_spacy I can see that NLU can recognize entities independently. However that is not leveraged in Rasa Core or I have not found a way how to leverage it. Is the assumption in the project that you can put into the NLU pipeline whaterver but to actually use it, the processing piece on top of tracker has to be fully developed independently on Rasa?
Common use case in my opinion is name extraction. ner_crf recognizes only first/last names that I manually teach it but ner_spacy would recognize the name with a label PERSON without me teaching it. Therefor to extract the name I have to build own layer on top of tracker that compares the ner_crf and ner_spacy results and fills entities/slots manually?
Is there a buildin way in Rasa that would feed ner_spacy specific label result into an entity/slot?

**Comment by akelad** [comment]
@twhughes will get back to you on this :) next time please post this kind of thing on our [forum](https://forum.rasa.com) as it's more of a question than an issue/bug with the stack

**Comment by twhughes** [comment]
@MartinGentleman Right now both ner components will work independently and give their own predictions for the various entities.  I agree that it would be nice to have some builtin component for combining these predictions but at the current time it is not supported.

For now, the best approach would be to manually combine the outputs based on whatever criteria make sense in your problem, as you suggest.
