### ISSUE TITLE
Arabic bot: Encoding problem

### ISSUE THREAD

**Issue by balinda-1995** [RasaHQ/rasa_nlu#1287]
**Rasa NLU version**: 0.12.3

**Issue**:
I am working on an arabic bot. My dialogue management model returns an encoding error when I try to train it. Everything else works fine ( NLU model and the online training).
This is the error:
`UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 410: character maps to <undefined>
`
This is the part of code it has a problem with:

```
def train_dialogue(domain_file='domain.yml',
                   model_path='C:/Users/Asus/Desktop/eng_intern/arabicBot2/model/dialogue',
                   training_data_file='C:/Users/Asus/Desktop/eng_intern/arabicBot2/data/train_stories.md'):
    agent = Agent(domain_file, policies=[MemoizationPolicy(), KerasPolicy()])

    agent.train(
        training_data_file,
        epochs=300,
        batch_size=50,
        validation_split=0.2)

    agent.persist(model_path)
    return agent
```

It is unable to read my md file train_stories where I stored my stories to train the model. Here is an example of a training story:
```
##Generated Story 3
* Selem
    - action_selem
* inform{"country":"الأرجنتين"}
	- slot{"country":"الأرجنتين"}
	- action_geo
	- slot{"country":"الأرجنتين"}
* inform{"country":"الجزائر"}
	- slot{"country":"الجزائر"}
	- action_geo
	- slot{"country":"الجزائر"}
* bye+thanks
    - action_goodbye
```

**Comment by akelad** [comment]
This is an issue with Core right? make sure to post in the correct repo next time please :)
which Core version are you using?

**Comment by balinda-1995** [comment]
I am sorry for that
it is 0.9.8

**Comment by akelad** [comment]
Can you try the latest 0.10 version?

**Comment by balinda-1995** [comment]
Thanks for your answer, but I still have the same answer.
My bot is actually working fine because it is very simple. So I am using the trained dialogue on my initial stateless stories. So I am not executing the function train_dialogue on my actual training stories, and the bot is still working fine. However it would be great to know how to fix the bug.

**Comment by akelad** [comment]
I tried training with that specific story and it worked fine for me. So could you maybe post your full stories file? 
Also what do you mean, so training on other stories works?

**Comment by akelad** [comment]
Thanks I'll try and reproduce this :)

**Comment by Ai80-8** [comment]
Delete it all
