### ISSUE TITLE
duckling_http suddenly giving wrong year

### ISSUE THREAD

**Issue by Krogsager** [RasaHQ/rasa_nlu#1291]
**Rasa Core version**: 0.10.3

**Rasa NLU version**: 0.13.0

**Python version**: Python 3.6.6

**Operating system** (windows, osx, ...):

**Issue**:
On thursday last week duckling was working fine. Now duckling ner is always returning the year 1970. 
Example:

> d. 12 juli klokken 16:30
> 'value': '1970-07-12T16:30:00.000+00:00'
> 'extractor': 'ner_duckling_http'}]'

Or "today":

> i dag
> 'value': '1970-01-18T00:00:00.000+00:00',
> 'extractor': 'ner_duckling_http'}]'

However it is not completely broken. Giving explicit date and the time "quarter past 8"

> 1/1/2018 klokken kvart over 8
> 'value': '2018-01-01T08:15:00.000+00:00'
> 'extractor': 'ner_duckling_http'}]'

If I test duckling separately it works as expected; the year is 2018. "i dag" again is "today"

> curl -XPOST http://0.0.0.0:8000/parse --data 'locale=da_DK&text=I dag'

> "value":"2018-08-06T00:00:00.000-07:00"

**Comment by akelad** [comment]
did you recently upgrade your NLU from 0.12 to 0.13?

**Comment by Krogsager** [comment]
Yes, would you recommend a downgrade?

**Comment by akelad** [comment]
no i wouldn't, but we changed something in the 0.13 version that might be causing it, i'll try to look into it today!

**Comment by akelad** [comment]
can you try setting the timezone in your config file: `timezone: "Europe/Berlin"`

**Comment by Krogsager** [comment]
Changing the timezone from Copenhangen to Berlin did not do any difference. Neither did removing the timezone entirely.

**Comment by akelad** [comment]
hmm ok, odd. i will take a proper look this afternoon what's going on

**Comment by akelad** [comment]
i've created a PR for this as you can see, use this branch for now and see if that fixes it please! 
we'll merge it hopefully soon and will then do a minor release so that's fixed

**Comment by Krogsager** [comment]
I've switched to new branch fix_ducklinghttp but I'm not getting the code changes in duckling_http_extractor.py
When I try to do `git pull `I get:

> There is no tracking information for the current branch.
> Please specify which branch you want to merge with.
> See git-pull(1) for details.
>     git pull <remote> <branch>
> If you wish to set tracking information for this branch you can do so with:
>     git branch --set-upstream-to=origin/<branch> fix_ducklinghttp

**Comment by Krogsager** [comment]
I took a hammer to git and got the pull. 
The fix works!
Vielen dank Akelad!

**Comment by akelad** [comment]
No problem! we release version 0.13.1 as well btw, including that fix
