### ISSUE TITLE
RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility.

### ISSUE THREAD

**Issue by ctrado18** [RasaHQ/rasa_nlu#1326]
After upgrading from 13.0 to 13.1 and Rasa Core from 0.9.0 to 10.4 I get a warning:

```
C:\Users\Anaconda3\envs\master\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
```

**Comment by amn41** [comment]
@ctrado18 is this when loading a model? Rasa core 0.10 is a major update with backwards, incompatible changes, see the [changelog](https://github.com/RasaHQ/rasa_core/blob/master/CHANGELOG.rst#id12) and [migration guide](http://rasa.com/docs/core/migrations/)

**Comment by Ghostvv** [comment]
Please see discussion: https://stackoverflow.com/questions/40845304/runtimewarning-numpy-dtype-size-changed-may-indicate-binary-incompatibility
