### ISSUE TITLE
NLU training data is tested for insufficient number of examples before merging individual files

### ISSUE THREAD

**Issue by hotzenklotz** [RasaHQ/rasa_nlu#1327]
**Rasa NLU version**:
0.13.x

**Operating system** (windows, osx, ...):
OSX

**Issue**:

When structuring NLU training data as multiple individual files in a single directory, all of them will be checked for insufficient number of training data individually. This will lead to false warning of insufficient training examples:

```
UserWarning: Entity `my_entity` has only 1 training examples! minimum is 2, training my fail.
```

To fix this, all NLU training data files should be merged before checking that entities or intents have enough training examples.

### Example
- Training Data file A only contains a single example for `my_entity`. This will raise a warning.
- Training Data file B contains 10 examples for `my_entity`. Everything is fine.

Even though there are plenty of examples of `my_entity`, any method loading the NLU data will raise this warning because in one file only a single instance was available.

**Comment by amn41** [comment]
thanks @hotzenklotz ! we'll check this out - sounds super valid
