### ISSUE TITLE
Cannot select buttons in interactive training/console

### ISSUE THREAD

**Issue by loochy** [RasaHQ/rasa_nlu#1332]
**Rasa NLU version**:
0.13.0a1
**Operating system** (windows, osx, ...):
OSX 10.12.6
**Content of model configuration file**:
```yml
domain.yml extract below
```

**Issue**:
I have slot filling from nlu, but want to use buttons to fill a slot and trigger an action in specific cases. My issue is that I cannot actually select a button in interactive training, or when I run the trained bot in the console, and so I cannot check if the slots are being filled to carry out an action. 

I have buttons defined in domain.yml like this:

  utter_ask_account:
  - buttons:
    - payload: /account_creation{account_type:Acct1}
      title: Acct1
    - payload: /account_creation{account_type:Acct2}
      title: Acct2
    - payload: /account_creation{account_type:Acct3}
      title: Acct3
    text: Can you tell me which account you need?

  utter_ask_first_visit:
  - buttons:
    - payload: /affirm
      title: New to bot
    - payload: /deny
      title: Been here before
    text: Have we met before?

And some stories that look like this (utter_ask_account used when "account_type" slot is not filled):
## story_004
* greet
  - utter_welcome
  - utter_ask_first_visit
* deny
  - utter_continue
* ask_logon_type
   - utter_ask_account
* account_creation{"account_type": "Acct1"}
   - slot{"account_type": "Acct1"}
   - action_get_logon
   - slot{"account_type": "Acct1"}
* goodbye
    - utter_goodbye
 ## story_005
* greet
  - utter_welcome
  - utter_ask_first_visit
* affirm
  - utter_new_id_num
* account_creation
    - utter_ask_account
* account_creation{"account_type": "Acct2"}
    - slot{"account_type": "Acct2"}
    - action_get_logon
    - slot{"account_type": "Acct2"}
* goodbye
    - utter_goodbye

I have been able to get the right actions to come up, like this console run of the bot, but the answers have to be in text, not in button selection:

User: hello
Bot: Welcome! I'm bot!
Have we met before?
1: New to bot (/affirm)
2: Been here before (/deny)

User: yes
Bot: Great! Your user id will be 1234.

User: i need a logon
Bot: Can you tell me which account you need?
1: Acct1 (/account_creation{account_type:Acct1})
2: Acct2 (/account_creation{account_type:Acct2})
3: Acct3 (/account_creation{account_type:Acct3})

User: I need a Acct2 account
Bot: You can get the logon for Acct2 at www.acct2.com.

If I answer with a button press, either in interactive training or in the console run of the trained bot, I get nothing (and in the console run I can't enter anything else): 

User: hello
Bot: Welcome! I'm bot!
Have we met before?
1: New to bot (/affirm)
2: Been here before (/deny)

User: 1

Bot: 

I'm very sorry if I'm missing something, but I've been searching for days and just can't figure it out. 
Thanks!

**Comment by amn41** [comment]
you can enter the button payload directly in the console, e.g. `/account_creation{account_type:Acct1}`

**Comment by loochy** [comment]
Hey, thanks for the info, but it doesn't seem to be working for intents with the slots attached. It works for the /affirm or /deny intent, but I can't seem to get a working format for the entity/slot identified one (Option1/2/3 below): 

hi
Bot: Welcome! I'm bot!
Have we met before?
1: New to bot (/affirm)
2: Been here before (/deny)

/affirm
Bot: Great! Your user id will be 1234.

I need a logon
Bot: Can you tell me which account you need?
1: Acct1 (/account_creation{account_type:Acct1})
2: Acct2 (/account_creation{account_type:Acct2})
3: Acct3 (/account_creation{account_type:Acct3})

Option1:
User: /account_creation{"account_type": "Acct2"}
Console: <nothing>

Option2:
User: /account_creation{account_type:Acct2}
Console: 2018-08-22 15:39:31 WARNING  rasa_core.interpreter  - Invalid to parse arguments in line '/account_creation{account_type:Saba}'. Failed to decode parametersas a json object. Make sure the intentfollowed by a proper json object. Error: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

Option3:
User: /account_creation[account_type=Acct2]
Console: /rasa_core-0.8.2-py3.6.egg/rasa_core/processor.py:208: UserWarning: Parsing messages with leading `_` is deprecated and will be removed. Instead, prepend your intents with `/`, e.g. `/mood_greet` or `/restart`.

I am formatting it incorrectly? Thanks!

**Comment by amn41** [comment]
option 1 is the correct format, if you are not getting a response then it looks like Rasa Core is predicting to `listen` - you may just need to add some more stories. It helps to run with `rasa_core.run --debug` to see exactly what's going on

**Comment by loochy** [comment]
@akelad  yes, I had seen that, but it was difficult for me to piece it together with exactly how the buttons could be triggered from a custom action or utterance (I was looking through the code about dispatcher.utter_button_template/dispatcher.utter_button_message for that). 

The formatting of the  buttons was new to me (e.g. payload to fill slots), the 'pushing' of the buttons was unknown (since I thought you could id them by the number automatically produced). So when I say documentation around buttons, I mean gathering all the related info together and having clear, full examples.

**Comment by akelad** [comment]
Cool, thanks for the feedback, we'll take a note of it :)

**Comment by pkchoudhary1211** [comment]
Thank You I got my  solution from this issue

**Comment by Saurbh060** [comment]
> Hey, thanks for the info, but it doesn't seem to be working for intents with the slots attached. It works for the /affirm or /deny intent, but I can't seem to get a working format for the entity/slot identified one (Option1/2/3 below):
> 
> hi
> Bot: Welcome! I'm bot!
> Have we met before?
> 1: New to bot (/affirm)
> 2: Been here before (/deny)
> 
> /affirm
> Bot: Great! Your user id will be 1234.
> 
> I need a logon
> Bot: Can you tell me which account you need?
> 1: Acct1 (/account_creation{account_type:Acct1})
> 2: Acct2 (/account_creation{account_type:Acct2})
> 3: Acct3 (/account_creation{account_type:Acct3})
> 
> Option1:
> User: /account_creation{"account_type": "Acct2"}
> Console:
> 
> Option2:
> User: /account_creation{account_type:Acct2}
> Console: 2018-08-22 15:39:31 WARNING rasa_core.interpreter - Invalid to parse arguments in line '/account_creation{account_type:Acct2}'. Failed to decode parametersas a json object. Make sure the intentfollowed by a proper json object. Error: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
> 
> Option3:
> User: /account_creation[account_type=Acct2]
> Console: /rasa_core-0.8.2-py3.6.egg/rasa_core/processor.py:208: UserWarning: Parsing messages with leading `_` is deprecated and will be removed. Instead, prepend your intents with `/`, e.g. `/mood_greet` or `/restart`.
>

 
> I am formatting it incorrectly? Thanks!




> Hey, thanks for the info, but it doesn't seem to be working for intents with the slots attached. It works for the /affirm or /deny intent, but I can't seem to get a working format for the entity/slot identified one (Option1/2/3 below):
> 
> hi
> Bot: Welcome! I'm bot!
> Have we met before?
> 1: New to bot (/affirm)
> 2: Been here before (/deny)
> 
> /affirm
> Bot: Great! Your user id will be 1234.
> 
> I need a logon
> Bot: Can you tell me which account you need?
> 1: Acct1 (/account_creation{account_type:Acct1})
> 2: Acct2 (/account_creation{account_type:Acct2})
> 3: Acct3 (/account_creation{account_type:Acct3})
> 
> Option1:
> User: /account_creation{"account_type": "Acct2"}
> Console:
> 
> Option2:
> User: /account_creation{account_type:Acct2}
> Console: 2018-08-22 15:39:31 WARNING rasa_core.interpreter - Invalid to parse arguments in line '/account_creation{account_type:Acct2}'. Failed to decode parametersas a json object. Make sure the intentfollowed by a proper json object. Error: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
> 
> Option3:
> User: /account_creation[account_type=Acct2]
> Console: /rasa_core-0.8.2-py3.6.egg/rasa_core/processor.py:208: UserWarning: Parsing messages with leading `_` is deprecated and will be removed. Instead, prepend your intents with `/`, e.g. `/mood_greet` or `/restart`.
> 
> I am formatting it incorrectly? Thanks!

why this /affirm(intent) is shown when we select 1: New to bot ?
and how to remove this intent from conversation
