### ISSUE TITLE
Trigger RasaNLU to perform action after uploading a CSV/Excel File

### ISSUE THREAD

**Issue by vinayver198** [RasaHQ/rasa_nlu#1333]
**Rasa NLU version**:

**Operating system** (windows, osx, ...):

**Content of model configuration file**:
```yml



**Issue**:

I am trying to trigger action , after uploading a csv file or Excel file. Can anyone help in this regard.

Thanks

**Comment by amn41** [comment]
@vinayver198 I'm afraid you don't provide many details, but it sounds like you are trying to achieve something quite custom. Also, Rasa  NLU currently doesn't support csv or excel input, is that what you are hoping to implement? This question might be better suited to our [community forum](https://forum.rasa.com)

**Comment by akelad** [comment]
This sounds like more of a Rasa Core thing, but I agree it should be posted in the forum, so I'll close this issue
