### ISSUE TITLE
RASA NLU not able to predict the entities

### ISSUE THREAD

**Issue by manojjjm** [RasaHQ/rasa_nlu#1339]
RASA nlu Version: 0.8

Windows os

config file

{
  "pipeline":"spacy_sklearn",
  "path":"./models/nlu",
  "data":"./data/data.json"
}

The data.json is as follow

{
  "rasa_nlu_data": {
    "common_examples": [
      {
        "text": "hi",
        "intent": "greet",
        "entities": []
      },
      {
        "text": "hello",
        "intent": "greet",
        "entities": []
      },
      {
        "text": "hey",
        "intent": "greet",
        "entities": []
      },
      {
        "text": "Hi there",
        "intent": "greet",
        "entities": []
      },
      {
        "text": "good morning",
        "intent": "greet",
        "entities": []
      },
      {
        "text": "good afternoon",
        "intent": "greet",
        "entities": []
      },
      {
        "text": "good evening",
        "intent": "greet",
        "entities": []
      },
      {
        "text": "bye",
        "intent": "bye",
        "entities": []
      },
      {
        "text": "good bye",
        "intent": "bye",
        "entities": []
      },
      {
        "text": "talk to you later",
        "intent": "bye",
        "entities": []
      },
      {
        "text": "ttul",
        "intent": "bye",
        "entities": []
      },
      {
        "text": "see you",
        "intent": "bye",
        "entities": []
      },
      {
        "text": "tata",
        "intent": "bye",
        "entities": []
      },
      {
        "text": "How can I update my name?",
        "intent": "inform",
        "entities": [
          {
            "start": 10,
            "end": 24,
            "value": "update my name",
            "entity": "update name"
          }
        ]
      },
      {
        "text": "how can i change my  name",
        "intent": "inform",
        "entities": [
          {
            "start": 9,
            "end": 25,
            "value": " change my  name",
            "entity": "update name"
          }
        ]
      },
      {
        "text": "how can i edit my name in pims",
        "intent": "inform",
        "entities": [
          {
            "start": 10,
            "end": 22,
            "value": "edit my name",
            "entity": "update name"
          }
        ]
      },
      {
        "text": "what is the process for name update in pims",
        "intent": "inform",
        "entities": [
          {
            "start": 23,
            "end": 36,
            "value": " name update ",
            "entity": "update name"
          }
        ]
      },
      {
        "text": "how to login  ask HR",
        "intent": "inform",
        "entities": [
          {
            "start": 6,
            "end": 20,
            "value": " login  ask HR",
            "entity": "login ask hr"
          }
        ]
      },
      {
        "text": "process to login ask hr",
        "intent": "inform",
        "entities": [
          {
            "start": 10,
            "end": 23,
            "value": " login ask hr",
            "entity": "login ask hr"
          }
        ]
      },
      {
        "text": "what is the url for ask hr portal",
        "intent": "inform",
        "entities": [
          {
            "start": 12,
            "end": 26,
            "value": "url for ask hr",
            "entity": "login ask hr"
          }
        ]
      },
      {
        "text": "can you please help me with the web address of ask hr ",
        "intent": "inform",
        "entities": [
          {
            "start": 31,
            "end": 53,
            "value": " web address of ask hr",
            "entity": "login ask hr"
          }
        ]
      },
      {
        "text": "how to change the address",
        "intent": "inform",
        "entities": [
          {
            "start": 7,
            "end": 25,
            "value": "change the address",
            "entity": "update address"
          }
        ]
      },
      {
        "text": "I am recently moved, I want to update my address?",
        "intent": "inform",
        "entities": [
          {
            "start": 31,
            "end": 48,
            "value": "update my address",
            "entity": "update address"
          }
        ]
      },
      {
        "text": "i want to update my address",
        "intent": "inform",
        "entities": [
          {
            "start": 10,
            "end": 27,
            "value": "update my address",
            "entity": "update address"
          }
        ]
      },
      {
        "text": "address update",
        "intent": "inform",
        "entities": [
          {
            "start": 0,
            "end": 14,
            "value": "address update",
            "entity": "update address"
          }
        ]
      },
      {
        "text": "update address",
        "intent": "inform",
        "entities": [
          {
            "start": 0,
            "end": 14,
            "value": "update address",
            "entity": "update address"
          }
        ]
      },
      {
        "text": "change the address",
        "intent": "inform",
        "entities": [
          {
            "start": 0,
            "end": 18,
            "value": "change the address",
            "entity": "update address"
          }
        ]
      },
      {
        "text": "change address",
        "intent": "inform",
        "entities": [
          {
            "start": 0,
            "end": 14,
            "value": "change address",
            "entity": "update address"
          }
        ]
      },
      {
        "text": "change  my address",
        "intent": "inform",
        "entities": [
          {
            "start": 0,
            "end": 18,
            "value": "change  my address",
            "entity": "update address"
          }
        ]
      },
      {
        "text": "i want to edit my address",
        "intent": "inform",
        "entities": [
          {
            "start": 9,
            "end": 25,
            "value": " edit my address",
            "entity": "update address"
          }
        ]
      },
      {
        "text": "how do i update my contact number",
        "intent": "inform",
        "entities": [
          {
            "start": 9,
            "end": 33,
            "value": "update my contact number",
            "entity": "update number"
          }
        ]
      },
      {
        "text": "update contact number",
        "intent": "inform",
        "entities": [
          {
            "start": 0,
            "end": 21,
            "value": "update contact number",
            "entity": "update number"
          }
        ]
      },
      {
        "text": "how can i change my phone number",
        "intent": "inform",
        "entities": [
          {
            "start": 10,
            "end": 32,
            "value": "change my phone number",
            "entity": "update number"
          }
        ]
      },
      {
        "text": "how can i edit my phone number",
        "intent": "inform",
        "entities": [
          {
            "start": 9,
            "end": 30,
            "value": " edit my phone number",
            "entity": "update number"
          }
        ]
      },
      {
        "text": "update mobile number",
        "intent": "inform",
        "entities": [
          {
            "start": 0,
            "end": 20,
            "value": "update mobile number",
            "entity": "update number"
          }
        ]
      },
      {
        "text": "how to change mobile number",
        "intent": "inform",
        "entities": [
          {
            "start": 0,
            "end": 27,
            "value": "how to change mobile number",
            "entity": "update number"
          }
        ]
      },
      {
        "text": "edit number",
        "intent": "inform",
        "entities": [
          {
            "start": 0,
            "end": 11,
            "value": "edit number",
            "entity": "update number"
          }
        ]
      },
      {
        "text": "how do i update my number",
        "intent": "inform",
        "entities": [
          {
            "start": 9,
            "end": 25,
            "value": "update my number",
            "entity": "update number"
          }
        ]
      },
      {
        "text": "how can i update my photo",
        "intent": "inform",
        "entities": [
          {
            "start": 10,
            "end": 25,
            "value": "update my photo",
            "entity": "update photo"
          }
        ]
      },
      {
        "text": "how can i change my photo ",
        "intent": "inform",
        "entities": [
          {
            "start": 10,
            "end": 26,
            "value": "change my photo ",
            "entity": "update photo"
          }
        ]
      },
      {
        "text": "how can i change my photo",
        "intent": "inform",
        "entities": [
          {
            "start": 10,
            "end": 25,
            "value": "change my photo",
            "entity": "update photo"
          }
        ]
      },
      {
        "text": "i wonder is it possible to update my photo ",
        "intent": "inform",
        "entities": [
          {
            "start": 27,
            "end": 43,
            "value": "update my photo ",
            "entity": "update photo"
          }
        ]
      },
      {
        "text": "i found my pic not good i want to change",
        "intent": "inform",
        "entities": [
          {
            "start": 26,
            "end": 40,
            "value": "want to change",
            "entity": "update photo"
          }
        ]
      },
      {
        "text": "can i change my pic in pims",
        "intent": "inform",
        "entities": [
          {
            "start": 6,
            "end": 20,
            "value": "change my pic ",
            "entity": "update photo"
          }
        ]
      },
      {
        "text": "change my pic in pims",
        "intent": "inform",
        "entities": [
          {
            "start": 0,
            "end": 13,
            "value": "change my pic",
            "entity": "update photo"
          }
        ]
      },
      {
        "text": "can i update my emergency contact number",
        "intent": "inform",
        "entities": [
          {
            "start": 15,
            "end": 40,
            "value": " emergency contact number",
            "entity": "update emergency contact"
          }
        ]
      },
      {
        "text": "my manager asked me to update my emrgency contact details",
        "intent": "inform",
        "entities": [
          {
            "start": 22,
            "end": 50,
            "value": " update my emrgency contact ",
            "entity": "update emergency contact"
          }
        ]
      },
      {
        "text": "where do i need to change emergency contact details",
        "intent": "inform",
        "entities": [
          {
            "start": 19,
            "end": 44,
            "value": "change emergency contact ",
            "entity": "update emergency contact"
          }
        ]
      },
      {
        "text": "please help me on updating emergency contact details",
        "intent": "inform",
        "entities": [
          {
            "start": 18,
            "end": 52,
            "value": "updating emergency contact details",
            "entity": "update emergency contact"
          }
        ]
      },
      {
        "text": "how do we update emergency contact phone number",
        "intent": "inform",
        "entities": [
          {
            "start": 9,
            "end": 40,
            "value": " update emergency contact phone",
            "entity": "update emergency contact"
          }
        ]
      },
      {
        "text": "Where could I find details of my local HR",
        "intent": "inform",
        "entities": [
          {
            "start": 19,
            "end": 41,
            "value": "details of my local HR",
            "entity": "localhrdetails"
          }
        ]
      },
      {
        "text": "how can i get in touch with my local hr",
        "intent": "inform",
        "entities": [
          {
            "start": 31,
            "end": 39,
            "value": "local hr",
            "entity": "localhrdetails"
          }
        ]
      },
      {
        "text": "i wish if there is a easy way to get in touch with hr",
        "intent": "inform",
        "entities": [
          {
            "start": 50,
            "end": 53,
            "value": " hr",
            "entity": "localhrdetails"
          }
        ]
      },
      {
        "text": "local hr url ",
        "intent": "inform",
        "entities": [
          {
            "start": 0,
            "end": 13,
            "value": "local hr url ",
            "entity": "localhrdetails"
          }
        ]
      },
      {
        "text": "if have some important query can you tell me where can i connect to hr",
        "intent": "inform",
        "entities": [
          {
            "start": 57,
            "end": 70,
            "value": "connect to hr",
            "entity": "localhrdetails"
          }
        ]
      },
      {
        "text": "Could I view my Compensation/Salary History and generate last increment letters",
        "intent": "inform",
        "entities": [
          {
            "start": 16,
            "end": 79,
            "value": "Compensation/Salary History and generate last increment letters",
            "entity": "getpayroll"
          }
        ]
      },
      {
        "text": "could i view my compensation",
        "intent": "inform",
        "entities": [
          {
            "start": 16,
            "end": 28,
            "value": "compensation",
            "entity": "getpayroll"
          }
        ]
      },
      {
        "text": "can i view my salary slip",
        "intent": "inform",
        "entities": [
          {
            "start": 13,
            "end": 25,
            "value": " salary slip",
            "entity": "getpayroll"
          }
        ]
      },
      {
        "text": "can i view my salary history",
        "intent": "inform",
        "entities": [
          {
            "start": 14,
            "end": 28,
            "value": "salary history",
            "entity": "getpayroll"
          }
        ]
      },
      {
        "text": "can i generate my last increment letter",
        "intent": "inform",
        "entities": [
          {
            "start": 15,
            "end": 39,
            "value": "my last increment letter",
            "entity": "getpayroll"
          }
        ]
      },
      {
        "text": "where can i see last increment letter ",
        "intent": "inform",
        "entities": [
          {
            "start": 16,
            "end": 38,
            "value": "last increment letter ",
            "entity": "getpayroll"
          }
        ]
      },
      {
        "text": "Could I view my Compensation/Salary History",
        "intent": "inform",
        "entities": [
          {
            "start": 16,
            "end": 43,
            "value": "Compensation/Salary History",
            "entity": "getpayroll"
          }
        ]
      },
      {
        "text": "Could I view my Compensation and generate last increment letters",
        "intent": "inform",
        "entities": [
          {
            "start": 16,
            "end": 64,
            "value": "Compensation and generate last increment letters",
            "entity": "getpayroll"
          }
        ]
      },
      {
        "text": "Could I view my Compensation generate last increment letters",
        "intent": "inform",
        "entities": [
          {
            "start": 16,
            "end": 60,
            "value": "Compensation generate last increment letters",
            "entity": "getpayroll"
          }
        ]
      }
    ]
  }
}
```

i am trying to predict the intents and entities of the following below sentence using below mentioned command

from rasa_nlu.converters import load_data
from rasa_nlu.config import RasaNLUConfig
from rasa_nlu.model import Trainer
from rasa_nlu.model import Metadata,Interpreter

def train_nlu(data,config,model_dir):
    training_data= load_data(data)
    trainer=Trainer(RasaNLUConfig(config))
    trainer.train(training_data)
    model_directory=trainer.persist(model_dir,fixed_model_name="HRQueryNLU")


def run_nlu():
    interpreter= Interpreter.load('./models/nlu/default/HRQueryNLU',RasaNLUConfig('config_spacy.json'))
    print(interpreter.parse("can i change my pic in pims"))
    #print(interpreter.parse("were do i can update address"))

if __name__ == '__main__':
    #train_nlu('./data/data.json','./config_spacy.json','./models/nlu')
    run_nlu()
    


the console output is as below:
C:\Users\LVVS0613\Desktop\HR Chatbot>python nlu_model.py
{'intent': {'name': 'inform', 'confidence': 0.92155145399950622}, 'entities': [], 'intent_ranking': [{'name': 'inform', 'confidence': 0.92155145399950622}, {'name': 'bye', 'confidence': 0.059447472391960673}, {'name': 'greet', 'confidence': 0.019001073608533307}], 'text': 'can i change my pic in pims'}


Can you please tell me why rasa nlu is not able to predict the entities

**Comment by manojjjm** [comment]
Please respond to this ASAP as this is little urgent

**Comment by akelad** [comment]
Can you update your NLU version to the latest one please? 0.8 is super old, 0.13.1 is the up to date one

**Comment by manojjjm** [comment]
Yes it's already upgraded sorry for the wrong information

**Comment by manojjjm** [comment]
one question out of current context but little query

how does rasa support multi user dialogue management

**Comment by wrathagom** [comment]
Rasa NLU doesn't. You would need to implement your own solution, use [Rasa Core](https://github.com/RasaHQ/rasa_core), or some other Dialogue management tool. Rasa NLU just does intent/entity parsing.

**Comment by akelad** [comment]
Since the original question has been answered, I'll close this issue. If you have questions about Core, feel free to post in our [forum](https://forum.rasa.com)
