### ISSUE TITLE
RASA_NUL can use trained NER model?

### ISSUE THREAD

**Issue by GaoQ1** [RasaHQ/rasa_nlu#1340]
**Rasa NLU version**:

**Operating system** (windows, osx, ...):

**Content of model configuration file**:
```yml

```

**Issue**:
As the title, can rasa nlu use already trained NER model? And how to use? Thanks.

**Comment by amn41** [comment]
please post usage questions on the [forum](https://forum.rasa.com)

**Comment by akelad** [comment]
Since this has been moved to the forum, I'll close this issue.
