### ISSUE TITLE
entity extraction throws warning and not returning the entities with ner_crf

### ISSUE THREAD

**Issue by danazen** [RasaHQ/rasa_nlu#1345]
**Rasa NLU version**: 0.13.0

**Operating system** (windows, osx, ...): Ubuntu 16

**Content of model configuration file**:
language: "en"
pipeline: "tensorflow_embedding"

**Issue**:
when I try with this "please help me with the issue id inc-1505304194839" utterance and "inc-1505304194839" as entity, its throwing the below warning and not returning the extracted entity even though there is no trailing and ending space.

WARNING:rasa_nlu.extractors.crf_entity_extractor:Misaligned entity annotation in sentence 'please help me with the issue id inc-1505304194839'. Make sure the start and end values of the annotated training examples end at token boundaries (e.g. don't include trailing whitespaces).

**Comment by danazen** [comment]
One quick update: The same training data with the same synonyms and synonym variant worked very well with pipeline spacy_sklearn and ner_crf. But not working with tensorflow pipeline.

PFB the training data:

Help me resolve my issue inc-1505304194839
resolve issue inc-1505304194839
resolve issue inc-1505304194839 please
please help me resolve my issue inc-1505304194839
I need help to resolve my issue inc-1505304194839
resolve issue inc-1505304194839
please resolve my issue inc-1505304194839
resolve issue inc-1505304194839 for me
can you resolve my issue inc-1505304194839
need your help in resolveing the issue inc-1505304194839
would you be able to resolve the issue inc-1505304194839
can you help me resolve the issue inc-1505304194839
Begin again the issue inc-1505304194839
I want you to take care of inc-1505304194839 issue
make the issue inc-1505304194839 to be resolved
Hi bot, resolve the machine inc-1505304194839
Let's resolve the issue inc-1505304194839
hello, resolve the issue inc-1505304194839
Continue with the issue inc-1505304194839

Synonym: inc-1505304194839
Synonym Variants:
xxx-1
xxx-12
xxx-123
xxx-1234
xxx-12345
xxx-123456
xxx-1234567
xxx-12345678
xxx-123456789
xxx-1234567890
xxx-12345678901
xxx-123456789012
xxx-1234567890123

**Comment by akelad** [comment]
Thanks for raising this issue, @Ghostvv will get back to you about it soon.

**Comment by Ghostvv** [comment]
Could you please provide your training data in rasa format, so I could reproduce the issue

**Comment by mirfan899** [comment]
rasa-nlu==0.13.3

having same issue with sentences like `call dr. John Smith` which throws warning
`Misaligned entity annotation in sentence 'call dr. Nick Michaels'. Make sure the start and end values of the annotated training examples end at token boundaries (e.g. don't include trailing whitespaces or punctuation).`
training example:

```json
{
        "text": "call dr. Nick Michaels",
        "intent": "navigate.call",
        "entities": [
          {
            "start": 0,
            "end": 4,
            "value": "call",
            "entity": "command"
          },
          {
            "start": 5,
            "end": 8,
            "value": "dr.",
            "entity": "user_type"
          },
          {
            "start": 9,
            "end": 13,
            "value": "Nick",
            "entity": "doctor_name"
          },
          {
            "start": 14,
            "end": 22,
            "value": "Michaels",
            "entity": "doctor_lastname"
          }
        ]
      }
```

**Comment by akelad** [comment]
I believe you already created a new issue with this question, so i'm going to close this issue
