### ISSUE TITLE
Extra whitespace inserted by CRF entity extraction

### ISSUE THREAD

**Issue by Tpt** [RasaHQ/rasa_nlu#1347]
**Rasa NLU version**: 0.13.1 

**Issue**:

French Spacy tokenizers sometime splits tokens even if there is no whitespace. For example "test d'extraction" is going to be tokenized as ["text", "d'", "extraction"]. CRF entity extractor is joining the tokens with whitespaces so, for example if the entity "test d'extraction" is extracted, it is going to be returned as  "test d' extraction" with a space after "d'".

The piece of code that should be updated is: https://github.com/RasaHQ/rasa_nlu/blob/b3565f19a3031ec0b6202748d7180e3ad44571b9/rasa_nlu/extractors/crf_entity_extractor.py#L221

**Comment by akelad** [comment]
Thanks for raising this issue, @twhughes  will get back to you about it soon.

**Comment by twhughes** [comment]
@tpt Thanks for raising the issue.  So just to be clear would it be better if this was returned as `"test d'extraction"` if french is used?  Is this true generally for any apostrophe after words in french?

**Comment by Tpt** [comment]
Thank you for your feedback!

> So just to be clear would it be better if this was returned as "test d'extraction" if french is used?

Yes exactly.

> Is this true generally for any apostrophe after words in french?

It seems true for me. But it does not solve all edge cases like "c'est-à-dire" parsed as "c'" "est-", "à-", "dire" but it is probably not something that people would want to extract.

**Comment by twhughes** [comment]
It seems also like this is a more general issue, for example in English if 'what's up' my be returned as 'what' s up?' if it is tokenized the same way.  Will look into it but for the meantime, perhaps add the line

     value = value.replace("' ", "'")

if that solves the problem temporarily for you.

**Comment by Tpt** [comment]
I just checked. When the "pos" feature is enabled, the label is what is intended. Spaces are inserted only when the "pos" feature is not used.

Thank you for the tip.

**Comment by TheBear44** [comment]
This also cause a problem when tokenizing word with pythainlp.
The ner_crf joins the word back by adding space in it which will mess with synonyms.
