### ISSUE TITLE
how to get remaining entities if entity not extracted by ner_crf then return None

### ISSUE THREAD

**Issue by DeepakJangir4** [RasaHQ/rasa_nlu#1349]
if user_message is like :- "add reminder for birthday" then parsed sentence be like
```
{'intent': {'name': 'reminder', 'confidence': 0.7890547285867484}, 'entities': [{'start': 0, 'end': 3, 'value': 'add', 'entity': 'action', 'confidence': 0.7908196570499199, 'extractor': 'ner_crf'}, {'start': 4, 'end': 10, 'value': 'reminder', 'entity': 'tag', 'confidence': 0.6884967987186512, 'extractor': 'ner_crf', 'processors': ['ner_synonyms']}, {'start': 15, 'end': 23, 'value': 'birthday', 'entity': 'type', 'confidence': 0.8760218106577189, 'extractor': 'ner_crf'}], 'intent_ranking': [{'name': 'reminder', 'confidence': 0.7890547285867484}, {'name': 'quotes', 'confidence': 0.16370194851763384}, {'name': 'joke', 'confidence': 0.04724332289561807}], 'text': 'add reminder for birthday'}
{'action': 'add', 'tag': 'reminder', 'type': 'birthday'}
```
but any entity not present then how to represent that intent's entity as None?

**Comment by DeepakJangir4** [comment]
@akelad in above extraction i got {'action': 'add', 'tag': 'reminder', 'type': 'birthday'} for available entities as query requested, but query does't contain any entity i want that entity as None.
like this. if query is "add reminder" only then {'action': 'add', 'tag': 'reminder', 'type': None}

**Comment by akelad** [comment]
this is something you can do in a custom action then. So you have a story like:

```
* add_reminder{"tag":"reminder", "action":"add", "type":"birthday"}
  - action_store_reminder
```
And your `action_store_reminder` would only store the tag and action entities into a slot. You then have to name your slots different from your entities though, to avoid them being filled automatically. Or turn off that feature in your domain file.

Also I'm going to close this issue now, as it's more for our [forum](https://forum.rasa.com). If you have any more questions, please post them there
