### ISSUE TITLE
Calling a custom action instead of template to fill up formaction required field

### ISSUE THREAD

**Issue by vinayver198** [RasaHQ/rasa_nlu#1350]
**Rasa NLU version**:

**Operating system** (windows, osx, ...):

**Content of model configuration file**:
```yml

```

**Issue**:
Hi,

In my use case I am using formaction to fill up some slots.
Lets take example 
Bot : Do you want to buy something ?
User : Yes / No

Now here this yes / no i defined as utter_ask_confirm as template in my domain. It was working fine. But now I want to callup a custom action. So I made a action in my actions.py as utter_ask_confirm. But now when I am testing the bot. It returns Undefined utter template <utter_ask_confirm>. 

Can anyone help in this case ?

**Comment by akelad** [comment]
Please post this in the Core repo along with which Core version you're using etc
