### ISSUE TITLE
rasa docker image (latest-full) not working

### ISSUE THREAD

**Issue by subbu107** [RasaHQ/rasa_nlu#1353]
**Rasa NLU version**: latest-full

**Operating system** (windows, osx, ...): CentOs 7.2

**Content of model configuration file**:
```yml

```

**Issue**: 

I tried running the rasa docker container as follows : 

docker run -p 5555:5000 rasa/rasa_nlu:latest-full

However, the container simply exits instead of the server listening on the specified port. Am I doing something wrong ?

**Comment by wrathagom** [comment]
@subbu107 I just tested this with your exact command from above and the Rasa container does not exit. I am left with this on the command line:

```
2018-08-30 01:24:42+0000 [-] Log opened.
2018-08-30 01:24:42+0000 [-] Site starting on 5000
2018-08-30 01:24:42+0000 [-] Starting factory <twisted.web.server.Site object at 0x7fe67c50f5f8>
```

It may be possible it is something specific to CentOS, which I can't easily test. Can you test it on a new VM/other device to see if it is happening for you elsewhere. I'll try to get a Cent VM to test it on myself.

**Comment by StefanKock** [comment]
I'm having a similar problem which @subbu107 ran in:
**Rasa NLU version:** latest-full
**Operating system:** Ubuntu 16.04
**System:** VM virtualized with ESXi

When I tried to train Rasa while building the image, I ran into this problem:
```
./train-rasa-stack.sh: line 4:     8 Illegal instruction     (core dumped) python -m rasa_nlu.train -c nlu_model_config.json -d data/nlu.md --fixed_model_name current
./train-rasa-stack.sh: line 6:    19 Illegal instruction     (core dumped) python -m rasa_core.train -s data/stories.md -d domain.yml -o models/dialogue --epochs 300
ERROR: Service 'rasa-stack' failed to build: The command '/bin/sh -c ./train-rasa-stack.sh' returned a non-zero code: 132
```

On my research I tumbled through various links which pointed to Python and TensorFlow:
- An example: https://github.com/RasaHQ/live-gdrive-demo/issues/4

On my Windows PC the image does work:
```
docker run -p 5555:5000 rasa/rasa_nlu
docker exec -ti [container_id] bash
pip list | grep tensorflow
tensorflow       1.10.0
```

What cirumstances outside the docker image might have such impact? Memory, CPU, GPU?

**Comment by akelad** [comment]
Yes memory might have some effect on that. How much memory does the machine have?

**Comment by akelad** [comment]
can you monitor your memory when you start training though? It could very well be that those 4GB get used up

**Comment by StefanKock** [comment]
I did not really succeed to solve the problem, but memory does not seem to be an issue. But right now I changed to another docker host to avoid problems.
