### ISSUE TITLE
Evaluation to plot confidence histogram for hits and misses 

### ISSUE THREAD

**Issue by jmrf** [RasaHQ/rasa_nlu#1354]
Currently, the evaluation script (`evaluate.py`) plots a histogram of intent prediction confidences but does not differentiate between the confidences of those predictions that were right or wrong.

Potentially we could allow for an argument to allow plotting a histogram with two columns per bin showing the confidence distribution for hits and misses as different bars.
This would help to visualize how error confidences distribute when compared to correct prediction confidences.

If this is something that would be of interest I am happy to create a PR.

Something like this for example: 
![hist](https://user-images.githubusercontent.com/10252518/44818058-e30ee780-abe7-11e8-876d-67105950c100.png)

**Comment by akelad** [comment]
Yes this looks like a super useful improvement, please go ahead and create a PR and make sure to reference this issue when doing so 🙂

**Comment by jmrf** [comment]
Fantastic @akelad, thanks for your answer. Will do so!
