### ISSUE TITLE
Getting evaluation metrics from python API.

### ISSUE THREAD

**Issue by twhughes** [RasaHQ/rasa_nlu#1357]
Currently, if `rasa_nlu.evaluate` is run via command line, the evaluation metrics are printed by the logger. Ideally, we would like to be able to grab the evaluation metrics if, instead, functions in evaluate are called from the python API.

Proposed changes:

Have `run_evaluation()` and `run_evaluation_cv()` return dictionary of metrics that can be accessed when calling these functions via python script.

**Comment by twhughes** [comment]
moving to roadmap

**Comment by daniel-wer** [comment]
@twhughes Any way to follow the progress on this feature?
We would like to use the evaluation metrics as part of our tests to automatically assess the impact of changes.

**Comment by twhughes** [comment]
@daniel-wer I'm not working on this anymore.  However, one suggestion that you could implement in your fork of rasa_nlu is to change the `run_evaluation()` and `run_evaluation_cv()` functions to return these metrics.  Then, you can retrieve these from within a python script.  

If you want to strip these metrics out without changing rasa_nlu, you can take a look at this https://github.com/RasaHQ/rasa_lookup_demo/blob/master/run_lookup.py

Here I used a regex to strip the metrics from the logging output.. but I wouldnt recommend this as a long term solution.

hope this helps

**Comment by daniel-wer** [comment]
Thanks for the detailed response @twhughes, we'll make it work using one of these methods :)
