### ISSUE TITLE
How do I add an entity to an utterance?

### ISSUE THREAD

**Issue by jaggernaut07** [RasaHQ/rasa_nlu#1359]
**Rasa NLU version**: 0.9.8

**Operating system** (windows.):

**Content of model configuration file**:slots:
  weather_location:
    type: text
  news_subject:
    type: text
  data_query:
    type: text
  requested_slot:
    type: unfeaturized
  game_type:
    type: text
  movies_location:
    type: text
  movies_time:
    type: text
  movies_genre:
    type: text
  movies_actor:
    type: text
  movies_rating:
    type: text
  movies_language:
    type: text

intents:
 - greet
 - goodbye
 - movies
 - Hobby
 - Hobby_like
 - Hobby_fav
 - Hobby_labor
 - Hobby_topic
 - weather_inform
 - joke_inform
 - joke_feedback_bad
 - joke_feedback_good
 - news_inform
 - data_information

entities:
 - weather_location
 - news_subject
 - data_query
 - game_type 
 - like_music
 - like_interest
 - work_interest
 - music_play
 - movies_location
 - movies_time
 - movies_genre
 - movies_actor
 - movies_rating
 - movies_language

templates:
  utter_greet:
    - 'Hello! How are you?'
    - 'Hi'
    - 'Hello'
  utter_goodbye:
    - 'Talk to you later.'
    - 'Bye bye :)'
    - 'Ok bye'
    - 'Take care! bye'
    - 'Have a nice day! bye'
    - 'See you later! bye'
  utter_hobby:
    - 'That sounds like a fun way to spend your free time. How long have you been interested in {game_type}?'
  utter_ask_weather_location:
    - 'In what location?'
    - 'location?'
  utter_joke_feedback_bad:
    - 'Thanks for your feedback..! i will do better on the next'
  utter_joke_feedback_good:
    - 'Thank you'
  utter_ask_news_subject:
    - 'News subject?'
  utter_data_change:
    - 'Where are you from?'
    - 'Do you know Stars do not twinkle.'
  utter_default:
    - 'Default'

actions:
 - utter_default
 - actions.Fallback
 - utter_greet
 - utter_goodbye
 - utter_hobby
 - utter_ask_weather_location
 - utter_ask_news_subject
 - actions.ActionWeather
 - utter_joke_feedback_bad
 - utter_joke_feedback_good
 - actions.ActionJokes
 - actions.ActionNews
 - utter_data_change
 - actions.ActionData
 - actions.ActionHobby

```yml

## Story-1
* Hobby{"game_type":"cricket"}
    - slot{"game_type":"cricket"}
    - utter_hobby
    - export

```story

**Issue**:

Getting entity as None in bot response along with the utter hobby, instead of gametype

**Comment by wrathagom** [comment]
You need to train an NLU model using the Rasa NLU [training data format](https://rasa.com/docs/nlu/dataformat/). This is documented in the [Rasa Core quick start](http://rasa.com/docs/core/quickstart/#train-a-dialogue-model) as well.

Let us know if that doesn't get you going again.

**Comment by jaggernaut07** [comment]
I have also trained the using the blue trainer. My weather API with slots is working just fine. The problem I have is with the slot filling as a reply from the agent. I am trying to debug this by using actions. It still isn't working. 

I think the problem is write here below 

utter_hobby:
- 'That sounds like a fun way to spend your free time. How long have you been interested in {game_type}?'

**Comment by akelad** [comment]
Please ask these kind of questions in the [forum](https://forum.rasa.com)

**Comment by jaggernaut07** [comment]
Okay. The forum was down when I put this up here. Thanks
