### ISSUE TITLE
RASA交流

### ISSUE THREAD

**Issue by LyJss** [RasaHQ/rasa_nlu#1368]
为了方便大家交流学习，我建立了一个QQ群：439993256

**Comment by akelad** [comment]
I can't read Chinese, but I think this is an invitation to add you on WeChat or similar? Please post this in the [forum](https://forum.rasa.com) instead

**Comment by howl-anderson** [comment]
In Chinese: 为了更好的供中国地区的 Rasa 用户相互交流学习，Rasa 已经建立了一个官方 QQ 群：820037374。欢迎各位加入。

------

In English: For better communicate with each other in China, Rasa already set up an official QQ group: 820037374.

PS: @akelad sorry, I had to update the news in this thread in case they don't read the announcement from the forum. I posted the announcement AT https://forum.rasa.com/t/rasa-qq-820037374-rasa-already-set-up-an-official-qq-group-820037374/1043
