### ISSUE TITLE
Dialog to Dialog set up

### ISSUE THREAD

**Issue by Frackup** [RasaHQ/rasa_nlu#1369]
**Rasa NLU version**: 0.13.2

**Operating system** (windows, osx, ...): windows 10

**Content of model configuration file**:
language: "fr"

pipeline:
- name: "nlp_spacy"                   # loads the spacy language model
- name: "tokenizer_spacy"             # splits the sentence into tokens
- name: "ner_crf"                   # uses the pretrained CRF NER model
- name: "intent_featurizer_spacy"     # transform the sentence into a vector representation
- name: "intent_classifier_sklearn"   # uses the vector representation to classify using SVM

**Issue**:
Hi,

I just wanna know how we can jump from a dialog to another one, to be able, depending of a context, to use different distinct dialogs.

**Comment by akelad** [comment]
Please post these kind of questions in our [forum](https://forum.rasa.com). With some additional information as well, because i'm not sure what you mean
