### ISSUE TITLE
how to call evaluate

### ISSUE THREAD

**Issue by zhaoyueplc** [RasaHQ/rasa_nlu#1370]
i have a test.

train with project project=test_model: 

```
curl --request POST --header ‘content-type: application/x-yml’ -d@- --url ‘localhost:5004/train?project=test_model’
```

use the model generated in step 1 : model_20180910-080232 to evaluate : 

```
curl -XPOST localhost:5004/evaluate?project=test_model&model=model_20180910-020832 -d @demo-rasa.json | python -mjson.tool
```

the error pops up:

```
{ “error”: “Unknown data format for file /tmp/tmp7ddx9cmp_training_data” }-d: command not found No JSON object could be decoded [1]+ Done curl -XPOST localhost:5004/evaluate?project=test_model
```

**Comment by wrathagom** [comment]
the endpoint isn't evaluate it is `/parse`. https://rasa.com/docs/nlu/http/

Let me know if that doesn't solve your issues.

**Comment by zhaoyueplc** [comment]
I would like to use the evaluate http call: curl -XPOST localhost:5004/evaluate?project=test_model&model=model_20180910-020832 -d @demo-rasa.json | python -mjson.tool

Could you help show me a example to use the evaluate call with the parameter "project " and "model"?

**Comment by zhaoyueplc** [comment]
yes , the model model_20180910-020832 was generated by  
curl --request POST --header ‘content-type: application/x-yml’ -d@- --url ‘localhost:5004/train?project=test_model’

**Comment by akelad** [comment]
@zhaoyueplc did that suggestion help or are you still getting an error?

**Comment by zhaoyueplc** [comment]
yes, still have this error. Can you leave me  a example to use  https://rasa.com/docs/nlu/http/#post-evaluate

**Comment by akelad** [comment]
there's an example in the link you posted. What was the output of the training curl request you posted? Because it doesn't look right

**Comment by zhaoyueplc** [comment]
The train CURL was right and output a model:model_20180910-080232.   Could help test it and send me a example ?

The command used in my test:
config_train_server_md.yml from 
wget 'https://raw.githubusercontent.com/RasaHQ/rasa_nlu/master/sample_configs/config_train_server_md.yml'

Train:
curl --request POST --header ‘content-type: application/x-yml’ -d@- --url ‘localhost:5004/train?project=test_model’

Evaluate:
curl -XPOST localhost:5004/evaluate?project=test_model&model=model_20180910-020832 -d @demo-rasa.json | python -mjson.tool

**Comment by akelad** [comment]
what are the contents of that model directory?

**Comment by zhaoyueplc** [comment]
the same directory as i run curl

**Comment by akelad** [comment]
But what is in the model directory? please post what `ls` shows
