### ISSUE TITLE
Entity is none

### ISSUE THREAD

**Issue by varshakirani** [RasaHQ/rasa_nlu#1374]
**Rasa NLU version**: 0.13.2
**Rasa Core version**: 0.11.3
**Python version**: 3.6.6

**Operating system**: macOS High Sierra

**Issue**:
I am new to rasa stack. I have an entity **role_type** of type text used with three intents: job_technical, job_business and job_any. Below is the snapshot of few of the stories.
![image](https://user-images.githubusercontent.com/3057235/45378519-f1083380-b5fd-11e8-9b50-c2f65ecbc33b.png)

After training rasa_core and rasa_nlu, the intents with high confidence has empty entities. Because of this I am not able to set the slot.
![image](https://user-images.githubusercontent.com/3057235/45378633-4f351680-b5fe-11e8-85fd-0ce668b5332c.png)

Slots can be set from the action dispatcher but not from the user intent. 
Can someone help me with this? 

Thanks,
Varsha

**Comment by akelad** [comment]
Please ask these kind of questions in our [forum](https://forum.rasa.com). You likely don't have enough training data
