### ISSUE TITLE
Need a clarification

### ISSUE THREAD

**Issue by prasanth55555** [RasaHQ/rasa_nlu#1375]
hi,
  am new to rasa_nlu am bulting a bot where it takes values that are dynamic i want the dynamic value to be captured by an entity 

examples:
with notes  please {  bring your college marksheets }
with notes  please { come prepared }

where the string inside braces are dynamic values i need to capture them and make use of them...suggest me a way..

Thank you in advance

**Comment by akelad** [comment]
Please ask these kind of questions in our [forum](https://forum.rasa.com)
