### ISSUE TITLE
Assignment of same value for multiple entities.

### ISSUE THREAD

**Issue by vinayver198** [RasaHQ/rasa_nlu#1376]
**Rasa NLU version**:

**Operating system** (windows, osx, ...):

**Content of model configuration file**:
```yml

```

**Issue**:
Hi,
I will explain my issue with example.
Suppose two intents I am having.
* Confirmation.Yes
     -Yes
     - Sure
     - Ok

* Confirmation.No
      - No
      - Nopes
      - Noooo

I have labelled the utterances as entity "confirm" and "confirm_again".

So , while running an action, and entering yes or no only confirm entity is set not confirm_again. and also I am having two slots, confirm and confirm_again.Why?
According to me both entities should be set. Any help ?

Thanks

**Comment by akelad** [comment]
Please post these kind of questions on our [forum](https://forum.rasa.com)
