### ISSUE TITLE
Unable to list model from persistor while using AWS S3

### ISSUE THREAD

**Issue by ritikanigam** [RasaHQ/rasa_nlu#1379]
**Rasa NLU version**: 0.13.0

**Operating system** (windows, osx, ...): OSX

**Content of model configuration file**:
```yml
language: en
pipeline: tensorflow_embedding
```

**Issue**: I am trying to load models from AWS S3, my trained data is placed in <s3-bucket>/models/current/data and my call looks like below:

http://localhost:5005/parse?query=<sample_question>&project=current&model=data.

The same model files work locally for me. 

FYI: On starting the server I can see all the content of the buckets. I am facing the problem at:

```python
def list_models(self, project):
        print("AWS pers.. list models")
        # type: (Text) -> List[Text]
        print(project)
        try:
            prefix = self._project_prefix(project)
            return [self._project_and_model_from_filename(obj.key)[1]
                    for obj in self.bucket.objects.filter(Prefix=prefix)]
        except Exception as e:
            logger.warn("Failed to list models for project {} in "
                        "AWS. {}".format(project, e))
            return []
```

in class AWSPersistor(Persistor)

Can anyone tell me whats wrong and why do we use prefix here?

**Comment by akelad** [comment]
Can you please format the code so it's in a legible format? Also, could you post the full error you're getting?

**Comment by ritikanigam** [comment]
@akelad I have updated my question above to get code in correct format.

Also this is the error I get:
```
2018-09-13 18:05:40 WARNING  rasa_nlu.project - Invalid model requested. Using default
```

when I try to access the S3 bucket and my data models are placed in 
<bucket>/models/current/data. Basically it doesn't find my model and fallback to default. I thought the structure of the models on S3 should be similar to the one when I have my models in local directory.

**Comment by careless25** [comment]
I am facing the same issue. Can someone write better documentation for this? Or anyone have experience working with S3?
