### ISSUE TITLE
Contextual Intent Classification

### ISSUE THREAD

**Issue by parthsharma1996** [RasaHQ/rasa_nlu#1388]
Currently `rasa_nlu` provides intent classification on a sentence-by-sentence basis. i.e a single user utterance is assigned an intent.

However, such a model is insufficient in any sufficiently complex dialog agent, since the same sentence can mean different things in different contexts. A simple example in the use case of a Mood Tracker bot would be

> okay

which can mean `confirmation` or `neutral_feeling` depending on the context. This creates a problem for a dialog manager using a simple finite state machine model, since the action is simply dependent on the previous intent and current state.

Now, I am aware of [Rasa Core](https://rasa.com/docs/core/)  (which uses an approach similar to [Hybrid Code Networks](https://arxiv.org/abs/1702.03274)), which would allow the agent to take different actions following the same intent, based on the context of the conversation. 

However, due to the nature of our use case and lack of training data, we would like to stick to a more predictable finite state model.  

Is there a possibly of contextual intent classification being implemented in `rasa_nlu` based on something like [this paper](http://giusepperizzo.github.io/publications/Mensio_Rizzo-HQA2018.pdf)? It uses an RNN to also include the previous user and bot utterances in intent classification.

I would be happy to contribute to the development of such a feature. However, it would be hard for me to completely implement the feature on my own. 

What are everyone else's thoughts on this?

**Comment by parthsharma1996** [comment]
We are trying to build a mental health chat bot to accompany our website which delivers Cognitive Behavioral Therapy for depressed individuals.

We had experimented with Rasa Core initially. However we chose to switch to the FSM based approach due to the following reasons:-

1. The bot simply wasn't performing as well as expected, especially in longer conversations. Maybe data was the bottleneck? But we currently do not have any training data as such and there doesn't seem to be easy way to get a lot of it currently. Any ideas in this regard would be helpful.

2. Because our users are individuals suffering from depression, we are especially concerned about the bot not replying something that would appear insensitive in an unforeseen situation (as a result of the DM being stochastic).  Also in cases such as suicide ideation, we need to ensure that the bot responds in a certain way ( i.e directing users towards the relevant immediate resources like a suicide prevention hotline, sending our team an alert and so on). We would like that to be completely deterministic. 

3. The Chatbot's content is also structured and needs some certain rules. e.g. We want some things to be delivered periodically, Some content to be unlocked after a certain conditions are met, Transition between different content modules based on some conditions and so on.  

Therefore we chose to stick to the Finite State Model. Of course, It's not scalable but our hope once we can deploy a bare minimum bot we can bootstrap from the data acquired to introduce some flexibility using an ML model.

**Comment by ctrado18** [comment]
That is actually a typical situation when you develop a chatbot. Sometimes you want a specific intent in specvific situation. So it would be nice to somehow force it to a wanted intent. https://forum.rasa.com/t/force-user-message-to-a-specific-intent-for-slot-filling/954/2 @akelad ?

**Comment by akelad** [comment]
I mean, we have no immediate plans to implement context based intent classification. But we'd be interested in seeing your results if you implement one!
Could you explain what exactly was going wrong when you were using Rasa Core? We're also working on an improved version of our [FormActions](https://rasa.com/docs/core/slotfilling/#slot-filling-with-a-formaction), which will allow some more rule based behaviours. Would that solve some of your problems do you think?

**Comment by akelad** [comment]
Hmm, the lack of data shouldn't be a huge issue with the new FormActions, you just need to write a few stories. I'd say it's definitely worth trying 
I don't know about how far along the process you and your team are, but maybe the [Rasa Platform](https://rasa.com/products/rasa-platform/) might be of use to you? It enables you to collect NLU training data and stories from users to improve your bot too

**Comment by genglinxiao** [comment]
I know this is closed. I would like to share my opinion on this:
1. Intentions are naturally context dependent. The same sentence will result in exactly the same intent is a false assumption.
2. It is true that Rasa Core can handle context. Achieving the same result using Rasa Core means we have to have something like a "real_intent" defined in intent handling. This "real_intent" will be based on the intent returned by Rasa NLU.
3. Rasa Core might not have all the data needed to determine the real_intent. For example, if a message with a specific intent is repeated, then we should probably return a "teasing_intent". However, we don't have the previous message in Sara Core for comparison.
Of course, there are ways to circumvent, but I see contextual intent classification as the most natural/straightforward solution.
