### ISSUE TITLE
The running in Docker documentation needs to be fixed

### ISSUE THREAD

**Issue by yellowiscool** [RasaHQ/rasa_nlu#1390]
Hei,

[The documentation about how to run rasa_nlu in Docker needs to be fixed.](https://rasa.com/docs/nlu/master/docker/)

The command `docker run rasa/rasa_nlu:latest-full -p5000:5000` is not a valid Docker command. The [documentation in Docker hub](https://hub.docker.com/r/rasa/rasa_nlu/#advanced-docker) provides a valid command : `docker run -p 5000:5000 rasa/rasa_nlu:latest-full`. However it does not run : 

```
docker run -p 5000:5000 rasa/rasa_nlu:latest-full rasa_nlu.server
Available options:
 start commands (rasa cmd line arguments)  - Start RasaNLU server
 download {mitie, spacy en, spacy de}      - Download packages for mitie or spacy (english or german)
 start -h                                  - Print RasaNLU help
 help                                      - Print this help
 run                                       - Run an arbitrary command inside the container
```

**Comment by akelad** [comment]
You should only be running this part of the command `docker run -p 5000:5000 rasa/rasa_nlu:latest-full`

**Comment by yellowiscool** [comment]
The container exists immediately. It's maybe a normal behaviour, but by reading the documentation I was expecting some kind of example.

**Comment by yellowiscool** [comment]
Ok, My issue is most likely related to TensorFlow being compiled with an instruction set which is not supported by the CPU of my server. Explaining why it does crash immediately.

If I start it manually (using ` docker run -it -p 5000:5000 rasa/rasa_nlu:latest-full run bash`) I can see a TensorFlow error:

```
$ python -m rasa_nlu.server --path /app --debug
2018-09-18 08:09:51 INFO     rasa_nlu.data_router - Logging of requests is disabled. (No 'request_log' directory configured)
Illegal instruction (core dumped)
```

**Comment by akelad** [comment]
We'd be happy to accept a PR for these docs changes
