### ISSUE TITLE
utf-8 error when we are passing some unicode symbols like £,$, etc

### ISSUE THREAD

**Issue by jayantrajwani** [RasaHQ/rasa_nlu#1392]
**Rasa NLU version**: 0.13.2

**Operating system** (windows, osx, ...): windows

**Content of model configuration file**: json
{
"language":"en",
"pipeline":"tensorflow_embedding",
"data":{

"rasa_nlu_data":{
"common_examples":[
{
"text":"Verification of Insurance We hereby certify that the following liability insurance is in force at this date. Certificate Number: AO415/04658791/2011/015 1. Name of Insured: Envitek Info. 2. Period of Insurance 2nd August 2011 to 1st August 2012 3. Liability: £ 10,000,000 4. Public Liability: £ 2,000,000 5. Insurer: Jayant Corporation PVT LTD This document is furnished as a matter of information only. The issuance of this document does not make the person or organisation to whom it is issued an additional insured, nor does it modify in any manner the contract of insurance between the insured and the Underwriters. Should the above mentioned contract of insurance be cancelled, assigned or charged during the policy period mentioned above in such as to affect this document, no obligation to inform the holder of this document is accepted by the undersigned or by the Underwriters. Dated this 2nd day of August 2011 Signed for and on behalf of As per the policy wording subscribing to the above policy (Authorised Insurers)",
"intent":"insurance one",
"entities":[
{
"start":210,
"end":225,
"value":"2nd August 2011",
"entity":"From Date"
},
{
"start":293,
"end":304,
"value":"£ 2,000,000",
"entity":"Public Liability"
},
{
"start":259,
"end":271,
"value":"£ 10,000,000",
"entity":"Liability"
},
{
"start":229,
"end":244,
"value":"1st August 2012",
"entity":"To Date"
}
]}]
}
}}

**Issue**: On passing Unicode character it converts to utf-8 format and gives error following which it gets stuck.

**Comment by akelad** [comment]
Thanks for raising this issue, @Ghostvv will get back to you about it soon.

**Comment by Ghostvv** [comment]
Thank you for raising an issue, could you pease provide a Traceback?

**Comment by jayantrajwani** [comment]
Hi @Ghostvv ,
I'm not aware where to find the traceback. Can you please guide me.
Thanks

**Comment by Ghostvv** [comment]
But, where do you se an error?

**Comment by jayantrajwani** [comment]
Hi @Ghostvv 

I am getting that error on console when calling through http api.
Here is a screenshot of the traceback you are looking for.

![image](https://user-images.githubusercontent.com/11351528/45808375-4a99ed80-bce3-11e8-8149-1d801838b25b.png)

Regards
Jayant

**Comment by jayantrajwani** [comment]
![image](https://user-images.githubusercontent.com/11351528/45810715-e24e0a80-bce8-11e8-929a-d1ec1272c461.png)

**Comment by ricwo** [comment]
@jayantrajwani what is the exact command you're using to `POST` the file to the server?

**Comment by ricwo** [comment]
@jayantrajwani python version are you running?

I'm not able to reproduce your error with the data you posted. it could also be a problem related to your editor you're using to save the file. which editor are you using?

You could try to `POST` the json directly instead of referring to a file with
```
curl -XPOST -H "Content-Type: application/x-json" "0.0.0.0:5000/train?project=my_project" --data '{                                                                                                       7 ↵  8405  08:54:22
  "pipeline": "tensorflow_embedding",
  "language" : "en",
        "data": {
  "rasa_nlu_data": {
    "common_examples": [
      {
        "text": "(...)",
        "intent": "insurance one",
        "entities": [
          {
            "start": 210,
            "end": 225,
            "value": "2nd August 2011",
            "entity": "From Date"
          },
          {
            "start": 293,
            "end": 304,
            "value": "£ 2,000,000",
            "entity": "Public Liability"
          },
          {
            "start": 259,                                                                                                                                                                                                               <....
{
  "info": "new model trained: model_20180921-085429"
}%
```

**Comment by jayantrajwani** [comment]
Hi @ricwo ,
On our machines also it is working on some machines and not on others,
from python it is working fine, but it seems like http api has some issues in training. We were also able to evaluate through the http server.

**Comment by ricwo** [comment]
@jayantrajwani have you resolved the error?

**Comment by kapilkathuria** [comment]
@jayantrajwani is your training data file saved in UTF-8 format? if not, try saving this in UTF-8 format.

**Comment by akelad** [comment]
Given there's been no response from the original author, i'll close this issue for now. @jayantrajwani if you're still having problems with this, feel free to reopen the issue
