### ISSUE TITLE
Chinese Tensoflow Embedding 

### ISSUE THREAD

**Issue by samho1028** [RasaHQ/rasa_nlu#1400]
Has anyone tried using the tensorflow embedding pipeline for Chinese? 

 if I use the below configuration file setting, would it still work? (please note: i do not need entity recognition)

language: "zn"

pipeline: "tensorflow_embedding"

i assume it is using the spacy tokenizer in the backend right?

Thanks

**Issue**:

**Comment by akelad** [comment]
it's using a whitespace tokenizer. Could you post this question on the [forum](https://forum.rasa.com) there please? We have a Chinese community as well, I'm sure someone will be able to give you some advice on the forum
