### ISSUE TITLE
On training large data set the response from HTTP API is "Object reference not set to an instance of an object."

### ISSUE THREAD

**Issue by jayantrajwani** [RasaHQ/rasa_nlu#1403]
**Rasa NLU version**: 0.13.2

**Operating system**: windows

**Content of model configuration file**: json

**Issue**:
The response from HTTP API is "Object reference not set to an instance of an object."
This happens when you try to train large training data.. 
Though I noticed that the training is happening in the back and after some time the model is getting trained and is working.

![image](https://user-images.githubusercontent.com/11351528/45817640-087da580-bcfd-11e8-8557-42cad505d8af.png)

**Comment by akelad** [comment]
Thanks for raising this issue, @ricwo  will get back to you about it soon.

**Comment by ricwo** [comment]
@jayantrajwani how large is the training file you're using (in kb and # of examples)? I'll try to reproduce the error and will get back to you about this

**Comment by jayantrajwani** [comment]
Hi @ricwo ,
Can you please share your email id so i can share with you the training data we are trying to use.

**Comment by ricwo** [comment]
> Can you please share your email id so i can share with you the training data we are trying to use.

@jayantrajwani please check your email
