### ISSUE TITLE
NER_CRF with spacy for pos feature?

### ISSUE THREAD

**Issue by ctrado18** [RasaHQ/rasa_nlu#1404]
NLU: 13.1

It is from docs not clear how what to do if you just want the POS feature for CRF. I assumed this here:

```
language: "de_core_news_sm"

pipeline:
- name: "nlp_spacy"
- name: "intent_featurizer_count_vectors"
- name: "intent_classifier_tensorflow_embedding"
- name: "tokenizer_whitespace"
- name: "ner_crf"
```

So just added the `nlp_spacy`.
 Then:

```
    return message.get("tokens")[i].get("pattern", {})
IndexError: list index out of range

```
I assume tghis comes from that just `tokens` and not `spacy_doc` is required?!

**Comment by akelad** [comment]
if you want to use pos tags, you'd need to actually list that feature in the `ner_crf` config in that file (for reference: https://rasa.com/docs/nlu/components/#ner-crf). Also use the `tokenizer_spacy`, rather than `tokenizer_whitespace`. 
Let me know if that works

**Comment by ctrado18** [comment]
Up to now I configured directly the features inside the crf_entity.py inside the default features. Weren't there not recognized now or is this only true for POS feature?

**Comment by ctrado18** [comment]
It is not working:

```
in _sentence_to_features
    value = self.function_dict[feature](word)
KeyError: 'upper"'

```
I assume that the new crf feature are not for spacy pipeline?
```
pipeline:
- name: "nlp_spacy"
- name: "intent_featurizer_count_vectors"
- name: "intent_classifier_tensorflow_embedding"
- name: "tokenizer_spacy"
- name: "ner_crf"
  "features": [
            ["prefix5", "prefix2", "suffix3",
             "suffix2", "title", "upper"],
            ["bias", "pos", upper", "title", "digit", "pattern"],
            ["prefix5", "prefix2", "suffix3",
             "suffix2", "title", "upper"]]
```

**Comment by akelad** [comment]
`"pos", upper", "title",` you're missing a quotation mark around upper

**Comment by ctrado18** [comment]
whoops. That's bad. Any way, does it matter if you use tokenizer_whitespace or the spacy one? I like the new agnostic CRF just need the Pos feature. I don't know if a complete new crf pipeline is used depending if you spacy or not...

**Comment by ctrado18** [comment]
Does the nlp_spacy pipeline influence my rest of pipelines? Do I really have to use the spacy tokenizer? Since I am interested to use the tensorflow embedding pipeline I hope this is not influenced by spacy anyhow?

**Comment by akelad** [comment]
well, if you need the POS feature, you need spacy, since that's what assigns POS tags. Whether you use the spacy tokenizer or the whitespace tokenizer doesn't really make a difference though. Can I ask why you need the POS feature?

**Comment by ctrado18** [comment]
I want test CRF because I think it will be more accurate for unseen words.

**Comment by ctrado18** [comment]
Why is nlp_spacy trained?

`INFO:rasa_nlu.model:Starting to train component nlp_spacy`

So the doc from spacy is not confused with doc from tensorflow pipeline?

**Comment by akelad** [comment]
Actually yeah sorry, please use the spacy tokenizer with the `nlp_spacy` pipeline

**Comment by ctrado18** [comment]
And why is the nlp spacy component trained? I have not looked into the sapcy tokenizer yet but I hope this is not interacting somehow with the tensorflow pipeline? Because the whitespace tokenizer is better for tensorflow embedding right?

**Comment by akelad** [comment]
it is interacting with the tensorflow pipeline, the words need to be tokenized somehow. It shouldn't negatively affect the classification though. If you don't want to use spacy, then don't use POS tags as features

**Comment by ctrado18** [comment]
Ok thanks. Would it be more complicated to add just the POS feature from another source like my own? Or is it enough to modify j the doc?

**Comment by akelad** [comment]
What do you mean? If you want to use the POS feature, why not just use spacy?

**Comment by akelad** [comment]
Then use the `ner_crf` without the POS feature. Or you can also build a custom component for this if you like. I'm going to close this issue now as it's more of a discussion, if you want to discuss this further please post in our forum

**Comment by adityasingh1993** [comment]
can we use pattern feature with tensorflow_embedding
