### ISSUE TITLE
Misaligned entity annotation in sentence

### ISSUE THREAD

**Issue by ctrado18** [RasaHQ/rasa_nlu#1407]
**Rasa NLU version**: 0.13.1

**Operating system** (windows, osx, ...):

**Content of model configuration file**:
```
language: "de_core_news_sm"

pipeline:
- name: "intent_featurizer_count_vectors"
- name: "intent_classifier_tensorflow_embedding"
- name: "tokenizer_whitespace"
- name: "ner_crf"

```

**Issue**:

I I get the misaligned entity annotation warning although I checked that start and end positions are correct. It seems the issue arises from the comma and punctuation in sentences like:

`I want to buy an apple, how can you help me` and apple is entity. 

The comma seems to be extra tokenized such that one additonal whitespace is inlcuded as you can see from warning:

`Misaligned entity annotation in sentence 'I want to buy an apple , how can you help me'. Make sure the start and end values of the annotated training examples end at token boundaries (e.g. don't include trailing whitespaces or punctuation).`

Is this expected beahviour? So you cannot use commas in training data?

**Comment by akelad** [comment]
How have you annotated it?

**Comment by ctrado18** [comment]
What you mean? With chatito...

**Comment by ctrado18** [comment]
Update I run eval in debug mode and get:

`2018-09-24 15:02:24 DEBUG    rasa_nlu.extractors.crf_entity_extractor  - Inconsistent BILOU tagging found, B- tag, L- tag pair encloses multiple entity classes.i.e. [B-a, I-b, L-a] instead of [B-a, I-a, L-a].
Assuming B- class is correct.`

I have used chatito with mixed one and two word entities...I hope not that you to BILOU tag yourself?

**Comment by akelad** [comment]
please post the training data excerpt where that first warning was generated

**Comment by ctrado18** [comment]
I found my problem. I used accidentally twice my stemmer for the training data such that some words are get stemmed twice... Now there are no warning and everything seems fine. Thank you for your time @akelad ! 😄

**Comment by mirfan899** [comment]
rasa-nlu==0.13.3

having same issue with sentences like `call dr. John Smith` which throws warning
`Misaligned entity annotation in sentence 'call dr. Nick Michaels'. Make sure the start and end values of the annotated training examples end at token boundaries (e.g. don't include trailing whitespaces or punctuation).`
training example:

```json
{
        "text": "call dr. Nick Michaels",
        "intent": "navigate.call",
        "entities": [
          {
            "start": 0,
            "end": 4,
            "value": "call",
            "entity": "command"
          },
          {
            "start": 5,
            "end": 8,
            "value": "dr.",
            "entity": "user_type"
          },
          {
            "start": 9,
            "end": 13,
            "value": "Nick",
            "entity": "doctor_name"
          },
          {
            "start": 14,
            "end": 22,
            "value": "Michaels",
            "entity": "doctor_lastname"
          }
        ]
      }
```
