### ISSUE TITLE
No EntityRecognition Evalution

### ISSUE THREAD

**Issue by JoeTorino** [RasaHQ/rasa_nlu#1413]
I am trying to compare two models when applying lookUpTables to see the difference in terms of Entity Recognition however when I run the code

"""evaluate_model('data/nlu_testdata.md', 'models/current/nlu_model/prova/default/SDT_WithLookup/')

evaluate_model('data/nlu_testdata.md', 'models/current/nlu_model/prova/default/SDT_WithoutLookup/')"""

it runs showing me information on Intent Classification but nothing on Entity Recognition.
I checked to see if my test data was lacking any entity examples and found they were there.

**Comment by akelad** [comment]
Where is this `evaluate_model` function coming from? this doesn't exist in Rasa NLU. 
Also, please fill out the issue template when creating an issue
