### ISSUE TITLE
crossvalidation warnings

### ISSUE THREAD

**Issue by terweh** [RasaHQ/rasa_nlu#1415]
**Rasa NLU version**: 0.13.2

**Operating system** (windows, osx, ...): unix

**Issue**: When running `python -m rasa_nlu.evaluate --crossvalidation` many warnings of the following format are produced:
```
.../rasa_nlu/training_data/training_data.py:187: UserWarning: Intent 'some_intent_name' has only 1 training examples! Minimum is 2, training may fail.
```
The warning does appear, only before the teting fold is declared with:
```
2018-09-25 10:38:26 INFO     rasa_nlu.training_data.training_data  - Training data stats: 
	- intent examples: 105 (95 distinct intents)
	- Found intents: 
...
```
Is this simply due to the way of reading in the data or is this an actual issue?

OVERVIEW:
```
2018-09-25 10:38:26 DEBUG    __main__  - Fold: X
2018-09-25 10:38:26 DEBUG    rasa_nlu.training_data.training_data  - Validating training data...
2018-09-25 10:38:26 INFO     rasa_nlu.training_data.training_data  - Training data stats: 
	- intent examples: 897 (110 distinct intents)
	- Found intents: 'some_intent_name', 'some_other_intent_name', ...
    ...

2018-09-25 10:38:26 DEBUG    rasa_nlu.training_data.training_data  - Validating training data...
(...)/rasa_nlu/training_data/training_data.py:187: UserWarning: Intent 'some_intent_name' has only 1 training examples! Minimum is 2, training may fail.
(...)/rasa_nlu/training_data/training_data.py:187: UserWarning: Intent 'some_other_intent_name' has only 1 training examples! Minimum is 2, training may fail.
...
2018-09-25 10:38:26 INFO     rasa_nlu.training_data.training_data  - Training data stats: 
	- intent examples: 105 (95 distinct intents)
	- Found intents: 'some_intent_name', 'some_other_intent_name', ...
    ...

2018-09-25 10:38:26 INFO     rasa_nlu.model  - Starting to train component
2018-09-25 10:38:33 INFO     rasa_nlu.model  - Finished training component.
```

**Comment by akelad** [comment]
It's an issue, how many examples do you have for this intent? You need to have at least two examples per intent

**Comment by terweh** [comment]
I have at least 5 examples per intent. Mostly 10 sometimes up to 18.
But if i have e.g. a fold of 5 I should for each fold have 4 examples in the training set, if i understand it correctly, but then i will get for each fold a warning.

**Comment by akelad** [comment]
so the thing is it will randomly select 80% of your training data, not 80% of each intent. That's why you're getting a warning. My suggestion is, add more training data. 5 is definitely too few anyways

**Comment by nkrot** [comment]
Hi

I think this behaviour
> so the thing is it will randomly select 80% of your training data, not 80% of each intent.

is not correct. Selecting 80% of *all* data may leave some intents w/o training data at all. Consequently, testing intent recognition for an intent without training samples will naturally result in misrecognition of the intent, wrong figures and wrong understanding of the situation. The developer will be tempted to fix problem that does not exist. In my opinion, the second approach, namely selecting 80% of *each* intent, is fair and more appropriate.
