### ISSUE TITLE
Pickling issue

### ISSUE THREAD

**Issue by k-koehler** [RasaHQ/rasa_nlu#1418]
**Rasa NLU version**:

0.13.2

**Operating system** (windows, osx, ...):

Ubuntu

**Issue**:

In my current workflow, I am training RASA on a p3 instance on Amazon AWS, taking the pickle files, uploading them onto an S3, and then using those files to load the model on production. I am experiencing an issue where RASA will happily load the pickle files, but when I call `parse`, it crashes. Very bizarrely, however, when I replace the new `intent_featurizer_count_vectors.pkl` with an old version, it suddenly works...

Some more information: I removed the `checkpoint` and `training_data.json` files from the s3 bucket.

I cannot understand this error.  I'm using python3.6 for training and python 3.5.2 for the prod server.

**Comment by k-koehler** [comment]
So apparently the python version matters when pickling... I'm assuming this is because `@staticmethod` decorators in python3.6 version of rasa but not in 3.5?

You can close this for now. A fix would be nice though, or at least a way to persist models on AWS when not running the server version of RASA.

**Comment by akelad** [comment]
You need to use the same python versions for pickling, there's no real workaround for this
