### ISSUE TITLE
Current CORS options of Rasa NLU HTTP server are too limited

### ISSUE THREAD

**Issue by neo-alex** [RasaHQ/rasa_nlu#1420]
**Rasa NLU version**: 0.13.4

**Operating system** (windows, osx, ...): Windows

**Content of model configuration file**:
```yml
language: "en"

pipeline: "spacy_sklearn"
```

**Issue**:
When calling an endpoint like /train of Rasa NLU HTTP server (server.py) from a browser such as Chrome (e.g. a web app), an exception is raised even when adding the option --cors *. Indeed, Chrome automatically sends an OPTIONS request first (before the actual POST one) to check what is allowed by the server and currently 'Content-Type' is not declared as an allowed header. In particular, this makes it impossible to use the /train endpoint which requires 'Content-Type' to be set to 'application/x-yml'.

Adding following lines (commented with # ADDED) in server.py inside "check_cors" solves the issue:

```python
            if '*' in self.cors_origins:
                request.setHeader('Access-Control-Allow-Origin', '*')
                request.setHeader('Access-Control-Allow-Headers', 'Content-Type')  # ADDED
                request.setHeader('Access-Control-Allow-Methods', 'POST, GET, OPTIONS, PUT, DELETE')  # ADDED
            elif origin in self.cors_origins:
                request.setHeader('Access-Control-Allow-Origin', origin)
                request.setHeader('Access-Control-Allow-Headers', 'Content-Type')  # ADDED
                request.setHeader('Access-Control-Allow-Methods', 'POST, GET, OPTIONS, PUT, DELETE')  # ADDED
```

Could you please consider it? Thanks!

**Comment by akelad** [comment]
Thanks for raising this issue, @tmbo  will get back to you about it soon.

**Comment by tmbo** [comment]
@neo-alex that is a very good point :+1: - you should be careful though about exposing that endpoint, as this will also expose access to all conversations, just wanted to mention that.

It would be great if you could create a PR adding these lines to the `server.py` :+1:

**Comment by abhishekchotaliya** [comment]
> **Rasa NLU version**: 0.13.4
> 
> **Operating system** (windows, osx, ...): Windows
> 
> **Content of model configuration file**:
> 
> ```yaml
> language: "en"
> 
> pipeline: "spacy_sklearn"
> ```
> 
> **Issue**:
> When calling an endpoint like /train of Rasa NLU HTTP server (server.py) from a browser such as Chrome (e.g. a web app), an exception is raised even when adding the option --cors *. Indeed, Chrome automatically sends an OPTIONS request first (before the actual POST one) to check what is allowed by the server and currently 'Content-Type' is not declared as an allowed header. In particular, this makes it impossible to use the /train endpoint which requires 'Content-Type' to be set to 'application/x-yml'.
> 
> Adding following lines (commented with # ADDED) in server.py inside "check_cors" solves the issue:
> 
> ```python
>             if '*' in self.cors_origins:
>                 request.setHeader('Access-Control-Allow-Origin', '*')
>                 request.setHeader('Access-Control-Allow-Headers', 'Content-Type')  # ADDED
>                 request.setHeader('Access-Control-Allow-Methods', 'POST, GET, OPTIONS, PUT, DELETE')  # ADDED
>             elif origin in self.cors_origins:
>                 request.setHeader('Access-Control-Allow-Origin', origin)
>                 request.setHeader('Access-Control-Allow-Headers', 'Content-Type')  # ADDED
>                 request.setHeader('Access-Control-Allow-Methods', 'POST, GET, OPTIONS, PUT, DELETE')  # ADDED
> ```
> 
> Could you please consider it? Thanks!

The above request is very important for the developers who wants to integrate rasa nlu in their application.

Even I am also facing the issue and my development work is stuck because of it.

**One important point though:**
@neo-alex 
Even after adding the above lines in server.py, it is failing.
Now, the options request is 200, but the actual post `/parse` api request is **404** Not Found

command to run the server:
`python -m rasa_nlu.server -c config.yaml  --pre_load model_1 --path models/nlu/ --cors *`

**Comment by tmbo** [comment]
do you mind creating a pull request to fix this?

**Comment by abhishekchotaliya** [comment]
> do you mind creating a pull request to fix this?

I already did it. And now, I also changed the `changelog` as you suggested, so I think there should be no problem in merging the code 🙂

**Comment by abhishekchotaliya** [comment]
@tmbo
You can mark these issue as solved as the code suggested by @neo-alex is pushed and now merged in the master branch.

**Comment by tmbo** [comment]
awesome :rocket:
