### ISSUE TITLE
Endpoint /evaluate of Rasa NLU HTTP server is not up-to-date

### ISSUE THREAD

**Issue by neo-alex** [RasaHQ/rasa_nlu#1421]
**Rasa NLU version**: 0.13.4

**Operating system** (windows, osx, ...): Windows

**Content of model configuration file**:
```yml
language: "en"

pipeline: "spacy_sklearn"
```

**Issue**:
The endpoint /evaluate of Rasa NLU HTTP server (server.py) is not up-to-date compared to the evaluate.py script of Rasa NLU. In particular it does not evaluate entities (only intents) and encounters some bugs that the script does not have.

Thus it would be great if Rasa NLU HTTP server could be inline with the latest evaluate.py script or maybe directly call it internally. Thanks!

**Comment by akelad** [comment]
Thanks for raising this issue, @ricwo  will get back to you about it soon.

**Comment by ricwo** [comment]
@neo-alex that's a valid point! would you be willing to create a PR that calls the `evaluate` methods directly from the http server?
