### ISSUE TITLE
Inconsistent BILOU tagging found

### ISSUE THREAD

**Issue by ctrado18** [RasaHQ/rasa_nlu#1422]
**Rasa NLU version**:.13.1

**Operating system** (windows, osx, ...):

**Content of model configuration file**:
```yml

```

**Issue**:
I get the following after NLU parsing. During training this messages don't come. What does this mean?
```
DEBUG:rasa_nlu.extractors.crf_entity_extractor:Inconsistent BILOU tagging found, B- tag, L- tag pair encloses multiple entity classes.i.e. [B-a, I-b, L-a] instead of [B-a, I-a, L-a].
Assuming B- class is correct.
DEBUG:rasa_nlu.extractors.crf_entity_extractor:Inconsistent BILOU tagging found, B- tag not closed by L- tag, i.e [B-a, I-a, O] instead of [B-a, L-a, O].
Assuming last tag is L-

```

**Comment by akelad** [comment]
Thanks for raising this issue, @Ghostvv will get back to you about it soon.

**Comment by tmbo** [comment]
Well, so this is a prediction error - most likely because something is wrong with the training data. It happens when the predictions are inconsistent and do not represent a proper order of the tags (which can happen because there are rules for how tokens should be tagged in the BILOU scheme, but the one who is tagging them is an ML model, so that one might do mistakes).

**Comment by ctrado18** [comment]
Thanks @tmbo 

>Well, so this is a prediction error - most likely because something is wrong with the training data. 

What is wrong?

>which can happen because there are rules for how tokens should be tagged in the BILOU scheme, but the one who is tagging them is an ML model, so that one might do mistakes

So, the tagging scheme is learned by an Algo from the training data and I do not need to provode the tagging schemes?

I used chatito and have single and two word entities (like adjective+Noun eg new shoes). Issue arises with two word entities.

**Comment by tmbo** [comment]
> What is wrong?
That is a very good question, and I don't know the answer to that without looking at the training data - might be a compound entity (e.g. 2 words) where the first word is can be the first wird of two different entites ("two shoes" -> pair_of_shoes entity  - "two eyes" -> normal_glasses entity  - the prefix "two" is the same for both entities)

**Comment by ctrado18** [comment]
I have just one entity class. It is not a result of the start and end positions of strings, right? I have one enty trained with single noun and two word entities compound of an adjective and noun such as new shoes. What does `B- tag not closed by L- tag, i.e [B-a, I-a, O] instead of [B-a, L-a, O].
Assuming last tag is L-` mean. Maybe is it that the case for just one word entity which otherwise occurs also inside the two word entity?

Does this influences the entity recognition at all or can ignore that.

**Comment by kothiyayogesh** [comment]
Hi @tmbo,
Even I am facing the similar issue.
Here is my training and validation data looks like, Please let me know what is wrong with data?
Training data:
```
## intent:cuisineNearMe
  - decent [hawaiian](cuisine) places to eat near me 
  - great [filipino](cuisine) restaurants close by 
  - classy [australian](cuisine) places closeby 
  - awesome [beverages](cuisine) places to get here 
  - superb [bihari](cuisine) places to eat near my location 
  - best [coffee and tea](cuisine) restaurants near me now 
  - amazing [russian](cuisine) places to get here 
```

Validation data:
```
## intent:cuisineNearMe
  - decent [chettinad](cuisine) places to eat near me 
  - great [vegetarian](cuisine) restaurants close by 
  - classy [panini](cuisine) places closeby 
  - awesome [armenian](cuisine) places to get here 
  - superb [british](cuisine) places to get near my location 
  - best [fish and chips](cuisine) places near me now 
  - amazing [ice cream](cuisine) restaurants near my location 
  - classy [raw meats](cuisine) places to eat here 
```
Also, does it affect precision/recall/f1-score?
