### ISSUE TITLE
Cloud storage docs are not clear

### ISSUE THREAD

**Issue by nielsrolf** [RasaHQ/rasa_nlu#1426]
I am trying to setup the server such that it uses google cloud storage to fetch the models. From the docs, I got that I need to specify my key file and install the google-cloud-storage package. I've done that, and startet the server like this:
`python -m rasa_nlu.server  -c config/nlu_config_en.yml --path . --storage gcs --debug`
I would now assume that path refers to a path in the bucket. However if I check /status, I see that rasa thinks that `path` is a local path, and it lists my files as projects:

```
"available_projects": {
    "customers": {
      "status": "ready",
      "current_training_processes": 0,
      "available_models": [
        "karousel_en",
        "karousel_de"
      ],
      "loaded_models": []
    },
    "gcloud": {
      "status": "ready",
      "current_training_processes": 0,
      "available_models": [
        "fallback"
      ],
      "loaded_models": [
        "fallback"
      ]
    },
    ".DS_Store": {
      "status": "ready",
      "current_training_processes": 0,
      "available_models": [
        "fallback"
      ],
      "loaded_models": [
        "fallback"
      ]
    },
    "config": {
      "status": "ready",
      "current_training_processes": 0,
      "available_models": [
        "fallback"
      ],
      "loaded_models": [
        "fallback"
      ]
    },
    "Dockerfile": {
      "status": "ready",
      "current_training_processes": 0,
      "available_models": [
        "fallback"
      ],
      "loaded_models": [
        "fallback"
      ]
    }
    ...
```

Maybe the docs could be a bit more in detail on how to use the cloud storage.

Another thing that should be mentioned in the docs is that you need to set `BUCKET_NAME` as environment variable (it's mentioned for S3, but not for gcs), I learned this from the debug output

**Comment by akelad** [comment]
Thanks for raising this issue, @JustinaPetr will get back to you about it soon.

**Comment by mohdgadi** [comment]
@akelad , @nielsrolf Is there an update? It's still unclear if the models in the bucket should exist in the project folder or in the root or should they be compressed?

**Comment by akelad** [comment]
@wochinge can you take a look at this please?

**Comment by careless25** [comment]
I am also stuck at the same place for AWS. I cannot seem to figure out how to setup Cloud Storage. Can this be reopened?

**Comment by akelad** [comment]
looks like you created a PR for this already, thanks so much!
