### ISSUE TITLE
"error": "0"

### ISSUE THREAD

**Issue by yuxuan2015** [RasaHQ/rasa_nlu#1431]
curl -XPOST localhost:5000/parse -d {"query": "钱在卡里", "project": "nlu", "model": "dun"}

When I type some text, the following phenomenon will occur
{
    "error": "0"
}

**Comment by akelad** [comment]
Please fill out the issue template

**Rasa Core version**:

**Python version**: 

**Operating system** (windows, osx, ...):

**Issue**:



**Content of domain file** (if used & relevant):
```yaml

```
