### ISSUE TITLE
Learn a new intent recursively

### ISSUE THREAD

**Issue by samarth12** [RasaHQ/rasa_nlu#1433]
So currently based on the training dataset, the classifier gives out the classified intent result with a probability of that resulting intent. Now what I am looking to do is if the output intent is below a certain threshold for any new user input sentence:

1. First, prompt the user to tag the input to any of the existing intents.
2.  Else, if the user thinks it doesn't match any existing intents then the user gets to define a new intent for that particular input sentence.
Now for both steps 1 and 2, I need to update the dataset with this new input sentence and its corresponding intent in the exact same format as the input dataset in order to retrain the model with updated dataset over time.

I would love to know your thoughts on that @akelad and team.

**Comment by akelad** [comment]
Have you tried interactive learning? Because there it prompts you to label the intent. And we're working on having that create an NLU training file so you don't need to manually add it

**Comment by samarth12** [comment]
So currently I am just working with the NLU part of Rasa ie. just with the intent classification. My aim is to give the user all the freedom to decide if the intent output by Rasa is correct or not, if it is not correct then select the right intent, if the intent is not present in the list then add a new intent. Add all this new information to the training dataset and retrain the model. 

From my understanding, interactive learning needs stories and a flow of conversation defined. I am just looking to work with intents in order to correct the intents or add new intents to the system in an iterative fashion. 

@akelad I hope I explained it better.

**Comment by akelad** [comment]
Yes that's true, our interactive learning module does require core. I'm not sure we'll be implementing something like this for NLU, just because Core already has this capability and we do encourage the use of Core with NLU.

**Comment by samarth12** [comment]
Yeah that makes sense. I have another question, I haven't been able to get Interactive Learning running but from the documentation, it seems that it allows the user to corrects the actions taken by the bot. But does it also allow the users to correct the NLU intent for every input sentence, and on top of that add new intents which do not exist in the system database?

**Comment by akelad** [comment]
New intents you have to specify in your domain file, but correcting the NLU intent works yes
