### ISSUE TITLE
I can't deploy my app on facebook

### ISSUE THREAD

**Issue by sirainatou** [RasaHQ/rasa_nlu#1434]
**Rasa NLU version**:
0.13.5
**Operating system** (windows, osx, ...):
windows
I am testing the moodbot from the rasa_core exemples
**Issue**:
Hi, I used the run script to connect to facebook and the command box showed that the rasa core is running on localhost ! but when I want to access it it returns 404 not found w thus facebook cannot accept the webhook ! what can I do ?

**logfile**:
C:\Users\Lenovo\Anaconda3\lib\site-packages\pykwalify\core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5002

**Comment by akelad** [comment]
So running on localhost won't let facebook connect to your server, please use ngrok for this https://rasa.com/docs/core/connectors/#using-ngrok-for-local-testing
Let me know if that helps.

**Comment by sirainatou** [comment]
Yes! it worked! facebook has accepted the webhook! but I got a new error ! thanks for your response !

**Comment by akelad** [comment]
I'll close this one then
