### ISSUE TITLE
ValueError: bad input shape (1, 5)

### ISSUE THREAD

**Issue by hydridity** [RasaHQ/rasa_nlu#1436]
**Rasa NLU version**: 0.13.5
**Python version**: 3.6

**Operating system**: Ubuntu:17.10 or Docker-Ubuntu:17.10

**Content of model configuration file**:
```yml
language: "en"
pipeline: spacy_sklearn
```

**Content of python file**:
```py
from rasa_nlu.training_data import load_data
from rasa_nlu.model import Trainer, Interpreter
from rasa_nlu import config



training_data = load_data('nlu_data.md') #tried with different datafiles from various sources both md or json
trainer = Trainer(config.load("rasa-config.yml"))
trainer.train(training_data)
model_directory = trainer.persist('./rasa_model')

interpreter = Interpreter.load(model_directory)

#same error for both
interpreter.parse(u"The text I want to understand")
interpreter.parse("The text I want to understand")
```

**Output**:
```
Fitting 2 folds for each of 6 candidates, totalling 12 fits
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  12 out of  12 | elapsed:    0.1s finished
/usr/local/lib/python3.6/dist-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from '/datas/./rasa_model/default/model_20180930-201701/entity_synonyms.json'
  "".format(entity_synonyms_file))
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    interpreter.parse(u"The text I want to understand")
  File "/usr/local/lib/python3.6/dist-packages/rasa_nlu/model.py", line 357, in parse
    component.process(message, **self.context)
  File "/usr/local/lib/python3.6/dist-packages/rasa_nlu/classifiers/sklearn_intent_classifier.py", line 176, in process
    intents = self.transform_labels_num2str(intent_ids)
  File "/usr/local/lib/python3.6/dist-packages/rasa_nlu/classifiers/sklearn_intent_classifier.py", line 112, in transform_labels_num2str
    return self.le.inverse_transform(y)
  File "/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/label.py", line 273, in inverse_transform
    y = column_or_1d(y, warn=True)
  File "/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py", line 788, in column_or_1d
    raise ValueError("bad input shape {0}".format(shape))
ValueError: bad input shape (1, 5)
```

**Issue**:
Hello, im trying to run example from documentation https://rasa.com/docs/nlu/0.13.5/python/ but im getting ValueError: bad input shape (1, 5) is this issue or im doing something wrong ?

**Comment by akelad** [comment]
Thanks for raising this issue, @MetcalfeTom  will get back to you about it soon.

**Comment by MetcalfeTom** [comment]
Hi @hydridity, just trying to recreate this error now to see if it's a bug or perhaps an issue with scikit-learn but in the meantime could you show me a snippet of how your `nlu_data.md` is formatted?

**Comment by MetcalfeTom** [comment]
Hello again.  I just recreated the situation from scratch and ran your python script.  I didn't encounter this error, however I can see from your traceback that the model trained correctly which leads me to believe this may arise from another package.  Have you ran `pip install -r requirements.txt` from the `/starter-pack-rasa-nlu` directory?

**Comment by hydridity** [comment]
That solved problem, i've installed most of those packages manually to the latest versions so it might be caused by some change in scikit-learn, i had 0.20 and in requirements is 0.19.1, or another package that was missing or had some change

**installation versions snippet**:
```powershell
  Found existing installation: scikit-learn 0.20.0
    Uninstalling scikit-learn-0.20.0:
      Successfully uninstalled scikit-learn-0.20.0
  Found existing installation: packaging 18.0
    Uninstalling packaging-18.0:
      Successfully uninstalled packaging-18.0
  Found existing installation: gevent 1.3.6
    Uninstalling gevent-1.3.6:
      Successfully uninstalled gevent-1.3.6
Successfully installed ConfigArgParse-0.13.0 Jinja2-2.10 MarkupSafe-1.0 click-7.0 colorhash-1.0.2 decorator-4.3.0 docopt-0.6.2 flask-1.0.2 flask-cors-3.0.4 gevent-1.2.2 itsdangerous-0.24 networkx-2.1 packaging-17.1 pika-0.11.2 pykwalify-1.6.0 pymongo-3.5.1 scikit-learn-0.19.1
```

**Comment by MetcalfeTom** [comment]
Hurrah!  Great to hear everything worked out.

Thanks for posting the snippet, that will help me find out where the problem may lie.  For now I will close this issue

**Comment by wilmerags** [comment]
Hello! i faced the same issue although with shape (1,4), i'm trying changing scikit-learn version, but there will be a way of solving it with scikit-learn 0.20.0 ?

**Comment by wilmerags** [comment]
after changing the version this erased as a warning: `lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: builtins.DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.`

**Comment by akelad** [comment]
That looks like it worked? If you're having trouble, please open a new issue

**Comment by Chidhambararajan** [comment]
Hello there,

I am new to rasa nlu, my model got trained but when i try to implement it , i get a similar error

Code:
`from rasa_nlu.model import Interpreter
import json
interpreter = Interpreter.load("models/current/nlu")
message = "let's see some italian restaurants"
result = interpreter.parse(message)
print(json.dumps(result, indent=2))
`
Error:
`Traceback (most recent call last):
  File "trained_model_test.py", line 5, in <module>
    result = interpreter.parse(message)
  File "/home/captain-america/.local/lib/python3.6/site-packages/rasa_nlu/model.py", line 357, in parse
    component.process(message, **self.context)
  File "/home/captain-america/.local/lib/python3.6/site-packages/rasa_nlu/classifiers/sklearn_intent_classifier.py", line 181, in process
    intents = self.transform_labels_num2str(intent_ids)
  File "/home/captain-america/.local/lib/python3.6/site-packages/rasa_nlu/classifiers/sklearn_intent_classifier.py", line 115, in transform_labels_num2str
    return self.le.inverse_transform(y)
  File "/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/label.py", line 273, in inverse_transform
    y = column_or_1d(y, warn=True)
  File "/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py", line 797, in column_or_1d
    raise ValueError("bad input shape {0}".format(shape))
ValueError: bad input shape (1, 3)`

Thanks in Advance!!

**Comment by samrudh** [comment]
Updating rasa-nlu to 0.14 solved my problem. Thanks.

**Comment by greg-springett** [comment]
Hi - i was getting the same bad input shape error, followed the suggested resolution above of installing the requirements from the starter pack git but now i get an 'illegal instruction 4 error'. any thoughts?

**Comment by sudhirkumar18** [comment]
i was try all thre above way how to solve this issue please reply me as soon as possible


  File "/usr/local/lib/python3.5/dist-packages/sklearn/utils/validation.py", line 797, in column_or_1d
    raise ValueError("bad input shape {0}".format(shape))
ValueError: bad input shape (1, 3)

**Comment by MetcalfeTom** [comment]
Hi, are you sure you've updated your rasa version?  Because we [fixed the line that was causing this error](https://github.com/RasaHQ/rasa/pull/1635)

Please open a new issue and include a full stacktrace if the error persists.

**Comment by PrithviRakshak** [comment]
Am new to programming and am facing the same issue. I updates rasa to latest version , created config file and followed every step, for whatever reason I keep getting the same error, can U help me?

**Comment by akashpanwar4411** [comment]
> Updating rasa-nlu to 0.14 solved my problem. Thanks.

thank you very much it work
