### ISSUE TITLE
weird max_training_processes parameter behaviour

### ISSUE THREAD

**Issue by frascuchon** [RasaHQ/rasa_nlu#1442]
**Rasa NLU version**: 0.13.5

**Operating system** (windows, osx, ...): ubuntu server 16.04

**Issue**: 
Setting argument `max_training_processes: 1` server deny training more than one model for a project with error:
```json
{
  "error": "The server can't train more models right now!"
}
```
But training a new project is possible

I really don't know if is an issue or an expected behaviour. It `max_training_processes` is related to a single project, the error seems to indicate that you cannot train at all. 

If it's a global parameter, there is a bug here. In this case, I've locate the bug in source code and I can prepare a little pull request for that.

Thanks in advance

**Comment by akelad** [comment]
Thanks for raising this issue, @ricwo  will get back to you about it soon.

**Comment by wrathagom** [comment]
@dcalvom FYI since you were likely the last one to touch this code.

**Comment by ricwo** [comment]
@frascuchon Thanks for pointing out this issue - it is indeed a bug. I have just pushed a fix with #1449

**Comment by frascuchon** [comment]
Cool @ricwo! Do you know in which release this fix will be included?

**Comment by ricwo** [comment]
@frascuchon It'll be in the next release, so `0.13.7`
