### ISSUE TITLE
AttributeError: module 'rasa_core.training.online' has no attribute 'serve_agent' while doing interactive learning

### ISSUE THREAD

**Issue by vikingsvivek** [RasaHQ/rasa_nlu#1451]
**Rasa NLU version** 0.13.6

**Operating system** windows 

**Content of model configuration file**:
{
"pipeline":"spacy_sklearn",
"path":"./models/nlu",
"data":"./data/data.json"
}

**Issue**:
Getting error 
INFO:rasa_core.policies.keras_policy:Done fitting keras policy model
Traceback (most recent call last):
  File "train_online.py", line 37, in <module>
    run_product_online(nlu_interpreter)
  File "train_online.py", line 30, in run_product_online
    online.serve_agent(agent)
**AttributeError: module 'rasa_core.training.online' has no attribute 'serve_agent'**

**Comment by akelad** [comment]
Thanks for raising this issue, @Ghostvv  will get back to you about it soon.

**Comment by Ghostvv** [comment]
This is `rasa_core` issue, please create an issue in `rasa_core` repo and provide the version of `rasa_core`
