### ISSUE TITLE
NLU Functioning 

### ISSUE THREAD

**Issue by Koushik0890** [RasaHQ/rasa_nlu#1452]
**Issue**: Can a single sentence of the training data have multiple synonyms, referring to the same entity?
Example:
Entity Values:
rasa
rasa_core [rasa core,rasacore]
rasa_nlu [rasa nlu]
rasa_ui [rasa ui]

Training Data:
i need to use the new rasa core
i need to use rasa core
i need to use rasa ui
how can i use rasa

User Utterance:
I need to use rasa core.

How will the NLU handle this? Will it figure out "rasa" or "rasa core". How should these use cases be handled?

**Comment by akelad** [comment]
Please ask these kind of questions in our [forum](https://forum.rasa.com). There's also documentation on how to use synonyms here: https://rasa.com/docs/nlu/dataformat/#entity-synonyms
