### ISSUE TITLE
Feature request: Custom NER model with spacy

### ISSUE THREAD

**Issue by kapilkathuria** [RasaHQ/rasa_nlu#1453]
**Rasa NLU version**: 0.13.4

As of now for creating a custom NER model, only option is CRF. I have multiple use cases where-in I need to extract data from documents / Pdfs. I haven't seen good results so far using CRF. I wanted to try spacy custom model.

As of now, I am creating spacy model via python script provided by spacy but I thought it will be good to get option out of box in RASA NLU to create custom spacy model.

**Comment by akelad** [comment]
I wouldn't really recommend using Rasa NLU to extract entities from documents/PDFs, it's for extracting entities from shorter sentences, mainly for chatbots. 
I think using your own python script for this is the correct approach in this case

**Comment by kapilkathuria** [comment]
@akelad thanks for your note. Just in case you aware of any starting point (python script or any other NLU library) for, please share.

**Comment by akelad** [comment]
i'm not really sure, the spacy documentation is maybe a good starting point. I'll close this issue for now

**Comment by prashant334** [comment]
> dn't really recommend using Rasa NLU to extract entities from documents/PDFs, it's for extracting entities from shorter sentences, main

@akelad Even for short sentences CRF BASED "ner_crf" is not giving accurate results. I have trained model to extract source and destination from short sentences like 
**_show me the trains   from Delhi to pune_** where **DELHI = SOURCE** and **PUNE=DESTINATION**

please find trained data in below attachment.

[data.txt](https://github.com/RasaHQ/rasa/files/3177804/data.txt)



--
