### ISSUE TITLE
Could not find a version that satisfies the requirement tensorflow==1.10.0 (from rasa_core)

### ISSUE THREAD

**Issue by alonsopg** [RasaHQ/rasa_nlu#1455]
I am trying to install rasa_core in windows as specified in the documentation:

`λ pip install rasa_core`

However, after trying to install the library I get the following mesage: 
```
  Could not find a version that satisfies the requirement tensorflow==1.10.0 (from rasa_core) (from versions: )
No matching distribution found for tensorflow==1.10.0 (from rasa_core)
```

Based on this [post](https://stackoverflow.com/questions/51590822/rasa-nlu-failed-building-wheel-for-spacy-and-failed-building-wheel-for-thinc), I thought that the reason was that I needed to install other dependencies. However, aftering installing those dependencies I am still having the same issue. I also tried to upgrade my pip, and it is not working.  Finally I tried to:

` pip install --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.10.0-py3-none-any.whl`

However, I am getting:

`Command "c:\users\user\appdata\local\programs\python\python37\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\user~1\\AppData\\Local\\Temp\\pip-install-r77vu_e5\\Twisted\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\user~1\AppData\Local\Temp\pip-record-ed0arqg0\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\user~1\AppData\Local\Temp\pip-install-r77vu_e5\Twisted\`

Therefore, which is the correct way of installing rasa_core?

**Comment by akelad** [comment]
Please fill out the issue template when creating an issue in future.

**Rasa Core version**:

**Python version**: 

**Operating system** (windows, osx, ...):

**Issue**:



**Content of domain file** (if used & relevant):
```yaml

```

Looks like you've got python 3.7 installed, tensorflow doesn't support this yet, and neither do we officially. So please downgrade to 3.6 and the issue should be resolved!

**Comment by deenaik** [comment]
@alonsopg in case you are using Anaconda (conda), you can get downgrade simply by using the following command.
`conda install -c conda-forge tensorflow`

conda will take care of all dependencies like upgrade/downgrade etc.

**Comment by Olesiatsa** [comment]
@akelad I downgraded to 3.6, but I get the same error. 
Can you help?

**Comment by Btibert3** [comment]
Just emphasizing the comment from @deenaik above; need to run that command first (say, in a new conda environment) prior to running the commands that we see in the docs online

**Comment by mausch** [comment]
For anyone else still running into this, the min version of rasa_core supporting Python 3.7 is 0.14.0
