### ISSUE TITLE
No module named 'sklearn' in anaconda jupyter

### ISSUE THREAD

**Issue by srideviaishwariya** [RasaHQ/rasa_nlu#1459]
Running into an issue similar to https://github.com/RasaHQ/rasa_nlu/issues/849 on MAC

![screen shot 2018-10-10 at 3 07 26 pm](https://user-images.githubusercontent.com/3505829/46768949-f14c2b00-cc9e-11e8-8b35-67900f873f04.png)

$ which conda
/anaconda3/bin/conda
$ which pip
/anaconda3/bin/pip

$ which pip3
/usr/local/bin/pip3

$which python3
/usr/local/bin/python3

$jupyter kernelspec list
Available kernels:
python3 /Users//Library/Jupyter/kernels/python3

**Comment by JustinaPetr** [comment]
Hey @srideviaishwariya. Are you running your notebook in a virtual environment? I can see that your system path points to python3.6 while using pip3 you install the libraries inside python3.7. So what I think is happening: you start your notebook in python 3.6, but you install your libraries to python 3.7.

If you use virtual env, are you sure you activate it before launching the notebook?
If not, can you check your environmental variables and tell me which version of python executable is set to be used?

**Comment by Vinay141194** [comment]
Hello, I am still facing the same issue, I have even not used any virtual environment, @JustinaPetr, Could you please suggest.
