### ISSUE TITLE
SVC' object has no attribute '_impl

### ISSUE THREAD

**Issue by Rosadojonathan** [RasaHQ/rasa_nlu#1463]
Hey there!

I'm running into some problems after running ->
![image](https://user-images.githubusercontent.com/25138966/46874430-7408ed80-ce39-11e8-8d5d-26a71d132dc9.png)

I get the following error ->
![image](https://user-images.githubusercontent.com/25138966/46874490-8daa3500-ce39-11e8-9010-3d61dabc026f.png)

I'm using `scikit-learn==0.19.1` version

**Comment by MetcalfeTom** [comment]
Hey @Rosadojonathan, how's it going.

Of course I'll ask you first to try downgrading to `scikit-learn==0.19.0` and see if this error ceases to raise.

**Comment by Rosadojonathan** [comment]
Hey @MetcalfeTom thank you for taking the time to help me.

You are right, changing the scikit-learn version to `scikit-learn==0.19.0` and making sure the model was also trained with the same scikit-learn version solved the issue. 

Thanks a lot, have a great day!

**Comment by akelad** [comment]
@MetcalfeTom can you check whether you can reproduce this issue with version 0.19.1? Because in that case we should change our requirements

**Comment by Rosadojonathan** [comment]
I've upgraded to 0.19.1 and it works fine,  it seems that the issue was caused by my model being trained on a different version.

**Comment by akelad** [comment]
awesome

**Comment by zhengzepeng** [comment]
Thanks for help.

-

**Comment by marcoruizrueda** [comment]
I solved this issue by installing a more recent version in python3:

`pip3 install scikit-learn==0.20.4`

**Comment by bm777** [comment]
Hi @marcoruizrueda,  It worked for me, with the version that you mentioned. In my virtual environment.

`pip install scikit-learn==0.20.4`

Thank :)

**Comment by ANAIDJM1** [comment]
HI, I had the same problem,I use Sklearn version 0.23.02 but I was trying to run an archive trained with a version 0.18... and my error said: "'SVC' object has no attribute 'break_ties'", I just retrained the model with my version and fix the problem I generate other svc.pickle to run with the  0.23.02 version and replace the oldie.
