### ISSUE TITLE
Synonym usage leading to wrong intent

### ISSUE THREAD

**Issue by sbadrinath** [RasaHQ/rasa_nlu#1465]
**Rasa NLU version**: 0.13.6

**Operating system** (windows, osx, ...): windows 8

**Content of model configuration file**:
``` json
{
  "path" : "./",
  "data" : "./nlu_data/gstfaq-data.json",
  "debugModeEnabled": true,
  "language" : "en",
  "pipeline" : "spacy_sklearn"
}
```

**Issue**:

I am using the below training_data.json and asking the below questions

1. what is GST
       I am getting an expected answer
2. what is gst
      I am getting correct and expected answer
3. what is tax
     It extracts wrong INTENT and hence wrong answer

``` json
"entity_synonyms": [
      {
        "value": "GST",
        "synonyms": ["Goods Service Tax", "gst","Tax", "tax"]
      }
    ]
{
  "rasa_nlu_data": {
    "common_examples": [
      {
        "intent": "gstbasicinfo",
        "entities": [
          {
            "start": 8,
            "end": 11,
            "value": "gst",
            "entity": "gstbasicinfo-value"
          }
        ],
        "text": "What is GST"
      }
    ]
  }
}
```

Please help me to understand where I am making mistake

**Comment by manslogic** [comment]
Provide more training samples in the training data and then check. it needs more training samples to generalize a pattern .

**Comment by wrathagom** [comment]
@sbadrinath @manslogic is correct, see this note in the docs

> Please note that adding synonyms using the above format does not improve the model’s classification of those entities. Entities must be properly classified before they can be replaced with the synonym value.
