### ISSUE TITLE
Pipelines when creating model from fastText vectors 

### ISSUE THREAD

**Issue by Harish238** [RasaHQ/rasa_nlu#1466]
I have been trying to build an NLU model for Hindi using fastText vectors. When building the package, I read that the "pipeline" parameter in meta.json would use the default spacy pipeline if not set, so I did not specify any pipeline.

Once the new language model was linked to spacy, I have changed the "language" parameter in config.yml file to the path of the model and the "pipeline" parameter to "spacy_sklearn".
Note: The path to the model did not have any tagger/parser/ner folders.

While I am able to build the NLU model successfully, none of the examples that I am using to test are being recognised, including the ones that are present in the training data itself. 

I have viewed the discussion on #869 and haven't found the answer to my questions. It would be of great help to know what components to include in both the pipelines.
Would love some assistance on solving this!

Here is the config.yml -
`language: "/path/to/model"
pipeline: "spacy_sklearn"`

And this is meta.json -
`{
  "lang":"hi",
  "name":"model",
  "version":"0.0.0",
  "spacy_version":">=2.0.11",
  "description":"",
  "author":"",
  "email":"",
  "url":"",
  "license":"",
  "vectors":{
    "width":300,
    "vectors":199336,
    "keys":158016,
    "name":null
  },
  "pipeline":[
  ]
}`

**Comment by akelad** [comment]
Thanks for raising this issue, @amn41  will get back to you about it soon.
