### ISSUE TITLE
DialogFlow emulator response does not match API

### ISSUE THREAD

**Issue by blakeandrewwood** [RasaHQ/rasa_nlu#1484]
**Rasa NLU version**: latest

**Issue**:

In the DF response there is key named `metaData` where the intent with the highest score gets placed. The issue is that rasa returns an object for `intentName` rather than what it should be, a string.

```
...
"metadata": {
  "intentId": "4b19212c-d89f-11e8-ab9d-fe4417299557",
  "webhookUsed": "false",
  "intentName": {
    "name": "welcome.greeting",
    "confidence": 0.9680702090263367
  }
},
...
```

https://github.com/RasaHQ/rasa_nlu/blob/master/rasa_nlu/emulators/dialogflow.py#L49

According to DialogFlow, this key should just be a string:
```
...
"metadata": {
  "intentId": "4b19212c-d89f-11e8-ab9d-fe4417299557",
  "webhookUsed": "false",
  "intentName": "welcome.greeting"
},
...
```

Solution:

In [the emulator](https://github.com/RasaHQ/rasa_nlu/blob/master/rasa_nlu/emulators/dialogflow.py) we set `result.action` and `result.metadata.intentName` to the intent, and `result.score` the intent confidence like I have below:

```python
"id": str(uuid.uuid1()),
"timestamp": datetime.now().isoformat(),
"result": {
  "source": "agent",
  "resolvedQuery": data["text"],
  "action": data["intent"]["name"],
  "actionIncomplete": None,
  "parameters": entities,
  "contexts": [],
  "metadata": {
     "intentId": str(uuid.uuid1()),
     "webhookUsed": "false",
     "intentName": data["intent"]["name"]
   },
   "fulfillment": {},
   "score": data["intent"]["confidence"],
 },
 ...
```

Changing the response to something other than the DialogFlow API returns breaks functionality. Currently I am writing a Rasa SDK that utilizes the C# ApiAiSdk model [Metadata](https://github.com/dialogflow/dialogflow-dotnet-client/blob/master/ApiAiSDK/Model/Metadata.cs#L25) for deserializing the response. As you can see, the member `IntentName` is a string.

If this seems like a valid solution I can make the change, write tests, and open a PR.

Thank you.

**Comment by EPedrotti** [comment]
Thanks for raising this issue, @ricwo will get back to you about it soon.

**Comment by ricwo** [comment]
thanks for pointing this out @blakeandrewwood! It would be great if you could create a PR with the changes you suggested  👍

**Comment by blakeandrewwood** [comment]
Awesome, will get back to you guys as soon as I open a PR.
