### ISSUE TITLE
Fitting 2 folds for each of 6 candidates, totalling 12 fits

### ISSUE THREAD

**Issue by sagarP47** [RasaHQ/rasa_nlu#1485]
after training Rasa nlu model, it is showing following msg "Fitting 2 folds for each of 6 candidates, totalling 12 fits". what exactly does it mean

**Rasa NLU version**:0.13.7

**Operating system** (windows, osx, ...):windows 10

**Content of model configuration file**:
```yml

```

**Issue**:

**Comment by akelad** [comment]
This is a message from sklearn i believe. In future, please ask these kind of questions in the [forum](https://forum.rasa.com)
