### ISSUE TITLE
rasa_nlu_synonyms Markdown File does not work

### ISSUE THREAD

**Issue by xinrouli** [RasaHQ/rasa_nlu#1488]
**Rasa NLU version**: Newest

**Operating system** (windows, osx, ...): osx

**Content of model configuration file**:
```
Markdown Format Dataset
```

**Issue**: When I follow the instruction on "Training Data Format" page in Rasa NLU, the Markdown file does not work for me for recognizing synonyms, but the Json File works well. I think it should recognize the "savings", but it not.  I attached my code below, please take a look and correct me if anything wrong. Thanks.

![image](https://user-images.githubusercontent.com/35542154/47655002-702bd980-db62-11e8-81a9-05a08f28b82c.png)
![image](https://user-images.githubusercontent.com/35542154/47655028-85a10380-db62-11e8-862a-d6d131478b4d.png)

**Comment by akelad** [comment]
Thanks for raising this issue, @wochinge  will get back to you about it soon.

**Comment by wochinge** [comment]
Hi @xinrouli ,
so `What is savings?` was recognised when you had the training data as json file?
I think you have to add more examples (>= 10) so that the bot has a higher confidence of extraction the entity.

**Comment by xinrouli** [comment]
@wochinge Thanks! you are so right. After adding more training examples, it works!

**Comment by wochinge** [comment]
Cool 🚀 If you have more questions or strange behaviors, which are no bugs, please post them on our forum: https://forum.rasa.com 🙂Happy chatbot building!

**Comment by xinrouli** [comment]
Sure!
