### ISSUE TITLE
handle emojis on the server training side

### ISSUE THREAD

**Issue by akelad** [RasaHQ/rasa_nlu#1489]
This is the line that breaks: 
https://github.com/RasaHQ/rasa_nlu/blob/master/rasa_nlu/utils/__init__.py#L337

The error is: `builtins.UnicodeEncodeError: 'utf-8' codec can't encode characters in position xxx: surrogates not allowed`

**Comment by aborsu** [comment]
Yeah, that means either you have malformed input that is not valid unicode or the unicodedata version that you are using doesn't contain the specific character you want to encode.

What version of python are you using and what version of unicode data is available?
```
import unicodedata
unicodedata.unidata_version
```

**Comment by akelad** [comment]
this was just a note to fix this 🙂 it's handled with rasa nlu not running as a server, just not when it's run as a server. 
Thanks for the reply though
