### ISSUE TITLE
Multiple intents and dropping intents below frequency - Tensorflow pipeline, starspace

### ISSUE THREAD

**Issue by LAV42** [RasaHQ/rasa_nlu#1495]
Let's say I have 15 intents and a thousand examples. Let's also presume that I want to do multiple intents classification. If examples are tagged with 1  intent up to Combination of 5 in 15 intents, it is highly probable that many examples with 5 intents will have only one occurrence of those specific combinations.

When I do Crossvalidation, the following line will drop any 'intent' (that is, combination of intents) that appears only once in the dataset:
https://github.com/RasaHQ/rasa_nlu/blob/00f6325ebbb834f5ce025abadd7f6cac992e30b4/rasa_nlu/evaluate.py#L895

`training_data.training_data` will also complain about that.

The way I understand the starspace paper, this should not be the case. We should be able to learn the embedding as long as there are enough different combinations.

**Comment by akelad** [comment]
Thanks for raising this issue, @Ghostvv  will get back to you about it soon.

**Comment by LAV42** [comment]
Assume we have a big dataset of labelled text.
Let also assume we have intents A, B, C,... M, N, O.
My training set is labelled with multiple intents, i.e. text_1 : A+B+J, text_2 : H + K + L + M, ...

Now, if I'm doing crossvalidation, the line `drop_intents_below_freq` will remove any example with a combination of intents that appears only a few times. (`drop_intents_bellow_freq` does not drop a specific intent, but any infrequent combination of intents)

That is, even though I have 100 examples of A, 100 examples of B, 100 examples of C, but only one example of A + B + C, this example will be dropped out of the training set. 

This becomes a problem especially when all your examples are combinations, learning (or crossvalidation for that matter) should work out even if you have only on example of a specific combination because element of that combination will appear many times in other combinations, and so the learning would still take place.

**Comment by Ghostvv** [comment]
Thanks for the explanation, I agree that in this case this line is a problem. It was added without multi intent in mind.
