### ISSUE TITLE
Custom web channels

### ISSUE THREAD

**Issue by Aaru229** [RasaHQ/rasa_nlu#1497]
Rasa NLU version: 0.13.7
Rasa Core version: 0.11.12
OS: Windows 10

How to use a custom input channel for providing user input to RASA Core and to get response back from Rasa Core.
All the issues seems to be pointing to either an invalid link or solutions to a previous versions. 
Could someone please provide an example for that.

**Comment by akelad** [comment]
Please take a look at the docs here: https://rasa.com/docs/core/connectors/
And for these kinds of questions, please post in the [forum](https://forum.rasa.com) in future :)
