### ISSUE TITLE
No module named 'rasa_nlu.training_data

### ISSUE THREAD

**Issue by Olesiatsa** [RasaHQ/rasa_nlu#1498]
**Rasa NLU version** : 13.7

**Operating system** (windows, osx, ...): Mac OS

If I try to run python nlu_model.py, I get following error: 
```
File "nlu_model.py", line 1, in <module>
    from rasa_nlu.training_data import load_data
ModuleNotFoundError: No module named 'rasa_nlu.training_data'
```

What's what I have in code:
```
from rasa_nlu.training_data import load_data
from rasa_nlu import config
from rasa_nlu.model import Trainer
from rasa_nlu.model import Metadata, Interpreter
```

I already read what it could be because of wrong person of Rasa_NLU, but I also read the docs, and the same imports are in the docs. I am frustrated.

Thank you for any help!

**Comment by Olesiatsa** [comment]
@wochinge 
I am using Python version 3.7.0

I changed the requirements.txt and now I have the following Error:
"Traceback (most recent call last):
  File "nlu_model.py", line 19, in <module>
    run_nlu()
  File "nlu_model.py", line 14, in run_nlu
    interpreter = Interpreter.load('./models/nlu/default/labornlu')
  File "/Users/user/anaconda3/lib/python3.7/site-packages/rasa_nlu/model.py", line 290, in load
    Interpreter.ensure_model_compatibility(model_metadata)
  File "/Users/user/anaconda3/lib/python3.7/site-packages/rasa_nlu/model.py", line 273, in ensure_model_compatibility
    "".format(model_version, rasa_nlu.__version__))
rasa_nlu.model.UnsupportedModelError: The model version is to old to be loaded by this Rasa NLU instance. Either retrain the model, or run withan older version. Model version: 0.11.4 Instance version: 0.13.7"

seems like I need to retrain my model. How do I do that?

**Comment by wochinge** [comment]
@Olesiatsa This looks like you used `0.11.4` before and now switched to `0.13.7`. These versions are not compatible. 
You can either train your NLU model using custom python code (like the one I shared above) or using the command line. Please refer to the NLU documentation (for NLU training: <https://rasa.com/docs/nlu/quickstart/#train-your-machine-learning-nlu-model>) for more details. Feel free to ask any questions in our forum (<https://forum.rasa.com/>), our community will be happy to help you out!

**Comment by nohumandotin** [comment]
![image](https://user-images.githubusercontent.com/48850523/60763302-76524e00-a03f-11e9-94fd-43c99a33451e.png)
If I try to run python flask_app.py, I get following error: 
Please help me to solve this issue, Thanks for help.

**Comment by wochinge** [comment]
@nohumandotin Please ask questions in the [forum](https://forum.rasa.com) and don't ask them in multiple different issues here.
