### ISSUE TITLE
tensorflow pipeline not loading component configuration

### ISSUE THREAD

**Issue by LAV42** [RasaHQ/rasa_nlu#1499]
Nothing is passed to
`self._load_params()`

https://github.com/RasaHQ/rasa_nlu/blob/21a8edc9c8842ac7c103f7c43353fa665fb8b3eb/rasa_nlu/classifiers/embedding_intent_classifier.py#L136

I think this should either read
`self._load_params(self.component_config)`
or
https://github.com/RasaHQ/rasa_nlu/blob/21a8edc9c8842ac7c103f7c43353fa665fb8b3eb/rasa_nlu/classifiers/embedding_intent_classifier.py#L195
should contain
`config.update(self.component_config)`

**Comment by akelad** [comment]
Please fill out the issue template

**Rasa Core version**:

**Python version**: 

**Operating system** (windows, osx, ...):

**Issue**:



**Content of domain file** (if used & relevant):
```yaml

```
