### ISSUE TITLE
How to mark entities in markdown format in case of ner_crf containers

### ISSUE THREAD

**Issue by ashukrishna100** [RasaHQ/rasa_nlu#1500]
**Rasa NLU version**:11.4

**Operating system** (windows, osx, ...):win 10

**Content of model configuration file**:
```yml

```

**Issue**:
My json data looks like this
`{
    "text": "1000",
    "intent": "press",
    "entities": [
      {
        "start": 0,
        "end": 4,
        "value": "1000",
        "entity": "emp_id"
      }
    ]
  }`
 Is there anyway to write it in markdown format.(ner_crf)
I think it must be along lines of
`[1000](text:emp_id)`

**Comment by akelad** [comment]
Please ask these kind of questions in our [forum](https://forum.rasa.com)
And here's the relevant documenation: https://rasa.com/docs/nlu/dataformat/
