### ISSUE TITLE
Cannot train model using Docker image in doc

### ISSUE THREAD

**Issue by alucard001** [RasaHQ/rasa_nlu#1504]
**Rasa NLU version**: 0.14.0a1

**Operating system** (windows, osx, ...): OSX 10.14

**Content of model configuration file**:
```
curl https://raw.githubusercontent.com/RasaHQ/rasa_nlu/master/sample_configs/config_train_server_json.yml
language: "en"

pipeline: "spacy_sklearn"

# data contains the same json, as described in the training data section
data: {
  "rasa_nlu_data": {
    "common_examples": [
      {
        "text": "hey",
        "intent": "greet",
        "entities": []
      }
    ]
  }
}
```

**Issue**:
I am currently testing RASA_NLU and when follow the instruction from Github first page README file under **Example use >> Training New Models** , I got an error when running:

`curl 'https://raw.githubusercontent.com/RasaHQ/rasa_nlu/master/sample_configs/config_train_server_json.yml' | curl --request POST --header 'content-type: application/x-yml' -d@- --url 'localhost:5000/train?project=test_model'`

Here is the error I got:
```
{
  "error": "while parsing a block mapping\n  in \"<unicode string>\", line 1, column 1:\n    language: \"en\"pipeline: \"spacy_s ... \n    ^\nexpected <block end>, but found '<scalar>'\n  in \"<unicode string>\", line 1, column 15:\n    language: \"en\"pipeline: \"spacy_sklearn\"# data  ... \n                  ^"
}
```
Can you please tell me what happened and how to fix this?  

Thank you very much.

**Comment by wochinge** [comment]
@wochinge

**Comment by wochinge** [comment]
@alucard001 Can you try using the flag `--data-binary` instead of `-d` . This would result in 

```
curl 'https://raw.githubusercontent.com/RasaHQ/rasa_nlu/master/sample_configs/config_train_server_json.yml' | \
curl --request POST --header 'Content-Type: application/x-yml' --data-binary @- --url 'localhost:5000/train?project=test_model'
```

**Comment by alucard001** [comment]
Sorry for replying you late.  The new command works.  Thank you.  Please update the README also.

**Comment by wochinge** [comment]
@alucard001 Great, happy to help. 
I already created a fix for that, I just have to wait until it is approved: https://github.com/RasaHQ/rasa_nlu/pull/1505
