### ISSUE TITLE
Multiple intent prediciting single intent

### ISSUE THREAD

**Issue by augusto-peterlevitz-movile** [RasaHQ/rasa_nlu#1519]
Hi! I'm using the multiple intent pipeline as suggested at []()http://blog.rasa.com/how-to-handle-multiple-intents-per-input-using-rasa-nlu-tensorflow-pipeline/. When I try the message "bom dia sair", Rasa predicts the intent "cumprimentar", and should be intent "cumprimentar+cancelar". Here is my NLU:

## intent:cumprimentar
 - ola
 - boa tarde
 - boa noite
 - oi
 - bom dia
 - dia

 ## intent:cancelar
 - desistir
 - cancelar
 - nao quero mais
 - estorno
 - sair
 - reembolso

 ## intent:cumprimentar+cancelar
  - ola desistir
  - oi cancelar
  - ola cancelar
  - oi desistir

**Comment by akelad** [comment]
Could you please fill out the issue template? Rasa nlu config, version you're using etc
