### ISSUE TITLE
what is the alternative of load_data() in rasa 0.13 and above versions

### ISSUE THREAD

**Issue by nuronics** [RasaHQ/rasa_nlu#1521]
_Originally posted by @nuronics in https://github.com/RasaHQ/rasa_nlu/issues/720#issuecomment-437366263_

**Comment by akelad** [comment]
not sure what you mean, this function still exists https://github.com/RasaHQ/rasa_nlu/blob/master/rasa_nlu/training_data/__init__.py#L10
Also please ask usage questions like this on our [forum](https://forum.rasa.com)
