### ISSUE TITLE
Server don't generate logs

### ISSUE THREAD

**Issue by adantoscano** [RasaHQ/rasa_nlu#1524]
**Rasa NLU version**: 0.13.7

- [ ] 

**Operating system**: Linux

**Issue**: 
Server don't generate logs. I tried with -w flag and creating a folder first but no results. I'm using a venv, could be that a problem?

**Comment by akelad** [comment]
Please provide some more details like what command you're running exactly and also what kind of logs you're looking for

**Comment by adantoscano** [comment]
I run:
`python -m rasa_nlu.server --path ./models -w ./logs`

and get
```bash
2018-11-13 16:30:04+0100 [-] Log opened.
2018-11-13 16:30:04+0100 [-] Site starting on 5000
2018-11-13 16:30:04+0100 [-] Starting factory <twisted.web.server.Site object at 0x7f6409c127f0>
```
then I do a post from postman and no logs is generated in logs folder, I tried without -w but same result

**Comment by akelad** [comment]
try adding the `--debug` flag and see if the logs get written then

**Comment by adantoscano** [comment]
now I get this:

`Logging of requests is disabled. (No 'request_log' directory configured)`

I thought request logs was active by default...

**Comment by adantoscano** [comment]
[Here](https://rasa.com/docs/nlu/evaluation/) says it's by default meanwhile with --hlep says 

```bash
--response_log RESPONSE_LOG
                        Directory where logs will be saved (containing queries
                        and responses).If set to ``null`` logging will be
                        disabled.
```

maybe it was default in older versions

**Comment by akelad** [comment]
Hmm, the link you sent me is to the evaluation page. In any case, seems like you found the solution, there's no default value for that flag so you need to pass it when launching the server

**Comment by adantoscano** [comment]
In that link say:

the Rasa NLU server will log every request made to the /parse endpoint to a file. By default these are saved in the folder logs.

But it's not by default
