### ISSUE TITLE
Query : Entity  and Training phrases

### ISSUE THREAD

**Issue by praveenkumart** [RasaHQ/rasa_nlu#1526]
**Rasa NLU version**:
rasa-core                0.11.12   
rasa-core-sdk            0.11.5    
rasa-nlu                 0.13.7
**Operating system** (windows, osx, ...):
Linux

**Content of model configuration file**:
```yml

```

**Issue**:

Train rasa nlu

Sample queries :

price of honda civic
price of toyota camry
price honda accord
price of honda amaze
price of toyota camry
price of toyota innova

.... so on.
I have 100+ different types of cars in my inventory database
do i need to create training set for all queries ?

in dialogflow there is an option to map entity values and entity name , is there anything like that in rasa nlu

**Comment by akelad** [comment]
Please ask these kind of questions in our [forum](https://forum.rasa.com)
