### ISSUE TITLE
Problems with nlu server project.py

### ISSUE THREAD

**Issue by basque21** [RasaHQ/rasa_nlu#1529]
**Rasa NLU version**:
0.13.5
**Operating system** (windows, osx, ...):
linux
**Issue**:
I'm trying to pre_load all the models with the server from local, but I'm facing an issue that in /project.py in the funcion `load_model(self)` it's calling to `model_name = self._dynamic_load_model()` without any argument, so it's impossible to set the `requested_model_name`. I changed it manually setting there my model name and it works but I don't know if this is the correct way. 
Please tell me something about it. Thanks

**Comment by akelad** [comment]
Thanks for raising this issue, @tmbo  will get back to you about it soon.

**Comment by tmbo** [comment]
There is a commandline option called `--pre_load all` that will load all the models - is that different from what you are trying to achieve?
