### ISSUE TITLE
Data augmentation stopped by lazyproperty

### ISSUE THREAD

**Issue by jamesmf** [RasaHQ/rasa_nlu#1531]
**Rasa NLU version**: 0.13.7

**Operating system** (windows, osx, ...): osx

**Issue**:
I'm trying to create a data augmentation Component that would sit at the head of a pipeline and extend the `training_data` to include augmented versions of the data. This is stymied downstream by the fact that the classifiers and featurizers might use the `.intent_examples` and `entity_examples` attributes, which are decorated with `@lazyproperty`. That makes it such that when I extend `.training_examples` to have more data, I don't manage to extend those two attributes, because they're lazy.

**Possible Solution**
If the `@lazyproperty` decorator was changed to support something like `@lazy_property.LazyWritableProperty` then it would be possible to have only special cases like this write to that property. So all featurizer/classifier functionality would remain the same, but a theoretical DataAugmentationComponent would be able to the `.entity_examples` and `.intent_examples` lazy attributes of the `training_data`. Basically something that allows you to force a non-lazy evaluation and reset that attribute.

**Comment by jamesmf** [comment]
Hmmm, this might be moot - looks like you can delete the _lazy_ part of the attribute and that forces re-computation. 

`del training_data._lazy_intent_examples`

Is that an actively poor practice?

**Comment by akelad** [comment]
Hey, what exactly does this data augmentation component do? As in, how does it augment the data?

**Comment by jamesmf** [comment]
It introduces new examples based on existing examples, but with typos, misspellings, etc.

Used as the first step in a pipeline, at train time it duplicates each member of `training_data.training_examples` but with a perturbed value of `text`. For `process` it just passes.
