### ISSUE TITLE
Dockerhub image latest-tensorflow and sklearn

### ISSUE THREAD

**Issue by rikhuijzer** [RasaHQ/rasa_nlu#1533]
**Rasa NLU version**: `latest-tensorflow` and `0.13.7-spacy` (both pulled from Docker hub on 15 November 2018)
**Operating system**: Ubuntu 18.04
**Content of model configuration file**: default for latest-tensorflow and 0.13.7-spacy

**Issue**: I'm trying to test `latest-tensorflow`. When training and sending requests to the container `0.13.7-spacy` it responds like it should. If I change my code such that it communicates with latest-tensorflow it fails on training. The response is:
`{'error': 'Not all required packages are installed. To use this pipeline, you need to install the missing dependencies. Please install sklearn'}`

I've done some further research, which might be useful: The Docker on Github clearly installs `alt_requirements/requirements_tensorflow_sklearn.txt` including sklearn. According to: `https://github.com/RasaHQ/rasa_nlu/issues/1315` it might be caused by missing `scipy` package. `scipy` is not included in `requirements_tensorflow_sklearn.txt` or `requirements_bar`. It is included for `requirements_spacy_sklearn.txt`.

**Comment by kleach** [comment]
#1534
