### ISSUE TITLE
Getting UniCodeDecodeError while training nlu model

### ISSUE THREAD

**Issue by NikhilBansal21** [RasaHQ/rasa_nlu#1541]
**Rasa NLU version**:0.13.7

**Operating system** (windows, osx, ...):win 10

**Content of model configuration file**:
language: "en"

pipeline:
- name: "tokenizer_whitespace"
- name: "intent_entity_featurizer_regex"
- name: "ner_crf"
- name: "ner_synonyms"
- name: "intent_featurizer_count_vectors"
- name: "intent_classifier_tensorflow_embedding"
  intent_tokenization_flag: true
  intent_split_symbol: "+"

**Issue**:

Hi,

I was given some data in a xls file where i copy-paste some utterances to the respective intents. But on training the nlu model with below command i.e -

> python -m rasa_nlu.train --c nlu_model_config.yml -d/ --data ./data -o projects

pls follow this link for more info - 

(https://forum.rasa.com/t/getting-unicodedecodeerror-while-training-nlu-model/2353)

**Comment by akelad** [comment]
Thanks for raising this issue, @EPedrotti  will get back to you about it soon.

**Comment by EPedrotti** [comment]
Hi @NikhilBansal21 ,
it seems that some non-printable characters ended up in you files, probably with the copy and paste from excel. Check your files for these characters and remove them. The error is pointing you at the location of the offending charcater. 

Let me know if this helps!
