### ISSUE TITLE
Unable to disable spacy pipeline components

### ISSUE THREAD

**Issue by laichunpongben** [RasaHQ/rasa_nlu#1544]
From spacy 2.x doc (https://spacy.io/usage/processing-pipelines#disabling), 
in order to disable spacy pipeline components, it uses the "disable" argument. For example, 
`nlp = spacy.load(spacy_model_name, disable=['parser', 'tagger', 'ner'])`

However, in utils/spacy_utils.py, it is
`nlp = spacy.load(spacy_model_name, parser=False)`
which seems to be obsolete.

I wonder if I could do the disabling in rasa_nlu config file. Thanks.

**Comment by akelad** [comment]
Thanks for raising this issue, @Ghostvv  will get back to you about it soon.

**Comment by Ghostvv** [comment]
this functionality is not supported from config, you would need to write a custom component
