### ISSUE TITLE
Env variables substitution in yaml config supports does not support more than one variable

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa_nlu#1552]
same as  https://github.com/RasaHQ/rasa_core/issues/1384#issuecomment-441234320

**Comment by akelad** [comment]
@wochinge is this still relevant?

**Comment by wochinge** [comment]
@akelad I guess this is a wontfix since after the merge it will be fixed by https://github.com/RasaHQ/rasa_core/pull/1705

**Comment by akelad** [comment]
ok i'll close then
