### ISSUE TITLE
Adding custom tokenizer SoMaJo

### ISSUE THREAD

**Issue by enryH** [RasaHQ/rasa_nlu#1553]
I wonder how difficult it would be to use predefined spacy word embeddings with a **custom tokenizer**. I would like to test [SoMaJo](https://github.com/tsproisl/SoMaJo) tokenization as it promises to separat joint words in German, e.g. *Autounfall* into *Auto* and *Unfall* as this can be expressed also as *Unfall mit dem Auto*.  

My main question to the maintainers:  Is it straightforward to "design" a new tokenizer as in [`rasa_nlu.tokenizers.spacy_tokenizer.py`](https://github.com/RasaHQ/rasa_nlu/blob/master/rasa_nlu/tokenizers/spacy_tokenizer.py) and add it as a [custom component](https://rasa.com/docs/nlu/customcomponents/#section-customcomponents)? 

If yes, I would try to tackle it.

Cheers,
Henry

**Comment by Ghostvv** [comment]
This is a promising idea. Custom `rasa_nlu` component should be a subclass of `Component` class: https://github.com/RasaHQ/rasa_nlu/blob/a0421db8a2566f3e3a22897042a96be5e679714d/rasa_nlu/components.py#L128

then you need to implement main methods like `train` (set examples' `tokens` property) and `process` (set message's `tokens` property). If your class needs to be persisted after training then `persist` and `load`.

Custom tokenizer should provide tokens: `provides = ["tokens"]`

**Comment by enryH** [comment]
Thanks for the hints! 
- Should I use the tree you specified in linking `rasa_nlu/rasa_nlu/components.py`? 

I had a look at the spacy_tokenizer Implementation:
https://github.com/RasaHQ/rasa_nlu/blob/a0421db8a2566f3e3a22897042a96be5e679714d/rasa_nlu/tokenizers/spacy_tokenizer.py#L19

If is see it correctly, then I need to provide a method `tokenize` which provides the token and its starting position? 

Does this example produce valid output which can be given to the `Token` Class?
```python
import spacy
nlp_de = spacy.load("de")
satz = nlp_de("Ich hatte einen Unfall mit meinem Auto.")
for token in satz:
    print( "token.text: {:>6}\ttoken.idx: {}".format(token.text, token.idx))
```
yielding
```
token.text:    Ich      token.idx: 0
token.text:  hatte      token.idx: 4
token.text:  einen      token.idx: 10
token.text: Unfall      token.idx: 16
token.text:    mit      token.idx: 23
token.text: meinem      token.idx: 27
token.text:   Auto      token.idx: 34
token.text:      .      token.idx: 38
```

**Comment by Ghostvv** [comment]
oh, unfortunately, it looks like it is not super helpful then. Thanks for trying and reporting results here.
Can we close an issue?

**Comment by enryH** [comment]
I agree. I will close it.
