### ISSUE TITLE
NLU server logging to files does not work

### ISSUE THREAD

**Issue by ricwo** [RasaHQ/rasa_nlu#1554]
**Rasa NLU version**: all

**Operating system** (windows, osx, ...): OSX

**Issue**:

Logging to files with `--write` option doesn't work. Replacing the `_configure_logging()` method in `rasa_nlu.server` fixes the problem:
```python
@staticmethod
    def _configure_logging(loglevel, logfile):
        for handler in logging.root.handlers[:]:
            logging.root.removeHandler(handler)
        logging.basicConfig(filename=logfile,
                            level=loglevel)
        logging.captureWarnings(True)
```
I'm not sure if there's a better approach.

Also, there is no command line option for `--loglevel` which that function is supposed to use.

**Comment by akelad** [comment]
@ricwo is this still relevant?

**Comment by ricwo** [comment]
yes, both issues are: 1. logging file isn't created, 2.`--loglevel` option doesn't exist
