### ISSUE TITLE
Rasa NLU story/domain editor

### ISSUE THREAD

**Issue by harrywang** [RasaHQ/rasa_nlu#1557]
I want to know whether there is any visual tool like the nlu trainer (https://github.com/RasaHQ/rasa-nlu-trainer) for editing the story and domain files.

**Comment by VPanjeta** [comment]
Hi @harrywang ,  
The stories and flow are a part of Rasa Core and not Rasa NLU. I doubt if there are visual editors available for Core.   
A quick github search brought me to a repo still under development but you can probably check it out if it suits you. Here's the repo: [Rasa Core GUI](https://github.com/veandco/rasa-core-gui)

**Comment by akelad** [comment]
Please ask these kind of questions in our [forum](https://forum.rasa.com)

**Comment by harrywang** [comment]
I found another one: https://github.com/samtecspg/articulate
