### ISSUE TITLE
Feature Enhancement: CLI Flag to output Correct Predictions

### ISSUE THREAD

**Issue by barakyo** [RasaHQ/rasa_nlu#1558]
**Rasa NLU version**: 0.13.8

We're trying to compare a current production model with a model that we're building with Rasa NLU. As part of our migration we want to compare how the two models handle the same input. The evaluate CLI tells us when our model has a different prediction, but we'd like to know if they have the same prediction to evaluate for false positives.

It would be awesome to add a CLI flag like `--successes successes.json` to get the output of all the correct predictions.

My team and I are willing to add this feature, if it will be accepted upstream.

Thanks!

**Comment by akelad** [comment]
this has been merged already
