### ISSUE TITLE
Bot answer error

### ISSUE THREAD

**Issue by Akshit99** [RasaHQ/rasa_nlu#1561]
**Rasa NLU version**:

**Operating system** (windows, osx, ...):
windows 7 
**Content of model configuration file**:
```yml

```

**Issue**:
Hey so whenever a bot answers something i get this line as well. Is there a way to remove this? I'm not that great in coding. Spare me if this is stupid?
![error](https://user-images.githubusercontent.com/34835800/49273378-b7c3bf00-f49a-11e8-916c-acfbcc1fd13e.PNG)

@JustinaPetr @akelad

**Comment by akelad** [comment]
This is the logs from the requests sent to the webhook, so no you can't get rid of it. It just means everything is working properly
