### ISSUE TITLE
Fix overlapping entities in evaluate script

### ISSUE THREAD

**Issue by akelad** [RasaHQ/rasa_nlu#1562]
Right now the evaluate script fails whenever there's any overlapping entity labels. It should only fail for overlapping entities *within* an entity classifier. In fact, I think it only actually makes sense for the `ner_crf`, given `ner_duckling_http` could identify both a number and a date in one which is fine.
PS. this causes evaluation on the platform to fail

**Comment by EPedrotti** [comment]
@akelad do we have an example of the offending data and/or error logs?

**Comment by akelad** [comment]
The website demo data causes this, and the error includes "overlapping entities". The error is thrown here: https://github.com/RasaHQ/rasa_nlu/blob/master/rasa_nlu/evaluate.py#L476 and the function is defined here: https://github.com/RasaHQ/rasa_nlu/blob/master/rasa_nlu/evaluate.py#L407
Basically, just add a check there whether the entity recogniser is `ner_crf`, if yes check for overlapping entities, if not then don't
