### ISSUE TITLE
Exception: Not all required packages are installed. To use this pipeline, you need to install the missing dependencies. Please install tensorflow

### ISSUE THREAD

**Issue by Manoj-t** [RasaHQ/rasa_nlu#1565]
**Rasa NLU version**: 0.13.8

**Operating system** (windows, osx, ...): MacOs Mojave version 10.14

**Content of model configuration file**:
```yml
language: en
pipeline: tensorflow_embedding

```
**Contents in nlu.md file**
## intent:greet
- hey
- hello
- hi
- good morning
- good evening
- hey there

## intent:restaurant_search
- i'm looking for a place to eat
- I want to grab lunch
- I am searching for a dinner spot
- i'm looking for a place in the [north](location) of town
- show me [chinese](cuisine) restaurants
- show me a [mexican](cuisine) place in this area
- i am looking for an [indian](cuisine) spot
- search for restaurants in the [center](location)
- anywhere in the [west](location)
- anywhere near [18328](location)
- I am looking for [asian fusion](cuisine) food
- I am looking a restaurant in [29432](location)

## synonym: indian
- Desi
- spicy
- Bharath

## synonym: center
- central
- midtown
- middle

## intent:thankyou
- thanks!
- thank you
- thx
- thanks very much

## intent:behavioral_greet
- how are you
- how is it going
- What is up
- What is going on

## intent:mood_great
- I am doing great
- I am absolutely alright
- I am fine
- great
- doing great

## intent:mood_unhappy
- I am not good
- I am so sad
- I am not happy
- I am sick

## intent:mood_deny
- No it didn't help
- I am not satisfied
- not okay

**Issue**: Not all required packages are installed. To use this pipeline, you need to install the missing dependencies. Please install tensorflow. But I have already installed tensorflow. I am attaching my .md file and .yml file as well. 

<img width="1425" alt="screen shot 2018-12-03 at 1 18 35 pm" src="https://user-images.githubusercontent.com/35119506/49402618-37ea5e80-f6ff-11e8-8221-3ed80f38514a.png">

**Comment by akelad** [comment]
Did you run `pip install rasa_nlu[tensorflow]`?

**Comment by Manoj-t** [comment]
Hii @akelad  my issue has got solved. Thanks for responding.

**Comment by davincif** [comment]
> Hii @akelad my issue has got solved. Thanks for responding.

How? please T.T
I'm having the same issue, but tensorflow and rasa_nlu are installed...

**Comment by shreyansbhardwaj** [comment]
I'm encountering the same issue as above, although I've been following all the steps mentioned.

**Comment by 913165** [comment]
C:\rasax\sara>nlu_model.py
Traceback (most recent call last):
  File "C:\rasax\sara\nlu_model.py", line 18, in <module>
    train_nlu('./data/data_rest2.json', 'config.yml', './models/nlu')
  File "C:\rasax\sara\nlu_model.py", line 8, in train_nlu
    trainer = Trainer(config.load(configs))
  File "C:\Users\Pritesh\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_nlu\model.py", line 147, in __init__
    components.validate_requirements(cfg.component_names)
  File "C:\Users\Pritesh\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_nlu\components.py", line 46, in validate_requirements
    "Please install {}".format(", ".join(failed_imports)))
Exception: Not all required packages are installed. To use this pipeline, you need to install the missing dependencies. Please install tensorflow
