### ISSUE TITLE
Check and possible uncomment volumes in full image

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa_nlu#1567]
In the NLU full docker image the volumes are commented out https://github.com/RasaHQ/rasa_nlu/blob/f619ea4559d27a5722bf32f989b273f9b3698cd0/docker/Dockerfile_full#L39 .

This is not the case for all the other images. 

Steps:

- [ ] check if there is a reason why it is commented out
- [ ] fix it (comment it in / remove the line)

**Comment by wrathagom** [comment]
@milutz you're the one who checked it in this way in https://github.com/RasaHQ/rasa_nlu/commit/c74e25c8cbc3f8d8c55e2e7743d6d86ff12bdaeb#diff-dad37a8818dd278b388b83c28579983a

Though that was a long time ago, not certain if you remember why that one is commented.
