### ISSUE TITLE
Lower-casing of Slots

### ISSUE THREAD

**Issue by loochy** [RasaHQ/rasa_nlu#1569]
**Rasa NLU version**:
0.13.5
**Operating system** (windows, osx, ...):
OSX (10.12.6)
**Content of model configuration file**:
```
language: "en"

pipeline: 
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "intent_entity_featurizer_regex"
- name: "intent_featurizer_spacy"
- name: "ner_crf"
- name: "ner_synonyms"
- name: "intent_featurizer_count_vectors"
- name: "intent_classifier_tensorflow_embedding"

path: "./models/nlu"

data: "./data/nlu.md"

```

**Issue**:
Sometimes the values filling the slots are (randomly?) put into all lowercase, even though the slot is clearly defined with First Caps. I don't want to just change everything to lowercase because I use the filled slots to display text on the screen and as indexes in a database, so the case needs to match. 

Most of the time the case is maintained, but sometimes it is lowercased. I checked all the entries defining the entity/slots and can't find any inconsistency.

Example from interactive training with one slot (although it happens with other slots as well) :
```
i want the Indigenous Awareness training
------
Chat history:

	bot did:	action_listen

	user did:	task_complete

	with Training:	Indigenous Awareness

	bot did:	action_task_complete

	bot did:	action_listen

	user said:	i want the Indigenous Awareness training

		 whose intent is:	get_Training

	with Training:	indigenous awareness

we currently have slots: About: None, Account: None, Acronym: None, Benefit: None, Health_Safety: None, Help: None, Networking: None, Training: indigenous awareness

------
The bot wants to [action_get_Training] due to the intent. Is this correct?

	1.	Yes
	2.	No, intent is right but the action is wrong
	3.	The intent is wrong
	0.	Export current conversations as stories and quit
```
Compare with a case where it works properly (for some reason):
```
awareness training
------
Chat history:

	bot did:	action_listen

	user did:	get_Training

	with Training:	indigenous awareness

	bot did:	action_get_Training

	bot did:	action_listen

	user said:	awareness training

		 whose intent is:	get_Training

	with Training:	Indigenous Awareness

we currently have slots: About: None, Account: None, Acronym: None, Benefit: None, Health_Safety: None, Help: None, Networking: None, Training: Indigenous Awareness

------
The bot wants to [action_get_Training] due to the intent. Is this correct?

	1.	Yes
	2.	No, intent is right but the action is wrong
	3.	The intent is wrong
	0.	Export current conversations as stories and quit
```
The domain entities look like this:
```
entities:
  - Training
  - [etc.]
slots:
  Training:
    type: categorical
    values:
    - Orientation
    - IT Security
    - Indigenous Awareness
  [Etc.]
```
In the nlu.md training data these slots are defined like this:
```
## synonym:Indigenous Awareness
- awareness training
- Indigenous Awareness
- Indigenous training
- indiginous training
- indegenous awareness

## intent:get_Training
- What training do I do next?
- What is the [Indigenous Awareness](Training:Indigenous Awareness)
- [Indigenous Awareness](Training:Indigenous Awareness)
- [etc.]
```
Apologies if I'm missing something obvious, or if this should be a question rather than an issue, but I can't find information about this problem. 

Cheers.

**Comment by akelad** [comment]
Thanks for raising this issue, @Ghostvv  will get back to you about it soon.

**Comment by Ghostvv** [comment]
Hi, thank you for raising the issue, is it possible for you to share some training data so I can reproduce it?

**Comment by loochy** [comment]
Hey, @Ghostvv, sorry for not getting back to you sooner. I have attached the nlu.md file (extension changed to .txt for upload). Thanks!
[nlu.txt](https://github.com/RasaHQ/rasa_nlu/files/2692148/nlu.txt)

**Comment by Ghostvv** [comment]
Thank you for the training data. `tokenizer_spacy` that you use returns lower case text for `ner_crf`. Therefore `ner_crf` returned lowercase extracted entity, but you didn't have `indigenous awareness` as a synonym for `Indigenous Awareness`

**Comment by loochy** [comment]
But 'indigenous awareness' does successfully fill the 'Training' slot (shown in my example above), which is marked as categorical but doesn't use one of the values listed in the domain (which have FirstCap). I can add the lowercase synonym, however I feel like this issue will come up when a user inputs a different lower case spelling that should be close enough to fill the slot, but may come out lowercase. Do you suggest a different tokenizer/pipeline? 

Also, I think I might be missing some of the docs about the nlu piplines. I'm trying to understand better step-by-step what is happening, but I'm not really getting that here: 

https://rasa.com/docs/nlu/components/

Tokenizer_spacy is there, but doesn't say anything about lowercasing, and I could not easily find that on Spacy either (https://spacy.io/api/tokenizer). The example given does not lowercase (https://spacy.io/usage/spacy-101#annotations-token). Is there documentation I'm missing about the pipelines and components that you can point me to so I can see the clear input/output and method description of each? 

Thanks

**Comment by loochy** [comment]
I'm a bit confused as to why the form listed in the domain/nlu.md 'Indigenous Awareness' only maps to 'indigenous awareness', but other listed synonyms like 'awareness training' maps to the correct 'Indigenous Awareness' (as per the example). Is it just because the NER component never sees the original non-lowercased form?

**Comment by Ghostvv** [comment]
tokenizer spacy uses spacy doc created bu `nlp_spacy`, which has config parameter `case_sensitive`: https://rasa.com/docs/nlu/components/#nlp-spacy

**Comment by loochy** [comment]
Ok thanks, I'm trying out the case sensitive option. 

Is there anything to be said about mapping to a categorical slot value when the exact synonym is not listed in the nlu training data? To me, this appears to be part of why the issue came up in the first place.

**Comment by Ghostvv** [comment]
sorry, I don't understand your question, setting a slot is independent process from extraction. The issue was due to the fact that `case_sensitive: false` by default
