### ISSUE TITLE
Module Not Found Error

### ISSUE THREAD

**Issue by santannamv** [RasaHQ/rasa_nlu#1570]
**Rasa NLU version**:13.8

**Operating system**: Windows 10 

**Content of model configuration file**:
```yml

```

**Issue**:
Please, I am trying to train the model in weatherbot tutorial and I am getting this error on CMD:

Traceback (most recent call last): File “nlu_model.py”, line 1, in from rasa_nlu.converters import load_data ModuleNotFoundError: No module named ‘rasa_nlu.converters’

Anything else I should inform here?

**Comment by akelad** [comment]
@santannamv please post these kind of questions in our forum. This isn't related to the code itself here, but an external tutorial

**Comment by santannamv** [comment]
Sorry. Understood.
