### ISSUE TITLE
Replace pytest-pep8 with pytest-codestyle

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa_nlu#1571]
Pep8 was replaced by pycodestyle.
Hence, `pytest-pep8` is not longer maintained and has to be replaced with `pytest-pycodestyle` (https://pypi.org/project/pytest-pycodestyle/)

Branch with implementation:
- https://github.com/RasaHQ/rasa_nlu/tree/pycodestyle (merging is currently blocked since `pytest-pycodestyle` does not support Python 2.7)

Steps:
- [x] replace dependencies in `requirements.txt` and `setup.py`
- [x] configure line length etc in `setup.cfg`
- [x] adapt `.travis`
- [x] fix new found linter errors
- [x] change line length to 80

see https://github.com/RasaHQ/rasa_core/pull/1446/files for the first three points

**Comment by wochinge** [comment]
@wrathagom Are you working on this? Otherwise I'd do that tomorrow.

**Comment by tmbo** [comment]
@wochinge this is in blocked because we need to drop support for py2 first, right? is there a branch where you implemented the change?

**Comment by wochinge** [comment]
https://github.com/RasaHQ/rasa_nlu/tree/pycodestyle

**Comment by tmbo** [comment]
@wochinge as discussed, I've moved this out of blocked. Just merged https://github.com/RasaHQ/rasa_nlu/pull/1642 so you can do the necessary changes for pycodestyle on a fresh branch from master
