### ISSUE TITLE
entity_synonyms are not recognized

### ISSUE THREAD

**Issue by Manoj-t** [RasaHQ/rasa_nlu#1574]
**Rasa NLU version**: 0.13.8

**Operating system** (windows, osx, ...): macOS mojave version 10.14

**Content of model configuration file**:
```yml
language: en
pipeline: tensorflow_embedding
```
**Contents of nlu.md file**
## intent:greet
- hey
- hello
- hi
- good morning
- good evening
- hey there

## intent:restaurant_search
- i'm looking for a place to eat
- I want to grab lunch
- I am searching for a dinner spot
- food near me
- restaurants near me
- place near me to eat
- i'm looking for a place in the [north](location) of town
- show me [chinese](cuisine) restaurants
- show me a [mexican](cuisine) place in this area
- i am looking for an [indian](cuisine) spot
- search for restaurants in the [center](location)
- anywhere in the [west](location)
- anywhere near [18328](location)
- I am looking for [asian fusion](cuisine) food
- I am looking a restaurant in [29432](location)

## synonym:indian
- Desi
- spicy
- Bharath

## synonym:center
- central
- midtown
- middle

## intent:thankyou
- thanks!
- thank you
- thx
- thanks very much
- thanks
- thankyou very much
- thanks a lot
- thanks. Have a nice day
- thanks. have a good one.
- have a good one

## intent:mood_great
- I am doing great
- I am absolutely alright
- I am fine
- I am happy. How about you
- fine
- alright
- good
- going good
- doing good
- happy
- superb
- All good. How are you?
- great
- doing great
- I am good
- absolutely fine

## intent:mood_unhappy
- I am not good
- I am so sad
- I am not happy
- I am sick

## intent:mood_deny
- No it didn't help
- I am not satisfied
- not okay

**Issue**: 
<img width="1435" alt="screen shot 2018-12-06 at 12 24 22 pm" src="https://user-images.githubusercontent.com/35119506/49620888-cc5ef600-f977-11e8-9fdc-2d01f0fe49e3.png">

I have defined synonyms in my nlu.md file. I have trained the model. but when I ran the model with some example message including synonyms in it. model is not recognising those entities.

**Comment by wrathagom** [comment]
Please see the [docs](https://rasa.com/docs/nlu/dataformat/#entity-synonyms) for this note:

> Note
> Please note that adding synonyms using the above format does not improve the model’s classification of those entities. Entities must be properly classified before they can be replaced with the synonym value.

**Comment by Manoj-t** [comment]
Hello @wrathagom Can you please tell me how to properly classify entities before they can be replaced with synonym value? I am very much new to python, Rasa stack. I have been using markdown format to define stories, but recently I changed it to json format. can you review my stories file.

**nlu.json**

{
  "rasa_nlu_data": {
    "common_examples": [
      {
        "text": "hey",
        "intent": "greet",
        "entities": []
      },
      {
        "text": "howdy",
        "intent": "greet",
        "entities": []
      },
      {
        "text": "hey there",
        "intent": "greet",
        "entities": []
      },
      {
        "text": "hello",
        "intent": "greet",
        "entities": []
      },
      {
        "text": "hi",
        "intent": "greet",
        "entities": []
      },
      {
        "text": "i'm looking for a place to eat",
        "intent": "restaurant_search",
        "entities": []
      },
      {
        "text": "i'm looking for a place in the north of town",
        "intent": "restaurant_search",
        "entities": [
          {
            "start": 31,
            "end": 36,
            "value": "north",
            "entity": "location"
          }
        ]
      },
      {
        "text": "show me chinese restaurants",
        "intent": "restaurant_search",
        "entities": [
          {
            "start": 8,
            "end": 15,
            "value": "chinese",
            "entity": "cuisine"
          }
        ]
      },
      {
        "text": "yes",
        "intent": "affirm",
        "entities": []
      },
      {
        "text": "yep",
        "intent": "affirm",
        "entities": []
      },
      {
        "text": "yeah",
        "intent": "affirm",
        "entities": []
      },
      {
        "text": "show me a mexican place in the centre",
        "intent": "restaurant_search",
        "entities": [
          {
            "start": 31,
            "end": 37,
            "value": "centre",
            "entity": "location"
          },
          {
            "start": 10,
            "end": 17,
            "value": "mexican",
            "entity": "cuisine"
          }
        ]
      },
      {
        "text": "bye",
        "intent": "goodbye",
        "entities": []
      },
      {
        "text": "goodbye",
        "intent": "goodbye",
        "entities": []
      },
      {
        "text": "good bye",
        "intent": "goodbye",
        "entities": []
      },
      {
        "text": "stop",
        "intent": "goodbye",
        "entities": []
      },
      {
        "text": "end",
        "intent": "goodbye",
        "entities": []
      },
      {
        "text": "i am looking for an indian spot",
        "intent": "restaurant_search",
        "entities": [
          {
            "start": 20,
            "end": 26,
            "value": "indian",
            "entity": "cuisine"
          }
        ]
      },
      {
        "text": "search for restaurants",
        "intent": "restaurant_search",
        "entities": []
      },
      {
        "text": "anywhere in the west",
        "intent": "restaurant_search",
        "entities": [
          {
            "start": 16,
            "end": 20,
            "value": "west",
            "entity": "location"
          }
        ]
      },
      {
        "text": "central indian restaurant",
        "intent": "restaurant_search",
        "entities": [
          {
            "start": 0,
            "end": 7,
            "value": "central",
            "entity": "location"
          },
          {
            "start": 8,
            "end": 14,
            "value": "indian",
            "entity": "cuisine"
          }
        ]
      },
      {
        "text": "indeed",
        "intent": "affirm",
        "entities": []
      },
      {
        "text": "that's right",
        "intent": "affirm",
        "entities": []
      },
      {
        "text": "ok",
        "intent": "affirm",
        "entities": []
      },
      {
        "text": "great",
        "intent": "affirm",
        "entities": []
      }
    ],
    "entity_synonyms": [
      {
        "value": "indian",
        "synonyms": [
          "desi",
          "spicy",
          "bharath"
        ]
      }
    ]
  }
}
