### ISSUE TITLE
how can I automate the intent creation from large data?

### ISSUE THREAD

**Issue by DhruvMevada** [RasaHQ/rasa_nlu#1576]
**Rasa NLU version**:

**Operating system** (windows, osx, ...):

**Content of model configuration file**:
```yml

```

**Issue**: Right now if there is less data then we can manually identify the data and put into right intent.
But what if we have large data? is there any automate way to classify it?

**Comment by wrathagom** [comment]
You'd be exchanging one machine learning problem for another. Sure you could train something to label it for you, but that is more or less what you are trying to do with Rasa.

Do you have a reason to believe you need large data?

This question seems better suited to the forums, so if you have more questions create a post there: https://forum.rasa.com
