### ISSUE TITLE
evaluate endpoint seems to be blocking

### ISSUE THREAD

**Issue by znat** [RasaHQ/rasa_nlu#1577]
**Rasa NLU version**:0.13.7

**Operating system** (windows, osx, ...): All

**Issue**:

`evaluate` endpoint seems to be blocking preventing any other endpoint to respond, including `/`. One consequence is that evaluation is impossible to evaluate on K8S clusters because of the induced latency on the health endpoint.

**Comment by akelad** [comment]
Thanks for raising this issue, @ricwo  will get back to you about it soon.

**Comment by ricwo** [comment]
@znat currently the `DataRouter` only delegates training to separate processes, and this hasn't been implemented for evaluations yet. This would be a useful feature if you like to raise a PR 🙂

**Comment by ricwo** [comment]
@znat we've moved to a new fully asynchronous webserver. can you let us know if you still experience this problem with the latest version of Rasa Stack? (intent evaluations are now in the Core server at `POST /intentEvaluation`)
