### ISSUE TITLE
Problem with overriding default values in tensorflow intent classification

### ISSUE THREAD

**Issue by hejazizo** [RasaHQ/rasa_nlu#1578]
**Rasa NLU version**: 0.14.0a1

**Operating system** (windows, osx, ...): Linux

**Issue**:
 `intent_classifier_tensorflow_embedding` does not override the default values.

**How to Reproduce**:
```
- name: "intent_classifier_tensorflow_embedding"
  "epochs": 100
```
does not override the default value of epochs (300) with 100.

**Comment by hejazizo** [comment]
I might know how to fix this.
`component_config` dict is not passed to `self._load_params()` in `embedding_intent_classifier.py` constructor.

Should I create a pull request for this?

**Comment by akelad** [comment]
@Ghostvv i believe we fixed this right? Or at least there's already an open PR for this?

**Comment by Ghostvv** [comment]
This should be fixed by this PR: https://github.com/RasaHQ/rasa_nlu/pull/1547
