### ISSUE TITLE
I am getting this error while trying to train rasa_nlu using the given command in website

### ISSUE THREAD

**Issue by saikat-bhattacharya** [RasaHQ/rasa_nlu#1581]
Command I am using: `python -m rasa_nlu.train -c nlu_config.yml --data nlu.md -o models --fixed_model_name nlu --project current --verbose`

<img width="1041" alt="screenshot 2018-12-11 at 5 39 13 pm" src="https://user-images.githubusercontent.com/43814494/49799876-1414c180-fd6c-11e8-90e3-98fcf75dcd5a.png">

**Comment by akelad** [comment]
Can you check which numpy/tensorflow versions you have installed? Make sure they match with the requirements of rasa nlu

**Comment by saikat-bhattacharya** [comment]
> Can you check which numpy/tensorflow versions you have installed? Make sure they match with the requirements of rasa nlu

Tensorflow - 1.12.0
Numpy - 1.15.4
