### ISSUE TITLE
ner_crf does not respect regex

### ISSUE THREAD

**Issue by tijsg** [RasaHQ/rasa_nlu#1586]
**Rasa NLU version**: 0.13.8

**Operating system** (windows, osx, ...): MacOS High Sierra 10.13.4

**Content of model configuration file**:
```yml
language: "nl"

pipeline: "spacy_sklearn"
```

**Issue**:
When specifying a regex for a custom entity called 'psp' in the NLU training data, the regex is not correctly applied.

From nlu.md:

```
## intent: inform
- de psp pm is [0123456789](psp)
- de PSP PM is [6541323543](psp)
- [8547132541](psp)
- [9574657674](psp)
- [7527214272](psp)
- [5725275247](psp)
- [7427427527](psp)
- [8352407275](psp)
- [1757427558](psp)
- [7571227575](psp)

## regex:psp
- ^[0-9]{10}$
```

The following regex `^[0-9]{10}$` should only accept 10 digit numbers, but when it's shorter or longer, it's also mapped to the custom entity.
It's picked up by ner_crf.

From the logs:
`entities '[{u'extractor': u'ner_crf', u'confidence': 0.8953123891331077, u'end': 5, u'value': u'12345', u'entity': 'psp', u'start': 0}]'`

`entities '[{u'extractor': u'ner_crf', u'confidence': 0.8953123891331077, u'end': 22, u'value': u'6516486464648468867461'`

**Comment by akelad** [comment]
it does, though regex features are just features. As in, the features are used to train the entity recognizer, but it's not a strict rule for extracting the entity. If you'd like to make sure you only use numbers with 10 digits, then you can either use the FormAction or a custom action in Rasa Core
