### ISSUE TITLE
Memory Increases with Every Training Even-though Unloading Model. How to release memory?

### ISSUE THREAD

**Issue by mjordan007** [RasaHQ/rasa_nlu#1589]
**Rasa NLU version**:0.14

**Operating system** (windows, osx, ...):Windows

**Content of model configuration file**: spacy, duckling.
```yml

```

**Issue**:

The case we're trying to guard against is that if you are continuously running a server and training models, the old ones never get unloaded automatically and Rasa's memory footprint will monotonically increase. 

While training it for the first time, it takes almost ~3 GB memory. Again, training a same project, now it's consuming total ~6 GB Memory for two model. To summarize, now I have two model and loaded in memory. After that I send request for unload old one. Now memory consummation decreased but not all memory will be released. Now it's consuming ~5 GB memory. I was wondering how to release rest of ~2 GB memory. logically it should release whole ~3 GB memory of old model. Any idea how to release rest of the memory?

Many thanks for your time and help.

**Comment by wochinge** [comment]
Thanks for raising this issue, @MetcalfeTom will get back to you about it soon.

**Comment by MetcalfeTom** [comment]
Hi @mjordan007,

No worries!  I'm already looking into this issue for another user.  Since your issues are almost identical, I'm closing this one so please post any relevant updates in [this thread](https://github.com/RasaHQ/rasa_nlu/issues/1585).
