### ISSUE TITLE
Should update spacy dependency

### ISSUE THREAD

**Issue by adantoscano** [RasaHQ/rasa_nlu#1593]
**Rasa NLU version**: 0.13.8

**Operating system** (windows, osx, ...): Manjaro

**Issue**:
Install Spacy with `pip install rasa_nlu[spacy]` gives you a dependency error that was fixed at spacy==2.0.18

**Comment by wochinge** [comment]
Thanks for raising this issue, @tmbo will get back to you about it soon.

**Comment by tmbo** [comment]
@adantoscano What is the spacy version which is creating the issue? Can you please also add the error details here?

for reference, spacy is pinned to an interval https://github.com/RasaHQ/rasa_nlu/blame/master/setup.py#L52

**Comment by wochinge** [comment]
We also should do this so we can remove `msgpack` and `msgpack-python` from our dependencies. Rasa Core is currently pinning this dependency because of https://github.com/explosion/spaCy/issues/2995 , which was also fixed in `2.0.18`.
