### ISSUE TITLE
How can I use the GPU to trainer the model

### ISSUE THREAD

**Issue by andy51002000** [RasaHQ/rasa_nlu#1594]
**Rasa NLU version**:
0.13.2
**Operating system** (windows, osx, ...):
ubuntu 16.04

**Issue**:
The training time is too long, I'm wondering it is possible to use the GPU to trainer the model. If so, how can I do

**Comment by wochinge** [comment]
Please ask usage questions in our [forum](https://forum.rasa.com).
Also see this issue https://github.com/RasaHQ/rasa_nlu/issues/1324.
