### ISSUE TITLE
inconsistency between dates extracted by duckling directly vs the post processed rasa nlu entities

### ISSUE THREAD

**Issue by Greg3108** [RasaHQ/rasa_nlu#1597]
**Rasa NLU version**: 0.14

**Issue**:
Looks like there's some inconsistency between dates/intervals extracted directly by duckling and then how rasa_nlu turns that into extracted entities. 
For "How many products do I have between 1/1/2017 to 31/1/2017", the returned result contains one date. And, if I enter the following query "How many products do I have between 1-1-2017 and 31-1-2017", the returned results contain "from" and "to" values but both of them are the same ('2017-01-01T02:00:00.000-08:00') which is incorrect.

**Comment by MetcalfeTom** [comment]
Hi @Greg3108,

Does duckling pick up on these entities at all?

**Comment by ahmad-abdellatif** [comment]
I am facing the same issue. Duckling picks the first date only. Here is part of the output JSON of my bot:

`  "project": "current",
  "entities": [
    {
      "extractor": "ner_duckling_http",
      "confidence": 1.0,
      "end": 34,
      "text": "1/1/2017",
      "value": "2017-01-01T00:00:00.000-08:00",
      "entity": "time",
      "start": 26,
      "additional_info": {
        "grain": "day",
        "values": [
          {
            "type": "value",
            "grain": "day",
            "value": "2017-01-01T00:00:00.000-08:00"
          }
        ],
        "value": "2017-01-01T00:00:00.000-08:00",
        "type": "value"
      }
    },
    {
      "extractor": "ner_duckling_http",
      "confidence": 1.0,
      "end": 47,
      "text": "1/2017",
      "value": "2017-01-01T00:00:00.000-08:00",
      "entity": "time",
      "start": 41,
      "additional_info": {
        "grain": "day",
        "values": [
          {
            "type": "value",
            "grain": "day",
            "value": "2017-01-01T00:00:00.000-08:00"
          }
        ],
        "value": "2017-01-01T00:00:00.000-08:00",
        "type": "value"
      }
    }
  ],
`

Here is the YML file configurations:
`language: "en"
pipeline:
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "intent_featurizer_count_vectors"
- name: "intent_entity_featurizer_regex"
- name: "intent_classifier_tensorflow_embedding"
- name: "ner_crf"
- name: "ner_duckling_http"
  url: "http://127.0.0.1:8000"
  dimensions: ["time"]`

**Comment by akelad** [comment]
There's not much we can do about this since the code for duckling isn't ours. Please raise an issue on their repo instead

**Comment by ahmad-abdellatif** [comment]
I agree with you @akelad that Duckling is not Rasa. But, if I pass the same query (passed to Rasa) to the Duckling container, it returns me the correct dates.

**Comment by akelad** [comment]
oh, sorry, i wasn't aware of that! i'll reopen this issue and we'll take a look

**Comment by akelad** [comment]
Just to confirm, when you enter "'How many products do I have between 1-January-2017 and 31-January-2017'" directly to the container, it gives you both dates, but Rasa nlu only gives you one date?

**Comment by ahmad-abdellatif** [comment]
> @ahmad-abdellatif Have you tried putting duckling_http earlier in the pipeline?

Yes, and I still get the same result.



> Just to confirm, when you enter "'How many products do I have between 1-January-2017 and 31-January-2017'" directly to the container, it gives you both dates, but Rasa nlu only gives you one date?

Yes, but to be more precise, this is the query "How many products do I have between 1/1/2017 to 31/1/2017", the returned result contains one date. And, if I enter the following query "How many products do I have between 1-1-2017 and 31-1-2017", the returned results contain "from" and "to" values but both of them are the same ('2017-01-01T02:00:00.000-08:00') which is incorrect.

**Comment by akelad** [comment]
alright thank you, we'll look into this

**Comment by erohmensing** [comment]
Hey @ahmad-abdellatif, it seems that using `language: "en"` defaults duckling to search for `mm/dd/yy format`. Please add `locale: 'en_GB'` to your pipeline -- this should fix the problem. 

```language: "en"
pipeline:
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "intent_featurizer_count_vectors"
- name: "intent_entity_featurizer_regex"
- name: "intent_classifier_tensorflow_embedding"
- name: "ner_crf"
- name: "ner_duckling_http"
  url: "http://127.0.0.1:8000"
  dimensions: ["time"]
  locale: 'en_GB'
```
P.S.  Correct output will include a `to` value of `'2017-02-01T00:00:00.000-08:00'` as it will include the entire day of 31-January-2017.

**Comment by rabinpoudyal** [comment]
Similar issue here:
![image](https://user-images.githubusercontent.com/20385396/99552237-de12fa00-29e4-11eb-9a47-25387352c2c6.png)

Solution:
Duckling gives the outer bounds for interval extraction. You can subtract the grain value from the bound. For example, from custom action you can do (to-grain)
