### ISSUE TITLE
Spacy time identification not working properly 

### ISSUE THREAD

**Issue by Greg3108** [RasaHQ/rasa_nlu#1598]
**Rasa NLU version**:0.14

**Operating system** (windows, osx, ...): windows

**Content of model configuration file**:
```yml

```

**Issue**:
While working with spacy time identification, sometimes, it identifies Q1-2017 and sometimes it doesn't. Is there any specific reason which might prevent it from identifying? We are using English - en_core_web_lg (v2.0.0) model (Large).

**Comment by akelad** [comment]
I don't think this is a Rasa NLU related problem, but a spacy problem. I'd recommend using duckling for time identification
