### ISSUE TITLE
Error while parsing input to trained data

### ISSUE THREAD

**Issue by Chidhambararajan** [RasaHQ/rasa_nlu#1600]
Hello there,

I am new to rasa nlu, my model got trained but when i try to implement it , i get a similar error

Code:

`from rasa_nlu.model import Interpreter`
`import json`
`interpreter = Interpreter.load("models/current/nlu")`
`message = "let's see some italian restaurants"`
`result = interpreter.parse(message)`
`print(json.dumps(result, indent=2))`

Error:
`Traceback (most recent call last):`
`  File "trained_model_test.py", line 5, in <module>`
`   result = interpreter.parse(message)`
`  File "/home/captain-america/.local/lib/python3.6/site-packages/rasa_nlu/model.py", line 357, in parse    component.process(message, **self.context)`
`  File "/home/captain-america/.local/lib/python3.6/site-packages/rasa_nlu/classifiers/sklearn_intent_classifier.py", line 181, in process`
`    intents = self.transform_labels_num2str(intent_ids)`
`  File "/home/captain-america/.local/lib/python3.6/site-packages/rasa_nlu/classifiers
/sklearn_intent_classifier.py", line 115, in transform_labels_num2str`
`    return self.le.inverse_transform(y)`
`  File "/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/label.py", line 273, in inverse_transform`
`    y = column_or_1d(y, warn=True)`
`  File "/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py", line 797, in column_or_1d`
`    raise ValueError("bad input shape {0}".format(shape))`
`ValueError: bad input shape (1, 3)`

Thanks in Advance!!

**Comment by wochinge** [comment]
Thanks for raising this issue, @EPedrotti  will get back to you about it soon.

**Comment by pspathakmsft** [comment]
This is due to scikit-learn version mismatch. Please use **pip install scikit-learn==0.19.1** and that should resolve this prolem.

Hope this helps!

Regards,
PS

**Comment by Chidhambararajan** [comment]
yeah it worked!

**Comment by Chidhambararajan** [comment]
The above mentioned error didnt come, but i got a different one
```
/usr/lib/python3/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type.
  from ._conv import register_converters as _register_converters
/usr/local/lib/python3.6/dist-packages/sklearn/base.py:311: UserWarning: Trying to unpickle estimator LabelEncoder from version 0.20.2 when using version 0.19.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/base.py:311: UserWarning: Trying to unpickle estimator SVC from version 0.20.2 when using version 0.19.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/base.py:311: UserWarning: Trying to unpickle estimator GridSearchCV from version 0.20.2 when using version 0.19.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
Traceback (most recent call last):
  File "trained_model_test.py", line 5, in <module>
    result = interpreter.parse(message)
  File "/home/captain-america/.local/lib/python3.6/site-packages/rasa_nlu/model.py", line 357, in parse
    component.process(message, **self.context)
  File "/home/captain-america/.local/lib/python3.6/site-packages/rasa_nlu/classifiers/sklearn_intent_classifier.py", line 180, in process
    intent_ids, probabilities = self.predict(X)
  File "/home/captain-america/.local/lib/python3.6/site-packages/rasa_nlu/classifiers/sklearn_intent_classifier.py", line 222, in predict
    pred_result = self.predict_prob(X)
  File "/home/captain-america/.local/lib/python3.6/site-packages/rasa_nlu/classifiers/sklearn_intent_classifier.py", line 210, in predict_prob
    return self.clf.predict_proba(X)
  File "/usr/local/lib/python3.6/dist-packages/sklearn/utils/metaestimators.py", line 109, in __get__
    getattr(delegate, self.attribute_name)
  File "/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py", line 590, in predict_proba
    self._check_proba()
  File "/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py", line 559, in _check_proba
    if self._impl not in ('c_svc', 'nu_svc'):
AttributeError: 'SVC' object has no attribute '_impl'
```

Is this issue because of python3 usage or anything else, Thanks for answering the prev question and thanks in advance for this one

**Comment by pspathakmsft** [comment]
Are you running Python 3.6.6 ? if yes, then upgrading/downgrading should fix it.

Hope this helps!

PS

**Comment by Chidhambararajan** [comment]
it is python3.6.7

**Comment by Chidhambararajan** [comment]
I am currently running python3.6.7 , to what version should i shift in py3

**Comment by pspathakmsft** [comment]
@Chidhambararajan please make sure scikit version as **scikit-learn==0.19.1**

**Comment by Chidhambararajan** [comment]
Yeah thank you so much!! it was a small confusion from my side, now its working!!!
