### ISSUE TITLE
how to install the corresponding version of rasa_core

### ISSUE THREAD

**Issue by 1090590768** [RasaHQ/rasa_nlu#1602]
**Rasa NLU version**:0.12.3
python version：3.6.7
mitie version：0.5.0
scikit-learn version：0.19.1
**Issue**:

I have installed rasa_nlu 0.12.3, how to install the corresponding version of rasa_core

**Comment by 1090590768** [comment]
I want to build a chatbot

**Comment by akelad** [comment]
`pip install rasa_core`
