### ISSUE TITLE
Add a main function wrapper in server.py ?

### ISSUE THREAD

**Issue by parthsharma1996** [RasaHQ/rasa_nlu#1616]
**Rasa NLU version**: 0.13.8

**Operating system** (windows, osx, ...): Arch Linux 4.20

**Issue**: 

I was thinking of writing a python script to allow for novice users in our project to directly run multiple `rasa_nlu` HTTP servers with without worrying about the arguments such as `--path`, `--port` etc. 

However, it seems that the `if` block to allow the module to be run as a standalone script is a bit lengthy in `rasa_nlu/server.py`

``` python
 if __name__ == '__main__':
    # Running as standalone python application
    cmdline_args = create_argument_parser().parse_args()

    utils.configure_colored_logging(cmdline_args.loglevel)
    pre_load = cmdline_args.pre_load

    _endpoints = read_endpoints(cmdline_args.endpoints)

    router = DataRouter(
            cmdline_args.path,
            cmdline_args.max_training_processes,
            cmdline_args.response_log,
            cmdline_args.emulate,
            cmdline_args.storage,
            model_server=_endpoints.model,
            wait_time_between_pulls=cmdline_args.wait_time_between_pulls
    )
    if pre_load:
        logger.debug('Preloading....')
        if 'all' in pre_load:
            pre_load = router.project_store.keys()
        router._pre_load(pre_load)

    rasa = RasaNLU(
            router,
            cmdline_args.loglevel,
            cmdline_args.write,
            cmdline_args.num_threads,
            cmdline_args.token,
            cmdline_args.cors,
            default_config_path=cmdline_args.config
    )

    logger.info('Started http server on port %s' % cmdline_args.port)
    rasa.app.run('0.0.0.0', cmdline_args.port)
```

Thus running the servers by importing `rasa_nlu.server` would require me to duplicate most of this code in my file, which seems like an unsatisfactory solution to me.

At this point I can see three possible solutions to this:-

1. Use a bash script instead and directly pass the command line arguments
2. Wrap all the code in the `if` block in a `main()` function and pass `cmdline_args` to it. Submit a PR
3. Use a python script and use `subprocess.Popen` and pass command line arguments to that.

1 and 2 both seem like promising solutions to me right now. 3 seems needlessly wasteful. 

Wanted to know if solution 2 is worth it and should I go ahead with it?

----
Reference :https://stackoverflow.com/a/3783185/5046549

**Comment by akelad** [comment]
Thanks for raising this issue, @wochinge  will get back to you about it soon.

**Comment by wochinge** [comment]
@parthsharma1996 I think the easiest would indeed be to use a bash script or Makefiles as we are using here `https://github.com/RasaHQ/rasa_core/blob/master/examples/concertbot/Makefile`.
However, there are a few ideas to redesign the cli all together and that's a good thing to consider :+1:
