### ISSUE TITLE
tensorflow - word embeding with n-grams?

### ISSUE THREAD

**Issue by ctrado18** [RasaHQ/rasa_nlu#1619]
Is it possible like with fasttext to use n-grams to get vectors for unseen words?

https://medium.com/cisco-emerge/creating-semantic-representations-of-out-of-vocabulary-words-for-common-nlp-tasks-842dbdafba18

As tensorflow-embeding is analog to the fasttext-algorithm, it should be?

Is it possible with the featurizer with analyzer n-gram?

**Comment by akelad** [comment]
Thanks for raising this issue, @Ghostvv  will get back to you about it soon.

**Comment by Ghostvv** [comment]
in the `master` branch you can set `analyzer` to `char` or `char_wb` in [intent_featurizer_count_vectors](https://rasa.com/docs/nlu/master/components/#intent-featurizer-count-vectors)

**Comment by Ghostvv** [comment]
As specified in our [docs](https://rasa.com/docs/nlu/master/components/#intent-featurizer-count-vectors): `OOV_token` is enabled only if `analyzer` is set to `word`

As specified in our [docs](https://rasa.com/docs/nlu/master/components/#intent-featurizer-count-vectors), for details on how n-grams are used see [sklearn’s CountVectorizer docs](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html)

Please read the docs, before asking a question!

**Comment by Ghostvv** [comment]
And this is a usage question, please ask it on our [forum](https://forum.rasa.com)
