### ISSUE TITLE
Add examples for synonyms

### ISSUE THREAD

**Issue by huberrom** [RasaHQ/rasa_nlu#1623]
**Rasa NLU version**: 0.13.8

Do I need to add exampels with synonyms in my training data ?

I have the following training data :

```
{
	"text": "Si je vais chez un psychologue, est-ce que vous me remboursez ?",
	"intent": "remboursement_medecine_douce",
	"entities": [
	 {
		"start": 19,
	    	"end": 30,
	    	"value": "psychologue",
	        "entity": "specialite_medecine_douce"
	  }
	  ]
},
```

with this synonym :

```
{
    "value": "psychologue",
    "synonyms": [
	  "psychologie",
	  "psy"
    ]
}
```

So if I use the exact training sentence, the NLU will detect "psychologue" but if I use the sentence with "psy" instead of "psychologue", the NLU won't extract it. I know there is the following statement in the doc : " **Entities must be properly classified before they can be replaced with the synonym value.**" but I don't understand the utility of the entity_synonyms field if I have to create an example for each synonyms.

So what is the correct use of synonyms ? In the entity doc (https://rasa.com/docs/nlu/master/dataformat/#entity-synonyms) there is two options one with two training sentences and one using entity_synonyms. The second alone doesn't seems to work, do I need to implement the first option too ?
If I have too, I don't see the point of the entity_synonyms section. Maybe I'm missing something but the logic doesn't make sense to me.

**Comment by akelad** [comment]
Please ask these kind of questions in our [forum](https://forum.rasa.com)

**Comment by huberrom** [comment]
Well I did, see https://forum.rasa.com/t/add-examples-with-synonyms/4329, but I didn't get an answer, and for me it looks like a bug / possible improvement since the current behavior is everything but logic to me

**Comment by akelad** [comment]
I'll answer you on there, and it is logical and intentionally implemented that way ;)
