### ISSUE TITLE
ModuleNotFoundError: No module named 'rasa_nlu.training_data'; 'rasa_nlu' is not a package

### ISSUE THREAD

**Issue by nesspll** [RasaHQ/rasa_nlu#1624]
**Rasa NLU version**: ```0.13.2``` or ```0.13.7```

**Operating system** (windows, osx, ...): Windows

**Content of model configuration file**: 
```yml
language: "en"
pipeline: "tensorflow_embedding"
```

**Issue**: 
```ModuleNotFoundError: No module named 'rasa_nlu.training_data'; 'rasa_nlu' is not a package```

I tried using both versions 0.13.2 or 0.13.7 - the import wont work
```
from rasa_nlu.training_data import load_data
from rasa_nlu.model import Trainer
from rasa_nlu import config
from rasa_nlu.model import Interpreter
```

See screenshots https://i.ibb.co/v4KLLJv/rasaerror.png

**Comment by akelad** [comment]
Thanks for raising this issue, @EPedrotti  will get back to you about it soon.

**Comment by EPedrotti** [comment]
Hi @nesspll,
are you using a virtual environment? Also, could you also check if the rasa packages are listed when running `pip list`?

**Comment by nesspll** [comment]
Yes in anaconda, (see the screenshot above) - when ```pip list``` I can see ```rasa-nlu 0.13.2``` I tried a higer version ```rasa-nlu 0.13.7``` but that wont work t0o.

**Comment by EPedrotti** [comment]
@nesspll if you have python 2 installed as well please make sure you are installing rasa with pip3. Also have a look at this and let me know if it helps [https://stackoverflow.com/questions/50914761/jupyter-notebook-cant-find-modules-for-python-3-6](https://stackoverflow.com/questions/50914761/jupyter-notebook-cant-find-modules-for-python-3-6)
