### ISSUE TITLE
Entity Extraction for custom application

### ISSUE THREAD

**Issue by sagarika3kundu** [RasaHQ/rasa_nlu#1628]
**Rasa NLU version**: 0.13.8

**Operating system** (windows, osx, ...): Windows

**Content of model configuration file**:
```yml
language: "en" 
pipeline: "spacy_sklearn"
```

**Issue**:
I am creating a chatbot for the internal purpose of an industry which should be able to extract the **group name, subgroup name, version, date and type of document** from a given text.

Eg the user inputs -
CASE 1 :
**I want details for Columbia, Fiji, dated 18/01/2019, version 1.2.3 and .txt file**
CASE 2 :
**May i know details for Canteen, Floor1, 12/01/2019, 5.5.5 and .xml file**

The chatbot should be able to extract :  
CASE 1 -
"**Columbia**" as group_name, "**Fiji**" as subgroup_name, "**18/01/2019**" as date, "**1.2.3**" as version and "**txt**" as the doc_type.
CASE 2 -
"**Canteen**" as group_name, "**Floor1**" as subgroup_name, "**12/01/2019**" as date, "**5.5.5**" as version and "**xml**" as the doc_type.

Now the problem is if i use lookup table it works fine, but becomes restricted as the model does not evolve to extract unseen values that are not present in the lookup table. Is there any other way to do it by training the RASA NLU model because these names are all from varied contexts with different intents according to spacy. Also that the user might input values in any random order and might forget providing some values. I would want them to be correctly classified into the respective slots. But when i am simply training the model on examples and without lookup tables, the entities are **NOT** getting extracted except for the ones which i mentioned in the training examples. Is there a proper way to achieve this with training? And if there is, please may i know the config or the required change?

**Comment by akelad** [comment]
Thanks for raising this issue, @wochinge  will get back to you about it soon.

**Comment by wochinge** [comment]
@sagarika3kundu Please ask usage questions in our [forum](https://forum.rasa.com/). You could use `spacy_ner` (checkout the demo here https://explosion.ai/demos/displacy-ent) to extract locations and maybe duckling for the dates / versions, and ner_crf for the rest?
