### ISSUE TITLE
RASA Tensorflow never ends

### ISSUE THREAD

**Issue by edwinliu18** [RasaHQ/rasa_nlu#1631]
basic info:
**‘rasa-core==0.9.6’ ‘rasa-nlu==0.12.3’**:
**python 3.6**
**'tensorflow==1.12.0'**
**Window 7** (windows, osx, ...):

below is the simple config file:

**language: "en"
pipeline: "tensorflow_embedding"**:

Issue:

**Hello all,

I am new to Rasa Nlu, my story is when I use tensorflow pipeline to train, if only 1 intent (below example) then it will finish fast (only comes with message ERROR rasa_nlu.classifiers.embedding_intent_classifier - Can not train an intent classifier. Need at least 2 different classes. Skipping training of intent classifier.

=============================================================

intent: meetup
I am new to the area. What meetups I could join in Berlin?
I have just moved to Berlin. Can you suggest any cool meetups for me?
I am live in Taiwan, can we meet? =============================================================
but when I have have 1+ intents (not talking about muti intents in one sentencce) as below, the train will never end.

=============================================================

intent: meetup
I am new to the area. What meetups I could join in Berlin?
I have just moved to Berlin. Can you suggest any cool meetups for me?
I am live in Shatin, can we meet?
intent: meetup1
again testing, will it work? =============================================================
can anyone helps, I am stuck for a week already, thanks so much!**:

**Comment by akelad** [comment]
Thanks for raising this issue, @Ghostvv  will get back to you about it soon.

**Comment by Ghostvv** [comment]
What do you mean the training will never end, could you please post the debug log

**Comment by edwinliu18** [comment]
[15] is running with different intents, it just hangs there over 24hr+ without result. that's my question, thanks.

**Comment by Ghostvv** [comment]
The first one is correct. It is impossible to tell what's going on with the second case without more details

**Comment by edwinliu18** [comment]
@Ghostvv , appreciate if you can let me know how can I obtain the infor you are seeking, thanks.
