### ISSUE TITLE
Allow multiple config files for train/test split

### ISSUE THREAD

**Issue by rgstephens** [RasaHQ/rasa_nlu#1632]
**Rasa NLU version**: 0.13.0

**Enhancement**:

After working with the train/test split mode (#1625) it would be nice to run the dynamically created test data against multiple NLU config's to compare the results against the same test data.

If it's of interest to others, I'll create a PR which would support this:

```
python rasa_nlu.evaluate.py --mode testtrain --config nlu_config.yml,nlu_config_tensorflow.yml --data ./training/
```

It would produce `error-0.json`, `error-1.json`, `conf-0.png`, etc.

**Comment by akelad** [comment]
@rgstephens are you still interested in working on this and the other thing?

**Comment by rgstephens** [comment]
This request was associated with my [PR #1630](https://github.com/RasaHQ/rasa_nlu/pull/1630) was was cancelled 3 weeks ago.

**Comment by akelad** [comment]
ah ofc, the code moved around -- sorry about that. i'm actually not sure it makes sense anymore, because you should usually have a fixed test set rather than a dynamically created one. so i think i'll close this issue
