### ISSUE TITLE
Rasa server can't find models on AWS EC2

### ISSUE THREAD

**Issue by Dylan0126** [RasaHQ/rasa_nlu#1637]
**Rasa NLU version**: 0.13.8

**Operating system** (windows, osx, ...):
AWS Deep Learning AMI version 20

**Content of model configuration file**:
```yml

```

**Issue**:

I used to setup rasa_server on my local machine by:

python -m rasa_nlu.server --path /chatbot/models

I have the following: 

curl http://localhost:5000/status
{
  "max_training_processes": 1,
  "current_training_processes": 0,
  "available_projects": {
    ".DS_Store": {
      "status": "ready",
      "current_training_processes": 0,
      "available_models": [
        "fallback"
      ],
      "loaded_models": [
        "fallback"
      ]
    },
    "default": {
      "status": "ready",
      "current_training_processes": 0,
      "available_models": [
        "model_20181114-122136",
        "model_20181114-141809"
      ],
      "loaded_models": []
    }
  }

This is good, the models can be found.

But Recently when I try to setup a server on AWS EC2
python -m rasa_nlu.server --path /chatbot/models

I can only get this:

curl http://localhost:5000/status
{
  "max_training_processes": 1,
  "current_training_processes": 0,
  "available_projects": {
    "default": {
      "status": "ready",
      "current_training_processes": 0,
      "available_models": [
        "fallback"
      ],
      "loaded_models": [
        "fallback"
      ]
    }
  }

The model I trained cannot be found, so I can not use them.

**Comment by akelad** [comment]
Thanks for raising this issue, @wochinge  will get back to you about it soon.

**Comment by Dylan0126** [comment]
@wochinge  
Yes, the models are there. I even tried to specify which model to use by:
python -m rasa_nlu.server --path /chatbot/models/default/model_20190122-201816
(You can also see the directory layout above)

Yes, I do have the permission to read that directory. I changed the permission to 777 for that entire folder. But everything still remains the same.

**Comment by wochinge** [comment]
> You can also see the directory layout above
Sorry, I can unfortunately not see it. Can you add it?
I just want to make sure `--path /chatbot/models/default/model_20190122-201816` is not `--path chatbot/models/default/model_20190122-201816`.

Can you please also try tostart NLU without specifying the concrete model? So just `--path /chatbot/models/default/`?

**Comment by Dylan0126** [comment]
> > You can also see the directory layout above
> > Sorry, I can unfortunately not see it. Can you add it?
> > I just want to make sure `--path /chatbot/models/default/model_20190122-201816` is not `--path chatbot/models/default/model_20190122-201816`.
> 
> Can you please also try tostart NLU without specifying the concrete model? So just `--path /chatbot/models/default/`?


My original post was using `--path /chatbot/models/default/`. I have also tried '--path /chatbot/models'

Layout:

cd chatbot
ls
configs  data  models

cd models
ls

default
cd default
ls

model_20190122-201816
cd model_20190122-201816
ls

checkpoint
crf_model.pkl
entity_synonyms.json
intent_classifier_tensorflow_embedding.ckpt.data-00000-of-00001
intent_classifier_tensorflow_embedding.ckpt.index
intent_classifier_tensorflow_embedding.ckpt.meta
intent_classifier_tensorflow_embedding_encoded_all_intents.pkl
intent_classifier_tensorflow_embedding_inv_intent_dict.pkl
intent_featurizer_count_vectors.pkl
metadata.json
regex_featurizer.json
training_data.json

**Comment by careless25** [comment]
@Dylan0126 have a look at this PR: https://github.com/RasaHQ/rasa_nlu/pull/1731
Maybe it will help

**Comment by wochinge** [comment]
@Dylan0126 did the pr from @careless25 help?
