### ISSUE TITLE
SpacyNLP component: migrate to Spacy 2 way to disable the dependency parser

### ISSUE THREAD

**Issue by Tpt** [RasaHQ/rasa_nlu#1649]
Spacy 2 introduced a new way to disable the dependency parser.

Instead of:
```
nlp = spacy.load(spacy_model_name, parser=False)
```

the following syntax should be used:
```
nlp = spacy.load(spacy_model_name, disable=['parser'])
```

Reference: The section "Important note: disabling pipeline components" of https://spacy.io/usage/processing-pipelines#disabling

**Comment by rugonzx** [comment]
why rasa wants to diable parser pipe from spacy? I am talking about the SpacyNLP wrapper to load the spacy model.

**Comment by jon-torres** [comment]
> 

Hi, could solve this issue?
