### ISSUE TITLE
let entity type affect intent classifier?

### ISSUE THREAD

**Issue by iorilu** [RasaHQ/rasa_nlu#1652]
I am not sure now if the intent classifier will be affected by entity types, as I read some content saying that they are independent process.

What I want is to have a additional rule , that will change the intent type if for some specific entity types combination occurs

now I am using the  intent_classifier_tensorflow_embedding

**Comment by akelad** [comment]
Currently entity extraction and intent classification are independent of each other

**Comment by akelad** [comment]
i'm going to close this for now as i don't think this is something we'll be doing any time soon
