### ISSUE TITLE
Fix the do_extractors_overlap function

### ISSUE THREAD

**Issue by akelad** [RasaHQ/rasa_nlu#1656]
Right now it returns `True` if the list of extractors is None, which is wrong because in your labelled training data there is usually no extractor defined. So it's not returning an error if your entities overlap
Apparently we need to separate out the `determine_token_labels` into two functions, because otherwise it's not fixable (@EPedrotti can explain this better)
Also we should write a test to check this actually performs as expected

**Comment by careless25** [comment]
I understand the first part - no extractors = return True. But I am not sure why we need to separate `determine_token_labels` into 2 functions. @EPedrotti if you can explain it better, maybe I can work on it
