### ISSUE TITLE
ImportError: cannot import name 'RasaNLUConfig'

### ISSUE THREAD

**Issue by lohitk27** [RasaHQ/rasa_nlu#1658]
rasa-core                          0.9.0a2
rasa-core-sdk                      0.12.1
rasa-nlu                           0.14.1

Im facing below issue while running code

from rasa_nlu.config import RasaNLUConfig
ImportError: cannot import name 'RasaNLUConfig'

@tmbo Kindly help me out with this query.

**Comment by akelad** [comment]
This is because the location/name of that has changed. Also rasa-core version 0.9.0 is incompatible with both your rasa_nlu version and your rasa_core_sdk version. Please upgrade your rasa_core version to fix these errors

**Comment by Blovash** [comment]
You can use RasaNLUModelConfig instead of RasaNLUConfig

**Comment by ymehta18** [comment]
> You can use RasaNLUModelConfig instead of RasaNLUConfig

then the giving error that RasaNLUConfig is not defined
