### ISSUE TITLE
How to keep the Twisted server running forever to improve performance?

### ISSUE THREAD

**Issue by axchanda** [RasaHQ/rasa_nlu#1685]
**Rasa NLU version rasa_nlu~=0.13.0**:

**Operating system = Windows 10 Home**

**Issue**:
I want to run the Rasa NLU server forever in the system. After a short while, it gets timed out; and the next time it gets connected there is a delay. How to avoid this delay and keep the RASA running on the edge? Immediate answers would be appreciable.

 
![image](https://user-images.githubusercontent.com/20764675/52175008-f7709500-27c2-11e9-8e8c-5c0df0e0551f.png)

**Comment by akelad** [comment]
Thanks for raising this issue, @EPedrotti  will get back to you about it soon.

**Comment by EPedrotti** [comment]
Hi @axchanda ,
to run Rasa NLU as you want you can either use Docker or you can follow this guide [https://www.banquise.org/python/making-and-deploying-a-twisted-project-as-a-service-under-windows/](https://www.banquise.org/python/making-and-deploying-a-twisted-project-as-a-service-under-windows/). Let me know if this solve your problem.

**Comment by axchanda** [comment]
@EPedrotti No this is not my problem. The twisted server seems to time out while run. While running NLU engine responds in millise conds. If the server gets time out, then the time to warm up make the server go slow in the order of 5~6 seconds.

**Comment by axchanda** [comment]
@akelad Can I have any ulpdqates on this, please?

**Comment by EPedrotti** [comment]
@axchanda how exactly are you running NLU? pure python or in docker? Did you try using `pythonw.exe`?

**Comment by axchanda** [comment]
@EPedrotti Kindly understand the problem first. It is about how to keep the Twisted server running forever without timeout; which doesn't involves either python or docker. And even if run through pythonw.exe, I don't think that's the solution for this problem. Please revert back with real answers and don't dodge on this!

**Comment by EPedrotti** [comment]
We are not dodging the question but we can't reproduce this. Could you please share more details about how you are running NLU?
