### ISSUE TITLE
multiple timezone support for rasa duckling http

### ISSUE THREAD

**Issue by dhirajpatnaik16297** [RasaHQ/rasa_nlu#1696]
**Rasa NLU version: 0.13.8**:

**Operating system** (ubuntu 16.04.):
**Issue**:
https://github.com/horeapopa/rasa_nlu/commit/278fb2356739846f6547e78fcb1aed0dd8688808
According to this commit, we can add multiple timezones. 
The main issue is i want to access ner_duckling_http like ner_duckling for which i need to add timezone in the query i am sending to rasa itself.
But ner_duckling only returned UTC time in rasa without creating a separate server for the duckling.
Is it going to be added to the master in the recent future?

**Comment by akelad** [comment]
Thanks for raising this issue, @wochinge  will get back to you about it soon.

**Comment by wochinge** [comment]
Unfortunately duckling currently does not make use of the time zone.

At their [documentation](https://duckling.wit.ai/) it says:
> Timezones are parsed, but they don’t impact the time value (will be fixed shortly).

A workaround for this is to adapt the timezone in your custom actions.

**Comment by dhirajpatnaik16297** [comment]
@wochinge can you please elaborate how to adapt the timezone in the custom actions ?
I am new to this so seeking help.

**Comment by wochinge** [comment]
Take the extracted entity and use the python library / module of your choice to convert. You can then e.g. reset the slot using a `SlotSet` event.
