### ISSUE TITLE
Not able to import KerasPolicy as from rasa_core.policies.keras_policy 

### ISSUE THREAD

**Issue by Palash1995** [RasaHQ/rasa_nlu#1699]
**Rasa NLU version**:

**Operating system** (windows, osx, ...):

**Content of model configuration file**:
```yml

```

**Issue**:

**Comment by Palash1995** [comment]
Environment 
Linux Ubuntu 16.04.5 LTS
Python 3.5.2 
rasa_nlu version -  0.15.0a1
 
I am receiving TypeError: descriptor '__subclasses__' of 'type' object needs an argument

while importing KerasPolicy from rasa_core.policies.keras_policy import 

Made the changes suggested in this thread as per below https://forum.rasa.com/t/typererror-in-keras-policy/2626/2 

self.model.fit(shuffled_X, shuffled_y,
    epochs=self.epochs,
    batch_size=self.batch_size,
    **params)

to

self.model.fit(shuffled_X, shuffled_y,
    **{'epochs': self.epochs, 'batch_size': self.batch_size, **params})  # params take precedence

But issue still persist

Could anyone please guide how to import KerasPolicy successfully

**Comment by akelad** [comment]
Could you please format your code? And what's the import statement you're using? Please post the full error trace as well

**Comment by Palash1995** [comment]
Hi Akela,

Thanks for the revert

Environment
Linux Ubuntu 16.04.5 LTS
Python 3.5.2
rasa_nlu version - 0.15.0a1

I am importing KerasPolicy as per below 

from rasa_core.policies.keras_policy import KerasPolicy

received below error. Executing in Visual studio code 

![image](https://user-images.githubusercontent.com/35071481/52634748-04d9fd80-2eee-11e9-9d18-6004e2495561.png)

Also while importing Agent as per below 

from rasa_core.agent import Agent

I am getting the following error

![image](https://user-images.githubusercontent.com/35071481/52634906-7154fc80-2eee-11e9-8b11-bdc5837e78ef.png)

Could you please guide me on these this error as well.

Regards
Palash

**Comment by akelad** [comment]
Thanks for that, @MetcalfeTom  will get back to you about it soon.

**Comment by MetcalfeTom** [comment]
Hi there, this is an [error with Python versions below 3.5.3](https://github.com/python/typing/issues/266), upgrading will fix it
