### ISSUE TITLE
error : Not all required packages are installed. To use this pipeline, you need to install the missing dependencies. Please install sklearn

### ISSUE THREAD

**Issue by PrasannaBrabourame** [RasaHQ/rasa_nlu#1702]
**Rasa NLU version**: 0.14.3

**Operating system** (windows, osx, ...): Windows 10

**Content of model configuration file**:
```
language: en
pipeline: tensorflow_embedding
```

**Issue**:File "d:\prasanna\files\projects\github\nlu-chatbot\rasa_nlu\rasa_nlu\train.py", line 133, in do_train
    trainer = Trainer(cfg, component_builder)
  File "d:\prasanna\files\projects\github\nlu-chatbot\rasa_nlu\rasa_nlu\model.py", line 141, in __init__
    components.validate_requirements(cfg.component_names)
  File "d:\prasanna\files\projects\github\nlu-chatbot\rasa_nlu\rasa_nlu\components.py", line 47, in validate_requirements
    "Please install {}".format(", ".join(failed_imports)))
Exception: Not all required packages are installed. To use this pipeline, you need to install the missing dependencies. Please install tensorflow

**Comment by akelad** [comment]
pip install rasa_nlu[tensorflow] should solve your problem, please take a look at our docs.

**Comment by PrasannaBrabourame** [comment]
even after using "pip install rasa_nlu[tensorflow]" the same error occurs

**Comment by akelad** [comment]
is it possible that you've installed it elsewhere? e.g. you're using a virtual env

**Comment by nedian** [comment]
I already install tensorflow but still got the same error
Exception: Not all required packages are installed. To use this pipeline, you need to install the missing dependencies. Please install tensorflow

**Comment by maheshkarriisb** [comment]
I too have same error

**Comment by maheshkarriisb** [comment]
Error:"Please install {}".format(", ".join(failed_imports)))

Exception: Not all required packages are installed. To use this pipeline, you need to install the missing dependencies. Please install sklearn_crfsuite

I installed all required packages but getting same error.

**Comment by Sathish750** [comment]
I keep getting the same issue (mentioned above) after installing all the packages.

**Comment by 913165** [comment]
I tried pip install rasa_nlu[tensorflow] should solve your problem but the same error

C:\rasax\sara>nlu_model.py
Traceback (most recent call last):
  File "C:\rasax\sara\nlu_model.py", line 18, in <module>
    train_nlu('./data/data_rest2.json', 'config.yml', './models/nlu')
  File "C:\rasax\sara\nlu_model.py", line 8, in train_nlu
    trainer = Trainer(config.load(configs))
  File "C:\Users\Pritesh\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_nlu\model.py", line 147, in __init__
    components.validate_requirements(cfg.component_names)
  File "C:\Users\Pritesh\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_nlu\components.py", line 46, in validate_requirements
    "Please install {}".format(", ".join(failed_imports)))
Exception: Not all required packages are installed. To use this pipeline, you need to install the missing dependencies. Please install tensorflow
