### ISSUE TITLE
re.I in regex match, and possible multiple matches

### ISSUE THREAD

**Issue by disimone** [RasaHQ/rasa_nlu#1703]
**Rasa NLU version**: 0.14.3

**Operating system** (windows, osx, ...): linux

**Issue**:

Hallo,

I have a few questions on regexes.

1) it would be nice to have an option to choose whether regex matches are case sensitive or not. Is this already supported? I would think a configuration parameter in RegexFeaturizer would do it, but it does not seem to exist. Should I be looking somewhere else?
2) if I understand the code correctly, the tokens are only flagged if they overlap with the first occurrence of the regex in the message. Multiple matches of the same regex in the message are not taken into account at all. So if a message contains, for example, two dates, only the first token will be flagged as "date". Is this intended?
3) For my education, how are the two different features (the "global" message-level match and the individual token-level matches) used in the following by the tensorflow_embedding model? The featurizer appears to only return the message-level matches. Are all tokens matched to the same regex treated as equal?

Thanks for your help,

Andrea.

**Comment by akelad** [comment]
Thanks for raising this issue, @MetcalfeTom  will get back to you about it soon.

**Comment by MetcalfeTom** [comment]
Hey @disimone,

1. This is supported, you just need to [define the regex pattern as normal in the training data](https://rasa.com/docs/nlu/master/dataformat/#regular-expression-features) including capitals.  For intent classification, just be careful of your processing pipeline:  by default the components `nlp_spacy` and `intent_featurizer_count_vectors` will convert your tokens to lowercase (these can be configured)

2. You're correct!  Thanks for pointing this out - we can make a fix for it (but contributions are also welcome)

3. Happy to explain: the global match is used as a feature for intent classification, the individual token-level match is only used for entity extraction: we take into account the features of neighbouring tokens when trying to identify an entity (be default, the features we search for are [these](https://github.com/RasaHQ/rasa_nlu/blob/master/rasa_nlu/extractors/crf_entity_extractor.py#L43))
