### ISSUE TITLE
RASA - HTTP API Endpoint Config get call is not working in NLU: 0.14.3 version

### ISSUE THREAD

**Issue by lakshmanaB** [RasaHQ/rasa_nlu#1704]
**Rasa NLU version**: 0.14.3

**Operating system** (windows 10):

http://localhost:5000/config Status Code : 404
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

In the RASA NLU version 0.13.1 we have localhost:5000/config endpoint. In version 0.14.3 its not there. but I am wondering that it is there in the documentation . :smiley:

I got to know after checking the Python file

https://github.com/RasaHQ/rasa_nlu/blob/master/rasa_nlu/server.py
```

**Issue**:

**Comment by akelad** [comment]
Thanks for raising this issue, @ricwo  will get back to you about it soon.

**Comment by ricwo** [comment]
the `/config` endpoint was removed with https://github.com/RasaHQ/rasa_nlu/commit/06b867d39d66878b5ac1a9a55121d7f459ab5532, based on this issue: https://github.com/RasaHQ/rasa_nlu/issues/1132

Thanks for pointing this out though - the docs are stale and should be removed as well (https://github.com/RasaHQ/rasa_nlu/issues/1706)
