### ISSUE TITLE
Add a 'dimensions' option to the ner_spacy extractor like in the duckling extractor

### ISSUE THREAD

**Issue by mauricedoepke** [RasaHQ/rasa_nlu#1705]
With the duckling extractor you can specify to extract only certain entities through the "dimensions" attribute. I'd like to have a similar feature in the spacy extractor.

This should not be much work to implement. I would open a pull request for this if you are interested in this feature.

We could even put the filtering function in the ExtractorBaseClass so it would be available for every extractor.

**Comment by akelad** [comment]
Sure, we'd love it if you could create a PR for that!
