### ISSUE TITLE
Adding a spelling correction component

### ISSUE THREAD

**Issue by mauricedoepke** [RasaHQ/rasa_nlu#1720]
Are you guys interested in adding a spelling correction component?

I am probably going to build one on the basis of [this levenshtein spellchecker](https://github.com/barrust/pyspellchecker) 

To get better results I'm thinking of
- Appending the vocabulary used in the nlu file to the pre-made word list.
- If there are multiple possible corrections with the same distance, prefer the ones that already occur in the nlu file
- Optionally adding custom words.

I'd appreciate suggestions to improve my approach

**Comment by mauricedoepke** [comment]
I'm closing this here, as this belongs to rasa core

**Comment by akelad** [comment]
Hi @mauricedoepke thanks a lot for this suggestion, we'll discuss this and get back to you

**Comment by careless25** [comment]
Be careful. You will slow down your server response. Spellchecking and correction is an expensive operation. We had this implemented and when people typed a words that were longer than 8 or 9 characters in the sentence, we would notice a huge slow down (~3 seconds) in server response due to it.

**Comment by mauricedoepke** [comment]
@careless25  This seems to be a valid concern. Also spellchecking could accidentally mess up the sentence more than it was originally. 

My main motivation to implement a spellchecker was actually because duckling can't handle spelling mistakes. So it might be wise to limit the spellchecking to date/time-related terms.

**Comment by nmstoker** [comment]
Apply only on entities or just to the first X characters may be worth considering. A while back I over-eagerly added a spell checker to a bot of mine, thinking it was fine after basic testing, only to discover that entering sufficiently long sentences tied it up enough that the front end thought the request was lost and resent it - which quickly brought things crashing down :open_mouth:
