### ISSUE TITLE
Using rasa-core endpoints to connect rasa-nlu server gets an unurldecoded string.

### ISSUE THREAD

**Issue by suenpun** [RasaHQ/rasa_nlu#1726]
**Rasa NLU version**:0.14.1

**Operating system** (windows, osx, ...):osx

**Content of model configuration file**:
```yml

```

**Issue**:rasa-core endpoints to connect rasa-nlu server got urlencodeed str
- rasa-nlu's log is like this : it indicate that the rasa-core uses a GET request 
`2019-02-22 19:43:36+0800 [-] "127.0.0.1" - - [22/Feb/2019:11:43:35 +0000] "GET /parse?model=model_20190222-163549&project=ins&q=%E4%BD%A0%E5%A5%BD HTTP/1.1" 200 925 "-" "python-requests/2.21.0"`
- but when I use POST request to test the rasa-nlu from command line ,it works well:
`$ curl -XPOST localhost:5000/parse -d '{"q":"你好", "project": "ins","model":"model_20190222-160808"}'`
the response is correct:
`{
  "intent": {
    "name": "hi",
    "confidence": 0.7992279529571533
  },
  "entities": [],
  "intent_ranking": [
    {
      "name": "hi",
      "confidence": 0.7992279529571533
    },
 ...
`
- It seems like that the problem is in rasa-core,but I am not sure.

Anybody could help me. Forgive me the rude question. Many thanks!!
@tmbo

**Comment by suenpun** [comment]
- rasa-nlu's log is like this : it indicate the the rasa-core uses a GET request 
2019-02-22 19:43:36+0800 [-] "127.0.0.1" - - [22/Feb/2019:11:43:35 +0000] "GET /parse?model=model_20190222-163549&project=ins&q=%E4%BD%A0%E5%A5%BD HTTP/1.1" 200 925 "-" "python-requests/2.21.0"
- but when I use POST request to test the rasa-nlu from command line ,it works well:
$ curl -XPOST localhost:5000/parse -d '{"q":"你好", "project": "ins","model":"model_20190222-160808"}'
the response is correct:
{
  "intent": {
    "name": "hi",
    "confidence": 0.7992279529571533
  },
  "entities": [],
  "intent_ranking": [
    {
      "name": "hi",
      "confidence": 0.7992279529571533
    },

Forgive me the rude question. Many thanks

**Comment by akelad** [comment]
Thanks for raising this issue, @wochinge  will get back to you about it soon.

**Comment by wochinge** [comment]
@suenpun Can you please attach
- the content of your endpoint configuration file
- your startup command for rasa core
- the stack trace of the error

**Comment by suenpun** [comment]
Thank u so much! I've changed the charset of nlu training json-data to utf-8 . It works ,but I'm not sure whether this is the source of the problem. If there are any further questions. I'll get back to you later. Thank u again! @akelad @wochinge

**Comment by akelad** [comment]
Sounds great! If you encounter further issues, please create a new one. I'll close this one for now
