### ISSUE TITLE
docker | Exception: Unable to load total_word_feature_extractor detector

### ISSUE THREAD

**Issue by lansedebing** [RasaHQ/rasa_nlu#1732]
[root@localhost multiplition]# docker run -it -v $(pwd):/app/multiplition -v $(pwd)/models/nlu:/app/multiplition/models/nlu rasa/rasa_nlu:latest run python -m rasa_nlu.train -c multiplition/config_jieba_mitie_sklearn.yml --fixed_model_name current --data multiplition/data/nlu/ -o models --project nlu --verbose
Error loading MITIE model file: data/total_word_feature_extractor_zh.dat
Unable to open data/total_word_feature_extractor_zh.dat for reading.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/rasa_nlu/train.py", line 170, in <module>
    num_threads=cmdline_args.num_threads)
  File "/app/rasa_nlu/train.py", line 133, in do_train
    trainer = Trainer(cfg, component_builder)
  File "/app/rasa_nlu/model.py", line 144, in __init__
    self.pipeline = self._build_pipeline(cfg, component_builder)
  File "/app/rasa_nlu/model.py", line 156, in _build_pipeline
    component_name, cfg)
  File "/app/rasa_nlu/components.py", line 422, in create_component
    cfg)
  File "/app/rasa_nlu/registry.py", line 134, in create_component_by_name
    return component_clz.create(config)
  File "/app/rasa_nlu/utils/mitie_utils.py", line 51, in create
    extractor = mitie.total_word_feature_extractor(model_file)
  File "/usr/local/lib/python3.6/site-packages/mitie/mitie.py", line 831, in __init__
    raise Exception("Unable to load total_word_feature_extractor detector from " + to_default_str_type(filename))
Exception: Unable to load total_word_feature_extractor detector from data/total_word_feature_extractor_zh.dat

config_jieba_mitie_sklearn.yml

language: "zh"

pipeline:

- name: "nlp_mitie"

  model: "data/total_word_feature_extractor_zh.dat"

- name: "tokenizer_jieba"

- name: "ner_mitie"

- name: "ner_synonyms"

- name: "intent_entity_featurizer_regex"

- name: "intent_featurizer_mitie"

- name: "intent_classifier_sklearn"

**Comment by akelad** [comment]
Please fill out the issue template

**Rasa Core version**:

**Python version**: 

**Operating system** (windows, osx, ...):

**Issue**:



**Content of domain file** (if used & relevant):
```yaml

```

**Comment by lansedebing** [comment]
I used the docker to run on Centos 7 ,   Rasa NLU Image is rasa/rasa_nlu:latest.

**Issue**:  
Exception: Unable to load total_word_feature_extractor detector from data/total_word_feature_extractor_zh.dat

**my pipeline**:
* name: "nlp_mitie"
  model: "data/total_word_feature_extractor_zh.dat"
* name: "tokenizer_jieba"
* name: "ner_mitie"
* name: "ner_synonyms"
* name: "intent_entity_featurizer_regex"
* name: "intent_featurizer_mitie"
* name: "intent_classifier_sklearn"

**Command:**
docker run -it -v $(pwd):/app/multiplition -v $(pwd)/models/nlu:/app/multiplition/models/nlu rasa/rasa_nlu:latest run python -m rasa_nlu.train -c multiplition/config_jieba_mitie_sklearn.yml --fixed_model_name current --data multiplition/data/nlu/ -o models --project nlu --verbose

the path of total_word_feature_extractor_zh.dat is  /home/multiplition/data/total_word_feature_extractor_zh.dat

**Comment by lansedebing** [comment]
It's work!
