### ISSUE TITLE
Evaluation unloads current model

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa_nlu#1733]
When Rasa NLU is running as server and receives an evaluation request for a different model, it loads the different model and evaluates it which unloads the current model.

**Comment by MetcalfeTom** [comment]
So my plan of attack here is to:

1. Unload the current model
2. Load the eval model
3. Evaluate it
4. Unload
5. Reload the first model

Could circumvent unloading the first model, but that could also lead to memory issues

**Comment by tmbo** [comment]
The current model should not be unloaded:
If this is a production server the model is needed and evaluation should happen in a separate thread / process with the model to be tested. If this is a worker which is just waiting for e.g. evaluation jobs, there shouldn't be a model to unload.

**Comment by MetcalfeTom** [comment]
Just to give an update here:

I am trying to run the eval in a separate process with the same `ProcessPool` as we use for training, however I come into errors when trying to pass the model into the `submit` function, since [the spaCy have some issues with pickling](https://github.com/explosion/spaCy/issues/2962).

**Comment by MetcalfeTom** [comment]
The issue is fixed, but we decided to edit the `test_server.py` tests since they weren't performed on a trained NLU model.  If this issue is to be handed over, it should be a relatively simple fix - just need to change the assertions of the other tests

**Comment by tmbo** [comment]
@MetcalfeTom where are we on this one?

**Comment by MetcalfeTom** [comment]
@tmbo Addressing review comments today, looks like we'll be ready to close
