### ISSUE TITLE
Feeding Custom/Pretrained embeddings for ner_crf

### ISSUE THREAD

**Issue by gowtham1997** [RasaHQ/rasa_nlu#1736]
This is not an issue but a general question. I have already posted this on the [forum](https://forum.rasa.com/t/feeding-custom-pretrained-embeddings-for-ner-crf/5406) and didn't get a response, so posting here.

I’m trying to use custom embeddings or pretrained embeddings with ner_crf for entity extraction, but can’t find a proper tutorial for it yet. I have tried using fasttext with spacy but I don’t think the embeddings are being used by ner_crf(as I’m not using POS tags feature with ner_crf).

If I had to feed custom embeddings as an additional feature to ner_crf, how should I do it with/without spacy(Spacy doesn’t have support for Bert embeddings yet)?

**Comment by akelad** [comment]
We'll get back to you about this on the forum

**Comment by gowtham1997** [comment]
Hello,
@akelad Any updates on this?
