### ISSUE TITLE
Wrong child pipeline order for spacy_sklearn in Rasa document

### ISSUE THREAD

**Issue by peidaqi** [RasaHQ/rasa_nlu#1744]
**Rasa NLU version**:
Current

**Operating system** (windows, osx, ...):
N/A

**Content of model configuration file**:
N/A

**Issue**:
In the official document about Rasa NLU pipelines (https://rasa.com/docs/nlu/choosing_pipeline/), it says the spacy_sklearn pipeline is consisted of:
language: "en"

pipeline:
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "intent_entity_featurizer_regex"
- name: "intent_featurizer_spacy"
- name: "ner_crf"
- name: "ner_synonyms"
- name: "intent_classifier_sklearn"

This is incorrect because the child pipeline "intent_featurizer_spacy" should be executed before "intent_entity_featurizer_regex".

In regex_featurizer.py, when processing incoming message, it will first examine if 'text_features' exist and stack new text features with old ones. spacy_featurizer.py doesn't do such tests. If the regex featurizer happens before the spacy one, the result would be overwritten.

In registery.py, however, the child pipeline order is actually correct (line 62), so this is only a problem with the documentation. 

This being said, maybe there should be such tests in spacy_featurizer, too, since both would generate text_features in parallel.

**Comment by akelad** [comment]
Thanks for raising this issue, @MetcalfeTom  will get back to you about it soon.

**Comment by MetcalfeTom** [comment]
Hi @peidaqi,

Could you please indicate where the result would be overwritten?  Looking through the code, I can see that both featurizers execute `_combine_with_existing_text_features()` during their processing, which checks for existing message features

**Comment by peidaqi** [comment]
I double checked the source code and indeed it's correct. I must have missed something when I first examined the code. Sorry it's only the inconsistency in documentation then.
registry.py - Line 62
https://rasa.com/docs/nlu/choosing_pipeline/ - Section "Pre-configured Pipelines"
