### ISSUE TITLE
Rasa NLU is getting trained with old data even i try to train with new data

### ISSUE THREAD

**Issue by vageesh7** [RasaHQ/rasa_nlu#1747]
**Rasa NLU version**: 0.11.4

**Operating system** (windows, osx, ...): Linux

**Content of model configuration file**:
```yml

```

**Issue**: RASA NLU is getting trained with old data eventhough i try to train it with new data.

**Comment by akelad** [comment]
Please provide some more details, e.g. what commands are you running
