### ISSUE TITLE
train a classifier using results of a previous one

### ISSUE THREAD

**Issue by disimone** [RasaHQ/rasa_nlu#1748]
**Rasa NLU version**: 0.14.3

**Operating system** (windows, osx, ...): Linux

**Issue**:

Hallo everyone,

I have a setup with two classifiers: the builtin embedding_classifier and a custom one.

The custom one needs to do some analysis on the results of the embedding classifier and decide on some confidence thresholds. This would be the its "training" step. I am using now some ugly workaround involving an external script doing the analysis and dumping some pickle that the custom classifier then reads, but I would like to move this to the "train" method of the class, so I can do everything in one go.

Here are my questions:

1) is the training order guaranteed to be the one in which the classifiers are mentioned in the configuration? Can I be sure that when the training of the second classifier starts, the embedding_classifier has been already trained?
2) the train method gets as argument an instance of TrainingData: is this a "clean" list of examples, or there any chance that they already have the final outcome of the previous classifiers? I assume it has in any case the tokens?
3) If the TrainingData has no classification yet, how do I pass it through the freshly trained embedding classifier?

Thanks for your help,

Andrea.

**Comment by akelad** [comment]
Please ask these kind of questions in our [forum](https://forum.rasa.com)
