### ISSUE TITLE
I'm training a bot on rasa-nlu . But keep getting this issue. Can someone help me out?

### ISSUE THREAD

**Issue by Ahzam-Lathiya** [RasaHQ/rasa_nlu#1756]
##This is my code 
##Im using:
                   rasa-0.14.4
                   python:3.6.2
                   Ubuntu:18.04.2
from rasa_nlu.training_data import load_data
from rasa_nlu.config import RasaNLUModelConfig
from rasa_nlu.model import Trainer

def train_nlu(data,config,model_dir):
    training_data=load_data(data)
    trainer=Trainer(RasaNLUModelConfig(config))
    trainer.train(training_data)
    model_directory = trainer.persist(model_dir, fixed_model_name= 'horoscope_bot')

train_nlu('./data/data.json','config.json','./models/nlu')

#And this is the issue I keep getting
Traceback (most recent call last):
  File "code.py", line 12, in <module>
    train_nlu('./data/data.json','config.json','./models/nlu')
  File "code.py", line 7, in train_nlu
    trainer=Trainer(RasaNLUModelConfig(config))
  File "/home/ahzam/venv/lib/python3.6/site-packages/rasa_nlu/config.py", line 119, in __init__
    self.override(configuration_values)
  File "/home/ahzam/venv/lib/python3.6/site-packages/rasa_nlu/config.py", line 196, in override
    self.__dict__.update(config)
ValueError: dictionary update sequence element #0 has length 1; 2 is required

**Comment by akelad** [comment]
Thanks for raising this issue, @erohmensing  will get back to you about it soon.

**Comment by erohmensing** [comment]
hi @Ahzam-Lathiya , it looks like what you're passing to `RasaNLUModelConfig` isn't the data inside `config.json`, but rather the string `'config.json'` itself. 

Here's what I recommend:
 - Rasa NLU configurations are by best practice found in yml files. I would turn your `config.json` to a `config.yml` that looks like pipelines found here: https://rasa.com/docs/nlu/choosing_pipeline/
 - Once you've done this, the `config.load` function will load your config and return an instantiated `RasaNLUModelConfig` object as in the code below.

Suggested code (I've changed the `config` variable to make it more clear where you're passing only a file name, not a config, and to avoid confusion with the module name):
```
def train_nlu(data,config_file,model_dir):
    training_data=load_data(data)
    trainer=Trainer(config.load(config_file))
    trainer.train(training_data)
    model_directory = trainer.persist(model_dir, fixed_model_name= 'horoscope_bot')

train_nlu('./data/data.json','config.yml','./models/nlu')
```
Let me know if this works for you.

**Comment by Ahzam-Lathiya** [comment]
This is what im getting. 
I'm using an i5 1st generation laptop.
YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  return yaml.load(read_file(filename, "utf-8"))
2019-03-18 13:45:08.929185: F tensorflow/core/platform/cpu_feature_guard.cc:37] The TensorFlow library was compiled to use AVX instructions, but these aren't available on your machine.
Aborted (core dumped)

**Comment by erohmensing** [comment]
This is more of a Tensorflow issue than a Rasa one, it seems that your machine doesn't support the version of tensorflow that rasa nlu requires ([here](https://github.com/tensorflow/tensorflow/issues/24548), someone at TensorFlow says "the AVX instruction set ... is supported from the second generation of Intel Core CPUs")

I'm afraid there may not be an easy solution to that problem. It's possible you could follow the advice on that thread and try to find a pre-compiled version or one that supports instructions that your machine supports, perhaps from the link someone provided [here](https://github.com/lakshayg/tensorflow-build) -- it seems there's one for tensorflow 1.12.0 for Ubuntu 18.04 on Python 3.6.5 (so you'd have to change to that version), but it would require playing around with, and I can't guarantee it'd work, as we don't test on those custom builds of TensorFlow.

Unfortunately without a compiled TensorFlow, you can't use the `tensorflow_embeddings` pipeline. Other pipelines/components (like spacy) should work, though.

**Comment by math77** [comment]
Hello, after I compile a version of TF without avx how can I make my rasa installation use that version and not the one by default?
