### ISSUE TITLE
robust entity value extraction problem

### ISSUE THREAD

**Issue by m3xw3ll** [RasaHQ/rasa_nlu#1758]
**Rasa NLU version:** 0.14.3

**Operating system:** Windoes 10

**Content of model configuration file:**
language: "de_core_news_sm"

pipeline:
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "ner_crf"
- name: "intent_featurizer_spacy"
- name: "intent_classifier_sklearn"
- name: "ner_synonyms"

**Issue**:
I try to extract the value of a entity 'domain' from a sentence. 
In my training data there is an example `'Who is responsible for the [network](domain:network)'`

I wrote a simple helper function in python to evaluate the model performance. For example the sentence "Who is responsible for the servers".
The model chooses the right intent but can not extract an entity. The sentence is almost the same like in the training data, only the entity value is different. 
How I make the model more robust against such errors?
I do not have many training examples but shouldn´t the model be able to extract the correct entity if the sentence is nearly the same like one in the training data?

**Comment by robinsongh381** [comment]
Have you tried  Lookup table ?
It might enhance the ner_crf performance
https://medium.com/rasa-blog/entity-extraction-with-the-new-lookup-table-feature-in-rasa-nlu-94c6c30876a3

**Comment by m3xw3ll** [comment]
I´ve heart about the lookup table but didn´t tried it yet. Is it the only option to gain a higher model performance?

**Comment by akelad** [comment]
Please ask these kind of questions in our [forum](https://forum.rasa.com)
