### ISSUE TITLE
rasa 0.14.4 fails to start with Python 3.6

### ISSUE THREAD

**Issue by abroojalil** [RasaHQ/rasa_nlu#1761]
**Rasa NLU version**:

**Operating system** (windows, osx, ...):

**Content of model configuration file**:
```yml

```

**Issue**:
![image](https://user-images.githubusercontent.com/11509107/53866159-b9a99b00-4012-11e9-81c3-d4512fb718cf.png)

(rasa) D:\starter-pack-rasa-stack>python -m rasa_nlu.train -c nlu_config.yml --data data/nlu_data.md -o models --fixed_model_name nlu --project current --verbose
D:\Anaconda\envs\rasa\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2019-03-06 13:13:43 INFO     rasa_nlu.utils.spacy_utils  - Trying to load spacy model with name 'en'
Traceback (most recent call last):
  File "D:\Anaconda\envs\rasa\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Anaconda\envs\rasa\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda\envs\rasa\lib\site-packages\rasa_nlu\train.py", line 184, in <module>
    num_threads=cmdline_args.num_threads)
  File "D:\Anaconda\envs\rasa\lib\site-packages\rasa_nlu\train.py", line 148, in do_train
    trainer = Trainer(cfg, component_builder)
  File "D:\Anaconda\envs\rasa\lib\site-packages\rasa_nlu\model.py", line 155, in __init__
    self.pipeline = self._build_pipeline(cfg, component_builder)
  File "D:\Anaconda\envs\rasa\lib\site-packages\rasa_nlu\model.py", line 166, in _build_pipeline
    component_name, cfg)
  File "D:\Anaconda\envs\rasa\lib\site-packages\rasa_nlu\components.py", line 441, in create_component
    cfg)
  File "D:\Anaconda\envs\rasa\lib\site-packages\rasa_nlu\registry.py", line 142, in create_component_by_name
    return component_clz.create(config)
  File "D:\Anaconda\envs\rasa\lib\site-packages\rasa_nlu\utils\spacy_utils.py", line 73, in create
    nlp = spacy.load(spacy_model_name, parser=False)
  File "D:\Anaconda\envs\rasa\lib\site-packages\spacy\__init__.py", line 21, in load
    return util.load_model(name, **overrides)
  File "D:\Anaconda\envs\rasa\lib\site-packages\spacy\util.py", line 119, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'en'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.

(rasa) D:\starter-pack-rasa-stack>python -c "import rasa_nlu; print(rasa_nlu.__version__);"
0.14.4

**Comment by erohmensing** [comment]
Hi @abroojalil, Rasa is trying to load your spacy model and failing to find it. I see you're using the starter pack -- did you install a spacy model using `python -m spacy download en` within your virtual environment as described in **Setup and installation** here? https://github.com/RasaHQ/starter-pack-rasa-stack

**Comment by abroojalil** [comment]
Requirement already satisfied: en_core_web_sm==2.0.0 from https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.0.0/en_core_web_sm-2.0.0.tar.gz#egg=en_core_web_sm==2.0.0 in d:\anaconda\envs\py36\lib\site-packages (2.0.0)
You do not have sufficient privilege to perform this operation.

    Linking successful
    D:\Anaconda\envs\py36\lib\site-packages\en_core_web_sm -->
    D:\Anaconda\envs\py36\lib\site-packages\spacy\data\en

    You can now load the model via spacy.load('en')
yes, I did.

**Comment by erohmensing** [comment]
To me it looks like the spacy package is located in the `py36` environment while you're trying to load it from within the `rasa` environment -- is this not the case?

**Comment by abroojalil** [comment]
> To me it looks like the spacy package is located in the `py36` environment while you're trying to load it from within the `rasa` environment -- is this not the case?

Actually, I created two different environments. both virtual environments are raising the same issue.

**Comment by erohmensing** [comment]
Hmm okay, I think you're running into the same security issue as this here: https://github.com/explosion/spaCy/issues/1283

I would read this thread and follow their suggestions -- i.e. try the security options thing first (giving symlink permissions to the relevant users) and if that doesn't work try I can try to help you to hack it using import like they've described instead. Unfortunately I'm not on windows so I can't reproduce the issue or test the fix, but let me know if that thread helps or if you're still stuck. Make sure to check out the links that user ines posted in the thread too :)
