### ISSUE TITLE
How to get one word answers into entities

### ISSUE THREAD

**Issue by tanmaysinghal98** [RasaHQ/rasa_nlu#1765]
I am using 0.13.1 and i want to implement this:-

user: create a new folder

bot: what should be the name of the folder?

user: let the name be Applications

bot: done

and

user: create a new folder

bot: what should be the name of the folder?

user: Applications

bot: done

and

user: create a new folder name Applications

bot: done

I have made a formAction for this. But the problem is, for single word answers it is guessing wrong intent like greet or goodbye. How to force nlu to look for specific intent if the entity is not captured in first intent. Even after forcing, how to train nlu for capturing entities from those single word answers.

**Comment by tanmaysinghal98** [comment]
intent:mkdir
create folder
new folder
new Directory
create a new directory
make folder
make a new folder
make Directory
create a new folder
create a folder named Downloads
new folder Tanmay
new folder sfesds
new folder Tasdascanmay
new folder Tasfscsdfvdddzscnmay
new folder Taenmdfgdtgdrsay
make directory with name Applications
make directory with name qdhebdefwer
make directory with name gftgbdgdrf
make directory with name edawdawde
make directory with name rdtgtg
please make a new folder and keep the name of folder Goa
please make a new folder and keep the name of folder rwrerfs
please make a new folder and keep the name of folder Grw4erw3oa
please make a new folder and keep the name of folder Goaxvxfvdvs
please make a new folder and keep the name of folder Godawdeqwewea
create a new directory with name India
create a new directory with name aefgajds
create a new directory with name Indefsrfsdawia
create a new directory with name Inqwsfdswqswdsfedia
create a new directory with name Indwewefdia
create a new folder tanmay
create a folder named laudjba
create a new folder rushabh
create a new folder sejfh
create a new folder woisdfsut
create a new folder rushsrggrafabh
create a new folder ruswewfwehabrgh
create a folder named djhf
create a folder named laudrglaa
create a folder named ljrgefjqerauda
create a folder named oweuro

intent:new_folder_mkdir
name of new directory is Pakistan
name of new directory is sefss
name of new directory is Pakisfsfaadstan
name of new directory is awsefsPaawaawakistan
name of new directory is Pafesfsejsajkistan
Pictures
Music
Downloads
Movies
madarjknnkjnchod
efsefs
madarsvsdcschod
madadsxasdawsrchod
awdsefsf
dcddcdcsd
sdsdfsfse
keep US as the name
keep shgdfnsdf as the name
keep ssfsefse as the name
keep sdfsdczsdsd as the name
keep jyuijyyujt as the name
keep UdfgdthS as the name
name should be Australia
name should be jfgjse dse
name should be Aussgdhgachmxaedaetralia
name should be Austdgdfvsdvsefralia
name should be efawaefefse
name should be efsrgrtr
keep it Kenya
keep it adsghfksjef
keep it sefjjeopoedpawjdka
keep it zdnasbda
keep it sfjksfefse
keep it as sfjksfefse
keep it as dfbsmesr
keep it as sfjkswadasxsfefse
keep it as sfjdgthgyjukuiksfefse
keep it as sfuikyujtyjksfefse
it should be named Priyanshi
it should be named fgjdgfdd
it should be named sdvxdvf
it should be named Priydgbfdanshi
it should be named Priyfvsdsdanshi

regex:new_folder
[a-zA-Z]+

**Comment by akelad** [comment]
Please ask these kind of questions in our [forum](https://forum.rasa.com)

**Comment by tanmaysinghal98** [comment]
@akelad I have already asked [there](https://forum.rasa.com/t/how-to-get-one-word-answers-into-entities/5790) but no one replied. That's why I created an issue.
