### ISSUE TITLE
Issue with missing dependencies tensorflow while training

### ISSUE THREAD

**Issue by pnandhini11** [RasaHQ/rasa_nlu#1782]
**Rasa NLU version**: 0.14.4

**Operating system** (windows, osx, ...): Windows

**Content of model configuration file**:
```yml

```

**Issue**:

When I tried to install Rasa today, though i have tensorflow installed in anaconda environment, I keep getting error while trying to train nlu model.  Any help??

![image](https://user-images.githubusercontent.com/19807328/54367104-d475b280-4697-11e9-9ce7-d4c9757e711a.png)

**Comment by akelad** [comment]
can you try running `pip show tensorflow`?

**Comment by pnandhini11** [comment]
![image](https://user-images.githubusercontent.com/19807328/54421660-e6f0fa00-4732-11e9-91ba-bab1df4e668a.png)

**Comment by akelad** [comment]
hmm that looks fine, training should work then... are you still experiencing difficulties with it?
