### ISSUE TITLE
evaluate error

### ISSUE THREAD

**Issue by rishi454** [RasaHQ/rasa_nlu#1788]
**Rasa NLU version**: 0.13.7

**Operating system** (windows.): windows 10

**Content of model configuration file**:
```yml

```

**Issue**:
(intelligent) D:\sr\nlu>python -m rasa_nlu.evaluate -d/--data data/data.json --config nlu_config.yml --mode crossvalidation

usage: evaluate.py [-h] -d DATA [--mode MODE] [-c CONFIG] [-m MODEL]
[-f FOLDS] [--errors ERRORS] [--histogram HISTOGRAM]
[--confmat CONFMAT] [--debug] [-v]

evaluate.py: error: unrecognized arguments: data/data.json --config nlu_config.yml --mode crossvalidation
while evaluating the rasa_nlu model, I am getting the above error. so any one can help me out.

**Comment by rishi454** [comment]
(intelligent) D:\sr\nlu>python -m rasa_nlu.evaluate -d/--data data/data.json \--config nlu_config.yml \--mode crossvalidation

usage: evaluate.py [-h] -d DATA [--mode MODE] [-c CONFIG] [-m MODEL]
                   [-f FOLDS] [--errors ERRORS] [--histogram HISTOGRAM]
                   [--confmat CONFMAT] [--debug] [-v]

evaluate.py: error: unrecognized arguments: data/data.json \--config nlu_config.yml \--mode crossvalidation

**Comment by imLew** [comment]
`(intelligent) D:\sr\nlu>python -m rasa_nlu.evaluate -d**/--data** data/data.json --config nlu_config.yml --mode crossvalidation`

You are specifying the `data` option twice. Remove the part printed in bold and it should work.
In general when a command line tool allows to specify an option in long-form and short-form (e.g. `--data` and `-d`) you should only user one them.
