### ISSUE TITLE
Temperature for intent features

### ISSUE THREAD

**Issue by tmbo** [RasaHQ/rasa_nlu#1798]
just a thought, if we don't want to be too sensitive to NLU model, but do want to support cases where multiple intents are probable, we could put the intent features through a softmax with a small temperature, to semi-binarise them, e.g.

```{python}
t = 0.1
p = np.exp(np.log(p) / t) / (np.sum(np.exp(np.log(p) / t)))
```

**Comment by akelad** [comment]
i think the Fallback policy covers this, so i'll close it
