### ISSUE TITLE
Training using multiple training data files

### ISSUE THREAD

**Issue by sankethpb** [RasaHQ/rasa_nlu#180]
Am a beginner with RASA Nlu, need some suggestions regarding below.
I want my bot to handle multiple intents. So, I want to train rasa_nlu with multiple intents. Is it required to create one training json with all intents or should I use separate training json for each instance? If I have to use separate file, I think rasa_nlu creates different models for each file. Is it possible to load multiple models at once per instance of rasa_nlu?

I use backend Spacy_scikitlearn.

Thanks in advance.

**Comment by tmbo** [comment]
@sankethpb feel free to use the gitter chat for these kinds of questions (https://gitter.im/golastmile/rasa_nlu).

If you want to classify multiple intents, you do not necessarily need multiple models. You can put all your training instances into one json file and use that to train the classifiers. The resulting model will be able to distinguish between the different intents (given enough training 😏 ).

Does that answer your question?

**Comment by sankethpb** [comment]
Thank you @tmbo  , I will use gitter chat next time :) 

Yes, it answers my question. I will start it using one file, but I think its going to be tough to maintain one json file as I keep adding new intents and extend existing intents. Will there be some improvements in this regard in future?

**Comment by tmbo** [comment]
Yeah, sure. So what you are basically looking for is a way to split the training data across multiple json files that are then used to train one model?

**Comment by Tejaf** [comment]
@tom how can one do that? split the training data across multiple json
files that are then used to train one model

**Comment by tmbo** [comment]
That's not implemented yet, just asking to clarify this is the feature you are looking for.

**Comment by sankethpb** [comment]
Yes, this is feature I am looking for. Thank you for clarifications.

**Comment by ram2408** [comment]
Is the enhancement done now? Like can we train the model using multiple files?
