### ISSUE TITLE
show conflicting stories during online training

### ISSUE THREAD

**Issue by JoeyFaulkner** [RasaHQ/rasa_nlu#1802]
A really cool and useful tool we could have is for Core to show, when instructing the bot on what it should be doing, conflicting or potentially conflicting stories in the training set. i.e. if you wanted to teach

```
*_intent_greet
 - action_greet
```
and there was a story in the training set
```
*_intent_greet
 - action_goodbye
```
then it would warn you about that one to show inconsistencies.

**Comment by akelad** [comment]
i think there's a newer issue about this
