### ISSUE TITLE
Configure path to export stories to after online lerning

### ISSUE THREAD

**Issue by deviantdes** [RasaHQ/rasa_nlu#1820]
**Rasa Core version** (e.g. `0.7.3`):
0.7.1
**Operating system** (windows, osx, ...):
Windows 10
**Issue**:
Hi there
For this example in https://core.rasa.ai/tutorial_fake_user.html , Where do i set the story path for exporting ?
the action for `0.Export current conversations as stories and quit`

i tried exporting but there don't seems to have any stories created.

Thanks in advance
**Content of domain file** (if used & relevant):
```yaml

```

**Comment by ihtisham0331** [comment]
I am facing same issue.I am unable to save online training  to my stories when i Press 0 to export my stories and quit.It did not export the stories.Please help me to resolve this issue
my Rasa nlu==0.11.4
rasa-core==0.7.0
