### ISSUE TITLE
Is there a reliable way to control the dialog flow using intent confidence levels?

### ISSUE THREAD

**Issue by ssanin82** [RasaHQ/rasa_nlu#1840]
**Rasa Core version** : `0.7.3`

**Operating system**: linux

**Issue**: Aside from "hacky" way of overriding certain methods of, for example, MessageProcessor class, is there any way to execute a specific predetermined action if last intent confidence level was below certain threshold? (for example, utter "I didn't understand. Please, be clear...")

Similarly, it'd be nice to know is there any standard supported way to implement other logic based on confidence level - for example, if 1st 2 intents in intent ranking are very close by confidence, I want to ask a clarifying question.

**Comment by akelad** [comment]
we've implemented the TwoStageFallbackPolicy so closing this
