### ISSUE TITLE
Correct entities during online training

### ISSUE THREAD

**Issue by benjamin-work** [RasaHQ/rasa_nlu#1857]
**Rasa Core version**: 0.7.3

**Python version**: 3.6

**Operating system**: Ubuntu 16.04

**Issue**: During online training, there is no possibility to correct false entities. It would be great if that worked.

Ideally, there should be an option "4. The entities are wrong", then an option to choose the entity type, then the possibility to fill the entity.

**Comment by akelad** [comment]
implemented
