### ISSUE TITLE
delay sending of messages

### ISSUE THREAD

**Issue by lokeshlal** [RasaHQ/rasa_nlu#1876]
Hello,

I have used MS bot framework in past and sending delayed messages is quite simple in MS bot framework. as a reference conversation:

_User: Can you please give me details of my last year trips
Bot: Please wait, while I find the information
... after 5 seconds
Bot: Here is the information of last year trips... <and then the information of trips>_

How this behavior can be achieved in RASA Core?

Thanks,
Lokesh

**Comment by akelad** [comment]
this behaviour can be achieved with a custom action, so i'll close this issue

**Comment by mohiitaa** [comment]
Hi, 

I am still not sure how custom actions can be used for inducing delay between responses. I tried using reminders but it does not work for me. 

Could someone help me?
