### ISSUE TITLE
"Wrong fb secret!" - How to configure the Facebook Connector correctly? - Python 3 only

### ISSUE THREAD

**Issue by bastiW** [RasaHQ/rasa_nlu#1893]
**Rasa Core version**: rasa-core (0.8.0a4, /root/rasa_core) including pull request #160 

**Python version**: Python 3.6.3 |Anaconda, Inc.

**Operating system** : Ubuntu 16.04.3

**Issue**:

I have a problem with connection the FB Messenger. I have included pull request #160 and also tried it with the old dependency pymessenger and with my workaround here  is supposed in Bug #153 

I get the **errormessage**:

```
2018-01-08 12:13:06 WARNING  rasa_core.channels.facebook - Invalid fb verify token! Make sure this matches your webhook settings on the facebook app.
127.0.0.1 - - [2018-01-08 12:13:06] "GET /webhook?hub.mode=subscribe&hub.challenge=246570936&hub.verify_token=my-rasa-testbot HTTP/1.0" 200 157 0.001802
2465709362018-01-08 
```
if i run

```
python -m rasa_core.run -d models/dialogue -u models/nlu/current    --port 5002 --connector facebook --credentials credentials.yml

```

and send a message (as an owner) to my Bot. 

The webhook looks like it is correctly installed:
![webhook](https://user-images.githubusercontent.com/7667003/34671199-e5ba5008-f479-11e7-9b2b-ef37866133b3.JPG)
I connect to my bot via an nginx proxy server with an Let's encrypt cert installed. 

In the `credentials.yml` I use the `secret ` from here. Is this correct?
![app secret](https://user-images.githubusercontent.com/7667003/34671241-14a1bdf2-f47a-11e7-9062-10708d9671c7.JPG)

What else can I try?

**Comment by LkhagvasurenAmar** [comment]
Hi 
I have the exact same problem 
Help 
[https://drive.google.com/file/d/16ooJc6E05QVDUy4lN7Sn6IU81_oBUkTO/view?usp=sharing](url)
Wrong fb secret! Make sure this matches the secret in your facebook app settings
