### ISSUE TITLE
 utils.configure_colored_logging(loglevel="DEBUG") AttributeError: module 'rasa_core.utils' has no attribute 'configure_colored_logging'

### ISSUE THREAD

**Issue by 12max34** [RasaHQ/rasa_nlu#1913]
**Rasa Core version**: rasa-core (0.7.9)

**Python version**: Python 3.5.4 :: Anaconda, Inc.

**Operating system** (windows, osx, ...): ubuntu

**Issue**:
File "bot.py", line 105, in <module>     utils.configure_colored_logging(loglevel="DEBUG") AttributeError: module 'rasa_core.utils' has no attribute 'configure_colored_logging'

**Content of domain file** (if used & relevant):
```yaml

```
The contents of bot.py is same as restaurant bot.py file in examples

**Comment by Keerlsm** [comment]
I have meet the same issue in rasa 1.1.8, soooo which version should I use?

```python
Python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 14:00:49) [MSC v.1915 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import logging
>>> from rasa import utils
>>> from rasa.core.validator import Validator
>>> logger = logging.getLogger(__name__)
>>>
>>> utils.configure_colored_logging('DEBUG')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'rasa.utils' has no attribute 'configure_colored_logging'
```
