### ISSUE TITLE
Improve automatic slot filling to take previous bot actions / utterances into account

### ISSUE THREAD

**Issue by anshulsolanki** [RasaHQ/rasa_nlu#1921]
**Rasa Core version**:
7.9

**Python version**: 
3.6

**Operating system** (windows, osx, ...):
windows

**Issue**:
rasa-nlu identifies the intent and entities, rasa core fills the slots and takes the next action. 

but rasa core performs in a way, where next action and filling of slots is not context aware and both seems to happen in isolation. Here is an example from restaurant bot.

you - Hello 
bot - How can i help you?
you - i need some food.
bot - what kind of cuisine would you like?
you - for six people

at this point the slot for people gets filled by value two. Why it happens. Because NLU said there is entity for 'people' and slot for filled for it. Even though the original question from bot was about cuisine.
Worst, the state machine thinks it has successfully passed that state and never returns to ask for cuisine again.
I my view the answer by user should be read in context of the question asked.

What are some of the thoughts for this? how should this be handled.

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by akelad** [comment]
i think this logic is filled with forms now
