### ISSUE TITLE
Guess next user intent, conjoint probabilities, proper intent definition

### ISSUE THREAD

**Issue by Le-Fix** [RasaHQ/rasa_nlu#1941]
### Question/Enhancement

Does Rasa Core take the entire intent ranking or the most confident intent exlusively? (Well I'm pretty sure it isn't but no idea what the devs already thinking of/working on)

E.g. NLU can't properly differenciate between to intents, but regarding the conversation core/or rl person could easily decide to take the second intent which has bit less confidence but is much more likely in the current conversation context

I guess the correct mathematical term is: joint probability distribution.

---
Example from my own work:
4 basic intents
- Confirm Action
- Confirm Value
- Deny Action
- Deny Value

For safety reasons some actions/recognized values need an explicit verification.
The "Confirm" Intents **partially overlap**:
"Is the value foo correct for paramater bar?" (Needs value verification)
"Should I perform the foo task?" (Needs action verification)
-> "Yes", "I'm fine with that", "I agree"
-> "No", "I Disagree"

**partially diverge**
-> "Do that", "Don't wait any longer" should invoke/verify the action
-> "The value is correct", "The parameter is right" should confirm/set the value

in conclusion
"Should I perform the foo task?" -> "The value is correct"
"Is the value foo correct for paramater bar?" -> "Do that"
obviously doesn't count as *safe* confirmation

**Therefore**
- The intents cannot be fused
either
restrict the possible language (not user friendly) by not allowing "Do that","The value is correct"
or
allowing to "Do that" for value verification (not safe)
- The intents cannot be distinguished by stateless NLU
"I agree" probably will associate slightler higher confidenc to *confirm_action* than to *confirm_value* and as a result the user won't be able to confirm a value with "I Agree" (not user friendly)

**Potential solution**
However when following a conversation it's easy to distinguish
"I agree" *confirm_value*
"I agree" *confirm_action*
so the Core part could easily ignore the *confirm_value* intent even though it has a slightly higher confidence score than *confirm_action* intent based on the bots previous action: utter_ask_for_foo_task_confirmation

So the core part could learn (probably already does due to magic of ML) which intents the user is saying next and assigns probabilities to the intents (expectation). Conjoining both probability distributions (NLU, Core) should allow what has been described above.
(Random/Out of context utterances by the user should still be recognized correctly which assumes that the Core probability distribution is somewhat close to the uniform distribution. This probably can be solved differently using a fallback/default action but the main idea stays the same)

**Better(?) already applicable solution**
While writing this I've got the idea to divide them into three(6) intents,
- *confirm_generic*
- *confim_value*
- *confirm_action*
- *deny_generic*
- *deny_value*
- *deny_action*

which probably is the best way and makes the question obsolete.
(Just need to double the stories and make on half with confirm_generic and the other half confirm_value but without using confirm_action and vice versa)

**Why I don't think this is the perfect solution?**
- Now generating data for the nlu intents becomes more difficult because developpers have to draw a line between *confirm_generic* and *confirm_value*
... *confirm_value*? ah I'll add "I agree" ah no that's too generic let's delete it... ;-)
- ML tends to End-to-End models and keeping things strictly apart won't last forever
(Single utterance intent classifcation is nice "simple" task, conversation modelling based on pre-classified intents as well, but both would profit from each others knowledge)
---
I know that in ML "safety" is often hard to measure and needs alot of work and verification depending on the industry standards. When I write "safe" here I mean wrong actions which are tedious to revert or hidden/invisible for the user. So they should be prevented but don't have to be technically impossible.

Feel free to suggest or directly change the title to something better.

Anyway I'm interested in your feedback and thoughts on this.
- Any misconceptions of mine
- Best solution with current release
- What does already exist elsewhere (e.g Dialogflow combines Core and NLU to small extent afaik)
- Maybe some interesting research papers considering this issue

**Comment by akelad** [comment]
i'm closing this because the main functionality can be achieved by the TwoStageFallbackPolicy, but we're still working on similar topics
