### ISSUE TITLE
How to pass parameters to a custom action

### ISSUE THREAD

**Issue by Kaijiro** [RasaHQ/rasa_nlu#1950]
**Rasa Core version**: 0.8.2

**Python version**: 2.7

**Operating system** (windows, osx, ...): Ubuntu 16.04

**Issue**:
When creating a custom action like the ApiAction example (https://core.rasa.ai/patterns.html#storing-api-responses-in-the-tracker), we could need some parameters (API URL, etc....). 
The idea behind this is to be able to define only one action to make as many REST call on different and not known APIs.

How can we pass those parameters in the story ?

** Example Story ** :
```yaml
## story_a
* greetings
  - utter_greetings
  - webhook_action # -> we need parameters here : which API do we call ?

```

**Content of domain file** (if used & relevant): Not relevant here.

**Comment by mounabenayed** [comment]
Did you find a solution for this issue ?

**Comment by MohammadYosifSharaf** [comment]
Hi @Kaijiro   , we have the same issue and we want to call multi API at run time, we need to pass these APIs as parameters through the tracker, to use it in the custom action, what is the idea of your final solution for this issue?

any help will be appreciated

Thanks

**Comment by mohanbabubb** [comment]
> Hi @Kaijiro , we have the same issue and we want to call multi API at run time, we need to pass these APIs as parameters through the tracker, to use it in the custom action, what is the idea of your final solution for this issue?
> 
> any help will be appreciated
> 
> Thanks

Where you able to find any way ?. i see some suggesting to use the slots to store and retrieve on the custom actions function.!
