### ISSUE TITLE
[FEATURE] Include confidence of predicted next_action

### ISSUE THREAD

**Issue by gregfitz23** [RasaHQ/rasa_nlu#1951]
**Rasa Core version**:
0.8.3

**Operating system** (windows, osx, ...):
OS X

**Issue**:
I have a use case where understanding the confidence / probability of the predicted `next_action` would be very valuable.  It appears that the default `EnsemblePolicy` has this information available as it is logged in `debug` mode.

This could be introduced as a non-breaking interface by adding a `next_action_confidence` to the response.  

Thanks in advance for consideration.

**Comment by akelad** [comment]
functionality exists now
