### ISSUE TITLE
Install Rasa_Core 0.8.3 fails on Windows10 with Python version 3.6.4 due to tensorflow version not available

### ISSUE THREAD

**Issue by csplrj** [RasaHQ/rasa_nlu#1953]
**Rasa Core version**:0.8.3

**Python version**: 3.6.4

**Operating system** (windows, osx, ...):Windows 10

**Issue**:
When I tried to install rasa_core using `pip install rasa_core` the following output comes and the rasa_core installation stops
`
Collecting rasa_core
  Downloading rasa_core-0.8.3.tar.gz (76kB)
    100% |████████████████████████████████| 81kB 173kB/s
Collecting jsonpickle (from rasa_core)
  Downloading jsonpickle-0.9.6.tar.gz (67kB)
    100% |████████████████████████████████| 71kB 341kB/s
Collecting six (from rasa_core)
  Downloading six-1.11.0-py2.py3-none-any.whl
Collecting redis (from rasa_core)
  Downloading redis-2.10.6-py2.py3-none-any.whl (64kB)
    100% |████████████████████████████████| 71kB 355kB/s
Collecting fakeredis (from rasa_core)
  Downloading fakeredis-0.9.0-py2.py3-none-any.whl
Collecting nbsphinx (from rasa_core)
  Downloading nbsphinx-0.3.1-py2.py3-none-any.whl
Collecting pandoc (from rasa_core)
  Downloading pandoc-1.0.2.tar.gz (488kB)
    100% |████████████████████████████████| 491kB 1.2MB/s
Collecting future (from rasa_core)
  Downloading future-0.16.0.tar.gz (824kB)
    100% |████████████████████████████████| 829kB 420kB/s
Collecting numpy>=1.13 (from rasa_core)
  Downloading numpy-1.14.1-cp36-none-win32.whl (9.8MB)
    100% |████████████████████████████████| 9.8MB 99kB/s
Collecting typing>=3.6 (from rasa_core)
  Downloading typing-3.6.4-py3-none-any.whl
Collecting requests (from rasa_core)
  Downloading requests-2.18.4-py2.py3-none-any.whl (88kB)
    100% |████████████████████████████████| 92kB 592kB/s
Collecting graphviz (from rasa_core)
  Downloading graphviz-0.8.2-py2.py3-none-any.whl
Collecting Keras (from rasa_core)
  Downloading Keras-2.1.4-py2.py3-none-any.whl (322kB)
    100% |████████████████████████████████| 327kB 425kB/s
Collecting tensorflow (from rasa_core)
  Could not find a version that satisfies the requirement tensorflow (from rasa_core) (from versions: )
No matching distribution found for tensorflow (from rasa_core)
`

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by Nishabijuv** [comment]
i got an error message while installing rasa on windows 10 using python 3.6 as
ERROR: Could not find a version that satisfies the requirement tensorflow-addons>=0.7.1 (from rasa) (from versions: none)
ERROR: No matching distribution found for tensorflow-addons>=0.7.1 (from rasa)
pls help
