### ISSUE TITLE
Support sending audio attachments

### ISSUE THREAD

**Issue by shasha79** [RasaHQ/rasa_nlu#1960]
**Rasa Core version**:
0.8.3
**Python version**: 
3.5
**Operating system** (windows, osx, ...):
Ubuntu 16.04
**Issue**:

Hi,
I need a bot to be able to send audio attachment via output channel (currently, only image attachments are supported). Do you have this feature in the roadmap? I can implement it (at least for console and Facebook) and make a pull request.

Thanks,
Alex

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by akelad** [comment]
closing bc we're refactoring I/O channels anyways
