### ISSUE TITLE
custom slot type 

### ISSUE THREAD

**Issue by lg05** [RasaHQ/rasa_nlu#2013]
**Rasa Core version**:0.8.05

**Python version**: 3.6

**Operating system** (windows, osx, ...):linux

**Issue**:
I create a custom slot type when i referenced the custom slot type in the domain file, it 
warns the custom slot type module path is wrong.I don’t find how to reference custom slot type in domain file in rasa core document .
anyone who can show me a
example is very appropriate ,thanks

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by baudzhou** [comment]
maybe you should try 
`export PYTHONPATH=/path/to/your/project/:$PYTHONPATH`

**Comment by saurabh-m523** [comment]
> maybe you should try
> `export PYTHONPATH=/path/to/your/project/:$PYTHONPATH`

Thank you so much, this worked!
