### ISSUE TITLE
Custom welcome message

### ISSUE THREAD

**Issue by aourednik** [RasaHQ/rasa_nlu#2023]
**Rasa Core version**: 0.8.5

**Python version**: 3.6

**Operating system** (windows, osx, ...): Ubuntu 16

**Issue**: Users often request the bot to utter something on startup, instead of being presented with an empty input. rasa-core actually provides a welcome message but it is hard-coded in console.py: "Bot loaded. Type a message and press enter: "
Would it be possible to make this message configurable? 
The solution I've found is overwriting the method, but that is a lot of code to change just one element in the method:

```python
...
from rasa_core.channels.console import * 
class MyConsoleInputChannel(ConsoleInputChannel): 
    def _record_messages(self, on_message, max_message_limit=None):
        utils.print_color("Hallo, ich bin ein ChatBot.",utils.bcolors.OKBLUE)
        num_messages = 0
        while max_message_limit is None or num_messages < max_message_limit:
            text = input().strip()
            if six.PY2:
                # in python 2 input doesn't return unicode values
                text = text.decode("utf-8")
            if text == INTENT_MESSAGE_PREFIX + 'stop':
                return
            on_message(UserMessage(text, ConsoleOutputChannel(),
                                self.sender_id))
        num_messages += 1
...
```

**Comment by nitinjain9282** [comment]
How to do it with rocket.chat

**Comment by cyrilthank** [comment]
> Many thanks for your answer. I was wondering if my workoaround would work for other channels.
> This seems to be a challenge for most chatbot frameworks (the MS bot framework has trouble with producing a welcome message, too). Yet our users say they are disoriented by an empty input in the messenger-like GUI frontend. Would you have an advice for making a story like this work?:
> 
> ```
> ## a story example
>     - bot_utter_greet
> * start
>     - utter_what_can_i_do_for_you
> ```
> 
> i.e. the bot would utter something defined in the domain as soon as the channel is opened

does this work on rasa-x ui?

**Comment by cryoff** [comment]
I know this is closed but I am still interested: is it possible to make a bot to send a greeting message on a startup when using rasa shell?
(same question raised here: https://forum.rasa.com/t/custom-welcome-message/12729/4)
