### ISSUE TITLE
Create domain and stories by programming?

### ISSUE THREAD

**Issue by luisdemarchi** [RasaHQ/rasa_nlu#2024]
**Rasa Core version**: 0.8.5

**Python version**: 3.6

**Operating system**: osx

**Issue**:
I did not find any reference on how to configure the domain and the stories directly through the source code. How do I do that? Or do I need to do a file generator, based on my database, and then do the training by calling the generated file?

PS: Why is not there a "rasa-core" tag in stackoverflow?

**Comment by Collen-Roller** [comment]
I made a library for the domain part of this if it will help anyone. https://github.com/Collen-Roller/Rasa-Denerator. You can install it with pip install rasa-denerator.

Keeps you from having to copy your intents, entities and actions to the domain file everytime!

Helps a lot when using rasa for production level bots with different domains for different bots and usecases
