### ISSUE TITLE
Interactive Learning with user-friendly interface

### ISSUE THREAD

**Issue by luisdemarchi** [RasaHQ/rasa_nlu#2025]
**Rasa Core version**: 0.8.5 

**Python version**: 3.6

**Operating system**: osx

**Issue**:
How can I "carry" interactive console learning to an HTTP / rest? The idea is to make a friendly front end for key people to do the training.

**Comment by amn41** [comment]
For anyone finding this via google - you can use Rasa X to do interactive learning with a GUI. 

Check out the docs [here](http://rasa.com/docs/rasa-x)
A video tutorial [here](https://youtu.be/VXvWdrr2yw8?t=681)

**Comment by ShaidaMuhammad** [comment]
@amn41 Rasa-x is no longer a free tool and there are no free GUI tools for interactive learning yet.
