### ISSUE TITLE
How to select attributes for training (epochs , max_history , batch_size)

### ISSUE THREAD

**Issue by AbdurRub** [RasaHQ/rasa_nlu#2030]
**Rasa Core version**: 0.8.5

**Python version**:  2.7

**Operating system** (windows, osx, ...): Ubuntu 17.10

**Issue**:
How can we change these attributes.  as default epochs: 100 , max_history is 3 and batch size is 20.
what are the basic guidelines we should keep in mind to handle these things because these 3 attributes gives clear impact on dialogue.
Can someone explain the logic behind these 3 in reference to our core and dialogue stories.

**Comment by 1000sprites** [comment]
if set max_history longer than story length, what is the max_history value?
