### ISSUE TITLE
categorical slot with less values than available

### ISSUE THREAD

**Issue by ctrado18** [RasaHQ/rasa_nlu#2031]
hi,

let's say you have an entity problem with 5 problems. But you just want to consider 3 of them for your stories. So you create in the domain file:

```
  problem:
    type: categorical
    values:  p1,p2,p3
```

Than I thought that only those 3 values would be recognized as slots? But I find that if a message conains an entity with problem p4 than this will be also a catgeorical slot of value p4?
But I want to ignore the rest of values other than defined in the slot above.

**Comment by artinegi1607** [comment]
@ctrado18  Is your issue resolved?
