### ISSUE TITLE
How to get User message ?

### ISSUE THREAD

**Issue by dilipbobby** [RasaHQ/rasa_nlu#2059]
**Issue**:
I want to get user message directly, when one of the intent is matched.I want to write a custom action class where I directly want to get users message ! Is it possible to get ? For getting Entities we are using tracker.get_slot() in same way do we have any other method to get user message directly In action class ?

**Comment by fakekphan** [comment]
how to get time lastest message ?

**Comment by Wing-e7** [comment]
> `tracker.latest_message.text` will do that

Can we get the previous 4-5 user messages as well ?

Using tracker.generate_all_prior_trackers doesn't work as it outputs other variables along with messages. Plus i get a plethora of errors when using the above.

I am trying to read all user messages related to a particular intent and analyse the whole combined text for subjectivity and sentiment. This needs to be done in  a custom action

**Comment by ravitejakammela** [comment]
I want to build a multi lang rasa bot but want to have all training in english. Can I access the user message before predicting intent and convert the language to english and send it for intent prediction?
