### ISSUE TITLE
Unable to enable CORS from HTTP API

### ISSUE THREAD

**Issue by auzair92** [RasaHQ/rasa_nlu#2063]
Specs: rasa-core v0.8.5 / rasa-nlu v0.11.4
OS: Linux 4.13.0-21-generic #24-Ubuntu SMP (Server) / Windows 10 (Client)

I am facing CORS issue while trying to call the Rasa server from a different origin (an Angular app hosted on different domain). I am trying the default [MoodBot](https://github.com/RasaHQ/rasa_core/tree/master/examples/moodbot) example, and facing the following error on client side (Windows 10 browser console):

> Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access. The response had HTTP status code 404.

I have tried:

- running the server with `--cors ['*']` option
- adding `"cors_origins" : ["*"]` to `nlu_model_config.json` file. 

The server responds correctly when using Postman to make the POST call. It was working without trying any CORS workaround as well. Valid JSON is received by Postman, and on server side, following message is displayed:

`"POST /conversations/default/parse HTTP/1.1" 200 635 "-" "PostmanRuntime/7.1.1"`

But when I make POST request from Angular app using no headers, server displays:

`"POST /conversations/uzair/parse/ HTTP/1.1" 404 233 "http://localhost:4200/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64)`

If I add `Content-Type: application/json` header with POST request from Angular, server returns:

`"OPTIONS /conversations/uzair/parse/ HTTP/1.1" 404 233 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64)` (`POST` is replaced by `OPTIONS` now)

The same 404 error posted on top is returned in both cases on client browser.

What am I doing wrong here? 

Cross SO question: [Link](https://stackoverflow.com/questions/49994909/enabling-cors-support-in-rasa-core-http-api)

**Comment by lohithpro** [comment]
The command should be auth-token  and not auth_token

**Comment by CryptoNinja0617** [comment]
how to run rasa action server?
