### ISSUE TITLE
Multiple entities with similar or same values

### ISSUE THREAD

**Issue by piyushporwal6795** [RasaHQ/rasa_nlu#2075]
Rasa Core version - 0.8.5

Python version - 3.5 

Operating system -  Windows 10

Issue - How rasa core can differentiate two slot values based on the user’s input? For example one slot is user and other slot is manager both have same or similar values like you can say it is in the format of FirstName.LastName?
How to use multiple slots with similar values?

And these slots defined in yaml file as type unfeaturized.

**Comment by timqian** [comment]
Meet the same issue recently.
We are using rasa_nlu for a rather big intent set. As the data set becomes larger, there are circumstance when two entities have same value.
For example:
"Chinese" can be a value of "country entity", and also be a value of "food type entity".
For now the ner_crf is not able to tell them apart.

One possible solution is, maybe we can provide `entity_ranking`(similar to intent ranking) so we can pick out the right entity out when the value is possible for two or more different entities

ref:

- probabilities to crf: https://github.com/RasaHQ/rasa_nlu/pull/883

**Comment by akelad** [comment]
@timqian ideally you should post usage questions on the [forum](https://forum.rasa.com). But have you tried using the same entity name and instead distinguishing which slot to put it in based on the context?

**Comment by timqian** [comment]
@akelad We are using rasa_nlu, it seem don't have `slot`

**Comment by akelad** [comment]
can you use rasa_core as well?

**Comment by arunsetty** [comment]
@akelad Please can you elaborate on using same entity for different slots using an example with the possible templates(excuse me for asking seemingly obvious question as I'm a beginner)
