### ISSUE TITLE
Rule-based intent recognition

### ISSUE THREAD

**Issue by jackolicious** [RasaHQ/rasa_nlu#208]
Say I'm trying to discern intents between "hello" and "goodbye" with one training example each ("hello" and "goodbye").

Is there a way to enable rule-based matching to reduce the training set requirements (https://spacy.io/docs/usage/rule-based-matching or https://wit.ai/docs/recipes#which-entity-should-i-use)

The goal being that the word "hello" would map to the "hello" intent without a huge training set of "hello" "hi" "Hello!" "hey" "HELLO!!!" etc.

**Comment by mikkelam** [comment]
You could just generate a shitload of these "hello" samples

**Comment by jackolicious** [comment]
@mikkelam correct. That's definitely an option!

**Comment by nmstoker** [comment]
That's a valid need, but in the choice between something built in and @mikkelam's idea, I'd go with the principle of least surprise. The latter idea would be more transparent and understandable, thus causing fewer cases of unintended consequences. And it would probably be more flexible (although I appreciate this depends on just how advanced a rule system you were envisaging!)

**Comment by tmbo** [comment]
The component based pipeline system is now merged. This mean we could now easily add another component that does the intent recognition based on regex patterns (e.g. similar to the existing https://github.com/golastmile/rasa_nlu/blob/master/rasa_nlu/classifiers/keyword_intent_classifier.py). You could even have both, a ML classifier and the regex based intent lookup in one pipeline.

I am not sure about the training data though, the current format doesn't support regexes and I haven't looked into the format of other services with regards to this. maybe @jackolicious you can provide more insights there

**Comment by tmbo** [comment]
we do have a regex component now that should ease that.
