### ISSUE TITLE
Auto updating domain.yml after training the model using python

### ISSUE THREAD

**Issue by stacybot123** [RasaHQ/rasa_nlu#2093]
**Rasa Core version**:0.9.0a2

**Python version**: 3.6

**Operating system** (windows, osx, ...): Windows 10

**Issue**:

I have a multi user/model structure where each model have  the training for specific industry for example model_1 have realstate , model_2 have mortgage based on the user . 

I have a form where a user can add question , answer and intent  to train the model. I am saving each of the text(question) and intent in their specific files and every time the user want to train the model I am rewriting the data.json with the training data.

The problem is how do I update the domian.yml file with the new intents and template responses. Does, there is an python script to generate domain.yml file based on the training data or some api endpoint that does that.

There are fixed actions so I do not have to worry about if they want to add a new action for now.

**Comment by Collen-Roller** [comment]
I wrote a solution for this if anyone is interested in automatically generating these files

https://github.com/Collen-Roller/Rasa-Denerator

The script will update a domain file when new actions are created within an actions module, new entities / intents are created within a training data fike, and automatically place templates within the actions section of the domain file to avoid copy/pasting utterances by hand.
