### ISSUE TITLE
How to set slot value automatically with predefined button payloads w/o training?

### ISSUE THREAD

**Issue by ewagner70** [RasaHQ/rasa_nlu#2100]
**Rasa Core version**: 0.9.0a3

**Python version**: 3.6

**Operating system** (windows, osx, ...): ubuntu 18.04

**Issue**: I would like to know if there's another possibility to set slot values automatically with predefined (ideally categorical) button payloads w/o intent training or user defined Actions?

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by mohamedHassanKa** [comment]
did you manage to solve it . how did you set slot value  with predefined button  from payloads
