### ISSUE TITLE
ValueError: on Action when trying to load Agent based post request

### ISSUE THREAD

**Issue by annadow75** [RasaHQ/rasa_nlu#2104]
**Rasa Core version**: 0.9.0a2

**Python version**: 3.6.5

**Operating system** (windows, osx, ...): Windows 10 

**Issue**:

How to handle request from HttpInputChannel when you have two bot created in two different folder under the root directory. I have a weather bot to get the current weather and the restaurant bot in example . Both of these are in their respective folders with different config files , stories and data folder.

I tried to load the Agent based on the folder name in  post request and it says 
```
ValueError: Action 'actions.ActionWeather' doesn't correspond to a template / action. Remember to prefix actions that should utter a template with `utter_`. Error: No module named 'actions'
```

**Comment by anilpankaj** [comment]
ValueError: Action '__main__.ApiAction' doesn't correspond to a template / action. Module doesn't contain a class with this name. Remember to prefix actions that should utter a template with `utter_`. Error: module '__main__' has no attribute 'ApiAction'

i got this error what can i do?

**Comment by TayyibahR** [comment]
@anilpankaj i am facing the same issue. did you find a way to resolve this issue?
