### ISSUE TITLE
allow for different log levels in ConsoleInputChannel and on file

### ISSUE THREAD

**Issue by disimone** [RasaHQ/rasa_nlu#2115]
**Rasa Core version**:
master (commit b0b76d8076b7165345477715b886f5771081c7f5)
**Python version**: 
3.5.2
**Operating system** (windows, osx, ...):
linux
**Issue**:

Hi, this is a followup on #449.

Logfiles are now being generated (thanks for the fix!), but they are forced to have the same loglevel as the ConsoleInput. In order to have a sensible chatting experience, the loglevel of the console needs to be kept at CRITICAL, while in principle one would want to log on file all the background of a converstation, which means DEBUG.

I am running with:

```
def run(serve_forever=True):

    utils.configure_colored_logging(logging.DEBUG)
    utils.configure_file_logging(logging.DEBUG,
                                 './rasa_core.log')

    log = logging.getLogger('werkzeug')
    log.setLevel(logging.WARN)

    interpreter = RasaNLUInterpreter("../../models/nlu/default/current")
    agent = Agent.load("../../models/dialogue", interpreter=interpreter)

    if serve_forever:
        agent.handle_channel(ConsoleInputChannel())
    return agent

```

the DEBUG messages are both printed on screen and saved on file. setting the colored_logging to CRITICAL and the file_logging to DEBUG, results in only CRITICAL messages being recorded (both on screen and on file).

**Comment by akelad** [comment]
i think we'll leave this as is
