### ISSUE TITLE
Slack triggers multiple messages to rasa (does not happen with Telegram/Commandline)

### ISSUE THREAD

**Issue by ewagner70** [RasaHQ/rasa_nlu#2120]
**Rasa Core version**: 0.9.0a5

**Python version**: 3.6

**Operating system** (windows, osx, ...): ubuntu 18.04

**Issue**: Slack triggers multiple messages to rasa and NO, this does not happen with Telegram and Commandline Interface (!) with the very same trained RASA_NLU and RASA_CORE models (!!)
Please, Rasa-Team: Try to reproduce that with any kind of story!

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by selident** [comment]
Hi Team, it seems this issue has been fixed for message with text only. 
Today when working with events, I always receive three same events if I upload a file (image). but it sends only 1 if I post a text message without images.
I think we missed the case for file uploading?
