### ISSUE TITLE
Imbalanced intent sample sizes during train

### ISSUE THREAD

**Issue by AndriiKr** [RasaHQ/rasa_nlu#213]
rasa NLU version): 0.7.1

Used backend & plattform: mitie_sklearn, Ubuntu 14.04

Issue: I will not provide any data examples they are so massive.
I found if I have 3 expressions in each intent and 9 expressions in one intent it's ok, if I add tenth expression and more the mess begins. Intents are eaten up by a greater intent and just ignored. Greater the quantitative difference, more and more small intents ignoring.
I can make a conclusion that more than triple quantitative difference broke it.

**Comment by tmbo** [comment]
should be fixed with weighted class balancing (at least for the sklearn intent classifier - e.g. the spacy_sklearn pipeline)
