### ISSUE TITLE
Support for multi domain HTTP server

### ISSUE THREAD

**Issue by karthikbalu** [RasaHQ/rasa_nlu#2158]
**Feature Request**

*master branch*

*3.6.4*

*OSX*
 
Please let me know, if we have any time line for implementing multi domain HTTP server that can handle message dynamically based on multiple domains specified by loading the appropriate module and processing the input message 

I tried command line but looks like it takes minutes to load and hence the model has to be loaded and maintained in the memory prior during the start of the HTTP Server and route input message accordingly

Please advice, we are in the process of completing the entire UI/UX for the rasa like "dialogflow" using all the latest tools such as mongodb, nodejs etc., and this is road block to proceed further

Thanks!

**Comment by karthikbalu** [comment]
Can you please let me know if there is a any other way to achieve this based on recent developments, since the issue is closed now

thanks

**Comment by akelad** [comment]
i think this is a duplicate of the other one i just commented on

**Comment by karthikbalu** [comment]
Please let me know the other issue, thanks

**Comment by jeffzhengye** [comment]
> checkout https://github.com/clofus/clofus-chatbot

@karthikbalu  clofus claims to support multi-domain, but I didn't see any code about it.
Could you show me where the code about multi-domain is ?
