### ISSUE TITLE
rasa NLU for mobile

### ISSUE THREAD

**Issue by AmitPoonia** [RasaHQ/rasa_nlu#216]
It would be great if there is a light-weight mobile version of RASA that can be deployed to both iOS & Android, for on-device NLU.

**Comment by amn41** [comment]
Thanks for making this suggestion! It's certainly possible, but device memory is likely to be a major constraint with the current implementation. Would love to hear suggestions for how to achieve this, though.

**Comment by amn41** [comment]
FYI spaCy 1.7 was just released and it includes a 50MB model - which is tiny! We need to do some QA but this should easily fit on any phone. Now for the question of language support...

**Comment by AmitPoonia** [comment]
Interesting, though 50mb is a bit on the higher side for a mobile app considering that this wouldn't be the only model or large file, and Spacy is only one of the dependencies.

For mobile NLU, ideally C/C++ bindings that can be compiled would be the best for cross-platform.

**Comment by amn41** [comment]
https://github.com/kivy/python-for-android

Could be interesting

**Comment by frink** [comment]
I agree that a C library would be idea. However, that's probably a VERY long term goal since the whole ecosystem of NLP / NLU / NER is built on Python and JavaScript right now. I'd love to see more C bindings since embedding Lua is a dream compared to the other major scripting languages and the FFI for Lua and Ruby is so simple. However, that's probably not possible right now.

**Comment by tmbo** [comment]
We won't tackle this anytime soon, especially since you can query the NLU over HTTP.

**Comment by smn-snkl** [comment]
is there any update on this? I know you can query the model via HTTP, but what if I want to have some offline chat capability for my app? Has there been any work on this subject yet?

**Comment by amn41** [comment]
hi @smn-snkl - thanks for checking in! this isn't something we've been working on actively, unfortunately
