### ISSUE TITLE
Problem settingup facebook connector webhook: response doesn't match the challenge

### ISSUE THREAD

**Issue by rusiaaman** [RasaHQ/rasa_nlu#2192]
**Rasa Core version**: 0.8.5

**Python version**: 3.6

**Operating system** (windows, osx, ...): Ubuntu 16.04.4 LTS

**Issue**:
I get the following error message on FB page while setting up webhook through ngrok:

`The URL couldn't be validated. Response does not match challenge, expected value="2035713680", received="{\"status\":\"ok\"}\n" `

The GET request received was:

`127.0.0.1 - - [2018-06-05 12:12:41] "GET /?hub.mode=subscribe&hub.challenge=2035713680&hub.verify_token=rasa-bot HTTP/1.1" 200 124 0.000667
`

On investigating the source code I looked at the relevant section in /channels/facebook.py from line 227:

``` 
        @fb_webhook.route("/", methods=['GET'])
        def health():
            return jsonify({"status": "ok"})

        @fb_webhook.route("/webhook", methods=['GET'])
        def token_verification():
            if request.args.get("hub.verify_token") == self.fb_verify:
                return request.args.get("hub.challenge")
            else:
                logger.warn("Invalid fb verify token! Make sure this matches "
                            "your webhook settings on the facebook app.")
                return "failure, invalid token"
```
From my understanding the GET request should have been similar to following (taken from some other issue):

`127.0.0.1 - - [2018-01-08 12:13:06] "GET /webhook?hub.mode=subscribe&hub.challenge=246570936&hub.verify_token=my-rasa-testbot HTTP/1.0" 200 157 0.001802
2465709362018-01-08 `

Especially the `/webhook` part which is missing from the GET message I received. The issue was resolved when I made the following changes to the code:

```
        #@fb_webhook.route("/", methods=['GET'])
        #def health():
        #    return jsonify({"status": "ok"})

        @fb_webhook.route("/", methods=['GET'])
        def token_verification():
            if request.args.get("hub.verify_token") == self.fb_verify:
                return request.args.get("hub.challenge")
            else:
                logger.warn("Invalid fb verify token! Make sure this matches "
                            "your webhook settings on the facebook app.")
                return "failure, invalid token"
```
Obviously this is not a permanent solution, but this gets the job done of validating the Facebook webhook. Looking at the latest source code it seems to me this section hasn't changed. I couldn't try the latest commit because my model is not supported. I haven't gone further in the chat-bot development so I don't know whether this change would break anything else or not. Can you please confirm if this is really an issue or something that I have done wrong.

**Comment by analyticalgagan** [comment]
@rusiaaman - Iam also facing same issue, my bot is published to gcp and using nginx and ssl certificates am trying to create webhook with facebook app but invalid fb token error appears.

Where can i find this file to change facebook.py or did you find any other alternative to solve this issue ?
