### ISSUE TITLE
setting slots directly from buttons

### ISSUE THREAD

**Issue by disimone** [RasaHQ/rasa_nlu#2198]
**Rasa Core version**:
commit b0b76d8076b7165345477715b886f5771081c7f5

**Python version**: 
3.5.2

**Operating system** (windows, osx, ...):
linux
**Issue**:

Hi, in the docs, you say that in case of a purely button-based bot, we would not need an NLU interpreter at all. However, I could not find the instructions on how to set slots directly from the buttons.

Examples and discussions I have found here seem to proceed as follows:

- define a button with a payload
- train an nlu interpteter to properly understand the payload and set the intent/entities
- let rasa_core map entities to slots

In a purely button-based bot, however, I think the best thing would be to let the button directly set intent and entities/slots. Is this supported? How does one avoid the NLU altogether?

Thanks for your help,

Andrea.

**Comment by sachin10101998** [comment]
Any solution to this? Need to fill slots on the basis of buttons chosen which is the original question asked in this issue.
