### ISSUE TITLE
What is the best way to train the rasa bot?

### ISSUE THREAD

**Issue by NikhilBansal21** [RasaHQ/rasa_nlu#2201]
**Rasa Core version**: 0.9.0a3

**Python version**: 3.6.5

**Operating system** (windows, osx, ...):10

**Issue**: I know you guys have given in docs the way to train a bot in rasa. But i am not able to understand it pretty well because of less content. I am using dialogflow agent data for my rasa core bot . It was working fine at first then i updated the bot with new intent's like i added some faq's in my bot. On adding that my welcome intent started misbehaving. The phrases of welcome intent like "Hi" catches an faq intent instead of welcome intent.  I don't want my bot to work in a specific flow. I just want it to act as an intent classifier and for entity extraction.
 I am sending you guys my stories.md snippet hope you can understand. I have just limiting it to welcome and faq intent only for now!

https://gist.github.com/NikhilBansal21/6be660f125b24e5fe5832331a6064543

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by memberAres** [comment]
How can i train my bot for law?
