### ISSUE TITLE
MITIE tokenizer() replacement

### ISSUE THREAD

**Issue by 2fat2kidnap** [RasaHQ/rasa_nlu#221]
**rasa NLU version:** `0.7.0a7` 

**Backend:** `MITIE`

**Operating System:** `macOS`

**Observed behaviour/issue:** See [this issue](https://github.com/mit-nlp/MITIE/issues/105) raised with the MITIE developer/maintainer. 

**Steps to reproduce:**
```
>>> import mitie
>>> string_1 = "Germany, way back then, won the world cup."
>>> string_2 = "Germany, in 1974, won the world cup."
>>> string_3 = "Germany won the world cup in 1974."

>>> mitie.tokenize(string_1)
['Germany', ',', 'way', 'back', 'then', ',', 'won', 'the', 'world', 'cup', '.']
>>> mitie.tokenize(string_2)
['Germany', ',', 'in', '1974,', 'won', 'the', 'world', 'cup', '.']
>>> mitie.tokenize(string_3)
['Germany', 'won', 'the', 'world', 'cup', 'in', '1974.']
```
Tokenising behaviour with string_1 is exactly as expected. However, if you look closely at string_2, you'll notice that it says `'1974,'` instead of `'1974', ','`. The same holds for string_3 at the end.
In rasa NLU, this causes the warning: `"Token '{0}' does not appear in tokenized sentence {1}.".format(token, text_tokens) +   "Entities must span whole tokens.")` which makes complete sense. rasa expects token `1974`, but only finds a token `1974,`, which doesn't match.

The MITIE dev has explained that while it looks to be a bug, he won't be updating the code, given that many people rely on MITIE behaviour remaining stable (see the link to the issue above).

**Expected behaviour:** Correct splitting of the punctuation from integers.

**Discussion:** I was thinking that perhaps `mitie.tokenize()` could be replaced by NLTK's [nltk.word_tokenize()](http://www.nltk.org/api/nltk.tokenize.html). It looks to do the same as the MITIE one at a first glance.
**However**, this would of course induce a dependency on NLTK, and on top of that, I don't know when/if they will officially drop support for Python2 (haven't found any indication they will, just wanted to put that out there).

**Comment by amn41** [comment]
The `pipeline` branch will make this really easy to implement. You can add your own tokenizer class (see [examples](https://github.com/golastmile/rasa_nlu/tree/pipeline/rasa_nlu/tokenizers)) and add them to your custom pipeline

**Comment by tmbo** [comment]
Now that we have the component based architecture in place, it would be really cool to use a different tokenizer and it is totally alright to add another optional dependency there as well.

**Comment by tmbo** [comment]
There is no a whitespace tokenizer as well as spacy tokenizer
