### ISSUE TITLE
How to remove sender_Id from InMemoryTrackerStore?

### ISSUE THREAD

**Issue by lisongshan** [RasaHQ/rasa_nlu#2222]
**Rasa Core version**:
0.9.4
**Python version**: 
3.6
**Operating system** (windows, osx, ...):
Linux
**Issue**:
Once a sender_id is added to InMemoryTrackerStore, it seems there is no function to remove it.  What is the best way to clear garbage sender_ids? 

I am using rasa_core http server, there is no end point for garbage collecting unneeded sender_ids.

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by Bandi-Saideva** [comment]
How to delete sender_id from InMemoryTrackerStore using actions.py method(or action), rasa version = 3.2.x
