### ISSUE TITLE
[Load balancing] - How many concurrent users a Rasa bot can handle?

### ISSUE THREAD

**Issue by imsurinder90** [RasaHQ/rasa_nlu#2236]
**Query**:
If I deploy Rasa Bot over the production. How many users can talk to the bot at the same time without getting delays in response?

**Comment by bamba518** [comment]
I have the same issue, it seems although the out of box solution with supervised embedding pipeline can handle about 40 concurrent connections, the response time increases linearly, so 2 concurrent is twice the time for 1, and this is using UUID and Jmeter for testing

**Comment by karman1102** [comment]
Has anyone tried locust for this approach? https://github.com/salgieri/rasa-locust-stress-test
