### ISSUE TITLE
[checkpoints] TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by reza-ebrahimi** [RasaHQ/rasa_nlu#2274]
**Rasa Core version**: master branch

**Python version**:  3.6.5

**Operating system** (windows, osx, ...): Ubuntu

**Issue**:
When I put checkpoints in stories file, it throws an error while training:

```python
/opt/python3.6/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
/opt/python3.6/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)
Processed Story Blocks:  40%|████████▍            | 55858/138686 [05:02<07:28, 184.81it/s, # trackers=1]Processed Story Blocks: 100%|████████████████████| 138686/138686 [16:19<00:00, 141.60it/s, # trackers=1]
Processed Story Blocks: 100%|███████████████████████████████| 138686/138686 [00:00<00:00, 337208.60it/s]
Processed Story Blocks: 100%|███████████████████████████████| 138686/138686 [00:00<00:00, 497263.38it/s]
Processed Story Blocks: 100%|███████████████████████████████| 138686/138686 [00:00<00:00, 521720.98it/s]
Traceback (most recent call last):
  File "bot.py", line 165, in <module>
    run(port=port)
  File "bot.py", line 140, in run
    train_dialogue()
  File "bot.py", line 128, in train_dialogue
    agent.persist(model_path)
  File "/home/chatbot/rasa/rasa_core/rasa_core/agent.py", line 332, in persist
    self.policy_ensemble.persist(model_path, dump_flattened_stories)
  File "/home/chatbot/rasa/rasa_core/rasa_core/policies/ensemble.py", line 158, in persist
    self._persist_metadata(path, dump_flattened_stories)
  File "/home/chatbot/rasa/rasa_core/rasa_core/policies/ensemble.py", line 135, in _persist_metadata
    self.training_trackers)
  File "/home/chatbot/rasa/rasa_core/rasa_core/policies/ensemble.py", line 58, in _training_events_from_trackers
    for t in training_trackers:
TypeError: 'NoneType' object is not iterable
```

Checkpoints:
```markdown
## greeting
* greet
 - utter_greet
 - utter_ask_help
> say_greeting

## goodbye
* goodbye
 - utter_welcome
 - utter_goodbye
> say_goodbye
```

**Comment by sanchit892** [comment]
hey I think I am also getting that same error:

C:\Users\sanchit\PycharmProjects\chatbots\venv\Scripts\python.exe C:/Users/sanchit/PycharmProjects/chatbots/train_init.py
C:\Users\sanchit\PycharmProjects\chatbots\venv\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\sanchit\PycharmProjects\chatbots\venv\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\sanchit\PycharmProjects\chatbots\venv\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\sanchit\PycharmProjects\chatbots\venv\lib\site-packages\tensorflow\python\framework\dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\sanchit\PycharmProjects\chatbots\venv\lib\site-packages\tensorflow\python\framework\dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\sanchit\PycharmProjects\chatbots\venv\lib\site-packages\tensorflow\python\framework\dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Processed Story Blocks: 100%|██████████| 4/4 [00:00<00:00, 4006.98it/s, # trackers=1]
Processed Story Blocks: 100%|██████████| 4/4 [00:00<00:00, 1334.38it/s, # trackers=4]
Processed Story Blocks: 100%|██████████| 4/4 [00:00<00:00, 181.90it/s, # trackers=20]
Processed Story Blocks: 100%|██████████| 4/4 [00:00<00:00, 173.89it/s, # trackers=20]
Traceback (most recent call last):
  File "C:/Users/sanchit/PycharmProjects/chatbots/train_init.py", line 11, in <module>
    agent.persist('./models')
  File "C:\Users\sanchit\PycharmProjects\chatbots\venv\lib\site-packages\rasa_core\agent.py", line 609, in persist
    self.policy_ensemble.persist(model_path, dump_flattened_stories)
  File "C:\Users\sanchit\PycharmProjects\chatbots\venv\lib\site-packages\rasa_core\policies\ensemble.py", line 172, in persist
    self._persist_metadata(path, dump_flattened_stories)
  File "C:\Users\sanchit\PycharmProjects\chatbots\venv\lib\site-packages\rasa_core\policies\ensemble.py", line 146, in _persist_metadata
    self.training_trackers)
  File "C:\Users\sanchit\PycharmProjects\chatbots\venv\lib\site-packages\rasa_core\policies\ensemble.py", line 51, in _training_events_from_trackers
    for t in training_trackers:
TypeError: 'NoneType' object is not iterable

Process finished with exit code 1
