### ISSUE TITLE
Rasa Core Error: Error: connect ECONNREFUSED 127.0.0.1:5005

### ISSUE THREAD

**Issue by Haythamamin** [RasaHQ/rasa_nlu#2297]
**Rasa Core version**:
rasa-core==0.9.7
**Python version**: 
Python 2.7.15rc1
**Operating system** (windows, osx, ...):
Ubuntu 18.0.4
**Issue**:
```
hamin101@ubuntu:~/rasaui$ sudo npm start

> RasaUI@0.2.0 start /home/hamin101/rasaui
> node server/server.js

Rasa UI Server: http://localhost:5001

Express server listening on port 5001

Rasa NLU Error: Error: connect ECONNREFUSED 127.0.0.1:5000
Using connection string from: package.json


Rasa Core Error: Error: connect ECONNREFUSED 127.0.0.1:5005
Using connection string from: package.json


Postgres DB Connected
Using connection string from: package.json
Postgres Server: 127.0.0.1:5432
Database:rasa
Schema:public
```
Why am I getting the Error: connect ECONNREFUSED 127.0.0.1:5000 for Rasa NLU and Error: connect ECONNREFUSED 127.0.0.1:5005 for Core?

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by devopsspider** [comment]
Rasa NLU Error: Error: connect ECONNREFUSED 127.0.0.1:5000
Using connection string from: package.json

what is the solutions any body solve this issuess
