### ISSUE TITLE
Can Rasa handle question answering

### ISSUE THREAD

**Issue by arachny** [RasaHQ/rasa_nlu#2308]
**Rasa Core version**: 0.9.7

**Python version**:  3.6

**Operating system** (windows, osx, ...): ubuntu18.04

**Issue**:

I just wanted to have your opinion on whether Rasa can handle multiple questions and answers that normally would not be more than just one level or two of a dialogue flow. For example asking several websites offer Q&As that could potentially be handled by the chatbot.

I can see how Rasa's intent recognition would work nicely and find what the question is about, but then how would it pick from an answer, especially if there are multiple matches.

I suppose we could build many intents that map to a few answers (to randomly select from), but what if there are thousands of intents (i.e. questions) and those keep growing. Can Rasa handle anything like that (since is already using SpaCy for featurisation) or should we be looking to integrate Rasa into another modules?

Anyone has any experiences or ideas?

**Comment by Naveen733** [comment]
HI 
If a user asks the unwanted questions or questions which are not listed in our stories then how can i handle it

**Comment by krtrimaiq** [comment]
> HI
> If a user asks the unwanted questions or questions which are not listed in our stories then how can i handle it

Please check the fall back actions in rasa documentation
