### ISSUE TITLE
multilingual chatbot

### ISSUE THREAD

**Issue by MinhMinnie** [RasaHQ/rasa_nlu#2353]
**Rasa Core version**: 0.9.6

**Python version**: python 3

**Operating system** (windows, osx, ...): Ubuntu

**Issue**:
I want to build a multilingual chatbot. for EX, when a user starts a conversation in French, The bot will response in French. if user types something in English, the bot will start the conversation in English. How can I do this? (I will use google translate API to detect language and translate)  
My idea is:
1. Create multiple agents in some languages 
2. Choose a default language, but allow switching to the other languages
3. Use language detection.
but I do not know how to make it work . 
 

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by mellahysf** [comment]
> @souvikg10 Could you help me please?
> I start the conversation by "Get started" button in fb messenger.
> The bot gives me 3 options, "Choose a language" is one of them
> After choosing "Choose a language", I have 2 choices : English and Français (I have 2 models : English and French)
> The bot is pre loaded with English model
> If I click on button "Français", How to reload the bot with the French model?
> 
> ![capture d ecran de 2018-08-28 18-37-17](https://user-images.githubusercontent.com/42778118/44734239-aeb50180-aae9-11e8-91a5-32a7f508a8f5.png)
@akelad 
Hi,
Did you implemented this ?

**Comment by seak-source-code** [comment]
i have same issue as these there seem to be rasa not support on this

**Comment by rgstephens** [comment]
Is there also the possibility of detecting language before connecting to Rasa. If the front end is a react widget, can't you detect the users language preference in Javascript from the browser and point the React widget at the rasa endpoint for their preferred language?  Seems like you could do the same from a mobile app.
