### ISSUE TITLE
Interactive learning as http server

### ISSUE THREAD

**Issue by jonDel** [RasaHQ/rasa_nlu#2418]
**Rasa Core version**:
rasa-core           0.9.8

**Python version**: 
Python 3.6.6 :: Anaconda, Inc.

**Operating system** (windows, osx, ...):
Fedora Linux

**Issue**:

Is there a way to run the interactive learning as a http server? Or, at, least, call its components programmatically, instead of using the usual CLI?
Reasoning: I want to build a simple frontend boostrap interface, very similar to the one I'll use to effectivelly chat with the bot (https://github.com/jonDel/simple_chat_interface), but with the purpose of training it. Then, the boring part of training the bot could be delegated to non-technicians, who are of course not familiar with CLI or terminal interfaces.

**Comment by dmnmht** [comment]
@akelad can you please elaborate how to run interactive learning as http server as I don't understand issue #343 you are referring above.

**Comment by dmnmht** [comment]
@jonDel Do you have got any lead how to use this as http server ?

**Comment by Aavesh** [comment]
@akelad hey please help to provide more clarity as how we can run interactive learning as http server. Also can interactive learning be carried out through external channels like messenger,slack ,or a custom one

**Comment by nikhilcss97** [comment]
Hey any progress here? Trying to do the same thing.
