### ISSUE TITLE
Improve build and test speed

### ISSUE THREAD

**Issue by twerkmeister** [RasaHQ/rasa_nlu#243]
Currently building and testing rasa on travis takes around half an hour. This impedes quick turnaround cycles.

Testing costs around 80-90% of this time. We might approach it in a tiered fashion to fail and see errors earlier.

I investigated if the other 10-20% could be saved by using caching features of Travis-CI. Unfortunately, Travis is using non-local caching at S3, so anything that takes long to download and is quick to install doesn't help. This is the case for us, as the largest part of the setup cost are downloading spacy and mitie models.

**Comment by tmbo** [comment]
I think there are a couple of locations where we could reuse pipelines instead of retraining them, hence saving the time of the training.
