### ISSUE TITLE
ConsoleInputChannel is Gone

### ISSUE THREAD

**Issue by adrianhumphrey111** [RasaHQ/rasa_nlu#2441]
**Rasa Core version**: Current Github Master

**Python version**: Python3.6

**Operating system** (windows, osx, ...): osx

**Issue**: The ConsoleInputChannel is no longer in channels.console. It breaks on my local machine and it also breaks inside of the Quick Start on the Documents page.

![image](https://user-images.githubusercontent.com/16964539/44634925-5f899800-a954-11e8-8189-7bb2f0b01a92.png)

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by Aashaybane** [comment]
Th link dosnt work @akelad

**Comment by WahabBhatti** [comment]
> Th link dosnt work @akelad

Try this link:
https://github.com/RasaHQ/rasa_core/blob/master/rasa/run.py
