### ISSUE TITLE
Enable HTTPS/SSL on rasa core server 

### ISSUE THREAD

**Issue by kumarkrish85** [RasaHQ/rasa_nlu#2509]
**Rasa Core version**: 0.11.3

**Python version**: 3.6.2

**Operating system** (windows, osx, ...): windows 10

**Issue**:

I am trying to hit RASA Core server (http) from my site (https), I am getting the below error

> Mixed Content: The page at 'https://mysite.com/index.php#' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://<ip>:5005/conversations/default/respond'. This request has been blocked; the content must be served over HTTPS.

I need to enable SSL in the RASA Core server, please share any docs?

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by Aakashdeveloper** [comment]
hi i am looking for running over nginx any .conf file or link that can help.

**Comment by AbhimanyuAnilkumar** [comment]
create ssl certificate and key using certbot. and replace the key file and crt file location respectively
rasa run --ssl-certificate /etc/letsencrypt/live/(Website)/fullchain.pem  --ssl-keyfile  /etc/letsencrypt/live/(Website)/privkey.pem  --enable-api -m model
