### ISSUE TITLE
Interactive learning can export current conversations as stories and continue

### ISSUE THREAD

**Issue by GaoQ1** [RasaHQ/rasa_nlu#2519]
**Rasa Core version**:
rasa-core 0.11
**Python version**: 
python 3.6
**Operating system** (windows, osx, ...):
windows 10
**Issue**:
As the tittle, can rasa-core interactive learning export current conversations as stories and continue. Now everytime it quite and I have to retrain the dialogue. Tks!

**Comment by ihtisham0331** [comment]
I am facing same issue.I am unable to save online training to my stories when i Press 0 to export my stories and quit.It did not export the stories.Please help me to resolve this issue
my Rasa nlu==0.11.4
rasa-core==0.7.0
