### ISSUE TITLE
Slot Setting and Filling from Button

### ISSUE THREAD

**Issue by asaiyed10** [RasaHQ/rasa_nlu#2525]
**Rasa Core version**:
11.3
**Python version**:  2.7

**Operating system** (windows, osx, ...):
ox
**Issue**:

These buttons that are not setting slots when selected by the user. 

I think im using the correct  / intent { entitiy : }   relationship, maybe I'm missing something obvious? My slot and entities are named the same.... 
The code is below. I would like the slot to set the type of cough selected by the user

#### domain.yml
    slots:
      cough:
        type: text
        initial_value: "empty"

    intents: 
      - symptoms_cough_wheezing
      - symptoms_cough_difficult

    entities:
      - cough

    templates: 

         utter_cough:
          - text: "You seem to be experiencing a cough. Please select the best description"
            buttons:
              - title: I am experiencing wheezing
                payload: '/symptoms_cough_wheezing{"cough":"wheezing"}'

              - title: Are you having shortness of breath? 
                payload: '/symptoms_cough_difficult{"cough":"shortness of breath"}'

```
##cough 1
* symptoms_cough
  - utter_cough
* symptoms_cough_wheezing{"cough": "wheezing"}
  - slot{"cough": "wheezing"}
  - action_1

```
```
##cough 2
* symptoms_cough
  - utter_cough
* symptoms_cough_wheezing{"cough": "difficult"}
  - slot{"cough": "difficult"}
  - action_2
```

**Comment by ravitejakammela** [comment]
I have a button with the title "Low". Whenever a user clicks this button I want this title("Low") should be set as the slot value. This particular button is mapped to an intent "incident". The slot name is "priority". Can anyone suggest to me how to achieve this?

**Comment by jonra1993** [comment]
Hello, Do you know how can I set a slot of type list using an action server? I am trying to create a checklist functionality I have the frontend ready but I am stuck on how to set the slot. This is a sample code. The idea is when the button is pressed it sets a slot of type List (a list of strings). I am using Rasa 3.0.3. I would really appreciate your help.

action.py

```
class ActionAskFeelings(Action):

    def name(self) -> Text:
        return "action_ask_feelings"

    async def run(self,
                  dispatcher: CollectingDispatcher,
                  tracker: Tracker,
                  domain: Dict[Text, Any]) -> List[Dict[Text, Any]]:

        app_dict = {
            'products': ['happy', 'great']
        }
        app_json = json.dumps(app_dict)
        dispatcher.utter_message(
            text='How do you feel',
            buttons=[
                {
                    "title": "great",
                    "type": "postback",
                    "payload": "/tell_hello_world{}".format(app_json),
                },
                {
                    "title": "super sad",
                    "type": "postback",
                    "payload": "/mood_sad",
                }
            ]
        )
        # dispatcher.utter_message(attachment=MOCK_SCHEMA)
        return []
```

I defined the slot in this way on domain.yml

```
slots:
  products:
    type: list
    mappings:
      - type: custom
```

This is the warning message I got

![image](https://user-images.githubusercontent.com/23468720/147181293-d9cb240a-b417-4428-98c1-003c49c13f4b.png)

I created an action to print the slot value after pressing the button, but it is always empty

![image](https://user-images.githubusercontent.com/23468720/147181326-e917e047-e534-4ba6-8598-138b19f1ff43.png)
