### ISSUE TITLE
HTTP API endpoint to export trained core+nlu models

### ISSUE THREAD

**Issue by nielsrolf** [RasaHQ/rasa_nlu#2543]
**Rasa Core version**:
rasa-core==0.11.5
**Python version**: 
3.6
**Operating system** (windows, osx, ...):
os x 10.13.1
**Issue**:
I would like to use the rasa HTTP API to train models and then export them from there, or send trained models (core + nlu) to the HTTP API. In the docs I could only find how to import core models, but not nlu models. If this is not a feature already / in progress, I would like to start a PR for that.

**Comment by kostaskat** [comment]
Are there any follow-up discussions or considerations to re-open this request? Currently, all major NLU/bot platforms (e.g. Dialogflow, LUIS etc.) do support either getting (exporting) a model (agent) or importing (putting) a model (agent), via REST endpoints.

Are there considerations to include that in the merged Rasa Core server and the HTTP endpoints it exposes?Would relevant PRs be prioritized/promoted?

Thank you for the great work!

**Comment by amn41** [comment]
Hi @kostaskat - these functions are all supported via the [Rasa X API](https://rasa.com/docs/rasa-x/api/rasa-x-http-api/#tag/Models)
