### ISSUE TITLE
can I map intent None in stories.md?

### ISSUE THREAD

**Issue by cesar-devera-movile** [RasaHQ/rasa_nlu#2547]
**Rasa Core version**: 0.10.4

**Python version**: 3.6.3

**Operating system** (windows, osx, ...): Linux CentOS 7.5.1804

**Issue**: 

sometimes rasa_nlu returns an intent None in the online training (probably when the confidence is very low). 

my question is: is there a way to map that intent None in the stories.md file? so I can handle those cases and send an utter like "sorry, I did not understand"?

I tried importing the EmbeddingPolicy and usign the x_for_no_intent argument, but the import always fail. (probably it is not available in my version). I was trying to return a "default intent" when no intent was found, but I coundn't get it working. 

I already have an out_of_scope intent in my setup with multiple examples of out-of-scope, but it will never be 100% complete, so... I thought I could try to handle the None intents in rasa_core. 

suggestions?

**Comment by bhandari-nitin** [comment]
> for now, I created a custom component to use in the rasa_nlu pipeline, that translates the None intent to out_of_scope:
> 
> ```
> from rasa_nlu.components import Component
> 
> class CustomComponent(Component):
>     name = "CustomComponent"
>     provides = ["intent"]
>     requires = []
>     defaults = {}
>     language_list = None
> 
>     def __init__(self, component_config=None):
>         super(CustomComponent, self).__init__(component_config)
> 
>     def train(self, training_data, cfg, **kwargs):
>         pass
> 
>     def process(self, message, **kwargs):
>         if message.get("intent")['name'] == None:
>             message.set("intent", {'name': 'out_of_scope', 'confidence': 1})
> ```
> 
> then, on nlu_config.yml:
> 
> ```
> language: "pt"
> 
> pipeline: 
> - name: "tokenizer_whitespace"
> ... other components ...
> - name: "customNLU.CustomComponent"
> ```
> 
> is this a reasonable approach?

Hi @cesar-devera-movile, I get the following error while trying out your approach.

```    component.process(message, **self.context)
  File "/Users/nitin.bhandari/Documents/GitHub/Work/sd-jpmc-rasa/customComponent.py", line 18, in process
    if message.get("intent")["name"] == None:
TypeError: 'NoneType' object is not subscriptable```
