### ISSUE TITLE
 Couldn't connect to the server

### ISSUE THREAD

**Issue by zhuohaochen** [RasaHQ/rasa_nlu#2559]
I create new CustomAction and succeeded registering it. And I also create a endpoints.yml file: action_endpoint:
  url: "http://localhost:5055/webhook"
core_endpoint:
  url: "http://localhost:5055"

and use --endpoints in the command. But when my program calls the custom action it shows "Failed to run custom action...Couldn't connect to the server at 'http://localhost:5055/webhook'" 
What's wrong with it?

**Comment by nabajitdey** [comment]
> python -m rasa_core_sdk.endpoint --actions action

@tmbo @zhuohaochen  please elaborate the firewall/ proxy settings approach. I also having the same issue.

**Comment by mayurkuwar43** [comment]
Hello, i am facing the same error , please help me.
 Failed to run custom action 'lead_form_p1'. Couldn't connect to the server at 'http://localhost:5055/webhook'. Is the server running? Error: Cannot connect to host localhost:5055 ssl:default [Connect call failed ('127.0.0.1', 5055)]
2020-07-31 18:39:55 ERROR    rasa.core.processor  - Encountered an exception while running action 'lead_form_p1'. Bot will continue, but the actions events are lost. Please check the logs of your action server for more information.

**Comment by rahulfibro** [comment]
> Are you sure `python -m rasa_core_sdk.endpoint --actions action` is still running? it needs to run in the background - you can not stop it to execute the other commands (use a second shell for that).
> 
> If it is actually running, another issue might be firewall / enterprise proxy settings that prevent you from connecting

Thanks to making easy my RASA work

**Comment by Shivappa** [comment]
> 

Did you get any solution ? Even I am facing same issue.
