### ISSUE TITLE
Conversation logs

### ISSUE THREAD

**Issue by jahirfiquitiva** [RasaHQ/rasa_nlu#2578]
**Rasa Core version**: 0.11.8
**Python version**: 3.7
**Operating system** (windows, osx, ...): macOS Mojave

**Issue**:
Hello

I am wondering where the conversation logs are located. I already tried looking into `rasa_core.log` but it contains only internal code related logs.

I would like to have the conversation logs like:
```md
- Hello (user)
- How are you? (bot)
- I'm good (user)
...
```

Something like that. Is it possible? If so, how can it be achieved? Thanks in advance!

**Comment by jainkrunal** [comment]
Hey @akelad,

rasa_core.log doesn't contain the conversation, it has only errors or warning thrown!..
Is there a file that contains which intents are classified by the bot or conversation??

**Comment by jainkrunal** [comment]
Hey @akelad,

rasa_core.log doesn't contain the conversation, it has only errors or warning thrown!..
Is there a file that contains which intents are classified by the bot or conversation??
