### ISSUE TITLE
Allow multiple stories being generated during interactive learning

### ISSUE THREAD

**Issue by smn-snkl** [RasaHQ/rasa_nlu#2583]
**Rasa Core version**:
0.11.6
**Python version**: 
Python 2.7.15
**Operating system** (windows, osx, ...):
osx
**Issue**:
Starting up the interactive learning session takes quite a while. So it would be nice to add multiple stories in one session. Right now you can use /restart to start over, but you lose your progress by doing so. Maybe there could be a /new to start a new conversation / story.

**Comment by bishtamit** [comment]
> Ok, I just found the solution. Instead of restarting with /restart which clears the history, you should /stop and then select "Start fresh". Then you keep all the stories.
> 
> Thanks, that's great!

Thanks this works for me
