### ISSUE TITLE
Getting AttributeError: module 'rasa_core.training.online' has no attribute 'serve_agent' while doing interactive learning

### ISSUE THREAD

**Issue by vikingsvivek** [RasaHQ/rasa_nlu#2610]
**Rasa Core version** 0.13.6

**Operating system** windows

**Content of model configuration file:**
{
"pipeline":"spacy_sklearn",
"path":"./models/nlu",
"data":"./data/data.json"
}

Issue:
Getting error
INFO:rasa_core.policies.keras_policy:Done fitting keras policy model
Traceback (most recent call last):
File "train_online.py", line 37, in 
run_product_online(nlu_interpreter)
File "train_online.py", line 30, in run_product_online
online.serve_agent(agent)
AttributeError: module 'rasa_core.training.online' has no attribute 'serve_agent'

**Comment by Sudheertati** [comment]
Traceback (most recent call last):
  File "train_online.py", line 28, in <module>
    agent = train_agent(interpreter)
  File "train_online.py", line 14, in train_agent
    return rasa_core.train.train_dialog_model(domain_file="horoscope_domain.yml",
AttributeError: module 'rasa_core.train' has no attribute 'train_dialog_model'

**Comment by akelad** [comment]
please create a new issue
