### ISSUE TITLE
Issue with retraining interactive learning

### ISSUE THREAD

**Issue by samarth12** [RasaHQ/rasa_nlu#2623]
**Rasa Core version**:
 0.11.12
**Python version**: 
Python 3.6.5
**Operating system** (windows, osx, ...):
MacOS
**Issue**:
I am using the quickstart bot provided in the rasa core documentation and running interactive learning on it. I am also using a corresponding nlu model for the intents for it. After running a few iterations I stop and export the stories.md file which is correctly updated and appended as well. 

Now if I try retraining the model I am thrown with this error: 

Samarths-MacBook-Pro:axio_bot samarth$ python -m rasa_core.train   --online -o models/dialogue   -d domain.yml -s stories.md   --endpoints endpoints.yml --nlu models/current/nlu
/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
:0: UserWarning: You do not have a working installation of the service_identity module: 'No module named 'service_identity''.  Please install it from <https://pypi.python.org/pypi/service_identity> and make sure all of its dependencies are satisfied.  Without the service_identity module, Twisted can perform only rudimentary TLS client hostname verification.  Many valid certificate/hostname mappings may be rejected.
/anaconda3/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/current/nlu/entity_synonyms.json'
  "".format(entity_synonyms_file))
2018-10-15 10:18:12.544627: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
INFO:tensorflow:Restoring parameters from models/current/nlu/intent_classifier_tensorflow_embedding.ckpt
2018-10-15 10:18:12 INFO     tensorflow  - Restoring parameters from models/current/nlu/intent_classifier_tensorflow_embedding.ckpt
/anaconda3/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)
Processed Story Blocks:   0%|               | 0/5 [00:00<?, ?it/s, # trackers=1]Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/anaconda3/lib/python3.6/site-packages/rasa_core/train.py", line 239, in <module>
    additional_arguments)
  File "/anaconda3/lib/python3.6/site-packages/rasa_core/train.py", line 185, in train_dialogue_model
    training_data = agent.load_data(stories_file, **data_load_args)
  File "/anaconda3/lib/python3.6/site-packages/rasa_core/agent.py", line 472, in load_data
    debug_plots)
  File "/anaconda3/lib/python3.6/site-packages/rasa_core/training/__init__.py", line 57, in load_data
    return g.generate()
  File "/anaconda3/lib/python3.6/site-packages/rasa_core/training/generator.py", line 282, in generate
    trackers = self._process_step(step, incoming_trackers)
  File "/anaconda3/lib/python3.6/site-packages/rasa_core/training/generator.py", line 477, in _process_step
    tracker.update(event)
  File "/anaconda3/lib/python3.6/site-packages/rasa_core/training/generator.py", line 136, in update
    self._append_current_state()
  File "/anaconda3/lib/python3.6/site-packages/rasa_core/training/generator.py", line 106, in _append_current_state
    self._states.append(frozenset(state.items()))
**AttributeError: 'NoneType' object has no attribute 'append'**

I am not sure why this is happening. By my understanding, if I retrain the model again interactive learning should be infulenced by the changes I made last time right? If some intent for misclassified it should get it right with a better confidence after the retrain? Please corrent me if I am wrong. 

Here is the command I running to train the basic quickstart bot:

**python -m rasa_core.train   --online -o models/dialogue   -d domain.yml -s stories.md   --endpoints endpoints.yml --nlu models/current/nlu**

**Content of domain file** (if used & relevant):
```yaml

domain.yml
intents:
  - greet
  - goodbye
  - mood_affirm
  - mood_deny
  - mood_great
  - mood_unhappy

actions:
- utter_greet
- utter_cheer_up
- utter_did_that_help
- utter_happy
- utter_goodbye

templates:
  utter_greet:
  - text: "Hey! How are you?"

  utter_cheer_up:
  - text: "Here is something to cheer you up:"
    image: "https://i.imgur.com/nGF1K8f.jpg"

  utter_did_that_help:
  - text: "Did that help you?"

  utter_happy:
  - text: "Great carry on!"

  utter_goodbye:
  - text: "Bye"
```

Please let me know if you need any further details, thank you!

**Comment by ihtisham0331** [comment]
I am facing same issue.I am unable to save online training to my stories when i Press 0 to export my stories and quit.It did not export the stories.Please help me to resolve this issue
my Rasa nlu==0.11.4
rasa-core==0.7.0
