### ISSUE TITLE
Error while Integrating with slack

### ISSUE THREAD

**Issue by mk4224** [RasaHQ/rasa_nlu#2632]
**Rasa Core version**: = 0.11.5

**Python version**:  2.7

**Operating system** (windows, osx, ...): unix

**Issue**:  When i am giving request URL it is giving error message. Your request URL gave us a 500 error. Update your URL to receive a new request and challenge value. 

Please help me to fix this issues.

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by ntmtrinh** [comment]
@mk424 please tell me how to fix error above
