### ISSUE TITLE
postprocessor of agent

### ISSUE THREAD

**Issue by fakesecret** [RasaHQ/rasa_nlu#2654]
**Rasa Core version**: 0.10.1

**Python version**:  3.6

**Operating system** (windows, osx, ...): Linux

**Issue**:
*Edit*
Here, a postprocessor means a "general NLU postprocessor", which can take input the parsed data from NLU such as Rasa-NLU and correct the results by some hand-crafted rules, correction by previous conversation, database mapping, etc. The main reason why this part is not included in NLU because we can use rasa-core slots to correct NLU results. The main reason why I don't want to include this part in actions is because an intent can also be modified before a decision of action is made. I don't really like to add an "action_general_postprocess" systematically into the training story.

With some discussion with community members (see below), we think most people maybe don't need this "general NLU postprocessor", but they can implement this directly in actions. Implmentation in actions makes more sense with current rasa-core designe. So I close this issue, but for those who have to implement this directly into the rasa-core process, I have a solution by adding `MessageProcessorWithPost(MessageProcessor)` and `AgentWithPost(Agent)` in order to postprocess NLU-parsed data, without modifying Rasa-core source code, stated below:

-------------------------------
*the 1st version of this post*
 We need to add an argument `message_postprocessor=None` in `Agent.handle_message`, `handle_channel` and `_create_processor`; and `MessageProcessor.__init__`. Most important, 2 lines need to be added in `MessageProcessor._handle_message_with_tracker`:
```python3
        parse_data = self._parse_message(message)
        if self.message_postprocessor is not None:  # added
            parse_data = self.message_postprocessor(parse_data, tracker) # added
```
The postprocessor is like:
```python3
def postprocess(parse_data, tracker):
    # type: (Dict, DialogueStateTracker) -> Dict
```

**Comment by solhd** [comment]
> Well for us,
> Let's take the example i gave above
> 
> our story looks like
> 
> ```
> * transfer_money{amount_of_money:"20"}
> - set_currency
> - slot{"currency":"euros"}
> - utter_confirm_amount
> * affirm
> - make_transfer
> ```
> 
> Now as you know with ner_duckling, it sends back an entity - "amount-of-money" with value - 20 and then some additional info like currency 'euros' for example.
> 
> With rasa core automatic slot filling from entity, it will set the money to the value 20 but that is not enough to make a transfer so we add a custom action set_currency that runs separately which basically parses the tracker object and looks for the entity amount-of-money and tries to parse the additional info to look for currency.
> we then return SlotSet("currency":"euros"}, where currency is text slot which enables the check if this particular slot is filled, it will call the next action - utter_confirm_action which has a template
> you want to send {amount-of-money} {currency} ?
> and the story goes on. So really we did some post processing outside the rasa stack because it is really linked to particular use-case, you should handle everything specific outside of rasa stack.

could you please suggest how to access the `additional_info` in the `set_currency` custom action ?

**Comment by agrawal-mohit** [comment]
> Well for us,
> Let's take the example i gave above
> 
> our story looks like
> 
> ```
> * transfer_money{amount_of_money:"20"}
> - set_currency
> - slot{"currency":"euros"}
> - utter_confirm_amount
> * affirm
> - make_transfer
> ```
> 
> Now as you know with ner_duckling, it sends back an entity - "amount-of-money" with value - 20 and then some additional info like currency 'euros' for example.
> 
> With rasa core automatic slot filling from entity, it will set the money to the value 20 but that is not enough to make a transfer so we add a custom action set_currency that runs separately which basically parses the tracker object and looks for the entity amount-of-money and tries to parse the additional info to look for currency.
> we then return SlotSet("currency":"euros"}, where currency is text slot which enables the check if this particular slot is filled, it will call the next action - utter_confirm_action which has a template
> you want to send {amount-of-money} {currency} ?
> and the story goes on. So really we did some post processing outside the rasa stack because it is really linked to particular use-case, you should handle everything specific outside of rasa stack.

Could you please suggest how to access the `additional_info` in the custom action `set_currency`?
Many thanks.
