### ISSUE TITLE
How to configure the action endpoint from within python script

### ISSUE THREAD

**Issue by tahesse** [RasaHQ/rasa_nlu#2660]
**Rasa Core version**:

    rasa-addons==0.4.3
    rasa-core==0.10.4
    rasa-core-sdk==0.11.5
    rasa-nlu==0.13.7

**Python version**: 3.6.6

**Operating system** (windows, osx, ...): GNU/Linux (Arch Linux) 4.18.14

**Issue**: Unclear on how to set action endpoint in my python script in which the dialogue model is trained.

**Content of domain file** (if used & relevant):
```yaml
intents:
  # add your intents
  - get_started
  - greet

entities:
  - forename

slots:
  forename:
    type: text

templates:
  # GENERAL PURPOSE UTTERANCES
  utter_greet:
    - text: "Hallo! Wie kann ich dir weiterhelfen?"

actions:
  # all the utter actions from the templates, plus any custom actions
  - utter_greet
  - action_store_forename

```

Hey there,

I'm trying to call a custom Action through my action endpoint `python -m rasa_core_sdk.endpoint --actions actions` after training the NLU through `python3.6 -m rasa_nlu.train -c nlu_config.yml --data data/nlu_data.md -o models --fixed_model_name nlu --project current --verbose` and my python script for training the dialogue model looks as follows:

    # -*- coding: utf-8 -*-
    
    import os
    import warnings
    
    from rasa_addons.webchat import WebChatInput, SocketInputChannel
    from rasa_core.agent import Agent
    from rasa_core.featurizers import MaxHistoryTrackerFeaturizer, BinarySingleStateFeaturizer
    from rasa_core.interpreter import RasaNLUInterpreter
    from rasa_core.policies import MemoizationPolicy
    from rasa_core.policies.fallback import FallbackPolicy
    from rasa_core.policies.keras_policy import KerasPolicy
    from rasa_core.utils import read_endpoint_config
    from ruamel import yaml
    
    
    def train_dialogue(domain_file, model_path, training_folder):
        policies = [
            MemoizationPolicy(max_history=3),
            KerasPolicy(MaxHistoryTrackerFeaturizer(BinarySingleStateFeaturizer(), max_history=3)),
            FallbackPolicy(fallback_action_name='utter_default', nlu_threshold=0.8, core_threshold=0.4)
        ]
    
        endpoint_cfg = read_endpoint_config('endpoints.yml', 'action_endpoint')
    
        agent = Agent(
            domain=domain_file,
            interpreter=RasaNLUInterpreter('models/current/nlu/'),
            policies=policies,
            action_endpoint='http://0.0.0.0:5055/',  # <--- where to put this endpoint ?
        )
    
        training_data = agent.load_data(training_folder)
    
        agent.train(training_data, epochs=300)
        agent.persist(model_path)
        return agent
    
    
    if __name__ == '__main__':
        warnings.simplefilter('ignore', yaml.error.UnsafeLoaderWarning)
    
        agent = train_dialogue('domain.yml', 'models/current/dialogue', 'data/core/')
    
        # create dialogue graph for debugging
        agent.visualize('data/core/stories.md', output_file='debug/stories.png', max_history=15)
    
        static_asset_path = os.path.join(os.path.dirname(os.path.realpath(__file__)), 'templates')
        input_channel = WebChatInput(static_assets_path=static_asset_path)
        agent.handle_channel(SocketInputChannel(5000, '/', input_channel))

and my `actions.py`:

    from rasa_core_sdk import Action
    from rasa_core_sdk.events import SlotSet

    class ActionStoreForename(Action):
        """Stores the users name in a slot"""
    
        def name(self):
            return "action_store_forename"
    
        def run(self, dispatcher, tracker, domain):
            forename = next(tracker.get_latest_entity_values('forename'), None)
    
            # if no name was extracted, use the whole user utterance
            # in future this will be stored in a `name_unconfirmed` slot and the
            # user will be asked to confirm their name
            if not forename:
                forename = tracker.latest_message.get('text')
    
            return [SlotSet('forename', forename)]

I also have a `endpoints.yml` file in the same folder with the content:

    action_endpoint:
      url: "http://localhost:5055/"

**My question:** How can I actually manage to add the `action_endpoint` to my python script?

PS.: Moreover, when running the action endpoint server and curling from it, I run into further issues:

    INFO:__main__:Starting action endpoint server...
    INFO:rasa_core_sdk.executor:Registered function for 'action_store_forename'.
    INFO:__main__:Action endpoint is up and running. on ('0.0.0.0', 5055)
    127.0.0.1 - - [2018-10-24 10:07:33] "GET /version HTTP/1.1" 404 342 0.023045

when using both, `curl http://0.0.0.0:5055/version` or `curl http://localhost:5055/version`.

**Comment by SuzanaK** [comment]
> You don't need an action endpoint for training your dialogue model. And the reason the `/version` endpoint doesn't work is because it doesn't exist.
> If you want to pass an action endpoint to running the bot, please take a look at the run script (https://github.com/RasaHQ/rasa_core/blob/master/rasa_core/run.py#L224), or use the run script to start your bot.
> I'm going to close this as it's a usage question. If you would like to know more, please post in our [forum](https://forum.rasa.com)

The link is dead.
