### ISSUE TITLE
Accessing files, using relative filepath, in custom actions endpoints

### ISSUE THREAD

**Issue by stalinsabu** [RasaHQ/rasa_nlu#2672]
**Rasa Core version**: 0.11.12

**Python version**: 3.6.6

**Operating system** (windows, osx, ...): windows 10

**Issue**:
I recently migrated to 0.11. As per the migration document the new actions run as endpoints in webhooks. Now the problem is; I have saved JSON files to access data from it for my bot to use. But now since it is running in the web, the relative path to the file is not possible and i get my error (I used try catch) 
```
127.0.0.1 - - [2018-10-29 09:45:08] "POST /webhooks/rest/webhook?stream=true&token= HTTP/1.1" 200 265 1.110955
Sorry we are down for the moment : [Errno 2] No such file or directory: 'info/images/images.json'
```
my actions.py looks like this
```
from rasa_core_sdk import Action, Tracker
from rasa_core_sdk.events import SlotSet, EventType

import requests
import json
import re
import sys

class ActionGetDiagram(Action):
    def name(self):
        return 'action_get_diagram'

    def run(self, dispatcher, tracker, domain):
        try:
            filename = "info/images/images.json"
            datastore = dict()
            with open(filename, 'r') as f:
                datastore = json.load(f)
            diagram_item = tracker.get_slot('diagram_item')

            if diagram_item not in datastore or diagram_item=="":
                response = "I dont understand what you are looking for?"
            else:
                dispatcher.utter_template('utter_here_you_go', tracker)
                response = datastore[diagram_item][0]["name"]+"\n"+datastore[diagram_item][0]["url"]
            dispatcher.utter_message(response)
        except Exception as e:
            dispatcher.utter_message("Sorry we are down for the moment : "+str(e))
        return [SlotSet('diagram_item', "")]
```
How do I fix the relative path issue in the new 0.11.x rasa_core. I was using rasa_core==0.10.4 and this issue wasn't a problem as the actions.py ran in that local folder. I know this isn't really a rasa core issue but I am a student so still new to programming. I don't feel Giving the full file path is a good solution. Any ideas would be appreciated. Thanks!

P.S. I think its better to _give the option_ of running actions as endpoints rather than making it mandatory. Making it independent is good (as separate services) but for small bots these are not required.

Also, I have made separate actions files. Example: for accessing json files I used a separate actions.py file and for checking the weather I used weather.py file. Do I have to run both the files as two different endpoints(services) or is there a way to access them both with just one endpoint? I know I can join them as one file, I am just curious that's all!

**Comment by Saurbh060** [comment]
HI @stalinsabu 
I have a pincode file and want to make action in action.py that read from pincode.txt file and search user's input pincode and utter actions according to pincode found or not.

**Comment by stalinsabu** [comment]
@Saurbh060 
Hi! Sorry about the late reply I have been away for quite some time.
You will have to train it in a way it recognizes pincode as an entity so you can take that  using tacker.get_slot(), pass it into your action logic and search for the pincode in your file. You might have to use regex to recognize the pincode. One lazy way for doing this would be to recognize the intent and take the user sent message using (tracker.latest_message)['text'] and applying regex to recognize and find your pincode. This way you only need to train its intent that user is sending a pincode and you dont need to train it to understand the entity pincode. This is one approach but perhaps not the best way but it is definitely easier to train
