### ISSUE TITLE
Rasa installation error

### ISSUE THREAD

**Issue by jahirfiquitiva** [RasaHQ/rasa_nlu#2684]
**Rasa Core version**: Latest

**Python version**: 3.7

**Operating system** (windows, osx, ...): MacOS Mojave

**Issue**:
I am trying to install `rasa_core` but I get this error:
```bash
Collecting tensorflow==1.10.0 (from rasa_core->-r requirements.txt (line 10))
  Could not find a version that satisfies the requirement tensorflow==1.10.0 (from rasa_core->-r requirements.txt (line 10)) (from versions: )
No matching distribution found for tensorflow==1.10.0 (from rasa_core->-r requirements.txt (line 10))
```
😕 

Can you please tell me what to do?

**Comment by 913165** [comment]
I have created rasa installation videos using ubuntu,windows and docker at
 https://www.youtube.com/watch?v=SKt8hO89X-I&list=PL3rAaHySgv9AvVXGwBCDww8jCoqQDmvkq
