### ISSUE TITLE
    from rasa_core.utils import EndpointConfig ImportError: cannot import name 'EndpointConfig'

### ISSUE THREAD

**Issue by praveenkumart** [RasaHQ/rasa_nlu#2695]
**Rasa Core version**:
0.8.2
**Python version**: 
3
**Operating system** (windows, osx, ...):
   ubuntu
**Issue**:

    from rasa_core.utils import EndpointConfig
 ImportError: cannot import name 'EndpointConfig'

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by iamrajatroy** [comment]
ImportError: cannot import name 'EndpointConfig' from 'rasa_core.utils'. I am getting same kind of error. I am using Rasa 1.1.3. Can anyone tell me which package to use for EndpointConfig?

**Comment by erohmensing** [comment]
@iamrajatroy if you are using `rasa`, you should not be importing anything from `rasa_core`, you should be importing from `rasa.core`.
