### ISSUE TITLE
Event Subscription with slack api, 404 not found error

### ISSUE THREAD

**Issue by stevenshichn** [RasaHQ/rasa_nlu#2703]
**Rasa Core version**: 0.11.1

**Python version**: 3.6

**Operating system** (windows, osx, ...):windows 10

**Issue**:
I am trying to use slackclient with rasa_core.agent. When I defined the request url in enable event section of slack api portal, everytime I received 404 not found error.

**run below code to start the server and enable communication with slack and rasa_core**
--start of code
```python
from rasa_core.channels.slack import SlackBot, SlackInput
from rasa_core.channels import InputChannel
from rasa_core.agent import Agent
from rasa_core.interpreter import RasaNLUInterpreter
from slackclient import SlackClient

nlu_interpreter = RasaNLUInterpreter('./models/nlu/default/chat')
agent = Agent.load('./models/dialogue', interpreter = nlu_interpreter)

token = 'MY_TOKEN'
sc = SlackClient(token)


def on_new_message(user_msg):
    print("received message " + user_msg)
 
channels = []
 
slackInput = SlackInput(token, slack_channel='botservice')
slackInput.blueprint(on_new_message)
channels.append(slackInput)
agent.handle_channels(channels, serve_forever = True)
```
--end of code

**change request url in slack API portal**, request url: https://myservername_ngrok/webhook
I got "Your URL didn't respond with the value of the challenge parameter." error in the portal. And from python console, I received **404 not found error**

Can someone give me some ideas to fix it? Do I need to execute the rasa_core.run.py first?

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by PrithviRakshak** [comment]
am facing a similar issue when I try to link my rasa bot to slack. I followed all steps and here am attaching the screenshots of error am getting.
![Screenshot (6)](https://user-images.githubusercontent.com/50570830/59336390-1a382a80-8d1c-11e9-9349-5f3e0627b861.png)
![Screenshot (5)](https://user-images.githubusercontent.com/50570830/59336411-20c6a200-8d1c-11e9-8616-5a1b311c8a00.png)
First  I got bad gateway error when I tried changing ports now am getting this error not found. Am new and this is the first time I've actually made something using python. So please forgive if my problem is very basic

**Comment by Dark-Coder-018** [comment]
first you should run python script  in which you have specified the slack Access token and port number of ngrok for eg: 5004,
and try to add Request URL in Event Subscription on slack.
then you won't get "502 Bad Gateway"
