### ISSUE TITLE
Custom Action : The model predicted the custom action 'action_weather' but you didn't configure an endpoint to run this custom action

### ISSUE THREAD

**Issue by praveenkumart** [RasaHQ/rasa_nlu#2708]
**Rasa Core version**:
rasa-core                0.11.12   
rasa-core-sdk            0.11.5    
rasa-nlu                 0.13.7  
**Python version**: 
3
**Operating system** (windows, osx, ...):
Ubuntu
**Issue**:
Problem with custom action .
The model predicted the custom action 'action_weather' but you didn't configure an endpoint to run this custom action. Please take a look at the docs and set an endpoint configuration. https://rasa.com/docs/core/customactions/

**Content of domain file** (if used & relevant):
slots:
  price:
    type: text

intents:
  - greet
  - goodbye
  - send_cash

entities:
  - price

templates:
  utter_greet:
    - 'Hello, How can i help'
  utter_goodbye:
    - 'Bye , c u later'
    - 'Bye bye' 

actions:

  - utter_greet
  - utter_goodbye
  - action_weather
  

```yaml
action_endpoint:
  url: "http://localhost:5055/webhook"
```

Commands used:

For training : 
python3 -m rasa_core.train -d weather_domain.yml -s story/stories.md -o models/dialogue -u models/default/model_20181108-102255/ --endpoints endpoints.yml
For run :

python3 -m rasa_core.run  -d models/dialogue -u models/default/model_20181108-102255/

**Comment by LearningCurveSL** [comment]
> Please pass the `--endpoints endpoints.yml` flag to the `rasa_core.run` command and it should work

Can you please put the code?

**Comment by venkattejaRaavi** [comment]
this is the worst response I have ever seen.
