### ISSUE TITLE
train_online.py error  attribute or import error

### ISSUE THREAD

**Issue by ztavlas** [RasaHQ/rasa_nlu#2711]
**Rasa Core version**: 0.11.1

**Python version**: 3.6.7

**Operating system** (windows, osx, ...): Windows

**Issue**: when i use, train_online.py like this :
from rasa_core.training import online

agent.train(data,
                       batch_size=50,
                       epochs=200,
                       max_training_samples=300)				   
    online.run_online_learning(agent)

i am getting : 
    online.run_online_learning(agent)
AttributeError: module 'rasa_core.training.online' has no attribute 'run_online_learning'

and when i use 

from rasa_core.interactive import interactive

agent.train(data,
                       batch_size=50,
                       epochs=200,
                       max_training_samples=300)			
interactive.run_interactive_learning(agent)

i am getting : 
    from rasa_core.interactive import interactive
ModuleNotFoundError: No module named 'rasa_core.interactive'

which one is correct and how can i solve my problem ?

Thanks.

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by anilpankaj** [comment]
> it's `rasa_core.training.interactive` i believe

i got same error 
Traceback (most recent call last):
  File "train_online.py", line 8, in <module>
    from rasa_core.training.interactive import interactive
ModuleNotFoundError: No module named 'rasa_core.training.interactive'
