### ISSUE TITLE
No module named 'rasa_core'

### ISSUE THREAD

**Issue by Olesiatsa** [RasaHQ/rasa_nlu#2714]
**Rasa Core version**:0.11.12

**Python version**: 3.6.3

**Operating system** (windows, osx, ...):MacOS

**Issue**:

I'm trying to run python train_online.py. And I get the following Error : 
"  File "train_online.py", line 8, in <module>
    from rasa_core.agent import Agent
ModuleNotFoundError: No module named 'rasa_core'"

Installation from rasa_core was successfully. When I type in "show rasa_core" I get the response:
"Name: rasa-core
Version: 0.11.12
Summary: Machine learning based dialogue engine for conversational software.
Home-page: https://rasa.com
Author: Rasa Technologies GmbH
Author-email: hi@rasa.com
License: Apache 2.0
Location: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages
Requires: slackclient, numpy, scikit-learn, flask-cors, redis, rasa-core-sdk, pytz, python-socketio, terminaltables, six, gevent, pykwalify, apscheduler, mattermostwrapper, rasa-nlu, tqdm, pymongo, twilio, python-telegram-bot, fbmessenger, jsonschema, coloredlogs, pyyaml, flask-jwt-simple, h5py, graphviz, colorclass, keras, pika, ConfigArgParse, python-dateutil, flask, packaging, jsonpickle, requests, rocketchat-API, typing, colorhash, ruamel.yaml, tensorflow, PyInquirer, networkx, future, fakeredis
"

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by guneet999** [comment]
### ### while installing rasa_core using pip install rasa_core getting the error.

ERROR: tensorflow-cpu 1.15.0 has requirement tensorboard<1.16.0,>=1.15.0, but you'll have tensorboard 1.13.1 which is incompatible.
ERROR: rasa 1.7.4 has requirement cloudpickle~=1.2.0, but you'll have cloudpickle 0.6.1 which is incompatible.
ERROR: rasa 1.7.4 has requirement fbmessenger~=6.0, but you'll have fbmessenger 5.6.0 which is incompatible.
ERROR: rasa 1.7.4 has requirement jsonschema~=3.0, but you'll have jsonschema 2.6.0 which is incompatible.
ERROR: rasa 1.7.4 has requirement matplotlib~=3.0, but you'll have matplotlib 2.2.5 which is incompatible.
ERROR: rasa 1.7.4 has requirement packaging~=19.0, but you'll have packaging 18.0 which is incompatible.
ERROR: rasa 1.7.4 has requirement pika~=1.0.0, but you'll have pika 0.12.0 which is incompatible.
ERROR: rasa 1.7.4 has requirement python-socketio>=4.3.1, but you'll have python-socketio 3.1.2 which is incompatible.
ERROR: rasa 1.7.4 has requirement pytz~=2019.1, but you'll have pytz 2018.9 which is incompatible.
ERROR: rasa 1.7.4 has requirement redis~=3.3.5, but you'll have redis 2.10.6 which is incompatible.
ERROR: rasa-sdk 1.7.0 has requirement ConfigArgParse>=0.14, but you'll have configargparse 0.13.0 which is incompatible.

**Comment by shambhaviparashar** [comment]
@guneet999 i think pip installs the correct requirements after showing these errors itself
