### ISSUE TITLE
train_online.py error attribute or import error

### ISSUE THREAD

**Issue by ztavlas** [RasaHQ/rasa_nlu#2717]
**Rasa Core version**:0.11.12

**Python version**: 3.6.7

**Operating system** (windows, osx, ...): Windows

**Issue**: train_online.py error attribute or import error

 when i use, train_online.py like this :
from rasa_core.training import online

agent.train(data,
batch_size=50,
epochs=200,
max_training_samples=300)
online.run_online_learning(agent)

i am getting :
online.run_online_learning(agent)
AttributeError: module 'rasa_core.training.online' has no attribute 'run_online_learning'

and when i use

from rasa_core.interactive import interactive

agent.train(data,
batch_size=50,
epochs=200,
max_training_samples=300)
interactive.run_interactive_learning(agent)

i am getting :
from rasa_core.interactive import interactive
ModuleNotFoundError: No module named 'rasa_core.interactive'

which one is correct and how can i solve my problem ?

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by anilpankaj** [comment]
> Hi @ztavlas,
> 
> We deprecated the term "online training" for "interactive", so the second method is correct. However, you need import in this fashion instead:
> 
> `from rasa_core.training import interactive`
> 
> Let me know if this solves your problem

i got same error after use it
Traceback (most recent call last):
  File "train_online.py", line 8, in <module>
    from rasa_core.training import interactive
ImportError: cannot import name 'interactive'

**Comment by Yattus** [comment]
hope it help:
**remove**  
```
from rasa_core.training import online
online.serve_agent(agent)
```
**Replace by this** 
```
from rasa_core.training import interactive
interactive.run_interactive_learning(agent)
```
