### ISSUE TITLE
RASA NLU predicting wrong intents

### ISSUE THREAD

**Issue by vinayver198** [RasaHQ/rasa_nlu#2736]
**Rasa Core version**:0.9.7

**Python version**:0.12

**Operating system** (windows, osx, ...):windows

**Issue**:Wrong intent prediction
Hi,

I am building a FAQ bot with small talk.
I have got 524 FAQ intent with 3 examples each.
I am using tensorflow embedding pipeline.
Can you help in this issue. 
Any pipeline suggestions will be helpful.
Also my stories is something like this

#story 1
* Greet
- utter_greet
#story 2
*Goodbye
- utter_goodbye
#story 3
* Q1 or Q2 or ......or Q 524
- action_say_faq

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by rachitbshephertz** [comment]
@vinayver198 Did you got this working?
