### ISSUE TITLE
Error while finding module specification for 'rasa_nlu.train' - ModuleNotFoundErrorL No module named 'rasa_nlu'

### ISSUE THREAD

**Issue by Manoj-t** [RasaHQ/rasa_nlu#2754]
**Rasa Core version**:

**Python version**:  3.7.1

**Operating system** (windows, osx, ...): Mac OS Mojave 10.14

**Issue**: Error while training the data.

I am trying to execute this command:
**python -m rasa_nlu.train -c nlu_config.yml --data nlu.md -o models --fixed_model_name nlu --project current --verbose**

**Content of nlu_config.yml**
“language” : “en”
“pipeline”: “tensorflow_embedding”

**Content of nlu.md**

## intent:greet
- hey
- hello
- hi
- good morning
- good evening
- hey there

## intent:restaurant_search
- i'm looking for a place to eat
- I want to grab lunch
- I am searching for a dinner spot
- i'm looking for a place in the [north](location) of town
- show me [chinese](cuisine) restaurants
- show me a [mexican](cuisine) place in the [centre](location)
- i am looking for an [indian](cuisine) spot
- search for restaurants
- anywhere in the [west](location)
- anywhere near [18328](location)
- I am looking for [asian fusion](cuisine) food
- I am looking a restaurant in [29432](location)

## intent:thankyou
- thanks!
- thank you
- thx
- thanks very much

Can someone help me out in solving this issue. Thanks in Advance.

**Comment by vinayak99999** [comment]
@Manoj-t  I am facing the same issue, please let me know how did you resolved it.

**Comment by anurag53** [comment]
Hi, I am also facing the same issue while training the rasa nlu using docker. Please help me to resolve this issue.

**Comment by ogq848** [comment]
I am having the same problem.  I installed nlu fine at my root directory last week.  I'm trying to follow the starter lab and it's telling me rasa-nlu is not found.

**Comment by NikkiJain09** [comment]
Having the same issue with 'python3 -m rasa_nlu.server'. Getting 'No module named rasa_nlu' error.
OS: Mojave
Python version: 3.7.3

**Comment by NikkiJain09** [comment]
Try pip install rasa_nlu
