### ISSUE TITLE
new slot type: struct or dict slot type for complex slots (Contribution)

### ISSUE THREAD

**Issue by jmrf** [RasaHQ/rasa_nlu#2762]
Some entities or in general extracted information from utterances might require structure, think of a time range as a simple case, but any heriarchical structure as the general case.
Such an entity might be represented by a JSON object or similarly a python dictionary. For example: 
`
"time": {"value": {"from": ...., "to": ....}}
`  

If we want to preserve such a structure as `slots` we would need a new type of slot. 
In addition the domain could define what fields of an entity like that should be kept, featurized and used.

I am happy to submit a PR to extend the current slot types and domain logic around it if anyone else is interested in this extension.

**Comment by akelad** [comment]
i think this is a very custom use case, so we'll stick to the existing method of creating your own custom slot type :)
