### ISSUE TITLE
Detailed and More tutorials

### ISSUE THREAD

**Issue by imraansarwar** [RasaHQ/rasa_nlu#278]
**rasa NLU version** (e.g. `0.7.3`):

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...):

**Operating system** (Linux):

**Recommendation/Suggestion**:
Hi, First of all thank you for developing such a useful product. Your efforts are much appreciated.

However I feel that for any product to lift-off and be in the main stream, its documentation plays a vital role. It would be very helpful if you include couple of more tutorials (step by step) in using rasa_nlu tackling different scenarios. My experience so far is that a good product may fail to get mainstream due to lack of resources.

Currently there's not much if you search for rasa_nlu on stackoverflow.com, or elsewhere on search engines, I couldn't find a single tutorial and/or documentation/forums except here on github.

Thanks & regards,
Imran

**Content of configuration file** (if used & relevant):
```json

```

**Comment by amn41** [comment]
Yes! totally agree. But please also see this an an invitation to contribute to the documentation and /or write blog posts / tutorials :)

**Comment by imraansarwar** [comment]
@amn41 
I wish if I could contribute, but this is the first time I'm trying it. 

I think there should be a guide(s) explaining the **project folder structure, the architecture and some tuning parameters** (if applicable) . Some information on the best practices to avoid common errors would be helpful too.

P.S. I'm from java world :) and this is the first time I'm getting my hands on Python, of-course rasa is driving me into this :dango:

**Comment by twerkmeister** [comment]
Hey @imraansarwar, thank you for bringing this up. Have you had a look at http://rasa-nlu.readthedocs.io/en/stable/tutorial.html ? Could you point out a few places where you loose track in the tutorial?

**Comment by tmbo** [comment]
Let's collect some ideas about possible tutorials. I'll keep this updated :
- [ ] How to setup rasa NLU using docker
- [ ] Tuning parameters and evaluating a trained pipeline / model

**Comment by wrathagom** [comment]
I believe this is fixed with the Community section, hopefully, it keeps growing!
