### ISSUE TITLE
Cannot load models in windows

### ISSUE THREAD

**Issue by thilakrajrk** [RasaHQ/rasa_nlu#281]
I'm using rasa NLU v0.7.4 and mitie v0.2.0 in windows.
I can able to train a model with the backend as "mitie_sklearn".

I'm getting the below error while loading the created model using the MITIESklearnInterpreter.

```
Traceback (most recent call last):
  File "test.py", line 38, in <module>
    interpreter = MITIESklearnInterpreter.load(metadata)
  File "C:\ProgramData\Anaconda2\lib\site-packages\rasa_nlu\interpreters\mitie_sklearn_interpreter.py", line 20, in load
    extractor = named_entity_extractor(meta.entity_extractor_path)
  File "C:\ProgramData\Anaconda2\lib\site-packages\mitie\mitie.py", line 234, in __init__
    raise Exception("Unable to load named entity extractor from " + filename)
Exception: Unable to load named entity extractor from D:\NLU\models\model_20170413-132623\entity_extractor.dat

```
I have tried the same in linux and the model is loading perfectly. i found a similar issue #185 but i have loaded the total_word_feature_extractor.dat file perfectly, still getting the same error. 

The code I have used:

```
metadata = Metadata.load(model_directory)
interpreter = MITIESklearnInterpreter.load(metadata)
print interpreter.parse(u'Text')
```

**Comment by tmbo** [comment]
Did you install the latest mitie version? 

Do you mind testing if this error still persists on the latest master? (You need to install from github, instructions are in the readme. Also make sure to adapt your configuration to the new format of the latest version (https://rasa-nlu.readthedocs.io/en/latest/changelog.html))

**Comment by thilakrajrk** [comment]
I'm using the latest version of mitie that is 0.2.0
yes the file is present and using that file only i have generated the model file.
I'm using python, so i believe there is no need for the conf.json file.
Let me check with the new version and share you the results.

**Comment by tmbo** [comment]
Thanks, let me know if the error persists there.

**Comment by thilakrajrk** [comment]
Tom, I can't able to find the trainers and interpreters folder inside the rasa_nlu folder in the master. `interpreter = MITIESklearnInterpreter.load(metadata)`. `MITIESklearnInterpreter` should be there inside interpreters folder. I can't find any alternatives in the Changelog also.

**Comment by tmbo** [comment]
Please have a look at https://rasa-nlu.readthedocs.io/en/latest/python.html

**Comment by thilakrajrk** [comment]
Sorry i think this changes has not been mentioned in the Changelog, Tom i have checked with the latest version which is there on the GIT and i'm getting the same error.
While training i got the below warning ```
C:\ProgramData\Anaconda2\lib\site-packages\sklearn\metrics\classification.py:1113: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
```
and while loading the model i got the below error which is the same that i got from v0.7.4(only in windows):
```
Traceback (most recent call last):
  File "test.py", line 22, in <module>
    interpreter = Interpreter.load(metadata, RasaNLUConfig("config.json"))
  File "build\bdist.win-amd64\egg\rasa_nlu\model.py", line 245, in load
    component = component_builder.load_component(component_name, context, model_config, meta)
  File "build\bdist.win-amd64\egg\rasa_nlu\components.py", line 234, in load_component
    component = registry.load_component_by_name(component_name, context, model_config)
  File "build\bdist.win-amd64\egg\rasa_nlu\registry.py", line 89, in load_component_by_name
    return load_component(component_clz, context, config)
  File "build\bdist.win-amd64\egg\rasa_nlu\components.py", line 27, in load_component
    return component_clz.load(*load_args)
  File "build\bdist.win-amd64\egg\rasa_nlu\extractors\mitie_entity_extractor.py", line 112, in load
  File "C:\ProgramData\Anaconda2\lib\site-packages\mitie\mitie.py", line 234, in __init__
    raise Exception("Unable to load named entity extractor from " + filename)
Exception: Unable to load named entity extractor from D:\models\model_20170421-133630\entity_extractor.dat
```

**Comment by thilakrajrk** [comment]
Tom, I'm waiting for your answer in this issue. Can i get some updates for this issue?

**Comment by tmbo** [comment]
Sorry, but I couldn't reproduce this issue yet. We are looking into setting up a windows CI to test more properly for windows. Actually, there shouldn't be any issues since we aren't doing anything platform specific, but then again...

In the meantime you could speed up things by debugging this issue, setting a breakpoint at the location and having a look why the file is not found.

**Comment by tmbo** [comment]
I'll close this issue due to inactivity and due to the fact that the issue can not be reproduced at the moment.
