### ISSUE TITLE
RASA | Slots | How to reset Slots in between the conversation?

### ISSUE THREAD

**Issue by EliBruce** [RasaHQ/rasa_nlu#2854]
**Rasa Core version**:0.12.1

**Python version**: 3.6.5

**Operating system** (windows, osx, ...):Win7

**Issue**:I have created a weather bot. Here first time the location(Chico) assign to the stot properly and the result showing as expected.

As per the story the bot will ask to the user for the weather continuously.
So in same conversation, I asked the weather for another place(Irish Town), but the result is showing with previous Slot value (Chico). Please see the attached image to get more details about the issue.

Also please find the attached stories and Domain…

here my question is, how can I reset the slot value in between the conversation?

Thanks in Advance, EB

![slot issue](https://user-images.githubusercontent.com/46138200/50426392-b7102400-08b2-11e9-8ff9-361a9dcd3935.png)

[bot_stories.txt](https://github.com/RasaHQ/rasa_core/files/2709024/bot_stories.txt)

[weather_domain.txt](https://github.com/RasaHQ/rasa_core/files/2709026/weather_domain.txt)

**Comment by Nishetvyas** [comment]
@MetcalfeTom  your code work Properly, Thank you so much for give this solution.Its Work great.

**Comment by mangopickle** [comment]
Hi @MetcalfeTom 

I tried your solution, but my code doesn't run because it doesn't recognize SlotSet. Any suggestions?

**Comment by NavdhaJindal** [comment]
Hi @EliBruce 

I found a simple solution for this. At the end of your stories, simply include the following

- action_restart

This is a default action provided by Rasa that resets all the slots and restarts the conversation.

**Comment by gmeisinger** [comment]
@NavdhaJindal did you import SlotSet?

```
from rasa_sdk.events import SlotSet
```

**Comment by gaurav21s** [comment]
> class ResetSlot(Action):
> 
>     def name(self):
>         return "action_reset_slot"
> 
>     def run(self, dispatcher, tracker, domain):
>         return [SlotSet("Location", None)]

Hey I have used these but I am getting the below errors:
 Task exception was never retrieved
future: <Task finished coro=<configure_app.<locals>.run_cmdline_io() done.
Encountered an exception while running action 'action_reset_slot'.Bot will continue, but the actio
ns events are lost. Please check the logs of your action server for more information.
