### ISSUE TITLE
How to enable https on rasa core server

### ISSUE THREAD

**Issue by Akshit99** [RasaHQ/rasa_nlu#2858]
**Rasa Core version**:
0.12.3
**Python version**: 
3.6.7
**Operating system** (windows, osx, ...):
windows 7 64 bit

**Issue**:

Hey guys! So my bot is running on AWS and i’m getting the reply in my browser. But it’s a “http” i.e. it’s not secure port. I need secure port to run with my web app. Whenever I enable the SSL on port 5005 and try to run the bot it gives error and says,

File “/home/ubuntu/.local/lib/python3.6/site-packages/gevent/server.py”, line 256,│

in _tcp_listener │ sock.bind(address) │

OSError: [Errno 98] Address already in use: (‘0.0.0.0’, 5005)

Now when I disable my SSL and run the bot, It runs easily and replies on http call. So how can I convert this http to https? Any help is appreciated.

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by Manthan1394** [comment]
Hi @bikashkumars 

I got error in these line and i am stucked here, Can you help me out in this.

 " **RedirectPermanent /rasa**"

Regards 
Manthan Tanna
