### ISSUE TITLE
FormAction: Slots are not filled when named other than entity name

### ISSUE THREAD

**Issue by satishavhad** [RasaHQ/rasa_nlu#2873]
**Rasa Core version**: 0.12.3
**Rasa NLU version**: 0.13.8
**Rasa Core SDK version**: 0.12.1
**Python version**: 3.6.7
**Operating system** windows

**Issue**: Slot mapping only works if the entity name matches the slot name.
But there are many use cases where same entity is used for filling different Slots depending on the intent. How should I resolve this problem?

Below s the relevant code:

Action.py
        return {"ENT_Security_Name": [self.from_entity(entity="ENT_Security_Name",
											intent="INT_API_BuySecurity"),
								  self.from_entity(entity="ENT_Security_Name",
											intent="enter_data")],
				"SLOT_ENT_Order_Quantity": [self.from_entity(entity="ENT_Number",
											intent="INT_API_BuySecurity"),
						   self.from_entity(entity="ENT_Number",
											intent="enter_data")],

**Comment by NomanSaleem4** [comment]
any solutions on it?
