### ISSUE TITLE
Switch between Projects in Rasa core as we do in rasa nlu.

### ISSUE THREAD

**Issue by azizullah2017** [RasaHQ/rasa_nlu#2874]
Is this possible to switch between project on same port ?? 
I have already asked my questions in forum, but I did not get reply up till now.

Is there any parameter to pass the project name while requesting ?
```
curl -X POST http://localhost:5002/webhooks/rest/webhook   -d '{"sender": "aziz", "message": "hi"}'   -H "Content-type: application/json"
```

````
python -m rasa_nlu.server -c nlu.yml --path models/nlu --port 5003

we can use any of these.

1-http://localhost:5003/parse?q=hi&project=resturant
2- http://localhost:5003/parse?q=hi&project=hotel
```

**Comment by akelad** [comment]
@azizullah2017 i'll close this issue because it's not something we're planning on doing at the moment
