### ISSUE TITLE
Rasa Core instance. Either retrain the model, or run withan older version. Model version: 0.12.3 Instance version: 0.13.0a5 Minimal compatible version: 0.13.0a2

### ISSUE THREAD

**Issue by milangm89** [RasaHQ/rasa_nlu#2875]
**Rasa Core version**: 0.11.11

**Python version**: 3.4

**Operating system** (windows, osx, ...): ubuntu 14.04

**Issue**: getting the below error during docker compose up

+++
rasa_core_1      | rasa_core.exceptions.UnsupportedDialogueModelError: The model version is to old to be loaded by this Rasa Core instance. Either retrain the model, or run withan older version. Model version: 0.12.3 Instance version: 0.13.0a5 Minimal compatible version: 0.13.0a2
starterpackrasastack_rasa_core_1 exited with code 1
+++

**Content of domain file** (if used & relevant):
```actions:
- utter_name
- utter_thanks
- utter_greet
- utter_goodbye
- action_joke
config:
  store_entities_as_slots: true
entities:
- name
forms: []
intents:
- deny:
    use_entities: true
- thanks:
    use_entities: true
- goodbye:
    use_entities: true
- joke:
    use_entities: true
- greet:
    use_entities: true
- name:
    use_entities: true
slots:
  name:
    auto_fill: true
    initial_value: null
    type: rasa_core.slots.TextSlot
templates:
  utter_goodbye:
  - text: Talk to you later!
  utter_greet:
  - text: Nice to you meet you {name}. How can I help?
  utter_name:
  - text: Hey there! Tell me your name.
  utter_thanks:
  - text: My pleasure.
```

**Comment by anilpankaj** [comment]
Traceback (most recent call last):
  File "run.py", line 7, in <module>
    interpreter = NaturalLanguageInterpreter.create('/home/anil/Documents/slackbot/models/dialogue')
  File "/home/anil/.local/lib/python3.6/site-packages/rasa_core/interpreter.py", line 34, in create
    return RasaNLUInterpreter(model_directory=obj)
  File "/home/anil/.local/lib/python3.6/site-packages/rasa_core/interpreter.py", line 234, in __init__
    self._load_interpreter()
  File "/home/anil/.local/lib/python3.6/site-packages/rasa_core/interpreter.py", line 257, in _load_interpreter
    self.interpreter = Interpreter.load(self.model_directory)
  File "/home/anil/.local/lib/python3.6/site-packages/rasa_nlu/model.py", line 290, in load
    Interpreter.ensure_model_compatibility(model_metadata)
  File "/home/anil/.local/lib/python3.6/site-packages/rasa_nlu/model.py", line 273, in ensure_model_compatibility
    "".format(model_version, rasa_nlu.__version__))
rasa_nlu.model.UnsupportedModelError: The model version is to old to be loaded by this Rasa NLU instance. Either retrain the model, or run withan older version. Model version: 0.0.0 Instance version: 0.14.6
i don't understand why my model version 0.0.0 showing.
i am stuck on that problem what can i do please  somebody help me.
