### ISSUE TITLE
Add 'is typing' feature and message delay to connectors

### ISSUE THREAD

**Issue by MatheusMiranda** [RasaHQ/rasa_nlu#2877]
**Rasa Core version**: 0.11.12

**Python version**:  3.6

**Operating system** (windows, osx, ...): Docker image `python 3.6`, with Linux Kernel.

**Issue**: 

While having a conversation with bots, it's important to have a  time delay between messages, especially for big messages, to make bot answers more natural for the user. 

This issue is to develop a way to set or estimate  time delay proportional to messages size, and to show 'bot is typing' indicator on the channels, using Rasa Core connectors.

As mentioned in the comment: https://github.com/RasaHQ/rasa_core/pull/462#issuecomment-416900009, it would be nice to develop a generic solution that could be used by all connectors that support this feature. 

what would be a good approach to implement this?

**Comment by akelad** [comment]
i'm going to close this as we're refactoring how input/output channels work
