### ISSUE TITLE
Problem of getting responses simultaneously 

### ISSUE THREAD

**Issue by vigneshp826** [RasaHQ/rasa_nlu#2881]
**Rasa Core version**: 0.11.8

**Python version**:  3.5.5

**Operating system** (windows, osx, ...): osx

**Issue**:
I have a custom action which takes almost two minutes to process the request. So to keep the user informed about the starting of back-end process first am sending the notification using dispatcher_utter_message("processing"), then processing request ( fetching big file from a DB ), then dispatcher_utter_message("completed") . 

But my slack channel  receives both of the utter_message response's simultaneously after 2 minutes instead of sending my first utter_message to channel immediately once the request comes, why?

**Expected Result:**

USER: Health check for ABC application
BOT: Health check in progress for ABC, wait for 2 minutes.
After 2 minutes or once the result is ready
BOT: Completed.

**Content of action file** :
```
class ActionHealthcheck(Action):
    def name(self):
        return 'action_healthcheck'
    
    def run(self, dispatcher, tracker, domain):
        appname = tracker.get_slot('application_name')
        response = "Health check in progress for  {},might take upto 2 mins".format(appname)
        
        dispatcher.utter_message(response)
        # result will be available after 2 minutes  
        ''' This section contains code which connects to a db and fetches the result and dispatcher.utter_attachement(result)'''
          
        dispatcher.utter_message("completed")
        return [SlotSet('application_name',appname)]        
```

**Comment by bamba518** [comment]
I don't understand the solution @Ghostvv,  not sure the meaning of this " As a solution, I recommend for the first utterance create utterance template in domain.yml and put it in the stories before your action,"

**Comment by Ghostvv** [comment]
treat the first utterance as a different `utter`-action
