### ISSUE TITLE
I need help in creating custom actions in rasa core and starting the server

### ISSUE THREAD

**Issue by Manoj-t** [RasaHQ/rasa_nlu#2891]
**Rasa Core version**: 0.12.2

**Python version**:  3.6.4

**Operating system** (windows, osx, ...): MacOS mojave 

**Issue**: need help in creating custom actions in rasa core. I am actually building a weather enquiry chatbot. I want to add a custom action that calls a **weather-api** and sends back a response to the rasa core server. As per the documentation, I created **endpoints.yml** file. I didn't understand what should I include in it. my custom action name is **action_get_weather**. I included this action in the list of actions in **domain.yml** file. can someone help me in this i.e. what to include in endpoints.yml file, when to start the server.
 

Content of **nlu.md**
## intent:greeting
- hey
- hello
- hi
- heya

## intent:how_are_you
- how are you
- how is it going
- how is life

## intent:bye
- bye
- good bye

## intent:my_name_is
- I am [Martin](PERSON)
- I am [Jack](PERSON)
- I'm [Steven](PERSON)
- im [Jack](PERSON)
- My name is [Martin Novak](PERSON)

## intent:get_weather
- what's the weather
- what's the weather in [Czech Republic](GPE)
- what is the weather
- what is the weather in [New Zealand](GPE)
- whats the weather

## synonym:Prague
- Czech Republic
- Czechia
- CR
- CZ

## synonym:Auckland
- New Zealand
- NZ
- Zealand

Contents of **domain.yml** file
slots:
  PERSON:
    type: text
  GPE:
    type: text

intents:
  - greeting
  - how_are_you
  - bye
  - my_name_is
  - get_weather

actions:
- utter_greeting
- utter_how_i_am
- utter_bye
- utter_its_nice_to_meet_you
- action_get_weather

templates:
  utter_greeting:
  - text: "Hi!"
  - text: "Hello, my friend."
  
  utter_how_i_am:
  - text: "I am doing ok."
  - text: "I am good."

  utter_bye:
  - text: "Bye."
  - text: "Good bye."
  
  utter_its_nice_to_meet_you:
  - text: "It's nice to meet you, {PERSON}."
  - text: "Nice to meet you, {PERSON}."

contents of **nlu_config.yml** file

language: en
pipeline: tensorflow_embedding

contents of **stories.md** file
## greeting
* greeting
- utter_greeting

## how are you
* how_are_you
- utter_how_i_am

## good bye
* bye
- utter_bye

## my name is
* my_name_is
- utter_its_nice_to_meet_you

## get weather
* get_weather
- action_get_weather

contents of my **action file (weather.py file)**

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

from rasa_core.actions.action import Action

# https://pypi.org/project/weather-api/
from weather import Weather,Unit

class ActionGetWeather(Action):
    def name(self):
        return 'action_get_weather'
    
    def run(self, dispatcher, tracker, domain):
        weather = Weather(unit=Unit.CELSIUS)
        gpe = ('Auckland', tracker.get_slot('GPE'))[bool(tracker.get_slot('GPE'))]
        result = weather.lookup_by_location(gpe)
        if result:
            condition = result.condition
            city = result.location.city
            country = result.location.country
            dispatcher.utter_message('It\'s ' + condition.text + ' and ' + condition.temp + '°C in ' +
                                     city + ', ' + country + '.')
        else:
            dispatcher.utter_message('We did not find any weather information for ' + gpe + '. Search by a city name.')

content in **endpoint.yml** file

action_endpoint:
- weather.ActionGetWeather

please help me in this. Thanks

**Comment by Saurbh060** [comment]
> Please ask these kind of questions in our [forum](https://forum.rasa.com)
Can you provide link of this issue on forum
