### ISSUE TITLE
ModuleNotFoundError: No module named 'actions.actions' when trying to run an action server in a docker container

### ISSUE THREAD

**Issue by leonore** [RasaHQ/rasa_nlu#2938]
**Rasa Core version**:  0.12.4

**Python version**: 3.6.4

**Operating system** (windows, osx, ...): macOS 10.14.2

**Issue**: Hi, I'm trying to create a docker image that runs the rasa-core action server.
My docker-compose.yml:
```
version: '3'

services:
  action_server:
    image: rasa/rasa_core_sdk:latest
    volumes:
      - ./chat-interface:/app/actions
    ports:
      - "5055:5055"
```
Running `docker-compose up` does get the action server up and running:
```INFO:__main__:Action endpoint is up and running. on ('0.0.0.0', 5055)```
But I get the following error beforehand:

```
action_server_1  | INFO:__main__:Starting action endpoint server...
action_server_1  | ERROR:rasa_core_sdk.executor:Failed to register package 'actions.actions'.
action_server_1  | Traceback (most recent call last):
action_server_1  |   File "/app/rasa_core_sdk/executor.py", line 144, in register_package
action_server_1  |     self._import_submodules(package)
action_server_1  |   File "/app/rasa_core_sdk/executor.py", line 131, in _import_submodules
action_server_1  |     package = importlib.import_module(package)
action_server_1  |   File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
action_server_1  |     return _bootstrap._gcd_import(name[level:], package, level)
action_server_1  |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
action_server_1  |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
action_server_1  |   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
action_server_1  | ModuleNotFoundError: No module named 'actions.actions'
action_server_1  | INFO:__main__:Action endpoint is up and running. on ('0.0.0.0', 5055)
```
I couldn't figure out what was going wrong so I followed this: https://github.com/RasaHQ/rasa_core/issues/1459#issuecomment-447323161 in another directory, which worked fine 

I tried copying the file structure for that example in my own directory as well but I always get the error 'No module named 'actions.actions''
Am I using the wrong syntax in my yml file? 

Here is my (simplified) directory structure:
```
.
├── chat-interface
│   ├── actions.py
│   ├── agent.py
│   ├── domain.yml
│   ├── endpoints.yml
│   ├── helpers.py
│   ├── main.py
│   ├── nlu-config.yml
│   └── trainer.py
├── LICENSE
├── README.md
├── docker-compose.yml
└── requirements.txt
```

Thanks for any help

**Comment by shahad-bit** [comment]
> Hey, I figured out where the error was coming from - rasa_core_sdk spins up the action server from the main directory and calls the actions files using actions.actions (/actions/actions.py) but my actions.py has a relative import helpers statement that doesn't work when being called from the main directory, which doesn't have a helpers.py file in it. I solved my issue by copying the helpers file into the main directory when creating my docker image.

I am new to docker and I am facing the same issue, can you please elaborate how did you fix it. I have all my chatbot files along with docker-compose file in one directory where i call docker-compose up, yet i am still getting the same error.

**Comment by leonore** [comment]
your rasa_core_sdk is most likely looking for an actions.py file in an actions/ directory within the main directory

**Comment by shahad-bit** [comment]
Thanks, it was fixed by adding init file as mentioned, and then coping actions.py and all related files to app using a dockerfile. 

```
# Extend the official Rasa SDK image
FROM rasa/rasa-sdk:latest

COPY * /app/
```

**Comment by harsharupraj** [comment]
Hi i am very new to this and i am unable to understand what the docker means actually 

i am working on mac os to build rasa chatbot 

This is the error i am getting:

2020-07-11 11:09:56 INFO     rasa_sdk.endpoint  - Starting action endpoint server...
2020-07-11 11:09:56 ERROR    rasa_sdk.executor  - Failed to register package 'actions'.
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/rasa_sdk/executor.py", line 250, in register_package
    self._import_submodules(package)
  File "/opt/anaconda3/lib/python3.7/site-packages/rasa_sdk/executor.py", line 206, in _import_submodules
    package = self._import_module(package)
  File "/opt/anaconda3/lib/python3.7/site-packages/rasa_sdk/executor.py", line 227, in _import_module
    module = importlib.import_module(name)
  File "/opt/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/harshareddy/Downloads/Upgrad/nlp/chatbot/Ha/2/actions.py", line 13, in <module>
    from flask_mail_check import send_email
  File "/Users/harshareddy/Downloads/Upgrad/nlp/chatbot/Ha/2/flask_mail_check.py", line 3, in <module>
    from flask_mail import Mail, Message
  File "/Users/harshareddy/Downloads/Upgrad/nlp/chatbot/Ha/2/flask_mail.py", line 17, in <module>
    import blinker
ModuleNotFoundError: No module named 'blinker'

**Comment by harsharupraj** [comment]
got it thanks installed blinker, so stupid of me

**Comment by AdityaSharma404** [comment]
Hi,
I was also facing same error, But when opened a new terminal and set the path of Rasa Folder then issue got Resolve

1. Set the path
2. rasa run actions
