### ISSUE TITLE
Policy Error

### ISSUE THREAD

**Issue by serdarbozoglan** [RasaHQ/rasa_nlu#2967]
**Rasa Core version**:
o.13.2
**Python version**: 
3.6
**Operating system** (windows, osx, ...):
Osx
**Issue**:
My code is bellow
training_data_file = './data/stories.md'
    model_path = './models/dialogue'
    
    agent = Agent('weather_domain.yml', policies=[MemoizationPolicy(max_history=3), fallback])
    training_data=agent.load_data(training_data_file)
    
    agent.train(training_data,
                augmentation_factor = 50,
               #max_history = 2,
                epochs=500,
                batch_size=10,
                validation_split=0.2)

I got the error of "Exception: Passing policy configuration parameters to `agent.train(...)` is not supported anymore. Specify parameters directly in the policy configuration instead. "

Could you clarify please?
**Content of domain file** (if used & relevant):
```yaml

```

**Comment by rishi454** [comment]
your code.
```
agent.train(training_data,
            augmentation_factor = 50,
           #max_history = 2,
            epochs=500,
            batch_size=10,
            validation_split=0.2)
```
replace with this code
`agent.train(training_data)`
I hope it will work.
