### ISSUE TITLE
White / black list entities for intents

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa_nlu#2970]
Currently you can instruct Rasa Core do ignore entities for certain intents:

```yaml
intents:
  - greet: {use_entities: false}
```

We should enable a more detailed configuration for that, so that you can exactly specify which entities should be considered by an intent and which should be ignored.

**Comment by akelad** [comment]
@wochinge this should be covered by @mauricedoepkes PR right? so we can close this?
