### ISSUE TITLE
Sort predicted actions on probability score from HTTP API 

### ISSUE THREAD

**Issue by therealdeadly** [RasaHQ/rasa_nlu#2973]
**Rasa Core version**: 0.12.4

**Python version**: 3.6

**Operating system** (windows, osx, ...): windows

**Issue**:  Currently, the API endpoint :-  `/conversations/{sender_id}/predict`  doesn't return the actions in the `score` array sorted on their score(probabilities) values. 
Is it feasible to sort the array in the `server.predict()`,  just like in the `training.interactive._request_action_from_user()` in consequence removing the need to implement it in `interactive` and making the `score` array more comprehensible.

**Comment by akelad** [comment]
@therealdeadly any luck?

**Comment by therealdeadly** [comment]
@akelad yes, done the work on pull request #1733, and merged with the master successfully. 
New to this I thought the issue would auto-close after the merge, do I have to close it?
