### ISSUE TITLE
Migration issue with events (from 0.9.0 to 0.13.2)

### ISSUE THREAD

**Issue by vax521** [RasaHQ/rasa_nlu#2993]
**Rasa Core version**:
0.13.2
**Python version**: 
3.6.2
**Operating system** (windows, osx, ...):
windows
**Issue**:
I run a demo from web writen by rasa_core 0.9.0, the code is as follows:
```
from rasa_core.agent import Agent
from rasa_core.channels.console import ConsoleInputChannel
def run(serve_forever=True):
    agent = Agent.load("projects/dialogue",
                       interpreter=RasaNLUInterpreter("projects/ivr_nlu/demo"))

    if serve_forever:
        agent.handle_channel(ConsoleInputChannel())
    return agent
```
it reports a bug: 
ImportError: cannot import name 'ConsoleInputChannel'

By reading the new docs of rasa_core 0.13.2, I found  the  function  agent.handle_channel in rasa_core version 0.9.0 was changed to  agent.handle_channels(channels: List[rasa_core.channels.channel.InputChannel], http_port: int = 5005, serve_forever: bool = True, route: str = '/webhooks/') → gevent.pywsgi.WSGIServer . 
Who can write a demo to introduce how to use the new api agent.handle_channels()? 
Thanks.

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by JorkeMooN** [comment]
oh,thanks.
