### ISSUE TITLE
Python-Socket-IO and session_request

### ISSUE THREAD

**Issue by george-ai** [RasaHQ/rasa_nlu#3023]
**Rasa Core version**:  0.13.2

**Python version**: 3.6.3

**Operating system** (windows, osx, ...): Mac (Virtual Env.)

**Issue**: I am looking to emit session_request in order to track my user session, however I am definitely not succeeding. I have included the below. Not sure is I am using the session_request with emit correctly? Should this be used in a different way? Any help will be greatly appreciated.

***Credentials File***
```
socketio:
  user_message_evt: user_uttered
  bot_message_evt: bot_uttered
  session_persistence: true
```
***Socket Client***
```
def botUtterTask(user_id, user_message):

    sio = socketio.Client()

    @sio.on('connect')
    def on_connect():
        print('Connected to the Rasa Socket Server')
    sio.connect('http://localhost:5500')

    sio.emit('session_request', {'session_id': user_id})
    sio.emit('user_uttered', {'message': user_message})

    def handler(data):
        if 'text' in data:
        <Custom Code>
       
        sio.send('user_uttered')
    sio.on('bot_uttered', handler)
```
***Error Message***
```
[2019-03-02 21:41:59,789: WARNING/ForkPoolWorker-2] Connected to the Rasa Socket Server
127.0.0.1 - - [2019-03-03 10:41:59] "POST /socket.io/?transport=polling&EIO=3&sid=d32ceae4156348ccb123d8324982dc51 HTTP/1.1" 200 175 0.000363
2019-03-03 10:41:59 WARNING  rasa_core.channels.socketio  - A message without a valid sender_id was received. This message will be ignored. Make sure to set a proper session id using the `session_request` socketIO event.

```
***Doc Link***
https://rasa.com/docs/core/connectors/#id56

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by sushilr007** [comment]
Hello @george-ai Can you tell me where you put that code in RASA ? I  mean in action file or you made different socket.py ?
Thank you.

**Comment by george-ai** [comment]
> Hello @george-ai Can you tell me where you put that code in RASA ? I mean in action file or you made different socket.py ?
> Thank you.

Hi @sushilr007 

I believe this was a seperate socket.py file, but it has been some time. This initiative was abandoned :(
