### ISSUE TITLE
Bot replying via DM instead of on the channel [Slack Integration]

### ISSUE THREAD

**Issue by Maverick23** [RasaHQ/rasa_nlu#3024]
**Rasa Core version**: 0.13.1

**Python version**:  3.6.7

**Operating system** (windows, osx, ...): Windows 10 Home

**Issue**: Integrated the bot with Slack. The bot responds as expected but always replies directly(DM) to the user even if the message was sent to a channel.

**Content of domain file** (if used & relevant): Dont think this is relevant as the behaviour of bot is fine.
```yaml

```
Events subscribed to :
![events subscribbed to](https://user-images.githubusercontent.com/2720929/53694778-74cffb00-3dab-11e9-9c44-6a678b81d442.PNG)

**Comment by ricwo** [comment]
There's currently no way to dynamically reply either back to the channel or to the user. We might implement this kind of functionality in the future.

**Comment by Maverick23** [comment]
Hi @ricwo & team , Thanks for earlier help.  I have implemented a solution, where in i am extracting the channel type when event happens and passing it as an extra argument till the final call where its decided to either send it to channel or DM. Works fine for me.
Happy to share the codes, if that helps.

**Comment by ricwo** [comment]
Hi @Maverick23 - that sounds great! Please raise a PR with your changes in this repo. Feel free to tag me and we'll discuss the changes

**Comment by Maverick23** [comment]
Sure @ricwo . PR means pull request ?

**Comment by ricwo** [comment]
@Maverick23 exactly 🙂

**Comment by anoop2503** [comment]
Could anyone please confirm, whether this feature has been implemented or not? Unfortunately we can not say the framework is supporting the slack integration, if we don't have this basic feature, which is really important and required for slack communication :(

**Comment by HESHN** [comment]
Please share the solution :)
