### ISSUE TITLE
upload a trained model 400 Bad request

### ISSUE THREAD

**Issue by algteam** [RasaHQ/rasa_nlu#3035]
**Rasa Core version**:0.12.4

**Python version**: 3.6

**Operating system** (windows, osx, ...):ubuntu 16.04

**Issue**: 400 bad request

![image](https://user-images.githubusercontent.com/41173624/53873136-ab6f7500-403a-11e9-931c-19713f6a3e75.png)

![image](https://user-images.githubusercontent.com/41173624/53872815-f937ad80-4039-11e9-8b94-93a8faa16f61.png)
How to set the correct parameters?

**Comment by ricwo** [comment]
@algteam what exactly does your POST look like? It's not sufficient to reference the file location - you should be posting multipart form data. Can you please try the following command:
`curl -k -F "model=@models/mobile/mobile_bot.zip" http://your_core_server_url/model`
