### ISSUE TITLE
Not able to train the interactive file.

### ISSUE THREAD

**Issue by Nikhileshorg** [RasaHQ/rasa_nlu#3038]
**Rasa Core version**: 0.14.0a1

**Python version**: python 3.6

**Issue**:  Exception: Passing policy configuration parameters to `agent.train(...)` is not supported anymore. Specify parameters directly in the policy configuration instead.

I tried passing directly in the policy configuration but it is throwing me an error. 

The content of the file : 

______________________________________________________________________________________

from __future__ import absolute_import
from __future__ import division
from __future__ import unicode_literals

import logging

from rasa_core.agent import Agent
from rasa_core.policies.keras_policy import KerasPolicy
from rasa_core.policies.memoization import MemoizationPolicy

if __name__ =='__main__':
    logging.basicConfig(level='INFO')
	
    training_data_file = './data/stories.md'
    model_path = './models/dialouge'

    agent = Agent('weather_domain.yml', policies = [MemoizationPolicy(), KerasPolicy()])

    agent.train(
	        training_data_file,
			augmentation_factor = 50,
			max_history = 2,
			epochs = 500,
			batch_size = 10,
			validation_split = 0.2)
			
    agent.persist(model_path) 

_____________________________________________________________________________________

Getting this error instead, 

Exception: Passing policy configuration parameters to `agent.train(...)` is not supported anymore. Specify parameters directly in the policy configuration instead.

can you please help me to train the interactive file.

Thanks in advance.
Sai

**Comment by JulienBrochier** [comment]
Could you explain how to do this ?
"So basically all those configs (apart from augmentation_factor), should go either in the individual policies, or you can specify them in the policy configuration yaml file"

I've tried to modify default_config.yml  in rasa_core :
![image](https://user-images.githubusercontent.com/34643041/58944481-3834e680-8782-11e9-8eae-9914f555b0fb.png)

My train_init.py file : 

![image](https://user-images.githubusercontent.com/34643041/58944698-abd6f380-8782-11e9-8dd9-0af2186a2c9a.png)

Now I'm getting this error : 

![image](https://user-images.githubusercontent.com/34643041/58944819-d9bc3800-8782-11e9-8038-4631bafb4040.png)

I don't know if I've made the good choices and which parameters use

**Comment by JulienBrochier** [comment]
Ok, I've found it. I just needed to use agent
