### ISSUE TITLE
No matching distribution found for tensorflow~=1.12.0 (from rasa_core) 

### ISSUE THREAD

**Issue by elygod** [RasaHQ/rasa_nlu#3048]
**Rasa Core version**: pip install rasa_core

**Python version**: 3.6

**Operating system** (windows, osx, ...): windows 10

**Issue**:
I keep getting this tensorflow error ;
```
Collecting rasa_core
  Using cached https://files.pythonhosted.org/packages/3e/6a/f2c4e8ae1903805324267e915a167ded91a439bafd09efa6da0a2a50e409/rasa_core-0.13.3-py3-none-any.whl
Collecting rocketchat-API~=0.6.0 (from rasa_core)
  Using cached https://files.pythonhosted.org/packages/5f/c0/117b97e5b4e057808b4db1dda3bfb9aef46e502b7f8107bc8e33d2df7ee9/rocketchat_API-0.6.27-py3-none-any.whl
Requirement already satisfied: ruamel.yaml~=0.15.0 in c:\users\asus\islemenv\lib\site-packages (from rasa_core) (0.15.37)
Collecting tensorflow~=1.12.0 (from rasa_core)
  Could not find a version that satisfies the requirement tensorflow~=1.12.0 (from rasa_core) (from versions: )
No matching distribution found for tensorflow~=1.12.0 (from rasa_core)
```
 I already tried this but still didn't work
```
 python -m pip install --upgrade 
https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.12.0-py3-none-any.whl

```
**EDIT**:  I solved this by installing an older version of rasa-core with tensorflow 1.10.0 ; then upgraded both ; dunno how it worked but it did

**Comment by akelad** [comment]
@paxinos is it possible that you have python 3.7 installed, because we don't quite support that yet

**Comment by paxinos** [comment]
Thanks.  That was it.

**Comment by sskorol** [comment]
Folks, please update your documentation, as it seems like only 3.6 python is currently supported. Note that 2.7 is usually OS-bundled, and 3.7 is the latest one. Neither of these 2 allows installing rasa core. It might be a very disappointing first impression, as people fail to install software from the very beginning.

**Comment by akelad** [comment]
that's not true, python 3.5 is supported as well and we're working on supporting python 3.7
support for 2.7 has been dropped because python themselves are dropping support for that soon.

Could you point me to where this is out of date? our github repos at least have the correct badges as far as i can see

**Comment by sskorol** [comment]
Sorry for being inaccurate with 3.x version assumptions. My bad.

Regarding references: neither [NLU](https://rasa.com/docs/nlu/installation/#setting-up-rasa-nlu) nor [Core](https://rasa.com/docs/core/installation/#install-rasa-core) installation sections have notes about supported Python versions.

Personally to me, who doesn't know Python ecosystem yet, it wasn't quite obvious to find the reason of the failure. And the first place where I was looking at, was your official extensive documentation. Badges are quite easy to miss, when you've just started playing with a product. But thanks for pointing out.

**Comment by akelad** [comment]
yeah that's a fair point -- would you be willing to raise a PR to add that to our documentation?

**Comment by ramsundhar20** [comment]
Am also facing the same issue.

**Comment by ramsundhar20** [comment]
> strange, tensorflow 1.12 definitely exists. Potentially a windows related problem. In any case, sounds like your issue is solved so I will close

1.12.0 has moved 1.12.2 may be a hard validation of 1.12.0 in requirements.txt is failing.

**Comment by akelad** [comment]
again, right now we just support 3.5 and 3.6. If you take a look at the open PRs you'll see there's one for python 3.7 compatibility. Tensorflow isn't the only package that needs to be updated for that, so we're still making sure everything runs. Once that's merged, python 3.7 will be supported on master

**Comment by PratyushTripathy** [comment]
Hey all, I got the same error on Python 3.5. I found the way out by using Python 3.7.4.

**Comment by nich02** [comment]
Hello friends, i am a bit frastrated I want to import tensor flow in my anaconda but i keep getting the error (ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)
ERROR: No matching distribution found for tensorflow)   

I have tried multiple options online. please help

**Comment by oma0256** [comment]
> Hey all, I got the same error on Python 3.5. I found the way out by using Python 3.7.4.

How did you solve that?

**Comment by nich02** [comment]
Myself I don't know how to do it in Python 3.5, I tried it Python 3.7.4.
and it was a challenge, how did you do it.? Please help

**Comment by akelad** [comment]
@nich02 which version of rasa are you installing and in which environment are you getting what errors? Would be good if you can post all this information here

**Comment by Raja2siva** [comment]
any one using tensorflow in windows
please tell me that python version and tensorflow version
and windows version

**Comment by angshuman-agarwal** [comment]
I have a similar issue - https://forum.rasa.com/t/error-no-matching-distribution-found-for-tensorflow-1-14-0-from-rasa-1-4-0-rasa-x/21171

**Comment by geet2019** [comment]
how to resolve this problem 👍 

RROR: Could not install packages due to an EnvironmentError: [WinError 5] Access is denied: 'C:\\Users\\USER\\Anaconda3\\envs\\py374\\Lib\\site-packages\\numpy\\core\\_multiarray_tests.cp37-win_amd64.pyd'
Consider using the `--user` option or check the permissions.

**Comment by dnwjddl** [comment]
Hi, I have a same problem. how did you solved it?

**Comment by sangee14** [comment]
I have the same issue, with Ubuntu OS and python 3.6, tried installing rasa-core and got this error
$ pip install rasa-core

ERROR: Could not find a version that satisfies the requirement tensorflow~=1.13.0 (from rasa-core) (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.2.1, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0, 2.3.1, 2.4.0rc0)
ERROR: No matching distribution found for tensorflow~=1.13.0 (from rasa-core)
