### ISSUE TITLE
Rasa command line interface

### ISSUE THREAD

**Issue by tmbo** [RasaHQ/rasa_nlu#3063]
# Goal
* intuitive
* short commands (if default configuration)
* reuse existing knowledge
* unify interface for Rasa Core / NLU

# General Idea
Assume a rasa project with a default project layout. This means we can assume the location and name of files (e.g. `domain.yml` is always in the project root and has this name). By looking in default locations for files the user can skip their declaration. If users deviate from the normal project layout, they have to specify the locations manually.

# Assumed project layout

```
.
├── __init__.py
├── actions.py
├── endpoints.yml
├── credentials.yml
├── data
├── domain.yml
├── models
│   ├── core
│   └── nlu
├── config.yml (contains both core and nlu config)
```
# Suggested command line commands:

## Creating the initial project (new feature)
* `rasa init` + interactive guide to create project (e.g. provide project name, etc)

## Training
* Training of Core and NLU: `rasa train`
* Training of the core model: `rasa train core`
* Training of the nlu model:`rasa train nlu`
* Interactive Training: `rasa interactive` (or `rasa train interactive`?)
* Special case compare polices: `rasa train core --config policy1.yml policy2.yml`

## Validating
* test both: `rasa test`
* test only core: `rasa test core`
* test only nlu: `rasa test nlu`

## Run Server
* Start Core with trained NLU model: `rasa run`
* Run Core server: `rasa run core`
* Run NLU server: `rasa run nlu`
* Run action server: `rasa run sdk` (should we include the sdk or keep that separate?)

## Visualize
* Show story paths: `rasa show` (alternatives: `rasa inspect`, `rasa visualize`)

## Data
There is currently just one command in this section, but we could have other commands like `rasa data validate <file>` or `rasa data split` here in the future
* Convert nlu data: `rasa data nlu convert`

## Interacting with the server
`rasa remote`
### Crucial
* provide credentials: `rasa remote login <host>` (where / how do we store them)
* select environment (prod / dev / test): `rasa remote stages <env>`
* set model as active: `rasa remote models select <model-id>`
* pushing models:  `rasa remote models push <model>`
* downloading models: `rasa remote models pull <model>`
* push data: `rasa remote data push`
* pull data: `rasa remote data pull`

### Nice to have
* list models: `rasa remote models list`
* list users: `rasa remote users list`
* status : `rasa remote status`
* logs: `rasa remote logs`
* show config: `rasa remote config`

## Interacting with local server
`rasa local`
commands as above for server except
* no login
* pushing / downloading are not needed (set as active should be enough)

## Other
* `rasa --version`
* `rasa --help`

## Parameter Names
* tbd, general idea is to keep them like they are, but unify them between Core and NLU

## Current Status
- [x] rasa init
- [x] rasa run
- [x] rasa train
- [x] rasa test
- [x] rasa show
- [ ] rasa remote
- [ ] rasa local
- [x] rasa data

## How to test
https://github.com/RasaHQ/rasa_stack/issues/1#issuecomment-462871671

**Comment by mukherjeesoumya** [comment]
> # Goal
> * intuitive
> * short commands (if default configuration)
> * reuse existing knowledge
> * unify interface for Rasa Core / NLU
> 
> # General Idea
> Assume a rasa project with a default project layout. This means we can assume the location and name of files (e.g. `domain.yml` is always in the project root and has this name). By looking in default locations for files the user can skip their declaration. If users deviate from the normal project layout, they have to specify the locations manually.
> 
> # Assumed project layout
> ```
> .
> ├── __init__.py
> ├── actions.py
> ├── endpoints.yml
> ├── credentials.yml
> ├── data
> ├── domain.yml
> ├── models
> │   ├── core
> │   └── nlu
> ├── config.yml (contains both core and nlu config)
> ```
> 
> # Suggested command line commands:
> ## Creating the initial project (new feature)
> * `rasa init` + interactive guide to create project (e.g. provide project name, etc)
> 
> ## Training
> * Training of Core and NLU: `rasa train`
> * Training of the core model: `rasa train core`
> * Training of the nlu model:`rasa train nlu`
> * Interactive Training: `rasa interactive` (or `rasa train interactive`?)
> * Special case compare polices: `rasa train core --config policy1.yml policy2.yml`
> 
> ## Validating
> * test both: `rasa test`
> * test only core: `rasa test core`
> * test only nlu: `rasa test nlu`
> 
> ## Run Server
> * Start Core with trained NLU model: `rasa run`
> * Run Core server: `rasa run core`
> * Run NLU server: `rasa run nlu`
> * Run action server: `rasa run sdk` (should we include the sdk or keep that separate?)
> 
> ## Visualize
> * Show story paths: `rasa show` (alternatives: `rasa inspect`, `rasa visualize`)
> 
> ## Data
> There is currently just one command in this section, but we could have other commands like `rasa data validate <file>` or `rasa data split` here in the future
> 
> * Convert nlu data: `rasa data nlu convert`
> 
> ## Interacting with the server
> `rasa remote`
> 
> ### Crucial
> * provide credentials: `rasa remote login <host>` (where / how do we store them)
> * select environment (prod / dev / test): `rasa remote stages <env>`
> * set model as active: `rasa remote models select <model-id>`
> * pushing models:  `rasa remote models push <model>`
> * downloading models: `rasa remote models pull <model>`
> * push data: `rasa remote data push`
> * pull data: `rasa remote data pull`
> 
> ### Nice to have
> * list models: `rasa remote models list`
> * list users: `rasa remote users list`
> * status : `rasa remote status`
> * logs: `rasa remote logs`
> * show config: `rasa remote config`
> 
> ## Interacting with local server
> `rasa local`
> commands as above for server except
> 
> * no login
> * pushing / downloading are not needed (set as active should be enough)
> 
> ## Other
> * `rasa --version`
> * `rasa --help`
> 
> ## Parameter Names
> * tbd, general idea is to keep them like they are, but unify them between Core and NLU
> 
> ## Current Status
> * [x]  rasa init
> * [x]  rasa run
> * [x]  rasa train
> * [x]  rasa test
> * [x]  rasa show
> * [ ]  rasa remote
> * [ ]  rasa local
> * [x]  rasa data
> 
> ## How to test
> https://github.com/RasaHQ/rasa_stack/issues/1#issuecomment-462871671

I would suggest we should give a makefile and give it to the users, it is still unclear how to run the action server with endpoints etc after introducing these commands. are we doing something on it

**Comment by mukherjeesoumya** [comment]
I would suggest we should give a makefile and give it to the users, it is still unclear how to run the action server with endpoints etc after introducing these commands. are we doing something on it
