### ISSUE TITLE
Proposal: EntitySlotMapping feature

### ISSUE THREAD

**Issue by mauricedoepke** [RasaHQ/rasa_nlu#3099]
As of my knowledge, rasa currently allows filling slots only with entities of the same name. (Without writing a custom action).

I propose an option to allow entity-slot-mapping on a per intent basis, with a syntax like this:

```
intents:
  - example_intent: {map_entities_to_slots: {entity_name: slot_name, other: slot_name}}
```

See these links for use cases:
https://forum.rasa.com/t/entities-and-slots-have-same-name/6166
https://forum.rasa.com/t/entity-detection-problem/6155

**Comment by akelad** [comment]
I think this is something you should handle in your custom action still, any reason this method doesn't work for you?
