### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by tiwo19** [RasaHQ/rasa_nlu#3101]
**Rasa Core version ==0.11.1

**Python version 3.6

Operating system  windows, 10

when i try to train my model with python train_initialize.py file i get this error message

(env) C:\Users\damipe\Desktop\horoscope_bot>python train_initialize.py
C:\Users\damipe\AppData\Local\Programs\Python\Python36\Lib\site-packages\pykwalify\core.py:99: UnsafeLoaderWarning:
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)
Traceback (most recent call last):
  File "train_initialize.py", line 16, in <module>
    policies=[MemoizationPolicy(), KerasPolicy()])
  File "C:\Users\damipe\AppData\Local\Programs\Python\Python36\Lib\site-packages\rasa_core\agent.py", line 198, in __init__
    self.domain = self._create_domain(domain)
  File "C:\Users\damipe\AppData\Local\Programs\Python\Python36\Lib\site-packages\rasa_core\agent.py", line 636, in _create_domain
    return Domain.load(domain)
  File "C:\Users\damipe\AppData\Local\Programs\Python\Python36\Lib\site-packages\rasa_core\domain.py", line 89, in load
    return cls.from_yaml(read_file(filename))
  File "C:\Users\damipe\AppData\Local\Programs\Python\Python36\Lib\site-packages\rasa_core\domain.py", line 95, in from_yaml
    return cls.from_dict(data)
  File "C:\Users\damipe\AppData\Local\Programs\Python\Python36\Lib\site-packages\rasa_core\domain.py", line 100, in from_dict
    slots = cls.collect_slots(data.get("slots", {}))
  File "C:\Users\damipe\AppData\Local\Programs\Python\Python36\Lib\site-packages\rasa_core\domain.py", line 140, in collect_slots
    slot_class = Slot.resolve_by_type(slot_dict[slot_name].get("type"))
AttributeError: 'NoneType' object has no attribute 'get'

Content of domain file
slots:
horoscope_sign:
type: text
DD:
type: text
MM:
type: text
subscribe:
type: bool
intents:

greeting
get_horoscope
subscription
dob_intent
entities:
horoscope_sign
DD
MM
subscribe
dob_intent

templates:
utter_greet:
'Hello! How are you doing today?'
utter_ask_horoscope_sign:
'What is your horoscope sign?'
utter_ask_dob:
'What is your DOB in DD-MM format?'
utter_subscribe:
'Do you want to subscribe for daily updates?'
actions:
utter_greet
utter_ask_horoscope_sign
utter_ask_dob
utter_subscribe
get_todays_horoscope
subscribe_user

**Comment by akelad** [comment]
Thanks for raising this issue, @paulaWesselmann  will get back to you about it soon.

**Comment by paulaWesselmann** [comment]
Hey @tiwo19, what is in your `train_initialize.py` file? It looks like you might be missing some inputs. Also you might be able to fix this by updating to a newer rasa_core version, have a look here https://rasa.com/docs/core/migrations/. If your issue still persists please let me know!

**Comment by tiwo19** [comment]
@paulaWesselmann  thank you for your support i actually was missing some input in train_initialize.py file i fixed it by downloading the Git Repo of the person i was learning the tutorial form Thank you so much for your support @paulaWesselmann .

**Comment by paulaWesselmann** [comment]
Awesome! I'll close this issue then.
