### ISSUE TITLE
agent.handle_message() returns empty text after a few conversations

### ISSUE THREAD

**Issue by ewagner70** [RasaHQ/rasa_nlu#3106]
**Rasa Core version**: 0.9.0a2
**Rasa NLU version**: 0.12.2
**Python version**: 3.6
**Tensorflow version**: tensorflow-gpu 1.7.0
**Operating system** (windows, osx, ...): Ubuntu 17.10
**Issue**: agent.handle_message() returns only empty dict/text after a few conversations. See example below:

George: hi
Bot: hey there None!
George: my name is eric
Bot: Good to know you, None
George: i am called eric
Bot: Good to know you, None
George: my parents call me eric
Bot: Good to know you, eric
George: bye
Bot: KEINE ANTWORT ## means dict/text is empty, i.e. None
George: that's correct
Bot: KEINE ANTWORT  ## means dict/text is empty, i.e. None
George: hi       
Bot: KEINE ANTWORT ## means dict/text is empty, i.e. None
George: my parents call me eric
Bot: KEINE ANTWORT ## means dict/text is empty, i.e. None
George: 

**Content of domain file** (if used & relevant):
see attached zip files 
```
Thx in advance for your help!
KR Eric
[test_rasa.zip](https://github.com/RasaHQ/rasa_core/files/1939666/test_rasa.zip)

**Comment by LakshiAthapaththu** [comment]
Hi,
I have trained rasa NLU and core separately and passed an NLU interpreter to Agent.load function and used it into handle_message function. But it always gives an empty response. Here is my code.

nlu_interpreter = RasaNLUInterpreter(nlu_model_path)
agent = Agent.load(core_model_path, interpreter = nlu_interpreter)
while True:
        user_input = input()
        if user_input == 'stop':
            break
        responses = agent.handle_text(user_input)
        print(response)

I need a help to fix the issue.
