### ISSUE TITLE
custom action not found

### ISSUE THREAD

**Issue by Krogsager** [RasaHQ/rasa_nlu#3110]
**Rasa Core version**: 0.11.0a1, commit 89b4651f4a

**Python version**: 
Python 3.6.6 |Anaconda, Inc.

**Operating system** (windows, osx, ...): macOS 10.13.6

**Issue**:
When running rasa_core.train my custom action is not found.

I first receive a warning:
`rasa_core.domain - Failed to use action 'custom_action_hello' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this 
warning. It should stop appearing after a while. `

Then I receive an error:
```
  File "/Users/andkr/rasa/rasa_core/rasa_core/domain.py", line 251, in index_for_action
    return self.action_names.index(action_name)
ValueError: 'custom_action_hello' is not in list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda3/envs/rasa_env/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/anaconda3/envs/rasa_env/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/andkr/rasa/rasa_core/rasa_core/train.py", line 191, in <module>
    additional_arguments)
  File "/Users/andkr/rasa/rasa_core/rasa_core/train.py", line 162, in train_dialogue_model
    agent.train(training_data, **kwargs)
  File "/Users/andkr/rasa/rasa_core/rasa_core/agent.py", line 513, in train
    **kwargs)
  File "/Users/andkr/rasa/rasa_core/rasa_core/policies/ensemble.py", line 61, in train
    policy.train(training_trackers, domain, **kwargs)
  File "/Users/andkr/rasa/rasa_core/rasa_core/policies/memoization.py", line 152, in train
    self._add(trackers_as_states, trackers_as_actions, domain)
  File "/Users/andkr/rasa/rasa_core/rasa_core/policies/memoization.py", line 108, in _add
    feature_item = domain.index_for_action(action)
  File "/Users/andkr/rasa/rasa_core/rasa_core/domain.py", line 253, in index_for_action
    self._raise_action_not_found_exception(action_name)
  File "/Users/andkr/rasa/rasa_core/rasa_core/domain.py", line 261, in _raise_action_not_found_exception
    "Available actions are: \n{}".format(action_name, action_names))
Exception: Can not access action 'custom_action_hello', as that name is not a registered action for this domain. Available actions are: 
	 - action_listen
	 - action_restart
	 - action_default_fallback
	 - actions.ActionHello
```

**Content of domain file** (if used & relevant):
```yaml
intents:
- int_greet

actions:
- actions.ActionHello
```

**Content of story file**
```md
## Generated Story 708345159307012596
* int_greet
    - custom_action_hello
```

**Content of actions.py**
```python
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

from rasa_core.actions import Action
from rasa_core.events import SlotSet, AllSlotsReset

class ActionHello(Action):  
    def name(self):         
        return 'custom_action_hello' 
    
    def run(self, dispatcher, tracker, domain):         
                dispatcher.utter_message("HELLO from python.")
        return[]

```

**Comment by anilpankaj** [comment]
> Some things have changed with 0.11, so rather than listing the action as `actions.ActionHello` you should list it as `custom_action_hello`. Also how custom actions are run now has changed, with the SDK factor. Here are the relevant links:
> https://rasa.com/docs/core/master/migrations/
> https://rasa.com/docs/core/master/customactions/

thank you so much it's work for me you save my time thanks again

**Comment by anilpankaj** [comment]
> This is even stranger. if I delete the training data then the error message will randomly treat a line from the NLU file as an action. E.g.
> 
> `Exception: Can not access action 'det passer', as that name is not a registered action for this domain. Available actions are: `
> 
> or
> 
> `Exception: Can not access action 'en [fysisk](physical) hændelse', as that name is not a registered action for this domain. Available actions are:`
> 
> After a few runs the problem "converges" and consistently reports an the same action:
> 
> `Exception: Can not access action 'custom_act_get_date', as that name is not a registered action for this domain. Available actions are: `

you should add in domain file into the actions 'custom_action_hello'. and run it i hope it's work for you
