### ISSUE TITLE
What is the stable version (Production Ready) for RASA CORE +  NLU + UI

### ISSUE THREAD

**Issue by bandarunagesh** [RasaHQ/rasa_nlu#3113]
**Question**:
Can you please help me find the stable version of RASA Core, NLU and UI to use for production deployments. 

Also , i would like to know if the tensorflow NLU are ready for production?

**Comment by rameshJantali3** [comment]
Please help : 
With Python 3.7 trying to install rasa_core = 0.11.3 and tensorflow = 1.10.0 getting this Error -  Could not find a version that satisfies the requirement tensorflow~=1.10 (from
rasa_core==0.11.3) (from versions: ) o matching distribution found for tensorflow~=1.10 (from rasa_core==0.11.3)
