### ISSUE TITLE
The rasa/rasa_nlu docker image is not up to date

### ISSUE THREAD

**Issue by yellowiscool** [RasaHQ/rasa_nlu#312]
Hi,

It seems that the [`rasa/rasa_nlu`](https://hub.docker.com/r/rasa/rasa_nlu/) docker image on the public hub is not maintained. Do you plan to update it or to setup an automated build connected this repository ?

**Comment by amn41** [comment]
Yes - we're working on it right now :)

**Comment by yellowiscool** [comment]
Great 😃

**Comment by tmbo** [comment]
We pushed the latest docker image - and we will do so in an automated way in the future.
