### ISSUE TITLE
ValueError: Unknown data format for file ./data/data.json

### ISSUE THREAD

**Issue by meghnasmhs** [RasaHQ/rasa_nlu#3125]
**Rasa version**:0.2.7

**Python version**: 3.6.4

**Operating system** (windows, osx, ...):windows 8

**Issue**:ValueError: Unknown data format for file ./data/data.json

**Content of configuration file (config.yml)**:
```yml

```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml

```

**Comment by akelad** [comment]
Please provide some more details on your issue, version 0.2.7 for example does not exist

**Comment by chaitu9701** [comment]
I didn't realize that this issue was already reported, I opened another one  [here](https://github.com/RasaHQ/rasa_lookup_demo/issues/2).
Would gladly provide additional details required.
