### ISSUE TITLE
Empty entities are being returned with ner_crf.

### ISSUE THREAD

**Issue by hijab10** [RasaHQ/rasa_nlu#3131]
I'm trying to extract entities in the Urdu language. 
The rasa version I'm using is 0.14.6 with python 3.7.2 on Windows 10.
I'm using the following configuration:

language: "ur"

pipeline: 
- name: "tokenizer_whitespace"
- name: "ner_crf"
- name: "ner_synonyms"
- name: "intent_featurizer_count_vectors"
- name: "intent_classifier_tensorflow_embedding"

There are no issues during training. I can't seem to figure out the issue because my model classifies the intents correctly but does not return the entities. I've made sure the starting and ending positions of my entities in my training data are correct. 
Any help in this regard is appreciated.

**Comment by akelad** [comment]
Please ask these kind of questions in our [forum](https://forum.rasa.com)
