### ISSUE TITLE
Spacy Entity Extractor Test Fails / Needs Fixing

### ISSUE THREAD

**Issue by demongolem** [RasaHQ/rasa_nlu#3155]
**Rasa version**:
0.15.0a4

**Python version**: 
3.6.7

**Operating system** (windows, osx, ...):
Windows 10

**Issue**:

>     Info about spaCy

    spaCy version      2.0.12
    Location           C:\Users\gwerner004\AppData\Local\Programs\Python\Python36\lib\site-packages\spacy
    Platform           Windows-10-10.0.16299-SP0
    Python version     3.6.7
    Models             en

With the above Spacy version, the function `test_spacy_ner_extractor` finds 0 entities.  The utterance which is currently present in that test file and used for testing is 

> anywhere in the West

which supposed to return West as a Loc, but it doesn't.  If I change "West" to be "Utah" and then entity type of "GPE", the test will pass.  Therefore, the utterance appears to not work with current spacy model and a more straightforward and obvious entity needs to be picked for test case, something that is highly unlikely to fail.

**Content of configuration file (config.yml)**:
```yml
NA, because I am running unit tests
```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml

```

**Comment by demongolem** [comment]
Also, let me throw out, the testing methodology for that spacy entity extractor could also change.  Certainly one could argue that replacing one entity with another is fragile.

**Comment by akelad** [comment]
how are you testing this? We actually don't test spacy entity extraction because it's fixed and therefore changing your training data won't have any influence over it

**Comment by demongolem** [comment]
Using pytest.  The assertion fails because 0 entities are seen in the given utterance.

I wrote a similar unit test for another ner tool (not included in the the rasa distribution) in the same manner and that passed.

**Comment by akelad** [comment]
ok could you paste the code of your test?

**Comment by demongolem** [comment]
As is, with the last line I give the line where the assertion error is because 0 entities are present:

`def test_spacy_ner_extractor(component_builder, spacy_nlp):
    _config = RasaNLUModelConfig({"pipeline":
                                 [{"name": "SpacyEntityExtractor"}]})
    ext = component_builder.create_component(_config.for_component(0), _config)
    example = Message("anywhere in the West", {
        "intent": "restaurant_search",
        "entities": [],
        "spacy_doc": spacy_nlp("anywhere in the west")})
    ext.process(example, spacy_nlp=spacy_nlp)

    assert len(example.get("entities", [])) == 1`

Now continuing on with the test here is one way to get the test to pass:
`def test_spacy_ner_extractor(component_builder, spacy_nlp):
    _config = RasaNLUModelConfig({"pipeline":
                                 [{"name": "SpacyEntityExtractor"}]})
    ext = component_builder.create_component(_config.for_component(0), _config)
    example = Message("anywhere in Utah", {
        "intent": "restaurant_search",
        "entities": [],
        "spacy_doc": spacy_nlp("anywhere in Utah")})
    ext.process(example, spacy_nlp=spacy_nlp)

    assert len(example.get("entities", [])) == 1
    assert example.get("entities")[0] == {
        'start': 12,
        'extractor': 'SpacyEntityExtractor',
        'end': 16,
        'value': 'Utah',
        'entity': 'GPE',
        'confidence': None}
`
Note that the second test in the function, the filtering one, still passes because it does not require West to be correctly recognized as an entity.

**Comment by akelad** [comment]
@demongolem ok and does an entity get picked up for `West` when you talk to your bot as usual? It might just be that the spacy extractor doesn't recognise that as an entity.

**Comment by demongolem** [comment]
I am not sure because my company only uses the Rasa NLU component.  Certainly we can say though that the Spacy extractor does not pick it up.

**Comment by akelad** [comment]
then in that case this is not a bug, but behaviour of the spacy model. If you think this is an issue, please raise on on the spacy repository

**Comment by demongolem** [comment]
But the point is that there is a test that fails in the Rasa repository and it is ludicrous to have this test.  Something needs to be done, perhaps remove this test, because how is it testing Rasa?

**Comment by akelad** [comment]
i'm a little confused, could you link to the test in the repo? because our builds are passing so i'm not sure what you mean that it's failing

**Comment by demongolem** [comment]
Well I have a feeling what we surmised is probably correct.  The spacy ner extractor fails to pick out the required entity, but at a different stage in the flow the West is somehow picked up as an entity and life is good.  So then we are testing on different levels, myself at a lower (per file) level and the tests you talk about at a higher level.  I will try to see how this higher level testing occurs and then duplicate the passing behavior.

**Comment by akelad** [comment]
yeah please let us know
