### ISSUE TITLE
Deploying Chatbot to production

### ISSUE THREAD

**Issue by thyravi** [RasaHQ/rasa_nlu#3158]
**Rasa version**:

**Python version**: 3.6

**Operating system** (windows, osx, ...): Windows 2016

**Issue**: I have created a Chatbot and it is working fine in our development environment. I want to migrate it to production. Production environment doesn't have internet and I cannot install directly. So I installed python 3.6.6 and rest of the components (folders & files) I copied from my dev server to prod. 

Initially I faced "ImportError: DLL load failed: The specified module could not be found"
I managed to resolve this issue. Now I am facing "ModuleNotFoundError: No module named 'scipy._lib'"

I never faced these issues in my dev environment. Is this correct approach? If not could you please advise what is the best approach. Production is very secured environment. So only way to get things is through thumb drive. Kindly advise. Thanks.

**Content of configuration file (config.yml)**:
```yml

```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml

```

**Comment by akelad** [comment]
Please ask these kind of questions in our [forum](https://forum.rasa.com). I'm afraid as it's not rasa specific, I'm not sure how best to advise you there. Our community may be of better help
