### ISSUE TITLE
couldnt connect to the rasa core server through post request.

### ISSUE THREAD

**Issue by suryavamsi1563** [RasaHQ/rasa_nlu#3165]
**Rasa version**: RASA NLU--0.14.6,RASA CORE--0.13.5, RASA CORE SDK--0.12.2

**Python version**: 3.6.8

**Operating system** (windows, osx, ...):Windows

**Issue**: I have built a weather bot and trained it.When i run the rasa server, Its working fine in the command line. I need to give my bot access to other applications through API's.

I tried to do POST requests with POSTMAN and curl but couldnt get any viable response from the server.

I need the information on urls which can be used to give the bot messages through html/Javascript and get back the responses.

**Content of configuration file (config.yml)**:
{
    "pipeline":"spacy_sklearn",
    "path":"./models/nlu",
    "data":"./data/data.json"
}

**Content of domain file (domain.yml)** (if used & relevant):
slots:
  location:
    type: text

intents:
  - greet
  - goodbye
  - inform

entities:
  - location

templates:
  utter_greet:
    - 'Hello! How can I help ?'
  utter_goodbye:
    - 'Talk to you later' 
    - 'Bye.Nice talking to you.'
    - 'Bye Bye'
    - 'Good bye.'
  utter_ask_location:
    - 'In what location ?'
    - 'Can you give me the location ?'

actions:
  - utter_greet
  - utter_goodbye
  - utter_ask_location
  - action_weather
```

**Comment by akelad** [comment]
what response are you getting?
