### ISSUE TITLE
update form docs

### ISSUE THREAD

**Issue by paulaWesselmann** [RasaHQ/rasa_nlu#3176]
Explain what every line in the story does for the form and when what information is needed in the stories. 
For example, the stories shown in the docs include: `- form{"name": null}` but don't say what it is doing. Also since interactive learning is printing much more than required that could be explained.

We want to to find the `forms docs` by searching `forms` and not just when searching `formaction`

**Comment by erohmensing** [comment]
Since `Slot Filling` is almost ALL forms now, i'd almost be tempted just to rename the whole chunk `Forms` in the side bar, and move anything left in `Slot Filling` that isn't about forms into `Using Slots`...

Also we should link to the information about form actions from the `Actions` page

**Comment by paulaWesselmann** [comment]
@erohmensing I will not address this in this PR, but I think there definitely are some improvements to be made in the structure and how things are referenced. Maybe we should open a new issue for that?

**Comment by akelad** [comment]
@paulaWesselmann @erohmensing did you guys open an issue for that?

**Comment by erohmensing** [comment]
I'm on it
