### ISSUE TITLE
Adding an `utter_*` action in interactive learning

### ISSUE THREAD

**Issue by anoop2503** [RasaHQ/rasa_nlu#3178]
**Rasa version:**
rasa-core (0.13.6)
rasa-core-sdk (0.12.2)
rasa-nlu (0.14.6)

**Python Version:** Python 3.6.7

**Operating System:** Linux- Ubuntu 18.04.2 LTS

**Issue:** Interactive learning should not throw this warning for an `utter_*` action because it's an utterance template. So we should:
* change it so that new utter actions don't get run by the action server
* throw a warning to add text to your utterance template (or enter your text there directly)

```
? What is the next action of the bot?  (Use arrow keys)
 » <create new action>
   1.00 utter_unclear
   0.00 __main__.ApiAction
   0.00 action_deactivate_form
   0.00 action_default_ask_affirmation
   0.00 action_default_ask_rephrase
   0.00 action_default_fallback
   0.00 action_listen
   0.00 action_restart
   0.00 action_retrieve_image
   0.00 action_revert_fallback_events
   0.00 utter_ask_picture
   0.00 utter_did_that_help
   0.00 utter_goodbye
   0.00 utter_greet
   0.00 utter_happy
   0.00 utter_question_answer



------
? What is the next action of the bot?  <create new action>
? Please type the action name utter_answer_age
Thanks! The bot will now run utter_answer_age.

2019-03-29 14:17:36 ERROR    rasa_core.server  - **Encountered an exception while running action 'utter_answer_age'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.**
? WARNING: You have created a new action: 'utter_answer_age', which was not successfully executed. If this action does not retu
rn any events, you do not need to do anything. If this is a custom action which returns events, you are recommended to implemen
t this action in your action server and try again.  (Y/n)
```

**Comment by anoop2503** [comment]
Any update on this please?

**Comment by akelad** [comment]
well, this isn't an error. This is intended. If you don't have your action implemented it can't be executed.  However, this seems to be an `utter_` template, so you should be able to hit "no" here.
I'm going to keep this issue and rename it, because it actually shouldn't be throwing this warning if you add an action with an `utter_` prefix.

**Comment by anoop2503** [comment]
Thank you @akelad for clarifying it.

Yeah, that was my question exactly. Since this is an utter_ action, I think it should not throw any exception when creating this action. Also it does not continue with template creation process after throwing this exception. In this case, the user has to edit the domain.yml manually to create a template for this new utter_ action. I believe, this is not the expected behavior.

**Comment by akelad** [comment]
yep, @paulaWesselmann will look into fixing it :)

**Comment by anoop2503** [comment]
Thank you for the support.

**Comment by paulaWesselmann** [comment]
@anoop2503 I'm working on a PR fixing this so that the user can add templates for 'utter_` actions and choose newly created actions from the same session.

**Comment by anoop2503** [comment]
Great, thank you @paulaWesselmann

**Comment by anoop2503** [comment]
Hey @paulaWesselmann, hope this is still in progress.

**Comment by paulaWesselmann** [comment]
Hey @anoop2503 if you need a quick fix for this please look at the PR. The review is in progress and will be merged once we get to it.

**Comment by anoop2503** [comment]
sure, thank you @paulaWesselmann

**Comment by ruchiawasthi63** [comment]
@anoop2503  Hi. Can you share the code through which you started interactive learning. I'm not able to get any command line command to start interactive learning except `rasa interactive \
  -m models/20190515-135859.tar.gz \
  --endpoints endpoints.yml`
This doesn't seem to be working for me
I tried this code as well but seems like this doesn't work with my rasa_core version. My rasa_core version is 0.14
`python -m rasa_core.train -d domain.yml -s stories.md -o models/dialogue --endpoints endpoints.yml --online`
