### ISSUE TITLE
NaturalLanguageInterpreter

### ISSUE THREAD

**Issue by bheemlabs** [RasaHQ/rasa_nlu#3182]
**Rasa version**:
0.8.12

**Python version**: 
Both Python2.7 and Python3.6
![Screenshot from 2019-03-31 10-23-05](https://user-images.githubusercontent.com/42903197/55284975-12b0e880-539f-11e9-870c-be01d08a0bc3.png)

As shown in the ss Error varies according to the python version.

**Operating system** (
Linux (Ubuntu 18.04)

**Comment by akelad** [comment]
@bheemlabs this seems to be an issue with weatherbot so please open an issue on that repo. Looks like you have a very old verison of rasa installed, so i'd say update those and also python 2.7 isn't support anymore
