### ISSUE TITLE
Have problem about formaction with chitchat

### ISSUE THREAD

**Issue by red-frog** [RasaHQ/rasa_nlu#3184]
**Rasa version**:

Rasa NLU: 0.14.4
Rasa core: 0.13.5

**Python version**: 
3.6.7

**Operating system** (windows, osx, ...):

ubuntu 16.04

**Issue**:

 the bot seems to always predict form_action, even though the intent is identified well as chitchat.

This is s same issue: https://forum.rasa.com/t/how-to-handle-chitchat-while-inside-a-form-action/6141

but i don't think it's a best practice, please help me, Thanks!

**Comment by akelad** [comment]
@red-frog i'm gonna close this and answer on the forum post

**Comment by red-frog** [comment]
Excuse me. Haven't solve it, and i not receive your response.

**Comment by akelad** [comment]
yes you did, we'll continue discussing this on the forum, it's a usage question rather than a bug
