### ISSUE TITLE
required slots informed of before a form is activated do not get validated by the form

### ISSUE THREAD

**Issue by paulaWesselmann** [RasaHQ/rasa_nlu#3194]
In this happy story for example, if the user requests a restaurant by saying:
"I'm looking for a Thai place for 4."
The entities for `[Thai](cuisine)` and `[4](num_people)` are identified correctly. The form is activated and not requesting those slots again, but both vales are not validated by the form.  
```
## happy path
* greet
    - utter_greet
* request_restaurant
    - restaurant_form
    - form{"name": "restaurant_form"}
    - form{"name": null}
    - utter_slots_values
* thankyou
    - utter_noworries
```

**Comment by erohmensing** [comment]
cc #3189

**Comment by akelad** [comment]
closing because it's a duplicate
