### ISSUE TITLE
rasa_core 0.11.3

### ISSUE THREAD

**Issue by rameshJantali3** [RasaHQ/rasa_nlu#3195]
Help : getting below error with Python 3.7 ; rasa_core =0.11.3 tried getting tensorflow 1.10 but not able to find one..
 Could not find a version that satisfies the requirement tensorflow~=1.10 (from
rasa_core==0.11.3) (from versions: )
o matching distribution found for tensorflow~=1.10 (from rasa_core==0.11.3)

**Comment by erohmensing** [comment]
Hi @rameshJantali3, `rasa_core` doesn't yet support python 3.7. Support is coming soon in a future version. Have you thought about creating a virtual environment for your rasa project with python 3.6?
