### ISSUE TITLE
Cors related issue for multiple links access

### ISSUE THREAD

**Issue by manpreetkaurm** [RasaHQ/rasa_nlu#3198]
**Rasa version**: latest stable

**Python version**: 3.6

**Operating system** (windows, osx, ...): windows

**Issue**: 
I am running my rasa chatbot using this command:

python -m rasa_core.run --enable_api --cors http://pnv6s1693:7001  http://pnv6s1693:3001 http://pnv6w278:3001 http://pnv6w278:7001 -d models/current/dialogue -u models/current/nlu -o out.log 

The links in the cors attribute, works for one link but not the the other simultaneously. 

One of the links always gives a cors issue:

Error: Access to XMLHttpRequest at 'http://pni6w2868:5005/conversations/infodba/respond' from origin 'http://localhost:3001' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. 

I need to access this for multiple links.
Can you help me with this?

**Content of configuration file (config.yml)**:
```yml

```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml

```

**Comment by akelad** [comment]
Thanks for raising this issue, @erohmensing  will get back to you about it soon.

**Comment by erohmensing** [comment]
@manpreetkaurm have you checked out the input method for `--cors` via the `-h` flag? When I look at it it says that `--cors` is 
> List of domain patterns from where CORS (cross-origin resource sharing) calls are allowed. The default value is `[]` which forbids all CORS requests.

Have you tried passing your urls as a list?

**Comment by manpreetkaurm** [comment]
Passing it as a list worked. Thanks a lot for the help. Would be great if you update this in the documentation, as it is unclear otherwise.

**Comment by digitalWestie** [comment]
Sorry, can you provide an example of the syntax you used? I've been trying various combinations to make a list and nothing works.

**Comment by digitalWestie** [comment]
OK what worked for me in the end was to just drop the brackets etc and space out the domains e.g.  `--cors https://foo.bar.com https://foo2.bar.com`

NB- I'm not sure why but this didn't work at first, but worked after a hard refresh :man_shrugging:
