### ISSUE TITLE
ERROR:rasa_core.training.interactive:An exception occurred while recording messages.

### ISSUE THREAD

**Issue by HovHak** [RasaHQ/rasa_nlu#3212]
**Rasa version**:13.3

**Python version**: 3.6

**Operating system** (windows, osx, ...): windows 10

**Issue**:Hi there so in my previous version of my code I was trying to run a bot with console input channel but then I found out that it was removed from the new rasa core versions, and could not complete my code. Thus I customized it to the new version where i call interactive.run_interactive_learning(agent, training_data_file) instead.  however, i still get an error. P.S I have tried to run it with skipping visualization it does not help.

**Content of domain.yml **:
```yaml
intents:
    - schedule_meeting
    - search_for_meeting
    - greet

entities:
    - meeting
    - time

slots:
    size:
         type: text
    toppings:
        type: text

templates:
    utter_greet:
        - 'Hello, how can I help you?'
        - 'Hi, I am here to help.'
    utter_ask_meeting_day:
        - 'What time would you like me to schedule your meeting?'
    utter_ask_meeting_time:
        - 'What time would you like me to schedule your meeting?'
    utter_get_meeting_time_place:
        - 'here are your meetings for today'
actions:
    - utter_greet
    - utter_ask_meeting_time
    - utter_ask_meeting_day
    - utter_get_meeting_time_place
    - actions.ActionShowMeeting
    
```

**Content of online train **:
```python3
from __future__ import unicode_literals
from __future__ import division
from __future__ import absolute_import

import logging

import agent as agent
import rasa_core
from rasa_core.agent import Agent


#from rasa_core.channels.console import ConsoleInputChannel
from rasa_core.interpreter import RegexInterpreter
from rasa_core.policies.keras_policy import KerasPolicy
from rasa_core.policies.memoization import MemoizationPolicy

from rasa_core.train import interactive
from rasa_core.utils import EndpointConfig
from rasa_core import config as policy_config
from rasa_core.interpreter import RasaNLUInterpreter

logger = logging.getLogger('__name__')


def run_hovo( interpreter, domain_file='chat_domain.yml'):
    policies = policy_config.load("./policies.yml")

    action_endpoint = EndpointConfig(url="http://localhost:5055/webhook")
    agent = Agent(domain_file, policies=policies, interpreter = interpreter, 
    action_endpoint=action_endpoint)
    training_data_file = agent.load_data('./stories.md')

    #rasa_core.run.serve_application(agent, channel='cmdline')
    #agent.train_online(training_data_file, augmentation_factor = 50)
    agent.train(training_data_file)
    interactive.run_interactive_learning(agent, training_data_file)
    return agent


if __name__ == '__main__':
    logging.basicConfig(level='INFO')
    nlu_interpreter = RasaNLUInterpreter('./models/nlu/default/MyNLU')
    run_hovo(nlu_interpreter)

    #dialogue_path = './models/dialogue'

```

**Content of error** (if used & relevant):
```
INFO:rasa_nlu.components:Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Processed Story Blocks: 100%|██████████| 1/1 [00:00<00:00, 1001.74it/s, # trackers=1]
Processed Story Blocks: 100%|██████████| 1/1 [00:00<00:00, 890.70it/s, # trackers=1]
Processed Story Blocks: 100%|██████████| 1/1 [00:00<00:00, 523.90it/s, # trackers=1]
Processed Story Blocks: 100%|██████████| 1/1 [00:00<00:00, 1105.80it/s, # trackers=1]
2019-04-05 19:16:23.084702: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
masking (Masking)            (None, 5, 19)             0         
_________________________________________________________________
lstm (LSTM)                  (None, 32)                6656      
_________________________________________________________________
dense (Dense)                (None, 12)                396       
_________________________________________________________________
activation (Activation)      (None, 12)                0         
=================================================================
Total params: 7,052
Trainable params: 7,052
Non-trainable params: 0
_________________________________________________________________
INFO:rasa_core.policies.keras_policy:Fitting model with 13 total samples and a validation split of 0.1
Epoch 1/100

... train Keras ...

13/13 [==============================] - 0s 239us/step - loss: 1.2922 - acc: 0.5385
INFO:rasa_core.policies.keras_policy:Done fitting keras policy model
Processed actions: 13it [00:00, 12695.22it/s, # examples=13]
INFO:rasa_core.training.interactive:Rasa Core server is up and running on http://localhost:5005
Bot loaded. Visualisation at http://localhost:5005/visualization.html.
Type a message and press enter (press 'Ctr-c' to exit). 
ERROR:rasa_core.training.interactive:An exception occurred while recording messages.
Traceback (most recent call last):
  File "C:\Users\ferar\Desktop\FYP\V2\venv\lib\site-packages\rasa_core\training\interactive.py", line 1199, in record_messages
    use_story_concatenation=False,
  File "C:\Users\ferar\Desktop\FYP\V2\venv\lib\site-packages\rasa_core\training\__init__.py", line 48, in load_data
    exclusion_percentage=exclusion_percentage)
  File "C:\Users\ferar\Desktop\FYP\V2\venv\lib\site-packages\rasa_core\training\__init__.py", line 28, in extract_story_graph
    exclusion_percentage=exclusion_percentage)
  File "C:\Users\ferar\Desktop\FYP\V2\venv\lib\site-packages\rasa_core\training\dsl.py", line 164, in read_from_folder
    if not os.path.exists(resource_name):
  File "C:\Python36\lib\genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not list

Process finished with exit code 0
```

**Comment by erohmensing** [comment]
Hmm, this is a strange issue. One way to test if it's your python code or the source code thats causing problems would be to try to run interactive learning from the command line -- the commands to do so can be found [here](https://rasa.com/docs/core/interactive_learning/). Can you try that and let me know the result?

**Comment by HovHak** [comment]
> Hmm, this is a strange issue. One way to test if it's your python code or the source code thats causing problems would be to try to run interactive learning from the command line -- the commands to do so can be found [here](https://rasa.com/docs/core/interactive_learning/). Can you try that and let me know the result?


hi thanx for coming back to me i tried yo do as you told me but started getting different error please chek below
![Capture](https://user-images.githubusercontent.com/48651497/55674257-f97dcf80-58a9-11e9-9e89-a992c8549959.PNG)

I am at last step this and after when I am done creating online trainer i aim to create a nice UI to chat with chatbot if you have any suggestions please feel free to share as well

**Comment by erohmensing** [comment]
The error I see here is that it's not finding your NLU directory `models\\nlu\\deffault\\MyNLU\\metadata.json` -- notice that `deffault` is spelled incorrectly and not the same as in your code -- try fixing that and re-running the command :)

**Comment by HovHak** [comment]
> The error I see here is that it's not finding your NLU directory `models\\nlu\\deffault\\MyNLU\\metadata.json` -- notice that `deffault` is spelled incorrectly and not the same as in your code -- try fixing that and re-running the command :)

it worked on cmd, I am sorry for this mistake  ( i am not using cmd usually)  for the online training i am running on python code on Pycharm do you see any major issues that i should change in my code to make it work through Pycharm? and as for the UI would u please give me any advice on which API's or interfaces are best to use with RASA?. again thank you very much for coming back to me

**Comment by erohmensing** [comment]
Hmm, okay. First of all we might get some more helpful info if you change `logging.basicConfig(level='INFO')` to `logging.basicConfig(level='DEBUG')`. 

The issue I believe is that the `training_data_file` you're passing to isn't a string filename, but the output of the `agent.load_data()` function (a list). The agent has already been trained on the stories, so you don't have to pass them. Can you try just 
```
interactive.run_interactive_learning(agent)
```
and see if that works?

**Comment by HovHak** [comment]
> Hmm, okay. First of all we might get some more helpful info if you change `logging.basicConfig(level='INFO')` to `logging.basicConfig(level='DEBUG')`.
> 
> The issue I believe is that the `training_data_file` you're passing to isn't a string filename, but the output of the `agent.load_data()` function (a list). The agent has already been trained on the stories, so you don't have to pass them. Can you try just
> 
> ```
> interactive.run_interactive_learning(agent)
> ```
> and see if that works?

worked! thank you very much

**Comment by erohmensing** [comment]
Awesome 🚀

**Comment by anilpankaj** [comment]
Traceback (most recent call last):
  File "dialogue_management_model.py", line 15, in <module>
    from rasa_core.train import interactive
ImportError: cannot import name 'interactive'

When i run this code that's i mention below, i sow that's error what i do? please help 

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

import logging
import warnings
import ruamel.yaml
warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

from rasa_core.agent import Agent
from rasa_core.policies import FallbackPolicy, KerasPolicy, MemoizationPolicy
from rasa_core.interpreter import RasaNLUInterpreter
from rasa_core.train import interactive
from rasa_core.utils import EndpointConfig

logger = logging.getLogger(__name__)


# this will catch predictions the model isn't very certain about
# there is a threshold for the NLU predictions as well as the action predictions
fallback = FallbackPolicy(fallback_action_name="utter_unclear",
                          core_threshold=0.2,
                          nlu_threshold=0.1)

def train_dialogue(interpreter,domain_file = 'domain.yml',
                   model_path = './models/dialogue',
                   training_data_file = './data/stories.md'):

    #action_endpoint = EndpointConfig(url="http://localhost:5055/webhook")
    agent = Agent(domain_file, policies=[MemoizationPolicy(), KerasPolicy(), fallback])
    training_data = agent.load_data('./data/stories.md')

    agent.train(
            training_data)

    agent.persist('models/dialogue')
    return agent




def run_weather_bot(serve_forever=True):
    nlu_interpreter = RasaNLUInterpreter('./models/nlu/default/current')
    action_endpoint = EndpointConfig(url="http://localhost:5055/webhook")
    agent = Agent.load('./models/dialogue', interpreter=nlu_interpreter, action_endpoint=action_endpoint)
    #rasa_core.run.serve_application(agent ,channel='cmdline')
    
    return agent

if __name__ == '__main__':
    train_dialogue(interpreter=RasaNLUInterpreter)
    run_weather_bot()

**Comment by erohmensing** [comment]
@anilpankaj please create a post on the [forum](http://forum.rasa.com) with this question.
