### ISSUE TITLE
tensorflow version incompatible with rasa core

### ISSUE THREAD

**Issue by karthikbalu** [RasaHQ/rasa_nlu#3213]
**Rasa version**: Not installed yet

**Python version**: 3.6.7

**Operating system** (windows, osx, ...): Ubuntu

**Issue**:  Could not find a version that satisfies the requirement tensorflow==1.12.0 (from -r requirements.txt (line 16)) (from versions: )
No matching distribution found for tensorflow==1.12.0 (from -r requirements.txt (line 16))

I have made sure to use Python version 3.6 and still getting this error

Im using Tensorflow 1.13.1

Please help, all other issues mentions us to use python3 3.6 but could this be due to higher tensorflow version?
Thanks

**Comment by erohmensing** [comment]
Correct, you'll need that version of tensorflow. Are you able to successfully download it using

**Comment by karthikbalu** [comment]
The problem is im using Jetson Nano it comes with its own latest tensorflow version 1.13 compiled for GPU cuda cores to perform better than on cpu

Hmm, How to solve this? Please Help!

**Comment by erohmensing** [comment]
Well rasa currently doesn't yet support tf 1.13.1 (i believe that support will come with python 3.7 support in the future), so if you can't change it, you're pretty much at a standstill. Is it possible for you to create a virtual environment with tf 1.12.0?

**Comment by karthikbalu** [comment]
Does Rasa support python version 3.5? as tensorflow gpu doesnot support python 3.6 unfortunately :(

**Comment by erohmensing** [comment]
Yes, both rasa_core and rasa_nlu support python 3.5. Which versions of rasa_core and rasa_nlu are you looking to download?

**Comment by karthikbalu** [comment]
The Latest core 0.13.7 and nlu 0.14.6, does it support version python 3.5?

**Comment by erohmensing** [comment]
Yes

**Comment by testforpepper** [comment]
Hi @karthikbalu, did you manage to make it work? :)

**Comment by rehnakamil89** [comment]
i need to know the rasa requirements for windows 10
please specify
