### ISSUE TITLE
Rasa core doesn't call a custom action server to run a custom TwoStageFallbackPolicy.

### ISSUE THREAD

**Issue by iHamed** [RasaHQ/rasa_nlu#3221]
**Rasa version**:

rasa-core                      0.13.7  
rasa-core-sdk               0.12.1   
rasa-nlu                        0.14.6

**Python version**:  Python 3.6.8

**Issue:**
Custom action server is up and running, but Rasa core doesn't call the custom action server in the cases of TwoStageFallbackPolicy. I use the custom action just for fallback policy. Rasa core works fine and response correctly to user input. But fail to follow a custom TwoStageFallbackPolicy and uses the default TwoStageFallbackPolicy. The action server used to work fine and stopped after I updated rasa-core to 0.13.7 and rasa-nlu to 0.14.6.  I can't remember the last version that used before, but certainly, it's around 0.13.0 when TwoStageFallbackPolicy is introduced.

Some notes:
- I retrained the agent with action_endpoint and without it. But still the same issues. Agent(...,action_endpoint=EndpointConfig(url="http://localhost:5055/webhook"))
- The action server still won't get called if I use command line or connectors (REST or Slack) to run the agent. 

I run the action server using this command on the directory of actions.py file

```yml
python -m rasa_core_sdk.endpoint --actions actions
```

 I run  Rasa Core as REST API using this command 
```yml
python -m rasa_core.run -c rest -d models/dialogue/default/dialogue_model -u models/nlu/default/nlu_model --endpoints endpoints.yml --credentials credentials.yml --log_file rest_serverlog.log --enable_api --debug
```

I tested the action server and it's up. and I sent a direct post request to http://localhost:5055/webhook with JSON in the action request format following the doc, and I got a valid response. The output of the terminal  running the action server after sending a direct post

```yml
INFO:__main__:Starting action endpoint server...
INFO:rasa_core_sdk.executor:Registered function for 'action_default_fallback'.
INFO:rasa_core_sdk.executor:Registered function for 'action_default_ask_affirmation'.
INFO:__main__:Action endpoint is up and running. on ('0.0.0.0', 5055)
127.0.0.1 - - [2019-04-08 14:23:21] "GET /health HTTP/1.1" 200 124 0.001861
127.0.0.1 - - [2019-04-08 14:23:35] "GET /health HTTP/1.1" 200 124 0.001435
127.0.0.1 - - [2019-04-08 14:24:08] "GET /health HTTP/1.1" 200 124 0.001212
DEBUG:rasa_core_sdk.executor:Received request to run 'action_default_fallback'
DEBUG:rasa_core_sdk.executor:Successfully ran 'action_default_fallback'
127.0.0.1 - - [2019-04-08 14:24:30] "POST /webhook HTTP/1.1" 200 244 0.001706
```

The content of endpoints.yml file :
```yml
action_endpoint:
  url: "http://localhost:5055/webhook"
```

The content of credentials.yml file :
```yml
rest:
  # you don't need to provide anything here - this channel doesn't
  # require any credentials
```

I train the agent using the following parameters

```py
fallback = TwoStageFallbackPolicy(fallback_nlu_action_name="action_default_fallback", fallback_core_action_name = "action_default_fallback",
                                        deny_suggestion_intent_name= "out_of_scope",
                          core_threshold=0.3, nlu_threshold=0.6)

agent = Agent(domain_file, policies=[MemoizationPolicy(max_history=3),
                                        KerasPolicy(epochs=300, batch_size=50, validation_split=0.2, max_history=3),
                                        fallback]) # action_endpoint=EndpointConfig(url="http://localhost:5055/webhook") 
```

Thanks for the wonderful work that you are doing.

**Comment by akelad** [comment]
Thanks for raising this issue, @wochinge will get back to you about it soon.

**Comment by iHamed** [comment]
`- action_default_fallback
- action_default_ask_affirmation`

**Comment by iHamed** [comment]
The issue was resolved by adding Rasa default actions to the domain file.

```yml
action:
- action_default_fallback
- action_default_ask_affirmation
```

As far as I know, this is not explicitly mentioned in the documentation of the custom actions section or Two-stage Fallback Policy.

**Comment by akelad** [comment]
if you've written your own actions for this then that is expected -- they're just normal custom actions
