### ISSUE TITLE
RASA_NLU performance really bad with faq data.

### ISSUE THREAD

**Issue by rachitbshephertz** [RasaHQ/rasa_nlu#3224]
Rasa version: 0.14.6

Python version: 3.6

Operating system: Windows

Issue: RASA_NLU performance really bad with faq data.

I am in the process of developing faq bot with around 250 unique QNAs. I am using tensorflow pipeline but its results are really bad.

I am open to providing the dataset privately to get the best possible pipeline. I am also not sure if rasa is a good fit for faq bots but I am a big advocate of rasa framework in general, So I would really want to make this work. Any help will be greatly appreciated. 

**Content of configuration file (config.yml)**:
language: "en"

pipeline:
- name: "tokenizer_whitespace"
- name: "intent_featurizer_count_vectors"
  token_pattern: '(?u)\b\w+\b'
  max_ngram: 2
- name: "intent_entity_featurizer_regex"
- name: "intent_classifier_tensorflow_embedding"

**Comment by akelad** [comment]
how many examples do you have per intent? we're actually currently researching how we can do faqs/chitchat better

**Comment by rachitbshephertz** [comment]
Per intent, I have just one example as of now. I understand that for every intent at least 3 examples are required, but for me, this will be at least a 2-day exercise and I am not sure even then it will be very accurate to take into production.

**Comment by diegoami** [comment]
3 examples per intent ? With so many QNAs you are going to need much more IMHO, like 20 or even better 50 per intent. 
The problem for me is Q&A do not map well into "intents". Intent is something users want to do, like book a trip or order a table. On the other hand, two separate, but similar questions might mean to the same intent.
For instance the questions: _Where can I open an account ? How can I open an account?_ are the same "intent" (open an account) but require two separate answers. Good luck training that. 

I would think about alternative approaches: merging some of your questions and/or force users into "paths" by selection of multiple choices.

**Comment by rachitbshephertz** [comment]
I absolutely get your point. With the approaches you suggested I can merge few question but I would still be left with way too many faqs. The other option is not feasible for me. 
I have worked with Microsofts qnamaker in the past and it works really really well but again I can only use open source frameworks.
Any other approaches you have in mind which I can give a try?

**Comment by akelad** [comment]
yeah you should probably have more examples per intent for now. Like i mentioned we're working on something for chitchat/FAQs in general though, we'll let everyone know when that work is ready. I'm going to close this issue in the meantime because it's more of a usage question, and those should be posted in our [forum](https://forum.rasa.com)

**Comment by RajithaFernando** [comment]
i am a newbie to rasa but i may have few suggestions for you. you can use [Chatito ](https://rodrigopivi.github.io/Chatito/) https://rodrigopivi.github.io/Chatito/ to generate more data. and also, i think you can reduce number of intents using slots. for example, there may be questions like _Where can I open an account ? How can I open an account?_. both of these intents can be taken into one intent and fill categorical slot as **How, Where** ... etc. then after you can write stories depend on the slot value, and pass different utter messages. hope this help someone if there is any mistake, please reply.
