### ISSUE TITLE
Slot updation on user utterance

### ISSUE THREAD

**Issue by shubhammainali-sdn** [RasaHQ/rasa_nlu#3231]
**Rasa version**:  rasa-core                          0.13.5   
                            rasa-core-sdk                      0.12.2   
                            rasa-nlu                           0.14.4   

**Python version**: 3.7

**Operating system** (windows, osx, ...): Ubuntu

**Issue**:

Hello everyone. In my scenario , I am asking user for the confermation on the values provided. If user denies and want s to update the specific values/slot I’m unable to find solution for this. Thanks.

```

**Comment by akelad** [comment]
Please ask these kind of questions in our [forum](https://forum.rasa.com)
