### ISSUE TITLE
Issue in Custom Action File

### ISSUE THREAD

**Issue by garchaaman19** [RasaHQ/rasa_nlu#3244]
**Rasa version**:
rasa-core                          0.13.7   
rasa-core-sdk                      0.12.2   
rasa-nlu                           0.14.6 
**Python version**: 
Python 3.6.0
**Operating system** (windows, osx, ...):
Kali LInux 2019
**Issue**:

UnboundLocalError: local variable 'response' referenced before assignment
 I am getting this error while running my actions file, The first class is getting executed but not the other classes.

`````
class AdmissionMcs(Action):
	response= " "
	def name(self):
		return 'admission_mcs'
	def run(self,dispatcher,tracker,domain):
		streams=tracker.get_slot('stream')
		if 'streams' == 'msc comp sci' or 'mcs':
			response=""" The admission for MCS is given on basis of 50% marks of bcs and 50% marks of entrance"""
		dispatcher.utter_message(response)
		return [SlotSet('stream',streams)]

class AdmissionBcs(Action):
	response=" "
	def name(self):
		return 'admission_bcs'
	def run(self,dispatcher,tracker,domain):
		streams=tracker.get_slot('stream')
		if 'streams' == 'bcs' or 'bsc comp sci':
			response=""" The admission for BCS is given on basis of entrance exam conducted by college"""
		dispatcher.utter_message(response)
		return [SlotSet('stream',streams)]

class AdmissionBba(Action):
	response= None
	def name(self):
		return 'admission_bba'
	def run(self,dispatcher,tracker,domain):
		streams=tracker.get_slot('stream')
		if 'streams' == 'bba':
			response=""" The admission for BBA is given through merit list on basis of 12th Marks """
		dispatcher.utter_message(response)
		return [SlotSet('stream',streams)]

class AdmissionMba(Action):
	response=" "
	def name(self):
		return 'admission_mba'
	def run(self,dispatcher,tracker,domain):
		streams=tracker.get_slot('stream')
		if 'streams' == 'mba':
			response=""" The admission for MBA is given through marks scored in CAT """
		dispatcher.utter_message(response)
		return [SlotSet('stream',streams)]

```
after i added response="  " the second class also started working, But not the further classes.
Its throwing me error in action server terminal
UnboundLocalError: local variable 'response' referenced before assignment

```

**Content of configuration file (config.yml)**:
```
{
"pipeline":"spacy_sklearn",
"path":"./models/nlu",
"data":"./data/data.json"
}
```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml

```

```

**Comment by tahamr83** [comment]
I would suggest moving the response variable inside your `run` method. You should use it as a local variable not a class variable. If you want to access it as you did you would do it like this `AdmissionMcs .response`

**Comment by garchaaman19** [comment]
No brother its not working, i will show you some changes,
Its giving me a blank output when i do this , i had first put, response="
", at that time also same blank output and even when i declared it inside
my run func its giving me a blank output.

On 11-Apr-2019 11:34 pm, "tahamr83" <notifications@github.com> wrote:

I would suggest moving the response variable inside your run method. You
should use it as a local variable not a class variable. If you want to
access it as you did you would do it like this AdmissionMcs .response

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/RasaHQ/rasa_nlu/issues/3244#issuecomment-482229969>,
or mute
the thread

**Comment by garchaaman19** [comment]
Please give me URGENT REPLY,its not working. I need it urgently.

**Comment by garchaaman19** [comment]
@akelad

**Comment by garchaaman19** [comment]
> I would suggest moving the response variable inside your `run` method. You should use it as a local variable not a class variable. If you want to access it as you did you would do it like this `AdmissionMcs .response`

Its giving me a blank output if i create an object of class.

**Comment by akelad** [comment]
I don't think this is a rasa related issue, but something with the way you've written your actions. If the `if` statement conditions aren't met, the `response` variable doesn't exist. You should add an `else` statement and assign the variable a value there as well.
In any case, this seems like a usage question so please ask any further questions in our [forum](https://forum.rasa.com)

**Comment by garchaaman19** [comment]
Alright I will put this on forum as well but ,only two classes are getting executed every time, even if changed the sequence of those two classes( i.e. at first they were defined at top of program), then also only those two classes are getting executed not the other classes.

**Comment by garchaaman19** [comment]
ok the error is solved i had put a else statement and put the message in else which i want to execute and now it's working,
thank you.
But i don't understand the logic behind putting the else statement?

**Comment by akelad** [comment]
well, why would you not put an else statement? If the condition doesn't match then the response variable doesn't get assigned and therefore there will be no variable of that name, meaning your code will error
