### ISSUE TITLE
how to handle wrong intent 

### ISSUE THREAD

**Issue by MaulishShah** [RasaHQ/rasa_nlu#3247]
**Rasa version** :13.04

**Python version**: 3.6.5

**Operating system** (windows, osx, ...):  Linux

**Issue**:
Can you suggest about rasa chatbot, how to handle an unknown question which enters by the user which would be not trained and getting random intent with it.

```

**Comment by Pennsy** [comment]
I am also facing the similar problem and looking for solutions...Although a threshold is set. Some user input with partial common parts with trained intents will easily get a confidence score higher than the threshold, also higher than completely new inputs. 

The problem does not only occur in rasa nlu, but it is also a common issue for intent classification. One approach is to add out-of-scope examples, and you may need to add a variety of examples for every unclassified intent you met.

**Comment by akelad** [comment]
Please ask these kind of questions in our [forum](https://forum.rasa.com)
