### ISSUE TITLE
Implement several CRF architectures

### ISSUE THREAD

**Issue by careless25** [RasaHQ/rasa_nlu#3255]
This repo here: https://github.com/guillaumegenthial/tf_ner
has a few improvements with the CRF implementation. Could this be something that could be implemented into the Rasa pipeline?

**Comment by akelad** [comment]
Thanks for the suggestion! We've been thinking of using tf for NER for a while now. @Ghostvv can you take a look into this repo and see if it would be worth it?

**Comment by Ghostvv** [comment]
thank you for the link. Unfortunately, we cannot use this library directly because we have custom featurizers, but as mentioned we have a plan to evaluate TensorFlow `crf`.
I'll close this issue for now, please feel free to reopen it
