### ISSUE TITLE
Try to see the the intermediate results of the Rasa_nlu pipeline

### ISSUE THREAD

**Issue by bofengshuimen77** [RasaHQ/rasa_nlu#3264]
**Rasa-nlu version**:0.14.6
**rasa-core version**:0.13.4

**Python version**: 3.6.5

**Operating system** (windows, osx, ...):windows 10

**Issue**:
I want to study the NLU pipeline, and output the intermediate results of each step of the pipeline. For example, I want to get the results after tokenizer or the component about feature extraction, and directly analyze the intermediate results, what should I do?

**Content of configuration file (config.yml)**:
```yml

```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml

```

**Comment by akelad** [comment]
Please ask these kind of questions in our [forum](https://forum.rasa.com)

**Comment by bofengshuimen77** [comment]
OK. Thank you for your reply. I have downloaded the code of rasa_nlu from github. And I directly modify the source code to output the intermediate results. This issue has been resolved now.
