### ISSUE TITLE
# questions/suggestion/requests: checkpoints, training parameters, literature

### ISSUE THREAD

**Issue by alexDeCastroAtGit** [RasaHQ/rasa_nlu#330]
Hi there,
thanks for the great product you guys are developing. 

Questions: 
1. Is there an option for model checkpoints? Scenario: I'm training a model (which could take hours) but I'd like to check every now and then how the model is behaving so far. 

2. I haven't seen (yet) where to tweak/gauge training parameters such as C, f-score (e.g. stop training after the deltas in f or C are below a certain threshold). Perhaps I've missed that in the documents? 

3. Documentation is good. Perhaps you guys could raise some Jira tickets specific to documentation points you'd like to improve, and then the community could help. I think I've seen in one of the previous issues a remark about folder tree structure when training a new model. (I'm hacking my way through it.) 

Any remarks on how entities can improve the quality of the model? 

4. Is there a bibliography session where the source code/academic references for the ML algos and source code is available? 

I'm still in doubt about which scikit-learn sublibraries are being used. Again, I'm hacking my way though the code. 

Thanks for your help and time. Let me know how I can help too, Alex

 

**rasa NLU version** (e.g. `0.7.3`):
- latest

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...):
- mities

**Operating system** (windows, osx, ...):
- osx

**Issue**:

**Content of configuration file** (if used & relevant):
```json

```

**Comment by twerkmeister** [comment]
Hey Alex,

thank you for reaching out and offering help. You raise some good questions. Unfortunately, there is no support for model checkpoints nor tweaking of the parameters through configuration possible yet. For some models, such as `ner_crf` you can easily adjust parameters in the source code though. 

The entity extractor models improve by having more entities available. But the intent classifiers are not using any entity related features yet. Certainly an improvement for the future, just as your proposal of adding some bibliography for the ML models we are using!

I getting familiar with many of the processes right now and I am trying to figure out how to better include the community. I'll get back to you soon :+1:

**Comment by alexDeCastroAtGit** [comment]
Thanks Thomas! Glad to help.

**Comment by tmbo** [comment]
I'll close this due to inactivity. Let me know if there are any further questions.
