### ISSUE TITLE
Add additional API endpoints

### ISSUE THREAD

**Issue by paschmann** [RasaHQ/rasa_nlu#334]
It would be helpful if the HTTP API had additional endpoints, these could include:

- [x] Rasa version - Merged in #338 
- [x] Current loaded configuration - Merged in #338
- [ ] Server log
- [ ] Request log

As mentioned by @alexDeCastroAtGit in https://github.com/golastmile/rasa_nlu/issues/332 

- [x] it would also be useful to return the training status/progress

**Comment by paschmann** [comment]
@tmbo @amn41 - I have these developed, if you would like to assign to me.

**Comment by amn41** [comment]
great! Please open a PR & we can discuss

**Comment by wrathagom** [comment]
It looks like config and version were merged, but I don't see anything for the logs. I'll leave it open for those two pieces of functionality unless they won't be implemented then I'll close.

**Comment by tmbo** [comment]
i'll close this in favor of https://github.com/RasaHQ/rasa_nlu/issues/1306
