### ISSUE TITLE
Improve logging content

### ISSUE THREAD

**Issue by paschmann** [RasaHQ/rasa_nlu#335]
Currently events are logged in different formats between the response/request logs and the server log. Also currently the events are not timestamped, making it difficult to know when they occurred.

**Comment by PHLF** [comment]
One very important feature, for the logs to be useful, would be to have a log for each running rasa model: see `server_model_dirs` config variable.

**Comment by tmbo** [comment]
I will close this for now as both timestamp and model name should be part of the log now.
