### ISSUE TITLE
Training doesn't end

### ISSUE THREAD

**Issue by sankethpb** [RasaHQ/rasa_nlu#340]
**rasa NLU version** (e.g. `0.7.3`): 0.8.0a17 (latest from master), Python 3.6 64bit

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...): spacy_sklearn
Spacy version: 1.8.2
Scikit-learn version: 0.18.1

**Operating system** (windows, osx, ...): Windows 7 64bit

**Hardware**:  i7 4790 CPU, 3.60GHz dual core processor with 16GB Ram
CPU consumption 85% to 100%

**Issue**:
Training started but doesn't end even after 12hours. It is stuck at below step and also shows incorrect remaining time.
Trial1: ![Console output](https://cdn.pbrd.co/images/2GyBGnH7l.png)
Trial2:
```
E:\Projects\source\RasaNLUTraining>python -m rasa_nlu.train -c config_spacy.json
DEBUG:pip.vcs:Registered VCS backend: git
DEBUG:pip.vcs:Registered VCS backend: hg
DEBUG:pip.pep425tags:Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
DEBUG:pip.pep425tags:Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
DEBUG:pip.pep425tags:Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
DEBUG:pip.pep425tags:Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
DEBUG:pip.vcs:Registered VCS backend: svn
DEBUG:pip.vcs:Registered VCS backend: bzr
INFO:root:Trying to load spacy model with name 'en'
INFO:root:Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
INFO:root:Training data format at ./data/eva_intents_new.json is rasa_nlu
DEBUG:root:Validating training data...
INFO:root:Training data stats:
        - intent examples: 45483 (3 distinct intents)
        - found intents: intent1, intent2, intent3
        - entity examples: 45360 (1 distinct entities)
        - found entities: entity1

INFO:root:Starting to train component nlp_spacy
INFO:root:Finished training component.
INFO:root:Starting to train component ner_spacy
INFO:root:Finished training component.
INFO:root:Starting to train component ner_synonyms
INFO:root:Finished training component.
INFO:root:Starting to train component intent_featurizer_spacy
INFO:root:Finished training component.
INFO:root:Starting to train component intent_classifier_sklearn
Fitting 5 folds for each of 6 candidates, totalling 30 fits
```
**Content of configuration file** (if used & relevant):
```json
{
  "name": "mymodel",
  "num_threads": 20,
  "pipeline": "spacy_sklearn",
  "path" : "./models",
  "data" : "./data/myintents.json",
  "log_level": "DEBUG"
}
```
Thanks in advance.

**Comment by twerkmeister** [comment]
Hey @sankethpb, how about the memory consumption? If you hit full memory that might effectively get the training to stop. I would try to run the training with less threads, probably 4, since your cpu likely can only execute that many simultaneously.

**Comment by sankethpb** [comment]
@twerkmeister @tmbo I tried already with 4 threads, 6 etc, finally it stops at Intent classifier sklearn

**Comment by twerkmeister** [comment]
@sankethpb could you try it with the new `0.8.5` version?

**Comment by sankethpb** [comment]
@twerkmeister @tmbo I tried with 0.8.5 and had the same issue on the i7 machine with 16GB RAM.
Finally I used a Azure Ubuntu VM - Standard DS15 v2 (20 cores, 140 GB memory). With this it took around 30mins, I used 15 threads. I am not sure if such high performance machines are really required or if something is wrong with training data. Any help here would be great. Thanks in advance.

**Comment by sankethpb** [comment]
@tmbo @twerkmeister any inputs here?

**Comment by tmbo** [comment]
Is this still an issue?

**Comment by sankethpb** [comment]
@tmbo On high performance machines, the training works.
Would it be possible to document approximately the required hardware configuration for to process large data?

**Comment by ujja** [comment]
Is it possible to write out an error message if the training is stopped?

**Comment by tmbo** [comment]
In the cases where the training takes long, it usually is not stopped. Rather mitie is trying to train the model while the machine is busy managing its main memory (e.g. constant page faults). So the training is still running but slow as most time is spend getting the data into memory.

**Comment by ujja** [comment]
Im using rasa with mitie in docker. Im calling the train endpoint.

With 4 sentences it finishes fast.

With 42 it is stopped here:
Part II: elapsed time: 14 seconds.
df.number_of_classes(): 4
INFO:root:Finished training component.
INFO:root:Starting to train component ner_synonyms
INFO:root:Finished training component.
INFO:root:Starting to train component intent_classifier_mitie
Training to recognize 12 categories: 'Computer_Crashes', 'General_Greeting', 'Computer_Does_Not_Turn_On', 'Hard_Disk_Fail', 'Monitor_Does_Not_Display', 'Monitor_Black_Borders', 'Mouse_Acting_Erratically', 'Mouse_Wheel_Issue', 'Outlook_Signature_Creation_Support', 'Outlook_Out_Of_Office_message', 'Keyboard_Cleaning', 'Windows_Safe_Mode'
Train classifier
extracting text features
now do training
num training samples: 42

I call the status endpoint, it says i have no training process. I suppose its right, process is died.

**Comment by wrathagom** [comment]
@ujja are you willing to share your training data with us either in a gist or privately via e-mail? I'd like to see the size of it and try to reproduce.

The number of intent training examples seems very high.

**Comment by ujja** [comment]
@wrathagom Does it helps to you? Im just playing with RASA, to see its limits, my training data is not important.

what is the "maximum" of intent training examples? Is the number of intents, or the number of sentences overall important? Or the number of the entities? The average lenghth of the sentences? The "distance" of two intent?

And is it possible that the /status endpoint says i have no running trainings, but this is not right?

Documentation is good for starters, but it is hard to get such informations as this.

**Comment by wrathagom** [comment]
Sorry, didn't realize you weren't the original poster. The OP has 45,000+ Intents and Entities he's the one who's data I really want to see. @sankethpb 

@ujja what is the size of your training data and the size of the machine you are running it on? Also which pipeline are you using?

Unfortunately all of your other questions kind of fall under `model performance` and that is something you have to discover on your own given your use case.

**Comment by sankethpb** [comment]
We recently had a discussion with @amn41 about our training data and we are currently using AWS EC2 instance 4.8x large for the training and works fine so far.

**Comment by omelnikov** [comment]
Why is this issue closed? It still seems to be unresolved. The training still runs forever for logistic regression fitting on a grid, even if the grid is one-dimensional.
