### ISSUE TITLE
Adding custom emulators

### ISSUE THREAD

**Issue by znat** [RasaHQ/rasa_nlu#344]
Is it possible to reference a custom emulator in a JS middleware fashion?
I guess it is always possible to clone and add an emulator class, but it'd be nice to add the flexibility to post-process the code according to anyone's need

**Comment by twerkmeister** [comment]
Interesting idea, could you be more specific at which point you would want to add your specific emulator and what use case you are looking at? The emulators are restructuring the response json - what keeps you from doing that in your application code?

**Comment by znat** [comment]
In my case, modifying the response is exactly what I want. But I guess in some cases you might want to preprocess the data too. For example lowercase all user entries (may be this can be done with a pipeline component). That's what I like with the middleware approach found in many javascript frameworks (e.g express.js). You can chain as many as you want so you have a lot of flexibility to transform incoming and outgoing data

**Comment by akelad** [comment]
@znat would you say this is still relevant?

**Comment by znat** [comment]
@akelad Probably not.
