### ISSUE TITLE
#Question# documentation on using docker

### ISSUE THREAD

**Issue by xliuhw** [RasaHQ/rasa_nlu#352]
I'd like to try to install rasa using docker. I find the instructions on the github site for the installation,
but didn't find the docs on how to use it to train and test. Maybe I missed it somewhere?
It would be great if you could provide a short example on training and testing in docker if this has not been documented. 

Thanks!

```json

```

**Comment by twerkmeister** [comment]
Good point, it's on my list and gonna be available soon :)

**Comment by tmbo** [comment]
I've added this suggestion to the tutorial-wishlist on #278
