### ISSUE TITLE
Sometimes punctuation gets added to an entities value

### ISSUE THREAD

**Issue by znat** [RasaHQ/rasa_nlu#356]
**rasa NLU version**: 0.8.5

**Used backend / pipeline**: npl_spacy, ner_crf,ner_synonyms

**Issue**:
In the sentence **where is the bar?** I would expect the what entity to be **bar** and not **bar?**

```json
{
  "entities": [
    {
      "end": 18,
      "entity": "what",
      "extractor": "ner_crf",
      "start": 13,
      "value": "bar?"
    }
  ],
  "text": "where is the bar?"
}

```

```json
{
  "entities": [
    {
      "end": 16,
      "entity": "what",
      "extractor": "ner_crf",
      "start": 13,
      "value": "bar"
    }
  ],
  "intent": {
    "confidence": 0,
    "name": ""
  },
  "text": "where is the bar"
}
```

**Comment by tmbo** [comment]
This seems to be an issue with the tokenizer, in this case spacy. I am not sure if there is anything we can do about this (other than using a different tokenizer).

**Comment by tmbo** [comment]
I think this got better with the current models, but also there isn't much we can do about this anyways.

**Comment by magdalini-anastasiadou** [comment]
I face the same issue with Rasa 1.10.1
