### ISSUE TITLE
How to find the accuracy of the model for ner_crf

### ISSUE THREAD

**Issue by shuvayan** [RasaHQ/rasa_nlu#366]
Hello,

Going through the documentation I could not find anywhere how to evaluate the model created.
Can someone please help me in this.
I have gone through the source code and it seems the classification_report has to be called but I am not sure how.

**Comment by JoeyFaulkner** [comment]
Thanks for bringing this to our attention, i'll work on a good way of doing this this week and get back to you :)

**Comment by tmbo** [comment]
I will close this one in favor of the more general #248. The goal is to be able to evaluate a processing pipeline to be able to exchange components and try out new things based on easily accessible evaluation results.
