### ISSUE TITLE
response field in output

### ISSUE THREAD

**Issue by gcln** [RasaHQ/rasa_nlu#380]
Is it possible to add multiple response texts for a intent to return one random text in case of a match.  is this feature by any chance part of an upcoming release in near future to both trainer project and nlu output text data.  is there a decent workaround at this time to add response text return results along with entity and intent text.

**Comment by tmbo** [comment]
We are currently working on a dialogue engine that will do just that - keeping track of the dialogue and generate appropriate responses / execute defined actions. So stay tuned 😃

**Comment by andikas** [comment]
@tmbo,

Yeah, I need this too.
Because I migrate from Api.ai and trying to get respose text also.
are you guys still working on it?

Thanks,
Cheers
