### ISSUE TITLE
Incorrectly Detecting Intents

### ISSUE THREAD

**Issue by gkf01** [RasaHQ/rasa_nlu#382]
**rasa NLU version** (e.g. `0.7.3`): 0.9.0a1

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...): spacy_sklearn

**Operating system** (windows, osx, ...): osx

**Issue**:
i am facing a problem with detecting intents. i am importing my data from wit (i am also using the default wit/number entity) and using the latest version of rasa to train (spacy and duckling). However, when i want to detect numbers, an intent is detected (which is not what i need). For example:
```json
[
  {
    "_text":"230",
    "confidence":0.7114206075436571,
    "entities":{
      "number":{
        "confidence":null,
        "end":3,
        "start":0,
        "type":"value",
        "value":230
      },
      "time":{
        "confidence":null,
        "end":3,
        "start":0,
        "type":"value",
        "value":"0230-01-01T00:00:00.000+02:22"
      }
    },
    "intent":"transfer"
  }
]
```
note that when a user types 230, this means he does not want to do a transfer.
I believe rasa's response must be the following:
```json
{
  "text":"230",
  "confidence":0.83553937041636217,
  "intent":"None",
  "entities":[
    {
      "start":0,
      "end":3,
      "value":"230",
      "entity":"number"
    }
  ]
}
```
(the intent field must be empty or has the word None as it used to be in version 0.5).

The training data for a number (example 1) as imported from wit is the following:
```json
{
  "text":"1",
  "entities":[
    {
      "entity":"number",
      "value":"1",
      "start":0,
      "end":1
    }
  ]
}
```
**Content of configuration file** (if used & relevant):
```json
{
  "name": null,
  "pipeline": ["nlp_spacy", "ner_crf", "ner_synonyms", "intent_featurizer_spacy", 
  "intent_classifier_sklearn", "ner_duckling"],
  "language": "en",
  "num_threads": 1,
  "path": "server_models",
  "response_log": "logs",
  "config": "config.json",
  "log_level": "DEBUG",
  "port": 6000,
  "data": "./data/rasawit/expressions.json",
  "emulate": "wit",
  "log_file": null,
  "mitie_file": "data/total_word_feature_extractor.dat",
  "spacy_model_name": null,
  "server_model_dirs": null,
  "token": null,
  "max_number_of_ngrams": 7,
  "duckling_dimensions": ["duration", "email", "number", "time", "timezone"],
  "luis_data_tokenizer": null,
  "entity_crf_BILOU_flag": false,
  "entity_crf_features": [
    [
      "low",
      "title",
      "upper",
      "pos",
      "pos2"
    ],
    [
      "bias",
      "low",
      "word3",
      "word2",
      "upper",
      "title",
      "digit",
      "pos",
      "pos2"
    ],
    [
      "low",
      "title",
      "upper",
      "pos",
      "pos2"
    ]
  ]
}
```

**Comment by tmbo** [comment]
The model will always assign one of the existing intents. The current model isn't able to return `None` as the intent - in its world every message belongs to one of the intents it knows. 

To circumvent that, you can create an intent, e.g. `out_of_scope` and create training examples for this reflecting sentences that should not get any of the other intents assigned. 

I opened a more general feature request #387.
