### ISSUE TITLE
Database to work with rasa_nlu

### ISSUE THREAD

**Issue by SwatiConnasys** [RasaHQ/rasa_nlu#384]
Hi,

Please let me know if this is irrelevant to rasa nlu development.

I am looking to store data which is currently in Natural language form in some database.
Mostly this data is facts like "Roses are red".
Then, when I get a query like "What is the color of a rose?", I want to be able to lookup the database for an answer. I can define intents like "flower-color" and even get the entities extracted out of the user's natural language query. But is there some open source library for databases that work well with the output of rasa nlu's entities and intents? My option is to write SQL query converter from intents and entities of rasa_nlu's query extraction.

Should I also convert the input data like "Roses are red" to entity and intent and then store in the database so when the user queries I can run a direct match to SQL?

**Comment by tmbo** [comment]
So you are concerned with matching the structured output of the message with information stored in a DB to generate a response? We haven't actually had a look at that but there are a lot of published methods in that area (e.g. in the area of Question Answering or Information Retrieval).

Although, this is a fascinating topic and I am interested in that as well, this is somewhat out of scope for the project.

**Comment by akshaydeeti1996** [comment]
So,rasa nlu cannot be used for the information retrieval right?(I mean we cannot use it to ,quey on a large corpus and get a relevant document)
