### ISSUE TITLE
How the ner_mitie component is trained? 

### ISSUE THREAD

**Issue by saimeghanakuchana** [RasaHQ/rasa_nlu#386]
**rasa NLU version** (e.g. `0.7.3`):

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...):
mitie 

**Operating system** (windows, osx, ...):

**Issue**:

**Content of configuration file** (if used & relevant):
```json

```
Hi, 
Im doing the training using mitie backend in the debugging mode. By stepping in line to line, I have reached a point where there is breakpoint. 
![screen shot 2017-05-23 at 14 22 21](https://cloud.githubusercontent.com/assets/10760836/26346009/7c7af7da-3fc2-11e7-9c69-495e764505aa.png)
The console output is the one shown in the figure. 
However on running the line, 
 "obj = ctypes.c_void_p(_f.mitie_train_named_entity_extractor(self.__obj))"
![screen shot 2017-05-23 at 14 25 15](https://cloud.githubusercontent.com/assets/10760836/26346141/e3999548-3fc2-11e7-8959-8d12aa4747e4.png)

![screen shot 2017-05-23 at 14 25 25](https://cloud.githubusercontent.com/assets/10760836/26346197/12a3c368-3fc3-11e7-85bc-c719f75b087d.png)
This is my console output. I'm unable to understand what is happening in the code [there is no indication in the entire project how the f-score and the losses are calculated]

**Comment by tmbo** [comment]
mitie is implemented in C, hence the code you are referring to is written there in the mitie repository: 
https://github.com/mit-nlp/MITIE
