### ISSUE TITLE
Returned json on train API endpoint doesn't contain PID

### ISSUE THREAD

**Issue by wrathagom** [RasaHQ/rasa_nlu#391]
**rasa NLU version** (e.g. `0.7.3`): 0.8.6 and master

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...): mitie

**Operating system** (windows, osx, ...): Custom docker image https://github.com/samtecspg/rasa-api/tree/RASA_0.8.6_full

**Issue**: 

I am fairly certain the `/train` endpoint should return he actual pid instead it returns:
```
{
	"info": "training started. Current pids: [<Process(Process-1, started)>]"
}
```

**Comment by wrathagom** [comment]
@tmbo confirmed that I was off by a bit. I was running 0.8.6, which I thought was farther along than what it is. but I've confirmed that the /train endpoint still just returns the above in 0.8.6 and master. Which I believe is still a legitimate regression?

**Comment by tmbo** [comment]
Yes, that is still a regression :+1: thanks for reporting it.
