### ISSUE TITLE
loss function ? 

### ISSUE THREAD

**Issue by saimeghanakuchana** [RasaHQ/rasa_nlu#392]
Hi, 
what is the algorithm and loss function used in this project?

**Comment by tmbo** [comment]
Please be a bit more specific - we use several different machine learning algorithms for different use cases.

**Comment by saimeghanakuchana** [comment]
Hi, 
In the mitie_intent_classifier, which loss function and algorithm are we using ?

**Comment by tmbo** [comment]
The mitie intent classifier is a multiclass sparse linear SVM. I think it uses the squared hinge loss, but would need to double check.
