### ISSUE TITLE
Improve Tutorial Training Data Example

### ISSUE THREAD

**Issue by aep** [RasaHQ/rasa_nlu#394]
**rasa NLU version**: 0.8.6

**Used backend / pipeline** : spacy_sklearn

**Operating system**: linux, python 3.6.1

**Issue**:

following http://rasa-nlu.readthedocs.io/en/stable/tutorial.html  verbatim with the example dataset,
will not actually result in the output show in that tutorial.

```
curl -XPOST localhost:5000/parse -d '{"q":"I am looking for Chinese food"}' | python -mjson.tool
{
    "entities": [],
    "intent": {
        "confidence": 0.7634807603171528,
        "name": "restaurant_search"
    },
    "intent_ranking": [
        {
            "confidence": 0.7634807603171528,
            "name": "restaurant_search"
        },
        {
            "confidence": 0.09409877789444974,
            "name": "goodbye"
        },
        {
            "confidence": 0.0940900289610396,
            "name": "greet"
        },
        {
            "confidence": 0.04833043282735786,
            "name": "affirm"
        }
    ],
    "text": "I am looking for Chinese food"
}
```
doesn't look like an actual bug, probably just not enough data.
However, this is confusing when it's the very first tutorial.

**Comment by tmbo** [comment]
Yes you are right there, it is due to a lack of training data. The training data set for the tutorial is rather small (to speed up the training and because it is part of the git repository). 

Open to suggestions on how to improve here (ideas or a PR 😉).

**Comment by jithurjacob** [comment]
Have we added  Word2vec to Rasa like this article.

https://medium.com/rasa-blog/do-it-yourself-nlp-for-bot-developers-2e2da2817f3d

**Comment by tmbo** [comment]
I don't quite get your question, can you please elaborate what you mean please?
