### ISSUE TITLE
Complete renaming Lastmile -> Rasa

### ISSUE THREAD

**Issue by tmbo** [RasaHQ/rasa_nlu#396]
I think I covered most of the things (gitter & readme). Things left:

- [ ] replace occurrences in documentation

**Comment by patlachance** [comment]
Hi, The Gitter chat link in the FAQ (https://rasa-nlu.readthedocs.io/en/stable/faq.html#which-languages-are-supported) is wrong.

**Comment by tmbo** [comment]
done
