### ISSUE TITLE
multi models and multi agent support for rasa in single deployment

### ISSUE THREAD

**Issue by pvagare** [RasaHQ/rasa_nlu#400]
As we know in the api.ai we have different agent and different training modules for each agent.
So is there such mechanism available in rasa.ai ?

Please let me know early as possible. Thanks !

**Comment by pvagare** [comment]
Sorry for this issue. I haven't gone through all documentation.
I got the solution : https://rasa-nlu.readthedocs.io/en/stable/http.html#section-http-config
I am closing issue.
Thank you.

**Comment by tmbo** [comment]
No worries :+1:

**Comment by devashishmamgain** [comment]
@tmbo whats the latest docs link to achieve multiple agents support in the same machine?

**Comment by wrathagom** [comment]
Assuming by latest you mean what is on Master: https://nlu.rasa.com/master/http.html#serving-multiple-apps

**Comment by wrathagom** [comment]
Not to my knowledge, but I have a lot less experience with Core than I do NLU. Might be worth asking on the [Rasa Core Gitter](https://gitter.im/RasaHQ/rasa_core).

**Comment by devashishmamgain** [comment]
tried gitter sometime back, didn't get any response. 
any solution for the following case:
- FAQ bot for multiple customers
- each customer have their own set of question answers
- we are able to achieve it by running multiple servers but we are looking for a way to run server on a single port and process request for different customers from their data only.

@tmbo

**Comment by streamride** [comment]
@vinayver198 
hi, did you figure out how to do it?

**Comment by gambhirpulkit** [comment]
@devashishmamgain Hey Devashish. Did you find a solution for this?

**Comment by devashishmamgain** [comment]
@vinayver198 @gambhirpulkit no, couldn't find a reliable and scalable solution.

**Comment by avinash9008** [comment]
@pvagare ---> multi models and multi agent support for rasa in single deployment

Sorry for this issue. I haven't gone through all documentation.
I got the solution : https://rasa-nlu.readthedocs.io/en/stable/http.html#section-http-config
I am closing issue.

hi ... pvagare i am also facing same issue  can you please give solution link the
above link i am not able to open that you have mentioned

**Comment by vkrntgtm** [comment]
Need to know, whether multiple agents or multiple projects running on single rasa server instance feature is enabled in rasa v2.1.2+ or v2.2.x?

**Comment by ftarlaci** [comment]
I have the same question above by @vkrntgtm

**Comment by taimoorkhokhar** [comment]
If anybody still stuck on getting this to work then I found a solution which seems to be working with multiple bots for a single server using a flask application.

https://medium.com/@b.pradeep.p/multi-agent-system-in-rasa-1c36c1a9c54

cheers!

**Comment by Mushahid2521** [comment]
@taimoorkhokhar Thanks for the solution. I am wondering can it retain the states for each bot? I can see each time a message comes and the bot is initialized each time. So can it be used in form filling when multiple users are chatting same time?
