### ISSUE TITLE
Returning default intent if no intent matches

### ISSUE THREAD

**Issue by harirehm** [RasaHQ/rasa_nlu#403]
Is there a way to create something like a default intent in the training data and return it when the given context doesn't matches any of the specified intents.

For example, consider the restaurant_search example in RASA. Now, when we ask the NLU "_Will it rain today?_", it should return some default intent. Is there a way to achieve this by specifying the default intent in the config file or training file or somewhere else?

We seriously need this feature so that, when the user searches something irrelevant, we would say something like, "_We can't understand you_", using the default intent.

**Comment by HansKannsNLP** [comment]
Hello,
I have no idea if there is already a functionality for your problem but i can tell you how i am handling this.

If I get a set which is under a limit of 0.9, I ignore the further processing and give the sentence "We can't understand you". Very simple but solved my "Default Intent"

Maybe it helps you :)

**Comment by tmbo** [comment]
There is no default intent yet. You can either go for the solution mentioned by @HansKannsNLP or you can also add another intent like `out_of_scope` labeling training data with this as well (or even a combination of both).

If you know a bit about ML, we are open for suggestions on how to integrate this.

**Comment by tmbo** [comment]
duplicates #387
