### ISSUE TITLE
MITIE Tokenizer usage for NER

### ISSUE THREAD

**Issue by vinvinod** [RasaHQ/rasa_nlu#404]
**rasa NLU version** (e.g. `0.9.0a3`):

**Used backend / pipeline** (`mitie_sklearn`):

**Operating system** (osx):

**Issue**: In a sentence, when a period follows two letter word, with first letter in caps and second not in caps, that period is not part of the tokens returned from MITIE tokenizer.
Here is the sample output
```python
>>> from mitie import tokenize
>>> text = "My name is Ab. Vinod."
>>> print(tokenize(text))
['My', 'name', 'is', 'Ab', 'Vinod', '.']
```
The `.` after `Ab` is not included in tokens. I confirmed that its done deliberately. You can check it here https://github.com/mit-nlp/MITIE/issues/133

Since that way of tokenizing is on purpose, we should take that into account when we are extracting entities.
We should modify the line 
```python
_regex = "\s*".join(re.escape(tokens[i]) for i in _range)
```
to 
```python
_regex = "\.?\s*".join(re.escape(tokens[i]) for i in _range)
``` 
in the file `mitie_entity_extractor.py`
Let me know if I should send the PR.

**Comment by tmbo** [comment]
We don't have that line anymore, this should be fixed. Let me know if this is still an issue.
