### ISSUE TITLE
Testing text with apostrophe 

### ISSUE THREAD

**Issue by nabihach** [RasaHQ/rasa_nlu#405]
How can I test the model on a query that has apostrophe symbols in it? For example, when I run
`curl -XPOST localhost:5000/parse -d '{"q":"either way I'm home today"}' | python -mjson.tool`
I see a prompt like this:
`>`

How to get around this?

**Comment by paschmann** [comment]
@nabihach - seems like you would need to replace the apostrophe with either `'\''` or `\u0027`

**Comment by nabihach** [comment]
@paschmann thanks! Both methods worked.
