### ISSUE TITLE
Exception("Invalid range given to ner_training_instance.overlaps_any_entity()")

### ISSUE THREAD

**Issue by karnigili** [RasaHQ/rasa_nlu#407]
**rasa NLU version** 0.8.6

**Used backend / pipeline** ["nlp_mitie", "tokenizer_mitie", "ner_mitie", "ner_synonyms", "intent_featurizer_mitie", "intent_classifier_sklearn"]

**Operating system** osx

**Issue**:
 I keep getting this error (Exception("Invalid range given to ner_training_instance.overlaps_any_entity()"). I checked by tokenizing the strings and it does not seems that there are overlapped tokens between different entities. 

Thank you 

**Content of configuration file** (if used & relevant):
```json

```

**Comment by tmbo** [comment]
If you don't mind, please share your data & configuration with me (tom@rasa.ai) as this will help to reproduce your issue.

**Comment by wrathagom** [comment]
@tmbo did you get the training data sample for this?

@karnigili if you would like you can send me the training data as well and I can look at this. I'll give it a few days before closing in case you still would like some help.
