### ISSUE TITLE
Rasa Training problem

### ISSUE THREAD

**Issue by andikas** [RasaHQ/rasa_nlu#410]
Hi all,

I got an issue.
I got this error when training my data.json use mitie.

![image](https://cloud.githubusercontent.com/assets/25953422/26708680/9547a184-4777-11e7-8c2f-38d669f02e48.png)

and here's my project file.
![image](https://cloud.githubusercontent.com/assets/25953422/26708728/d95d77a4-4777-11e7-9cc5-08d31f77951d.png)

plese help me fix this error.

Thanks,
Cheers

**Comment by vyudenkov** [comment]
mitie.dll which you have copied to python/lib has conflict compiled version: note if you're using x64 python than you've to compile with defined Win64:
cmake -G "Visual Studio 10 Win64" ..

**Comment by tmbo** [comment]
Let me know if this is still an issue

**Comment by andikas** [comment]
Hi @tmbo,

There's no more issue here. I solve the problem already.
Sorry for late respond and thanks for closing the thread.

Thanks,
Cheers

**Comment by prasu1222** [comment]
I am having the issue can you help me here how to resolve it?
