### ISSUE TITLE
Exception: Not all required packages are installed. Please install spacy

### ISSUE THREAD

**Issue by ashuags2** [RasaHQ/rasa_nlu#412]
hey @tmbo  can you tell how can i solve this problem.i installed spacy,rasa-nlu,scikit and all the reuirements. but i found an error during i run my python file trainer.py ,here it is:
```
from rasa_nlu.converters import load_data
from rasa_nlu.config import RasaNLUConfig
from rasa_nlu.model import Trainer

training_data = load_data('C:\Users\ABC\Desktop\project\rasa_nlu-master\rasa_nlu-master\data\examples\rasa\demo-rasa.json')
trainer = Trainer(RasaNLUConfig("C:\Users\ABC\Desktop\project\rasa_nlu-master\rasa_nlu-master\config_spacy.json"))
trainer.train(training_data)
model_directory = trainer.persist('./models/') # Returns the directory the model is stored in
and the error is:
C:\Users\ABC\Desktop\project>python trainer.py
Traceback (most recent call last):
File "trainer.py", line 6, in 
trainer = Trainer(RasaNLUConfig("C:\Users\ABC\Desktop\project\rasa_nlu-master\rasa_nlu-master\config_spacy.json"))
File "C:\Users\ABC\Miniconda3\lib\site-packages\rasa_nlu\model.py", line 125, in init
components.validate_requirements(config.pipeline)
File "C:\Users\ABC\Miniconda3\lib\site-packages\rasa_nlu\components.py", line 103, in validate_requirements
" ".join(failed_imports)))
Exception: Not all required packages are installed. Please install spacy
```

**Comment by PHLF** [comment]
What version of spacy do you have? I had the same issue before updating to > 1.8.

**Comment by ashuags2** [comment]
i have 1.8.2 @PHLF

**Comment by ashuags2** [comment]
i think it is the latest version.

**Comment by PHLF** [comment]
And which rasa version? Latest too? How did you install spacy? Are you using python virtual environments?

**Comment by ashuags2** [comment]
@PHLF rasa latest version and i installed spacy using conda beacuse i have windows and pip had some issues  during installation of scikit-learn . python virtual environment ,no not yet .

**Comment by ashuags2** [comment]
the reason of using conda is rasa and u know in rasa  for run the trainer model we required scikit-learn.

**Comment by ashuags2** [comment]
now i installed python virtual environment.

**Comment by PHLF** [comment]
My point of asking you if you were using a python virtual environment was not because I wanted you to do so, but I was wondering what would make spaCy not visible from RASA if it is installed on your system. Anyway, did you use conda to create a virtual environment? Reinstall all RASA's dependencies in your virtual environment and give it another try. I'm afraid I won't be able to help you much with your issue as I don't use Windows and I never used Conda before 😐

**Comment by ashuags2** [comment]
yes i installed virtual environment using conda .and i insstalled rasa dependencies ..but it is not working.

**Comment by wrathagom** [comment]
@ashuags2 were you able to get all of this working?

**Comment by ashuags2** [comment]
No i can not ....solve this problem..

**Comment by PHLF** [comment]
Did you try to install Spacy following [this page](https://spacy.io/docs/usage/)?

**Comment by ashuags2** [comment]
@PHLF yes , i used this page.

**Comment by tmbo** [comment]
@ashuags2 do you still have issues with this? What happens if you open the python interactive shell within your environment and try to `import spacy`?

**Comment by avi0gaur** [comment]
I am also facing this issue in ubuntu

**Comment by tmbo** [comment]
What happens if you try to run `import spacy` in your environments python shell?

**Comment by avi0gaur** [comment]
It is working fine in python shell, I am able to import and use spacy there.

**Comment by tmbo** [comment]
There is not a lot I can do to help you fix this. The problem is that spacy isn't installed properly. Most likely you installed it in the wrong environment (e.g. in your local python instead of anaconda or in a different virtual environment).

**Comment by wrathagom** [comment]
@avi0gaur were you able to get this running?

**Comment by wrathagom** [comment]
@ashuags2 were you able to get this running as well?
