### ISSUE TITLE
CRF Custom Feature Function

### ISSUE THREAD

**Issue by pm3310** [RasaHQ/rasa_nlu#416]
Is there any way to support custom CRF Feature functions?

**Comment by tmbo** [comment]
Mhm I mean you could, in code, define your own functions and use them.

**Comment by pm3310** [comment]
You can pass only the names of the feature functions in the init https://github.com/RasaHQ/rasa_nlu/blob/master/rasa_nlu/extractors/crf_entity_extractor.py#L41

It would be great if a function_dict could be passed in order to support custom feature functions

**Comment by tmbo** [comment]
I got you.

Thinking about it, you could always subclass the component and change the dictionary which should allow you to add new functions. I think this is simple as we can make it. Nevertheless, if there are obvious functions missing, we should also just add them.

**Comment by akelad** [comment]
gonna close this, as the solution is creating a custom component
