### ISSUE TITLE
Recognizing phone numbers, postal codes etc out of the box

### ISSUE THREAD

**Issue by nabihach** [RasaHQ/rasa_nlu#418]
Is there a way in Rasa to recognize common-place objects like dates, email addresses, phone numbers and postal codes (etc) out-of-the-box, without having to input hundreds of examples for each?

**Comment by PHLF** [comment]
That's the point of the [duckling component](http://rasa-nlu.readthedocs.io/en/latest/pipeline.html?highlight=duckling#ner-duckling).

**Comment by tmbo** [comment]
As @PHLF mentioned, the duckling component is really useful for finding structured entities (dates, times, numbers and such). Furthermore, you can also use the pretrained entity models from spacy, which includes persons, orgs, ... (https://spacy.io/docs/usage/entity-recognition#entity-types).

Furthermore, we are currently also working on #415 to extract intent / entities based on regex expressions.

**Comment by reddyakilesh22** [comment]
Can I save an email id and phone which is given by a person to the chatbot? How do we do that? Can someone show me the way how to do that or suggest some URL who already did that.
