### ISSUE TITLE
 Model Persistence - Azure Storage Support

### ISSUE THREAD

**Issue by vinsaTimeparity** [RasaHQ/rasa_nlu#419]
Please add Model Persistence support to Azure Blob Storage , Currently only AWS S3 and Google Cloud Storage are supported.
[https://azure-storage.readthedocs.io/en/latest/upgrade.html#blob](https://azure-storage.readthedocs.io/en/latest/upgrade.html#blob)

**Comment by tmbo** [comment]
I think this is a great feature request for a PR.
