### ISSUE TITLE
training a model for entity through Regex

### ISSUE THREAD

**Issue by parmeshashwath** [RasaHQ/rasa_nlu#421]
**rasa NLU version** (e.g. `0.7.3`):0.9.0a3

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...): spacy-sklearn

**Operating system** (windows, osx, ...):Windows

**Issue**: Is there a way to train a model through a Regex. Example : all 10 digit numbers should be identified as entity 
(Training : Get me the order status for 8987123452 )
In this case 8987123452 should be identified as one entity and order as another entity

**Content of configuration file** (if used & relevant): NA
```json

```

**Comment by tmbo** [comment]
@parmeshashwath that is a great idea, and we actually working on that at the moment as part of # #415.
