### ISSUE TITLE
Adding contexts

### ISSUE THREAD

**Issue by matteoredaelli** [RasaHQ/rasa_nlu#423]
it would be nice to add contexts. See https://chatbotsmagazine.com/contextual-chat-bots-with-tensorflow-4391749d0077

Regards
Matteo

**Comment by wrathagom** [comment]
This will be addressed by the dialogue manager to be released by the Rasa team. @tmbo gave a presentation on it at Pyberlin, you can check out the slides here. https://github.com/pydataberlin/conf2017slides/blob/master/conversational-ai-clever-chatbots-using-rasa.pdf

Please keep watching http://rasa.ai/products/rasa-core/ for more information or to request early access.
