### ISSUE TITLE
Intent classification using keras network

### ISSUE THREAD

**Issue by matteoredaelli** [RasaHQ/rasa_nlu#424]
could be useful adding Tensorflow ML?  see https://chatbotsmagazine.com/contextual-chat-bots-with-tensorflow-4391749d0077

regards
Matteo

**Comment by tmbo** [comment]
duplicates #423

**Comment by matteoredaelli** [comment]
..but adding tensorflow ML and contexts/topics in conversatios are two different features..

**Comment by tmbo** [comment]
I am not sure what you mean by "adding tensorflow ML" then. Care to elaborate a bit? Thought it was just about adding it as a dependency for the context implementation.

**Comment by PHLF** [comment]
I think @matteoredaelli mean having a component classifying intents like sklearn but backed by a Tensorflow model.

**Comment by tmbo** [comment]
Alright, I reopened it and renamed it. I think this would be a good contribution.

**Comment by rajesh-bhat** [comment]
Wouldn't we need lots of training data if we try to go with deep learning models in tensorflow or keras ?

**Comment by PHLF** [comment]
Not necessarily as Tensorflow allows one to build more than DeepLearning models.

**Comment by rajesh-bhat** [comment]
You mean to say word vectors with neural networks would do better?

**Comment by PHLF** [comment]
I mean all machine learning models for classification you can build with Tensorflow like [shallow neural networks, Random Forests, Support Vector Machines, logistic regression](http://terrytangyuan.github.io/2016/08/06/tensorflow-not-just-deep-learning/) don't necessarily require huge training data sets.

**Comment by rajesh-bhat** [comment]
Thank you @PHLF

**Comment by ajayrfhp** [comment]
I raised something related to this in gitter. Someone was kind enough to point out that performance gain if any would be marginal unless you have real huge datasets.  Huge datasets for intent classification are limited. The largest I have found is 20,000 sample big Frames dataset, but dataset is skewed towards a few classes.

**Comment by itsmudassir** [comment]
@ajayrfhp  can you please provide this  20 k frames dataset. Thanyou

**Comment by akane999** [comment]
I already have a code for intent recognition with bag of words  and a DNN classifier (keras) . Tell me if you still need help with this issue.

**Comment by itsmudassir** [comment]
Thanks for the reply. yes i would love to learn from your code . If you can
please show me your repository and provide a read-me about how to run the
code  and  the intents dataset that you have used .
Thanks!

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by nahidalam** [comment]
@akane999 I would love to look into that intent recognition code too.
