### ISSUE TITLE
How to create a rasa startup service in centOS

### ISSUE THREAD

**Issue by cpraveen412** [RasaHQ/rasa_nlu#428]
Could anyone help me how to add rasa as startup service in centOS?

**Comment by PHLF** [comment]
Did you try using [cron](https://www.centos.org/docs/5/html/Deployment_Guide-en-US/ch-autotasks.html)?  
Also see [SO related question](https://stackoverflow.com/questions/8727935/execute-python-script-on-crontab)

**Comment by cpraveen412** [comment]
Hello @PHLF ,
Thank you for your response. cron starts/restarts particular task in specific intervals of time right?
I want the service to be started when the Linux machine starts and run without any interruption.

Please correct me if i'm missing / misunderstanding anything.

Thanks

**Comment by amn41** [comment]
I like using [monit](https://mmonit.com/monit/) for this

**Comment by PHLF** [comment]
As for cron, you can use the special [`@reboot` tag](https://www.cyberciti.biz/faq/linux-execute-cron-job-after-system-reboot/).  
If you happen to look at this link, just pay attention to the systemd related part.

**Comment by cpraveen412** [comment]
Thank you @amn41 and @PHLF 
@reboot in cron worked.
