### ISSUE TITLE
requirements.txt # char breaking docker build

### ISSUE THREAD

**Issue by jdchmiel** [RasaHQ/rasa_nlu#430]
approx 3 hours ago the requirement.txt file had licenses added as comments.  This breaks the dockerbuild process at  RUN pip install $(tail -n +2 requirements.txt)

I assume the comments were added for some reason, so a quick workaround is to change the line to:

run pip install $(tail -n +2 requirements.txt| awk '{print $1;}')

**Comment by tmbo** [comment]
Oh, sorry my bad. I will remove them and list the licenses somewhere else. Thanks for creating the issue.

**Comment by tmbo** [comment]
@jdchmiel I removed the comments from the requirements file, should be good to go now.
