### ISSUE TITLE
Best practices to improve "non classification"

### ISSUE THREAD

**Issue by nicolay1** [RasaHQ/rasa_nlu#432]
Infos : rasa v `0.8.11`, using mitie on ubuntu 16.04

Hi,

First, I wanted thank all your team for your awesome job. 

I have used Mitie over Rasa for a while and so have been able to produce quite good entity recognition between two intents.
But as my project goes further I would like to assure that other intents (which also exist in my project), not to be detected by the classifier. Unlike API.ai, bullshit sentences will often be classified.
So there is the question : 
_What are the best practices to prevent wrong classification ?_

Thank's

Nicolas

**Comment by PHLF** [comment]
Could [**that**](https://github.com/RasaHQ/rasa_nlu/issues/387) be in any way related to your question?

**Comment by nicolay1** [comment]
Thank, I watched the opened issue but didn't find it, please pardon this irrelevant post.
