### ISSUE TITLE
Unable to run Rasa Docker a Windows

### ISSUE THREAD

**Issue by bigman73** [RasaHQ/rasa_nlu#434]
**rasa NLU version** (e.g. `0.7.3`):

NLU version: Latest docker image
https://hub.docker.com/r/rasa/rasa_nlu/

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...):

**Operating system** (windows, osx, ...):
Windows 7 64 bit

**Issue**:
The Rasa NLU Docker image is created from Kitemagic but doesn't run. When starting it it stops.
"Caveat for Docker for Windows users: please share your C: in docker settings, and add -v C:\path\to\rasa_nlu:/app to your docker run commands for download and training to work correctly."

The Caveat is not clear. 
What exact steps are needed for either the Docker terminal or Kitemagic?
Can you provide screenshots and a concrete example?

**Content of configuration file** (if used & relevant):
```json

```

**Comment by bigman73** [comment]
Note: I found another rasa image (custom one) that does work out of the box:
https://hub.docker.com/r/samtecspg/rasa-api/

**Comment by tmbo** [comment]
I guess @wrathagom is maintaing the rasa-api docker. @wrathagom is there something that might make sense to be changed in the repositories docker file?

**Comment by wrathagom** [comment]
@tmbo we're happy to review. I'll try to get one of our team members to post something back here or give you a pull request.

We still need our repo because we have a few things set up just a little bit different.

**Comment by tmbo** [comment]
That sounds great.

**Comment by bigman73** [comment]
What if the docker hub repository had "vanilla certified" tags along side "modified/experimental" tags?
This way users can choose which image fits them the best.

I think the key for me, as a user of Rasa, is to be able to deploy the solution with zero effort.

**Comment by ahmni01** [comment]
@wrathagom - I'm about to try RASA through Docker, Do you have an update?

**Comment by milutz** [comment]
@ahmni01 Do you have the same issue? Are you wanting to run on Windows kitematic?  The rasa images do work in general.

**Comment by ahmni01** [comment]
I had little bit of hiccup getting started and here are some steps that I went over:
1. Build the image:
**docker build -t rasa_nlu .**

Instead of the above documentation of building the image, it would be better to have a docker pull command as follows:
1. Pull the docker image:
**docker pull rasa/rasa_nlu**
_______________
2. Start the web server:
docker run -p 5000:5000 rasa_nlu start

Should be: 
docker run -p 5000:5000 **rasa**/rasa_nlu start

**Comment by wrathagom** [comment]
The command in the docs assumes you want to build from source to get the absolute latest. so you have to git clone first.

I'll try to submit a documentation change for this.

@tmbo is there a reason you don't have docker hub building automatically on all tags/merges?

**Comment by tmbo** [comment]
@wrathagom no there isn't a reason why we wouldn't do this

**Comment by nkabrich** [comment]
Related: last week I tried building a docker image from source on windows, and ran into the error `standard_init_linux.go:178: exec user process caused "no such file or directory"`.  In case anyone else is having the same problem, [the fix mentioned on this issue](https://github.com/docker/labs/issues/215) solved the problem: 

step 1: git config --global core.autocrlf false
step 2: delete code and git clone again

**Comment by tmbo** [comment]
@nkabrich mind creating a PR including a `.gitattributes` file with the setting?

**Comment by nkabrich** [comment]
@tmbo sure: https://github.com/RasaHQ/rasa_nlu/pull/461

**Comment by tmbo** [comment]
closed in favor of #455

**Comment by PreranaPolekar** [comment]
Hello all,
I am new to dockers and RASA. When I try to run the docker image , its stuck after "starting factory...." 
![dockererror](https://user-images.githubusercontent.com/2700711/34286746-c5946ca6-e708-11e7-8803-a1cbf7743c27.PNG)
<b>OS Configurations</b>
Windows 7, 64 bit
Any pointers will be of great help!
Thanks.

**Comment by KiranRW1** [comment]
+1

**Comment by mpbalshetwar** [comment]
hey @wrathagom,

I have my Windows Server 2019, Python 3.6.5 and Rasa installed on it.

I also have my Rasa bot created along with all the required things - It's absolutely working fine. Now what I want is - I want to create a docker image for that. 

Would you mind giving me steps for creating docker image of my solution please?

Thanks and Regards,
Mahesh Balshetwar
