### ISSUE TITLE
Sklearn on other languages

### ISSUE THREAD

**Issue by oximer** [RasaHQ/rasa_nlu#435]
I have the MITIE trained for Portuguese.

However, I aiming a big dataset and for this reason I'm interested on MITIE+SKLEARN usage.
It's not really clear to me how SKLearn works and if it has any language dependency. It's Sklearn language dependent? How to prepare SkLearn to deal with Portuguese?

**Comment by PHLF** [comment]
Scikit-learn is a machine learning library. Among other things it contains classification algorithms allowing you to identify intents in the RASA context.
To summarize quickly, your language model that you built using MITIE allows you to get features vector from your input sentences that can be used by any ML classifier trained over the sets of intents you defined.
A pure MITIE pipeline use MITIE words features and its own classifier (a linear SVM) for intent recognition whereas MITIE + Sklearn use MITIE words features and a Scikit-learn classifier (also a linear SVM).

**Comment by oximer** [comment]
Thus, SKLearn is language agnostic, right?

**Comment by PHLF** [comment]
Like any ML algorithm, (the classifier used by RASA)[http://scikit-learn.org/stable/modules/svm.html] is data agnostic
