### ISSUE TITLE
Crashes if too many concurrent requests to HTTP query endpoint

### ISSUE THREAD

**Issue by seenickcode** [RasaHQ/rasa_nlu#437]
**rasa NLU version** (e.g. `0.7.3`):   0.9.0a1

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...):  `spacy_sklearn`

**Operating system** (windows, osx, ...):  OSX 10.12.4

**Issue**:  Is there a max concurrent connection limit for the HTTP API?  Or is the HTTP endpoint sensitive to too many connections?  On my Macbook Pro, using Apache Benchmark, it looks like a lot of requests fail after 200 concurrent requests:

```
ab -p q.txt -T application/json -c 200 -n 5000 http://127.0.0.1:5000/parse
```

q.txt
```
{"q":"I''m at a dead end"}
```

**Content of configuration file** (if used & relevant):
```json

```

**Comment by PHLF** [comment]
Hello, please have a look at https://github.com/RasaHQ/rasa_nlu/pull/426.

**Comment by seenickcode** [comment]
Thank you.  I'm interested in using rasa as a scalable, private API.ai alternative. It seems that until some of the points are addressed in that ticket, it'd be safest to throttle requests to the rasa server. Is that a fair assumption, @PHLF?

**Comment by PHLF** [comment]
Yes it is. You can also [use gunicorn](https://rasa-nlu.readthedocs.io/en/stable/http.html#running-the-server) to circumvent flask synchronous and blocking API.

**Comment by wrathagom** [comment]
At the moment RASA is stateless, you could also run multiple instances of RASA against the same model and load balance using nginx or some tool like that.

**Comment by tmbo** [comment]
So yes, as @wrathagom @PHLF correctly mentioned, a single instance can handle only so many requests. So the solution is to start multiple instances, either using gunicorn (more information in the documentation) or use a reverse proxy (e.g. nginx) as a load balancer routing traffic to multiple Rasa NLU instances.

**Comment by seenickcode** [comment]
Humm, unfortunately for unpredictable load, it'd be impossible to guarantee that even multiple instances will handle things.  I've had the same things happen with Elastic Search crashing due to memory limits reached etc.

It seems like a consumer-side queue is the only way for now.  Thank you.

**Comment by tmbo** [comment]
Yes that is the way to go (it really depends on how much your load varies, if you expect spikes, etc.). Add a message queue that stores (possibly even persists messages for fail safety) and then pull messages from that queue and process them one after another.
