### ISSUE TITLE
Delete and unload model from server through API

### ISSUE THREAD

**Issue by bigman73** [RasaHQ/rasa_nlu#438]
Feature request

**rasa NLU version** (e.g. `0.7.3`):
0.8.10

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...):
spacy_sklearn

**Operating system** (windows, osx, ...):
Docker/Linux

**Issue**:
Add an REST DELETE API for deleting an available model. As of 0.8.10 the workaround is to delete the trained model folder from the parent /models folder. 
The Delete API should not just delete the folder but clean up any internal data structures holding the model trained data - basically untrain the model.

**Content of configuration file** (if used & relevant):
```json

```

**Comment by tmbo** [comment]
That sounds like a good addition :+1:
