### ISSUE TITLE
Spacy_sklearn and Mitie_sklearn

### ISSUE THREAD

**Issue by andikas** [RasaHQ/rasa_nlu#440]
Hi all,

reffering to this isseu:
https://github.com/RasaHQ/rasa_nlu/issues/164

I want to clear about which one is better between spacy_sklearn and mitie_sklearn.
I have an example data that I have exported it before from api.ai.
my data consist of 2 entities and 4 intents.
I train the data with those 2 and return 2 different models.

entities:
1: greetings: hello, -> synonims: hello, hi
2. nutrients: 
- protein, ->synonims: protein, proteins
- carbohidrate, -> synonims: carbohidrate, carbohidrates, carbs

1. Mitie + Skelarn
![image](https://user-images.githubusercontent.com/25953422/27417560-8b83dfaa-573f-11e7-9f09-1b9b635886b2.png)

![image](https://user-images.githubusercontent.com/25953422/27417570-a3ad0296-573f-11e7-9553-8949b4ac0db7.png)

different respond with same text.

2. spacy sklearn

![image](https://user-images.githubusercontent.com/25953422/27417633-035212cc-5740-11e7-9868-23707e9feafd.png)

![image](https://user-images.githubusercontent.com/25953422/27417648-243dc4c2-5740-11e7-80d5-db94c1582188.png)

we can see the entities sometimes not detected, even protein and carbohidrate in the same entities.
and here's  the impact. it goes to other intents because there's no entities detected.
![image](https://user-images.githubusercontent.com/25953422/27417789-0e88b41a-5741-11e7-9f53-8bfeb91bdb9c.png)
it goes to other intent (bot info intent) -> refering to 'what is your name'

so which one is better?
I'll use about 100 intents and 30 entities.
please help me decide.
and do spacy sklearn didn't return entities?

Thanks,
Cheers

**Comment by PHLF** [comment]
What is the size of your dataset: how many examples do you use for training?  
Moreover you referenced issue https://github.com/RasaHQ/rasa_nlu/issues/164 but what in @tmbo 's answer doesn't satisfy you?

**Comment by andikas** [comment]
For now, I just use dummy training data that I create from API.AI.
The data not that much, only 5 to ten each intent and only 5 data in entities.
do this spacy/mitie good at large data?

my project will use at max 10 data training each intents (there's will be 100 intents), and 10 data for each entities (there's will be aroung 20 entities).

**Comment by PHLF** [comment]
To quote @tmbo :  

> For the spacy backend a suggested amount of training data per entity is around 5000 samples (see explosion/spaCy#773). Hence it might very well be that spacy is faster but bad and mitie is slow but might perform better on your data.

**Comment by andikas** [comment]
Thanks @PHLF ,

Yeah I've read that tmbo quotes.
I just confused,
Should I continue my Rasa AI project with my existing data. my data seems too small compared to tmbo quotes. That's all.
I need some advice from  you guys as the expert here. your opinion.

Thanks,
Cheers

**Comment by PHLF** [comment]
If your pipeline doesn't work well enough for your use case try either to increase your dataset (which is currently too small) or test with another pipeline. Try also to define syntactically distinct intents and entities.

**Comment by andikas** [comment]
Thanks for your advice @PHLF ,
I'll review my project again and try that syntactically distinct intents and entities.

Thanks,
Cheers,

**Comment by parvathysarat** [comment]
@andikas Did you choose spaCy or mitie for your training, finally? I'm facing the same problem here, not getting good confidence levels for spacy. Wondering if I should switch to mitie or add more examples.
