### ISSUE TITLE
Clear documentation on how to make rasa work with api.ai is missing 

### ISSUE THREAD

**Issue by toofan0909** [RasaHQ/rasa_nlu#446]
Hello Team,

I am a starter in this field, could some provide bit more details in terms of making rasa work with my api.ai information 

C:\Python27\Scripts>python -m rasa_nlu.train -h
usage: train.py [-h] [-p PIPELINE] [-o OUTPUT] [-d DATA] -c CONFIG
                [-l {de,en}] [-t NUM_THREADS] [-m MITIE_FILE]

train a custom language parser

optional arguments:
  -h, --help            show this help message and exit
  -p PIPELINE, --pipeline PIPELINE
                        pipeline to use for the message processing.
  -o OUTPUT, --output OUTPUT
                        path where model files will be saved
  -d DATA, --data DATA  file containing training data
  -c CONFIG, --config CONFIG
                        config file
  -l {de,en}, --language {de,en}
                        model and data language
  -t NUM_THREADS, --num_threads NUM_THREADS
                        number of threads to use during model training
  -m MITIE_FILE, --mitie_file MITIE_FILE
                        file with mitie total_word_feature_extractor

I am trying 

C:\Python27\Scripts>python -m rasa_nlu.train -c  d:\rasa\Flowers 

 Directory of d:\rasa\Flowers

06/25/2017  05:44 PM    <DIR>          .
06/25/2017  05:44 PM    <DIR>          ..
06/25/2017  03:05 PM             1,702 agent.json
06/25/2017  03:05 PM                52 customDomainsResponses.json
06/25/2017  05:44 PM    <DIR>          entities
06/25/2017  05:44 PM    <DIR>          intents
           

Any one here to help?

**Comment by PHLF** [comment]
Have a look at [Training your model](https://rasa-nlu.readthedocs.io/en/latest/tutorial.html#training-your-model) from the doc. You must specify a configuration file with the `-c` parameter whereas you specified your training data path `d:\rasa\Flowers`. This must be the value of the `data` parameter in your config file.  
Once set, you can launch your training process `python -m rasa_nlu.train -c my_config.json`

**Comment by wrathagom** [comment]
Also the specific docs about migrating from API.ai. http://rasa-nlu.readthedocs.io/en/latest/migrating.html#api-ai

If you still have questions then let us know?

**Comment by tmbo** [comment]
I'll close this for now. Please let me know if you still have issues.

**Comment by kimkartavyavimudh** [comment]
I am try to use rasa NLU from python to do this. I have added the path to api.ai data in config. But what should be given in training_data variable as we need to use trainer.train(training_data) to train the model.
