### ISSUE TITLE
Training process won't stop with rasa nlu in python along Flask and Gunicorn

### ISSUE THREAD

**Issue by shinoys222** [RasaHQ/rasa_nlu#452]
The training process gets repeated forever when i run rasa nlu from python 3 with flask deployed using Gunicorn. I used training example of restaurant search from rasa trainer project. I'm using the spacy-scikit backend/pipeline provided in the documentation. 

The scikit-learn error message pops up in log ( F-score is ill defined ..) The log shows Done 12 out of 12 meaning training complete i guess.  I think this problem will be solved with enough training data.  But this process repeats again after a few seconds and another major problem is i don't get the return value from 

`interpreter.parse(u'Some random text input')`

I don't know if i'm doing it the right way. Please help

![rasa_error](https://user-images.githubusercontent.com/3121528/27647395-f19d4976-5c48-11e7-8e12-86dc9fd737bf.PNG)

**Comment by tmbo** [comment]
Do you mind sharing the code from the screenshot as a snippet?

**Comment by shinoys222** [comment]
```
from flask import Flask,request,jsonify
from rasa_nlu.converters import load_data
from rasa_nlu.config import RasaNLUConfig
from rasa_nlu.model import Trainer
from rasa_nlu.model import Metadata,Interpreter


app = Flask(__name__)
training_data = load_data('data/examples/rasa/demo-rasa.json')
trainer = Trainer(RasaNLUConfig("config_spacy.json"))
trainer.train(training_data)
model_directory = trainer.persist('./models/')

metadata = Metadata.load(model_directory)
interpreter = Interpreter.load(metadata,RasaNLUConfig("config_spacy.json"))

@app.route('/',methods = ['GET'])
def start():
    dict = interpreter.parse(u"Hello , How are you")
    #return jsonify(dict)
    return dict

```

**Comment by efvaldez1** [comment]
Hi @shinoys222 , I am experiencing the sample problem. How do you set this up? In my Flask App I previously used API.AI , now I want to use RASA NLU insteaad, I have added /data /projects and /sample_configs from the tutorial:

I added the python code found in https://rasa-nlu.readthedocs.io/en/latest/python.html
to my main app, however when I run run.py, it trains the bot and just reloads again
