### ISSUE TITLE
Missing tqdm python library

### ISSUE THREAD

**Issue by beeva-fernandocerezal** [RasaHQ/rasa_nlu#454]
Using latest version of github, after creating docker image, on execute:
./entrypoint download mitie en

It shows an error of missing tqdm library.

It is solved executing (inside the container):
pip install tqdm

**Comment by beeva-fernandocerezal** [comment]
Or Adding tqdm to requirements.txt

**Comment by tmbo** [comment]
just did that, mind trying it out again with the latest version I just pushed?

**Comment by beeva-fernandocerezal** [comment]
Tried, it works.

Thank you
