### ISSUE TITLE
Improve docker images and dependency management within containers

### ISSUE THREAD

**Issue by beeva-fernandocerezal** [RasaHQ/rasa_nlu#455]
Using github last version, on try to install spacy:
#./entrypoint.sh download spacy en
Downloading spacy.en model...
/usr/local/bin/python: No module named spacy.en

Trying to install handly:
python -m spacy.en.download all
/usr/local/bin/python: No module named spacy.en

Regards

**Comment by tmbo** [comment]
could you please retry with the latest version?

**Comment by sankethpb** [comment]
@beeva-fernandocerezal 
`python -m spacy.en.download all `command works only for spacy version less than 1.7

For newer versions, please try below command
`python -m spacy download en` 
for more details on installing other models you may check https://spacy.io/docs/usage/models

**Comment by beeva-fernandocerezal** [comment]
If that is the case, then the version should be defined in the install function inside entrypoint script. Other way, following the installation steps leads to an error.

**Comment by tmbo** [comment]
Where did you install spacy from? The version is pinned in the `dev-requirements.txt`

**Comment by beeva-fernandocerezal** [comment]
It doesn't works.

# ./entrypoint.sh download spacy en
Downloading spacy.en model...
/usr/local/bin/python: No module named spacy

#python -m spacy download all
/usr/local/bin/python: No module named spacy
# python --version
Python 2.7.13
# uname -a
Linux d8237a7b4d39 4.4.0-79-generic #100-Ubuntu SMP Wed May 17 19:58:14 UTC 2017 x86_64 GNU/Linux

I'm using a clean container just created with repository dockerfile.

If I do "pip install spacy", it installs something, but I don't know if that is suitable for Rasa.

**Comment by tmbo** [comment]
It depends a bit on which docker file you are using. There are actually two (minimal and full). The minimal one only contains the absolutely necessary dependency but doesn't include all the dependencies needed for specific components of the Rasa NLU processing pipelines. The full container on the other hand installs all necessary requirements, which includes spacy. When using the minimal container you should install spacy on your own, but by specifying the version of spacy (have a look at the dev-requirements.txt for the currently recommended version).

**Comment by beeva-fernandocerezal** [comment]
Hello, after several tries, this is my summary:

After using Dockerfile o dockerfile_minimal, you must going into container, copy a config file like config.json and then install the libraries y restart the service.

./entrypoint download spacy en is broken. It doesn't work. You must install spacy manually using standard dockerfile or minimal.

There is only a way you don't need to install libraries manually: using dockerfile_full. Anyway, you need to copy configuration file. I didn't finish this way after ten minutes installing libraries that I'm not going to use.

I think it would be better to create a dockerfile per subsystem or use an script that change the parameters of installation (and use a different requirements.txt), but dockerfiles giving a non ready-to-work container I think it's a obstacle for users.

I did scripts giving a ready to work container for a previous version, but you upgraded before they could be integrated. If I can help you, just tell me.

**Comment by tmbo** [comment]
You are right, the docker files are far from optimal. I think @wrathagom is working on some really cool improvements there :+1:

**Comment by beeva-fernandocerezal** [comment]
I followed with my tests. 

After installing spacy manually, you get another error for other dependencies. Even after that, there is an error because you must download the model:
pip install spacy=1.8.2
pip install sklearn-crfsuite==0.3.5 scikit-learn==0.18.1 scipy==0.19.0
python -m spacy download en

Once that done, it seems to work, creates the model after training and loads it, but that model is not used as default. Event after restart the container with only a model, it is not used a default. You have to rename the model directory to "default" and restart the container. Then it works.

So, total steps are:
Create container
inside the container, copy spacy_config.json to config.json
pip install spacy=1.8.2
pip install sklearn-crfsuite==0.3.5 scikit-learn==0.18.1 scipy==0.19.0
python -m spacy download en
Train the model
inside the container, rename model to default
Restart the container.

At least, I hope this issue could be useful for other people trying to use rasa.

**Comment by wrathagom** [comment]
@beeva updates are coming, but just out of curiosity are you using the rasa_nlu or rasa_nlu_full image?

**Comment by beeva-fernandocerezal** [comment]
I'm using the "Dockerfile" file, not full. I don't think it is acceptable download and install hundreds of MB, or gigabytes (it didn't finish), of libraries I'm not going to use.

**Comment by wrathagom** [comment]
well, unfortunately we don't know which pipeline you are going to use ahead of time so you have to either start with nothing or start with everything. We could create MITIE and sklearn specific images, but then we'd be up to 5 or more images coming from a single repo... We'll give that some thought. 

The above struggle that you went through is all documented here on getting setup. Since you used the non-full docker it applied to the container as well.

**Installation:** http://rasa-nlu.readthedocs.io/en/latest/installation.html#setting-up-rasa-nlu
**Default Model:** http://rasa-nlu.readthedocs.io/en/latest/http.html#serving-multiple-apps

So my takeaways:
 - Update `entrypoint.sh` to download python requirements as well as models
 - Potentially maintain a MITIE and SpaCy docker image
 - Update docker docs to make all of the above more clear

**Comment by wrathagom** [comment]
This was addressed a long time ago with the new Docker images. To see the available images check [Docker Hub](https://hub.docker.com/r/rasa/rasa_nlu/).
