### ISSUE TITLE
Allow Loading SpaCy model by Path

### ISSUE THREAD

**Issue by oximer** [RasaHQ/rasa_nlu#457]
Now my question is how to use my own Spacy model in Rasa. 

Our config file says that http://rasa-nlu.readthedocs.io/en/latest/config.html#spacy-model-name that spacy_model_name will pass to "Spacy.load('spacy_model_name'). It's possible to send a path to the model and load it from the disk?

> Loading models
> 
> spacy.load() is now only intended for loading models – if you need an empty language class, import it directly instead, e.g. from spacy.lang.en import English. If the model you're loading is a shortcut link or package name, spaCy will expect it to be a model package, import it and call its load() method. If you supply a path, spaCy will expect it to be a model data directory and use the meta.json to initialise a language class and call nlp.from_disk() with the data path.
> 

```
nlp = spacy.load('en')
nlp = spacy.load('en_core_web_sm')
nlp = spacy.load('/model-data')
nlp = English().from.disk('/model-data')
# OLD Version 1.8: nlp = spacy.load('en', path='/model-data')
```

**Comment by wrathagom** [comment]
@oximer was requested to create the issue by @tmbo, here's some Gitter background:

**Can I load a spacy model "by path“?** I am not sure that works, tbh, I haven’t tested that. But that should be an easy fix - please create an issue for that

**Comment by tmbo** [comment]
@oximer have you tried it? I just had a look at the code and I can't see a reason why setting `spacy_model_name` to a path wouldn't work.

**Comment by tmbo** [comment]
should be working, let me know if there are issues.
