### ISSUE TITLE
ner_duckling not working in Windows

### ISSUE THREAD

**Issue by sagarjs** [RasaHQ/rasa_nlu#458]
**rasa NLU version** (e.g. `0.7.3`):
0.9.0a4

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...):
["nlp_spacy", "ner_crf", "ner_synonyms", "intent_featurizer_spacy", "intent_classifier_sklearn", "ner_duckling"]

**Operating system** (windows, osx, ...):
Windows

**Issue**:
I get a python.exe has stopped error and I have to "Close the program" which leads to exiting of python in my command prompt whenever I use ner_duckling. The pipeline works perfectly fine as long as "ner_duckling" isn't in it.

I also tried using ubuntu, which worked, and i took that model and used it in windows, this also gives the same 'close the program iss'

**Content of configuration file** (if used & relevant):
```json
{
  "pipeline": ["nlp_spacy", "ner_crf", "ner_synonyms", "intent_featurizer_spacy", "intent_classifier_sklearn", "ner_duckling"],
  "path" : "./models",
  "data" : "./data/uotm/expressions.json"
}

```

**Comment by wrathagom** [comment]
@sagarjs are you able to run the duckling python tools outside of rasa successfully? That may help us identify if this is actually a Rasa bug or something from the duckling wrapper.

**Comment by sagarjs** [comment]
@wrathagom  i tried this code

```
import duckling
d = duckling.Duckling()
```

I get the same error, so i guess this is an issue with the duckling wrapper

**Comment by wrathagom** [comment]
Sounds like it.

I'll leave this one open while we wait for a response on the python duckling repo. @tmbo you've been able to get stuff fixed on the python duckling side before, in case you can make it happen again.

**Comment by wrathagom** [comment]
Just because I haven't asked, which version of duckling are you using?

**Comment by wrathagom** [comment]
Closing since it's been a few days. If this issue persists, please let us know.

**Comment by MartinWilden** [comment]
I got exaclty the same problem with duckling 1.7.2

**Comment by xuduo18** [comment]
same here. no duckling results in responses. i am on ubuntu with duckling 1.7.2

**Comment by wrathagom** [comment]
Please open a new issue and provide the information requested in the issue template.

**Comment by serdarbozoglan** [comment]
I have the same problem. Even though I installed duckling, when I use in pipeline (such as ner_duckling) I got an error.

Thank you

**Comment by akelad** [comment]
we removed ner_duckling recently, if you want to use duckling please use `ner_duckling_http` instead and if you have any issues with that open a new issue please
