### ISSUE TITLE
Allow addition of custom C parameter values to the sklearn_intent_classifier

### ISSUE THREAD

**Issue by Ayoubb94** [RasaHQ/rasa_nlu#459]
Hi all,

I've been using the sklearn intent classifier, and noticed that the C parameter and the kernel are fixed and hardcoded inside `sklearn_intent_classifier.py`. Perhaps it would be useful to add the ability to specify these inside the configuration json file if one wants to pass their own parameters to sklearn. At the moment the only way seems to be modifying the tuned_parameters variable in that script?

**Comment by wrathagom** [comment]
Sounds like a good idea, doesn't sound too hard either, perfect thing for a quick pull request ;)

**Comment by IanRogers-LabShift** [comment]
PR submitted for this: https://github.com/RasaHQ/rasa_nlu/pull/475

**Comment by wrathagom** [comment]
This one was merged.
