### ISSUE TITLE
Training the same model twice with different data - Incremental Learning

### ISSUE THREAD

**Issue by kishoredevaraj** [RasaHQ/rasa_nlu#463]
**rasa_nlu version** : 0.9.0a7

**Used pipeline** : spacy_sklearn

**Operating System** : os x

**Issue**: Cannot train the same model with different different data set 

Hello everyone,
I'm new to rasa_nlu as well as to python world. I checkout rasa_nlu for the last 10 days and it has been amazingly great. Kudos to those who created it :).

Two days before i got stuck with one problem. I want to train a model with multiple datasets. Lets say i have 'one.json' and 'two.json', both contain different intents and entities. First i have to train a model using one.json and save it as model_X. Once model X is saved, I need to train the same model with 'two.json'.

But the problem is whenever i train the same model with 'two.json', I'm not getting the intents and entities it learned before. I checked out the documentation and i could not find any resource related to this issue. If it is there, please point me out.

Could someone help me out how to solve this problem. Any help would be appreciated. :)

**Comment by wrathagom** [comment]
Hey @kishoredevaraj can I ask how you're training your data, via the HTTP API or directly in python?

Either way really, it is known that once a model with a particular name is loaded it can't be unloaded without restarting Rasa. Though there is a request to make it possible, see #438 

But the way your trying to use your training data doesn't sound quite right either. All training data for a single model has to go in a single file (or single POST request) for training. It can still contain different intents and entities, but should be consolidated into a single document. The best documentation covering it is here, though I am sure you saw it already: http://rasa-nlu.readthedocs.io/en/latest/dataformat.html#training-data-format

Examples of the training data are located here: https://github.com/RasaHQ/rasa_nlu/tree/master/data/examples/rasa

Also, it is possible to serve multiple models at the same time: http://rasa-nlu.readthedocs.io/en/latest/http.html#serving-multiple-apps

And finally @PHLF has some cool changes coming to the way `agents` handle models and training. https://github.com/RasaHQ/rasa_nlu/pull/449

**Comment by kishoredevaraj** [comment]
Hey @wrathagom, I'm training my data through my python script. And also i know that all data should be in single document to train a model.

But am actually checking whether the concept of "Pre trained Models" and "Transfer Learning" is possible in Rasa.

**Comment by wrathagom** [comment]
Sorry maybe I should've been more direct with my original response. It is currently not possible to train a model with one.json and then add on to it. The only way would be two merge one.json and two.json and then train a new model with the merged training data.

As far as pre-trained models, again it depends a bit on what you mean. Rasa itself is consuming some MITIE and Spacy pre-trained models, which can be substituted. You can train models in one instance of Rasa and move them to another instance. It is also possible to use Spacy for entity recognition which has a quite a few pre-trained entities.

I don't believe anyone is attempting transfer learning with Rasa.

**Comment by kishoredevaraj** [comment]
Thanks for your suggestion @wrathagom. I'll try that.

**Comment by tmbo** [comment]
I am also currently looking into adding a feature that allows you to pass in multiple training data files. I think that might make it easier for you as well.
