### ISSUE TITLE
Bug in Duckling_ner with the name of the language

### ISSUE THREAD

**Issue by amirkargar** [RasaHQ/rasa_nlu#465]
**rasa NLU version** :
0.9.0a4
**Used backend / pipeline** :
["nlp_spacy",
        "ner_spacy",
        "ner_synonyms",
        "intent_featurizer_spacy",
        "intent_classifier_sklearn",
        "ner_duckling"]
**Operating system** :
OSX
**Issue**:
In multi-tenancy mode, when I loaded all the models and tried to parse some sentences I noticed the following error from Duckling showing it can't load the language module:

```
Jul 7, 2017 12:12:24 PM clojure.tools.logging$eval277$fn__281 invoke
SEVERE: [duckling] Module en is not loaded. Did you (load!)?
```

After digging I noticed that Duckling is being loaded with language 'en' inside duckling_extractor.py.
The name of the language should be as following:

```
  | DANISH = 'da$core'
  | GERMAN = 'de$core'
  | ENGLISH = 'en$core'
  | SPANISH = 'es$core'
  | ESTONIAN = 'et$core'
  | FRENCH = 'fr$core'
  | IRISH = 'ga$core'
  | INDONESIAN = 'id$core'
  | ITALIAN = 'it$core'
  | JAPANESE = 'ja$core'
  | KOREAN = 'ko$core'
  | PORTUGUESE = 'pt$core'
  | RUSSIAN = 'ru$core'
  | UKRAINIAN = 'uk$core'
  | VIETNAMESE = 'vi$core'
  | CHINESE = 'zh$core'
```

Replacing 'en' with 'en$core' fixed the issue.

**Comment by tmbo** [comment]
@amirkargar which version of duckling are you using? I created a PR at the duckling repo a while ago fixing that, so a version update there might resolve that.

**Comment by amirkargar** [comment]
I’m using Duckling 1.3.0. I should update and see how it works. Thanks.

**Comment by tmbo** [comment]
I'll close this one, let me know if the problem persists with the updated version.

**Comment by amirkargar** [comment]
The upgrade fixed the issue, thanks.
