### ISSUE TITLE
How many models can a 1GB ram rasa server can support in parallel ?

### ISSUE THREAD

**Issue by sanathp** [RasaHQ/rasa_nlu#469]
Hi,

I am planning to build a bot platform, which helps to create a messenger/slack bot in few clicks for a specific use case. So i will be creating and hosting bots on behalf of users.  I want to use rasa for natural language processing.

My questions : 
1) Can i use rasa to create multiple models , may be hundreds ?
2) For a 100 medium side models( 10 intents) how much server capacity is required ?
3) Can i train multiple models at a time ?

Please help, Thanks in advance.

**Comment by wrathagom** [comment]
Are you trying to develop this in python or are you using the HTTP API? That will impact the answers below.

1) Yes, see here https://rasa-nlu.readthedocs.io/en/latest/http.html#serving-multiple-apps
2) qualitatively 1-2G ram before you add any models and 10+M for each model that is loaded.
3) Not using the HTTP API but #450 seeks to address that I believe

**Comment by sanathp** [comment]
Thank you very much for the quick response.

I want to use the HTTP API

Questions :
1) I want to create and train models dynamically using http requests. Is this possible ?
2) I see three different Dockerfiles in the repo. Which one should i use for the complete HTTP server which syncs with AWS S3 ?
3) are there any limitations on how many apps can be served or trained in parallel ?

Thanks in advance.

**Comment by wrathagom** [comment]
1) yes see the documentation here http://rasa-nlu.readthedocs.io/en/latest/http.html#post-train
2) We are currently re-working the docker files. At the moment none of them support AWS persistence. That being said you can take one of our docker files and use that as the basis for a custom build with a config file specifying the AWS info.
3) From my understanding training does not happen in parallel, it is blocking. So only 1 model may be trained at a time. As far as number of active models, I believe that is only limited based on hardware, though I have not confirmed.

**Comment by tmbo** [comment]
Yes, number of loaded models is only limited by the available main memory.

**Comment by wrathagom** [comment]
@sanathp I'm going to close, if you want to discuss further hop on the [Gitter channel](https://gitter.im/RasaHQ/rasa_nlu?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge).

**Comment by sanathp** [comment]
This information is very useful. Thanks for the response.
