### ISSUE TITLE
TrainingSet Properties to be added & retrieved from Result

### ISSUE THREAD

**Issue by thilagaDas** [RasaHQ/rasa_nlu#471]
**rasa NLU version** (e.g. `0.8`):

**Used backend / pipeline** (`mitie`):

**Operating system** (ubuntu):

**Issue**:
I am trying to add additional Properties in the Training Set. And the same has to be returned while intent classification.
**Sample Input:**
  "intent": "greet",
        "entities": [],
        "text": "Hello",
        "parameters": "[username]",
        "response": "Hi, you are welcome"
      }
**Expected Result:**
{
        "_text": "hello",
        "confidence": 0.4794813722432127,
        "entities": {},
        "intent": "greet",
        **"parameters": "[username]",
        "response": "Hi, you are welcome"**
    }

**Content of configuration file** (if used & relevant):
```json

```

**Comment by tmbo** [comment]
I don't yet get the use case for this and how this is supposed to work.
- What is this used for?
- How do you determine when the parameters is returned?

**Comment by thilagaDas** [comment]
Thanks for the reply tmbo.

I am developing a chatbot. This will simply say "Hi, howmay i help you"  if we say hi. It will ask username when we ask its name.. Please find below the training set.
RASA will return only intent and score for the matched text. I would like to get additional keys like parameters and response. As of now i am directly appending response text with the Intent itself. Once RASA returns the matched intent, then i will parse in the python code and displays the response to the user. Instead of doing this, directly i would like to trains response, parameters in the trainingset and fetch as result along with score and intent

**TRAINING_SET:**
 {
  "rasa_nlu_data": {
    "common_examples": [
      {
	   "Id":1,
        "text": "Hi",
        "intent": "I[General]~colon;~R[Hi, how may I help you?]",
        "entities": [],
        "parameters":[]
      },       
	 {
	   "Id":2,
        "text": "What is your name",
        "intent": "I[General]~colon;~R[I am testBOT, your digital assistant. What is your name]",
        "entities": [],
        "parameters":["@userName"]
      } 
    ]
  }
}

**Comment by wrathagom** [comment]
The Rasa team has announced a dialogue manager that is currently in a closed testing, but will be open sourced. This feels best suited to that tool. You can request access in the link below.

http://rasa.ai/products/rasa-core/

Here are some slides that Tom presented at PyBerlin https://github.com/pydataberlin/conf2017slides/blob/master/conversational-ai-clever-chatbots-using-rasa.pdf some of which address the dialogue manager.
