### ISSUE TITLE
Trained some datas but output result doesn't matched

### ISSUE THREAD

**Issue by AP8050** [RasaHQ/rasa_nlu#474]
**rasa NLU version** (e.g. `0.8`):

**Used backend / pipeline** (`mitie`):

**Operating system** (ubuntu):

**Issue**: 
If I am giving input as "hi", i'm getting the response as,
{
        "text": "Hi",
        "intent": "I[General]~colon;~R[Ok]",
        "entities": []
 }, 
In this scenario I'm getting the reponse as expected.

If I am giving input as "hai", i'm getting the response as,
{
        "text": "different regional packs you have",
        "intent": "I[RegionalPacks]~colon;~R[The regional packs available are:  Bengali, Tamil, Malayalam, Telugu, Marathi, Kannada.  You can choose any two free regional packs in addition to your base pack]",
        "entities": []
 },
In this scenario I'm not getting the reponse as expected. I just want to know on what basis I'm getting this reponse. 

**Content of configuration file** (if used & relevant):
**config.json**:
{
"pipeline": "mitie",
"mitie_file": "./data/total_word_feature_extractor.dat",
"path" : "./models",
"data" : "./data/examples/rasa/test.json"
}
**test.json**
{
  "rasa_nlu_data": {
    "common_examples": [
      {
        "text": "Hi",
        "intent": "I[General]~colon;~R[Ok]",
        "entities": []
      },
      {
        "text": "Hello",
        "intent": "I[General]~colon;~R[Ok]",
        "entities": []
      },
        {
        "text": "different regional packs you have",
        "intent": "I[RegionalPacks]~colon;~R[The regional packs available are:  Bengali, Tamil, Malayalam, Telugu, Marathi, Kannada.  You can choose any two free regional packs in addition to your base pack]",
        "entities": []
      },
	  {
        "text": "HD channels included in the basic sports pack",
        "intent": "I[HD_Channels]~colon;~R[No.  The various sports pack are DSPORT,  Sony ESPN HD, Sony Six HD, Star Sports 1 HD, Star Sports 2 HD, Star Sports Hindi 1 HD, Star Sports Select 1 HD, Star Sports Select 2 HD, Ten 1 HD, Ten Golf HD]",
        "entities": []
      }
    ]
  }
}

**Comment by wrathagom** [comment]
Long story short, it appears you need more training data. One utterance example per intent is not enough to train a model that will perform as expected.

**Comment by thilagaDas** [comment]
Hi wrathgom,

Howmany utterance per intent would you be suggested for intent classification the with minimal error rate ?

**Comment by wrathagom** [comment]
Unfortunately that is entirely dependent upon the pipeline you are using, and the information that you are training against.  Though I would think a qualitative minimum would be 2-4 examples per intent. Start at that minimum, train, then test the model performance. Add more intent examples where parsing fails.

**Comment by wrathagom** [comment]
@thilagaDas let us know if you're still having trouble. Closing unless we hear that you need more assistance.
