### ISSUE TITLE
Add CORS option to config

### ISSUE THREAD

**Issue by wrathagom** [RasaHQ/rasa_nlu#478]
Currently cross domain requests are blocked on the HTTP API. A need was mentioned on Gitter to allow this. It appears Flask has a CORS module that looks trivial to add. Though I would think you'd want to add it in an optional way such as `cors: true` in the config file.

https://flask-cors.readthedocs.io/en/latest/

**Comment by PHLF** [comment]
It looks like enabling CORS should be as easy as adding a `Access-Control-Allow-Origin: *` header to the server response or even better a `Access-Control-Allow-Origin: origins_specified_in_config_file`.

**Comment by tmbo** [comment]
Sounds good :+1:

**Comment by tmbo** [comment]
done
