### ISSUE TITLE
Synonyms seem broken in 0.9.1

### ISSUE THREAD

**Issue by znat** [RasaHQ/rasa_nlu#481]
**rasa NLU version**: 0.9.1

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...):
`["nlp_spacy", "tokenizer_spacy", "intent_entity_featurizer_regex", "intent_featurizer_spacy", "ner_crf", "ner_synonyms", "intent_classifier_sklearn"]`

**Issue**:
Entity synonyms are not recognized. In the training file below, "looking for a restaurant in new-york" will be parsed as expected but no city entity will be found for  "looking for a restaurant in NYC".

`models/current/entity_synonyms.json` content: `{"nyc": "new-york", "the big apple": "new-york"}`

This is just a toy file to reproduce the issue found on a larger set 

```json
{
    "rasa_nlu_data": {
        "common_examples": [
            {
                "text": "looking for a restaurant in new-york", 
                "intent": "inform", 
                "entities": [
                    {
                        "start": 28, 
                        "end": 36, 
                        "value": "new-york", 
                        "entity": "city"
                    }
                ]
            }, 
            {
                "text": "looking for a restaurant in the big apple", 
                "intent": "inform", 
                "entities": [
                    {
                        "start": 28, 
                        "end": 41, 
                        "value": "new-york", 
                        "entity": "city"
                    }
                ]
            }, 
            {
                "text": "good food in new-york", 
                "intent": "inform", 
                "entities": [
                    {
                        "start": 13, 
                        "end": 21, 
                        "value": "new-york", 
                        "entity": "city"
                    }
                ]
            }, 
            {
                "text": "good food in NYC", 
                "intent": "inform", 
                "entities": [
                    {
                        "start": 13, 
                        "end": 16, 
                        "value": "new-york", 
                        "entity": "city"
                    }
                ]
            }, 
            {
                "text": "hey", 
                "intent": "greet"
            }, 
            {
                "text": "hello", 
                "intent": "greet"
            }
        ], 
        "entity_synonyms": []
    }
}
```

**Comment by znat** [comment]
Closing it for now as I only have the issue on one machine. Will investigate further and re-open if there is indeed a Rasa related issue.

**Comment by tmbo** [comment]
I also don't think this is related to the synonyms. It might be that the entity recognition doesn't always recognize the entity (which might be to the small number of training examples - depending on the initialization of the model we might sometimes get lucky and sometimes the training might not be enough). That being said, if you think there might be an issue, that is definitely something we need to have a look at.
