### ISSUE TITLE
re-run rasa_nlu.server

### ISSUE THREAD

**Issue by karnigili** [RasaHQ/rasa_nlu#484]
How can I re-train a running model and re-run it without ?
Is there a build in solution for that?

I read  #342 but did not understand it fully.

Thank you

**Comment by HansKannsNLP** [comment]
Hey @karnigili 

If i understood it in the right way you cannot retrain models which are already loaded from the server (you can do it but it have no effect without re-run). There is a way to get a nearly same result. If you retrain a Model just give it a version in the name and always use the latest Version in the parse request. So you cannot re-train a existing Model and use it without restart but you can do it with a little workaround.

In additional you can read the #463 issue looks like the same. I think @wrathagom explained it much better ;)
Greetings!

**Comment by wrathagom** [comment]
almost a duplicate of #433, but this one seems more about doing it in Python and that one is for the HTTP API.

@karnigili my advice until one of these is implemented is to use a version number so my_model_v1 then use that model for parsing.

I was thinking on Gitter someone found a manual workaround for this, but I can't seem to find it.

**Comment by tmbo** [comment]
should be fixed with current projects implementation
