### ISSUE TITLE
Extracting a token as two entities simultaneously

### ISSUE THREAD

**Issue by nabihach** [RasaHQ/rasa_nlu#485]
How can I get "ner_crf" to extract the same word as two different entities?
For example, given the input sentence `"I want to go home"`, I want the output to be:
```
    "entities": [
        {
            "end": 17,
            "entity": "A",
            "extractor": "ner_crf",
            "start": 13,
            "value": "home"
        },
        {
            "end": 17,
            "entity": "B",
            "extractor": "ner_crf",
            "start": 3,
            "value": "home"
        }
    ]
```
Is this doable? I tried inputing training examples for both but Rasa only recognizes the word as either A or B, never both together.

**Comment by wrathagom** [comment]
This is not currently possible. Can you give us your use case on how this would be used?

Could you implement this in the fulfillment code you have on your backend?

**Comment by nabihach** [comment]
As an example, entity A could be where_i_live and B could be where_i_want_to_go. This isn't a great example I know, but in general multiple entities could have the same value.

Can you give me some tips on how to implement this? I'll try my best.

**Comment by wrathagom** [comment]
Sorry, I mis-understood. I thought you were asking for the entity to be duplicated in the response even if it's only found once in the sentence.

So given the sentence: `Show me how to get from home to work.` and `Show me how to get from work to home` are those good examples?

Something like this (probably with more examples) would work.

```
{
  "rasa_nlu_data": {
    "common_examples": [
      {
        "text": "Show me how to get from home to work.",
        "intent": "get_directions",
        "entities": [
          {
            "start": 24,
            "end": 28,
            "value": "home",
            "entity": "location"
          },
          {
            "start": 32,
            "end": 36,
            "value": "work",
            "entity": "destination"
          }
        ]
      },
      {
        "text": "Show me how to get from work to home.",
        "intent": "get_directions",
        "entities": [
          {
            "start": 24,
            "end": 28,
            "value": "work",
            "entity": "location"
          },
          {
            "start": 32,
            "end": 36,
            "value": "home",
            "entity": "destination"
          }
        ]
      }
    ]
  }
}
```

**Comment by nabihach** [comment]
Actually I do want the entity to be duplicated in the response. So even though the word "home" occurs once in the input, I want it to be extracted as two different entities. I understand this isn't possible, but I would love to get tips on how to do this.

**Comment by wrathagom** [comment]
It would be implemented in whatever backend you are using for fulfillment or interaction with Rasa.

**Comment by nabihach** [comment]
Sorry but I'm not sure how. I would like rasa to identify all the entities "home" could possibly be refer to. Doesn't this require modification to Rasa's core entity extraction model?

**Comment by tmbo** [comment]
That is quite an interesting issue. At the moment entities can not overlap as this is how most of the models are designed (so the one we have implemented as well as the ones from spacy / mitie).

I am not sure if there are models out there that can achieve that.

**Comment by wrathagom** [comment]
@tmbo can you think of a place where this would be used or give me a use case? Let's say you want the user to be able to ask for `Give me directions home.` and home is identified as an entity. You'd have to have some backend that looks up home and ties it to an address. So if there were two possible homes then they would show up in that layer.

**Comment by nabihach** [comment]
Here's another use case. 

Q. What type of insurance policy do you want?
A. Business

Q. What do you use your vehicle for the most?
A. Business.

In the first case, business refers to the entity insurance_type. In the second case, it refers to entity vehicle_use.

**Comment by wrathagom** [comment]
Wouldn't those be separate intents? So If `entity==Business && intent==insurance` do A vs if `entity==Business && intent==vehicle` do B?

Sorry not trying to be difficult, just trying to wrap my head around it.

**Comment by PHLF** [comment]
@nabihach unfortunately implementing this is not as easy as you may think. Have a look at [multilabel classification](https://en.wikipedia.org/wiki/Multi-label_classification). There are some insights about this topic in the [sklearn documentation](http://scikit-learn.org/stable/auto_examples/plot_multilabel.html)

**Comment by nabihach** [comment]
@wrathagom You're right. The alternative way to define the entities and intents is better and bypasses the issue. I can't think of another use case right now that depicts the ambiguity I discussed. I'll think a bit more on this.

@PHLF Thanks for the links. Let me check them out and then get back to you guys here if I have any questions.

**Comment by wrathagom** [comment]
Glad to help, sorry we weren't able to give you exactly what you were after. I'll close this for now, but feel free to post back with more questions.
