### ISSUE TITLE
Returning training entity value vs. synonym value

### ISSUE THREAD

**Issue by sepheronx** [RasaHQ/rasa_nlu#487]
**rasa NLU version** (e.g. `0.9.1`):

**Used backend / pipeline** (`spacy_sklearn`):

**Operating system** (OSX):

**Issue**: When using Spacy_sklearn pipeline w/ ner_synonym, is there a way to have rasa output the original entity value vs the synonym value? In the documentation, it states "The use of synonyms can also cause the value field not match the text exactly. Instead it will return the trained synonym."

I still want to use ner_synonyms to map words to training set entity values, but in the output, i want to normalize it by having it return the original entity value. e.g. For entity "Topic", the training value is "location" and the synonym value is "position", I want it to return "location" even though the synonym is "position".

The use case is that I'm using the training entity value to determine response logic. e.g. when entity value == "location", respond with X.

**Comment by tmbo** [comment]
I am not sure what you need synonyms for. If you don't want the output to be mapped to a synonym, why have them in the first place? They do not influence the training, adding them will not increase the performance in extracting the synonym.

**Comment by wrathagom** [comment]
@tmbo I also don't follow the use case, but I think I could make an argument for wanting the matched synonym in the return object:

```
"entities": [
		{
			"end": 32,
			"entity": "topic",
			"extractor": "ner_crf",
			"processors": [
				"ner_synonyms"
			],
			"start": 25,
			"value": "position",
                        "original_value": "location"
		}
	]
```

or something like that. Understood I can parse this myself using the start/end and text keys...

**Comment by sepheronx** [comment]
@tmbo @wrathagom Thank you for your input. Sorry if I'm not clear on use case. 

 @wrathagom, that's exactly how I'm using it - Instead of writing more code to map it back, my question is whether there is a way to configure rasa to just return the original value vs. the synonym.

**Comment by wrathagom** [comment]
So your saying you need both? 

If you just need the original value then I don't see why you're using synonyms in the first place.

**Comment by sepheronx** [comment]
I got the answer to my question offline. Thanks for your help.

**Comment by wrathagom** [comment]
Okay I'll close, but if you think it could help the next person with the same question please post the answer you found back here.

Let us know if you need anything else.

**Comment by pranav-nadkarni** [comment]
Hi, I am new to Github and have started using Rasa few days ago. I have the same issue. I get synonym instead of original entity thus my ruleset goes for a toss. Can you help me with the answer you found ? That it should use original entity rather than synonym ?
Thanks in advance.

**Comment by pranav-nadkarni** [comment]
I turned the synonyms off manually by taking them out of Entity synonyms of the model. It worked as an interim solution, is there a better way to have the synonyms in place but use original entity when needed ?

**Comment by wrathagom** [comment]
Please create a new issue if your still having trouble, but as @tmbo said above

> I am not sure what you need synonyms for. If you don't want the output to be mapped to a synonym, why have them in the first place? They do not influence the training, adding them will not increase the performance in extracting the synonym.

if you want to disable synonyms completely you can remove it from the [pipeline](https://rasa-nlu.readthedocs.io/en/latest/pipeline.html#pre-configured-pipelines) in your [configuration](https://rasa-nlu.readthedocs.io/en/latest/config.html).

**Comment by pranav-nadkarni** [comment]
Got it. Thank you.
