### ISSUE TITLE
"advanced" number entity extraction

### ISSUE THREAD

**Issue by yevgenykh** [RasaHQ/rasa_nlu#49]
Hello, 
Is it possible to train Rasa to extract numbers even in "tricky" cases like: 100K -> 100000, 100,000->100000, 100.5K -> 100500 etc. 
wit/number entity managed to extracted it very well.

Thanks, Yevgeny

**Comment by amn41** [comment]
Hey Yevgeny,

I would suggest you try using https://github.com/datamade/parserator for this. So extract the numbers "100K" as entities using rasa, and then pass these to a custom model. 

If this works well I'd love to include this functionality in rasa, so let me know how it goes!
A

**Comment by yevgenykh** [comment]
Hey Alan,
thanks, we'll check it. Elad, our ML expert, already started "playing" with
rasa, which we want to integrate to our system. He may have some questions
(saw that he already wrote to you), so I'll appreciate if you could help in
the beginning if he gets stuck

Thanks again, Yevgeny

**Comment by wrathagom** [comment]
This one has been addressed by the inclusion of duckling in the pipeline http://rasa-nlu.readthedocs.io/en/latest/pipeline.html#ner-duckling
