### ISSUE TITLE
Exception: Failed to validate at component 'ner_crf'. Missing property: 'tokens'

### ISSUE THREAD

**Issue by karnigili** [RasaHQ/rasa_nlu#492]
Hi,
I wrote the code on rasa-nlu 0.9.0a3
using the following pipeline: ["nlp_spacy", "ner_crf", "ner_synonyms", "intent_featurizer_spacy", "intent_classifier_sklearn"]

I moved the code to an venv and downloaded the most recent version rasa-nlu 0.10.0a0.

The code fails on the line trainer.train(training_data). and raises the exceptions in the title.

I read about the cyclic dependencies  between python-crfsuite and sklearn-crfsuite but could not manage to resolve it.

Thank you !

**Comment by karnigili** [comment]
@tmbo in respect to your request on issue #362

**Comment by tmbo** [comment]
You should use the following pipeline:
```
  ["nlp_spacy",
        "tokenizer_spacy",
        "intent_featurizer_spacy",
        "intent_entity_featurizer_regex",
        "ner_crf",
        "ner_synonyms",
        "intent_classifier_sklearn"]
```
Which should resolve your issue. The most important part is the addition of the tokenizer that is missing in your pipeline but needs to be present in the newer version of Rasa for the CRF component to function properly.

**Comment by karnigili** [comment]
@tmbo Thank you :)

**Comment by karnigili** [comment]
@tmbo If I had to use the stable version, what would be the right pipeline to use?

Thank you

**Comment by tmbo** [comment]
This should work with the `0.9.x` versions.

**Comment by tmbo** [comment]
#496

**Comment by coco-egaliciar** [comment]
what is the best pipeline to use with spanish languaje?
