### ISSUE TITLE
Allow components to restrict themselfs to certain languages

### ISSUE THREAD

**Issue by tmbo** [RasaHQ/rasa_nlu#497]
A component should be able to specify that it can only handle certain languages (e.g. there is a Chinese tokenizer in the pipeline that wouldn't make much sense added to a pipeline trained on english sentences).

During pipeline validation it should be checked whether all components support the specified language.

**Comment by Lilylii** [comment]
hi, I have encountered a similar problem in #764. Is there any progress in this issue? Hope to have answers, thanks.

**Comment by tmbo** [comment]
I think the issue you are facing in #764 is a bit different. Even if this is implemented, this is rather a sanity check to ensure that when you use a component in a language the compont doesn't support you will get a warning.

**Comment by tmbo** [comment]
implemented.
