### ISSUE TITLE
Mitie Multiple Intents

### ISSUE THREAD

**Issue by vkrgowtham** [RasaHQ/rasa_nlu#498]
Hi, Is there any way to display multiple intents(assume top 10 intents based on probability) using mitie-classifier ? If not can you please explain the reason behind this.

**Comment by PHLF** [comment]
Hi. Unfortunately, no [as MITIE classifier only output the probability for the predicted class](https://github.com/RasaHQ/rasa_nlu/issues/199#issuecomment-287320034)

**Comment by vkrgowtham** [comment]
Can i tweak the code some where to output different classes probability? As probability is usually generated for each class and it outputs the one with maximum probability.

**Comment by PHLF** [comment]
You have to get your hands dirty [into dlib](https://github.com/mit-nlp/MITIE/blob/master/dlib/dlib/svm/svm_multiclass_linear_trainer.h) and make a PR.
