### ISSUE TITLE
f.write(data) -> f.write(data.encode('utf-8'))

### ISSUE THREAD

**Issue by vinnitu** [RasaHQ/rasa_nlu#499]
https://github.com/RasaHQ/rasa_nlu/blob/03262b1faa37cdbd2989caf9dc94e98e3d58ab43/rasa_nlu/data_router.py#L205

**Comment by PHLF** [comment]
Hum it looks like you were very much in a hurry, so I'll make a sentence for you:

> Hello, wouldn't that be better if the call to f.write() in the [DataRouter.py (line 205)](https://github.com/RasaHQ/rasa_nlu/blob/03262b1faa37cdbd2989caf9dc94e98e3d58ab43/rasa_nlu/data_router.py#L205) would explicitly specify 'utf-8' as encoding? 'cause you know: 'utf-8' is so cool! (disclaimer: this sentence is only the result of my own interpretation)

What would be the point as this is a temporary file used only by Rasa? Did you encounter an issue related to this line?

**Comment by vinnitu** [comment]
Yes, my friend! Sorry for my shor question-propose before )

Yes. If data.json has string like 'grêve général' and processing through /train
it failed with

```
  ...
  File "build/bdist.linux-x86_64/egg/rasa_nlu/data_router.py", line 205, in start_train_process
    f.write(data)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe8' in position 553: ordinal not in range(128)
```

**Comment by PHLF** [comment]
It sounds easy enough for a PR, we just need to make sure that trained components can handle unicode characters.

**Comment by vinnitu** [comment]
maybe pass encoding='utf-8' in params?

**Comment by thaume** [comment]
Hi guys, just opened za PR over here : https://github.com/RasaHQ/rasa_nlu/pull/511

Let me know how that looks !
