### ISSUE TITLE
Relation between Entities and Intents

### ISSUE THREAD

**Issue by vkrgowtham** [RasaHQ/rasa_nlu#503]
Hi,
Q1) Is there any relation between entity and intent classification in the pipeline (or) does both of them function separately in the pipeline? For example training classifier without any entity data will it affect the intent classification ?

Q2) I have read the medium article Alan where he explains even average of word2vec's of a sentence give decent performance. My question is what exactly are you doing to represent a sentence for classification after getting word embeddings for each word ?

Thank you.

**Comment by PHLF** [comment]
1. Yes they work independently
2. Depends on the featurizer you use, for instance [with spacy](https://github.com/RasaHQ/rasa_nlu/blob/76fe1e38c49cac158a3fae55d17eb72af4ef6745/rasa_nlu/featurizers/spacy_featurizer.py#L47)

**Comment by vkrgowtham** [comment]
Thanks for the reply. Do you know about mitie ?

**Comment by wrathagom** [comment]
MITIE is an option for both intent and entity recognition in the Rasa pipeline.  https://rasa-nlu.readthedocs.io/en/latest/pipeline.html#pre-configured-pipelines

**Comment by vkrgowtham** [comment]
For classification we need vector for each sentence. So in the mitie pipeline, after getting spectral word embeddings for each word, what did you do to obtain a single vector for sentence. Is it just an average of all the word embeddings present in the sentence ?

**Comment by wrathagom** [comment]
@PHLF or @tmbo may know the answer to that off the top of their head. I would have to dig through code.

Here's the Rasa MITIE classifier component code if you want to look yourself. https://github.com/RasaHQ/rasa_nlu/blob/master/rasa_nlu/classifiers/mitie_intent_classifier.py

**Comment by vkrgowtham** [comment]
From what i understood from mitie_featurizer.py, it's just an average of all spectral word embeddings present in the sentence.(https://github.com/RasaHQ/rasa_nlu/blob/76fe1e38c49cac158a3fae55d17eb72af4ef6745/rasa_nlu/featurizers/mitie_featurizer.py#L71)
Please correct me @PHLF  @tmbo

**Comment by PHLF** [comment]
Looks like you're right.

**Comment by wrathagom** [comment]
I'm closing, but let us know if you have more questions.
