### ISSUE TITLE
No documentation on how to feed api.ai data to rasa app.

### ISSUE THREAD

**Issue by irfan-zoefit** [RasaHQ/rasa_nlu#508]
I'm looking for a way to use my api.ai data in rasa but so far no success. I did not find any utility or script to use api.ai data. It looks like I have to manually update my training data. 

**rasa NLU version** (`0.9.1`):

**Used backend / pipeline** (`spacy_sklearn`):

**Operating system** (Ubuntu):

**Issue**:

**Content of configuration file** (if used & relevant):
```json
{
  "pipeline": "spacy_sklearn",
  "path" : "./models",
  "data" : "./data/data.json",
  "spacy_model_name": "en_default"
}
```

**Comment by amn41** [comment]
Did you download your data from api.ai? it normally comes as a directory with a bunch of files. You should point the `data` config var to this directory, and you should be able to train. Conversion to rasa format happens automatically. Alternatively you can convert using `python -m rasa_nlu.convert -d /path/to/dir -o my_data.json`, see https://github.com/RasaHQ/rasa_nlu/blob/master/rasa_nlu/convert.py
