### ISSUE TITLE
Update API.ai response emulation to match current format

### ISSUE THREAD

**Issue by irfan-zoefit** [RasaHQ/rasa_nlu#509]
api.ai response for query 

```json
{
  "id": "4d5db452-e2bc-4469-a407-f91c372fa029",
  "timestamp": "2017-08-01T10:04:26.376Z",
  "lang": "en",
  "result": {
    "source": "agent",
    "resolvedQuery": "i want to log my blood pressure",
    "action": "",
    "actionIncomplete": true,
    "parameters": {
      "command": "log",
      "diastolic": "",
      "navModule": "blood_pressure",
      "systolic": ""
    },
    "contexts": [
      {
        "name": "blood_pressure_dialog_context",
        "parameters": {
          "systolic": "",
          "diastolic": "",
          "command.original": "log",
          "navModule.original": "blood pressure",
          "systolic.original": "",
          "navModule": "blood_pressure",
          "diastolic.original": "",
          "command": "log"
        },
        "lifespan": 2
      },
      {
        "name": "blood_pressure_dialog_params_systolic",
        "parameters": {
          "systolic": "",
          "diastolic": "",
          "command.original": "log",
          "navModule.original": "blood pressure",
          "systolic.original": "",
          "navModule": "blood_pressure",
          "diastolic.original": "",
          "command": "log"
        },
        "lifespan": 1
      },
      {
        "name": "80345f9c-838a-41e8-bbe9-1ea165f23764_id_dialog_context",
        "parameters": {
          "systolic": "",
          "diastolic": "",
          "command.original": "log",
          "navModule.original": "blood pressure",
          "systolic.original": "",
          "navModule": "blood_pressure",
          "diastolic.original": "",
          "command": "log"
        },
        "lifespan": 2
      }
    ],
    "metadata": {
      "intentId": "80345f9c-838a-41e8-bbe9-1ea165f23764",
      "webhookUsed": "false",
      "webhookForSlotFillingUsed": "false",
      "intentName": "blood_pressure"
    },
    "fulfillment": {
      "speech": "What is the value of Systolic?",
      "messages": [
        {
          "type": 0,
          "speech": "What is the value of Systolic?"
        }
      ]
    },
    "score": 1
  },
  "status": {
    "code": 200,
    "errorType": "success"
  },
  "sessionId": "20f1c201-12a4-4293-b524-61295a63354b"
}
```
but rasa response misses the fullfillment, contexts and also the some values of parameters. Even format is different for parameters, rasa returning parameters as an array while api.ai as dictionary object in parameters
```json
{
    "id": "d57d0ec4-76a2-11e7-894b-6817298f3f22",
    "result": {
        "action": null,
        "actionIncomplete": null,
        "contexts": [],
        "fulfillment": {},
        "metadata": {
            "intentId": "d57d0ec5-76a2-11e7-894b-6817298f3f22",
            "intentName": {
                "confidence": 0.597486798355622,
                "name": "blood_pressure"
            },
            "webhookUsed": "false"
        },
        "parameters": {
            "command": [
                "Log"
            ],
            "navModule": [
                "Blood Pressure"
            ]
        },
        "resolvedQuery": "I want to log my blood pressure",
        "score": null,
        "source": "agent"
    },
    "sessionId": "d57d0ec6-76a2-11e7-894b-6817298f3f22",
    "status": {
        "code": 200,
        "errorType": "success"
    },
    "timestamp": "2017-08-01T15:18:59.661244"
}
```

**rasa NLU version** (`0.9.1`):

**Used backend / pipeline** (["nlp_spacy", "tokenizer_spacy", "intent_entity_featurizer_regex", "intent_featurizer_spacy", "ner_crf", "ner_synonyms",  "intent_classifier_sklearn"]):

**Operating system** (UBUNTU):

**Issue**:
fullfillment, contexts missing. Response format is different as compared to api.ai
There are also other parameters issues like score is null for rasa but for api.ai is 1

**Content of configuration file** (if used & relevant):
```json
{
  "pipeline": ["nlp_spacy", "tokenizer_spacy", "intent_entity_featurizer_regex", "intent_featurizer_spacy", "ner_crf", "ner_synonyms",  "intent_classifier_sklearn"],
  "path" : "./models",
  "data" : "./data/",
  "spacy_model_name": "en_default",
  "emulate": "api",
  "language": "en"
}
```

**Comment by amn41** [comment]
thanks.

-  format: this does sound like an issue. My guess is that api have updated their API since we last looked at this.
- context, fulfillment. Rasa NLU doesn't support these features. If you want dialogue management, I can give you early access to Rasa Core which does exactly that.

**Comment by irfan-zoefit** [comment]
Yes, I want the access.

**Comment by wrathagom** [comment]
I'll rename this one and re-purpose it for an update to the api.ai output.

**Comment by AbdulrahmanAzmy** [comment]
@amn41 , if possible I want an early access too! :)

**Comment by irfan-zoefit** [comment]
It's has been 2 months yet there is no progress on the issue!! Should I move back to api.ai!?

**Comment by wrathagom** [comment]
I'm actually thinking that @deubaka may have fixed this in #630 and we just didn't notice since there were two separate issues. Can you test the latest?

Also, as you may have noticed Rasa NLU is an open source project. There is a core team behind it, but what they work on is driven by the needs of their business. This issue being labeled as help wanted indicates that we need a member of the community to step in and do it as it's not a priority for the core team at the moment.

If it isn't fixed by #630 then it would be a great pull request.

**Comment by irfan-zoefit** [comment]
Same response in rasa-nlu=0.10.4. as stated above.

**Comment by tmbo** [comment]
@irfan-zoefit the format is created right there:

https://github.com/RasaHQ/rasa_nlu/blob/02c6d6bda3961605127c5f3da2a5bd95a6308b45/rasa_nlu/emulators/dialogflow.py#L36

should be easy to change and adapt to the new format. mind creating a PR?

**Comment by irfan-zoefit** [comment]
Yes, why not.

**Comment by twerkmeister** [comment]
@tmbo I'd have someone who would like to get started contributing to rasa, was thinking handing this issue to him. This has not been solved, right?

**Comment by tmbo** [comment]
Sure thing.

**Comment by twerkmeister** [comment]
:+1:
