### ISSUE TITLE
correctly serialize API.AI imported TrainingData object (to_json and others broken)

### ISSUE THREAD

**Issue by r-wheeler** [RasaHQ/rasa_nlu#510]
**rasa NLU version** (e.g. `0.7.3`):
rasa NLU Version 0.10.0a1 

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...):
Python 3.5 `spacy_sklearn`
**Operating system** (windows, osx, ...):
osx 

**Issue**:

```
training_data = load_data('path/to/apiai/export/')
trainer = Trainer(RasaNLUConfig("rasa_nlu/config_spacy.json"))
trainer.train(training_data)#this works fine 

#This is broken
training_data.as_json()
AttributeError: 'list' object has no attribute 'items'
```
A few other aspects of the api are broken, when looking at the methods on the TrainingData object appear to be broken for me 

self.entity_synonyms.items() 
Would not work as
```
training_data.entity_synonyms
```
is a list 

**Content of configuration file** (if used & relevant):
```json

```

**Comment by znat** [comment]
This issue might be introduced by [this PR](https://github.com/RasaHQ/rasa_nlu/pull/490) 
Would you mind sharing your api.ai data or a sample that reproduces the issue?

**Comment by r-wheeler** [comment]
Sure -- 

Also mentioned [here](https://github.com/RasaHQ/rasa_nlu/issues/509) is Rasa Core that supports dialog management. Can I get access?

**Comment by znat** [comment]
Core is not up to me: @amn41 
Re api.ai, can you upload your data here?

**Comment by amn41** [comment]
@r-wheeler invited you

**Comment by r-wheeler** [comment]
@znat 
Working on getting the data, create a brand new agent with a few entities and a single intent causes the issues as well.

**Comment by r-wheeler** [comment]
@amn41 
Thanks for invite!

**Comment by r-wheeler** [comment]
[test 2.zip](https://github.com/RasaHQ/rasa_nlu/files/1222438/test.2.zip)
