### ISSUE TITLE
Error in persisting the model of a new component

### ISSUE THREAD

**Issue by thaume** [RasaHQ/rasa_nlu#514]
**rasa NLU version** : 0.9.1

**Used backend / pipeline** : custom pipeline

**Operating system** (windows, osx, ...): linux (on docker)

**Content of configuration file** : not relevant

**Issue**:
When creating a new classifier (in `rasa_nlu/classifiers/`) I can do the training alright but I come across a problem in the `persist` hook.

My code is simple, I use exactly the same as the `persist` hook in the sklearn classifier but I get this error :

```
File "/usr/local/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/lib/python2.7/site-packages/cloudpickle/cloudpickle.py", line 631, in save_file
    raise pickle.PicklingError("Cannot pickle closed files")
pickle.PicklingError: Cannot pickle closed files
```

I'm not sure if it is a problem with the size of the model or if there's something that I should do to be able to persist the model (its directory is created and has the good read/write rights).

Thanks !

**Comment by tmbo** [comment]
@thaume The code from the sklearn persist method uses the pickle protocol to persist the trained classifier.

It might not be the best way to persist your component, as it will try to persist all attributes of your components instance. It seems like there is an attribute of your object that can not be pickled (in this case a closed file, e.g. somewhere in your component you got something like `self.

How you can resolve this (there are two ways):
- make sure **all** attributes of your component are pickable 
- only dump the attributes you want (e.g. have a look at the persist implementation of the `crf_entity_extractor.py`, it dumps specific attributes to file and writes other attributes to the metadata)

**Comment by thaume** [comment]
@tmbo thanks I will look into it !
