### ISSUE TITLE
More than one model

### ISSUE THREAD

**Issue by ridhaos** [RasaHQ/rasa_nlu#515]
Hi everyone , i asking for solution in RAsa Nlu, now i know how to use multiple models but i wont if i send a request to rasa_nlu server i dont specify the model name I want my server to detect it ? how can make it ? and thanks all

**Comment by wrathagom** [comment]
You'll need to explain more about what you mean by `detect it`. Do you want it to choose the latest? Do you want it to choose the most recently used? Or you want to detect it with natural language?

It sounds like you should really just be using a single model and allowing it to parse out the correct intent.

**Comment by ridhaos** [comment]
@wrathagom thanks for your answer, i mean by detect it : i suppose that i made many models like weather, restaurant, ... and you want when i send request i dont wont to specify wish model i can use i want it to search in all models and give the best respond.

**Comment by wrathagom** [comment]
Why did you separate them in the first place?

The problem with separating and then rejoining is that the confidence scores won't be weighted the same. So choosing the right intent will not be as straightforward as it seems.

**Comment by sipvoip** [comment]
I also would like to have more then one model. My use case is a support bot that is used by several different companies. I would like to be able to send requests to rasa while specifying the model to use so that companies data can overlap.

**Comment by wrathagom** [comment]
@tmbo @amn41 @PHLF any thought on offering cross-domain or cross-agent parsing? If so I can mark as enhancement and help wanted. Otherwise I'll close.

**Comment by amn41** [comment]
I think it adds a lot of complexity and I wouldn't know to make this work "in general". Let's close - I think this is up to bot developers to create for their use case.
