### ISSUE TITLE
Pipeline config does not look like it is working for me.

### ISSUE THREAD

**Issue by sipvoip** [RasaHQ/rasa_nlu#516]
**rasa NLU version** (e.g. `0.10.0a1`):

**Used backend / pipeline** (`nlp_spacy, ner_mitie, ner_mitner_duckling'):

**Operating system** (Centos 7):

**Issue**:
I am trying to add ner_mitie and ner_duckling to a pipeline, but no matter what I enter with time, number, money, distance I can't get duckling to work. If I enter a city such as New York City, I get back a response from ner_crf but it is not even listed in my config!!! 

    "entities": [
        {
            "end": 32,
            "entity": "internal_apps",
            "extractor": "ner_crf",
            "start": 19,
            "value": "New York City"
        }
    ],

Logs show:
    "pipeline": [
        "nlp_spacy", 
        "ner_mitie", 
        "ner_duckling"
    ], 

**Content of configuration file** (if used & relevant):
{
  "pipeline": ["nlp_spacy", "ner_duckling"],
  "language": "en",
  "num_threads": 2,
  "max_training_processes": 2,
  "path" : "./models",
  "data" : "./data/uc-one-apiai",
  "response_log": "logs",
  "log_level": "DEBUG",
  "port": 5000,
  "mitie_file": "data/total_word_feature_extractor.dat",
  "spacy_model_name": "en_core_web_sm",
  "duckling_dimensions": ["time", "number", "amount-of-money", "distance"]
}

**Comment by wrathagom** [comment]
What command are you using to run Rasa?

**Comment by sipvoip** [comment]
python -m rasa_nlu.server -c config_apiai_spacy.json --server_model_dirs=../models/model_20170807-122102

I believe it is reading my config because I see the pipeline listed in the logs.

**Comment by wrathagom** [comment]
in `../models/model_20170807-122102/metadata.json`. What is the pipeline shown there?

**Comment by sipvoip** [comment]
Thanks, did not realize that overwrote my config.

**Comment by wrathagom** [comment]
the pipeline in the config is what is used when training new models. But an already trained model will use the pipeline from when it was trained...

Try:
["nlp_mitie", "tokenizer_mitie", "ner_mitie", "ner_synonyms", "intent_entity_featurizer_regex", "intent_classifier_mitie", "ner_duckling"]

**Comment by wrathagom** [comment]
@tmbo can we add a `pipeline dependencies`: to each pipeline component. That way we have a place that documents what components are required upstream in the pipeline to work.
