### ISSUE TITLE
When parsed entity is numerical replace synonyms fails due to exceptions.AttributeError: 'float' object has no attribute 'lower'

### ISSUE THREAD

**Issue by sipvoip** [RasaHQ/rasa_nlu#517]
**rasa NLU version** (e.g. `0.10.01a`):

**Used backend / pipeline** (`"nlp_spacy", "tokenizer_spacy", "intent_entity_featurizer_regex", "intent_featurizer_spacy", "ner_duckling", "ner_crf", "ner_synonyms",  "intent_classifier_sklearn"'):

**Operating system** (Linux):

curl -XPOST 10.88.0.9:5000/parse -d '{"q":"He was 6 feet away"}' | python -mjson.tool

2017-08-07 17:29:18+0000 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 500, in errback
	    self._startRunCallbacks(fail)
	  File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 567, in _startRunCallbacks
	    self._runCallbacks()
	  File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 1442, in gotResult
	    _inlineCallbacks(r, g, deferred)
	--- <exception caught here> ---
	  File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
	    result = result.throwExceptionIntoGenerator(g)
	  File "/usr/lib64/python2.7/site-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
	    return g.throw(self.type, self.value, self.tb)
	  File "/root/rasa_nlu/rasa_nlu/server.py", line 127, in parse_get
	    else threads.deferToThread(self.data_router.parse, data))
	  File "/usr/lib64/python2.7/site-packages/twisted/python/threadpool.py", line 250, in inContext
	    result = inContext.theWork()
	  File "/usr/lib64/python2.7/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
	    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
	  File "/usr/lib64/python2.7/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/usr/lib64/python2.7/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "rasa_nlu/data_router.py", line 199, in parse
	    response = model.parse(data['text'], data.get('time', None))
	  File "rasa_nlu/model.py", line 246, in parse
	    component.process(message, **self.context)
	  File "rasa_nlu/extractors/entity_synonyms.py", line 50, in process
	    self.replace_synonyms(updated_entities)
	  File "rasa_nlu/extractors/entity_synonyms.py", line 81, in replace_synonyms
	    if entity_value.lower() in self.synonyms:
	exceptions.AttributeError: 'float' object has no attribute 'lower'

**Content of configuration file** (if used & relevant):
{
  "pipeline": ["nlp_spacy", "tokenizer_spacy", "intent_entity_featurizer_regex", "intent_featurizer_spacy", "ner_duckling", "ner_crf", "ner_synonyms",  "intent_classifier_sklearn"],
  "language": "en",
  "num_threads": 4,
  "max_training_processes": 4,
  "path" : "./models",
  "data" : "./data/uc-one-apiai",
  "response_log": "logs",
  "log_level": "DEBUG",
  "port": 5000,
  "mitie_file": "data/total_word_feature_extractor.dat",
  "spacy_model_name": "en",
  "duckling_dimensions": ["time", "number", "amount-of-money", "distance"]
}

**Comment by PHLF** [comment]
Did you define any synonyms in your training data? Check if all among all the synonyms you defined there is no number. Also check the content of your `entity_synonyms.json` file in your model folder If any number is defined as a synonym, try to add some `"` around them.

**Comment by sipvoip** [comment]
Looks like I have one, "3-way", but I have " around it.  

{"desktop phone": "Desktop phone", "share my screen": "screen share", "desktop  application": "Desktop  Application", "presence": "presence status", "pick up": "receive", "my room": "my Room", "video": "Video", "thanks": "Thanks", "personalise": "personalize", "parking": "park", "colleague": "Colleague", "presence status": "Presence Status", "three-way": "three way", "3-way": "three way", "availability": "presence status", "files": "Files", "invite": "Invite", "conference": "three way", "customise": "personalize", "participant": "Participant", "hub": "Hub", "broadworks": "BroadWorks", "uc-one client": "UC-One client", "user": "User", "share your screen": "share your Screen", "hey": "Hey", "send": "Send", "desktop": "Desktop Application", "start": "Start", "add": "Add", "internal": "colleague", "call": "Call", "myroom": "MyRoom", "answer": "receive", "third party": "external", "3rd party": "external", "alter": "change", "friend": "colleague", "cloud apps": "Cloud Apps", "status": "status message", "presence  status": "Presence  Status", "my  room": "My  Room", "configure": "Configure", "attend": "receive", "internal guest": "guest", "screen  share": "Screen  share", "join": "Join", "third-party": "external", "modify": "change", "personalize": "Personalize", "cloud  apps": "Cloud  Apps", "visual": "video", "hi": "Hi", "external": "External", "anywhere": "Anywhere", "pull": "Pull", "external  guest": "External  Guest", "without": "Without", "change": "Change", "guest": "Guest", "desktop application": "Desktop Application", "account": "Account", "3 way": "three way", "three way": "Three way", "broad works": "broadworks", "calls": "Calls", "mobile": "phone", "voice": "Voice", "bot": "Bot", "location": "Location", "external guest": "External Guest", "thank you": "Thank you", "initiate": "Initiate", "contact": "Contact", "place": "initiate", "client": "Client", "pick": "receive", "uc one client": "UC One client", "audio": "voice", "hello": "Hello", "connect": "Connect"}

**Comment by wrathagom** [comment]
Did you try wrapping occurrences of `entity_value` with `str()` so: `str(entity_value).lower()`? That probably not the best long term fix, but it may get you going.

Coming up with a more elegant solution to this may be bit more involved if my understanding of precision in python is correct.

**Comment by sipvoip** [comment]
Changing it to str(entity_value) fixed the issue, should someone change it in the code?

**Comment by wrathagom** [comment]
I'll leave that up to @tmbo to decide if that is the solution he wants, but yep we'll get it fixed.
