### ISSUE TITLE
(concurrency?) Issue with components validation

### ISSUE THREAD

**Issue by znat** [RasaHQ/rasa_nlu#518]
**rasa NLU version**:0.10.1a

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...):
["nlp_spacy", "tokenizer_spacy", "intent_entity_featurizer_regex", "intent_featurizer_spacy", "ner_crf", "ner_synonyms", "ner_duckling", "intent_classifier_sklearn"]

**Issue**:
When running Rasa (training or serving), component validation fails because of a missing requirement (duckling, which is properly installed and visible with `pip show duckling`).

However, when [setting a breakpoint here](https://github.com/RasaHQ/rasa_nlu/blob/master/rasa_nlu/components.py#L83) and stopping at every iteration, it works, which makes it look like some concurrency issue.

**Comment by wrathagom** [comment]
Can we get the actual log output? Trying to cross check with previous issues, this looks familiar.

**Comment by znat** [comment]
Hi @wrathagom, this morning it works like a charm and I can't reproduce the error. But the only logs I had were the [exception raised here](https://github.com/RasaHQ/rasa_nlu/blob/master/rasa_nlu/components.py#L94), stating duckling requirement was missing.

**Comment by wrathagom** [comment]
Okay, I'll guess I'll close until it re-occurs.

**Comment by znat** [comment]
Not sure the fact it happens randomly justifies closing the issue

**Comment by wrathagom** [comment]
The justification I saw was actually that you couldn't reproduce and neither could I. Thus if it re-occurs maybe it will shed more light on how to re-produce it.
