### ISSUE TITLE
Unable to load total_word_feature_extractor detector from data\total_word_feature_extractor.dat

### ISSUE THREAD

**Issue by ankitarath2011** [RasaHQ/rasa_nlu#519]
**rasa NLU version** (e.g. `0.7.3`): 0.9.1

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...):   mitie_sklearn

**Operating system** (windows, osx, ...):   windows 10

**Issue**: I have kept "total_word_feature_extractor.dat" file in data folder. still I am getting error saying unable to load this file. Please find below my code.

```
from __future__ import unicode_literals

import io, logging, json, sys
from rasa_nlu.training_data import TrainingData
from rasa_nlu.model import Interpreter, Trainer
from rasa_nlu.config import RasaNLUConfig
from rasa_nlu.converters import load_data
import rasa_nlu

sys.path.append("C:/Users/ankita.a.rath/Desktop/my_codes/Rasa_nlu/MITIE-master/mitielib")


def pprint(o):
    print(json.dumps(o, indent=2))

logging.basicConfig(level="INFO")

model_config = {
    "pipeline": [ "nlp_mitie",
                  "tokenizer_mitie",
                  "ner_mitie",
                  "ner_synonyms",
                  "intent_entity_featurizer_regex",
                  "intent_featurizer_mitie",
                  "intent_classifier_sklearn" ],
    "language": "en"
}

config = RasaNLUConfig(cmdline_args=model_config)
trainer = Trainer(config)
train_file = "C:/Users/ankita.a.rath/Desktop/my_codes/Rasa_nlu/rasa_nlu-master/data/examples/rasa/demo-rasa.json"
training_data = load_data(train_file)
interpreter = trainer.train(training_data)
logging.info("done")

result = interpreter.parse("Tell me mexican restaurant near Bellandur")
print result
```

Also I do not know where to mention the "config_mitie_sklearn.json". 

Tried executing "python -m rasa_nlu.train -c config_mitie_sklearn.json" in command prompt. But got following error.
```

Exception: Not all required packages are installed. Failed to find the following imports mitie. To use this pipeline, you need to install the missing dependencies, e.g. by running:
        > pip install git+https://github.com/mit-nlp/MITIE.git#egg=mitie
```
when I executed the above command it is saying

```
rasa_nlu_master>pip install git+https://github.com/mit-nlp/MITIE.git#egg=mitie
Requirement already satisfied: mitie from git+https://github.com/mit-nlp/MITIE.git#egg=mitie in c:\users\ankita.a.rath\mitie
```

Please help me out.

**Comment by wrathagom** [comment]
As far as the code when you try to execute your script can you try to add the absolute path for `"mitie_file": "C:/PATH/TO/total_word_feature_extractor.dat"` to your `model_config`?

As for the not all required packages: are you running in a venv or something similar? Looks to me like you've got multiple versions of python overlapping, but maybe I am missing something else.

Does everything run if you execute something that doesn't rely on mitie like `python -m rasa_nlu.train -c config_spacy.json`

**Comment by ankitarath2011** [comment]
I gave absolute path and tried. But still same issue. 
I am not running in venv, trying in windows 10 and yes I have installed both python 2.7 and 3.6. But have added only 2.7 in env variable.

spacy installation is failing. So unable to run "python -m rasa_nlu.train -c config_spacy.json" command. Moreover I want to use Mittie+sklearn

**Comment by tmbo** [comment]
@ankitarath2011 So the remaining issue is, that you get the 
```
Exception: Not all required packages are installed. Failed to find the following imports mitie. To use this pipeline, you need to install the missing dependencies, e.g. by running:
        > pip install git+https://github.com/mit-nlp/MITIE.git#egg=mitie
```
Error message?

You are most certainly running Rasa NLU with a different python (or in a different environment). Make sure you are in the correct environment before executing the above mitie installation command.

**Comment by ankitarath2011** [comment]
I am using Python2.7. Now I have uninstalled Python3.6 from my system. Still getting the issue.

**Comment by tmbo** [comment]
Try running `import mitie` in a python console (make sure you are using the same environment here as you are using when running Rasa NLU)

**Comment by ankitarath2011** [comment]
I am not getting any error when I am doing `import mitie` in a python console

**Comment by wrathagom** [comment]
@ankitarath2011 were you able to get this going?

**Comment by ankitarath2011** [comment]
No that thing did not work. I am using spacy+sklearn :)
