### ISSUE TITLE
"EOFError: Ran out of input" when trying to train the model remotely

### ISSUE THREAD

**Issue by xz348** [RasaHQ/rasa_nlu#520]
**rasa NLU version**: 0.9.1

**Used backend / pipeline**: spacy_sklearn

**Operating system**: Windows 10

**Issue**: When trying to train the model through HTTP POST request, the following error occurs on the server end and sometimes python (v3.5) crashes simultaneously.

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\user name\AppData\Local\Programs\Python\Python35\lib\multiprocessing\spawn.py", line 106, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\user name\AppData\Local\Programs\Python\Python35\lib\multiprocessing\spawn.py", line 116, in _main
    self = pickle.load(from_parent)
EOFError: Ran out of input

**Content of configuration file** (if used & relevant):
```
(The default demo_rasa.json file.)
```

**Comment by wrathagom** [comment]
Can you provide the command you're using to POST?

Your config file?

and the specs of your server?

**Comment by RachaRatan** [comment]
I am having the same issue. Can anyone please help me to fix this. I am trying to execute 'http://localhost:5000/train' using post method nowhere it working giving the same error as above mentioned. 
When am training the same using commands it is working find but remotely not working.
Please help me to fix this.

**Comment by tmbo** [comment]
Did you install using pypi or the latest master version from github?

**Comment by RachaRatan** [comment]
Yes I have installed using 'pip install' and my operating system is windows server 2012 rs standard.

**Comment by RachaRatan** [comment]
Can anyone help me on this

**Comment by tmbo** [comment]
Can you please also state what you are `POST`ing to that URL, i.e. the body of the request?

**Comment by wrathagom** [comment]
This same issue is being discussed by the same person in #586 sounds like @PHLF found the problem there.

Now that they're linked going to close this one.

**Comment by RachaRatan** [comment]
Hi @wrathagom, we have discussed regarding this in #586 but I have not get resolution there.
I think you got to know what I did for taring and what is my issue.
I can not go with linux so Help me to fix this in windows server.

**Comment by PHLF** [comment]
Hi @RachaRatan. You didn't answer to my last reply in #586: did you try to run it with MITIE? Not that I expect it to work but at least we could have more details regarding your issue.  
Moreover you cannot go with Linux, fair enough. But did you get a look at what @wrathagom and I mentionned? Respectively running [Rasa Docker image](https://github.com/RasaHQ/rasa_nlu#install) or using [Windows Subsystem for Linux](https://msdn.microsoft.com/en-us/commandline/wsl/install_guide).

**Comment by RachaRatan** [comment]
Hi @PHLF, I tried to install mitie but i faced an issue as in below image.

![image](https://user-images.githubusercontent.com/30255507/30856436-fc238076-a2d5-11e7-994d-5a33b38da1df.png)

And also I tried to user the Docker but as am using VMWare am not able to setup Docker successfully. As in below in image, It is asking me to enable VT-x/AMD-v which I can't enable as my mechine VMWare which was created in Data center where I have installed Rasa and doing my training.

![image](https://user-images.githubusercontent.com/30255507/30856535-4c489d66-a2d6-11e7-8664-ea9fe0392313.png)

Please suggest what I can do further.

**Comment by tmbo** [comment]
Did you install `mitie`? if not either go with sklearn or install mitie, e.g. by following the instructions for windows using a prepackaged build https://github.com/mit-nlp/MITIE#precompiled-python-27-binaries

**Comment by PHLF** [comment]
MITIE is not available as a PIP package: look at [how MITIE is installed for Travis](https://github.com/RasaHQ/rasa_nlu/blob/master/.travis.yml#L26).  
If you cannot use docker, try [WSL](https://msdn.microsoft.com/en-us/commandline/wsl/install_guide).

**Comment by RachaRatan** [comment]
Now I have tried to train Rasa using HTTP end point 
http://localhost:4000/train?model=people

I am getting "forbidden" error instead of "Run out of input" error.
I am giving the data input as below.

{
  "rasa_nlu_data": {
    "common_examples": [
      {
        "entities": [
          {
            "entity": "RideTime",
            "value": "later",
            "start": 0,
            "end": 5
          }
        ],
        "intent": "None",
        "text": "later"
      },
      {
        "entities": [],
        "intent": "ServiceRequestEnquiry",
        "text": "wake up"
      },
      {
        "entities": [],
        "intent": "ConfirmationNo",
        "text": "no not now"
      },
      {
        "entities": [],
        "intent": "ConfirmationNo",
        "text": "not sure"
      },
      {
        "entities": [],
        "intent": "ConfirmationNo",
        "text": "no bot"
      },
      {
        "entities": [],
        "intent": "ConfirmationNo",
        "text": "no goride bot"
      },
      {
        "entities": [
          {
            "entity": "RideTime",
            "value": "later",
            "start": 12,
            "end": 17
          }
        ],
        "intent": "BookCab",
        "text": "book a ride later"
      },
      {
        "entities": [
          {
            "entity": "RideTime",
            "value": "now",
            "start": 21,
            "end": 24
          }
        ],
        "intent": "BookCab",
        "text": "i want go for a ride now"
      },
      {
        "entities": [
          {
            "entity": "RideTime",
            "value": "today",
            "start": 12,
            "end": 17
          }
        ],
        "intent": "BookCab",
        "text": "book a ride today"
      },
      {
        "entities": [
          {
            "entity": "RideTime",
            "value": "today 5pm",
            "start": 18,
            "end": 27
          }
        ],
        "intent": "BookCab",
        "text": "I want to go ride today 5pm"
      },
      {
        "entities": [
          {
            "entity": "RideTime",
            "value": "today",
            "start": 12,
            "end": 17
          }
        ],
        "intent": "BookCab",
        "text": "book a ride today 5pm"
      },
      {
        "entities": [
          {
            "entity": "RideTime",
            "value": "later",
            "start": 13,
            "end": 18
          }
        ],
        "intent": "BookCab",
        "text": "book shuttle later"
      },
      {
        "entities": [
          {
            "entity": "RideTime",
            "value": "now",
            "start": 15,
            "end": 18
          }
        ],
        "intent": "None",
        "text": "i want to book now"
      },
      {
        "entities": [
          {
            "entity": "RideTime",
            "value": "booknow",
            "start": 10,
            "end": 17
          }
        ],
        "intent": "None",
        "text": "i want to booknow"
      },
      {
        "entities": [
          {
            "entity": "RideTime",
            "value": "book later",
            "start": 10,
            "end": 20
          }
        ],
        "intent": "None",
        "text": "i want to book later"
      }
    ],
    "regex_features": []
  }
}

and find the screen shot of postman as below.

![image](https://user-images.githubusercontent.com/30255507/30857774-a6728abe-a2da-11e7-9160-d54973e5423f.png)
 I have given data and option as suggest by @PHLF.
before I was found "Run out of input exception" now it is showing "forbidden exception".
may I know your comments on it. Please suggest.

**Comment by wrathagom** [comment]
Make sure core is configured properly: http://rasa-nlu.readthedocs.io/en/latest/config.html#cors-origins

**Comment by RachaRatan** [comment]
I am using config_spacy file with below content.

{
  
"name": "People",
"pipeline" : ["nlp_spacy", "tokenizer_spacy", "intent_featurizer_spacy", 
              "ner_crf", "ner_synonyms", "intent_classifier_sklearn", 
              "ner_duckling","ner_spacy"],
  
"path" : "./models",
  
"data" : "./data/examples/rasa/People.json"

}
 I am able to train with cmd "
![image](https://user-images.githubusercontent.com/30255507/30858261-91484852-a2dc-11e7-9a1c-b94e8cdb972f.png)
"
but with HTTP end point am facing this issue.

**Comment by PHLF** [comment]
As @wrathagom said: you have to setup correctly your [`cors_origins` parameter](http://rasa-nlu.readthedocs.io/en/latest/config.html#cors-origins). With CORS enabled, if the domain from which you're sending your request is not the same as the Rasa NLU server's domain, you'll get this `403, forbidden` error.

**Comment by RachaRatan** [comment]
I have tried with below cors origin. Now my config file looks like.
{
  
"name": "People",
"pipeline" : ["nlp_spacy", "tokenizer_spacy", "intent_featurizer_spacy", 
              "ner_crf", "ner_synonyms", "intent_classifier_sklearn", 
              "ner_duckling","ner_spacy"],
  
"path" : "./models",
"port" : 4000,
"cors_origins":['auto.local'],
"data" : "./data/examples/rasa/People.json"

}

but am not able to start the server am getting an issue as below.

![image](https://user-images.githubusercontent.com/30255507/30861030-15f1f36e-a2e7-11e7-8fc1-bc16ed5c1073.png)

"auto.local" is my on premises server domine.
 
 did I mention cors origin in wrong way? how can I mention cors_orgin parameters ?

**Comment by PHLF** [comment]
Strings in JSON are defined between `"` not `'`. Moreover auto.local is not a valid domain address. Just use `"cors_origins" : ["*"]`: that'll disable CORS and you'll be able to use the server.

**Comment by RachaRatan** [comment]
Now it is working properly with training using HTTP end point but parse request is not returning proper intent results.
can you please check issue #611 and get me some help to resolve it.

**Comment by RachaRatan** [comment]
Can any body help me on this.

**Comment by shaqb4** [comment]
@RachaRatan Sorry to keep this issue going, but I'm having the same problem. How did you end up getting rid of the error when attempting to train with the HTTP end point?

**Comment by RachaRatan** [comment]
Yes, @shaqb4 I have resolved it by upgrading Rasa nlu
