### ISSUE TITLE
Improve documentation about existing predefined entities

### ISSUE THREAD

**Issue by ne00346536** [RasaHQ/rasa_nlu#522]
Hi Team,

Can you please let me know how to add system/predefined entities in Rasa .

Ex: 1) please book conf call tomorrow at 9am. Here tomorrow is the date picker need to identify as date entity and share the date

Ex 2) book conf call tomorrow for thirty mins at 9am . Here  either user mentioning the duration in numbers/ words need to detect it.

Can you please let me know how to achieve the above use cases.?

Thanks,
Naresh

**Comment by PHLF** [comment]
Hi,

   Could [this](https://rasa-nlu.readthedocs.io/en/latest/pipeline.html#ner-duckling) be what you are looking for?

**Comment by tmbo** [comment]
Additionally, there are already trained entities from the spacy model: 

https://spacy.io/docs/usage/entity-recognition#entity-types

Should add a section for that use case to the documentation.

**Comment by Zbigatron** [comment]
Oh yes! I would also like to know how to leverage spaCy's default model rather than having to train my own. Any chance someone could give a quick summary of how to do this here?

**Comment by tmbo** [comment]
solved with the new documentation.
