### ISSUE TITLE
Server gets killed while loading second spacy model

### ISSUE THREAD

**Issue by HansKannsNLP** [RasaHQ/rasa_nlu#523]
**rasa NLU version** : 0.9.0a3

**Used backend / pipeline** : spacy_sklearn

**Operating system** : docker

**Issue**:
```
INFO:rasa_nlu.data_router:Logging requests to '/app/rasa_nlu_test/logs/rasa_nlu_log-20170811-142255-47.log'.
INFO:rasa_nlu.data_router:Loading model './model_Default'...
INFO:rasa_nlu.utils.spacy_utils:Trying to load spacy model with name 'en_core_web_md'
INFO:rasa_nlu.components:Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en_core_web_md'.
INFO:rasa_nlu.data_router:Loading model './de'...
INFO:rasa_nlu.utils.spacy_utils:Trying to load spacy model with name 'de'
Killed
```
If i use two diffrent languages the server gets killed. I did not try it with another (stable) Version of rasa. And i did not try to change the order of loading the languages.

**Content of configuration file** (if used & relevant):
```
{
    "language": "en",
    "spacy_model_name": "en",
    "path": "./models/en/",
	"log_level": "INFO",
    "data": "./data/default.json",
    "pipeline": [
        "nlp_spacy",
        "ner_crf",
        "ner_synonyms",
        "intent_featurizer_spacy",
        "intent_classifier_sklearn"
    ],
    "server_model_dirs": {
		"model_en" :"./model_Default",
		"model_de" :"./de"
		}
}
```

**Comment by amn41** [comment]
I suspect you're running out of memory. How much RAM do you have? The german model is quite big and takes up ~1Gb on its own

**Comment by HansKannsNLP** [comment]
Did not tried a lot because the laptop is in the office and i will get there back on wednesday. I will have a look than and answer back but sounds like the "issue" maybe is solved already :)

**Comment by HansKannsNLP** [comment]
Ups

**Comment by HansKannsNLP** [comment]
@amn41  your guess was right. I looked for my memory and while loading the second model it passed the max size and get killed. Before testing i run with 2GB and with one model it is enough but loading two models consumes 2,7GB for me and after setting the max size higher it works.

Thanks for the fast help and i think i can close this because its no bug rather than a "memory problem" of my site 👍
