### ISSUE TITLE
ascii-error on train-endpoint

### ISSUE THREAD

**Issue by mnannt** [RasaHQ/rasa_nlu#524]
**rasa NLU version**: `0.9.1`

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...): `spacy_sklearn`

**Operating system** (windows, osx, ...): `osx`

**Issue**:
When I post a json-file with expressions with unicode characters (e.g. euro sign (€)) to the servers' /train endpoint, I get an "500 Internal Server Error" response and the server-logs say:
`UnicodeEncodeError: 'ascii' codec can't encode character u'\u20ac' in position 72: ordinal not in range(128)`

My steps:
`expressions.json`:
```json
{
  "rasa_nlu_data": {
    "common_examples": [
      {
        "text": "50 €",
        "intent": "set_price",
        "entities": []
      }
    ]
  }
}
```
- `curl -XPOST localhost:5000/train -d @expressions.json`
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
```

**Content of configuration file** (if used & relevant):
```json

```

**Comment by tmbo** [comment]
Can you please try with the latest version on github, I think that has already been fixed.

**Comment by mnannt** [comment]
Hey Tom, thanks for the quick answer :-)
But unfortunately it doesn't work with the newest version. "klein" just prints the error in a different way

`curl -XPOST localhost:5000/train -d @expressions.json`
```
{"error": "'ascii' codec can't encode character u'\\u20ac' in position 72: ordinal not in range(128)"}%
```

**Comment by tmbo** [comment]
Yes you are right, hasn't been merged yet: https://github.com/RasaHQ/rasa_nlu/pull/511

**Comment by tmbo** [comment]
Fix has been merged, so you should be good to go when using the latest version from the repository.

**Comment by poojapawar123** [comment]
When I click on start training button,it gives error like Error Occured when posting data to nlu endpoint in rasa nlu.error :Invalid protocol
