### ISSUE TITLE
Dialog and context with rasa

### ISSUE THREAD

**Issue by MoAbd** [RasaHQ/rasa_nlu#525]
How to make a context and Dialog using rasa.nlu ?

**Comment by wrathagom** [comment]
e-mail hi@rasa.ai or ask @amn41 for access to [Rasa Core](http://rasa.ai/products/rasa-core/) or use a service similar to [botkit](https://www.botkit.ai).

**Comment by MoAbd** [comment]
@wrathagom many thanks

**Comment by MoAbd** [comment]
@amn41  can U please give me access to Rasa Core?
