### ISSUE TITLE
start and end in json scripts

### ISSUE THREAD

**Issue by jloveric** [RasaHQ/rasa_nlu#527]
Hi, I'm curious why 'start' and 'end' need to be specified in the json scripts.  Could those positions not be computed after the fact using substring matching when the files are loaded?  Maybe they are when the value matches the string in the text?  Seems like that should be the default.

Thanks,

John

**Comment by wrathagom** [comment]
Entity extraction is just about where in the sentence a word occurs as it is which works occurs. A good example of this would be `I'm looking for a plane from New York to New York` the first being labeled as the origin and the second as the destination. It may be a bit of a contrived example, but if I think about it even harder then I probably could come up with better results. 

I think the most common use cases generate this training data in an [interface](https://github.com/RasaHQ/rasa-nlu-trainer) or programmatically so the pain of finding the position isn't felt by a user.

**Comment by tmbo** [comment]
@jloveric If you want to skip calculating the start and end values, you can also use the alternative data format:
https://rasa-nlu.readthedocs.io/en/latest/dataformat.html#markdown-format

(be aware though that this is only available in the latest version on github and not released to the version on pypi)
