### ISSUE TITLE
Unable to recognize basic entities such as money/currency,time,organizations using spacy_sklearn

### ISSUE THREAD

**Issue by gurunathpr** [RasaHQ/rasa_nlu#533]
rasa-NLU version : 0.9.1

Used backend / pipeline: `spacy_sklearn`

OS: Ubuntu 16.04

Issue:

- In Spacy ,I was able to do NER for basic entities like date,time,money,etc which were included in Spacy model by default. 
However even though I am using spacy_sklearn as backend here,I am unable to get the basic entities such as date,time,amount,organization names,etc.

**Comment by tmbo** [comment]
The `spacy_sklearn` pipeline doesn't use the pretrained entities by default. To add the pretrained spacy entities to your pipeline, change the `pipeline` configuration value in your configuration to something like:
```
  "pipeline": [
        "nlp_spacy",
        "tokenizer_spacy",
        "intent_featurizer_spacy",
        "intent_entity_featurizer_regex",
        "ner_spacy",
        "ner_crf",
        "ner_synonyms",
        "intent_classifier_sklearn",
    ]
```

Notice the added `ner_spacy` component which is responsible for annotating pretrained entities.

**Comment by gurunathpr** [comment]
Thanks
