### ISSUE TITLE
A simple restaurant search bot — IS NOT showing up expected results ..

### ISSUE THREAD

**Issue by projectlab1** [RasaHQ/rasa_nlu#537]
**rasa NLU version** :       **0.10.0a1  (python3)**

**Used backend / pipeline** :  **Spacy**

**Operating system** :   **Mac**

**Issue**: 
I have installed rasa_nlu following the instructions provided at https://rasa-nlu.readthedocs.io/en/latest/installation.html#section-backends . However, the results, I got using the test queries are not same as, that are posted on the tutorial. For example, in case of the query ------> 

“ **$ curl -XPOST localhost:5000/parse -d ‘{“q”:”I am looking for Chinese food”}’ | python -mjson.tool** ”

The tutorial shows that the expected results would be -

`{
    "text": "I am looking for Chinese food",
    "entities": [
        {
          "start": 8,
          "end": 15,
          "value": "chinese",
          "entity": "cuisine",
          "extractor": "ner_spacy"
        }
    ],
    "intent": {
        "confidence": 0.6485910906220309,
        "name": "restaurant_search"
    },
    "intent_ranking": [
        {
            "confidence": 0.6485910906220309,
            "name": "restaurant_search"
        },
        {
            "confidence": 0.14161531595656784,
            "name": "affirm"
        }
    ]
}`

**However, I got the following results —**

`{
“entities”: [],
“intent”: {
“confidence”: 1.0,
“name”: “greet”
},
“text”: “I am looking for Chinese food”
}`

**The results are showing that the intent of the query is “greet” , which is not the case**. I am looking for help to analyze and resolve this issue.

**Comment by wrathagom** [comment]
Directly below the expected results in the tutorial it says this

> If you are using the spacy_sklearn backend and the entities aren’t found, don’t panic! This tutorial is just a toy example, with far too little training data to expect good performance.

It should work if using the mitie backend, but the spacy backend requires more training data.

**Comment by projectlab1** [comment]
Thank you very much @wrathagom . Using mitie it worked :D  .
