### ISSUE TITLE
print welcome message after pip install

### ISSUE THREAD

**Issue by amn41** [RasaHQ/rasa_nlu#538]
For users installing from PyPI, I think it would be great to print a 'welcome to rasa' message with links to the documentation and the gitter channels for support.

**Comment by azie-ginanjar** [comment]
@amn41 could I take on this one?

**Comment by wrathagom** [comment]
I'd say go for it, no one else has claimed it or made a PR for it.

**Comment by azie-ginanjar** [comment]
ok then

**Comment by azie-ginanjar** [comment]
PR submitted : #541

**Comment by wrathagom** [comment]
merged
