### ISSUE TITLE
What is the best way to train ?

### ISSUE THREAD

**Issue by AbdulrahmanAzmy** [RasaHQ/rasa_nlu#540]
I'm using mitie_sklearn and I want to ask about some things,

1) What is the best way to make data-set for the training? are there any optimum values? Also What is the optimum value for the number of data points per entity?
e.g. say I have 8 entity should each one of them contain equal numbers of data points? assume I have 100 data points on one of them. all of them should be the same ?

2) Should I make combination or rasa capable of doing combinations? 
e.g. a) What is John's Last name.
       b) What is John's age ?. 
Should I train the third one like - Tell me The Last name and Age of John's. 
or it doesn't need to be trained with combinations?

3)What is the best way to extract the generic entities such as "objects name" as it may contain any values e.g.  please tell me the price of XYZ.
I want to extract entity of XYZ as an Object name.

Thank you :)

**Comment by wrathagom** [comment]
1. The optimum number is whatever number it takes for your model to work well. Google overfitting vs undercutting. Ideally intent examples would be balanced, but entities don't need to be.
2. The more natural way someone would ask the second question is `What is his age?` using the context of the first question. This can be accomplished with [Rasa Core](http://rasa.ai/products/rasa-core/).
3. I have no idea what you're asking. [Entities are part part of the training data format](http://rasa-nlu.readthedocs.io/en/latest/dataformat.html#common-examples). So XYZ would be labeled as an entity and it would be extracted with a value and a named. That's what makes it Named Entity Recognition.

**Comment by AbdulrahmanAzmy** [comment]
Many thanks @wrathagom ,
let me explain what I meant in the 3rd one .
I know when extracting an entity like 'person' , the classifier would be robust to that , but what if I want to extract multiple entities like [SW engineer, programmer, student, etc..] and they all are persons and the context almost the same? what is the best way to handle this problem using rasa_nlu?

**Comment by wrathagom** [comment]
Seeing as you created a new issue for the 3rd question #548  I am guessing the other 2 are resolved. I'll close, but if you're still having trouble (not relating tot he 3rd item) then we can re-open.
