### ISSUE TITLE
Adding my own place names

### ISSUE THREAD

**Issue by gagan-bansal** [RasaHQ/rasa_nlu#542]
**rasa NLU version**:  0.10.0a2

**Used backend / pipeline** : mitie_sklearn

**Operating system**:  CentoOS 7

**Issue**:  This is great work and I am getting good result. I want to know one thing that for sure must be available. I am extracting the place names by training the entities marked place_name in training set. Its working fine, the issue arises when place name is comprised of more than one word.
Examples:
word1 word2: It extracts two entities as place_name word1 and word2 e.g "Khanjr Pur" 
or the words which are from dictionary, dropped and remaining is returned as  entity e.g "Gateway of India"

I have all place names for my region. So is it possible to add all place names somewhere so that proper place_name entity is extracted?

**Comment by PHLF** [comment]
I'm sorry but what you want to achieve is not very clear 😐 
Entities can span several words, so you should have no issue defining "Khanjr Pur" as an example of `place_name` in your dataset. Is that your problem?

**Comment by gagan-bansal** [comment]
I have these ~30,000 place names already, you mean I should add these words in training set each as entity "place".
If we do this training would take too much of time. 
My question is, can we not add these as place names somewhere in MITIE NER data?

**Comment by PHLF** [comment]
@amn41 I don't see any good solution here considering the actual processing pipeline. Would an hypothetical `keyword_entity_extractor` fit this usecase? 😕

**Comment by bigman73** [comment]
One solution is to handle those entities yourself and replace them with a token, such as {PLACE_NAME}
Then the training will be done not on the concrete entity value but on the token.
Tokenize it the input string, as a preprocessing step, before you pass the string to Rasa

**Comment by gagan-bansal** [comment]
@bigman73 You mean to say that I should change all place names in a sentence to token. Like:
`book my flight from Mumbai to London`
will be changed before passing to Rasa as:
`book my flight from PLACE_NAME to PLACE_NAME`

**Comment by bigman73** [comment]
Yes, or:
"book my flight from PLACE_NAME1 to PLACE_NAME2"

**Comment by gagan-bansal** [comment]
Ok now its quite clear before passing to Rasa I have to pre-process the text to find locations ("Gateway of India" or "New Bombay" ) using trie or some other algo and then change to PLACE_NAME1 and PLACE_NAME2. 
Same should  be done for training data also and should be tagged PLACE_NAME1 and PLACE_NAME2 as entities `source` and `destination` respectively.

Thanks
