### ISSUE TITLE
Training process is still running since 3 days 

### ISSUE THREAD

**Issue by projectlab1** [RasaHQ/rasa_nlu#544]
**rasa NLU version** : 0.10.0a1

**Used backend / pipeline** : mitie, mitie_sklearn

**Operating system** : MAC (Virtual Machine)

**Issue**:

The training process is executing since 3 days, it has not finished yet . The training sample contains 8 entities and 151 common examples. I can share the training data if you want so.

Is it an expected behavior for Rasa NLU ? What can be done for faster training ?

**Comment by wrathagom** [comment]
Are you using mitie, or mitie_sklearn? 

Mitie is notoriously slow. Can you provide the specs (ram and CPU) for the VM and your configuration file (particularly number of threads).

Please see the note below the MITIE backend section http://rasa-nlu.readthedocs.io/en/latest/installation.html#option-1-mitie

**Comment by projectlab1** [comment]
Here are the specs of Mac VM -------
Processor :  2 x 3.43 GHz Unknown
Memory : 4 GB 0 MHz DRAM
Following is the rasa config file attributes, as uploading python file is not supported ------ 

`DEFAULT_CONFIG = {
    "name": None,
    "config": DEFAULT_CONFIG_LOCATION,
    "data": None,
    "emulate": None,
    "language": "en",
    "log_file": None,
    "log_level": 'INFO',
    "mitie_file": os.path.join("data", "total_word_feature_extractor.dat"),
    "spacy_model_name": None,
    "num_threads": 1,
    "max_training_processes": 1,
    "path": "models",
    "port": 5000,
    "server_model_dirs": None,
    "token": None,
    "cors_origins": [],
    "max_number_of_ngrams": 7,
    "pipeline": [],
    "response_log": "logs",
    "aws_endpoint_url": None,
    "duckling_dimensions": None,
    "ner_crf": {
        "BILOU_flag": True,
        "features": [
            ["low", "title", "upper", "pos", "pos2"],
            ["bias", "low", "word3", "word2", "upper", "title", "digit", "pos", "pos2", "pattern"],
            ["low", "title", "upper", "pos", "pos2"]],
        "max_iterations": 50,
        "L1_c": 1,
        "L2_c": 1e-3
    },
    "intent_classifier_sklearn": {
        "C": [1, 2, 5, 10, 20, 100],
        "kernel": "linear"
    }
}`

**Comment by sipvoip** [comment]
Also I have learned that most of the training process with MITIE is single threaded so it does not really matter how many threads you throw at it.

**Comment by wrathagom** [comment]
@sipvoip The Rasa implementation does take advantage of multiple threads. https://github.com/RasaHQ/rasa_nlu/blob/master/rasa_nlu/classifiers/mitie_intent_classifier.py#L45 exactly how would be better answered by @amn41 or @tmbo I'm not a MITIE user.

@projectlab1 there are 2 problems here. The MITIE work library is fairly large ~1GB, which is al stored in memory and that is before training beings. So there is a high probability that while you're training that you are swapping to disk.

Also, I believe I have seen @amn41 recommend setting the num_threads to 2-3x the number of cores you have. Where it looks like you are just using one.

I would recommend training on a cloud provider if that is a possibility. See #340 where they were able to get things running on a large AWS instance.

Other considerations, are you using the default MITIE library or have you tried @tmbo's fork. See the note in the section of the docs: https://github.com/RasaHQ/rasa_nlu/blob/master/rasa_nlu/classifiers/mitie_intent_classifier.py#L45

**Comment by sipvoip** [comment]
Hmm, when I train with MITIE some of it uses more then one thread, but most of the time I just see one thread being used when I check with top. I asked on the [MITIE github page](https://github.com/mit-nlp/MITIE/issues/151) and they mentioned that some parts of MITIE are not threaded. 

BTW, what does @tmbo fork provide?

**Comment by wrathagom** [comment]
@projectlab1 are you still have trouble?

@sipvoip it is a very small change https://github.com/mit-nlp/MITIE/compare/master...tmbo:master

**Comment by projectlab1** [comment]
@wrathagom I have actually moved to spacy_sklearn backend, so it is not troubling me though ....... Can i know how to install duckling for using the 'ner_sklearn' pipeline ........ I am getting the following error when trying to train the model - 

Traceback (most recent call last):
	  File "/usr/local/lib/python3.5/dist-packages/twisted/internet/defer.py", line 500, in errback
	    self._startRunCallbacks(fail)
	  File "/usr/local/lib/python3.5/dist-packages/twisted/internet/defer.py", line 567, in _startRunCallbacks
	    self._runCallbacks()
	  File "/usr/local/lib/python3.5/dist-packages/twisted/internet/defer.py", line 653, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/usr/local/lib/python3.5/dist-packages/twisted/internet/defer.py", line 1442, in gotResult
	    _inlineCallbacks(r, g, deferred)
	--- <exception caught here> ---
	  File "/usr/local/lib/python3.5/dist-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
	    result = result.throwExceptionIntoGenerator(g)
	  File "/usr/local/lib/python3.5/dist-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
	    return g.throw(self.type, self.value, self.tb)
	  File "/home/afrin/Desktop/RASA/rasa_nlu/rasa_nlu/server.py", line 176, in train
	    response = yield self.data_router.start_train_process(data_string, kwargs)
	builtins.FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/jvm'

**Comment by wrathagom** [comment]
Can you open a new issue for that?
