### ISSUE TITLE
How to deal with similar entities? 

### ISSUE THREAD

**Issue by MoAbd** [RasaHQ/rasa_nlu#548]
I know when extracting an entity like 'person', the classifier would be robust to that, but what if I want to extract multiple entities like [SW engineer, programmer, student, etc..] and they all are persons and the context almost the same? what is the best way to handle this problem using rasa_nlu?

**Comment by wrathagom** [comment]
Have you tried it and had problems? Can you provide you're training set. and the actual text you are trying to parse?

**Comment by tmbo** [comment]
That is quite an interesting problem and I'd be very happy to hear more about that. Do you have a dataset for testing & evaluation?

**Comment by tmbo** [comment]
closed due to inactivity
