### ISSUE TITLE
Tarining API shows "unknown training file format : unk" error ---

### ISSUE THREAD

**Issue by projectlab1** [RasaHQ/rasa_nlu#549]
**rasa NLU version**: 0.10.0a1

**Used backend / pipeline** : spacy_sklearn

**Operating system** : Ubuntu 17.04

**Issue**:

I am trying to train a model by calling the API http://localhost:5000/train. Although the training happens when using  CURL command as shown in tutorial 
**curl -XPOST localhost:5000/train -d @data/examples/rasa/demo-rasa.json**

However, the training gets following error when being called from python code.  I have started the server by calling - 
python3 -m rasa_nlu.server -c config_spacy.json --server_model_dirs=./model_YYYYMMDD-HHMMSS

and I requested the API from python code in following manner
`import requests
import json

param = {
    'name' : 'abc'
}
newData={
'data': '@demo-rasa.json'
    }
response = requests.post('http://localhost:5000/train', params=param, data=json.dumps(newData))
print(response.content)`

running this code I get the following error - 
**=========== RESTART: /home/afrin/Desktop/RASA/rasa_nlu/RasaApi.py ===========
b'{"error": "unknown training file format : unk for file /tmp/tmpmfxkvu3r_training_data.json"}'**

 Am i performing the post request in wrong way ? I am seeking your help to solve the issue.

**Comment by PHLF** [comment]
To me it looks like the `@filepath` is something only working with `curl`. Try to open the json file in Python and sending the content as `data`: http://docs.python-requests.org/en/master/user/quickstart/#post-a-multipart-encoded-file.
Nothing related but if you're going this way, I advise you to use [treq](https://github.com/twisted/treq) instead of requests.

**Comment by projectlab1** [comment]
Thank you for the reply. Sending the json as data worked for me. I would definitely see treq for future use.
