### ISSUE TITLE
WindowsError: exception: access violation reading 0x00000028

### ISSUE THREAD

**Issue by mvsrao** [RasaHQ/rasa_nlu#552]
**rasa NLU version** (e.g. `0.8.0`):

**Used backend / pipeline** (`mitie`):

**Operating system** (windows 2012/ WIndows 10.):

**Issue**:

The rasa NLU training with demo data seems to fail with following error. The rasa NLU version up to 0.7.4 is working perfectly with MITIE NLU. Something changed since Rasa NLU 0.8.0 that is causing below errors when train is executed with mitie nlu. Initially I thought it was mitie problem but then rasa nlu v0.7.4 worked perfectly with mitie nlu. It definitely points to some change since rasa v0.8.0 causing this issue. The issue was old but any help is appreciated.
 

  File "C:\DEVELOPMENT\SOFTWARES\Anaconda2\lib\site-packages\mitie.py", line 734, in save_to_disk
    if (_f.mitie_save_text_categorizer_pure_model(filename, self.__obj) != 0):
WindowsError: exception: access violation reading 0x00000028

**Comment by PHLF** [comment]
WindowsError? Looks like a pleonasm to me.
More seriously, did you have a look at https://github.com/RasaHQ/rasa_nlu/issues/178, https://github.com/RasaHQ/rasa_nlu/issues/269 and https://github.com/mit-nlp/MITIE/issues/111?

This issue doesn't seem to have any clearly identified cause, kinda hard to solve.

**Comment by mvsrao** [comment]
Yes I looked at above threads for same issue but none of them had a solution. For I now I have to settle with Rasa NLU v0.7.4 until this issue is resolved in the latest version. 

Thank you.

**Comment by mvsrao** [comment]
Once I changed the pipeline to mitie_sklearn from mitie the latest Rasa NLU 0.9.2 worked perfectly with MITIE NLP.

{
  "pipeline": "mitie_sklearn",
  "mitie_file": "./data/total_word_feature_extractor.dat",
  "path" : "./models",
  "data" : "./data/examples/rasa/demo-rasa.json"
}

I am not sure what is difference between mitie vs mitie_sklearn

Thank you all for your help.

**Comment by tmbo** [comment]
There is not a lot we can do about it as it is an internal error within mitie. Best is to use `spacy_sklearn` or `mitie_sklearn` as a pipeline instead.
