### ISSUE TITLE
Same phrase , different results !

### ISSUE THREAD

**Issue by AbdulrahmanAzmy** [RasaHQ/rasa_nlu#553]
After training Rasa, I'm currently testing the trained model but just I found a strange case.

After sending the following phrase: Hi can you please send my tasks
I get back this values
```
{
    "entities": [
        {
            "end": 2,
            "entity": "member",
            "extractor": "ner_mitie",
            "start": 0,
            "value": "Hi"
        }
    ],
    "intent": null,
    "intent_ranking": [],
    "text": "Hi can you please send my task"
}

```
and if trying with "hi" instead of "Hi" I get this 
```
{
    "entities": [],
    "intent": null,
    "intent_ranking": [],
    "text": "hi can you please send my tasks"
}

```

What might cause this issue?, note that my Application is working on retrieving the members from the sent message.

**Comment by tmbo** [comment]
entity extraction is case sensitive.
