### ISSUE TITLE
can't able to train more than 50 intents

### ISSUE THREAD

**Issue by mahesh-av3ar** [RasaHQ/rasa_nlu#562]
**rasa NLU version** (e.g. `0.10`):

**Used backend / pipeline** (`mitie`):

**Operating system** (linux):

**Issue**:  Actually we are working the chat bot application in python past 6 months using rasa_nlu for various flow operations. In rasa_nlu Training set occupied more memory space and taking hudge time to train the json data. And hudge amount of json data will not trained(contains 100 intent and 100 samples ) .Kindely do the needfull

**Content of configuration file** (if used & relevant):
```json
{
"pipline": "mitie"',
"mitie_file": "./data/total_word_feature_extractor.dat",
 "path" : "./models",
 "data" : "./data/examples/rasa/test.json",
 "server_model_dirs": {
     "test" : "/home/administrator/simulation_webBot_10/WebBot/TrainingData/test"
  }
}

```

**Comment by wrathagom** [comment]
What are the specifications of the server you are running the training on?

**Comment by mahesh-av3ar** [comment]
OS          :  Ubuntu-14.04
Tool        :  Pycharm
language    :  Python-3.5.4
Package     :  Mitie-0.2
DataBase    :  MySqlserver-5.6
opensource  :  rasa-0.10
Ram         :  125GB

**Comment by wrathagom** [comment]
CPU? Also are you running mysql on the same server? How much memory is it using?

Your config file isn't specifying a num_threads, so you're defaulting to one. That won't help with the amount of memory needed for training, but it could help with over all time.

Are you running the standard MITIE or did you see the Note below MITIE in the docs? http://rasa-nlu.readthedocs.io/en/latest/installation.html#option-1-mitie

**Comment by tmbo** [comment]
@mahesh-av3ar is there any specific reason you are using the `mitie` pipeline?

**Comment by mahesh-av3ar** [comment]
@wrathagom No i used MYSQL in different machines. Im using this MITIE_Master Package only. In config file it contains default num_threads 1 changed it into 3 and trained the data but data(75 intent and 75 samples)are not trained.  I mention the specification in below if need any changes in specfication and configuration tell that.

soecification:
                      OS : Ubuntu-14.04
                      Tool : Pycharm
                      language : Python-3.5.4
                      Package : Mitie-0.2
                      DataBase : MYSQLserver-5.6(other machine)
                      opensource : rasa-0.10
                      Ram : 125GB

configuration:
               {
                  "pipline": "mitie"',
                  "mitie_file": "./data/total_word_feature_extractor.dat",
                  "path" : "./models",
                 "data" : "./data/examples/rasa/test.json",
                 "server_model_dirs": {
                 "test" : "/home/administrator/simulation_webBot_10/WebBot/TrainingData/test"
                  }
               }

I need help to train the more intent with samples

**Comment by wrathagom** [comment]
Are you killing the process or is it getting killed? Training that number of intents on Mitie may take > 24 hours.

There no error or message logged to the console? Also are you training with the HTTP API or command line or custom python?

Also the num_threads recommendation is 2-3 times the number of cores you have. So if you have a 4 core machine set num_threads to 8 to 12. Monitor CPU usage with top or top to maximize core usage without pegging each of them at 100%.

**Comment by mahesh-av3ar** [comment]
@wrathagom In 16 GB ram the training set will automatically killed. Using command line to trained the set.

**Comment by wrathagom** [comment]
For 75 intents I think you are better off changing pipelines.

If you for some reason have to keep MITIE then you need to move the training onto a Cloud VM with lots of memory and processing power. You can train it and then pull the model down and load it into your local instance of Rasa.

**Comment by mahesh-av3ar** [comment]
@wrathagom How much memory need to train 100 intent .

**Comment by tmbo** [comment]
@mahesh-av3ar did you try using the `spacy-sklearn` pipeline? It should require alot less memory.

**Comment by wrathagom** [comment]
@mahesh-av3ar let us know if switching pipelines didn't solve your problems. If it created a new problem then please create a new issue.
