### ISSUE TITLE
Invalid range given to ner_training_instance.overlaps_any_entity().  It overlaps an entity given to a previous call to add_entity().

### ISSUE THREAD

**Issue by madhusudhannsn** [RasaHQ/rasa_nlu#564]
I am getting the following error when I use MITIE as back end. 

> __Traceback (most recent call last):
>   File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/usr/local/lib/python3.6/site-packages/rasa_nlu/train.py", line 88, in <module>
>     do_train(config)
>   File "/usr/local/lib/python3.6/site-packages/rasa_nlu/train.py", line 78, in do_train
>     interpreter = trainer.train(training_data)
>   File "/usr/local/lib/python3.6/site-packages/rasa_nlu/model.py", line 145, in train
>     updates = component.train(data, self.config, **context)
>   File "/usr/local/lib/python3.6/site-packages/rasa_nlu/extractors/mitie_entity_extractor.py", line 90, in train
>     sample.add_entity(list(range(start, end)), ent["entity"])
>   File "/usr/local/lib/python3.6/site-packages/mitie/mitie.py", line 477, in add_entity
>     raise Exception("Invalid range given to ner_training_instance.overlaps_any_entity().  "
> Exception: Invalid range given to ner_training_instance.overlaps_any_entity().  It overlaps an entity given to a previous call to add_entity().__

I see in some posts that it is caused by using a word under multiple entities. But I ran a simple script to check that case and I see no overlapping entities in my data. Could you guys please help me in resolving the issue.

**Comment by tmbo** [comment]
I just pushed a small change that will catch the exception from mittie, continue the training and tell you the example it skipped. Does that help you?

To try it out, you need to install the latest version from github.

**Comment by madhusudhannsn** [comment]
@tmbo Thanks for quick response and the fix solved the issue.
