### ISSUE TITLE
api.ai emulater in rasa 

### ISSUE THREAD

**Issue by ha11o** [RasaHQ/rasa_nlu#567]
**rasa NLU version** (e.g. `0.7.3`):0.9.2

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...):   mitie, spacy_sklearn

**Operating system** (windows, osx, ...): Linux

**Issue**:   The api emulator for rasa is missing the **fulfillment** is missing from the return value.
I trained rasa with the data exported from api.ai. It does not return the fulfillment field in the return valve.
Is fulfillment an important part of my chatbot is there any way around to that?
or am I missing some configurations?

**Content of configuration file** (if used & relevant):
```json

```

**Comment by wrathagom** [comment]
Rasa NLU doesn't implement the fulfillment piece and therefore it's not included in the response. You would have to implement that yourself as part of your own back end code.

See this response from @amn41 on an earlier issue #95 

> Regarding the fulfilment part, this is currently not part of rasa NLU's functionality. The idea is just to understand what a user says and respond with an intent and a list of entities. How your bot responds to that information should then be handled by your code.

**Comment by mbettan** [comment]
Just to circle back, as I have I have the same need - I am not sure to understand how can we do conversation then, if the bot have to ask several questions before doing a fulfillment? If not supported with api.ai emulator, is it supported with other ones such as native rasa?

It means we have to parse the json and get the intent name and entities and trigger the right function to fullfill the action but also answer to the end user right?

**Comment by tmbo** [comment]
Yes - there will be another tool, Rasa Core, that we will open source in a minute. That will help you to do the `dialogue state -> next action` mapping
