### ISSUE TITLE
"ner_duckling" component prolongs model training time .....

### ISSUE THREAD

**Issue by projectlab1** [RasaHQ/rasa_nlu#568]
**rasa NLU version**  : 0.10.0a1

**Used backend / pipeline** : spacy_sklearn

**Operating system** : Ubuntu 17.04

**Issue**:

I have added "ner_duckling" component in the **"config_spacy.json"** file in the following manner ---
`{
  "path": "./models",
  "name": "big-data",
  "data": "./big-data.json",
  "pipeline": ["nlp_spacy", "tokenizer_spacy", "intent_entity_featurizer_regex", "intent_featurizer_spacy", "ner_crf", "ner_synonyms",  "intent_classifier_sklearn","ner_duckling"]
  
}`

Here, pipeline ["nlp_spacy", "tokenizer_spacy", "intent_entity_featurizer_regex", "intent_featurizer_spacy", "ner_crf", "ner_synonyms",  "intent_classifier_sklearn"] is collected from the spacy pipeline template.

And i also changed **"config_defaults.json"** as follows -----
`"duckling_dimensions": ["time","temperature","number","ordinal","distance","volume","amount-of-money","duration","email","url","phone-number"],`

 Am i going wrong ? Why the training is taking huge time ?

**Comment by PHLF** [comment]
Is the training slower since you added `duckling` ? Or did you try without before ? As `duckling` is a component which doesn't require any training.

**Comment by projectlab1** [comment]
after adding ducking its taking time. It performed fine earlier. Is the sequence of the pipeline ok ? duckling will be added at the end ?

**Comment by tmbo** [comment]
The training itself doesn't take longer by adding duckling (as the duckling component doesn't do any processing during the training phase).

You migh run into memory issues though. The duckling component needs to fire up a JVM so the memory pressure might be higher and your machine is busy with pagination (can you check that?)

**Comment by projectlab1** [comment]
Yes memory pressure is occuring. Following is the specification of the machine ---
Memory : 15.5 GiB
Processor : Intel® Core™ i5-3470 CPU @ 3.20GHz × 4 
Os type : 64-bit
Disk : 135.3 GB

What can be done to resolve this issue ?

**Comment by tmbo** [comment]
To be honest, I haven't seen that issue occur when using the spacy backend (usually only mitie is known for excessive memory usage). How large is your training data set?

**Comment by projectlab1** [comment]
It contains 8 entities and 151 common examples only .............

**Comment by wrathagom** [comment]
What else is running on the computer. What is the free memory before starting Rasa?

**Comment by projectlab1** [comment]
I have also noticed a weird problem. Every 2nd time i run the server, it takes hrs to train. However, performs well in the first time, while using duckling .....

The state of memory usage before running rasa -

                       total        used        free      shared  buff/cache   available
Mem:          15917        2997       11377         333        1541       12288
Swap:          3904           0        3904

After running rasa, while taking hours to train ---
![screenshot from 2017-09-07 10-13-48](https://user-images.githubusercontent.com/6197124/30145736-47404ace-93b5-11e7-8a80-f394cb099c5b.png)

**Comment by wrathagom** [comment]
Can you share your training data, I can spin up a VM and try to re-produce. In a gist or e-mail to myself and @tmbo

**Comment by projectlab1** [comment]
Here is the data set

**Comment by projectlab1** [comment]
Can i get the email id of @tmbo <https://github.com/tmbo>

**Comment by tmbo** [comment]
tom@rasa.ai
