### ISSUE TITLE
Unable to perform custom NER on rasa-NLU using spacy trained custom model

### ISSUE THREAD

**Issue by gurunathpr** [RasaHQ/rasa_nlu#569]
rasa-NLU version : 0.9.2
Used backend: spacy_sklearn
Operating system:Ubuntu 16.04
Issue: 
I have trained a custom NER model named "en_dec" on spacy and tried to use it on rasa-nlu.But it gives up an error saying word vector length is 0.Suppose I want to load even the word vectors given in spacy(Example: en_vectors_glove_md).How do I do it in rasa-NLU? 
Error message:

INFO:rasa_nlu.model:Starting to train component nlp_spacy
INFO:rasa_nlu.model:Finished training component.
INFO:rasa_nlu.model:Starting to train component tokenizer_spacy
INFO:rasa_nlu.model:Finished training component.
INFO:rasa_nlu.model:Starting to train component intent_entity_featurizer_regex
INFO:rasa_nlu.model:Finished training component.
INFO:rasa_nlu.model:Starting to train component intent_featurizer_spacy
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/rasa_nlu/train.py", line 88, in <module>
    do_train(config)
  File "/usr/local/lib/python2.7/dist-packages/rasa_nlu/train.py", line 78, in do_train
    interpreter = trainer.train(training_data)
  File "/usr/local/lib/python2.7/dist-packages/rasa_nlu/model.py", line 145, in train
    updates = component.train(data, self.config, **context)
  File "/usr/local/lib/python2.7/dist-packages/rasa_nlu/featurizers/spacy_featurizer.py", line 35, in train
    features = self.features_for_doc(example.get("spacy_doc"))
  File "/usr/local/lib/python2.7/dist-packages/rasa_nlu/featurizers/spacy_featurizer.py", line 47, in features_for_doc
    return doc.vector   # this will return the sentence embedding as calculated by spacy (currently averaged words)
  File "spacy/tokens/doc.pyx", line 275, in spacy.tokens.doc.Doc.vector.__get__ (spacy/tokens/doc.cpp:7291)
  File "spacy/tokens/doc.pyx", line 275, in genexpr (spacy/tokens/doc.cpp:7114)
  File "spacy/tokens/token.pyx", line 240, in spacy.tokens.token.Token.vector.__get__ (spacy/tokens/token.cpp:7249)
ValueError: Word vectors set to length 0. This may be because you don't have a model installed or loaded, or because your model doesn't include word vectors. For more info, see the documentation: 
https://spacy.io/docs/usage

Content of configuration file:

{
  "name": null,
  "pipeline": ["nlp_spacy", "tokenizer_spacy", "intent_entity_featurizer_regex", "intent_featurizer_spacy","ner_spacy","ner_crf", "ner_synonyms",  "intent_classifier_sklearn"],

  "language": "en",
  "num_threads": 1,
  "max_training_processes": 1,
  "path": "./models",
  "response_log": "logs",
  "config": "config.json",
  "log_level": "INFO",
  "port": 90,
  "data":  "./data/demo-rasa.json",
  "emulate": null,
  "log_file": null,
  "mitie_file": null,
  "spacy_model_name": "en_dec",
  "server_model_dirs": null,
  "token": null,
  "cors_origins": [],
  "aws_endpoint_url": null,
  "max_number_of_ngrams": 7,
  "duckling_dimensions":  null,

  "ner_crf": {
    "BILOU_flag": true,
    "features": [
      ["low", "title", "upper", "pos", "pos2"],
      ["bias", "low", "word3", "word2", "upper", "title", "digit", "pos", "pos2", "pattern"],
      ["low", "title", "upper", "pos", "pos2"]],
    "max_iterations": 10000,
    "L1_c": 1,
    "L2_c": 1e-3
  },

  "intent_classifier_sklearn": {
    "C": [1, 2, 5, 10, 20, 100],
    "kernel": "linear"
  }

**Comment by PHLF** [comment]
I think [it's not officially supported yet](http://rasa-nlu.readthedocs.io/en/latest/entities.html#places-dates-people-organisations):  
> We don’t recommend that you try to train your own NER using spaCy, unless you have a lot of data and know what you are doing.  

For training custom entities, you should have a look at the `ner_crf` component.

**Comment by wrathagom** [comment]
@gurunathpr Do you have a reason you're trying to train a custom Spacy model vs using ner_crf in the Rasa pipeline?

**Comment by tmbo** [comment]
Which spacy version is that? looks more like an issue with spacy / the trained model than with Rasa. we don't do anything with the model but load and use it.

**Comment by tmbo** [comment]
closed due to inactivity
