### ISSUE TITLE
Enabling HTTPS instead of HTTP - API.AI

### ISSUE THREAD

**Issue by mbettan** [RasaHQ/rasa_nlu#570]
**rasa NLU version** (e.g. `0.7.3`):
latest, docker image

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...):

**Operating system** (windows, osx, ...):
Linux Ubuntu 16.04

**Issue**:
I am not able to switch my hubot platform from api.ai to rasa nlu due to httpS issues. My application only supports HTTPS.

Unfortunately the Docker image start with HTTP. how could I switch to HTTPS?

docker run -p 443:5000 --entrypoint /app/entrypoint.sh  rasa/rasa_nlu:latest-full start -c /app/config.json -e api

**Content of configuration file** (if used & relevant):
```json

```

**Comment by PHLF** [comment]
Didn't try but should be [easy to do thanks to twisted](http://klein.readthedocs.io/en/latest/introduction/2-twistdtap.html).

**Comment by wrathagom** [comment]
As stated in Gitter the easiest way I would think to accomplish this is leave rasa on localhost:5000 and put an nginx container in front of it.

That being said we'll leave this issue here if anyone wants to implement this in a configurable way.

**Comment by mbettan** [comment]
To be sure to understand:

You suggest to replace "python -m rasa_nlu.server" in entrypoint.sh by twistd ?
I am not sure what is inside the python module rasa_nlu.server provided by the team. How to replace it by
twistd -n web --class=twistdPlugin.resource -c cert.pem -k privkey.pem --https=4433

**Comment by PHLF** [comment]
This needs some proper develoment, but as I said, I'm pretty confident that this could easily be done, the only difficulty would be to pass the configuration to the server. You can try yourself. Edit the [`server.py`](https://github.com/RasaHQ/rasa_nlu/blob/master/rasa_nlu/server.py#L177) as follows:

```python
if __name__ == '__main__':
    # Running as standalone python application
    arg_parser = create_argparser()
    cmdline_args = {key: val for key, val in list(vars(arg_parser.parse_args()).items()) if val is not None}
    rasa_nlu_config = RasaNLUConfig(cmdline_args.get("config"), os.environ, cmdline_args)
    rasa = RasaNLU(rasa_nlu_config)
    logger.info('Started http server on port %s' % rasa_nlu_config['port'])
    rasa.app.run('0.0.0.0', rasa_nlu_config['port'])
```
to
```python
rasa_nlu_config = RasaNLUConfig(os.environ)
rasa = RasaNLU(rasa_nlu_config)
resource = rasa.app.resource()
```
Edit the default `config.json` file according to your needs, then you should be able to launch the server using:

`twistd -n web --class=twistdPlugin.resource -c cert.pem -k privkey.pem --https=4433`

instead of

`python -m rasa_nlu.server -c <your_config_file>`

**Comment by tmbo** [comment]
Mhm not sure this is going into Rasa NLU. The better setup is always to put a proxy infront of the application server. If you want to test with something that needs an https endpoint, I'd suggest to use ngrok for development puroposes: https://ngrok.com/

**Comment by wrathagom** [comment]
What about a proxy on Server A and Rasa on Server B and wanting https between them? Don't know if that's a really use case, but just trying to play devil's advocate.

**Comment by tmbo** [comment]
I'd still install e.g. nginx  on Server B, but yes it depends on the setup and I guess the above change PHLF posted isn't directly related to HTTPS but rather allows to run the application directly using twistd. @PHLF maybe we should add a script with that code (we had something before for wsgi that we removed) and add the line you wrote to the docs?

**Comment by ha11o** [comment]
The easiest way i see is that 
Just use run it on the local host and run ngrok on the same port you will get a https link you can use that now

**Comment by PHLF** [comment]
No of course using twisted web goes further just enabling HTTPS and yes setting up a reverse proxy should be the way too go, but if for whatever reason one really needs to run the Rasa NLU server in HTTPS without changing anything to its infrastructure, it's possible. Moreover as Klein relies on twisted, using twisted web just looks like a natural solution.  

> maybe we should add a script with that code (we had something before for wsgi that we removed) and add the line you wrote to the docs?  

Maybe, but if the gunicorn + WSGI stuff was important for performance reason as WSGI is a synchronous, blocking model, this is less the case now. Moreover if it were for using HTTPS, setting up a reverse proxy seems to be what most people think of in the first place.  
Would that be really useful? What do you think?

Anyway, just ask, and I'll try to find the time to make a PR.
