### ISSUE TITLE
Questions about training phases & Dictionary

### ISSUE THREAD

**Issue by CorentinAddventa** [RasaHQ/rasa_nlu#572]
**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...): mitie_sklearn
**Operating system** (windows, osx, ...): linux

**Issue**:

Hello,

I'am currently using the mitie_sklearn pipeline as suggested.
I have a few questions to ask you about the learning process that Rasa is carrying out, and more precisely about the different steps:

**1-** We want to use rasa in French, so we create our own dictionaries '.dat' from French movies subtitles. I noticed that depending of the dictionary, the learning process of rasa changes.
 
For example, when we used a '.dat' of 100 lines of subtitles the 'Part II: train segment classifier' was very long (about an hour) and displayed result lines (such as "C: 20 loss: 3 0.54643") and when we used 10 000 lines of subtitles, it was very short (10 minutes) and we had the table "test on train ". The result is that the bigger dictionary is less efficient than the small one, which is illogical. Can you tell me what impacts the learning of Rasa in order to create this difference? Is using subtitles a bad idea?

**When we use 10 000 lines of subtitles as dictionary:**
```
Part II: train segment classifier
now do training
num training samples: 37
test on train:
4 0 0 0 0 0 0 0 0 0 0 0
0 3 0 0 0 0 0 0 0 0 0 0
0 0 2 0 0 0 0 0 0 0 0 0
0 0 0 4 0 0 0 0 0 0 0 0
0 0 0 0 2 0 0 0 0 0 0 0
0 0 0 0 0 2 0 0 0 0 0 0
0 0 0 0 0 0 3 0 0 0 0 0
0 0 0 0 0 0 0 8 0 0 0 0
0 0 0 0 0 0 0 0 2 0 0 0
0 0 0 0 0 0 0 0 0 2 0 0
0 0 0 0 0 0 0 0 0 0 4 0
0 0 0 0 0 0 0 0 0 0 0 1

overall accuracy: 1
Part II: elapsed time: 434 seconds.
```

**When we use 100 lines of subtitles as dictionary:**
```
Part II: train segment classifier
now do training
num training samples: 37

​C: 200   loss: 3         0.561111
C: 400   loss: 3         0.561111
C: 300   loss: 4.5       0.588889
C: 100   loss: 3      0.561111
C: 0.01   loss: 1.5       0.533333
```

**2-** Following the learning, Rasa will assimilate a certain number of entities. When we test, Rasa will assign entities to new words, what logic does he follow to make this? Is there a link to the dictionary we used?

**What we use to learn:**
```
{
        	"text": "Je veux du champagne", 
        	"intent": "service_de_chambre", 
        	"entities": [
        		{
        			"start": 11,
        			"end": 20,
        			"value": "champagne",
        			"entity": "nourriture"
        		}
        	]
      	},
      	{
        	"text": "du vin s'il vous plaît!", 
        	"intent": "service_de_chambre", 
        	"entities": [
        		{
        			"start": 3,
        			"end": 6,
        			"value": "vin",
        			"entity": "nourriture"
        		}
        	]
      	},
      	{
        	"text": "un sandwich s'il vous plaît!", 
        	"intent": "service_de_chambre", 
        	"entities": [
        		{
        			"start": 3,
        			"end": 11,
        			"value": "sandwich",
        			"entity": "nourriture"
        		}
        	]
      	},
```

**What we have:**
```
{ entities:
   [ { end: 8,
       entity: 'prix',
       extractor: 'ner_mitie',
       start: 3,
       value: 'femme' },
     { end: 26,
       entity: 'nourriture',
       extractor: 'ner_mitie',
       start: 21,
       value: 'aussi' },
     { end: 32,
       entity: 'envoyer',
       extractor: 'ner_mitie',
       start: 27,
       value: 'avoir' },
     { end: 54,
       entity: 'nourriture',
       extractor: 'ner_mitie',
       start: 48,
       value: 'séjour' },
     { end: 61,
       entity: 'envoyer',
       extractor: 'ner_mitie',
       start: 56,
       value: 'merci' } ],
  intent: { confidence: 0.434016424873349, name: 'wifi' },
  intent_ranking:
   [ { confidence: 0.434016424873349, name: 'wifi' },
     { confidence: 0.26536677980588036, name: 'copy_de_facture' },
     { confidence: 0.21158334550640828, name: 'service_de_chambre' },
     { confidence: 0.08903344981436241,
       name: 'reserver_une_chambre' } ],
  text: 'Ma femme souhaiterai aussi avoir une facture du séjour, merci' }
```
​
The words "aussi" and "séjour" are tagged as "nourriture" entity but it's illogical since it's not food.

Regards,

Corentin Gaillard, @ludan-av

**Comment by wrathagom** [comment]
I need more time to read over this and digest everything, but just first glance subtitles strikes me as odd. I doubt the words in subtitles would be representative of an entire language. Food may be a great example how many subtitles have the name of a food in them?

The next thing that strikes me as odd is the size of your corpus. I was thinking the MITIE models were made from 20,000 wikipedia documents. Which would equate to 100s of thousands of sentences if not millions.

@tmbo @amn41 any comments. Do you know of anyone with a French MITIE model?

**Comment by tmbo** [comment]
Yes there are a couple of people using the spacy fr model (https://spacy.io/docs/usage/models#available). Maybe that is an option for you as well @CorentinAddventa? Not sure subtitles are the best source for a language, depends on the domain.

Concerning the entity extraction: Rasa isn't using a dictionary to look up your entities or to extract them. Entities are extracted based on their surroundings and depending on the sentence structure they occur in, therefore the model might find an entity which it hasn't seen during training if it occurs in a similar location as the training entities. If the performance isn't to good with the mitie model, you should try using the `spacy_sklearn` pipeline.
