### ISSUE TITLE
when /train  API with name parameter fails with forbidden error. 

### ISSUE THREAD

**Issue by danazen** [RasaHQ/rasa_nlu#574]
**rasa NLU version** : 0.10.0a2

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...):  mitie

**Operating system** (windows, osx, ...): ubuntu

**Issue**:  When /train API is invoked from RASA UI, I am getting forbidden response from RASA NLU where as I am able to invoke /train using a curl command successfully. I have given read write access to all folders of RASA NLU container. Rasa NLU is deployed as a container. All /parse is working fine. 

**Content of configuration file** (if used & relevant):
```json
config.json
  "pipeline": "mitie",
  "mitie_file": "./data/total_word_feature_extractor.dat",
  "path" : "./models",
  "data" : "./data/demo-rasa.json",
 "server_model_dirs" : "./models"

```

**Comment by cnilesh** [comment]
Hello @danazen ,

Were you able to fix the issue? Can you please help me with the resolution?

Regards,
Nilesh
