### ISSUE TITLE
Will rasa_nlu match the exact phrase if the number of training example per intent is 1?

### ISSUE THREAD

**Issue by kishore-devaraj** [RasaHQ/rasa_nlu#577]
Rasa_nlu version: 0.9
Backend : mitie_sklearn
OS: ubuntu

          Is it possible for rasa_nlu to match the exact phrase that was given in the training data if the number of training sample for each intent is one?
          I tried this but sometimes it is not matching with the right intent. Is there any way where i can modify the code to achieve this?

**Comment by tmbo** [comment]
No, the trained models in Rasa NLU use machine learning. So there is no direct lookup of examples nor keyword matching.
