### ISSUE TITLE
Rasa nlu model is not updating (while server is running)

### ISSUE THREAD

**Issue by RachaRatan** [RasaHQ/rasa_nlu#581]
I have run the server for Rasa nlu using below command.
'python -m rasa_nlu.server -c config_spacy.json --server_model_dirs=./model_name'
Server started with 5000 port, I can able to get the response properly using 'http://localhost:5000/parse?q=hello' end point.

Now I have updated model with new intents while the server is in running state with below command.
'python -m rasa_nlu.train -c config_spacy.json' 

But after updating the model while the server is in running state I am not able to get response with updated model data.
If I stop the server and again start the server then I am able to see my updated results.

Can't I get the updated result while running the server, why should I restart the server every time.

Please suggest and give me the solution for it.

**Comment by PHLF** [comment]
Hi,
 Could you please fill the issue template so we can have a better understanding of the situation :  

**rasa NLU version** (e.g. `0.7.3`):

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...):

**Operating system** (windows, osx, ...):

**Issue**:

**Content of configuration file** (if used & relevant):  

What was the server output during training? Did you see an error?

**Comment by RachaRatan** [comment]
**rasa NLU version (e.g. 0.7.3):** 0.10.0a4

**Used backend / pipeline (mitie, spacy_sklearn, ...):** ["nlp_spacy", "tokenizer_spacy", "intent_featurizer_spacy", 
              "ner_crf", "ner_synonyms", "intent_classifier_sklearn"]

**Operating system (windows, osx, ...):** windows

**Issue:** If I update the model while the Rasa Server is running it is not reflecting my newly update data. If I stop the Rasa Server and again I start the Rasa Server then I am able to see my updated data.
As I said, for every update in model, I can't restart the Rasa Server.
Can I reflect my newly updated data without restarting the Rasa Server.  

**Content of configuration file (if used & relevant):**

{
  
"name": "People",
"pipeline" : ["nlp_spacy", "tokenizer_spacy", "intent_featurizer_spacy", 
              "ner_crf", "ner_synonyms", "intent_classifier_sklearn"],
  
"path" : "./models",
  
"data" : "./data/examples/rasa/People.json"

}



What was the server output during training? Did you see an error? 
I haven't seen any error in server output during training. I can see reflected json with my new values in models.

Please let me know if you require anything more info I will share thank you :)

**Comment by PHLF** [comment]
After training, you should query the newly trained model by specifying its folder name:  

`curl 'localhost:5000/parse?q=hello&model=model_XXXXXX'`

Instead of the default `model_XXXXXX` name, you can use a custom one during training:

`[...]/train?name=my_model`

Then : 
`curl 'localhost:5000/parse?q=hello&model=my_model'`

**Comment by RachaRatan** [comment]
Thank you so much :) @PHLF.
I added model name in parse end point, it is working now.

**Comment by RachaRatan** [comment]
http://localhost:5000/parse?q=hello&model=my_model

In the above mentioned end point my_model(model name) is case sensitive or not?
why because I am asking this question my model name is 'People'

after training my model without any issue, I am getting different parse end point results for both small letter(people) and capital letter(People).

Please let me know whether the parse end point is case sensitive or not. if so how can I mention my model name in parse end point
