### ISSUE TITLE
Not giving proper intents when using parse endpoint along with model name

### ISSUE THREAD

**Issue by RachaRatan** [RasaHQ/rasa_nlu#586]
**rasa NLU version** (e.g. `0.7.3`):0.10.0a4

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...):["nlp_spacy", "tokenizer_spacy", "intent_featurizer_spacy",
"ner_crf", "ner_synonyms", "intent_classifier_sklearn"]

**Operating system** (windows, osx, ...):Windows

**Issue**:http://localhost:5000/parse?q=hello&model=my_model

In the above mentioned end point my_model(model name) is case sensitive or not?
why because I am asking this question my model name is 'People'

after training my model without any issue, I am getting different parse end point results for both small letter(people) and capital letter(People).

Please let me know whether the parse end point is case sensitive or not. if so how can I mention my model name in parse end point

**Content of configuration file** (if used & relevant):
```json
{

"name": "People",
"pipeline" : ["nlp_spacy", "tokenizer_spacy", "intent_featurizer_spacy",
"ner_crf", "ner_synonyms", "intent_classifier_sklearn"],

"path" : "./models",

"data" : "./data/examples/rasa/People.json"

}
```

**Comment by tmbo** [comment]
@RachaRatan which subfolders has the folder `./models` on that machine?

**Comment by tmbo** [comment]
Model names should be case sensitive.

**Comment by RachaRatan** [comment]
Even after I am giving the same model name including case sensitive parse end point is not reflecting updated intent names.
But if I do the restart of Rasa sever it is reflecting.

So, please let me know how can I get my updated results without restarting the sever.

**Comment by PHLF** [comment]
Did you try using only lowercase for your model name?

**Comment by RachaRatan** [comment]
Yes I tried with lower cases.
still I am not able to get proper result. It is showing wrong intents sometime and sometime it giving intent as none.

**Comment by tmbo** [comment]
This feature is not part of the version you installed. The server will load a model you query only if that model is not loaded yet. Therefore, if you retrain with the same model name, the server will not load that retrained model as it thinks it already loaded that model.

**Comment by PHLF** [comment]
Sorry I didn't get what you tried to achieve: as Tom said, you cannot update the same model, you have to give it a different name like my_model_v1 then my_model_v2... Some changes where introduced in Rasa NLU yesterday, you may want to have [a look at it](https://github.com/RasaHQ/rasa_nlu/blob/master/CHANGELOG.rst#added)

**Comment by RachaRatan** [comment]
Thank you so much for your reply :).

May I know in which version this feature is enabled.

My overall requirement is, I can't restart the Rasa server every time when my model is updated with new intents or utterences. I want get the proper result without restarting the server when my model update is happen.

**Comment by RachaRatan** [comment]
I will explain in detail what my problem is:

I have created one Json with some of the intents and utterences.
I am attaching my Json file
[Jsonformat.txt](https://github.com/RasaHQ/rasa_nlu/files/1299207/Jsonformat.txt)

Now I executed below command to train the Rasa.
![image](https://user-images.githubusercontent.com/30255507/30374633-411e52ec-98a3-11e7-9bd8-61d89ec721fe.png)

My config_spacy looks like below.
[config_spacy.txt](https://github.com/RasaHQ/rasa_nlu/files/1299209/config_spacy.txt)

Now one model is created in models folder and I can see the update intent values.
Now I have started Rasa server with below command.
![image](https://user-images.githubusercontent.com/30255507/30374739-95f73d38-98a3-11e7-9859-0a02c20e556d.png)

The server started with 5000 port. Now I went to browser and used Parse end point to check my intent score using below url.
http://localhost:5000/parse?q=how%20about%20pizza&model=People
 I get the intent score and intent name what I have mentioned in the Json file.

after all this I have not stop the Rasa server, while it is running mode. I updated Json file with new intent and utterences. and I executed the same command to update the model(
![image](https://user-images.githubusercontent.com/30255507/30374910-2e7902b2-98a4-11e7-8c94-19067e05fc2c.png)
)

Now model is update with new intents successfully. I can see the update value in the model file.
after I have tried to hit same parse end point with new utterence values, here I am not able to get the intents value here it is showing intent as None.

If I do stop the Rasa server and again if I restart the server with same command 
![image](https://user-images.githubusercontent.com/30255507/30375040-b884191a-98a4-11e7-8476-9d0ae8305f51.png)

I am able to get the intent result properly.
I want this to be happen with out restarting Rasa server every time.
Thank you so much.. :)

**Comment by PHLF** [comment]
[There is a `/train` HTTP endpoint](http://rasa-nlu.readthedocs.io/en/stable/http.html#post-train) for you to send requests to instead of initating the training directly with the python interpreter.  
You could just send a train request with `my_model_v1`, then update the training data while the server is still running and send a train request for your updated model `my_model_v2`.
You can also consider yesterday's update which allows you to work with [projects instead of models](http://rasa-nlu.readthedocs.io/en/latest/http.html#serving-multiple-apps).

**Comment by RachaRatan** [comment]
When I am using /train end point I am facing an issue as in the below picture.
please let me know what exactly is happening.
![trainign issue with train end point](https://user-images.githubusercontent.com/30255507/30380907-79d46aa8-98b8-11e7-9ad7-7fdf3e142a72.png)

**Comment by RachaRatan** [comment]
Any body help me to fix this

**Comment by PHLF** [comment]
No. 
More seriously I cannot see where you sent your training request in your logs: I can just see hundreds of parse requests and the server beginning the training. How did the request you sent to the server look like?

**Comment by RachaRatan** [comment]
I am executing /train request from postman tool. That looks like as mentioned below picture.
![image](https://user-images.githubusercontent.com/30255507/30437941-8a87e78c-998d-11e7-948a-3fd412fbe873.png)
when I execute this request it is showing an error message as in below picture.
![image](https://user-images.githubusercontent.com/30255507/30437987-b4ecd960-998d-11e7-9f66-abaa65cf3ea1.png)
when I click on close program button the request is getting cancel and it is stopping the Rasa server with below mentioned error message.
![image](https://user-images.githubusercontent.com/30255507/30438098-f832225c-998d-11e7-806d-60621ba95c0e.png)

I did not understand what is happening when execute trian request. If execute any other HTTP endpoints /parse or /status it is fine without any issue. And also if train the model with command prompt with below command training is completed successfully.
![image](https://user-images.githubusercontent.com/30255507/30438225-53b71c22-998e-11e7-8715-057b37c34061.png)

Let me know why it failing to train with HTTP end points. If you require more information let me know I will share. But I have tried a lot to fix it but I am not able to fix it.
Please help me fix this issue.

**Comment by PHLF** [comment]
It looks like your request lacks a body including the data to train the model with. Something like : 

```json
{ "name" : "my_model", "data" : <content of your training_data.json file> }
```

**Comment by RachaRatan** [comment]
I have tried this by passing the body to HTTP end point, still I am facing the same issue.
no difference at all in my error.
I am giving the body looks like:

> { "name" : "People", "data" : "{"rasa_nlu_data":{"common_examples":[{"text":"later","intent":"None","entities":[{"start":0,"end":5,"value":"later","entity":"RideTime"}]},{"text":"wake up","intent":"ServiceRequestEnquiry","entities":[]},{"text":"no not now","intent":"ConfirmationNo","entities":[]},{"text":"not sure","intent":"ConfirmationNo","entities":[]},{"text":"no bot","intent":"ConfirmationNo","entities":[]},{"text":"no goride bot","intent":"ConfirmationNo","entities":[]},{"text":"i want to book now","intent":"None","entities":[{"start":15,"end":18,"value":"now","entity":"RideTime"}]},{"text":"i want to booknow","intent":"None","entities":[{"start":10,"end":17,"value":"booknow","entity":"RideTime"}]},{"text":"i want to book later","intent":"None","entities":[{"start":10,"end":20,"value":"book later","entity":"RideTime"}]},{"text":"get me satheesh details","intent":"GenericGreeting","entities":[{"start":7,"end":15,"value":"satheesh","entity":"People"}]},{"text":"i want to know who is satheesh","intent":"GenericGreeting","entities":[{"start":22,"end":30,"value":"satheesh","entity":"People"}]},{"text":"who is satheesh","intent":"GenericGreeting","entities":[{"start":7,"end":15,"value":"satheesh","entity":"People"}]},{"text":"tell me about satheesh","intent":"GenericGreeting","entities":[{"start":14,"end":22,"value":"satheesh","entity":"People"}]},{"text":"get me details of satheesh","intent":"GenericGreeting","entities":[{"start":18,"end":26,"value":"satheesh","entity":"People"}]},{"text":"can I get satheesh detials","intent":"GenericGreeting","entities":[{"start":10,"end":18,"value":"satheesh","entity":"People"}]},{"text":"who is satti","intent":"GenericGreeting","entities":[{"start":7,"end":12,"value":"satti","entity":"People"}]},{"text":"where is satheesh","intent":"GenericGreeting","entities":[{"start":9,"end":17,"value":"satheesh","entity":"People"}]},{"text":"Where is satti","intent":"GenericGreeting","entities":[{"start":9,"end":14,"value":"satti","entity":"People"}]},{"text":"you know Satti pandu","intent":"GenericGreeting","entities":[{"start":9,"end":20,"value":"Satti pandu","entity":"People"}]},{"text":"where is Satti pandu","intent":"GenericGreeting","entities":[{"start":9,"end":20,"value":"Satti pandu","entity":"People"}]},{"text":"details of deepak","intent":"PeopleSearch","entities":[{"start":11,"end":17,"value":"deepak","entity":"People"}]},{"text":"tell me about deepak","intent":"PeopleSearch","entities":[{"start":14,"end":20,"value":"deepak","entity":"People"}]},{"text":"who is deepak","intent":"PeopleSearch","entities":[{"start":7,"end":13,"value":"deepak","entity":"People"}]},{"text":"deepak","intent":"PeopleSearch","entities":[{"start":0,"end":6,"value":"deepak","entity":"People"}]}],"entity_synonyms":[{"value":"Satheesh","synonyms":["Satti","Sat","Satti pandu"]},{"value":"Hari Govind","synonyms":["Hari","Govind"]},{"value":"Deepak Koduri","synonyms":["Deepak","Koduri"]}]}}"}

**Comment by PHLF** [comment]
Did you remove the `?name=People` parameter? Did you set the content type to `raw` and `application/JSON` ? Again can you show your complete HTTP request?

**Comment by RachaRatan** [comment]
Yes I set the content type to raw and application/json as you mentioned in the screen shot.
I tried with both options by removing ?name=People parameter and adding the parameter but still I am facing the same issue.

![image](https://user-images.githubusercontent.com/30255507/30470762-abebc7d2-9a13-11e7-9e99-05ee358bcc8e.png)

![image](https://user-images.githubusercontent.com/30255507/30470785-c4033490-9a13-11e7-8db1-7191466347e7.png)

**Comment by PHLF** [comment]
Did you see my edit?

**Comment by RachaRatan** [comment]
Yes, @PHLF I have tried EDIT part as well. But it is not resolving. Giving the same error message. What I am doing wrong I don't understand

![image](https://user-images.githubusercontent.com/30255507/30471269-bd158a5a-9a15-11e7-9440-76303e874942.png)


![image](https://user-images.githubusercontent.com/30255507/30471421-446fef22-9a16-11e7-86ab-9c4af6e312af.png)

**Comment by PHLF** [comment]
I may missed the point but I think the only thing you're doing wrong here [is using windows](https://docs.python.org/3/library/tempfile.html#tempfile.NamedTemporaryFile):  

> Whether the name can be used to open the file a second time, while the named temporary file is still open, varies across platforms (it can be so used on Unix; **it cannot on Windows NT or later**).

@tmbo : The training data is copied to [named temporary file](https://github.com/RasaHQ/rasa_nlu/blob/master/rasa_nlu/data_router.py#L188) then closed and reopened by the training process.

**Comment by PHLF** [comment]
@RachaRatan In the meantime you could be interested by [the Windows Subsystem for Linux](https://msdn.microsoft.com/fr-fr/commandline/wsl/about).

**Comment by PHLF** [comment]
Looks like some issue between Windows and the multiprocessing lib. You should give a try to [https://msdn.microsoft.com/fr-fr/commandline/wsl/about](Windows Subsystem for Linux). I don't think there is an easy fix for that. What is your python version by the way?

**Comment by RachaRatan** [comment]
@PHLF you mean to say we can't fix this while using windows os. It is a problem because of using Rasa in windows?
Is this limitation from Rasa itself?
I am using Python-3.6.2

**Comment by PHLF** [comment]
> Is this limitation from Rasa NLU itself?  

I would say no: Rasa NLU just make indirect use of the multiprocessing library through concurrent.futures.ProcessPoolExecutor and sklearn using joblib. As I said it looks like some specific issue between Windows and the multiprocessing lib. I may be wrong. Any thoughts on this one @tmbo ?

**Comment by RachaRatan** [comment]
Ok @PHLF, I can able to train the same using below command.

![image](https://user-images.githubusercontent.com/30255507/30475956-1ade1584-9a26-11e7-9fcc-4d5b358a50dd.png)

But After I do this training model is creating successfully, but I am facing one issue.
below are the steps that I have and my issue details.

I have created one Json with some of the intents and utterences.
I am attaching my Json file
[Jsonformat.txt](https://github.com/RasaHQ/rasa_nlu/files/1305899/Jsonformat.txt)


Now I executed below command to train the Rasa.
![image](https://user-images.githubusercontent.com/30255507/30476065-79e13836-9a26-11e7-9efe-05c694f3679d.png)


My config_spacy looks like below.
[config_spacy.txt](https://github.com/RasaHQ/rasa_nlu/files/1305901/config_spacy.txt)


Now one model is created in models folder and I can see the update intent values.
Now I have started Rasa server with below command.
![image](https://user-images.githubusercontent.com/30255507/30476117-a9520f78-9a26-11e7-8513-1d405ea0d198.png)


The server started with 5000 port. Now I went to browser and used Parse end point to check my intent score using below url.
http://localhost:5000/parse?q=how%20about%20pizza&model=People
I get the intent score and intent name what I have mentioned in the Json file.

after all this I have not stop the Rasa server, while it is running mode. I updated Json file with new intent and utterences. and I executed the same command to update the model(
![image](https://user-images.githubusercontent.com/30255507/30476153-bf6da056-9a26-11e7-9bcf-60fe76f73025.png)

)

Now model is update with new intents successfully. I can see the update value in the model file.
after I have tried to hit same parse end point with new utterence values, here I am not able to get the intents value here it is showing intent as None.

If I do stop the Rasa server and again if I restart the server with same command
![image](https://user-images.githubusercontent.com/30255507/30476178-cfdd5c60-9a26-11e7-8e71-9b7bca3195f9.png)


I am able to get the intent result properly.
I want this to be happen with out restarting Rasa server every time.
Thank you so much.. :)

**Comment by PHLF** [comment]
Yes, I fully understand that's what you're trying to do as [you already explained it two days ago](https://github.com/RasaHQ/rasa_nlu/issues/586#issuecomment-329139181) hence the suggestion to use the HTTP endpoint which is meant to train a new model without having to relaunch the server every time. Unfortunately as stated before, it appears that you hit some specific issue related to the `multiprocessing` lib and Windows. Only suggestion I have ATM is to use a linux environmnent (Windows Subsystem for Linux being the easiest solution). Could you also give it a try with the MITIE pipeline instead of spacy?  
It won't solve your issue but we'll get a bit more information.

**Comment by wrathagom** [comment]
@RachaRatan another very good option would be to run Rasa NLU in Docker, if you're familiar with it.

**Comment by vikash044** [comment]
@tmbo  hi all !
i facing such as problem any solution ? (http://localhost:5000/parse)

{
"error": "Invalid parse parameter specified"
}

and also ?(http://localhost:5000/parse?q=hello%20there)

{
"project": "default",
"entities": [],
"intent": {
"confidence": 0.6852470563023119,
"name": "greet"
},
"text": "hello there",
"model": "model_20181026-123523",
"intent_ranking": [
{
"confidence": 0.6852470563023119,
"name": "greet"
},
{
"confidence": 0.1782927244349375,
"name": "affirm"
},
{
"confidence": 0.07256601013379048,
"name": "thank"
},
{
"confidence": 0.04439257040932929,
"name": "bye"
},
{
"confidence": 0.011187696661811092,
"name": "name"
},
{
"confidence": 0.008313942057819792,
"name": "joke"
}
]
}

**Comment by akelad** [comment]
Please create a new issue

**Comment by vikash044** [comment]
hi thank you ! for replay
well i am vikash anand sharma from india... i am beginner in chat bot making, can you help me for clear my some doubts.
regarding ! rasa NLU !

thanks !
________________________________
