### ISSUE TITLE
AttributeError: 'module' object has no attribute 'stack'

### ISSUE THREAD

**Issue by odedhb** [RasaHQ/rasa_nlu#588]
**rasa NLU version** (e.g. `0.7.3`):
0.9.2

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...):
spacy_sklearn

**Operating system** (windows, osx, ...):
osx

**Issue**:
When trying to train a spacy model by running:
`Odeds-MacBook-Pro:rasanlu oded$ python -m rasa_nlu.train -c config_spacy.json`

I get:
```
  File "/Users/oded/Library/Python/2.7/lib/python/site-packages/rasa_nlu/classifiers/sklearn_intent_classifier.py", line 94, in train
    X = np.stack([example.get("text_features") for example in training_data.intent_examples])
AttributeError: 'module' object has no attribute 'stack'
```

**Content of configuration file** (if used & relevant):
```
{
  "pipeline": "spacy_sklearn",
  "path" : "./models",
  "data" : "./data/demo-rasa.json"
}
```

**Comment by tmbo** [comment]
@odedhb do you have numpy installed?

**Comment by odedhb** [comment]
Looks like I do:

```
Odeds-MacBook-Pro:rasanlu oded$ pip install numpy
Requirement already satisfied: numpy in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python
```

**Comment by tmbo** [comment]
which version is that? (`pip list | grep numpy`)

**Comment by odedhb** [comment]
numpy (1.8.0rc1)

**Comment by tmbo** [comment]
That is indeed a bit old - try updating to at least 1.12

**Comment by odedhb** [comment]
thanks! that worked!

**Comment by harirehm** [comment]
I am getting a similar error @tmbo. And I'm in **Linux**.

`AttributeError: 'module' object has no attribute 'OP_NO_TLSv1_1'`

Below are the versions that's currently installed in my system:
**RASA NLU** : 0.10.4
**python** : 2.7.13
**numpy** : 1.13.3
**spacy** : 2.0.2
**scikit-learn** : 0.19.1

**Comment by tmbo** [comment]
@harirehm this is unreleated & this issue is closed. please open a new one if that problem persists.
