### ISSUE TITLE
Should stop words be used as features?

### ISSUE THREAD

**Issue by znat** [RasaHQ/rasa_nlu#589]
I understand from Spacy documentation that `doc.vector` averages a document's vectors without removing stop words. I am wondering if keeping them make sense for short sentences uttered in chatbots, or if they just add noise? What are your thoughts?

https://github.com/RasaHQ/rasa_nlu/blob/cfd26fc565e62a53d828cba889015f97a2730a81/rasa_nlu/featurizers/spacy_featurizer.py#L47

**Comment by wrathagom** [comment]
I'd say set up an experiment to test both methods and report back how it goes.

**Comment by akelad** [comment]
you can turn these off/on in the tf_embedding pipeline
