### ISSUE TITLE
How can I implement Rasa NLU new update related to project structure 

### ISSUE THREAD

**Issue by RachaRatan** [RasaHQ/rasa_nlu#590]
**rasa NLU version** (e.g. `0.7.3`): 0.10.0a4

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...):["nlp_spacy", "tokenizer_spacy", "intent_featurizer_spacy",
"ner_crf", "ner_synonyms", "intent_classifier_sklearn"]

**Operating system** (windows, osx, ...): windows

**Issue**: I found recently Rasa introduced new update of project structure.
I am trying to implement the same in my current version of Rasa. 
I have changed my model folder structure as Rasa mentioned in website related to project structure.
But I am not able to understand how the config_spacy.json file format.
Please let me know how can I implement this new update of Rasa.

**Content of configuration file** (if used & relevant):
```json
{
  
"name": "People",
"pipeline" : ["nlp_spacy", "tokenizer_spacy", "intent_featurizer_spacy", 
              "ner_crf", "ner_synonyms", "intent_classifier_sklearn"],
  
"path" : "./models",
  
"data" : "./data/examples/rasa/demo-rasa.json"

}

```

**Comment by PHLF** [comment]
The only difference is that there is no more `server_model_dirs` parameter in the configuration file. You should change the value of your `path` parameter from `./models` to `./projects` to avoid confusion. If you want to reuse already trained models you may have, just create a project folder under your `path` like `my_project` and move all the models you want to use under this folder. Rename the models folders to something like `model_YYYYMMDD-HHMMSS` if it is not already the case.

**Comment by wrathagom** [comment]
@RachaRatan let us know if that didn't answer your questions.
