### ISSUE TITLE
Option to export wrong nlu predictions after evaluation

### ISSUE THREAD

**Issue by madhusudhannsn** [RasaHQ/rasa_nlu#594]
I am using spacy and sklearn as backend for my assistant app. I ran evaluate command on my model with evaluation dataset and I see in confusion matrix, for some of the intents the prediction is not accurate. 

How can I improve the model accuracy ? Is it just by correcting the wrongly predicted data ? If so then how can I get the lines of an intent which model/classifier wrongly predicted ? 

![figure_1](https://user-images.githubusercontent.com/12062385/30481686-a1225648-9a3d-11e7-9897-b5071a64ff75.png)

**Comment by madhusudhannsn** [comment]
@tmbo Could you please help me on this query.

**Comment by wrathagom** [comment]
Until @tmbo responds I would:

1. Walk through the examples provided for the intents that don't have a perfect score. And see how they fail. Or what they are mistaken for.
2. Pay close attention to overlaps amongst sentences. Looking at your confusion matrix and reading into it a bit if cancellation had an example `Cancel my appointments` and hold calls had an example `cancel my calls` they may overlap too much in vector space to get good separation between them.
3. Review the number of training examples. It appears that your worst performing intents are also the ones with the fewest training examples. Can you add more to the ones with few examples to help separate them from the others?

**Comment by madhusudhannsn** [comment]
@wrathagom Thanks for your suggestions. I have a question regarding point 1. 
Is there any command/step to see the examples that don't have perfect score ?

**Comment by wrathagom** [comment]
Not that I can tell. I'll see if @tmbo maybe wants to add a `-v verbose` flag that prints the mismatches. I would think you could add a small bit of code [here](https://github.com/RasaHQ/rasa_nlu/blob/master/rasa_nlu/evaluate.py#L91) or [here](https://github.com/RasaHQ/rasa_nlu/blob/master/rasa_nlu/evaluate.py#L96)  to print the examples that were incorrectly classified.

**Comment by tmbo** [comment]
Yes that sounds like a good idea :+1:

**Comment by tmbo** [comment]
done
