### ISSUE TITLE
Update default configs and Docker folder to reference projects folder instead of models

### ISSUE THREAD

**Issue by wrathagom** [RasaHQ/rasa_nlu#595]
In #590 @PHLF recommend to a user that they change their folder from being `./models` to `./projects` given the new folder structure. This makes sense to me, but looks like we should change the sample configs and dockerfiles to follow this recommendation.

@PHLF @tmbo if you agree I'll work on updates this weekend.

**Comment by PHLF** [comment]
I'm sorry @wrathagorn, I forgot the docker part.

**Comment by tmbo** [comment]
@wrathagom sounds great. how much work is that?

**Comment by tmbo** [comment]
@wrathagom I made a PR (#606) with the renaming - mind taking a look at that? I guess it is rather straightforward.
