### ISSUE TITLE
Can I get the currently training models from the HTTP server

### ISSUE THREAD

**Issue by zhuscat** [RasaHQ/rasa_nlu#597]
**rasa NLU version**: 0.10.0a2

**Issue**: Can I get the currently training models from the HTTP server

**Comment by PHLF** [comment]
Since 0.10.0a5, you can get the [current project for which a new model is trained](https://rasa-nlu.readthedocs.io/en/latest/http.html#get-status).

**Comment by zhuscat** [comment]
thank you!
