### ISSUE TITLE
Retrained models not getting reflected

### ISSUE THREAD

**Issue by dhilipPalanisamy** [RasaHQ/rasa_nlu#599]
Hi Team,

This issue is similar to https://github.com/RasaHQ/rasa_nlu/issues/581. I have assigned a model name while training and i am using the same when starting the server.

But when i retrained the model (i.e the same model), i am not able to get the updated values. 

**rasa NLU version** (0.10.0a2):

**Used backend / pipeline** (`spacy_sklearn`, ...):

**Operating system** ( osx, ):

Thanks in advance..

**Comment by PHLF** [comment]
Yes, you're right this behaviour is to be expected (aka "it's not a bug: it's a feature"). This is because of how models are handled in memory by the server for your version. If you want to version your model, you have to [use different name reflecting your model version](https://github.com/RasaHQ/rasa_nlu/issues/581#issuecomment-328548070). If you want to have a cleaner behaviour (being able to use the same name to update your model) [update to >=0.10.0a5](https://github.com/RasaHQ/rasa_nlu/blob/master/CHANGELOG.rst#added).

**Comment by dhilipPalanisamy** [comment]
@PHLF 

Thanks for your reply. But i could found that, the version you have mentioned is under development . Is it stable to use ? if so can you mention steps to upgrade to that version ?

**Comment by PHLF** [comment]
It should be as safe as the version you're currently using which is also a development snapshot (0.10.0a2). The stable version is 0.9.2.

**Comment by dhilipPalanisamy** [comment]
@PHLF ,

I tried training model in 0.10.0.a2 version using **python -m rasa_nlu.train -c sample_configs/config_spacy.json** command , but trained model is getting stored under models>default . So I couldn't retrain it by giving name .Moreover i am not able to use --server-moderl-dirs command while starting server . can you please help me on this?

**Comment by PHLF** [comment]
If you are using 0.10.0a**5** (just to be sure we're talking about the same thing here), and you didn't specify a `name` for your first training, Rasa NLU server will create a `default` project and store the trained model inside. Just rename the `default` folder to `my_project` or whatever you want to name it and you should be good to train new models for this project by specifying `name=my_project`. 
In >=0.10.0a**5**, the Rasa NLU server looks for all projects folders under the `path` directory specified in the config and expose them as multiple parse endpoints, hence nullifying the need of the `server_models_dir` parameter.

**Comment by dhilipPalanisamy** [comment]
@PHLF 

Thanks for your support @PHLF . Upgrading to 0.10.0a5 fixed my issue.
