### ISSUE TITLE
Exposing spacy features over api

### ISSUE THREAD

**Issue by pocman** [RasaHQ/rasa_nlu#601]
Hi,

I would like to expose spacy features over api. The goal is to save memory (storing vectors only into rasa_nlu) while allowing others services to use vectors.

In practice, I would create a new component pretty similar to [intent-featurizer-spacy](http://rasa-nlu.readthedocs.io/en/latest/pipeline.html#intent-featurizer-spacy) but with an output.

Is this something you would merge in master ? Do you have any advice ?

**Comment by tmbo** [comment]
@pocman do you need the vector for the whole sentence or the vectors for each individual word?

**Comment by pocman** [comment]
The vector for the whole sentence (doc.vector).

**Comment by tmbo** [comment]
I think that should be easy to change and if it is bound to a configuration variable that might be useful :+1:
