### ISSUE TITLE
values are not returned using HTTP

### ISSUE THREAD

**Issue by Fuadk** [RasaHQ/rasa_nlu#604]
Hi,
Following the tutorial, and testing using : "show me chines restaurants"
I am not getting Chinese as value for an antitiy, while getting restaurant_search.

If I make search more complicated : "I am looking for Japanse food in the north town beside the hospital"
I am getting proper entity and value
```json
{
  "entities": [
    {
      "end": 42,
      "entity": "location",
      "extractor": "ner_crf",
      "start": 37,
      "value": "north"
    },
    {
      "end": 67,
      "entity": "location",
      "extractor": "ner_crf",
      "start": 59,
      "value": "hospital"
    }
  ],
  "intent": {
    "confidence": 0.7403247144023908,
    "name": "restaurant_search"
  }
}
```
But still chinese is not coming as a value for an entity.
How to retrieve the value of the entity for chinese value, so resturant search is targeting chiness resturants only.
Regards,
Fuad

**Comment by wrathagom** [comment]
Per the [tutorial](https://rasa-nlu.readthedocs.io/en/latest/tutorial.html#using-your-model):

> If you are using the spacy_sklearn backend and the entities aren’t found, don’t panic! This tutorial is just a toy example, with far too little training data to expect good performance.

Sounds like you just need to more training data.
