### ISSUE TITLE
Support spacy 1.9

### ISSUE THREAD

**Issue by tmbo** [RasaHQ/rasa_nlu#605]
Got the same issue with spacy 1.9

>   File "rasa_nlu/utils/spacy_utils.py", line 53, in create
    cls.ensure_proper_language_model(nlp)
  File "rasa_nlu/utils/spacy_utils.py", line 109, in ensure_proper_language_model
    if nlp.path is None:
AttributeError: 'English' object has no attribute 'path'
➜  rasa_nlu git:(master) ✗
➜  rasa_nlu git:(master) ✗
➜  rasa_nlu git:(master) ✗ pip show spacy
Name: spacy
Version: 1.9.0
Summary: Industrial-strength Natural Language Processing (NLP) with Python and Cython
Home-page: https://spacy.io
Author: Matthew Honnibal
Author-email: matt@explosion.ai
License: MIT
Location: /Users/44045241/anaconda2/lib/python2.7/site-packages
Requires: ftfy, requests, pathlib, plac, numpy, regex, dill, preshed, ujson, cymem, murmurhash, six, thinc, pip

**Comment by wrathagom** [comment]
Closing since we're on 2.x
