### ISSUE TITLE
Separate server and model configuration during train / run

### ISSUE THREAD

**Issue by sichun** [RasaHQ/rasa_nlu#610]
**Rasa NLU version** (e.g. `0.7.3`):

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...):

**Operating system** (windows, osx, ...):

**Issue**:
in the version, the config file is loaded when the server starts. 
I wonder if it can support to train new model in a HTTP server with a new config file to override existed files.
even though, the change makes the training parameter be a config file(contain project name, new training data, new pipeline)

**Content of configuration file** (if used & relevant):
```json

```

**Comment by wrathagom** [comment]
You can specify almost any configuration parameter as a url parameter when you POST to the `/train` endpoint.

For example you can override the pipeline by:
`http://localhost:5000/train?project=my_project&pipeline=nlp_spacy,tokenizer_spacy,ner_spacy`

Does that help?

**Comment by tmbo** [comment]
New configuration should be able to:
- clearly separate server configuration from model configuration (maybe we can just remove the server parameters and pass them via cmdline - need to check how many there are)
- allow to specify a run configuration to be used when running a model (e.g. to specify mitie vector file path)

**Comment by tmbo** [comment]
very good question that I don't know the answer to - but I don't think it is possible to pass in anything but strings and arrays, so no objects.

**Comment by tmbo** [comment]
Very good input from @Le-Fix :

1 Pipeline setup (including component specific setup)
2 Training Data
3 Training Configuration (reference 1, reference 2, target folder, num_threads,...)
4 Trained Model (exisiting metadata.json which consists of: 1, reference 2 and some training log)
5 Model Serving (reference 4, token, port, logfile, emulate,...)

(I just pasted this from the closed issue for reference)

**Comment by Le-Fix** [comment]
I just update this comment from time to time whenever I think some config behavior is not obvious/easy to understand based on the one cluttered configuration.

As far as I can see the config is passed straightforward to the ComponentBuilder
Therefore the config(s) should only consist of 4 (and maybe 5 if the Interpreter itself considers how/where it's run)
4 already would be specified by the model dir
```py
rasa_nlu.model Interpreter
def load(model_dir, config=RasaNLUConfig(), component_builder=None, skip_valdation=False):
        """Creates an interpreter based on a persisted model."""
```

**Comment by tmbo** [comment]
done.

**Comment by justinclare** [comment]
May I know if currently the config is now refreshed every time the server starts? Say if I specify duckling url to http://duckling:1234, will it be able to call the corresponding port number without retraining the model?

**Comment by PROrock** [comment]
Hi @justinclare, hopefully, you'll find an answer to this in https://github.com/RasaHQ/rasa/issues/6240 comments. I did :-)
