### ISSUE TITLE
Unable to change port in Rasa when dockerized

### ISSUE THREAD

**Issue by saileshcts** [RasaHQ/rasa_nlu#612]
**Rasa NLU version** (e.g. `0.7.3`): 0.10.0

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...): spacy_duckling

**Operating system** (windows, osx, ...): debian

**Issue**:
I'm new with Rasa and docker. My attempt to dockerize Rasa-NLU consists of the below steps: Instructions were referred from [here](http://www.toptechpoint.com/mlai/rasa-nlu-installation-configuration)

1. Did a Git clone of latest Rasa-NLU
2. Copied `Dockerfile_full` (from within `/docker`) to the root directory
3. Changed the port number specified in `config_default.json` and `Dockerfile_full` from default(5000) to 5048.
4. Build done using: `docker build -t rasa_nlu .`
5. Run the docker on a port(5048) different from the default(5000) port.

However, the following gets logged in the console:

```
INFO:rasa_nlu.data_router:Logging requests to '/app/logs/rasa_nlu_log-20170928-091903-1.log'. INFO:__main__:Started http server on port 5000 2017-09-28 09:19:03+0000 [-] Log opened.
2017-09-28 09:19:03+0000 [-] Site starting on 5000
2017-09-28 09:19:03+0000 [-] Starting factory <twisted.web.server.Site instance at 0x7fbab0bfdd40>
```

If I try to hit the Rasa endpoint locally using CURL, I get a `connection reset` error. My doubts on whether a wrong port was being referred were confirmed when checked within docker container (using `docker exec`)it was running on port 5000.

Can someone help me out here as to where exactly I'm going wrong and where should the port number be configured ?

Thanks in advance!

Note: Added the same issue at [SO](https://stackoverflow.com/questions/46466517/how-to-configure-the-port-to-be-exposed-for-dockerized-rasa-nlu) as well

**Content of configuration file** (if used & relevant):
```json

```

**Comment by wrathagom** [comment]
Dockerfile_full expects the config file to be in the sample_configs folder. Also Dockerfile_full uses the config_spacy_duckling.json config file. So make sure you replace the below reference in the dockerfile.

`COPY sample_configs/config_spacy_duckling.json ${RASA_NLU_HOME}/config.json`

Ignoring that, why change the ports in both locations? All you need to do is change it in your docker run or compose command.

`docker run -p 5048:5000 rasa/rasa_nlu:latest-full`

**Comment by saileshcts** [comment]
Hi I figured out from SO that I just needed to set the port explicitly inside `sample_configs/config_spacy_duckling`. Now that it works, I'm closing this.

Thanks!
