### ISSUE TITLE
Rasa: arbitrary input language

### ISSUE THREAD

**Issue by TDehaene** [RasaHQ/rasa_nlu#614]
Hi, just have a small question about the 'pipeline' concept : 

we deal with input that can arbitrarely be in any of four languages: Chinese, English, French and Dutch. Due to parsing issues, each of these languages requires a different pipeline (English uses the standard sklearn-spacy one, others would use custom pipelines). 

Is it possible to launch multiple pipelines at once, which get activated depending on the language that was used. Where the language selection would for example be a first component that gets launched to determine the language (using NLTK stopwords for example).

**Comment by wrathagom** [comment]
Rasa doesn't have this functionality built it, though it sounds like something the Rasa guys (@tmbo @amn41) would be interested In including.

I don't know if you are planning on using Rasa from within Python or via it's HTTP Api, but I can tell you that the pipeline specified in the configuration file is the pipeline for _new_ training sessions. The pipeline used by an individual model is actually saved in a file `metadata.json` in the model folder.

Using the HTTP API allows you to train a model, give it a name, specify a custom pipeline and language. For example the two url's below could be used for POST commands:

```
http://localhost:5000/train?project=my_project_en&pipeline=nlp_spacy,tokenizer_spacy,ner_spacy&language=en
http://localhost:5000/train?project=my_project_de&pipeline=nlp_spacy,tokenizer_spacy,ner_spacy&language=de
```

You'd still need something sitting in front of them to route request to the right project language, but hopefully you get the idea.

I haven't implemented this myself, but it would be the approach I would start with. If you were looking for a python solution you'll have to wait for @tmbo or @PHLF to comment.

**Comment by wrathagom** [comment]
noticing that spacy has this extension, maybe something like this would be possible. Especially since the configuration changes. If this component could set the language used by the rest of the pipeline... https://github.com/nickdavidhaynes/spacy-cld

I'm going to re-tag this issue as an enhancement with help wanted.

**Comment by akelad** [comment]
you can achieve this kind of behaviour by having a separate component that identifies the language (or maybe it's pre-existing information) and then calling different docker containers running different language models
