### ISSUE TITLE
Limit Iterations to find best C value for mitie classifier training

### ISSUE THREAD

**Issue by rajgupt** [RasaHQ/rasa_nlu#615]
**Rasa NLU version** (e.g. `0.7.3`): 0.9.2

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...): mitie

**Operating system** (windows, osx, ...): windows

**Issue**: Need to speed up the mitie training 

**Train classifier section:**
## _As seen in the log below, C values is iterating for long time around a same value. Is there a way to limit the number of iterations for finding best C value in classifier training._

**Content of configuration file** (if used & relevant):
```json
{
    "pipeline": "mitie",
    "path" : "models",
    "data" : "data/example/rasa/question.json",
    "spacy_model_name": "en_default",
    "mitie_file": "C:/Users/rajat/Downloads/MITIE-models-v0.2.tar/MITIE-models-v0.2/MITIE-models/english/total_word_feature_extractor.dat"
}
```
Log of training:
(kb) C:\Users\rajat\projects\knowledge\knowledge_assistant\src>python rasa\demo_aero\train_rasa.py
Training to recognize 4 labels: 'activity', 'object', 'observation', 'parameter'
Part I: train segmenter
words in dictionary: 200000
num features: 271
now do training
C:           20
epsilon:     0.01
num threads: 1
cache size:  5
max iterations: 2000
loss per missed segment:  3
C: 20   loss: 3         0.472222
C: 35   loss: 3         0.472222
C: 20   loss: 4.5       0.416667
C: 5   loss: 3  0.472222
C: 20   loss: 1.5       0.5
C: 20   loss: 1         0.527778
C: 20   loss: 1.1       0.555556
C: 20   loss: 1.2       0.527778
C: 20.6196   loss: 1.02151      0.555556
C: 21   loss: 1.1       0.555556
C: 19.3804   loss: 1.17849      0.527778
C: 19.0713   loss: 1.06291      0.555556
best C: 20
best loss: 1.1
num feats in chunker model: 4095
train: precision, recall, f1-score: 1 1 1
Part I: elapsed time: 7 seconds.

Part II: train segment classifier
now do training
num training samples: 38
C: 200   f-score: 1
C: 400   f-score: 1
C: 300   f-score: 1
C: 100   f-score: 1
C: 0.01   f-score: 1
C: 50.005   f-score: 1
C: 25.0075   f-score: 1
C: 12.5088   f-score: 1
C: 6.25938   f-score: 1
C: 3.13469   f-score: 1
C: 1.57234   f-score: 1
C: 0.791172   f-score: 1
C: 0.400586   f-score: 1
best C: 0.791172
test on train:
 3  0  0  0
 0 21  0  0
 0  0  3  0
 0  0  0 11

overall accuracy: 1
Part II: elapsed time: 164 seconds.
df.number_of_classes(): 4
Training to recognize 12 categories: 'hi', 'morning', 'evening', 'affirm', 'how_to_activity_on_object', 'get_plots_for_object', 'where_is_object', 'get_variation', 'get_param_of_object', 'who', 'what', 'help'
Train classifier
extracting text features
now do training
num training samples: 49
C: 200   f-score: 0.833333
C: 400   f-score: 0.857143
C: 300   f-score: 0.833333
C: 500   f-score: 0.857143
C: 700   f-score: 0.857143
C: 1100   f-score: 0.857143
C: 1900   f-score: 0.857143
C: 3500   f-score: 0.857143
C: 5000   f-score: 0.833333
C: 2650   f-score: 0.833333
C: 1475   f-score: 0.857143
C: 937.5   f-score: 0.857143
C: 668.75   f-score: 0.857143
C: 534.375   f-score: 0.857143
C: 467.187   f-score: 0.833333
C: 383.594   f-score: 0.857143
C: 391.797   f-score: 0.857143
C: 395.898   f-score: 0.833333
C: 431.543   f-score: 0.857143
C: 415.771   f-score: 0.857143
C: 407.886   f-score: 0.857143
C: 403.943   f-score: 0.857143
C: 401.971   f-score: 0.857143
C: 400.986   f-score: 0.857143
C: 400.493   f-score: 0.857143
C: 400.246   f-score: 0.857143
C: 397.949   f-score: 0.857143
C: 400.025   f-score: 0.857143
C: 398.975   f-score: 0.857143
C: 399.487   f-score: 0.857143
best C: 400
test on train:
 5  0  0  0  0  0  0  0  0  0  0  0
 0  2  0  0  0  0  0  0  0  0  0  0
 0  0  2  0  0  0  0  0  0  0  0  0
 0  0  0 11  0  0  0  0  0  0  0  0
 0  0  0  0  3  0  0  0  0  0  0  0
 0  0  0  0  0  6  0  0  0  0  0  0
 0  0  0  0  0  0  3  0  0  0  0  0
 0  0  0  0  0  0  0  6  0  0  0  0
 0  0  0  0  0  0  0  0  3  0  0  0
 0  0  0  0  0  0  0  0  0  2  0  0
 0  0  0  0  0  0  0  0  0  0  3  0
 0  0  0  0  0  0  0  0  0  0  0  3

overall accuracy: 1
**## Training time: 18072 seconds.**
df.number_of_classes(): 12

**Comment by wrathagom** [comment]
@rajgupt did you see the note in the [docs concerning MITIE](http://rasa-nlu.readthedocs.io/en/latest/installation.html#first-alternative-mitie)?

Specifically the Note:

> Training MITIE can be quite slow on datasets with more than a few intents. 
>  - You can try
to use the sklearn + MITIE backend instead (which uses sklearn for the training) or
> - you can install [our mitie fork](https://github.com/tmbo/mitie) which should reduce the training time as well.

**Comment by tmbo** [comment]
@rajgupt That is a great idea, and exactly what we did in the fork mentioned by @wrathagom. The official MITIE doesn't provide that option yet (and to be fair we didn't have the time yet to create a PR from our fork to the main repo).

**Comment by rajgupt** [comment]
Thanks a lot @wrathagom  , @tmbo . I'll try to use the forked version. 👍
