### ISSUE TITLE
API.AI new Export Data Format - Multi-Language

### ISSUE THREAD

**Issue by deubaka** [RasaHQ/rasa_nlu#616]
**Rasa NLU version**: 0.9.1
**Issue**: Just today, API.ai added a new [multi-language agent feature](https://api.ai/docs/multi-language). With this, exports now creates a new file based on the language. An excerpt from their docs is as follows,

<kbd><img width="847" alt="screen shot 2017-10-05 at 16 44 44" src="https://user-images.githubusercontent.com/1931819/31218327-95127fc2-a9ec-11e7-9bf4-1fb15d50cf32.png"><kbd>

So previously you only had these files,

-` entities/Location.json`
-` intents/FindRestaurant.json`

To this,

-` entities/Location.json`
-` entities/Location_entries_en.json` (the `entries`-attribute is extracted to this new JSON)
-` intents/FindRestaurant.json`
-` intents/FindRestaurant_usersays_en.json` (the `userSays`-attribute is extracted to this new JSON)

To mitigate for now, I just wrote a script re-convert the new format to the 'legacy' format. However, I would like to know if this is something that is already being done or a PR is already present. 

Cheers,
Deu 🤖

**Comment by tmbo** [comment]
No, we didn't have a look at that yet - would make a good contribution 😉

**Comment by deubaka** [comment]
I see. Sure thing, I guess it would be a good contribution on that part. :)

BTW, is there anything that I should be aware of when submitting PRs. I've tried submitting a PR for the 'languages.rst' typos.

**Comment by tmbo** [comment]
@deubaka No you are good, the PR looks fine. There is just an issue with the travis build (unrelated to your PR - some mess up with the keys for pushing the documentation)

**Comment by deubaka** [comment]
Initial PR #625
