### ISSUE TITLE
Can't convert 'bytes' object to str implicitly

### ISSUE THREAD

**Issue by sichun** [RasaHQ/rasa_nlu#617]
**Rasa NLU version** (e.g. `0.7.3`):

**Used backend / pipeline** (`mitie`):

**Operating system** (windows, osx, ...):

**Issue**:
i start to train some data in Chinese, then show the error for me. I have no idea for the error

**Content of configuration file** (if used & relevant):
```json

```

**Comment by glacierck** [comment]
@sichun 老乡，你的models路径里带中文啦，这句 update = component.persist(dir_name) 代码过不了的，
![image](https://user-images.githubusercontent.com/21599896/43062174-7edb767c-8e8a-11e8-9f3b-c67537e4fc93.png)
