### ISSUE TITLE
Not all required packages are installed. To use this pipeline, you need to install the missing dependencies. Please install sklearn

### ISSUE THREAD

**Issue by RachaRatan** [RasaHQ/rasa_nlu#619]
**Rasa NLU version** (e.g. `0.7.3`):0.10.0a5

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...): 
{
	"project": "People",
	"pipeline" : "spacy_sklearn",
	"path" : "./projects",
	"cors_origins":["*"],
	"data" : "./data/examples/rasa/demo-rasa.json"
}

**Operating system** (windows, osx, ...):windows with docker and woindows server 2012 r2

**Issue**: I have installed sklearn using command 'pip install sklearn' and able to see in the pip list as well as in the below screen shot.

![image](https://user-images.githubusercontent.com/30255507/31227684-65107bba-a9f8-11e7-8478-181585c151ab.png)

But when I am trying to train project I am getting below error.

![image](https://user-images.githubusercontent.com/30255507/31227710-7e1b521a-a9f8-11e7-94e1-bbc7234b0271.png)

Why am getting this error even after I install sklearn.
please to fix this.

**Content of configuration file** (if used & relevant):
```json
{
	"project": "People",
	"pipeline" : "spacy_sklearn",
	"path" : "./projects",
	"cors_origins":["*"],
	"data" : "./data/examples/rasa/demo-rasa.json"
}

```

**Comment by wrathagom** [comment]
Can you successfully run the pre-built docker images?

or are you running it in an actual windows container?

**Comment by RachaRatan** [comment]
I have run this in Docker as well as in windows container.
I failed to resolve it in both.
Please help me to fix this

**Comment by rithwikjc** [comment]
I also faced the same problem when using the trainer. I tried importing the reported packages in python env (for me the missing dependencies where numpy and sklearn). I was using pip so i reinstalled the packages using `pip install --upgrade --force-reinstall <package>`. And everything started working. 
I think the errors came about when i installed Rasa Core.

**Comment by syntithenai** [comment]
me too using anaconda
sklearn claims to be installed but till failing after   --force-reinstall above
root@c1e939a5c0f7:/opt/snips_services# /opt/rasa/anaconda/bin/pip install --upgrade --force-reinstall sklearn
Collecting sklearn
  Downloading sklearn-0.0.tar.gz
Collecting scikit-learn (from sklearn)
  Downloading scikit_learn-0.19.1-cp27-cp27mu-manylinux1_x86_64.whl (12.2MB)
    100% |################################| 12.2MB 94kB/s 
Building wheels for collected packages: sklearn
  Running setup.py bdist_wheel for sklearn ... done
  Stored in directory: /root/.cache/pip/wheels/d7/db/a3/1b8041ab0be63b5c96c503df8e757cf205c2848cf9ef55f85e
Successfully built sklearn
Installing collected packages: scikit-learn, sklearn
  Found existing installation: scikit-learn 0.19.1
    Uninstalling scikit-learn-0.19.1:
      Successfully uninstalled scikit-learn-0.19.1
Successfully installed scikit-learn-0.19.1 sklearn-0.0

--------------------------------------------
/opt/rasa/anaconda/bin/python -m rasa_core.server -d models/core/ -u models/nlu/default/current
.....
Exception: Not all required packages are installed. To use this pipeline, you need to install the missing dependencies. Please install sklearn

**Comment by wrathagom** [comment]
@RachaRatan hopefully you got up and running (since it's been awhile :/ ) let us now if not!!!

**Comment by wuminghsuan** [comment]
@RachaRatan  I had the same problem as you. I did pip install "scipy" and passed "Please install sklearn". Hope it can help you.

**Comment by ZhaoZeqing** [comment]
me too using anaconda and had the same problem, but some solutions above can not solve the problem

**Comment by Ghostvv** [comment]
Do you have `scipy` installed? See: https://github.com/RasaHQ/rasa_nlu/issues/1315
PR to add it to dependencies: https://github.com/RasaHQ/rasa_nlu/pull/1316

**Comment by ZhaoZeqing** [comment]
@Ghostvv I had installed scipy, but still have the problem:

  File "rasa_nlu/model.py", line 146, in __init__
    components.validate_requirements(cfg.component_names)
  File "rasa_nlu/components.py", line 63, in validate_requirements
    "Please install {}".format(", ".join(failed_imports)))
Exception: Not all required packages are installed. To use this pipeline, you need to install the missing dependencies. Please install sklearn

here is my installed packages:
Package                            Version                  
---------------------------------- -------------------------
absl-py                            0.4.0                    
alabaster                          0.7.10                   
anaconda-client                    1.6.14                   
anaconda-navigator                 1.8.7                    
anaconda-project                   0.8.2                    
asn1crypto                         0.24.0                   
astor                              0.7.1                    
astroid                            1.6.3                    
astropy                            2.0.6                    
attrs                              18.1.0                   
Automat                            0.7.0                    
Babel                              2.5.3                    
backports-abc                      0.5                      
backports.functools-lru-cache      1.5                      
backports.shutil-get-terminal-size 1.0.0                    
backports.ssl-match-hostname       3.5.0.1                  
backports.weakref                  1.0.post1                
beautifulsoup4                     4.6.0                    
bitarray                           0.8.1                    
bkcharts                           0.2                      
blaze                              0.11.3                   
bleach                             1.5.0                    
bokeh                              0.12.16                  
boto                               2.48.0                   
boto3                              1.5.20                   
botocore                           1.8.50                   
Bottleneck                         1.2.1                    
bz2file                            0.98                     
cdecimal                           2.3                      
certifi                            2018.4.16                
cffi                               1.11.5                   
chardet                            3.0.4                    
click                              6.7                      
cloudpickle                        0.5.2                    
clyent                             1.2.2                    
colorama                           0.3.9                    
coloredlogs                        9.0                      
conda                              4.5.4                    
conda-build                        3.10.5                   
conda-verify                       2.0.0                    
configparser                       3.5.0                    
constantly                         15.1.0                   
contextlib2                        0.5.5                    
cryptography                       2.2.2                    
cycler                             0.10.0                   
cymem                              1.31.2                   
Cython                             0.28.2                   
cytoolz                            0.9.0.1                  
dask                               0.17.5                   
datashape                          0.5.4                    
decorator                          4.3.0                    
dill                               0.2.8.2                  
distributed                        1.21.8                   
docutils                           0.14                     
duckling                           1.8.0                    
entrypoints                        0.2.3                    
enum34                             1.1.6                    
et-xmlfile                         1.0.1                    
fastcache                          1.0.2                    
filelock                           3.0.4                    
Flask                              1.0.2                    
Flask-Cors                         3.0.4                    
funcsigs                           1.0.2                    
functools32                        3.2.3.post2              
future                             0.16.0                   
futures                            3.2.0                    
gast                               0.2.0                    
gensim                             3.5.0                    
gevent                             1.2.2                    
glob2                              0.6                      
gmpy2                              2.0.8                    
greenlet                           0.4.13                   
grin                               1.2.1                    
grpcio                             1.14.1                   
h5py                               2.7.1                    
heapdict                           1.0.0                    
html5lib                           0.9999999                
humanfriendly                      4.16.1                   
hyperlink                          17.3.1                   
idna                               2.6                      
imageio                            2.3.0                    
imagesize                          1.0.0                    
incremental                        17.5.0                   
ipaddress                          1.0.22                   
ipykernel                          4.8.2                    
ipython                            5.7.0                    
ipython-genutils                   0.2.0                    
ipywidgets                         7.2.1                    
isort                              4.3.4                    
itsdangerous                       0.24                     
jdcal                              1.4                      
jedi                               0.12.0                   
jieba                              0.39                     
Jinja2                             2.10                     
jmespath                           0.9.3                    
JPype1                             0.6.2                    
jsonschema                         2.6.0                    
jupyter                            1.0.0                    
jupyter-client                     5.2.3                    
jupyter-console                    5.2.0                    
jupyter-core                       4.4.0                    
jupyterlab                         0.32.1                   
jupyterlab-launcher                0.10.5                   
kiwisolver                         1.0.1                    
klein                              17.10.0                  
lazy-object-proxy                  1.3.1                    
llvmlite                           0.23.1                   
locket                             0.2.0                    
lxml                               4.2.1                    
Markdown                           2.6.11                   
MarkupSafe                         1.0                      
matplotlib                         2.1.0                    
mccabe                             0.6.1                    
mistune                            0.8.3                    
mitie                              0.5.0                    
mkl-fft                            1.0.0                    
mkl-random                         1.0.1                    
mock                               2.0.0                    
monotonic                          1.5                      
more-itertools                     4.1.0                    
mpmath                             1.0.0                    
msgpack                            0.5.6                    
msgpack-numpy                      0.4.3.1                  
msgpack-python                     0.5.4                    
multipledispatch                   0.5.0                    
murmurhash                         0.28.0                   
navigator-updater                  0.2.1                    
nbconvert                          5.3.1                    
nbformat                           4.4.0                    
networkx                           2.1                      
nltk                               3.3                      
nose                               1.3.7                    
notebook                           5.5.0                    
numba                              0.38.0+0.g2a2b772fc.dirty
numexpr                            2.6.5                    
numpy                              1.14.4                   
numpydoc                           0.8.0                    
odo                                0.5.1                    
olefile                            0.45.1                   
openpyxl                           2.5.3                    
packaging                          17.1                     
pandas                             0.23.0                   
pandocfilters                      1.4.2                    
parso                              0.2.0                    
partd                              0.3.8                    
path.py                            11.0.1                   
pathlib                            1.0.1                    
pathlib2                           2.3.2                    
patsy                              0.5.0                    
pbr                                4.2.0                    
pep8                               1.7.1                    
pexpect                            4.5.0                    
pickleshare                        0.7.4                    
Pillow                             5.1.0                    
pip                                18.0                     
pkginfo                            1.4.2                    
plac                               0.9.6                    
pluggy                             0.6.0                    
ply                                3.11                     
preshed                            1.0.1                    
prompt-toolkit                     1.0.15                   
protobuf                           3.6.1                    
psutil                             5.4.5                    
ptyprocess                         0.5.2                    
py                                 1.5.3                    
pycairo                            1.15.4                   
pycodestyle                        2.4.0                    
pycosat                            0.6.3                    
pycparser                          2.18                     
pycrypto                           2.6.1                    
pycurl                             7.43.0.1                 
pyflakes                           1.6.0                    
Pygments                           2.2.0                    
PyHamcrest                         1.9.0                    
pylint                             1.8.4                    
pyodbc                             4.0.23                   
pyOpenSSL                          18.0.0                   
pyparsing                          2.2.0                    
PySocks                            1.6.8                    
pytest                             3.5.1                    
python-crfsuite                    0.9.6                    
python-dateutil                    2.7.3                    
pytz                               2018.4                   
PyWavelets                         0.5.2                    
PyYAML                             3.12                     
pyzmq                              17.0.0                   
QtAwesome                          0.4.4                    
qtconsole                          4.3.1                    
QtPy                               1.4.1                    
rasa-nlu                           0.13.1                   
regex                              2017.4.5                 
requests                           2.18.4                   
rope                               0.10.7                   
ruamel-yaml                        0.15.35                  
s3transfer                         0.1.13                   
scandir                            1.7                      
scapy                              2.4.0                    
scikit-image                       0.13.1                   
scikit-learn                       0.19.1                   
scipy                              1.1.0                    
seaborn                            0.8.1                    
Send2Trash                         1.5.0                    
setuptools                         39.1.0                   
simplegeneric                      0.8.1                    
simplejson                         3.13.2                   
singledispatch                     3.4.0.3                  
six                                1.11.0                   
sklearn                            0.0                      
sklearn-crfsuite                   0.3.6                    
smart-open                         1.6.0                    
snowballstemmer                    1.2.1                    
sortedcollections                  0.6.1                    
sortedcontainers                   1.5.10                   
spacy                              2.0.11                   
Sphinx                             1.7.4                    
sphinxcontrib-websupport           1.0.1                    
spyder                             3.2.8                    
SQLAlchemy                         1.2.7                    
statsmodels                        0.9.0                    
subprocess32                       3.5.0                    
sympy                              1.1.1                    
tables                             3.4.3                    
tabulate                           0.8.2                    
tblib                              1.3.2                    
tensorboard                        1.8.0                    
tensorflow                         1.8.0                    
termcolor                          1.1.0                    
terminado                          0.8.1                    
testpath                           0.3.1                    
thinc                              6.10.3                   
toolz                              0.9.0                    
tornado                            5.0.2                    
tqdm                               4.19.5                   
traitlets                          4.3.2                    
Twisted                            18.7.0                   
typing                             3.6.2                    
ujson                              1.35                     
unicodecsv                         0.14.1                   
urllib3                            1.22                     
wcwidth                            0.1.7                    
webencodings                       0.5.1                    
Werkzeug                           0.14.1                   
wheel                              0.31.1                   
widgetsnbextension                 3.2.1                    
wrapt                              1.10.11                  
xlrd                               1.1.0                    
XlsxWriter                         1.0.4                    
xlwt                               1.3.0                    
zict                               0.1.3                    
zope.interface                     4.5.0

**Comment by Ghostvv** [comment]
could you try in python shell `import sklearn`?

**Comment by ZhaoZeqing** [comment]
yes, I tried and I also tried importlib.import_module("sklearn"), it's ok in python shell.

**Comment by Ghostvv** [comment]
Are you sure, you use the same `python`/`venv` for rasa?

**Comment by ZhaoZeqing** [comment]
Yes. I had checked it many times. I'm using anaconda2.
$ which pip
~/anaconda2/bin/pip
$ which python
~/anaconda2/bin/python
$ ls -l ~/anaconda2/lib/python2.7/site-packages/ | grep scipy
drwxrwxr-x. 20 zeqing wheel    4096 Aug 16 16:19 scipy
drwxrwxr-x.  2 zeqing wheel    4096 Aug 16 16:05 scipy-1.1.0-py2.7.egg-info
$ ls -l ~/anaconda2/lib/python2.7/site-packages/ | grep sklearn
drwxrwxr-x. 27 zeqing wheel    4096 Aug 16 16:17 sklearn
drwxrwxr-x.  2 zeqing wheel    4096 Aug 16 21:13 sklearn-0.0.dist-info
drwxrwxr-x.  2 zeqing wheel    4096 Aug 16 16:17 sklearn_crfsuite
drwxrwxr-x.  2 zeqing wheel    4096 Aug 16 16:17 sklearn_crfsuite-0.3.6.dist-info
$ ls -l ~/anaconda2/lib/python2.7/site-packages/ | grep scikit_learn
drwxrwxr-x.  2 zeqing wheel    4096 Aug 16 16:17 scikit_learn-0.19.1.dist-info

**Comment by ZhaoZeqing** [comment]
@Ghostvv I uninstalled scipiy and reinstalled it again, it's ok now! Thanks for your help :)

**Comment by sandzone** [comment]
@RachaRatan @wuminghsuan 'pip install scipy' solved the issue for me too
