### ISSUE TITLE
Performance Bench Mark 

### ISSUE THREAD

**Issue by danazen** [RasaHQ/rasa_nlu#621]
**Rasa NLU version**  :  0.10.0a5

**Used backend / pipeline** :   `spacy_sklearn`,

**Operating system** (windows, osx, ...): ubuntu

**Issue**:

1. Are there any performance bench mark available for rasa nlu (preferably with spacy pipeline)
2. Further, given a certain hardware configuration, I would like some guidance on improving performance.

**Content of configuration file** (if used & relevant):
```json
language ="en"
```

**Comment by tmbo** [comment]
You can use the `rasa_nlu/evaluate.py` script to evaluate your trained model on data file. There are papers around that compare the performance between different services (e.g. api.ai, rasa_nlu,...) if you are interested in that let me know and I'll look it up.

**Comment by danazen** [comment]
Thanks so much for your response. I was looking for the result of  rasa bench mark test for the following parameters.
1. Maximum number of intents and utterance supported
2. How much time did it take to test the maximum number of Intents and utterances.
3. What is the hardware requirement to support the bench mark test
4. Was there an impact on the confidence of the identified intents (with the maximum number of intents/utterance).
5. How can the performance be improved with a given hardware.
Please help me if you have the data for the above questions.

**Comment by wrathagom** [comment]
The biggest thing we talk about when these request come up are the training data sources to support such tests. If you have some in the Rasa format or another compatible format we'd be interested in them. But as it is many of the data sources that are being used by community members are considered proprietary I've never found a great dataset to do such testing.
