### ISSUE TITLE
Developer using Rasa should be able to start HTTP server easily from within Python

### ISSUE THREAD

**Issue by jfinkels** [RasaHQ/rasa_nlu#623]
As a developer using Rasa, I want to start the Rasa HTTP server easily from within a Python program, so that I can start a standalone Rasa server as if I had called `python -m rasa_nlu.server` from the command-line (for example, for testing interaction between two Python processes, one of which is a Rasa server).

One simple solution is to just place that code into a `main()` function and then simply call `main()` in the body of the `if` statement. A workaround that works right now is to essentially copy and paste the code under the `if __name__ == '__main__':` guard in the `rasa_nlu.server` module to the program where I want to start the process.

**Comment by roman-telepathy-ai** [comment]
do you really want this? once you started server, you will be not able to kill it (easily).
You might want to use a thread or queue...

**Comment by tmbo** [comment]
What is the use case, @jfinkels?

**Comment by wrathagom** [comment]
@jfinkels any response?

@tmbo want me to leave it open or close it if we don't get a use case. I am assuming close.

**Comment by kunalm37** [comment]
You can use subprocess.Popen("start /wait python -m rasa_nlu_server .....", shell = True) to spawn the server process in a new child window.

**Comment by jfinkels** [comment]
In the previous version of Rasa, there was a Flask app for which I could
create a test client for unit tests using `create_app().test_client()`. I'd
like to be able to do something similar with the Klein app, but I'm not
familiar with the Klein framework. One way of solving the problem is to
allow the user to spawn a new process in the setup test fixture and kill
that process in the teardown.

**Comment by wrathagom** [comment]
@PHLF I am sure I am awakening the beast, but any comment?

**Comment by PHLF** [comment]
If this is for testing purposes, have a look at [the current server tests](https://github.com/RasaHQ/rasa_nlu/blob/master/tests/base/test_server.py#L45): you should use a [StubTreq object](http://treq.readthedocs.io/en/latest/testing.html#writing-tests-for-http-clients) from the [treq lib](http://treq.readthedocs.io/en/latest/index.html) to fake a http server.

**Comment by wrathagom** [comment]
thanks @PHLF, @jfinkels post back if you want me to re-open.

**Comment by jfinkels** [comment]
I'll check it out, thank you.
