### ISSUE TITLE
thread-safe interpreter / components

### ISSUE THREAD

**Issue by roman-telepathy-ai** [RasaHQ/rasa_nlu#624]
Hi all,
I have not found a good place to post my question so it is here.

**rasa-nlu==0.9.2**

As far I understand the architecture - the interpreter is a holder of pipeline with components. Whereby loaded component can be cached in a builder to save loading time.

**is `Component.process(...)` thread-safe?**

I did some experiments calling interpreter in threads and seems to work. But still would like to have a confirmation from a developer.

Many Thanks in advance,
best,
r

**Comment by wrathagom** [comment]
@PHLF @tmbo?

**Comment by PHLF** [comment]
@wrathagom You never heard about the danger of summoning ancient and forgotten daemons?

1. simple answer : let's consider it thread-safe in the general case. If you're building a solution relying on Rasa NLU for a production environmnent, please refer to **2** 😃 
2. detailed answer : it depends as `Component` is a base class inherited by classifiers, featurizers, extractors... So the `process` method may be implemented in a thread safe manner or not. So you have to check for each component you wanna use if a call to a `self.method_X` in the implemented `process` method changes the object's internal state or not. If not, it's most likely not thread-safe.

**Comment by roman-telepathy-ai** [comment]
@PHLF thanks!
There are some components shipped with rasa - as have seen, then do not modify its state.
Therefore for any other component I implement on my own, is my own responsibility to keep it thread-safe.

Thx. can be slosed
