### ISSUE TITLE
Test_model doesn't work for all the intent??

### ISSUE THREAD

**Issue by melfk** [RasaHQ/rasa_nlu#628]
**Rasa NLU version = 0.10.1

**Used backend / pipeline = keyword

Operating system = MACOS Sierra

Issue: We trained the test_model as per documentation and it was successful. curl 'https://raw.githubusercontent.com/RasaHQ/rasa_nlu/master/data/examples/rasa/demo-rasa.json' | 
curl --request POST --header 'content-type: application/json' -d@- --url 'localhost:5000/train?project=test_model&pipeline=keyword'

However, we are passing differnt text to test the test_model it does not pick the right intent.
for example the following command should have found the affirm intent according to the test_model.

curl 'http://localhost:5000/parse?q=yep&model=test_model'
{"entities": [], "intent": {"confidence": 1.0, "name": "None"}, "text": "yep"}

**Comment by tmbo** [comment]
The `keyword` pipeline from the documentation is a super simple model that should actually not be used. Maybe it was a mistake to use it as an example. You need to use a different pipeline to get any good results: https://rasahq.github.io/rasa_nlu/pipeline.html

**Comment by tmbo** [comment]
e.g. install the dependencies for the `spacy_sklearn` pipeline and use that instead of the keyword one
