### ISSUE TITLE
How to send multiple data/text to train the model ?

### ISSUE THREAD

**Issue by Pallavi1693** [RasaHQ/rasa_nlu#629]
**Rasa NLU version = 0.10.1

**Used backend / pipeline = keyword

Operating system = MACOS Sierra

Issue: I  trained the test_model as per documentation and it was successful. curl 'https://raw.githubusercontent.com/RasaHQ/rasa_nlu/master/data/examples/rasa/demo-rasa.json' |
curl --request POST --header 'content-type: application/json' -d@- --url 'localhost:5000/train?project=test_model&pipeline=keyword'

However, I am passing differnt text to test the test_model it does not pick the right intent.
for example the following command should have found the affirm intent according to the test_model.

curl 'http://localhost:5000/parse?q=yep&model=test_model'
{"entities": [], "intent": {"confidence": 1.0, "name": "None"}, "text": "yep"}

**Comment by PHLF** [comment]
You mean
```bash
curl 'http://localhost:5000/parse?q=yep&PROJECT=test_model' {"entities": [], "intent": {"confidence": 1.0, "name": "None"}, "text": "yep"}
```
don't you?

Morerover you used the `keyword` pipeline for training which is a weak classifier.

**Comment by tmbo** [comment]
@Pallavi1693 Please also let us know where you got the later curl url from, maybe we've missed to update the parameter somewhere in the docs.
