### ISSUE TITLE
API.ai is now Dialogflow

### ISSUE THREAD

**Issue by deubaka** [RasaHQ/rasa_nlu#630]
Just thought that this deserves a ticket itself.

The _major_ changes aside from the name are:
- [In-line code editor](https://dialogflow.com/docs/how-tos/getting-started-fulfillment): you can now write fulfilment logic, test, and implement a functional webhook directly in the console.
> This, however, is irrelevant to rasa, so no changes.

- [Multi-lingual agent support](https://dialogflow.com/docs/multi-language): building for multiple languages is now easier than ever. You can now add additional languages and locales to your new or existing agent.
> Initially reported and addressed in #616 and #625.

With that, changes across _API.ai_-related documentation and codes seem to be in need. How do you generally approach this?

**Comment by tmbo** [comment]
Summing that up, the only thing left is to rename `api.ai` to `dataflow` everywhere, right?

**Comment by deubaka** [comment]
@tmbo Yes and removing support for any API.ai format support (a separate `api_legacy` format was added in  #625). What do you think?

**Comment by tmbo** [comment]
@deubaka let's remove the old API.ai format support. You can't download that format anyways. And if you want to use the old converter you can still install an older rasa version convert the data and install a new one.

**Comment by deubaka** [comment]
Added changes in #625.

**Comment by wrathagom** [comment]
@deubaka does #625 being merged fully close this issue?

**Comment by deubaka** [comment]
@wrathagom Yes. I've included updates on references in docs and code, as well as clean up any sample data of API.ai.

**Comment by wrathagom** [comment]
Okay, thanks. Closing.
