### ISSUE TITLE
AWS s3 model retrieval

### ISSUE THREAD

**Issue by clennan** [RasaHQ/rasa_nlu#633]
**Rasa NLU version** : 0.10.1

**Used backend / pipeline**:  spacy_sklearn

**Operating system**: osx

**Issue**:
Hi, I created an empty default projects folder and wanted to start a server with a model saved on s3.
It seems that the persistor throws the error when trying to list objects in the bucket

```
python -m rasa_nlu.server -c config.json
INFO:rasa_nlu.data_router:Logging requests to '/Users/CL/rasa_nlu/logs/rasa_nlu_log-20171011-150059-7072.log'.
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:boto3.resources.action:Calling s3:create_bucket with {'CreateBucketConfiguration': {u'LocationConstraint': u'eu-west-1'}, 'Bucket': u'ava-nlu-server-rasa-test'}
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): s3-eu-west-1.amazonaws.com
WARNING:rasa_nlu.persistor:Failed to list models for project default in AWS. 's3.Bucket' object has no attribute 'list'
INFO:__main__:Started http server on port 5000
2017-10-11 15:01:00+0200 [-] Log opened.
2017-10-11 15:01:00+0200 [-] Site starting on 5000
2017-10-11 15:01:00+0200 [-] Starting factory <twisted.web.server.Site instance at 0x106d9d368>
```

**Content of configuration file**:
```
{
  "pipeline": "spacy_sklearn",
  "bucket_name": "ava-nlu-server-rasa-test",
  "aws_region": "eu-west-1",
  "language": "en",
  "path": "./projects",
  "storage": "aws",
  "port": 5000
}
```

**Comment by DominicBreuker** [comment]
Requirements say boto3 is used for connecting to AWS, but `list` exists only in boto2 for Bucket objects. Added a quick fix in PR #637

**Comment by pradeepmvn** [comment]
@DominicBreuker After the PR #637 , if a project is specified in the config, rasa server will load the respective model from S3 during the startup and make them available for parse requests?

**Comment by DominicBreuker** [comment]
Have you tried it? I did not test with specific project names, only "empty" aka "default". 

After a quick look at the code, I suspect it will not work. I might dig into it further on the weekend to check it.

**Comment by pradeepmvn** [comment]
All the API's seem to be in place, the Project name is not added to the List of Projects to be loaded. Created a PR for that. Hope this helps.

**Comment by wrathagom** [comment]
Waiting on #691
