### ISSUE TITLE
Ngram featurizer fitting noise

### ISSUE THREAD

**Issue by twerkmeister** [RasaHQ/rasa_nlu#643]
**Rasa NLU version** (e.g. `0.10.1`):

**Used backend / pipeline** (..., `intent_featurizer_ngrams`, ...):

**Issue**:
I think the ngram featurizer should use reasonable ngrams by default, e.g. 2grams or 3grams, and only diverge when there is a strong enough signal. Otherwise we might simply fit to some noise in the training data. See below 
```
DEBUG:rasa_nlu.featurizers.ngram_featurizer:Evaluating usage of 1 ngrams. Score: 0.363302749387
DEBUG:rasa_nlu.featurizers.ngram_featurizer:Evaluating usage of 2 ngrams. Score: 0.363302749387
DEBUG:rasa_nlu.featurizers.ngram_featurizer:Evaluating usage of 3 ngrams. Score: 0.363302749387
DEBUG:rasa_nlu.featurizers.ngram_featurizer:Evaluating usage of 4 ngrams. Score: 0.338078286517
DEBUG:rasa_nlu.featurizers.ngram_featurizer:Evaluating usage of 5 ngrams. Score: 0.358586897329
DEBUG:rasa_nlu.featurizers.ngram_featurizer:Evaluating usage of 6 ngrams. Score: 0.36000907244
DEBUG:rasa_nlu.featurizers.ngram_featurizer:Evaluating usage of 7 ngrams. Score: 0.361385903733
DEBUG:rasa_nlu.featurizers.ngram_featurizer:Score without ngrams: 0.0
INFO:rasa_nlu.featurizers.ngram_featurizer:Best score with 1 ngrams: 0.363302749387
```

**Comment by amn41** [comment]
I'm not sure what you mean thomas - can you please explain in more detail?

**Comment by twerkmeister** [comment]
Sure! So, the ngram_featurizer tests which ngrams work best. Which is a great idea for domain adaption. There might be some domains where one works much better than the other. However, it might also not make a big difference, as in my case above. In fact, unigrams, bigrams, and trigrams had the same score and the rasa picked the unigrams which basically translates to features like a,b,c,d,e,... right? Actually I have two points here.

1. I assume unigrams are rarely helpful. As there are only a handful of them and there presence is probably relatively uniform across sentences of English thus giving little useful information to the intent classifier.

2. bigrams or trigrams should be a reasonable default for most domains. It translates into quite a number of features, that actually contain some information. 4-7 grams might be too fine-grained in many cases. They translate into a huge amount of features that rarely occur (sparsity). That is why, we shouldn't make a move to use them if there isn't a strong signal for them. Right now they would be used even if they just have an 0.000001 edge over bi- or trigrams. However, bi- and trigrams will usually generalize much better to test data than the specialized highgrams (lol, just made up this word ^^).

The change I propose is to a) cut unigrams completely because I think they are not helpful and thus might confuse users, and b) pick either bi- or trigrams as the default and only switch if there is enough evidence that another ngram is actually better in this domain. This might mean a couple percentage points in difference

**Comment by twerkmeister** [comment]
Actually unigrams might make sense for Chinese 🤔

**Comment by amn41** [comment]
also longer ngrams make sense for german compound words - virtually all of which are out of vocabulary

**Comment by tmbo** [comment]
@twerkmeister you are interpreting the logging incorrectly, in 
```
DEBUG:rasa_nlu.featurizers.ngram_featurizer:Evaluating usage of 2 ngrams. Score: 0.36330274938
```
The `2 ngrams` is not referring to ngrams of length 2 but to "use two ngrams" whos length is unknown. The model creates ngrams of different lengths, sorts them according to there usefullness and then starts to add them to the feature vector one after another until the model doesn't get better anymore. So the first added ngram could be `"en"` the second `"bart"` the third `"be"` and so one. The result after adding the fourth ngram is this line:
```
DEBUG:rasa_nlu.featurizers.ngram_featurizer:Evaluating usage of 4 ngrams. Score: 0.338078286517
```

**Comment by twerkmeister** [comment]
Ok, good to know :+1:, closing this then!

**Comment by znat** [comment]
About unigram making sense: could '$' generate a feature for sentences generally containing an amount of money?
RegexFeaturize could be used to but I think it only works with the crf.
