### ISSUE TITLE
How to include RASA NLU in python code?

### ISSUE THREAD

**Issue by efvaldez1** [RasaHQ/rasa_nlu#646]
Hi All, I have a flask web app with a chatbot in it, I used to have api.ai but I know rasa nlu is better. After going to the tutorials, I followed http://rasa-nlu.readthedocs.io/en/latest/python.html?highlight=python#. 
I added the code in my __init__.py since my @routes will be there and then I plan to use interpreter inside a route. However when I run python run.py, it trains the model then keeps restarting. I tried creating a separate file train.py  containing:

```
from rasa_nlu.converters import load_data
from rasa_nlu.config import RasaNLUConfig
from rasa_nlu.model import Trainer
from rasa_nlu.components import ComponentBuilder

builder = ComponentBuilder(use_cache=True)
training_data = load_data('/var/www/new/registration/data/examples/rasa/demo-rasa.json')

trainer = Trainer(RasaNLUConfig("/var/www/new/registration/sample_configs/config_spacy.json"),builder)
trainer.train(training_data)
model_directory = trainer.persist('/var/www/new/registration/projects/default/')**


Then in my __init__.py

I have the following.
from rasa_nlu.config import RasaNLUConfig
from rasa_nlu.model import Metadata, Interpreter
from .train import *

config= RasaNLUConfig("/var/www/new/registration/sample_configs/config_spacy.json")
interpreter = Interpreter.load(model_directory,config,builder)
```

After running run.py
![image](https://user-images.githubusercontent.com/8022105/31881295-b06b22e2-b815-11e7-9543-51023fc96e4f.png)

it train it successfully then restarts the server again then stops/kills the server suddenly, How can I add rasa nlu to my python code? Thanks

**Comment by alexweidauer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [test card](https://trello.com/c/k1J4bq01/1-test-card)

**Comment by wrathagom** [comment]
@efvaldez1 how were you interacting with API.ai? I assume via an API endpoint. If that's true I would encourage you to use Rasa in Docker and interact with it via it's own [HTTP API](https://rasahq.github.io/rasa_nlu/master/http.html). you may be able to get near plug and play compatibility using the [emulation](https://rasahq.github.io/rasa_nlu/master/migrating.html#emulation) functionality. 

Are you by any chance running on a computer/server/vm with very little memory allocated?

**Comment by wrathagom** [comment]
Closing from inactivity, see above questions/answer and let us know if you never got this working,
