### ISSUE TITLE
UnicodeEncodeError under python2 caused by warning message

### ISSUE THREAD

**Issue by howl-anderson** [RasaHQ/rasa_nlu#647]
**Rasa NLU version** (e.g. `0.7.3`):
0.10.1

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...):
spacy_sklearn

**Operating system** (windows, osx, ...):
Mac osx

**Issue**:
**Under python2**, if there have an unicode-named intent has only 1 training examples, like below:

```json
{
  "rasa_nlu_data": {
    "entity_synonyms": [],
    "common_examples": [
      {
        "text": "中文样例",
        "intent": "中文意图"
      },
      {
        "text": "中文样例2",
        "intent": "中文意图2"
      }
    ]
  }
}
```

training RASA__NLU will cause fatal exception like this:

    UnicodeEncodeError: 'ascii' codec can't encode characters in position 8-11: ordinal not in range(128)

which supposed to output warning message like:

    UserWarning: Intent '中文意图' has only 1 training examples! minimum is 2, training may fail.

**How to fix**

This bug is caused by python2's standard library `warnings` which not support unicode warning message. I will submit a pull request to fix this bug.

**Comment by tmbo** [comment]
Fixed in latest master
