### ISSUE TITLE
Model in training status, "unknown training file format : unk for file"

### ISSUE THREAD

**Issue by ChamathK** [RasaHQ/rasa_nlu#650]
**Rasa NLU version** : "0.10.0" Docker latest full

**Used backend / pipeline** : "nlp_spacy", "tokenizer_spacy", "intent_featurizer_spacy", "ner_crf", "ner_synonyms", "intent_classifier_sklearn", "ner_duckling"

**Operating system** (windows, osx, ...): Ubuntu 16.04, docker version 17.03.1-ce

**Issue**: When trying to train a new project it is giving the following error on post request. 
{"error": "unknown training file format : unk for file /tmp/tmpy31sXe_training_data"}

I am trying to train a new project using the tutorial found in [https://rasahq.github.io/rasa_nlu/http.html#post-train](url)

`curl -XPOST localhost:5000/train?project=my_project -d demo-rasa.json`

When checking the status, using http://localhost:5000/status
{"available_projects": "default": {"status": "ready", "available_models": ["model_20171006-062344"]}, "my_project": {"status": "training", "available_models": ["fallback"]}}}

**"my_project" is not in ready status, remains in training status.**

Config.json
[config.txt](https://github.com/RasaHQ/rasa_nlu/files/1413587/config.txt)

**Comment by PHLF** [comment]
You're just missing the `@` symbol in your request which is a `curl` specific instruction to load the content of the file at the relative path `demo-rasa.json` : 

```bash
$ curl -XPOST localhost:5000/train?project=my_project -d @data/examples/rasa/demo-rasa.json
```

**Comment by amn41** [comment]
@PHLF is right - but the project shouldn't get stuck in training status. See #652

**Comment by tmbo** [comment]
I guess this is fixed now :)

**Comment by ChamathK** [comment]
@PHLF thanks for the support. Solution worked!
