### ISSUE TITLE
how to know if a training task is success

### ISSUE THREAD

**Issue by zhuscat** [RasaHQ/rasa_nlu#654]
**Rasa NLU version** : `0.10.0`

**Operating system**: macOS

**Issue**:

I'm writing a management system to manage intent, entity, send data to train etc.

And I have a set of training data, which has about 8000 intents. However, there is some problem with the training data, so `rasa_nlu` output:

```
exceptions.Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=2
```

Does this means the training task is failed. Because I wait for a long time, but there is no output anymore.

However, when I request `/status`, the `status` of the project is `training`. It seems the `status` will always be `training`...

My question is, is there any way to know if a training task is failed from the HTTP server.

**Comment by wrathagom** [comment]
@zhuscat can you verify that installing the latest version fixes your problem or at least highlights it better?

**Comment by zhuscat** [comment]
I update `rasa_nlu` to `0.10.4`,  and use the same dataset.

Here is the log

```
INFO:rasa_nlu.model:Finished training component.
INFO:rasa_nlu.model:Starting to train component ner_synonyms
INFO:rasa_nlu.model:Finished training component.
INFO:rasa_nlu.model:Starting to train component intent_entity_featurizer_regex
INFO:rasa_nlu.model:Finished training component.
INFO:rasa_nlu.model:Starting to train component intent_featurizer_mitie
INFO:rasa_nlu.model:Finished training component.
INFO:rasa_nlu.model:Starting to train component intent_classifier_sklearn
```

```
2017-11-02 11:24:24+0800 [-] Fitting 2 folds for each of 6 candidates, totalling 12 fits
```

```
2017-11-02 11:24:24+0800 [-] /Library/Python/2.7/site-packages/sklearn/model_selection/_split.py:597: exceptions.Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=2.
```

```
2017-11-02 11:25:42+0800 [-] /Library/Python/2.7/site-packages/sklearn/metrics/classification.py:1135: sklearn.exceptions.UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
```

This seems the training is failed?

But the `status` is still training...

**Comment by wrathagom** [comment]
what is the result of `/status`?

I think @amn41 was saying that the status endpoint would show that the training had completed/failed.

You still need to address the root of the problem, if I remember that error message correctly it means that some place you have an intent that only has 1 training example, which is too few to actually train with.

**Comment by zhuscat** [comment]
Yes, there is many intents only have 1 training example.

The result is like:

```json
{
  "available_projects":  {
    "my_project": {
      "status": "training",
      "available_models": ["fallback"]
    }
}
```

From the docs, there is only two status for now: `ready` and `training`？

**Comment by wrathagom** [comment]
what is the result of `/version`?

**Comment by zhuscat** [comment]
It turns that my dataset can be successfully trained.

It takes about 8 minutes.

When I saw the warning, and no more logs were produced, I thought the task was failed...

So, from my understanding, if a task is really failed, the `status` will become `ready`, am I right?

**Comment by zhuscat** [comment]
Yes

**Comment by zizhec** [comment]
@wrathagom 
I would imagine though that all of those intents you mentioned with only 1 utterance aren't in the model?

Why is that the case?
