### ISSUE TITLE
`nlp_mitie` limit the portability of model

### ISSUE THREAD

**Issue by howl-anderson** [RasaHQ/rasa_nlu#655]
**Rasa NLU version** (e.g. `0.7.3`):
0.10.1

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...):
mitie

**Operating system** (windows, osx, ...):
osx

**Issue**:
Currently, `nlp_mitie` just save the path of `mitie_file` to metadata which make model not portable: if model need copied to other server, user also need copy `mitie_file` to server and make sure put to correct path or change `metadata.json` make sure `mitie_file` set to the correct value.

**Comment by wrathagom** [comment]
I closed the PR, but I think we should discuss the end goal here some more.

Maybe the path just shouldn't be persisted at all and instead always read from he global configuration? or we should try the path and if it fails fallback to the path in the configuration file?

**Comment by howl-anderson** [comment]
The global configuration way doesn't work. There are many projects and models, each one may use different `mitie_file`, use global configuration will force all models use the same `mitie_file` which is not desirable.

**Comment by tmbo** [comment]
THis is related to an update of the configuraiton format. I will close this is in favour of #610
