### ISSUE TITLE
Mark only part of words as entities (versus whole words)?

### ISSUE THREAD

**Issue by pheraph** [RasaHQ/rasa_nlu#657]
**Rasa NLU version**: 0.10.1
**Used backend / pipeline**: spacy_sklearn
**Operating system**: linux

If I mark only a part of a word as entity the python trainer returns a warning. Is this something that should work?

`WARNING:rasa_nlu.extractors.crf_entity_extractor:Misaligned entity annotation in sentence 'Zeig mir Bilder unter einer CC0-Lizenz.'. Make sure the start and end values of the annotated training examples end at token boundaries (e.g. don't include trailing whitespaces).`

This is the relevant part of the training file:

```json
      {
        "text": "Zeig mir Bilder unter einer CC0-Lizenz.",
        "intent": "oer_search",
        "entities": [
          {
            "start": 9,
            "end": 13,
            "value": "Bild",
            "entity": "resource"
          },
          {
            "start": 28,
            "end": 31,
            "value": "CC0",
            "entity": "license"
          }
        ]
      },
```

**Comment by pheraph** [comment]
OK, now I understand the entity value can differ from the selected text, so I modified the training file:

```json
      {
        "text": "Zeig mir Bilder unter einer CC0-Lizenz.",
        "intent": "oer_search",
        "entities": [
          {
            "start": 9,
            "end": 15,
            "value": "Bild",
            "entity": "resource"
          },
          {
            "start": 28,
            "end": 31,
            "value": "CC0",
            "entity": "license"
          }
        ]
      },
```

And the python trainer no longer complains. :-)

**Comment by saishaga** [comment]
here X is also an entity but i'm unable to extract it
pprint(interpreter.parse("Our yearly revenue has grown at a 50X rate to $22,500 over the last two years"))

{
  "intent": {
    "name": "revenue",
    "confidence": 0.9284462221808045
  },
  "entities": [
    {
      "start": 23,
      "end": 28,
      "value": "increased",
      "entity": "verb",
      "confidence": 0.960265495627011,
      "extractor": "ner_crf",
      "processors": [
        "ner_synonyms"
      ]
    },
    {
      "start": 46,
      "end": 47,
      "value": "$",
      "entity": "unit",
      "confidence": 0.9452229431259471,
      "extractor": "ner_crf"
    },
    {
      "start": 47,
      "end": 53,
      "value": "22,500",
      "entity": "value",
      "confidence": 0.9166615710795952,
      "extractor": "ner_crf"
    },
    {
      "start": 63,
      "end": 77,
      "value": "last two years",
      "entity": "time",
      "confidence": 0.978303264391344,
      "extractor": "ner_crf"
    }
  ],
  "intent_ranking": [
    {
      "name": "revenue",
      "confidence": 0.9284462221808045
    },
    {
      "name": "customers",
      "confidence": 0.07155377781919549
    }
  ],
  "text": "Our yearly revenue has grown at a 50X rate to $22,500 over the last two years"
}
