### ISSUE TITLE
Parse does not return a intent for simple model '"intent": null'

### ISSUE THREAD

**Issue by ChamathK** [RasaHQ/rasa_nlu#658]
**Rasa NLU version** : "0.10.0" Docker latest full

**Used backend / pipeline** : "nlp_spacy", "tokenizer_spacy", "intent_featurizer_spacy", "ner_crf", "ner_synonyms", "intent_classifier_sklearn", "ner_duckling"

**Operating system** : Ubuntu 16.04, docker version 17.03.1-ce

**Issue**: Parse does not return a intent for simple model

training json : 
`{"rasa_nlu_data":{"common_examples":[{"entities":[],"text":"hello","intent":"greet"},{"entities":[],"text":"hi","intent":"greet"}]}}`

`curl -XPOST localhost:5000/parse -d '{"q":"hello", "project": "my_project"}'`

result : 
`{"entities": [], "intent": null, "text": "hello", "intent_ranking": []}`

Am i missing any configuration to achieve this?

status : 
`{"available_projects":{"default":{"status":"ready","available_models":["model_20171006-062344"]},"my_project":{"status":"ready","available_models":["fallback","model_20171027-093344"]}}}`

Config.json
[config.txt](https://github.com/RasaHQ/rasa_nlu/files/1421732/config.txt)

**Comment by wrathagom** [comment]
If I remember right you need more than one intent in your training data. Check your console as you should've received a warning about this.

```
WARNING:rasa_nlu.classifiers.sklearn_intent_classifier:Can not train an intent classifier. Need at least 2 different classes. Skipping training of intent classifier.
```

**Comment by ChamathK** [comment]
I didn't see the warning for the curl. Anyway I can put an additional dummy intent to achieve my task.

Finding the classification for one intent should be a use case right? May I know the reason for this?

**Comment by ChamathK** [comment]
I am trying new training data with two intents,
```json
{
  "rasa_nlu_data": {
    "common_examples": [
      {
        "entities": [],
        "text": "Bye",
        "intent": "goodbye"
      },
      {
        "entities": [],
        "text": "hello",
        "intent": "greet"
      },
      {
        "entities": [],
        "text": "hi",
        "intent": "greet"
      }
    ]
  }
}
```
I got the following error
`{"error": "The number of classes has to be greater than one; got 1"}`

**Comment by ChamathK** [comment]
@wrathagom can we reopen the issue?

**Comment by ChamathK** [comment]
The error is gone for the following training data,

```json
{
  "rasa_nlu_data": {
    "common_examples": [
      {
        "entities": [],
        "text": "bye",
        "intent": "goodbye"
      },
      {
        "entities": [],
        "text": "goodbye",
        "intent": "goodbye"
      },
      {
        "entities": [],
        "text": "hello",
        "intent": "greet"
      },
      {
        "entities": [],
        "text": "hi",
        "intent": "greet"
      }
    ]
  }
}
```
Can anyone explain, how this works, any good documentation?

**Comment by wrathagom** [comment]
Just need to make sure you have more than one training example. The error your seeing isn't actually generated by Rasa, but rather the underlying tools Rasa uses. I don't know if we can intercept and improve the error messages or not.

@tmbo FYI.
