### ISSUE TITLE
Exception: Not all required packages are installed. To use this pipeline, you need to install the missing dependencies. Please install sklearn

### ISSUE THREAD

**Issue by irfan-zoefit** [RasaHQ/rasa_nlu#660]
I've update the rasa_nlu version and now getting the requirement not satisified issue.

**Rasa NLU version** (rasa-nlu==0.10.3):
Python=2.7.10
```shell
pip freeze
attrs==17.2.0
Automat==0.6.0
backports.functools-lru-cache==1.4
boto3==1.4.7
botocore==1.7.36
certifi==2017.7.27.1
chardet==3.0.4
cloudpickle==0.4.1
constantly==15.1.0
cycler==0.10.0
cymem==1.31.2
cytoolz==0.8.2
dill==0.2.7.1
docutils==0.14
ftfy==4.4.3
functools32==3.2.3.post2
future==0.16.0
futures==3.1.1
gevent==1.2.2
greenlet==0.4.12
html5lib==0.999999999
hyperlink==17.3.1
idna==2.6
incremental==17.5.0
jmespath==0.9.3
jsonschema==2.6.0
klein==17.10.0
matplotlib==2.1.0
murmurhash==0.26.4
numpy==1.13.3
pathlib==1.0.1
plac==0.9.6
preshed==1.0.0
pyparsing==2.2.0
python-crfsuite==0.9.5
python-dateutil==2.6.1
pytz==2017.2
rasa-nlu==0.10.3
regex==2017.9.23
requests==2.18.4
s3transfer==0.1.11
scikit-learn==0.19.1
simplejson==3.11.1
six==1.11.0
sklearn==0.0
sklearn-crfsuite==0.3.6
spacy==1.9.0
subprocess32==3.2.7
tabulate==0.8.1
termcolor==1.1.0
thinc==6.5.2
toolz==0.8.2
tqdm==4.19.4
Twisted==17.9.0
typing==3.6.2
ujson==1.35
urllib3==1.22
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.12.2
wrapt==1.10.11
zope.interface==4.4.3
```
**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...):
["nlp_spacy", "tokenizer_spacy", "intent_entity_featurizer_regex", "intent_featurizer_spacy", "ner_crf", "ner_synonyms",  "intent_classifier_sklearn"]

**Operating system** ( osx):

**Issue**:
(.carecinch) Macbook-pro-core-i-7:carecinch mirfan$ python -m rasa_nlu.train -c config.json
INFO:rasa_nlu.components:Couldn't read dev-requirements.txt. Error: [Errno 2] No such file or directory: u'/Users/mirfan/appify/carecinch/.carecinch/lib/python2.7/site-packages/rasa_nlu/../alt_requirements/requirements_dev.txt'
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/mirfan/appify/carecinch/.carecinch/lib/python2.7/site-packages/rasa_nlu/train.py", line 125, in <module>
    do_train(config)
  File "/Users/mirfan/appify/carecinch/.carecinch/lib/python2.7/site-packages/rasa_nlu/train.py", line 111, in do_train
    trainer = Trainer(config, component_builder)
  File "/Users/mirfan/appify/carecinch/.carecinch/lib/python2.7/site-packages/rasa_nlu/model.py", line 126, in __init__
    components.validate_requirements(config.pipeline)
  File "/Users/mirfan/appify/carecinch/.carecinch/lib/python2.7/site-packages/rasa_nlu/components.py", line 96, in validate_requirements
    "Please install {}".format(", ".join(failed_imports)))
Exception: Not all required packages are installed. To use this pipeline, you need to install the missing dependencies. Please install sklearn
**Content of configuration file** (if used & relevant):
```json
{
  "pipeline": ["nlp_spacy", "tokenizer_spacy", "intent_entity_featurizer_regex", "intent_featurizer_spacy", "ner_crf", "ner_synonyms",  "intent_classifier_sklearn"],
  "path" : "./models",
  "data" : "./data/",
  "spacy_model_name": "en_default",
  "emulate": "api",
  "language": "en"
}
```

**Comment by ray-man** [comment]
@irfan-zoefit  Maybe this ? It worked just fine for me.
`pip install -U scikit-learn scipy sklearn-crfsuite`

**Comment by wrathagom** [comment]
Sounds like this was just a small hiccup due to upgrading/installing.

**Comment by axxiao** [comment]
I had same error message and it was casued by incorrect setting of LD_LIBRARY_PATH (did not include anaconda3/lib)

Found the missing by:
```
import importlib
package='sklearn'
importlib.import_module(package)
```
showed: ImportError: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found...

Fix: export LD_LIBRARY_PATH=<path to anaconda3>/lib:$LD_LIBRARY_PATH
