### ISSUE TITLE
How to remove a project?

### ISSUE THREAD

**Issue by ChamathK** [RasaHQ/rasa_nlu#661]
**Rasa NLU version** (e.g. `0.7.3`): "0.10.0" Docker latest full

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...): "nlp_spacy", "tokenizer_spacy", "intent_featurizer_spacy", "ner_crf", "ner_synonyms", "intent_classifier_sklearn", "ner_duckling"

**Operating system** (windows, osx, ...): Ubuntu 16.04, docker version 17.03.1-ce

**Issue**: I started my training with the data with only one intent in the training data #658, Now I am having project retrain issue via http endpoint #529 . 

It is giving read timeout (5mins) for new training data of

```json
{"rasa_nlu_data":{"common_examples":[{"entities":[],"text":"Bye","intent":"goodbye"},{"entities":[],"text":"hello","intent":"greet"},{"entities":[],"text":"hi","intent":"greet"}]}}
```
As there is no endpoint to remove a existing project #433 , How can i remove this project manually and start over? 
[config.txt](https://github.com/RasaHQ/rasa_nlu/files/1423935/config.txt)

**Comment by PHLF** [comment]
Just delete the corresponding folder under the [path](https://rasa-nlu.readthedocs.io/en/latest/config.html#path) directory.

**Comment by ChamathK** [comment]
@PHLF thanks, it works. 

- go to container 
`docker exec -it "gallant_bell" bash`
- go to the project directory
`cd projects`
- remove the folder "my_project"
`rm -R my_project`
- restart the container
`docker restart gallant_bell `
