### ISSUE TITLE
text-cnn classification for intent classifier

### ISSUE THREAD

**Issue by sichun** [RasaHQ/rasa_nlu#662]
**Issue**:
I plan to classify intent with text-cnn. Due to the requirement of dataset size, I don't have huge samples as input. There are several worries;
1. is it convenient to build a new pipeline with new components 
2. small dataset size must influence the results of classification. if I have 10 samples per intents, how to get a similar result with a big dataset.
3. or any other deep learning classifier can be recommended.

if any idea, pls comment on. Thanks

**Comment by wrathagom** [comment]
I would get this working outside of Rasa NLU before I ever try to bring text-can in. and you'll probably get better support on how to improve the results from text-can by engaging their community. I don't know of anyone else who is using it inside or with Rasa.

**Comment by sichun** [comment]
em, you mean you have tried the text-cnn classification method,  I can't find your method, and the community is what?  the rasa_nlu community? @wrathagom

**Comment by wrathagom** [comment]
My point was that you seem to have fundamental questions about deep learning classifiers, which re probably best asked elsewhere. for example [here](https://github.com/dennybritz/cnn-text-classification-tf). Once you have a toolset like that working outside of Rasa then we will be better able to help you bring it inside of Rasa if it makes sense to do so.

**Comment by sichun** [comment]
indeed,  I have really followed a model in [here](https://github.com/jiegzhan/multi-class-text-classification-cnn-rnn), but that need a big training data. Whereas, rasa_nlu use a small dataset that has a bad influence of text-cnn. Thus I still find the solution to solve the problem with a small dataset. 
Moreover, the toolset as you said means a black box whose input is the rasa_samples and output is intent(I don't care entity extractor) @wrathagom
