### ISSUE TITLE
Rasa NLU v0.10.1 issues while training.

### ISSUE THREAD

**Issue by ray-man** [RasaHQ/rasa_nlu#664]
Rasa NLU version : 0.10.1

Used backend / pipeline: ("nlp_spacy", "tokenizer_spacy", "intent_entity_featurizer_regex", "intent_featurizer_spacy", "intent_classifier_sklearn", "ner_crf", "ner_synonyms")

Operating system: OSX 10.11.6

Issue:

1. 

While training 'default' folder is added in my models folder as parent directory to all training models.
e.g: info/models/nlu/**default**/model_20171030-092415,
info/models/nlu/**default**/model_20171029-092415

while my code is 
`cwd = os.path.abspath(os.path.dirname(__file__))`
`training_data = load_data(cwd +'/data/data_nlu.json')`
`trainer = Trainer(RasaNLUConfig(cwd +'/data/config_nlu.json'))`
`trainer.train(training_data)`
`model_directory = trainer.persist(cwd +'/models/nlu/')`
`return model_directory`
any way to get rid of this DEFAULT named folder ?

2.  if i use `model_directory = trainer.persist(cwd +'/models/nlu/', fixed_model_name='tc_nlu')` while training, first time training goes well but on trying to train again i get
**TypeError: Cannot interpret feed_dict key as Tensor: Tensor Tensor("masking_1_input:0", shape=(?, 3, 23), dtype=float32) is not an element of this graph.**

error unless i remove the 'default/tc_nlu' folder.

**Comment by ray-man** [comment]
@tmbo , @amn41 , @deubaka guys any workaround or fix ?

**Comment by wrathagom** [comment]
default here is the project name not the model name. I'm not the best reference when using direct in python, but this can be changed with this configuration variable. https://rasahq.github.io/rasa_nlu/master/config.html#project

**Comment by ray-man** [comment]
@wrathagom @tmbo @rasa @nkabrich @phoet @sheldon guys any response over **TypeError: Cannot interpret feed_dict key as Tensor: Tensor Tensor("masking_1_input:0", shape=(?, 3, 23), dtype=float32) is not an element of this graph.** this error am facing while trying to train ?

**Comment by ray-man** [comment]
Thanks fixed the issue guess it was a mismatch between config file and nlu version.
