### ISSUE TITLE
Dialogflow example failed.

### ISSUE THREAD

**Issue by VincentMD** [RasaHQ/rasa_nlu#666]
**Rasa NLU version** (`0.10.3`):

**Used backend / pipeline** ( `spacy_sklearn`, ...):

**Operating system** (windows, osx, ...):
Linux - Ubuntu

**Issue**:
Try to use dialogflow examples with new format.

- Some intents are missing when use dialogflow sample, 
Only 2 intents found. No logs or errors in train result to explain why some file are not read.

```code
INFO:rasa_nlu.utils.spacy_utils:Trying to load spacy model with name 'en'
INFO:rasa_nlu.components:Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
INFO:rasa_nlu.converters:Training data format at ./dialogflow is api
INFO:rasa_nlu.training_data:Training data stats:
        - intent examples: 12 (2 distinct intents)
        - found intents: 'hi', 'inform'
        - entity examples: 5 (2 distinct entities)
        - found entities: 'cuisine', 'location'
```

- In rasa_nlu/data/test/dialogflow_en_converted_to_rasa.json, intents are also missing. 

**Content of configuration file** (if used & relevant):
```json
{
  "pipeline": "spacy_sklearn",
  "data" : "./dialogflow",
  "path" : "./models",
  "log_level": "DEBUG",
  "response_log" : "./logs",
  "language" : "en"
}
```

**Comment by tmbo** [comment]
The format reading has been updated in the meantime (your log still show `Training data format at ./dialogflow is api`).
