### ISSUE TITLE
Intent Score is varying on each training of Rasa Nlu model

### ISSUE THREAD

**Issue by RachaRatan** [RasaHQ/rasa_nlu#667]
**Rasa NLU version** (e.g. `0.7.3`): 0.10.0a6  

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...): ["nlp_spacy", "tokenizer_spacy", "intent_featurizer_spacy","ner_crf", "ner_synonyms", "intent_classifier_sklearn","ner_spacy"]

**Operating system** (windows, osx, ...): Windows server 2012

**Issue**:  I have trained Rasa for one intent along with some utterences.
after training I have executed parse request as below.
**Req-1:**  http://localhost:5000/parse?q=finance%20partner&project=People

And I got the response as below.
[Parse Response.txt](https://github.com/RasaHQ/rasa_nlu/files/1427966/Parse.Response.txt)

After I have trained Rasa for one another intent along with some other utterences.
And I executed prase requests as below.
**Req-2:** http://localhost:5000/parse?q=chief%20executive%20partner&project=People
[Parse Request-1.txt](https://github.com/RasaHQ/rasa_nlu/files/1427975/Parse.Request-1.txt)

Now Again I executed parse request for above **Req-1** as below.
http://localhost:5000/parse?q=finance%20partner&project=People
[Parse Response -2.txt](https://github.com/RasaHQ/rasa_nlu/files/1427982/Parse.Response.-2.txt)

I got different confidence score for same request and decreased it.

In such way for training I am getting different confidence score. if I execute training command without doing any changes in intents and utterances, I am getting different confident score.

On every training the confidence score is fluctuating.

Please let me know what is reason for fluctuating score. 
Is it default behavior of Rasa Nlu?
if so how can I stop this behavior.

**Content of configuration file** (if used & relevant):
```json
{
  
	"project":"People",
	"pipeline" : ["nlp_spacy", "tokenizer_spacy", "intent_featurizer_spacy","ner_crf", "ner_synonyms", "intent_classifier_sklearn","ner_spacy"],
	"path" : "./projects",

	"cors_origins":["*"],
	"data" : "./data/examples/rasa/AbbieData.json"

}

```

Please suggest on this and help me to fix it.

Thank you..

**Comment by wrathagom** [comment]
I can give more details if needed, but the simple answer is that this is expected behavior.

Every time you change the training data expect the resultant scores to change. Is Rasa NLU parsing the correct intent each time?

**Comment by RachaRatan** [comment]
Yes Rasa is parsing the correct intent each time but I have seen in some scenarios, Rasa is returning worng intent instead returning None. 
Is this the default behavior or is there any configuration needed to be done?

**Comment by tmbo** [comment]
@RachaRatan Rasa does never* return `None`. It will always select one of the intents you trained it on.

*: let's say almost never - only if the model did not load properly.

**Comment by wrathagom** [comment]
See the discussion on this issue https://github.com/RasaHQ/rasa_nlu/issues/387
