### ISSUE TITLE
Testing installation

### ISSUE THREAD

**Issue by doraithodla** [RasaHQ/rasa_nlu#669]
**Rasa NLU version** 
0.10.4

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...):

**Operating system**
windows

**Issue**:

curl 'http://localhost:5000/parse?q=hello'
curl: (1) Protocol "'http" not supported or disabled in libcurl

curl 'https://localhost:5000/parse?q=hello'
curl: (1) Protocol "'https" not supported or disabled in libcurl

**Comment by wrathagom** [comment]
Can you try with double quotes?

https://stackoverflow.com/questions/6684235/perl-curl-1-protocol-http-not-supported-or-disabled-in-libcurl

**Comment by doraithodla** [comment]
Double quotes work. 
C:\Users\Dorai>curl "http://localhost:5000/parse?q=hello"
{"intent": {"name": "greet", "confidence": 1.0}, "entities": [], "text": "hello"}
C:\Users\Dorai>

Should we change it in the documentation? Do you want me to do a pull request?

**Comment by wrathagom** [comment]
PR would be great.

**Comment by doraithodla** [comment]
Done. This is my first pull request. Not sure about the right etiquette. So
created a branch.

https://github.com/doraithodla/rasa_nlu/pull/1




-- Dorai

http://www.doraithodla.com/
<http://lbok.in/>
LinkedIn Profile <http://www.linkedin.com/in/doraithodla>
@dorait <https://twitter.com/dorait>
<http://lbok.in/>
