### ISSUE TITLE
Dialogflow import failing

### ISSUE THREAD

**Issue by thomas-mitchell** [RasaHQ/rasa_nlu#670]
**Rasa NLU version** (e.g. `0.7.3`): 0.10.1

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...): spacy_sklearn

**Operating system** (windows, osx, ...): Windows 10

**Issue**:
Unable to train using Dialogflow export data. I downloaded the export zip from Dialogflow and extracted to data/vita . The contents look similar to:
https://github.com/RasaHQ/rasa_nlu/tree/master/data/examples/dialogflow
(no entities directory in mine but I tried creating an empty one, no difference). Have tried pointing the config data entry to both the agent.json file and the directory itself (as below)

Keep getting this error:

INFO:rasa_nlu.utils.spacy_utils:Trying to load spacy model with name 'en'
INFO:rasa_nlu.components:Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
INFO:rasa_nlu.converters:Training data format at ./data/vita is unk
Traceback (most recent call last):
  File "C:\Python\Python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python\Python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python\Python36-32\lib\site-packages\rasa_nlu\train.py", line 121, in <module>
    do_train(config)
  File "C:\Python\Python36-32\lib\site-packages\rasa_nlu\train.py", line 109, in do_train
    training_data = load_data(config['data'])
  File "C:\Python\Python36-32\lib\site-packages\rasa_nlu\converters.py", line 325, in load_data
    raise ValueError("unknown training file format : {} for file {}".format(fformat, resource_name))
ValueError: unknown training file format : unk for file ./data/vita

**Content of configuration file** (if used & relevant):
{
  "pipeline": "spacy_sklearn",
  "path" : "./projects",
  "data" : "./data/vita"
}

**Comment by thomas-mitchell** [comment]
Appears to be a Python compatibility issue. I installed everything on Python 2.7 instead of 3.6.3 and retried, import worked correctly.

Leaving open since I'm not sure if anyone will want to look into this.

**Comment by patlachance** [comment]
Same error here on latest rasa/rasa_nlu:latest-full docker image.
 
```
# python --version
Python 2.7.14
```

```
# cat config.json 
{
  "pipeline": "spacy_sklearn",
  "path" : "./models",
  "data" : "./data/intents"
}
```

```
# python -m rasa_nlu.train -c config.json 
INFO:rasa_nlu.utils.spacy_utils:Trying to load spacy model with name 'en'
INFO:rasa_nlu.components:Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
INFO:rasa_nlu.converters:Training data format at ./data/intents is unk
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/app/rasa_nlu/train.py", line 125, in <module>
    do_train(config)
  File "/app/rasa_nlu/train.py", line 113, in do_train
    training_data = load_data(config['data'], config['language'])
  File "rasa_nlu/converters.py", line 332, in load_data
    raise ValueError("unknown training file format : {} for file {}".format(fformat, resource_name))
ValueError: unknown training file format : unk for file ./data/intents
```

**Comment by tmbo** [comment]
I can not reproduce this even with 3.6 

I will close it until there is more information about how to reproduce this.
