### ISSUE TITLE
Swagger/OpenAPI spec for Rasa NLU instance

### ISSUE THREAD

**Issue by SteffenLuypaert** [RasaHQ/rasa_nlu#672]
Hello,

First of all thanks for the work you are doing on Rasa NLU.

I needed to write a Rasa client for the REST API today but I figured since it's a standard REST api it was actually better to create a Swagger/OpenAPI spec for it and generate a client based on that spec. 
I would now like to contribute the spec I wrote to the project since I believe it could be handy for other people as well - Swagger/OpenAPI is getting quite some adaption.

**Comment by wrathagom** [comment]
PR was closed so closing this as well.
