### ISSUE TITLE
Trainer fails on special characters

### ISSUE THREAD

**Issue by mhjb** [RasaHQ/rasa_nlu#674]
**Rasa NLU version**: 0.10.4

**Used backend / pipeline**: spacy_sklearn

**Operating system**: osx 10.12.6

**Issue**:
I'm attempting to train on some data exported from dialogflow.

`$ python -m rasa_nlu.train -c ./config_spacy.json` 
fails with messages like:
`UnicodeEncodeError: 'ascii' codec can't encode character u'\u201c' in position 32: ordinal not in range(128)`

It's easy enough to find and replace the special characters (in the above case, a left double quotation mark); but it would be nicer if the trainer could just handle them. 

**Content of configuration file** (if used & relevant):
```json
{
  "pipeline": "spacy_sklearn",
  "path" : "./projects",
  "data" : "./Wagbot-data/"
}
```

**Comment by wrathagom** [comment]
Can you provide a training data sample that would cause this to fail, it will be helpful for whomever jumps in to tackle it.

**Comment by mhjb** [comment]
Sure:

[Are schools allowed to have different uniforms for males and females_.json.txt](https://github.com/RasaHQ/rasa_nlu/files/1436273/Are.schools.allowed.to.have.different.uniforms.for.males.and.females_.json.txt)

**Comment by tmbo** [comment]
I couldn't reproduce this just now. 
- Which python version are you using?
- Can you please post the whole stacktrace of that exception?

**Comment by mhjb** [comment]
Mac being repaired right now; when it's back I'll respond properly

**Comment by wrathagom** [comment]
@mhjb stlil encountering this issue?
