### ISSUE TITLE
Processing pipeline is not being configured via the environment variable

### ISSUE THREAD

**Issue by jasonmattiace** [RasaHQ/rasa_nlu#677]
**Rasa NLU version** (e.g. `0.7.3`):
0.10.4-spacy

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...):
spacy

**Operating system** (windows, osx, ...):
linux and osx

**Issue**:
I am trying to configure the processing pipeline through the env var using the 0.10.4-spacy docker image but the configuration does not seem to change at all. I have tried `export RASA_PIPELINE='intent_classifier_keyword, nlp_spacy'`, `export RASA_PIPELINE='intent_classifier_keyword'` and `export RASA_PIPELINE=['intent_classifier_keyword']` and then restarted my docker container, but when i hit the /config endpoint i see "pipeline" : [ "nlp_spacy", "tokenizer_spacy", "intent_featurizer_spacy", "intent_entity_featurizer_regex", "ner_crf", "ner_synonyms", "intent_classifier_sklearn" ]

**Content of configuration file** (if used & relevant):
```json

```

**Comment by wrathagom** [comment]
How are you executing the above commands, are you connecting into the container?

Executing 
```
docker run -p5000:5000 -e RASA_PIPELINE='intent_classifier_keyword,nlp_spacy' rasa/rasa_nlu:latest-full
```

worked fine for me
```
{
	"aws_endpoint_url": null,
	"response_log": "/app/logs",
	"max_number_of_ngrams": 7,
	"cors_origins": [],
	"port": 5000,
	"log_level": "INFO",
	"mitie_file": "data/total_word_feature_extractor.dat",
	"duckling_dimensions": null,
	"spacy_model_name": null,
	"duckling_http_url": null,
	"config": "config.json",
	"emulate": null,
	"nlu_python_packages": "/usr/local/lib/python2.7/dist-packages",
	"path": "/app/./projects",
	"data": "./data/examples/rasa/demo-rasa.json",
	"num_threads": 1,
	"pipeline": [
		"intent_classifier_keyword",
		"nlp_spacy"
	],
	"language": "en",
	"max_training_processes": 1,
	"project": null,
	"token": null,
	"nlu_home": "/app",
	"nlu_docker": "YES",
	"fixed_model_name": null,
	"log_file": null
}
```

**Comment by jasonmattiace** [comment]
Ok yes that does work. I am new to Docker so I assumed the env vars were taken from the environment it was running in. I'll read up on the Docker docs more next time :)

**Comment by wrathagom** [comment]
no worries, glad I could help. I'm working on some better Docker docs, but not finding enough time to get through it :/

**Comment by tmbo** [comment]
I think there is another issue for the docs, so I'll close this one.
