### ISSUE TITLE
Random string shouldn't match with any intent.

### ISSUE THREAD

**Issue by shaileshpatel91** [RasaHQ/rasa_nlu#678]
Rasa NLU version (e.g. 0.7.3):
0.10.4-spacy

Used backend / pipeline (mitie, spacy_sklearn, ...):
spacy

Operating system (windows, osx, ...):
linux and osx

I was trying Rasa NLU for intent classification, it works well when trained with test data. If I ask something like " curl -XPOST localhost:5000/parse -d '{"q":"dsf dsf dfdf", "project":"heyzot"}' " i.e. is any random string which is not in test data it still matches it with some intents . With confidence as high as 0.52 ( I understand this high confidence is because of small test-data.) but isn't there a way that it shouldn't match anything and give a none result as its not even close to any of the entry in the training data ?

**Comment by PHLF** [comment]
A classifier's job is to classify, no matter how out of place the input data features' values are. So this issue is a little bit more complicated than it looks. See https://github.com/RasaHQ/rasa_nlu/issues/387 for more explanations.

**Comment by shaileshpatel91** [comment]
Thanks @PHLF for quick reply. I will refer  [#387](https://github.com/RasaHQ/rasa_nlu/issues/387) for update.
