### ISSUE TITLE
Make working with non-ascii characters easier

### ISSUE THREAD

**Issue by twerkmeister** [RasaHQ/rasa_nlu#683]
**Rasa NLU version** (e.g. `0.10.x`):

*General*
We should recommend usage of python3 for people working with non-ascii character sets. I have been fiddling for quite a while with python2 but couldn't get it to print Chinese Characters in unescaped form in log messages. On the other hand, this just works out of the box in python3. 

*Json.dumps*
`json.dumps` uses the parameter `ensure_ascii=True` by default (in both py2 and py3) and escapes any non-ascii characters (中文->\uXXXX\uXXXX). As a result, rasa sometimes converts strings into non-human-readable form. For example, when converting a Chinese training dataset from md to json format. I suggest we use `ensure_ascii=False` with `json.dumps` by default.

**Comment by tmbo** [comment]
Agreed, Please create a PR for the `json.dumps` change.
