### ISSUE TITLE
Entity Synonyms detection inconsistency

### ISSUE THREAD

**Issue by harigovind511** [RasaHQ/rasa_nlu#688]
**Backend: SkLearn + Spacy**

**Operating system: Windows**

**Issue: Entity synonyms detection is highly inconsistent**:

Hi All,
Me and my team have been using Rasa NLU as a replacement for MS LUIS for over 2 months now, and it has worked out pretty well for us so far. Now we have around 900 entries as **Entity Synonyms**(as we were using List entity in LUIS). 

And only for some utterances, the entity is detected as synonyms and for the majority of utterances, it is unable to detect Entity Synonyms. In order to detect synonyms, I have to create another simple entity which again we are manually training with all the synonym values, once the intents are trained with this simple Entity Rasa seems to detect entity for this intent as both simple and synonyms. 

And another quick question, Is the Entity Synonyms in Rasa designed to return only one matched entity(unlike LUIS which used to return all the matched entities values)?

Is there any alternative to list entity from LUIS here in Rasa?

**Comment by wrathagom** [comment]
Whoops, sorry I didn't see this here. I believe I answered this on SO [here](https://stackoverflow.com/questions/47299882/rasa-nluentity-synonyms-detection-inconsistency/47300608#47300608).

My doc update was already merged #690

**Comment by harigovind511** [comment]
Hey @wrathagom  sorry to disturb you again mate, I have an automated script which as you recommended is constructing the examples for me to add inside **common_examples**. So I have around 900 names and all I want is for them to be detected as custom **People** entity(in total it has some synonyms which makes it around 2000 entities). Even after training all of the entities Rasa is not able to detect all the names. Any suggestions as to how can I optimise the detection.

**Comment by wrathagom** [comment]
I think names are pretty hard. Can you use the pre-trained `ner_spacy` component? They've trained how to recognize names on a much larger dataset.
