### ISSUE TITLE
How to push training data to rasa nlu through a program?

### ISSUE THREAD

**Issue by chkiriti** [RasaHQ/rasa_nlu#692]
**Rasa NLU version** (e.g. `0.7.3`):

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...):

**Operating system** (windows, osx, ...):

**Issue**:

**Content of configuration file** (if used & relevant):
```json

```

I am using a MEAN web application which creates intents & entities that is pushed to api.ai through REST apis.  Now I want to replace api.ai completely with RASA NLU. 
Please help me how to push the training data to RASA NLU through my nodejs server ?
Let me know if I need to provide any further info?

**Comment by wrathagom** [comment]
Pretty confident I already answered this on SO [here](https://stackoverflow.com/questions/47313046/how-to-create-training-data-for-rasa-nlu-through-program-nodejs).

I wont repeat my answer, but I will link to the [HTTP docs](https://rasa-nlu.readthedocs.io/en/latest/http.html#), which already describe how to do this.
