### ISSUE TITLE
The correct way to use regex features

### ISSUE THREAD

**Issue by nabihach** [RasaHQ/rasa_nlu#693]
I am trying to figure out how to work with the regex features. Here is what my data examples look like:
```
 "common_examples": [
      {
        "text": "What is WSIB insurance?", 
        "intent": "FAQs_wsib", 
        "entities": []
      },   
      {
        "text": "Do you offer WSIB insurance", 
        "intent": "FAQs_wsib", 
        "entities": []
      },   
      {
        "text": "Do you offer WSIB?", 
        "intent": "FAQs_wsib", 
        "entities": []
      }
],
 "regex_features": [
      {
        "name": "wsib",
        "pattern": "\bwsib\b"
      },
      {
        "name": "WSIB",
        "pattern": "\bWSIB\b"
      }
]
```
Basically, whenever I see the word `wsib` or `WSIB` in a message, I want to classify its intent as `FAQs_wsib`. But with the above data, it never gets the intent right. Am I doing something wrong?

**Comment by tmbo** [comment]
What does you configuration look like?

(There is a reason there is an issue template. please also state the library version you are using as well as the python version.)

**Comment by wrathagom** [comment]
@nabihach were you able to figure this out? Closing from lack of activity, but I can re-open if you answer Tom's questions/request for more info.
