### ISSUE TITLE
Token used to work but not anymore

### ISSUE THREAD

**Issue by pranav-nadkarni** [RasaHQ/rasa_nlu#694]
**Rasa NLU version** 0.10.4:

**Operating system** : Ubuntu 16.04 LTS

**Issue**:
Token used to work in 0.9.3b but after installing Rasa_Core the Typing module changed and since then rasa_nlu stopped working giving error on ClassVar

So I upgraded the Rasa NLU to 0.10.4. The configuration is simple but when I use Token, and also pass it in URL it still gives me unauthorized output. 
Thus I had to remove token from the configuration file to make it work. is it a bug?
This seems no brainer but can't figure out why token is not working. Please help.

config file
{"pipeline":"spacy_sklearn","num_threads":4,"path":"./models", "token":"12345"}

```

**Comment by tmbo** [comment]
Which python version are you using? Can you please also provide an example request?

**Comment by pranav-nadkarni** [comment]
Hi, sorry for the delay as I was out of town without access to the Internet.

I am using Python 3.5
http://localhost:5000/status?token=12345

gives me unauthorized if I set token in above config file. This used to work earlier.

**Comment by tmbo** [comment]
@pranav-nadkarni - @twerkmeister just created a PR #698, do you mind trying if that works for ou?

**Comment by pranav-nadkarni** [comment]
will try, and let you know. thanks

**Comment by pranav-nadkarni** [comment]
Yes this PR is working correctly. Thanks a lot !

**Comment by pranav-nadkarni** [comment]
Thanks tmbo & twerkmeister.
