### ISSUE TITLE
Training not working in OSX High Sierra

### ISSUE THREAD

**Issue by edng** [RasaHQ/rasa_nlu#697]
**Rasa NLU version** (e.g. `0.7.3`): 0.10.4

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...): spacy_sklearn

**Operating system** (windows, osx, ...): OSX High Sierra

**Issue**:

Rasa NLU broke after upgraded OSX to High Sierra.  Got these messages when submitting a  training data set.

```
WARNING:rasa_nlu.project:Failed to list models of project ai. u'No persistent storage specified. Supported values are aws, gcs'
objc[29540]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[29540]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
```

The set up worked fine in OSX prior of upgrading to High Sierra.  It might be related to this issue http://www.sealiesoftware.com/blog/archive/2017/6/5/Objective-C_and_fork_in_macOS_1013.html.  Tried both installation via `pip` and latest and greatest from git, got the same results.  

Python version
```
Python 2.7.14 (default, Nov 16 2017, 22:12:45)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.38)] on darwin
```

**Content of configuration file** (if used & relevant):
```
{
  "pipeline": "spacy_sklearn",
  "path" : "./projects_spacy",
  "data" : "./testData.json"
}
```

**Comment by wrathagom** [comment]
I just tried this (running high Sierra as well) and couldn't re-produce. Do I read it right that you upgraded after having already installed everything?

If that is the case perhaps you should try with a fresh condo/venv environment and re-installing.

Were you trying to train via the command line or via the HTTP API?

**Comment by edng** [comment]
Yeah, I did try to reinstall all the modules fresh after upgrading to High Sierra.  I started the project as usual (prior of High Sierra upgrade), no existing trained model yet.
```
$ python -m rasa_nlu.server -c conf/config_spacy.json
INFO:rasa_nlu.data_router:Logging requests to '....logs/rasa_nlu_log-20171119-102330-93444.log'.
WARNING:rasa_nlu.project:Failed to list models of project None. u'No persistent storage specified. Supported values are aws, gcs'
INFO:__main__:Started http server on port 5000
2017-11-19 10:23:30-0500 [-] Log opened.
2017-11-19 10:23:30-0500 [-] Site starting on 5000
2017-11-19 10:23:30-0500 [-] Starting factory <twisted.web.server.Site instance at 0x1035a2dd0>
WARNING:rasa_nlu.project:Failed to list models of project ai. u'No persistent storage specified. Supported values are aws, gcs'
objc[93519]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[93519]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
```
Got the above error as soon as I submit a training data set.  I also got an alert prompt that said `Python quit unexpectedly`.  The logs in logs directory are empty.
```
curl -XPOST localhost:5000/train?project=ai -d @training_set/trainingData.json
```

**Comment by wrathagom** [comment]
Did the OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES environment variable suggested in the article you linked work for you?

**Comment by edng** [comment]
Tried it, this workaround didn't work for me.  Got the same result.

**Comment by wrathagom** [comment]
what about falling back to 2.7.10 or 2.7.13?

**Comment by edng** [comment]
Just tried reverting back to 2.7.10.  Same results, with and without environment variable `OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES`. :(

**Comment by XBeg9** [comment]
Same here, any updates?

**Comment by XBeg9** [comment]
`OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES make run-nlu` works for me!

**Comment by edng** [comment]
I couldn't make it work at all in High Sierra.  I moved the project onto another machine with Sierra, guess I'm not upgrading this machine to High Sierra for a while.

**Comment by XBeg9** [comment]
@edng I recommend you to use Docker.
