### ISSUE TITLE
How does conflicting entities are handled in pipeline?

### ISSUE THREAD

**Issue by shgidi** [RasaHQ/rasa_nlu#700]
I'm wondering how does conflicting eintities, found by differnt components are handeled.
e.g, in the sentence: "I'm going to see King David" component A can tag "King David" as a person, and component B may tag it as a place. What will be the final verseict in the output? will they both be presented?
If I'll add my own components to the pipeline, will the logic stay the same?

**Comment by tmbo** [comment]
Yes, they will both be present. Currently, there is no conflict resolution - you will get all entities that are extracted by any component.

**Comment by tmbo** [comment]
And yes, will be the same for a component you add to the pipeline (if you use the same code to add entities to the output - you can also overwrite entities that component previous to yours in the pipeline have added, it is up to you. but all current entity component implementation append their entities to the existing ones).
