### ISSUE TITLE
Keep rasa server on

### ISSUE THREAD

**Issue by roysoham** [RasaHQ/rasa_nlu#701]
**Rasa NLU version** (`0.7.3`):

**Used backend / pipeline** (`spacy`):

**Operating system** (ubuntu 16.04):

**Issue**:
How to keep rasa server on ?
I need to keep the rasa server on, the moment I log out from my terminal (ubuntu) it closes down.

If I want to create a cron job what should be the parameter (python /??)

Thanks

**Content of configuration file** (if used & relevant):
```json

```

**Comment by wrathagom** [comment]
I'd recommend using docker, but if you need an alternate solution try this SO thread https://stackoverflow.com/questions/24518522/run-python-script-at-startup-in-ubuntu
