### ISSUE TITLE
How to check if everything is correctly installed

### ISSUE THREAD

**Issue by SeyoS** [RasaHQ/rasa_nlu#703]
**Rasa NLU version** (e.g. `0.7.3`): 0.10.4
**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...): spacy_sklearn

**Operating system** (windows, osx, ...): windows server

**Issue**:
I'm going through the basic tutorial (https://nlu.rasa.ai/) but results from the first query (I am looking for chinese food) are different from the example and it don't extract entities. Moreover, even if I try to ask exactly a query like 'Hey', and even if it is present in the demo data set, confidence drops to 0.48.

So, is there a way to check that everything is correctly installed ?

**Comment by wrathagom** [comment]
See the note in this section: https://nlu.rasa.ai/#the-quickest-quickstart-in-the-west

> This demo uses a very limited ML model. To apply rasa NLU to your use case, you need to train your own model! Follow the tutorial to get to know how to apply rasa_nlu to your data.

You're training a machine learning model, it requires enough examples to learn on. The tutorial doesn't quite provide enough to get optimum results.
