### ISSUE TITLE
MITIE confidence score > 1

### ISSUE THREAD

**Issue by snktagarwal** [RasaHQ/rasa_nlu#704]
**Rasa NLU version** (e.g. `0.7.3`):

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...):
mitie

**Operating system** (windows, osx, ...):
osx

**Issue**:
confidence scores > 1

Eg:
`curl -XPOST localhost:5000/parse -d '{"q":"the physical exam is normal", "project": "macro_mitie", "model": "model_20171121-151643"}' | python -mjson.tool
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   227    0   132  100    95  18443  13273 --:--:-- --:--:-- --:--:-- 18857
{
    "entities": [],
    "intent": {
        "confidence": 1.1994423720427168,
        "name": "MACRO_PHYSICAL_EXAM"
    },
    "text": "the physical exam is normal"
}`

Is this possible? And if yes, how to make sense out of the confidence scores?

**Comment by PricelessRabbit** [comment]
yes it's possible. check out https://nlu.rasa.ai/tutorial.html:

> rasa NLU will also print a confidence value for the intent classification. For models using spacy intent classification this will be a probability. For MITIE models this is just a score, which might be greater than 1.

**Comment by snktagarwal** [comment]
Thanks for the cross check. The bigger question is where do I learn more
about it? Having a high "confidence" is okay. But what's the normalizing
factor here? How do I make sense of these values?

**Comment by tmbo** [comment]
If you want to know more details - there is unfortunately not a lot of documentation for mitie so you'd need to search through the source code of either https://github.com/mit-nlp/MITIE or https://github.com/davisking/dlib
