### ISSUE TITLE
Add spacy Chinese model

### ISSUE THREAD

**Issue by 731935354** [RasaHQ/rasa_nlu#705]
**Rasa NLU version**: 0.10.4

**Used backend** : spacy

**Pipeline(expected)**: ["nlp_spacy", "tokenizer_spacy(for Chinese)", “intent_entity_featurizer_regex”, 
“intent_featurizer_spacy”, “ner_crf”, “ner_synonyms”, “intent_classifier_sklearn”]

**Operating system** : win7

**Python**: 3.6.3

Recently I try to add a spacy Chinese model for rasa_nlu. According to the instruction [here](https://rasahq.github.io/rasa_nlu/languages.html), I need to add tokenizer and vocabulary for spacy.

So far I have successfully 
- Add Chinese tokenizer for spacy and pass the test.
- Generate a "sample" vocab including words and vectors(randomly generated, range: [-1,1], dim:300),
and output the vocab by "vocab.to_disk()", including "_key2row_", "_lexemes.bin_", "_strings.json_", "_vectors_", same structure as "_en_core_web_sm-2.0.0/vocab_"

However, I just don't know what to do next. Some questions:
- I notice that both "ner_crf" and "intent_featurizer_spacy" component require "spacy_doc", but "spacy_doc" may contain more than words, such as "entity" and "pos" annotations. So what exactly
do "ner_crf" and "intent_featurizer_spacy" require?
- Are "ner“，”parser", "tagger" in spacy's language model necessary for rasa_nlu?
- How can I generate a minimum spacy's model for rasa? What should be included in it? 

I am new to rasa and spacy, so my understanding may be a bit wrong. Any correctness or suggestion will be appreciated!

**Comment by 731935354** [comment]
After trying one more day, I finally generate a "sample" Chinese model which only contains vocab and tokenizer. And I succeed in using my generated model in rasa. I plan to study the component in the pipeline ["nlp_spacy", "tokenizer_spacy(for Chinese)", “intent_entity_featurizer_regex”,
“intent_featurizer_spacy”, “ner_crf”, “ner_synonyms”, “intent_classifier_sklearn”] one by one next step.

**Comment by kuriakinzeng** [comment]
Could you submit a PR for your model?

**Comment by 731935354** [comment]
@kuriakinzeng 
Really appreciate your attention.
Here is the complete construction process in Chinese. http://zhurongxin.site/2017/11/25/nlp_1_build_chinese_spacy_model_for_rasa/

According to Confidentiality agreement, I couldn't share my full Chinese model. Maybe you can build your own model following the steps in my blog.

If you prefer English or have trouble visiting the website above(DNS by Alibaba Cloud Computing, China) , just let me know.
