### ISSUE TITLE
How to improve intent classification?

### ISSUE THREAD

**Issue by pranav-nadkarni** [RasaHQ/rasa_nlu#708]
OS: Ubuntu 16.04LTS 64bit
Rasa: 0.10.4

**Issue**:
created a project with 16 intents each having 20+ expressions (common_examples/use cases)
This NLP output is not accurate as 0.9.3b
What am I doing wrong? Shall I reduce cases? I am using Spacy_sklearn. No regex or synonyms as of yet. Please help me correct it. Attaching data & config files.

Thanks
Pranav
[psn_rasa_10-4.zip](https://github.com/RasaHQ/rasa_nlu/files/1508726/psn_rasa_10-4.zip)

**Comment by wrathagom** [comment]
I've trained your data, but can you provide some specific examples of parse requests that came back "way off"? For the most part everything seems to be working well for me.

Also, how are you training, via cli or http?

**Comment by wrathagom** [comment]
@pranav-nadkarni if this is still an issue can you try the evaluate.py script that was added to test your training data.

Re-Open if you haven't overcome this problem.
