### ISSUE TITLE
How to train rasa using https

### ISSUE THREAD

**Issue by BhargavJanardhan** [RasaHQ/rasa_nlu#710]
Hey Folks,

I am facing an issue with Rasa training with https. 
Below is the issue. Please help me out with it.

**ISSUE:** Could train using http where I couldn't do with https.
**ERROR:** **Timing client out IPV4 Address TCP 182.158.31.58**
**Rasa Version: ** 0.10.0a6
**Trails:** 
     **Worked:** 
          * I am able to train the json by using python command and its generating the model.
          * I am able to train the json using ajax call i.e; using **http://fcvtx1:5000/train?project=People**
     **Not Worked:** 
         * When i try to trigger with https i.e; **https://fcvtx1:5000/train?project=People** its throwing an error time out.
        * When I try to browse the url without http am getting the response "hello from rasa" as in screenshot, but when I try to browse with https am getting error "Timing out client" in console as you can find it in screenshot.
![image](https://user-images.githubusercontent.com/27334482/33335474-28b0fc06-d493-11e7-8eba-84d5ca05d019.png)
     * I installed ssl certificate and am still I am facing the issue.

Thanks in Advance :)

**Comment by wrathagom** [comment]
Rasa doesn't have the components in place to do SSL without some development work. Probably your quickest path is to place Rasa behind an Nginx reverse proxy with SSL enabled in Nginx.

**Comment by wrathagom** [comment]
I still believe the easiest path forward is placing Rasa NLU server behind an Nginx reverse proxy. Where Nginx handles the SSL and then proxies to rasa over HTTP (locally).

But if you want a different solution here is the starting point. I haven't used it this way so I have no idea what is involved.

http://klein.readthedocs.io/en/latest/introduction/2-twistdtap.html#using-https-via-the-twistd-web-plugin

**Comment by tmbo** [comment]
If you get a 500, there should be an error logged in the log of the application, mind sharing that?

**Comment by BhargavJanardhan** [comment]
Guys,

Nginx works and the issue of https with ajax is coz of 
1. Rasa was corrupted
2. Removed contentType:'application/json' and no-cache header from ajax.

It works now. Thank you all :)

**Comment by Akshit99** [comment]
> I still believe the easiest path forward is placing Rasa NLU server behind an Nginx reverse proxy. Where Nginx handles the SSL and then proxies to rasa over HTTP (locally).
> 
> But if you want a different solution here is the starting point. I haven't used it this way so I have no idea what is involved.
> 
> http://klein.readthedocs.io/en/latest/introduction/2-twistdtap.html#using-https-via-the-twistd-web-plugin

hey! I see that you are saying to put RASA behind a Nginx reverse proxy! I'm not sure how to do it. I have a bot on AWS server and made the IP static. Then I installed apache and setup the SSL for ports. But my bot doesn't respond on that port because it's giving a HTTP request. As you said I need to put core behind a Nginx server. Can you please provide steps on how can i achieve that? Please provide me some steps on how to do it? I need to pass request from an https server to my rasa server!
