### ISSUE TITLE
Rasa Training with HTTPS end point

### ISSUE THREAD

**Issue by RachaRatan** [RasaHQ/rasa_nlu#712]
**Rasa NLU version** (e.g. `0.7.3`):'0.10.0a6'

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...):["nlp_spacy", "tokenizer_spacy","intent_featurizer_spacy","ner_synonyms","ner_crf","intent_classifier_sklearn","ner_spacy"],

**Operating system** (windows, osx, ...):WIndows srever 2008r2

**Issue**:
I have installed Rasa in one server. And I am trying to train the Rasa from one of my other application which is hosted in other server.
The application I am using is hosted in IIS with HTTPS url not with HTTP.
Now am trying to train Rasa using HTTP end point fron that application but as my application is having HTTPS url Rasa is not able to train with HTTP end.
I have tried to use HTTPS to train Rasa instead of HTTP but still it is not working.
Will this not work when I try to train from HTTTPS application or is there any way to overcome this issue.
Please help me on this.

**Content of configuration file** (if used & relevant):
```json
{
  
	"project":"People",
	"pipeline" : ["nlp_spacy", "tokenizer_spacy","intent_featurizer_spacy","ner_synonyms","ner_crf","intent_classifier_sklearn","ner_spacy"],
	"path" : "./projects",

	"cors_origins":["*"],
	"data" : "./data/examples/rasa/AbbiecassV2.json"

}

```

**Comment by tmbo** [comment]
What is the issue you are seeing? E.g. is there any response? 

That said, this doesn't look like an issue of rasa nlu but rather like a configuration issue. I am not sure how IIS works as I have not used it, but usually the proxy handles the https connection and the application is called using http.

**Comment by wrathagom** [comment]
IIS can do a URL re-write, I have no experience with IIS, but this is similar to the Nginx reverse proxy.

https://weblogs.asp.net/owscott/creating-a-reverse-proxy-with-url-rewrite-for-iis

Also note the SSL offloading.
