### ISSUE TITLE
Variables in Rasa

### ISSUE THREAD

**Issue by varshini-prasanna** [RasaHQ/rasa_nlu#715]
templates:
  utter_greeting:
  - text: "Hey, {name}. How are you?"
 this is my template containing a variable 'name'. How do i get the value of 'name' from the user,so that it displays " Hey, xyz(the name entered).How are you?"

**Comment by wrathagom** [comment]
This looks like a Rasa Core issue, not NLU. Can you re-create [here](https://github.com/RasaHQ/rasa_core).
