### ISSUE TITLE
valueerror : unknown training file format: unk for file ./data/demo_nlu.json

### ISSUE THREAD

**Issue by shreyas1990** [RasaHQ/rasa_nlu#716]
Rasa NLU version: 0.10
Python version: 2.7.6

Training was working fine until i updated my interpreter (demo_nlu.json). Started throwing this error after the update.

**Comment by tmbo** [comment]
From which version did you upgrade?

Do you mind attaching the file as well as mentioning the command you are running? We need to reproduce this.

**Comment by shreyas1990** [comment]
i updated the file i have attached 
[demo_nlu.txt](https://github.com/RasaHQ/rasa_nlu/files/1541406/demo_nlu.txt)

the command i was trying to run was 
python -m rasa_nlu.train -c nlu_model_config.json --fixed_model_name current

it doesn't seem to recognize the demo_nlu.json as a valid file format

**Comment by tmbo** [comment]
Please use, e.g. https://jsonlint.com/ to validate your file - there are syntax errors in there which leads to Rasa NLU being unable to load the file.
