### ISSUE TITLE
No module named converters

### ISSUE THREAD

**Issue by deep150** [RasaHQ/rasa_nlu#720]
**Rasa NLU version** (e.g. `0.7.3`): 0.10.4

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...):  spacy_sklearn

**Operating system** (windows, osx, ...): linux

**Issue**:  Traceback (most recent call last):
  File "train.py", line 1, in <module>
    from rasa_nlu.converters import load_data
ImportError: No module named converters

getting this error while importing rasa_nlu.converters

**Comment by tmbo** [comment]
How did you install Rasa NLU?

What command did you run that produced the error?

**Comment by wrathagom** [comment]
@deep150 closing since there wasn't a response. If you want help please answer @tmbo's questions and we will re-open.

**Comment by chenk17** [comment]
I have the same modulenNotFoundError! Im using the Introduction form the docs.
It only cannot load the converter module. Everything else is found.

Installation:

git clone https://github.com/RasaHQ/rasa_nlu.git
cd rasa_nlu
pip install -r requirements.txt
pip install -e .


nd then spacy a backend. 

Training with 

$ python -m rasa_nlu.train -c sample_configs/config_spacy.json

works. But I want to run the example via python as here:

https://nlu.rasa.ai/python.html

**Comment by tmbo** [comment]
If you are using the code from the master branch, you also need to use the documentation for that branch, so http://nlu.rasa.ai/master/python.html

**Comment by chenk17** [comment]
That makes sense! ;-) Thank you!

**Comment by Brijeshlakkad** [comment]
I have upgraded to version 11.5 and problem solved:

pip install rasa-nlu==0.11.5

**Comment by thethinkingmonks** [comment]
Thank you I also switch to 11.5 and it solved the issue.

**Comment by nuronics** [comment]
what is the alternative of load_data in rasa 0.13

**Comment by darkmanAmazigh** [comment]
i use rasa-nlu 0.13 and i have this error,
how it possible to install this module ?

**Comment by ihtisham0331** [comment]
> How did you install Rasa NLU?
> 
> What command did you run that produced the error?

I use the command following command to install rasa nlu 
pip install rasa-nlu
and showing same error

**Comment by ihtisham0331** [comment]
> I have upgraded to version 11.5 and problem solved:
> 
> pip install rasa-nlu==0.11.5

I installed it but not showing result of training

**Comment by tmbo** [comment]
this is a closed issue. please open new issues with your problem description.
