### ISSUE TITLE
Confidence 0.0

### ISSUE THREAD

**Issue by fofiedelly** [RasaHQ/rasa_nlu#725]
**Issue**:
I've followed the tutorial and its works very fine with the total_word_feature_extractor. 
I wanted to do exactly the same for the following use-case: **A user enters a text and the intent should say if the user is searching for a person!**

But unfortunately for every request even with exactly the same text as in the example i alway get the  same result:

```
{
    "entities": [],
    "intent": {
        "confidence": 0.0,
        "name": "person"
    },
    "text": "which persons create cds"
}
```

**Content of configuration file** (if used & relevant):
```json
{
  "rasa_nlu_data": {
       "entity_synonyms": [
      {
        "value": "who",
        "synonyms": ["which persons", "which person"]
      },
      {
        "value": "cto",
        "synonyms": ["cio", "ceo", "cfo"]
      }
    ],
    "common_examples": [
      {
        "text": "who is delly fofie",
        "intent": "person",
        "entities": []
      },
      {
        "text": "who works on sap hana",
        "intent": "person",
        "entities": []
      },
      {
        "text": "organization of delly fofie",
        "intent": "person",
        "entities": []
      },
      {
        "text": "who is working with sap hana",
        "intent": "person",
        "entities": []
      },
      {
        "text": "which persons create cds",
        "intent": "person",
        "entities": []
      },
      {
        "text": "who can fix my machine",
        "intent": "person",
        "entities": []
      },
      {
        "text": "cto",
        "intent": "person",
        "entities": []
      },
      {
        "text": "who is the cto",
        "intent": "person",
        "entities": []
      },
      {
        "text": "who created the car?",
        "intent": "person",
        "entities": []
      },
      {
        "text": "for who works matthias",
        "intent": "person",
        "entities": []
      },
      {
        "text": "for who does matthias works ",
        "intent": "person",
        "entities": []
      }
    ]
  }
}
```

**Comment by tmbo** [comment]
This might indicate that you are not using the model you trained, but the default model.

**Comment by fofiedelly** [comment]
Thanks @tmbo Yes you are certainly right. I'm using the default model. It's certainly the reason why it's not working. 
I will investigate how to build my own model. Are there some links/references regarding this ? 
btw yes i'm running the server.
Cheers.

**Comment by wrathagom** [comment]
I'm really confused. the second snippet above is your training data not your config file.

And then in that training data you only have one intent defined and no entities. Can you give an example of the expected output? Please see the documentation on training data formats [here](https://rasahq.github.io/rasa_nlu/master/dataformat.html#common-examples).

Keep in mind that defining entity synonyms is not the same as training entities in common_examples. See the note in the docs referring to entity synonyms:

> Please note that adding synonyms using the above format does not improve the model’s classification of those entities. Entities must be properly classified before they can be replaced with the synonym value.

**Comment by tmbo** [comment]
I'll close this for now - please comment if this is still an issue for you.
