### ISSUE TITLE
Docs: section about server_model_dirs is irrelevant in persistence documentation

### ISSUE THREAD

**Issue by sfranchois** [RasaHQ/rasa_nlu#730]
**Rasa NLU version** (e.g. `0.7.3`): 0.10.5

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...): n/a

**Operating system** (windows, osx, ...): n/a

**Issue**:
https://nlu.rasa.ai/0.10.5/persist.html
Last paragraph about 'server_model_dirs' is inaccurate/irrelevant. 
Don't think it is even used in the code.

**Content of configuration file** (if used & relevant):
```json

```

**Comment by wrathagom** [comment]
Care to open a PR? If not then hopefully someone else can.

**Comment by sfranchois** [comment]
Hi

Fyi a PR was submitted for this.


Serge Franchois
Data Engineering

 <http://www.foodpairing.com/>
T +32 9277 7771  |  cfi.foodpairing.com <http://cfi.foodpairing.com/>

**Comment by tmbo** [comment]
PR has been merged.
