### ISSUE TITLE
How to export trained model to be used by javascript

### ISSUE THREAD

**Issue by rodrigopivi** [RasaHQ/rasa_nlu#734]
Is there  a way to reuse a trained model form other environments? or how much work would it take to be able to reuse a trained model from javascript, as is done by tensorfire?

**Comment by wrathagom** [comment]
Looks like there are ways https://github.com/nok/sklearn-porter to port pieces of it to JS.

Though I am not certain I see an advantage of that vs running the Rasa NLU server and interacting with it via HTTP from javascript. Keep in mind that the full Rasa solution is a pipeline so each individual piece would have to be ported or similar solutions implemented from the featurizer, entity model, intent model, etc.

**Comment by rodrigopivi** [comment]
Well i would like the ability to run a trained model offline and on the browser, i would like to start working on an example of this but maybe you can point me to some of te steps required to run a Rasa trained model once i port the estimator to a JS compatible format?

**Comment by wrathagom** [comment]
If you can successfully port it you wont need help running it. What is the use case for needing to run serverless? Would it not be possible to run run the server locally?

**Comment by tmbo** [comment]
This is a non trivial task. From the top of my head there are a number of things that need to be done:
- read in the spacy (or mitie) word vector model in JS (making sure the correct vectors are assigned to words)
- dumping the machine learning models of the classifiers
- recreating any processing logic any of the components in your pipeline does (e.g. the CRF entitiy classifier is doing quite some work, so you need to do that in JS as well - just loading the model of the Conditional Random Field won't be enough).

I will close this issue as this will not be part of the project in the foreseeable future.
