### ISSUE TITLE
wrong entity detection

### ISSUE THREAD

**Issue by huqingzhou** [RasaHQ/rasa_nlu#735]
#./data/nlu.md

## intent:greet
- hey
- hello
- hi
- hello there
- good morning
- good evening

## intent:goodbye
- [bye](entity1)
- [goodbye](entity2)
- have a nice day
- see you around
- bye bye
- see you later

#config.json
{
  "pipeline": "spacy_sklearn",
  "path" : "./models",
  "project": "nlu",
  "data" : "./data/nlu.md"
}

#training
python -m rasa_nlu.train -c config.json --fixed_model_name current1

#server
python -m rasa_nlu.server -c config.json

#test
$ curl -s  -XPOST 10.225.17.100:5000/parse -d '{"q":"thank you very much",  "project": "nlu", "model": "current1"}' | jq .
{
  "entities": [
    {
      "start": 0,
      "extractor": "ner_crf",
      "end": 5,
      "value": "thank",
      "entity": "entity1"    ===================> wrong
    },
    {
      "start": 6,
      "extractor": "ner_crf",
      "end": 9,
      "value": "you",
      "entity": "entity1"  ===================> wrong
    },
    {
      "start": 10,
      "extractor": "ner_crf",
      "end": 14,
      "value": "very",
      "entity": "entity1"
    },
    {
      "start": 15,
      "extractor": "ner_crf",
      "end": 19,
      "value": "much",
      "entity": "entity1"  ===================> wrong
    }
  ],
  "intent": {
    "confidence": 0.7133572451492164,
    "name": "goodbye"
  },
  "text": "thank you very much",
  "intent_ranking": [
    {
      "confidence": 0.7133572451492164,
      "name": "goodbye"
    },
    {
      "confidence": 0.2866427548507836,
      "name": "greet"
    }
  ]
}

**Comment by huqingzhou** [comment]
$ python -c "import rasa_nlu; print(rasa_nlu.__version__);"
0.10.5
$ pip show spacy
Name: spacy
Version: 2.0.5

**Comment by parthsharma1996** [comment]
Maybe it is because of the very small dataset? 1 example per entity might be too low a number to produce any results at all, maybe. Have you tried increasing the number of examples for entities ?

**Comment by wrathagom** [comment]
Why use the entities at all? Do you need more than hello and goodbye intents? Eitherway @parthsharma1996 is right and you need to increase your training data size.

I'm going to close, but post back here if a larger dataset doesn't improve performance.

**Comment by huqingzhou** [comment]
[nlu.md.txt](https://github.com/RasaHQ/rasa_nlu/files/1581285/nlu.md.txt)

**Comment by huqingzhou** [comment]
## intent:thankyou
- thank you very much !
- that is helpful !

## intent:continue_inform
- how about [item5](item) and [s3](service)
- how about [item3](item) and [s2](service)
- how about [item2](item) and [s2](service)
- how about [item4](item) and [s2](service)
- how about [item5](item) and [s2](service)
- how about [item1](item) and [s4](service)
- how about [item4](item) and [s4](service)
- how about [item7](item) and [s2](service)
- how about [item7](item)
- how about [item1](item)
- how about [item1](item) and [s3](service)
- how about [item3](item) and [s1](service)
- how about [item5](item) and [s1](service)
- how about [item7](item) and [s1](service)
- how about [item7](item) and [s3](service)
- how about [item5](item)
- how about [item4](item) and [s3](service)
- how about [item3](item) and [s4](service)
- how about [item8](item) and [s4](service)
- how about [item6](item) and [s2](service)
- how about [item6](item) and [s1](service)
- how about [item2](item) and [s4](service)
- how about [item1](item) and [s2](service)
- how about [item5](item) and [s4](service)
- how about [item8](item) and [s2](service)
- how about [item3](item) and [s3](service)
- how about [item2](item) and [s3](service)
- how about [item2](item)
- how about [s3](service)
- how about [s4](service)
- how about [item4](item)
- how about [item6](item)
- how about [item4](item) and [s1](service)
- how about [item3](item)
- how about [s2](service)
- how about [item6](item) and [s4](service)
- how about [item7](item) and [s4](service)
- how about [item8](item) and [s1](service)
- how about [item8](item) and [s3](service)
- how about [item8](item)
- how about [item6](item) and [s3](service)
- how about [item2](item) and [s1](service)
- how about [s1](service)
- how about [item1](item) and [s1](service)

## intent:query
- please show service [s4](service)
- check service [s2](service) [item6](item)
- please show service [s1](service) [item1](item)
- please show service [s1](service) [item8](item)
- please show service [s2](service) [item6](item)
- please show service [s4](service) [item4](item)
- check service [s3](service) [item8](item)
- check service [s4](service) [item8](item)
- please show service [item3](item)
- please show service [s2](service) [item3](item)
- please show service [s3](service) [item5](item)
- check service [s1](service) [item8](item)
- check service [s1](service) [item7](item)
- check service [item8](item)
- check service [s1](service) [item5](item)
- check service [s1](service) [item4](item)
- check service [s2](service) [item2](item)
- please show service [s2](service) [item4](item)
- please show service [item4](item)
- check service [item5](item)
- please show service [s1](service) [item6](item)
- check service [s1](service) [item1](item)
- query
- please show service [s3](service) [item6](item)
- check service [item2](item)
- please show service [item6](item)
- check service [s3](service) [item7](item)
- please show service [s2](service) [item2](item)
- check service [s4](service) [item6](item)
- check service [item6](item)
- check service [s4](service)
- please show service [s4](service) [item7](item)
- check service [s4](service) [item5](item)
- please show service [s1](service) [item2](item)
- please show service [item1](item)
- check service [s1](service)
- please show service [s3](service) [item7](item)
- check service [s3](service) [item5](item)
- please show service [s2](service) [item7](item)
- check service [item1](item)
- check service [s2](service) [item1](item)
- please show service [s3](service)
- please query
- please show service [s1](service)
- check service [s4](service) [item3](item)
- check service [s2](service) [item8](item)
- please show service [s3](service) [item8](item)
- check service [s3](service) [item2](item)
- please show service [s2](service) [item8](item)
- check service [s1](service) [item2](item)
- please show service [s4](service) [item3](item)
- please show service [s2](service) [item1](item)
- check service [s4](service) [item1](item)
- check service [s2](service) [item4](item)
- check service [s3](service) [item1](item)
- check service [s2](service)
- check service [s3](service) [item6](item)
- check service [s4](service) [item2](item)
- check service [item4](item)
- please show service [s3](service) [item2](item)
- check service [s2](service) [item5](item)
- check service [s1](service) [item3](item)
- check service [s1](service) [item6](item)
- please show service [s2](service)
- please show service [s1](service) [item3](item)
- please show service [s1](service) [item7](item)
- please show service [s4](service) [item5](item)
- check service [s2](service) [item3](item)
- please show service [s4](service) [item1](item)
- please show service [s3](service) [item1](item)
- check service [s4](service) [item4](item)
- check service [s3](service)
- please show service [s4](service) [item8](item)
- please show service [s3](service) [item4](item)
- check service [s3](service) [item3](item)
- check service [s2](service) [item7](item)
- check service [item3](item)
- please show service [item5](item)
- please show service [item7](item)
- please show service [s1](service) [item4](item)
- please show service [s2](service) [item5](item)
- please show service [s1](service) [item5](item)
- please show service [item8](item)
- please show service [s4](service) [item6](item)
- please show service [s4](service) [item2](item)
- check service [s4](service) [item7](item)
- check service [item7](item)
- please show service [s3](service) [item3](item)
- please show service [item2](item)
- check service [s3](service) [item4](item)

## intent:greet
- hi bot
- hello
- hello bot
- Hey there, bot

## intent:inform
- [item2](item)
- [item5](item)
- [s3](service)
- [s1](service)
- [s2](service)
- [item6](item)
- [item8](item)
- [item3](item)
- [s4](service)
- [item7](item)
- [item4](item)
- [item1](item)

**Comment by huqingzhou** [comment]
@parthsharma1996  @wrathagom   thanks for your reply.

**Comment by huqingzhou** [comment]
after i added more training data.
still can not parse  'Thank you very much' right.

**Comment by huqingzhou** [comment]
$ curl -s  -XPOST 127.0.0.1:5000/parse -d '{"q":"thank you very much",  "project": "nlu", "model": "current"}' | jq .
{
  "entities": [
    {
      "start": 10,
      "extractor": "ner_crf",
      "end": 14,
      "value": "very",
      "entity": "service"
    },
    {
      "start": 15,
      "extractor": "ner_crf",
      "end": 19,
      "value": "much",
      "entity": "item"
    }
  ],
  "intent": {
    "confidence": 0.6803716574426739,
    "name": "thankyou"
  },
  "text": "thank you very much",
  "intent_ranking": [
    {
      "confidence": 0.6803716574426739,
      "name": "thankyou"
    },
    {
      "confidence": 0.1765147169998018,
      "name": "greet"
    },
    {
      "confidence": 0.06148735605846666,
      "name": "continue_inform"
    },
    {
      "confidence": 0.05053404378794035,
      "name": "query"
    },
    {
      "confidence": 0.03109222571111734,
      "name": "inform"
    }
  ]
}
