### ISSUE TITLE
Using Rasa for Address parsing

### ISSUE THREAD

**Issue by KeerthanaChowdary** [RasaHQ/rasa_nlu#736]
Can we use RASA NLU for breaking down address (which ever way it is written) into separate entities like apartment name, street name, zip code etc? Honestly is RASA the best tool for this (considering the word vectors won't be of much use when we have all nouns in the text (address))?

**Comment by wrathagom** [comment]
I would think it is possible, but even if you succeeded at parsing you wouldn't know if it is a valid address or not without some sort of other lookup based tool. I think another approach would be to just detect complete addresses. and then pass the "address" entity to a lookup based tool.

**Comment by amn41** [comment]
Some libraries you can look into for this:

https://github.com/openeventdata/mordecai

https://github.com/openvenues/pypostal

**Comment by KeerthanaChowdary** [comment]
@wrathagom Hi, that's good advice. Infact, that is the way I chose. I am letting rasa detect entities like house number, building name, street and zip. Though rasa is doing a good job, I am afraid it is not the tailor-made tool here. I think this because rasa uses word vectors and word embeddings to learn the context, and addresses have no context; since they are all proper nouns. I am thinking if a traditional look-up searching each and every word would work better (faster) ? Let me know your thoughts on this.

**Comment by tmbo** [comment]
With lookup you mean checking if the messages contains, e.g. a street name from a list of street names?

**Comment by KeerthanaChowdary** [comment]
Yes, something similar.

**Comment by wrathagom** [comment]
similar to #773 

Seems like original request has been filled, so closing in favor of other discussions.
