### ISSUE TITLE
Does rasa use any word embeddings internally ?

### ISSUE THREAD

**Issue by vivekaditya** [RasaHQ/rasa_nlu#740]
Does rasa use any word embeddings internally ( like word2vec or glove ) ?

**Comment by wrathagom** [comment]
Rasa uses either [spaCy](https://legacy.spacy.io/docs/) or [MITIE](https://github.com/mit-nlp/MITIE) as a backend for much of the NLP tasks. Both of which use word embeddings. You'll find better answer to how each of those two tools work in their own documentation.
