### ISSUE TITLE
Multiple intent classifier

### ISSUE THREAD

**Issue by anwesh44** [RasaHQ/rasa_nlu#742]
**Rasa NLU version** (e.g. `0.7.3`):
0.10.5

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...):
spacy_sklearn

**Operating system** (windows, osx, ...):
osx

**Issue**:
Does Rasa NLU support a classifier for classifying multiple intents in the same sentence?

**Content of configuration file** (if used & relevant):
```json

```

**Comment by wrathagom** [comment]
No Rasa can't, see #374 for more discussion.
