### ISSUE TITLE
Names of models in the form of absolute paths

### ISSUE THREAD

**Issue by wormuz** [RasaHQ/rasa_nlu#744]
Rasa-Nlu: 0.10.5

Issue: Hello! At the moment current list of model names is formed by the following method using absolute paths:

```
 @staticmethod
    def _list_models_in_dir(path):
        if not path or not os.path.isdir(path):
            return []
        else:
            return [model
                    for model in glob.glob(os.path.join(path, '*'))
                    if os.path.isdir(model)]
```

to be returned further as:

```
{
    available_projects: {
        default: {
            status: "ready",
            available_models: [
                "/media/.../projects/default/model_20171225-154624"
            ],
        }
    }
}
```

That results in certain difficulties of service deployment, as it exposes internal server paths and is not good for security reasons. When trying to use only model name without path in query, fallback is used, as there is no such name in current models list, where names are stored with paths.

Are there any plans to change something in this regard?

**Comment by tmbo** [comment]
That is a very good point :+1: I think it would make sense to return the path relative to the project directory. Do you mind creating a PR fixing this?

**Comment by majeedk526** [comment]
anyone working on this ? I would love to raise PR for it.

**Comment by tmbo** [comment]
@majeedk526 I don't think so, would be great if you could work on this :+1:

**Comment by majeedk526** [comment]
seems like it has already been fixed. 

current output: {
    "available_projects": {
        "default": {
            "status": "ready",
            "available_models": [
                "fallback"
            ]
        }
    }
}

    def _list_models_in_dir(path):
        if not path or not os.path.isdir(path):
            return []
        else:
            return [os.path.relpath(model, path)
                    for model in glob.glob(os.path.join(path, '*'))
                    if os.path.isdir(model)]
