### ISSUE TITLE
Entity extraction is case sensitive. How can we make it case insensitive

### ISSUE THREAD

**Issue by teja463** [RasaHQ/rasa_nlu#745]
**Rasa NLU version** (`0.10.4`):

**Used backend / pipeline** ( `spacy_sklearn`):

**Operating system** (windows):

**Issue**:
Hi,
I am using spacy_sklearn as backend for training my models with rasa nlu. When i query models with the same case as defined in the training data, entity extraction is working fine. But if i use small case it does not extract the entities. Is there any way we can make entity extraction as case insensitive. There is a open issue #729 . 

**Content of configuration file** (if used & relevant):
```json

```

**Comment by wrathagom** [comment]
@teja463 there the conversation seemed to suggest trying the medium spacy model, have you done that?

**Comment by wrathagom** [comment]
so it was likely because of spacy 2.0 changes.

**Comment by mpbalshetwar** [comment]
I am using tensorflow and I have exact same issue. does anyone has any solution for this?
