### ISSUE TITLE
Support for LUIS closed list entities

### ISSUE THREAD

**Issue by pupipipu** [RasaHQ/rasa_nlu#747]
**Rasa NLU version** (e.g. `0.7.3`):

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...):

**Operating system** (windows, osx, ...):

**Issue**:

**Content of configuration file** (if used & relevant):
```json

```

Is there any timeline to support LUIS closed list entities?

**Comment by tmbo** [comment]
I am sorry, but there isn't a timeline for this yet.

**Comment by akelad** [comment]
i belive this is covered by lookup tables
