### ISSUE TITLE
Can't find logs folder

### ISSUE THREAD

**Issue by scevola44** [RasaHQ/rasa_nlu#752]
**Rasa NLU version** : 0.10.4

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...):
  
```
    "nlp_spacy",
    "tokenizer_spacy",
    "intent_featurizer_spacy",
    "intent_classifier_sklearn",
    "ner_crf",
    "ner_synonyms"
```
**Operating system** (windows, osx, ...): CentOS 7 - 64bit

**Issue**: Does Rasa NLU save its predictions in the logs during use? If not, how do I manually activate it? Because for some reason, I cannot find the "logs/" folder cited in the docs. I even tried giving it a unique name (entry in config file), easy to find with search functions, but it's just not anywhere, in or outside of rasa_nlu package folder. If relevant, I'm using Rasa NLU with **Rasa Core 0.7.6**.

Edit: Also, to clarify, this is where I'm getting the "logs/" folder stuff from: http://rasa-nlu.readthedocs.io/en/stable/closeloop.html?highlight=logs

**Content of configuration file** (if used & relevant):
```json
"response_log" : "TEST_LOGS/"
```

**Comment by twerkmeister** [comment]
If you use Rasa NLU as a http server, then you should find these logs in the working directory from which you started the server.

For Rasa core itself - all logs go into it's own logging file `rasa_core.log`. And if you set the log level to debug, you should get all the messages with classified intent and entities in that file.

Does that help?

**Comment by scevola44** [comment]
Yes, using Rasa NLU as an http server did create the log files. However, Rasa Core doesn't do so when run locally on the machine (at least, I can't find the rasa_core.log file anywhere in either the project folder or rasa_core's). Is this behavior expected and the logs only appear when using Rasa as a server?

**Comment by wrathagom** [comment]
Probably a better question to ask on an issue in the Rasa Core repository, Can you re-ask there?

**Comment by sandeepsuvit** [comment]
Hope this helps someone. If you run the server using the following command the logs file will be generated under the project root `logs` folder

```
python -m rasa_nlu.server --path projects --response_log logs
```
