### ISSUE TITLE
Feature to persist trained model to Azure Cloud Storage

### ISSUE THREAD

**Issue by shicode** [RasaHQ/rasa_nlu#765]
**Rasa NLU version** (e.g. `0.7.3`):

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...):

**Operating system** (windows, osx, ...):

**Issue**:

Rasa NLU is a very useful tool but model persistence options are a little limited currently. Would it be possible to add a feature to persist trained pipeline models to Azure Blob Storage?

**Content of configuration file** (if used & relevant):
```json

```

**Comment by wrathagom** [comment]
Someone would just have to add a new persister [here](https://github.com/RasaHQ/rasa_nlu/blob/master/rasa_nlu/persistor.py#L126).

If I am remembering all of the cloud persistors have been community contributions. So likely the Rasa team would be looking for a PR from someone to add this, but it is certainly doable and would be a valuable addition.
