### ISSUE TITLE
Varying-Length Entities

### ISSUE THREAD

**Issue by MariamMohamedFawzy** [RasaHQ/rasa_nlu#768]
**Rasa NLU version** : `0.10.6`

**Operating system**: Linux

**pipeline**: ["nlp_mitie", "tokenizer_mitie", "ner_mitie", "ner_duckling", "ner_synonyms", "intent_entity_featurizer_regex", "intent_featurizer_mitie", "intent_classifier_sklearn"]

**Issue**:

I want to train rasa to detect names of meetings and names of rooms. I do not have control over the length of names,  but the name of a room is followed by "room" and the name of a meeting is followed by "meeting".
Rasa cannot detect lengths of names not in the training data, so in "show me Chatbot final discussion meeting in the conference room today" or "I wanna see my meetings in Five Minutes room", the full names are not detected.  
why does not rasa get the pattern meeting_name + meeting or room_name + room?

**Comment by wrathagom** [comment]
How much training data are you providing to train these entities, entities can often take lots of examples to train successfully. Also have you tried `ner_crf`?

If it's possible to provide your full training data I can test it out and see if I have other suggestions.

**Comment by MariamMohamedFawzy** [comment]
I am using about 250 examples for 7 entities, but have not tried ner_crf.  How many examples for each entity are enough to get good results?

**Comment by wrathagom** [comment]
unfortunately it really depends on the entities and sentences that contain them. If you could provide your training data it would probably help us help you.

**Comment by MariamMohamedFawzy** [comment]
Adding more examples using the same pipeline makes the model better, it can detect longer names. Thanks
