### ISSUE TITLE
Misaligned entity annotation warning for special cases in MD training format

### ISSUE THREAD

**Issue by nmstoker** [RasaHQ/rasa_nlu#769]
**Rasa NLU version**  `0.10.6`

**Used backend / pipeline** `spacy_sklearn`

**Operating system** Arch Linux

**Issue**:
I've just switched from JSON training format to MD (and it's nicer in lots of ways! :smile:) but when I train with data in the new format, I don't seem able to avoid the warning with some special cases, such as this:

```- When was [he](pronoun) [born](feature)?```

That gives a warning like this:

```WARNING:rasa_nlu.extractors.crf_entity_extractor:Misaligned entity annotation in sentence 'When was he born?'. Make sure the start and end values of the annotated training examples end at token boundaries (e.g. don't include trailing whitespaces).```

It occurs where one of the entities repeats earlier in the text. In the example above "he" is part of "W**he**n". It's more likely to come up when you've got a short entity (eg "I", "he" are obvious ones).

This didn't occur in the JSON format so far as I recall, because you were specifying the precise location numerically, but now as the MD parser does that for you, I think it makes a mistake about which bit of the text is referenced.

It's not a big deal as it doesn't seem to affect training results (so far as I can tell)

**Comment by amn41** [comment]
Thanks! no this will definitely affect results. If it doesn't in your case it's probably because the crf is placing most of the weight on the word's identity to determine if it's an intent. 

I remember we had this issue with one of the import formats (I think the LUIS v1 with word index annotations) and we fixed it then.

**Comment by tmbo** [comment]
Should be fixed by the PR #772 that just got merged :)
