### ISSUE TITLE
Interactive training: Bot resets after running train_init.py

### ISSUE THREAD

**Issue by bhaskarvarman** [RasaHQ/rasa_nlu#770]
Hi,

I have a simple interactive/stateless story that if the user says hi, bot should greet back. 
Step 1: Created stories.md file with a couple of stories
Step 2: Ran train_init.py
Step 3: Ran run.py. Minimal bot launched, it correctly gives the utter based on previous training. For e.g., 
User: _greet
Bot: _utter_greet
Step 4: Ran train_online.py. The bot doesn't remember anything and I have to start again.
User: Hi
Bot:
intent: none
action is wrong
and I have to retrain it.

According to the documentation:
"The policy model will get updated on-the-fly, so that it’s less likely to make the same mistake again. You can also export all of the conversations you have with the bot so you can add these as training stories in the future."

Is something wrong with the above mentioned steps? If not, how can I make this work?

**Comment by amn41** [comment]
thanks for creating this issue @bhaskarvarman - but I think this is a rasa_core issue, correct? Could you please post your issue there?

**Comment by bhaskarvarman** [comment]
Sure, thank you!
