### ISSUE TITLE
gazetteer support

### ISSUE THREAD

**Issue by twerkmeister** [RasaHQ/rasa_nlu#773]
**Proposed Improvement**:
Add another entity extractor component that makes use of gazetteers, i.e. list of known entities. Such a component would be useful if you have a large number of entities that you know upfront, e.g.  an index of all the streets in a city or a list of dishes on a menu. Could be an alternative to filling your training data with lots of templated and similarly structured sentences for training.

Possible extensions
* fuzzy matching (also matching variants up to edit distance X)
* combination with the regex component to define regexes in combination with each instance in the entity list, e.g. streetname + streetnumber?
* integration as a feature into the crf model - so the crf could accept or overwrite the gazetteers finding

Thoughts?

**Comment by wrathagom** [comment]
Similar to #747 or at least related.

**Comment by twerkmeister** [comment]
Templated sentences are also making the entity recognizer overly greedy. I created many sentences on the basis of templates to let the CRF learn the structure of the sentences and entities. As a result I have 10000 examples of this intent with entities now. My other intents are more in the range of 10-30 examples and do not have entities. I subsampled the intent field of the overrepresented intent and that helps improve intent classification, but the entities are still in all these sentences, so I am optimizing the extractor to be more greedy. Gazetteer could help here too. Another way would be to create some flexible balancing for intents and entities, multiplying examples so that neither intents nor entities are skewed.

**Comment by amn41** [comment]
yeah I quite like the approach of adding `exists_in_list` as a feature to the CRF. I think this is a better approach than using templates to generate lots of examples, because that will overfit to your template + lead to class imbalances

**Comment by twerkmeister** [comment]
For the language models I built, I use [spacy 2.0 extension tags](https://spacy.io/usage/processing-pipelines#section-extensions) to bring in additional features for the crf ([see this PR](https://github.com/RasaHQ/rasa_nlu/pull/749)). Also, [here is a complete extension tag example](https://github.com/ines/spacymoji).

I was wondering if we could use these extension tags to dynamically integrate features into the crf. Components would register extensions on tokens, spans, or documents. When it's the crf's turn, it checks which extensions have been registered and adds them as features. 

----

As you mentioned, the gazetteer extractor could set a flag on a token based on the entity lists provided to it. So it would create extensions like `in_street_list` or `in_city_list`, depending on the different entity lists provided. The semantic would be "We found a string from the list and this token is part of that string". If we wanted to be more assertive, the gazetteer component could even merge the tokens together as a span (like seen in the spacymoji example).

I am worried that the integration of the gazetteer into the crf brings it's own challenges for crf training. Because now we are introducing a highly indicative feature, and left unchecked, the crf would probably be prone the overly rely on the gazetteer. For robustness we could deliberately have the gazetteer create false positives, false negatives, and conflicts during training.

Am I overthinking this?
How much benefit would we get from integrating gazetteers into the crf vs keeping it to a simple string matching component?

**Comment by twerkmeister** [comment]
I think a minimal implementation of this should include a component that can extract entities given a number of entity lists. The integration with the CRF would build on top of that in any case, by setting flags on tokens associated with the extracted strings.

In terms of implementation, I came up with a Trie-based approach. It's very simple and not bad in terms of efficiency for multi string search. Tested it in this jupyter notebook:
<img width="1144" alt="screen shot 2018-01-19 at 13 28 15" src="https://user-images.githubusercontent.com/1107341/35136150-d991b982-fd1c-11e7-88d3-c73218af110e.png">

In terms of how to supply the lists, there would be multiple options:
* add them to the training data files, which is convenient, since only one file needs to be handled ,but it might make it unwieldy for long lists of entities. Also needs support in both json and md
* supply them in a seperate json file or directory with one json per entity type. more files and yet another config var, but less cluttered

What do you think @amn41, should I move forward with this?

**Comment by amn41** [comment]
thanks @twerkmeister - let me get back to you on this ASAP

**Comment by twerkmeister** [comment]
@amn41 🎃

**Comment by amn41** [comment]
sorry for the week delay :) 
1. having a pre-existing list is a super relevant use-case we see often
2. I think it's not a good approach to use templates to generate a bunch of examples. The CRF will just reverse-engineer the templates and preventing overfitting there is highly delicate. 
3. One approach I often suggest is to remove the `'low'` feature from the CRF, so that it doesn't see the identity of the word at all. 
4. I do think that the `exists_in_list` feature carries valuable information, but we would probably have to regularise by e.g. artificially dropping out this feature sometimes. Doing that robustly so Rasa users don't have to tweak parameters could be a challenge.
5. [mordecai](https://github.com/openeventdata/mordecai) has an interesting approach where they combine entities with a gazetteer *after* they've been extracted. 

Let's start as you propose with a simple `list of entities` extractor & then try to combine with the crf in a sensible way

**Comment by twerkmeister** [comment]
1. 👍 
2. 👍 
3. I suppose you mean not just for the center word, but at every word position, right?
4. 👍 
5. Had a look at it! Their approach gives you the benefit of creating less false positives extracting the entities, but it requires you to already have a classifier for the given entity type. Afterwards they use the gazetteer as a knowledge base and do entity linking. Conflict resolution is done with a classifier trained with data they annotated using prodigy. I am not sure how a similar approach would help us.

**Comment by r-wheeler** [comment]
Interested in this as well. Used spacy 2.0 PhraseMatcher for gazetteer and would love to be able to integrate into pipeline.

**Comment by tstreamDOTh** [comment]
When can we expect this feature?

**Comment by akelad** [comment]
gonna close because we have lookup tables now
