### ISSUE TITLE
How many training examples should I feed to prepare good model 

### ISSUE THREAD

**Issue by dilipbobby** [RasaHQ/rasa_nlu#780]
**Rasa NLU version** (e.g. `0.7.3`):

**Used backend / pipeline** (`spacy_sklearn`):

**Issue**: In the example of the restaurant data, less number of examples were used  (very less conversations).In order to prepare a good model how many examples should I feed to RASA to train ? what should be the size of my train data ?
**Content of configuration file** (if used & relevant):
```json

```

**Comment by twerkmeister** [comment]
Unfortunately, there is no cookie-cutter answer to this question. It depends on your intents and your entities.

If you have intents that are easily confusable, you will need more training data. Accordingly, as you add more
intents, you also want to add more training examples for each intent. If you quickly write 20-30 unique expressions for
each intent, you should be good for the beginning.

The same holds true for entities. the number of training examples you will need depends on how closely related your different entity types are and how clearly
entities are distinguishable from non-entities in your use case.

To assess your model's performance on your use case, run the server and manually test some messages, as shown in the tutorial, or use the evaluation script

**Comment by dilipbobby** [comment]
Thank you :) I will close the issue for now if there are any doubts on the same,I will re-open it.
