### ISSUE TITLE
Intents not resolved correctly.

### ISSUE THREAD

**Issue by mehfuzh** [RasaHQ/rasa_nlu#787]
Hi Guys-

I am implementing Rasa Core into my project and could not get the intents working other than sample data. I am using spacy-sklearn as pipeline.

Here is the project:
https://github.com/mehfuzh/rasa-nlu-debug

It looks like the data is correct and here it is:

```
{
    "rasa_nlu_data": {
        "regex_features": [],
        "entity_synonyms": [],
        "common_examples": [
            {
                "text": "Hi",
                "intent": "start"
            },
            {
                "text": "Hello",
                "intent": "start"
            },
            {
                "text": "Start",
                "intent": "start"
            }
        ]
    }
}
```

Thanks in advance!

**Comment by careless25** [comment]
You should start with at least 10-20 examples per intent

**Comment by mehfuzh** [comment]
Cool. I will try it. However, the documentation suggests at least 2. This is not the case of other nlu where it will just return null if I send it "Hi"

```
{
    "intent": null,
    "text": "hi",
    "entities": [],
    "intent_ranking": []
}
```
May be there is a sample database?

**Comment by wrathagom** [comment]
Pretty certain the documentation suggests 2 intents, not 2 examples. What @careless25 is suggesting is at least 10-20 examples per intent.

Since you only give one intent then there is nothing to classify.

**Comment by wrathagom** [comment]
Let us know if adding another intent and perhaps a few more examples doesn't solve it.

**Comment by mehfuzh** [comment]
Ok Thanks for the clarification

**Comment by mehfuzh** [comment]
Yep. Adding few more, makes it work like a charm!
