### ISSUE TITLE
No project found error

### ISSUE THREAD

**Issue by majeedk526** [RasaHQ/rasa_nlu#788]
**Issue**:
The current parse() implementation in data_router.py is that if a project is not found in project_store it loads it from project directory.

However _list_projects() return list of project names with absolute path:
def _list_projects(path):
        """List the projects in the path, ignoring hidden directories."""
        return [fn
                for fn in glob.glob(os.path.join(path, '*'))
                if os.path.isdir(fn)]

and since user passes only project name (ex: http://localhost:5000/parse?q=hi&project=project1)

so due to this project name is not matched even if the project is present in the directory

        if project not in self.project_store:
            projects = self._list_projects(self.config['path']) // returns ['/absolute-path/projects/project1']
            if project not in projects: // does not match as project = project1
                raise InvalidProjectError("No project found with name '{}'.".format(project))

This is for the case when rasa server is already running and user puts a pre-trained project from another directory to current project directory

**Comment by PHLF** [comment]
@tmbo I didn't test it but this quick fix should work:

https://github.com/RasaHQ/rasa_nlu/blob/bf9a04a8238c80e902dafbebb8c79468471090aa/rasa_nlu/data_router.py#L171-L175

to

```python
 @staticmethod
    def _list_projects(path):
        """List the projects in the path, ignoring hidden directories."""
        return [os.path.basename(os.path.normpath(fn))
                for fn in glob.glob(os.path.join(path, '*'))
                if os.path.isdir(fn)]
```

**Comment by wrathagom** [comment]
@majeedk526 could you attempt to implement @PHLF's suggestions and see if that works. If it does a PR would be appreciated.

**Comment by majeedk526** [comment]
I tested the fix. It seems working. Have raised PR #812 as well. Thanks @PHLF
