### ISSUE TITLE
literal match misclassified

### ISSUE THREAD

**Issue by tycho01** [RasaHQ/rasa_nlu#790]
**Rasa NLU version**: `0.10.6`
spacy: `1.8.2`
**Operating system**: ubuntu
**Used backend / pipeline**: `spacy_sklearn`
**Issue**:

Even when I try an input message that literally matches a known example, it is somehow misclassified.

`nlu.md`:
```md
## intent:literal_match
- hi
- foo

## intent:irrelevant
- bar
- baz
```

**config**:
```json
{
  "pipeline": "spacy_sklearn",
  "path" : "./models",
  "data" : "./data/nlu.md"
}
```

After training and serving, I try it out: `curl -XPOST localhost:5000/parse -d '{"q":"hi"}'`.
The result I get is as follows: `{"entities": [], "intent": {"confidence": 0.7500297328927935, "name": "irrelevant"}, "text": "hi", "intent_ranking": [{"confidence": 0.7500297328927935, "name": "irrelevant"}, {"confidence": 0.24997026710720655, "name": "literal_match"}]}`.

It appears that despite `hi` literally matching an explicit training example in category `literal_match`, category `irrelevant` is nevertheless considered a significantly closer hit.
This is a minimum repro of my initial encounter of this problem, which had more realistic input data, yet similarly failed to recognize even literal matches.
Perhaps one would normally use more input data than this, but I'm still surprised -- shouldn't a trivial example be easy?

This issue appears to be a minimum reproduction of #767.
Suggestions in that thread have included using Spacy 1.x and (re-)linking spacy's `web_md`. I was already on 1.x, and tried relinking the corpus, but the behavior appears to persist for me.

**Comment by wrathagom** [comment]
Given you've covered the basics. Please provide your complete training data so we can re-produce.

**Comment by tycho01** [comment]
Sure. I've put my repro [here](https://github.com/tycho01/rasa_nlu/commit/b2a7e7fe2585604412820f62a0c033942a211f07) now, up to date with the current master branch.

```bash
# try tutorial on master, ok
$ python -m rasa_nlu.train -c sample_configs/config_spacy.json
$ python -m rasa_nlu.server -c sample_configs/config_spacy.json
$ curl -XPOST localhost:5000/parse -d '{"q":"hi"}'
# retry with changed input data on repro branch, prediction breaks
```

**Comment by twerkmeister** [comment]
Hey @tycho01 could you try adding a couple more examples? If I am not mistaken the sklearn classifier splits the training data into multiple "folds". Only having 4 examples might mess up the training. Try with some more :+1:

**Comment by tycho01** [comment]
Thanks, seems that was it, I'll close then!
