### ISSUE TITLE
Detecting and normalizing amount/numeric from user input

### ISSUE THREAD

**Issue by sauviksarkar** [RasaHQ/rasa_nlu#791]
**Rasa NLU version** (e.g. `0.7.3`):0.10.6

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...): spacy_sklearn

**Operating system** (windows, osx, ...): osx

**Issue**:
How can we detect and parse out amount from user input 
e.g. 
100k translated to 100,000 
1m to 1000000 etc.

Is there any examples of this type of inputs available somewhere.

**Content of configuration file** (if used & relevant):json
```json

```

**Comment by wrathagom** [comment]
I'm pretty certain duckling does this. https://rasa-nlu.readthedocs.io/en/latest/pipeline.html#ner-duckling

**Comment by sauviksarkar** [comment]
got it, Thank YOU!!

**Comment by wrathagom** [comment]
I'll close for now, let me know if that doesn't get you what you need.
