### ISSUE TITLE
Extity extraction classification report is hard to call

### ISSUE THREAD

**Issue by NickHogan** [RasaHQ/rasa_nlu#792]
Rasa NLU version: '0.10.6'

How do you get the bioclassification report to run on entity extraction for ner_crf? Can you provide some example code to navigate the json to crf process?

@twerkmeister suggests this feature is already operable for ner_crf and duckling in this doc: https://github.com/RasaHQ/rasa_nlu/commit/0d2611b094e48cc82a5f00f4fc03bf1e8227aaf9. Is that correct?

**Comment by twerkmeister** [comment]
Hey @NickHogan sorry for the confusion, BILOU tag evaluation is not supported as this point in time, maybe we should be more clear about it in the docs. We only supported the simple tags and the distinction to BILOU serves only as an explanation of how the system works.

Does this answer your question?
