### ISSUE TITLE
How to deploy current version of rasa on the gunicorn under nginx as proxy 

### ISSUE THREAD

**Issue by pvagare** [RasaHQ/rasa_nlu#793]
I want to deploy rasa_nlu on the gunicorn and nginx as proxy.  In previous version it is possible but in this new version I am not able to deploy the same. 
How should I deploy the rasa_nlu on gunicorn and ngxix as proxy. 
Please help me to sort out the same.

**Comment by pvagare** [comment]
HI Team,
Any updates ???

**Comment by wrathagom** [comment]
I am pretty confident that support for gunicorn was dropped in this PR https://github.com/RasaHQ/rasa_nlu/pull/450#issuecomment-317029061

I would recommend looking into docker and scale https://docs.docker.com/compose/reference/scale/

@PHLF any other comments?

**Comment by tmbo** [comment]
Yeah, scaling with gunicorn doesn't work so well because of the memory the language model requires so we removed it when switching from flask to Klein HTTP framework. Rather spin up multiple instances (e.g. using docker as @wrathagom suggested).
