### ISSUE TITLE
Interpreter.load performance issues

### ISSUE THREAD

**Issue by dcolomvakos** [RasaHQ/rasa_nlu#799]
**Rasa NLU version** (e.g. `0.10.6`):

**Used backend / pipeline** (`spacy_sklearn`):

**Operating system** (windows Python 3.5.1 Anaconda 64bit):

**Issue**:
Interpreter.load can take up to 30 seconds to load a model (even a very small one.)   When setting "skip_validation = False" this comes down to 20 seconds.  This still seems an order of magnitude too slow? Is there a way to speed this up (my model is tiny, like 32kb, classifier is 60kb)

![image](https://user-images.githubusercontent.com/4049724/35339174-e505f4f2-00ed-11e8-8408-7e0931265648.png)

![image](https://user-images.githubusercontent.com/4049724/35339157-d67cc938-00ed-11e8-88ae-621522b957c0.png)

[[Interpreter.load time: 18.61006450653076]]

**Comment by tmbo** [comment]
You need to keep in mind that this wont only load your model but will also load the spacy word vectors (this takes most of the time). there is not a lot we can do there to speed that up - there is caching rasa nlu does but only if you load multiple models

**Comment by wrathagom** [comment]
The approach we take is to pre-load by making a request to the model as soon as training is finished. It doesn't make it load faster, but rather just means that the model is already loaded once requested.
