### ISSUE TITLE
Inconsistencies in Tutorial documentation

### ISSUE THREAD

**Issue by Ghostvv** [RasaHQ/rasa_nlu#800]
**Rasa NLU version**:
`0.10.6`
**Used backend / pipeline**:
`mitie`, `spacy_sklearn`
**Operating system**:
`osx`
**Issue**:
In "Tutorial: A simple restaurant search bot" part of documentation, the trained model applied to "I am looking for Chinese food" does not extract any entities. That can be confusing for an inexperienced user even though there is a line afterwards saying that it happens due to lack of training data.

I suggest, first giving the example of "I am looking for Mexican food" where the entities are extracted, and then say that due to the lack of training data in some cases like "I am looking for Chinese food" the entities are not extracted, though the intent classification is correct.

In the end, it is said that the "mitie" pipeline doesn’t include the "intent_ranking", however in the example below, the entities are extracted with "ner_mitie", but there is "intent_ranking". Probably mitie-sklearn pipeline was used in this case, but in this tutorial it was not properly introduced and can create confusion for first time users.

In master version, there is a typo in Rasa_nlu_docs->Evaluation->Entity Extraction->ner_synoMyms

**Comment by tmbo** [comment]
@Ghostvv this sounds very good and I think the suggested change to the example is a great idea. Do you mind working on that change and creating a pull request to update the documentation?
