### ISSUE TITLE
Question: Intents with required or disallowed entities

### ISSUE THREAD

**Issue by wuschi** [RasaHQ/rasa_nlu#801]
Hi,

i'm currently evaluating rasa-nlu for a voice assistant that i'm writing for my smart home.

it looks quite good at first sight, however i am trying to solve some questions:

I'm currently writing a (german) training file for switching on/off some lights in my house.

The training data looks something like this:

```
## intent:light_on

- turn on the light

- lights off

- ...

## intent:light_on_room

- turn on the light in the [living room](location)

- [kitchen](location) lights off

- ...
```

The idea is that light_on_room requires a valid entity, while light_on doesn't.

In case of light_on i will immediately switch on/off the lights in the current room, which will be delivered in the context of my voice assistant.

In case of light_on_room i will switch on/off the lights in the room given by the entity, or ask for the location if no entity is recognised.

Now to the questions:
1) Is it somehow possible to tell rasa_nlu that no entity is allowed for light_on while an entity will be required for light_on_room? I guess this would improve confidence because while testing my setup i sometimes received false intents.
2) is it possible to restrict entities to a list of valid values (plus some synonyms) = the rooms in my house?

Thanks and kind regards

**Comment by wrathagom** [comment]
all of this would need to be implemented on top of Rasa. Rasa NLU handling the intents/entity classification and some custom programming to enforce your rules and handle fulfillment.

There are other issues specifically discussing adding this type of functionality.
