### ISSUE TITLE
The document should be clear

### ISSUE THREAD

**Issue by hieuxinhe94** [RasaHQ/rasa_nlu#804]
project use many package and tools. 
In your document, you haven't mentioned OS you are working.

**Comment by tmbo** [comment]
I am not quite sure what you mean. Can you explain a bit further what document you mean? Also feel free to create a PR to improve the document you are referencing.

**Comment by PHLF** [comment]
Your question should be clear.

(I'm sorry, I just couldn't resist 😃)


If I understand your question, Rasa NLU can be used almost wherever a Python interpreter runs (macOS, Windows, Linux derivatives...). You can also use it through [Docker](https://github.com/RasaHQ/rasa_nlu#quick-install) which should ease a lot the deployment pain.

**Comment by wrathagom** [comment]
@hieuxinhe94 let us know if you have more questions.
