### ISSUE TITLE
Make regex features training data format less verbose

### ISSUE THREAD

**Issue by twerkmeister** [RasaHQ/rasa_nlu#807]
**Rasa NLU version** (e.g. `0.10.6`):

It seems to me that the regex feature training data format is overly verbose. Right now it's a list of object in the form
```json
[{
  "name": "zipcode",
  "pattern": "[0-9]{5}"
},
{
  "name": "greet",
  "pattern": "hey[^\\s]*"
}]
```

It could be much shorter in the form:
```json
{
  "zipcode": "[0-9]{5}",
  "greet": "hey[^\\s]*"
}
```
The only thing that we would need to take care of here is feature ordering.
Same goes for entity synonyms

**Comment by tmbo** [comment]
I think this was the reason to make it an array, to have the feature ordering right there. I mean it is not like we could do that differently, but then again I wan't to push the `md` format instead of the json one for human usage.
