### ISSUE TITLE
How to run latest version of rasa nlu (0.10.4) on gunicorn server?

### ISSUE THREAD

**Issue by sagardevadakar** [RasaHQ/rasa_nlu#809]
**Rasa NLU version** : 0.10.4

**Used backend / pipeline** : spacy_sklearn`

**Operating system** Linux (ubuntu)

**Issue**: I want to run rasa_nlu 0.10.4 on gunicorn server. I have created separate daemon process to run it with command
`exec Rasaenv/bin/gunicorn -w 1 --threads 3 -k gevent -b unix:/RASA_DIR/gunicorn.sock rasa_nlu.wsgi ` 
OR
`exec Rasaenv/bin/gunicorn -w 1 --threads 3 -k gevent -b unix:/RASA_DIR/gunicorn.sock rasa_nlu.server`

but it could not start. It was working for old version of RASA. It is giving an error
'Model Error: rasa_nlu.wsgi model does not found' even though I have installed rasa_nlu.

**Content of configuration file** (if used & relevant):
```json

```

**Comment by PHLF** [comment]
Hi, sorry but this is not possible anymore.

See https://github.com/RasaHQ/rasa_nlu/issues/793

**Comment by sagardevadakar** [comment]
Thanks @PHLF

**Comment by sagardevadakar** [comment]
@PHLF Can you suggest which application server should I use for deploy rasa nlu?

**Comment by wrathagom** [comment]
See #793 we're recommending docker. Let us know if you have anymore questions.
