### ISSUE TITLE
Which application server should used for deploy lateste version of RASA NLU?

### ISSUE THREAD

**Issue by sagardevadakar** [RasaHQ/rasa_nlu#810]
**Rasa NLU version** : 0.10.4

**Used backend / pipeline** : `spacy_sklearn`

**Operating system** : Linux (ubuntu 16.04)
**Issue**:  I want to deploy/ run rasa nlu latest version but support for gunicorn was dropped in latest version of rasa nlu so can anybody suggest which other application server should I use as nginx proxy?

**Content of configuration file** (if used & relevant):
```json

```

**Comment by PHLF** [comment]
Rasa NLU has its own http server, but if you mean "how to scale up Rasa NLU", see https://github.com/RasaHQ/rasa_nlu/issues/793#issuecomment-360858278

**Comment by wrathagom** [comment]
docker for the win, let us know if you have more questions.
