### ISSUE TITLE
Train multiple files for single model and DeprecationWarning

### ISSUE THREAD

**Issue by AbdurRub** [RasaHQ/rasa_nlu#811]
**Rasa NLU version** : 0.11

**Used backend / pipeline** : spacy_sklearn

**Operating system**: Ubuntu 17.04

**Issue**:
How can we train multiple files for single model (JSON) case , I could not find any documentation on this.

Plus 
I am facing this warning while evaluating my model
DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use array.size > 0 to check that an array is not empty.

**Comment by PHLF** [comment]
Hi, sorry but it doesn't seem possible at the moment. See: https://github.com/RasaHQ/rasa_nlu/issues/180

As for the deprecation warning, this is likely a numpy warning, you can ignore that for now.

**Comment by AbdurRub** [comment]
support for splitting training data into multiple files (markdown and JSON only) has been given in Version 0.11 released yesterday.

**Comment by amn41** [comment]
The latest release (0.11.0) supports this: http://nlu.rasa.ai/config.html?highlight=multiple#data

your 'data' config var just needs to point to a directory containing mutliple data files (and nothing else). The files must be the same format, e.g. all json or all markdown

**Comment by PHLF** [comment]
My bad 😢

**Comment by amn41** [comment]
no worries!

**Comment by AbdurRub** [comment]
Perfect! thanks @amn41 and no worries @PHLF
