### ISSUE TITLE
'0' Entity appearing in model performance metrics 

### ISSUE THREAD

**Issue by tori-salido** [RasaHQ/rasa_nlu#813]
**Rasa NLU version** (e.g. `0.7.3`):
0.12

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...):
spacy_sklearn

**Operating system** (windows, osx, ...):
linux 
**Issue**:
When I run rasa_nlu.evaluation and get the confusion matrix/performance metrics for the entities, there's an entity named '0'. I'm not sure where that's coming from. I'm thinking maybe it's a default for the unknown/not tagged entities? thanks

**Content of configuration file** (if used & relevant):
```json

```

**Comment by twerkmeister** [comment]
Yes right, it's the default for tokens without an entity tag

**Comment by wrathagom** [comment]
Closing in favor of #814
