### ISSUE TITLE
Spam input

### ISSUE THREAD

**Issue by maxbry** [RasaHQ/rasa_nlu#815]
**Rasa NLU version**: `0.10.6`

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...): nlp_mitie, nlp_spacy, tokenizer_mitie, ner_mitie, ner_synonyms, intent_entity_featurizer_regex, intent_featurizer_mitie, intent_classifier_sklearn, ner_spacy, ner_duckling

**Operating system**: Ubuntu

**Issue**: I have input sentences like `I want to drink a beer` which are mapped to the correct intent with a confidence of `~0.75`. Inputs like `Huh?`, `fsdfas fa` or `sdhfnjdasjsdf`are mapped to that very same intent with confidence `0.99`. Why?

**Comment by wrathagom** [comment]
how many intents? can you provide a sample of your training data?

**Comment by wrathagom** [comment]
if it is unbalanced then yes. but also, the junk words you are showing will have no vector representation since they aren't really words. Even `huh` I doubt is in the vocabulary/vectors for spacy.

Which backend are you using, and which spacy version/model?

**Comment by maxbry** [comment]
spacy is version `2.0.5`. What kind of backend do you mean? My pipeline?

**Comment by JediRhymeTrix** [comment]
Same issue with:
`"pipeline": ["nlp_spacy", "tokenizer_spacy", "intent_featurizer_spacy", "intent_entity_featurizer_regex", "ner_crf", "ner_synonyms", "intent_classifier_sklearn", "ner_duckling"],`

**Comment by PHLF** [comment]
To me this sounds like https://github.com/RasaHQ/rasa_nlu/issues/387

**Comment by wrathagom** [comment]
@JediRhymeTrix you're problem sounds like too little training data.

@maxbry I was asking if you were using Spacy or MITIE, looks like spacy is the answer. As @PHLF suggested you could try training an intent to gather the junk

@tmbo what do you think about some sort of console warning when the text to parse is 0% represented by the spacy model?

**Comment by tmbo** [comment]
Yes duplicates #387. For anything in scope the ngram featurizer can be used the amend the embedding with non zero features.

Because this shouldn't happen for in scope data I don't think a warning makes sense.
