### ISSUE TITLE
Missing package in egg after training_data changes

### ISSUE THREAD

**Issue by jamietoyoda** [RasaHQ/rasa_nlu#819]
**Rasa NLU version** (e.g. `0.7.3`): 0.12

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...): N/A

**Operating system** (windows, osx, ...): all

**Issue**: When using your egg (git+https://github.com/RasaHQ/rasa_nlu.git#egg=rasa_nlu) the training_data package is being excluded. I believe this is because it is missing in the setup.py file

**Content of configuration file** (if used & relevant):
```json

```

**Comment by tmbo** [comment]
Just cut a new release, slipped through - sorry for that. 0.11.2 should fix it.
