### ISSUE TITLE
Problem with python 2.7 and japanese characters on current master

### ISSUE THREAD

**Issue by happysalada** [RasaHQ/rasa_nlu#825]
**Rasa NLU version** (e.g. `0.7.3`):
current master
**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...):
spacy_sklearn
**Operating system** (windows, osx, ...):
osx
**Issue**:
I am using rasa nlu in english, but some places name are in japanese, so in my dialogflow origin data entities I have japanese characters.
Using python 2.7 on current master and a training set of data from dialogflow containing japanese characters I get the following error
```
INFO:rasa_nlu.components:Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Traceback (most recent call last):
  File "/Users/Raphael/.asdf/installs/python/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Users/Raphael/.asdf/installs/python/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/Raphael/Documents/Projects/caleb/rasa_nlu/rasa_nlu/train.py", line 125, in <module>
    do_train(config)
  File "/Users/Raphael/Documents/Projects/caleb/rasa_nlu/rasa_nlu/train.py", line 113, in do_train
    training_data = load_data(config['data'], config['language'])
  File "rasa_nlu/training_data/loading.py", line 49, in load_data
    data_sets = [_load(f, language) for f in files]
  File "rasa_nlu/training_data/loading.py", line 63, in _load
    fformat = _guess_format(filename)
  File "rasa_nlu/training_data/loading.py", line 86, in _guess_format
    content = utils.read_file(filename)
  File "rasa_nlu/utils/__init__.py", line 149, in read_file
    return f.read()
  File "/Users/Raphael/.asdf/installs/python/2.7/lib/python2.7/codecs.py", line 296, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc1 in position 1079: invalid start byte
```
I don't have the problem with python 3.6.
Normally this wouldn't be a problem but your docker image uses python 2.7 so I get the same problem

Just a question, is there a particular reason you are using python 2.7 in the docker image ? Are there incompatibility problems ?

(I don't think my configuration file will help a lot here, but I have added it anyways)
let me know if you need more informations
**Content of configuration file** (if used & relevant):
```json
{
  "pipeline": "spacy_sklearn",
  "language": "en",
  "num_threads": 1,
  "max_training_processes": 1,
  "path": "./projects",
  "response_log": "logs",
  "config": "config.json",
  "log_level": "INFO",
  "port": 5000,
  "data": "./data/examples/dialogflow",
  "max_number_of_ngrams": 7,
  "ner_crf": {
    "BILOU_flag": true,
    "features": [
      ["low", "title", "upper", "pos", "pos2"],
      ["bias", "low", "word3", "word2", "upper", "title", "digit", "pos", "pos2", "pattern"],
      ["low", "title", "upper", "pos", "pos2"]],
    "max_iterations": 50,
    "L1_c": 1,
    "L2_c": 1e-3
  },

  "intent_classifier_sklearn": {
    "C": [1, 2, 5, 10, 20, 100],
    "kernel": "linear"
  }
}
```

**Comment by twerkmeister** [comment]
Thanks for submitting the issue, we should change the docker image to python 3! Python2 can be quite a pain working with the non-latin character sets...

**Comment by twerkmeister** [comment]
But in general py2.7 should work... I tried to reproduce the issue with a dialogflow dataset with some Chinese characters, but I don't get the error. Also, both py2 and py3 use the same encoding to read the file, since it's explicitly set. Hmmm, I think we'll update the docker images, since py3 is generally much nicer for these character sets, but I don't understand why py2 chrashes

**Comment by happysalada** [comment]
locally I had the error with py2.7 but not py3.6. When you switch version in images, I can try again and update/close this issue.

**Comment by twerkmeister** [comment]
Btw could you try with the latest master again? We changed the standard encoding a day ago

**Comment by happysalada** [comment]
Just tried, and I still get the same error

**Comment by tmbo** [comment]
I think in the meantime we changed the encoding to `utf8-sig` so that might fix this (the first byte the app tries to read might be a BOM). Can you test on the latest master?
