### ISSUE TITLE
Rasa is not recognizing proper Intent

### ISSUE THREAD

**Issue by BhargavJanardhan** [RasaHQ/rasa_nlu#830]
**Rasa NLU version** (e.g. `0.7.3`): 0.10.0a6

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...): Spacy & Sklearn

**Operating system** (windows, osx, ...): Windows 8

**Issue**: Rasa is not recognizing proper Intent
**Example:**
I created an Intent name “GenericGreetingGM” and trained with utterances like(Good Morning, Gud mrng, gud morning, very good morning etc…). But for few utterances like (gud morning) is going into GenericSmallTalkFamily and we don’t have any words matching with “morning” or “gud” in this intent.

After communicating with few people, they suggested me to check with Rasa evaluation http://rasa-nlu.readthedocs.io/en/latest/evaluation.html (Intent Confusion Matrix) and below are my observations from the image.
Total Utterances: 28
Correct Utterances: 8
Rest of the utterances are going to wrong Intent as I mentioned you in an example. 
![RasaEvaluation_ConfusionMatrix](https://user-images.githubusercontent.com/27334482/35961415-a168ad42-0cd3-11e8-82b9-afab177744bc.png)

Below are my questions.
1.	How does Rasa work
2.	How do rasa analyse the text and give the Intent.
3.	How can I analyse using Rasa evaluation/above picture

Could you please help us with this issue and **mainly using Rasa evaluation.**

Thanks in Advance

@wrathagom

**Comment by wrathagom** [comment]
Sorry for the delayed response. The intent that ends with `lkBeliefs` seems to be dominating. Does it have a lot more `common_examples` than any of the other intents?
