### ISSUE TITLE
Flask app not working on browser

### ISSUE THREAD

**Issue by KungFuPandey** [RasaHQ/rasa_nlu#831]
**Rasa NLU version**:
0.10.6

**Used backend / pipeline** :
Spacy_sklearn

**Operating system** ):
OSX 10.13.3

**Issue**:
I am able to setup and train the model. In the trained model folder, I get 2 .pkl and 3 .json files as well.

Now when I try to open the browser and see the chat-bot, all I see is a static page saying "hello from Rasa NLU: 0.10.6".

I am using mac and earlier there were issues linking with SPACY’s en dictionary too (I had to download using python -m spacy download en ). Also there are some environment variable issues when using spacy so we need to initiate these 2 variables to initiate utf-8 locale :
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

The FLASK app isnt opening at all. The webpage which opens (http://127.0.0.1:5000/) is just static and has this written : ‘hello from Rasa NLU: 0.10.6’ .

I used 5000 port as i got that from the output on terminal (from
python -m rasa_nlu.server -c config.json -e luis) :

INFO:__main__:Started http server on port 5000
2018-02-01 13:11:08+0530 [-] Log opened.
2018-02-01 13:11:08+0530 [-] Site starting on 5000
2018-02-01 13:11:08+0530 [-] Starting factory

Any help ?

**Content of configuration file** :
```json
{
  "pipeline": "spacy_sklearn",
  "path" : "models/",
  "data" : "data/gstfaq-data.json",
  "num_threads":10
}
```

**Comment by tmbo** [comment]
Which app are you referring to? The build in server just serves a trained NLU machine learning model there is no UI. You can shot examples at that model using the `http://127.0.0.1:5000/parse?q=my message` endpoint.
