### ISSUE TITLE
  "error": "'NoneType' object has no attribute 'getName'"

### ISSUE THREAD

**Issue by sushantshekhar20** [RasaHQ/rasa_nlu#835]
**Rasa NLU version** ( 0.10.6`):

config : {
  "aws_endpoint_url": null, 
  "response_log": "/app/logs", 
  "max_number_of_ngrams": 7, 
  "ner_crf": {
    "BILOU_flag": true, 
    "L2_c": 0.001, 
    "L1_c": 1, 
    "features": [
      [
        "low", 
        "title", 
        "upper", 
        "pos", 
        "pos2"
      ], 
      [
        "bias", 
        "low", 
        "word3", 
        "word2", 
        "upper", 
        "title", 
        "digit", 
        "pos", 
        "pos2", 
        "pattern"
      ], 
      [
        "low", 
        "title", 
        "upper", 
        "pos", 
        "pos2"
      ]
    ], 
    "max_iterations": 50
  }, 
  "cors_origins": [], 
  "port": 5000, 
  "log_level": "INFO", 
  "mitie_file": "data/total_word_feature_extractor.dat", 
  "duckling_dimensions": null, 
  "storage": null, 
  "spacy_model_name": null, 
  "duckling_http_url": null, 
  "config": "config.json", 
  "emulate": null, 
  "nlu_python_packages": "/usr/local/lib/python2.7/dist-packages", 
  "path": "/app/./projects", 
  "data": "./data/examples/rasa/demo-rasa.json", 
  "num_threads": 1, 
  "pipeline": [
    "nlp_spacy", 
    "tokenizer_spacy", 
    "intent_featurizer_spacy", 
    "ner_crf", 
    "ner_synonyms", 
    "intent_classifier_sklearn", 
    "ner_duckling"
  ], 
  "language": "en", 
  "intent_classifier_sklearn": {
    "kernel": "linear", 
    "C": [
      1, 
      2, 
      5, 
      10, 
      20, 
      100
    ]
  }, 
  "max_training_processes": 1, 
  "project": null, 
  "token": "SOME_TOKEN_HERE", 
  "nlu_home": "/app", 
  "nlu_docker": "YES", 
  "fixed_model_name": null, 
  "log_file": null
}

**Comment by tmbo** [comment]
Without any additional information, this can not be reproduced. Please add some lines of text as well as a stacktrace / output of the log.
