### ISSUE TITLE
How can I run different models on same nlu server ?

### ISSUE THREAD

**Issue by dilipbobby** [RasaHQ/rasa_nlu#837]
if I prepared restaurant search model and ran it on the NLU server
and if i had one more model like hospital_serach and how can I run that model in the NLU server which is up and running restaurant_search model ?
just changing the port number make sense ?

**Comment by tmbo** [comment]
You can either spin up multiple instances or you can server both models with one instance of Rasa NLU. To do so, make sure to properly set the project directory of the server and put both models in there. When using the `/parse` endpoint specify the models & projects as shown in the docs http://nlu.rasa.ai/http.html#post-parse-no-emulation.
