### ISSUE TITLE
"utf-8" vs "utf-8-sig" encoding issue

### ISSUE THREAD

**Issue by akelad** [RasaHQ/rasa_nlu#838]
**Rasa NLU version** (e.g. `0.7.3`): master

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...): spacy_sklearn

**Operating system** (windows, osx, ...): osx

**Issue**:
Getting an UNK training data format when loading the training data file during training. 
This seems to be caused by a change to using "utf-8" encoding from "utf-8-sig" in loading a training data file. 

So this is what the function used to be:
https://github.com/RasaHQ/rasa_nlu/blob/0.11.x/rasa_nlu/converters.py#L310

And this is what it is now:
https://github.com/RasaHQ/rasa_nlu/blob/master/rasa_nlu/utils/__init__.py#L151
https://github.com/RasaHQ/rasa_nlu/blob/master/rasa_nlu/training_data/loading.py#L88

**Comment by tmbo** [comment]
This has been fixed in the latest master.
