### ISSUE TITLE
Variations in Confusion Matrix with changing Kernel for Intent Classifier Sklearn

### ISSUE THREAD

**Issue by AbdurRub** [RasaHQ/rasa_nlu#843]
**Rasa NLU version** (e.g. `0.7.3`): 0.11

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...): spacy_sklearn

**Operating system** (windows, osx, ...):  Ubuntu 17.04

**Issue**:
Attached is the picture of Intent Confusion Matrix using all 3 kernels (Linear , RBF , Polynomial)
There is slight variation in Linear and RBF  but huge variation in Polynomial kernel usage.

I want to ask which one is better to use and what this picture is showing regarding kernel usage. 
I am confused which one is better in my use case.

I am building chatbot for automobile industry assume it.
Data contains different type of messages. falling in Sales Service Parts Intents. 

![abdur 2018-02-13 12-02-36](https://user-images.githubusercontent.com/29856813/36137461-330aacbe-10b7-11e8-9127-87cfe29abbcc.png)

**Comment by tmbo** [comment]
Either Linear or RBF look fine, the polynomial kernel doesn't seem to get the difference between service and anything else. The confusion matrix shows you the prediction of the model on the X axis and the expected label on the y axis. So the diagonal shows the number of examples where the model predicted the label that was expected. Anything that is not on the diagonal is an example where the model predicted the wrong label.
