### ISSUE TITLE
No module named 'sklearn'   in anaconda jupyter

### ISSUE THREAD

**Issue by PriyankaGulhane** [RasaHQ/rasa_nlu#849]
**Rasa NLU version** (e.g. `0.7.3`):

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...):

**Operating system** (windows, osx, ...):

**Issue**:

**Content of configuration file** (if used & relevant):
```json

```

```
ModuleNotFoundError
Traceback (most recent call last) <ipython-input-4-b7c74cbf5af0> in <module>() ----> 1 import sklearn  ModuleNotFoundError: No module named 'sklearn'   in anaconda jupyter 
```

**Comment by tmbo** [comment]
I'll close this, let me know (and provide more details) if this is still an issue.

**Comment by MHDeveloping** [comment]
I still have this issue, on a win7 64 bit machine, using Annaconda5.1 Jupyter 5.5.0
- Before I came to this thread found some on stackoverflow, cause  I couldnt install scipy, which is neede for sklearn?
- stackover : "import sys !{sys.executable} -m pip install scipy", it says "succesfully installed", except "mkl random", but till now I dont considere it as something which is needed.
- tried again: "import sklearn as s", but still the same: "No module named 'sklearn' "

![jupyter_import_sk](https://user-images.githubusercontent.com/28641172/40272786-f9498ebe-5ba2-11e8-827c-f9ad9dbd1c76.PNG)

**Comment by naoko** [comment]
@MHDeveloping , 
When you starat jupyter notebook, do you have environment activated? 
See: https://stackoverflow.com/questions/20081338/how-to-activate-an-anaconda-environment

You can see which environment you are running by executing the following code in jupyter notebook cell
```
%%bash
which python
```

**Comment by MHDeveloping** [comment]
For now I have only 2 environments, only one of them has tensorflow. 
So far as I understand it now, the import of numpy would have faild, if I' use the wrong one?

But I tried your comand either, just got that: "UsageError: %%bash is a cell magic, but the cell body is empty."

**Comment by naoko** [comment]
It is a bit challenging as I don't have/use windows nor conda but I will try my best...

Exit notebook from terminal where you started the notebook by typing `jupyter notebook`
In the same terminal session, when you type `conda list` I'm betting sklearn is not listed. Correct?
If so, run `conda install scikit-learn` and start notebook again and see?

**Comment by MHDeveloping** [comment]
I'm glad to see you still try to help.
I keep my expressions mostly really short, like telegram.
Well, I start Jypiter without command lines, it like:
- start button
- wrting "ana"
- click on it
- click environment
- click on the name (in my case 'tensorflow2')
- click on 'Home'
- click launch Jupyter
I have no idea where to write conda list, but the last comand might be some for cmd?
I already tried, but it just says "conda is a unknown comand"

**Comment by MHDeveloping** [comment]
There is this Webpage with the suitable comandline for windows to install sklearn
`[http://scikit-learn.org/stable/developers/advanced_installation.html]`
But in that case 'pip' is the unknown command

**Comment by naoko** [comment]
Hmm, sorry @MHDeveloping, I'm no help here as it sounds like you might be using some type of graphical user interface to start Jupyter Notebook.. Sorry :(

**Comment by MHDeveloping** [comment]
For all Windows Users,
 this commands are needed and python needs to be installed with adding a path variable (**nor manually steps are requiered,** just call the customize installation, then  it comes to that point where a mark needs to be set)

And for all who have forgotten every thing about command lines, 
- click start
- write 'cmd'
- enter
there will be no more than one icon, click on it.

Here the command lines:
python -m pip install -U pip
(wait for what happend)

pip install numpy
(wait for what happend)

pip install scipy
(wait for what happend)

pip install -U scikit-learn
(wait for what happend)

Whats still left is, cant import 'sklearn'
![jupyt_import_sk](https://user-images.githubusercontent.com/28641172/40274834-bfb86d68-5bd0-11e8-8f4e-a56ddddbaba8.PNG)

**Comment by MHDeveloping** [comment]
@naoko 
Yeah, its true , with some graphical user interface. Before your answer I havnt known, there are ways without it. 
But, at the end of the line, Jupyter is Jupyter, no matter how you start it, Am I wrong?
So I claim, the reason for 'import sklearn' cause an error, is out of: graphical or not graphical.

**Comment by naoko** [comment]
@MHDeveloping , you are absolutely right. I just don't know how to navigate that UI to install package you want in correct environment. 
There is a way to install on Jupyter cell with using `%%bash` but you were getting an error earlier which is mystery for me... this should install in the same environment that running jupyter. It should look like this. Maybe give it one more try?

```bash
%%bash
pip install scikit-learn
```

![screen shot 2018-05-20 at 9 49 59 am](https://user-images.githubusercontent.com/615292/40281211-4baefe12-5c13-11e8-9a1d-b64e4a1269e8.png)

**Comment by MHDeveloping** [comment]
Well, maybe we are a step further, got a different error message. "Couldn't find program: 'bash'"
I attached a png to this message.

Is "'import sklearn' " the way on windows? Maybe it has to be different, there are tones of videos explaining the installation of anaconda on windows, of numpy and scipy, even sklearn, but havnt seen till know the import, except in videos about OSx

**Comment by MHDeveloping** [comment]
there might be the answere, where thy talk **_about the path_**: [(https://stackoverflow.com/questions/42178070/jupyter-notebook-importerror-no-module-named-sklearn)]
I installed jupyter under **_my Path, like_** : C:\User\Me, so I did with Anaconda
So I tried the commands, but they all just throw errors
![jupyter_syntaxerrors](https://user-images.githubusercontent.com/28641172/40326226-1deb80e2-5d2e-11e8-8651-d9a422bf4925.PNG)

**Comment by srideviaishwariya** [comment]
Running into similar issue on MAC

![screen shot 2018-10-10 at 3 07 26 pm](https://user-images.githubusercontent.com/3505829/46768803-708d2f00-cc9e-11e8-83d0-a2e7cc97cf14.png)

$ which conda
/anaconda3/bin/conda
$ which pip
/anaconda3/bin/pip

$ which pip3
/usr/local/bin/pip3

$which python3
/usr/local/bin/python3

**Comment by luciana742014** [comment]
he leido recientemente, en mi caso tenia el mismo problema, en lugar del %%bash, solo digite la linea de abajo: pip install scikit-learn , y la libreria se instalo luego en otra linea hize la importacion y fue correcto
