### ISSUE TITLE
Entity recognition from other intents

### ISSUE THREAD

**Issue by ctrado18** [RasaHQ/rasa_nlu#855]
1 ) I have a general question.

If I have defined an entity in one intent which also occurs in an other intent (where it is not defined), is this entity then recognized?

2 ) How are same values for different entities treated? I have 2 different entities but with same values, are they synonynms?

Is it possible that Verbs as Entity raises problems?

**Comment by chenk17** [comment]
Can anyone help with my questions?

**Comment by wrathagom** [comment]
Can you provide your pipeline or backend configuration. Exactly how entities are trained is specific to the backend.

have you read the entity documentation [here](https://nlu.rasa.ai/entities.html) and [here](https://nlu.rasa.ai/dataformat.html#training-data-format). There is also information about the specific entity pipeline components [here](https://nlu.rasa.ai/pipeline.html#ner-mitie).

if those don't help let me know and I will try and answer any questions that remain.

**Comment by chenk17** [comment]
I am using the spacy sklearn backend and the ner_crf. And I have read erverything. But my questions are special. I asumme that my first question is obvious. Entities should be recognized across different intents, right?

My 3) questions bothers me. I summarize this again: If I have only training example of one entity, will this be recognized everytime? Since I defined it in one sentence I assume it will be recognized everytime in any sentence independently of number of training examples

**Comment by wrathagom** [comment]
Knowing that you are using the CRF matters, as the CRF has a lot more to do with what is around the word and how the word is formatted than it does the actual word. So using CRF to try and answer your questions

1) Assuming that the entity is used in a sentence with similar structure/patterns then it is likely that the entity would be found in other intents.

2) Entities almost always have lots of values. For example the entity PizzaToppings would have lots of values: sausage, pepperoni, cheese, etc.

3) You've discovered synonyms the word **erstattet** should now be classified as the entity `Erstattung` but it will be re-mapped to have a value of `Hoehe` this is useful in the case of common mis-spellings or different words that have the same meaning when trying to answer them. For example someone may ask `I'm looking for a novel by JR Tolkien` while another may ask  `I'm looking for a book by JR Tolkien` novel and book are mostly the same thing so we can use synonyms to re-map book to novel. Entity synonyms are discussed here https://nlu.rasa.ai/dataformat.html#entity-synonyms

**Comment by chenk17** [comment]
Thanks.

2 ) What about different entities but with same values?

1 ) Tha leads to a further question. Is the dependency structure used as a feature for the ner_crf?

**Comment by wrathagom** [comment]
Entities can have the same values, but it can lead to unpredictable results. I would recommend minimizing how often this occurs, potentially by using the intent as the context for which entity is which. For example let's say I have a _Customer Name_ entity and an _Employee Name_ entity. Perhaps I should consider having just a _Name_ entity and using the intent to determine how to use it.

No the dependency structure is not used as a CRF feature. The CRF features used are listed here in the config file: https://rasa-nlu.readthedocs.io/en/latest/config.html#ner-crf Though there Is some discussion about enhancing them #773

**Comment by chenk17** [comment]
Many thanks! But that is now really confusing! You say the entities are coupled to the intent where they have been defined? That was my first question question at the beginning. Or maybe I did not relyy not understand the concept of the entity's **values**?

**Comment by chenk17** [comment]
@wrathagom 

> Assuming that the entity is used in a sentence with similar structure/patterns then it is likely that the entity would be found in other intents.

Furthermore, I have e.g. I have defined one entity in a sentence. Then if I use the same sentence for testing, the entity is not found. That is mostly the case. Why is the entity in the same sentence as used for training not recognized?

**Comment by tmbo** [comment]
What @wrathagom meant with the intent suggestion is to label your intents using the entity type `Name` instead of `Customer Name` and `Employee Name` & *on your end* decide what to do based on intent + entities.

At the moment intent and entity classification are independent.

**Comment by ctrado18** [comment]
Thank you. I try to figure out right now what are the feauture used for the sklearn intent classifier. As I understood it is only the doc.vector which is the average of all word numbers, right? Or is this an array for every word in doc?

And, why are they integer? I would think that real word vector from word emebedding is better?

**Comment by wrathagom** [comment]
@ctrado18 get your questions answered?
