### ISSUE TITLE
Entity recognition with ner_mitie component

### ISSUE THREAD

**Issue by bhaskarvarman** [RasaHQ/rasa_nlu#857]
Rasa NLU version : 0.11.3

Used backend / pipeline : mitie_sklearn

Operating system : Win

Issue : I have defined some entities and have given the synonyms in the "entity_synonyms" section in training data file. After training the data, I started nlu server and tried to test using curl. All the intents are being identified as expected. But I'm facing issues with entity extraction. The ner_mitie extractor is identifying the expected entities but additionally it identifies partial matches which is starting to become the issue. It even takes small words like "in", "at", "hello", etc as entity if the entity values are matching partially(3 letters out of 8 letter word). Is there a way to control this behavior?

Alternately, I used spacy_sklearn and it does not pick the enitites as expected so I'm leaning towards using Mitie as it is giving better responses but with the above mentioned problem. Please let me know what you think.

Thank you!

**Comment by wrathagom** [comment]
It sounds like in both cases (mitie and spacy) you are likely not providing enough training data. Please see this note in the [entity synonyms section](https://nlu.rasa.ai/dataformat.html#entity-synonyms):

> Please note that adding synonyms using the above format does not improve the model’s classification of those entities. Entities must be properly classified before they can be replaced with the synonym value.

Make sure that you are providing enough training examples in the `common_examples` section of the training data for the model to learn enough about your entities.

**Comment by tmbo** [comment]
I'll close this, let me know if there are any follow up questions.

**Comment by bhaskarvarman** [comment]
Sure, thank you.
