### ISSUE TITLE
Tutorial does not work

### ISSUE THREAD

**Issue by nggary** [RasaHQ/rasa_nlu#858]
**Rasa NLU version** (`0.11.3`):

**Used backend / pipeline** (`spacy_sklearn`):

**Operating system** (osx):

**Issue**: I tried to follow the tutorial: https://rasahq.github.io/rasa_nlu/tutorial.html?highlight=project#, 
1. Installed spaCy + sklearn
2. created config_spacy.json
3. downloaded sample file and train
4. I've test greeting and goodbye intent and they are work
but when I test with command: 
`curl -X POST localhost:5000/parse -d '{"q":"I am looking for Mexican food"}' | python -m json.tool`

it returns:
```json
{
  "intent": {
    "name": "None",
    "confidence": 1.0
  },
  "entities": [],
  "text": "yes"
}
```

**Content of configuration file** (if used & relevant):
```json
{
  "project": null,
  "fixed_model_name": null,
  "config": "config.json",
  "data": null,
  "emulate": null,
  "language": "en",
  "log_file": null,
  "log_level": "INFO",
  "mitie_file": "data/total_word_feature_extractor.dat",
  "spacy_model_name": null,
  "num_threads": 1,
  "max_training_processes": 1,
  "path": "/rasa_nlu/projects",
  "port": 5000,
  "token": null,
  "cors_origins": [],
  "max_number_of_ngrams": 7,
  "pipeline": [],
  "response_log": "/rasa_nlu/logs",
  "storage": null,
  "aws_endpoint_url": null,
  "duckling_dimensions": null,
  "duckling_http_url": null,
  "ner_crf": {
    "BILOU_flag": true,
    "features": [
      [
        "low",
        "title",
        "upper",
        "pos",
        "pos2"
      ],
      [
        "bias",
        "low",
        "word3",
        "word2",
        "upper",
        "title",
        "digit",
        "pos",
        "pos2",
        "pattern"
      ],
      [
        "low",
        "title",
        "upper",
        "pos",
        "pos2"
      ]
    ],
    "max_iterations": 50,
    "L1_c": 1,
    "L2_c": 0.001
  },
  "intent_classifier_sklearn": {
    "C": [
      1,
      2,
      5,
      10,
      20,
      100
    ],
    "kernel": "linear"
  }
}
```

Status:
```json
{
  "available_projects": {
    "default": {
      "status": "ready",
      "available_models": [
        "fallback"
      ]
    }
  }
}
```

**Comment by tmbo** [comment]
You shouldn't set the `pipeline` configuration key to `[]` as in this case no component will get trained or used resulting in the above output. Use either a default pipeline `"pipeline": "spacy_sklearn"` or define a pipeline with at least one component in it.

**Comment by nggary** [comment]
I've already define the config_spacy.json, is there any way to restart the server, I think the config isn't updated

**Comment by wrathagom** [comment]
Cross post on SO. https://stackoverflow.com/questions/48882061/rasa-nlu-tutorial-doesnt-work

Do you still have the terminal window open where Rasa is running? If so press `ctrl+c` to stop the process and re-enter the command used to star the server.

**Comment by nggary** [comment]
It works after I restarted the server.
