### ISSUE TITLE
Inconsistent use of config file/object

### ISSUE THREAD

**Issue by Le-Fix** [RasaHQ/rasa_nlu#859]
**Rasa NLU version**:
0.11.3
**Issue**:
I'm confused by the way the RasaNLUConfig is used.
Probably most of the users stick with one specific way of using RASA and don't think about this but after using different ways I think it's somehow inconsistent and not self-explanatory.

The configuration file can have following parameters:
https://nlu.rasa.ai/config.html
```json
{
  "project": null,
  "fixed_model_name": null,
  "pipeline": [],
  "language": "en",
  "num_threads": 1,
  "max_training_processes": 1,
  "path": "projects",
  "response_log": "logs",
  "storage": null,
  "config": "config.json",
  "log_level": "INFO",
  "port": 5000,
  "data": null,
  "emulate": null,
  "log_file": null,
  "mitie_file": "data/total_word_feature_extractor.dat",
  "spacy_model_name": null,
  "token": null,
  "cors_origins": [],
  "aws_endpoint_url": null,
  "max_number_of_ngrams": 7,
  "duckling_dimensions": null,
  "duckling_http_url": null,

  "ner_crf": {
    "BILOU_flag": true,
    "features": [
      ["low", "title", "upper", "pos", "pos2"],
      ["bias", "low", "word3", "word2", "upper", "title", "digit", "pos", "pos2", "pattern"],
      ["low", "title", "upper", "pos", "pos2"]],
    "max_iterations": 50,
    "L1_c": 1,
    "L2_c": 1e-3
  },

  "intent_classifier_sklearn": {
    "C": [1, 2, 5, 10, 20, 100],
    "kernel": "linear"
  }
}
```
[Here](https://nlu.rasa.ai/tutorial.html#training-a-new-model-for-your-project) the training process relies on many parameters in the .json file e.g:
pipeline, data, path, project
but also has them as direct/additional arguments which adds/overwrites the values of the json file
- -p --pipeline
- -o --path
- -d --data

```bash
$ python -m rasa_nlu.train -c sample_configs/config_spacy.json
```

But [here](https://nlu.rasa.ai/python.html#training-time) ([code](https://github.com/RasaHQ/rasa_nlu/blob/0.11.x/rasa_nlu/model.py)) it only uses the pipeline and the language parameter and ignores any other existing parameter.
For example, the persist arguments are optional but their default values don't consider any existing parameter of the config object which has been passed.

demo-rasa.json contains "fixed_model_name": "myFixedModel"
trainer.persist(..., fixed_model_name = None)
-> "myFixedModel" isn't considered at all.

In my opinion, the trainer class should take the values from the config file as default if they are available.

```py
from rasa_nlu.converters import load_data
from rasa_nlu.config import RasaNLUConfig
from rasa_nlu.model import Trainer

training_data = load_data('data/examples/rasa/demo-rasa.json')
trainer = Trainer(RasaNLUConfig("sample_configs/config_spacy.json"))
trainer.train(training_data)
model_directory = trainer.persist('./projects/default/')  # Returns the directory the model is stored in
```

Í hope my issue is clear enough for some feedback.

**Comment by tmbo** [comment]
Yes, that is a very good point.

I have been thinking about the configuration handling for a while and I agree. There is two things I have in mind which should fix this:
- split the configuration in configuration keys specific to a model (kind of a training configuration) and arguments used to configure any non model related things (like ports, project directory, token,... )
- read defaults from config everywhere (I think this is exactly what you are proposing as well)

I just didn't get around to do that yet.

**Comment by Le-Fix** [comment]
I thought about the same two points you mentioned.

Those things are somewhat independent and I'd like to have them in seperate files:
1 Pipeline setup (and component setup)
2 Training Data
3 Training Configuration (reference 1, reference 2, target folder, num_threads,...)
4 Trained Model (exisiting metadata.json which consists of: 1, reference 2 and some training log)
5 Model Serving (reference 4, token, port, logfile, emulate,...)

However, I just started using RASA Core and Nlu and probably don't see the big picture yet.

**Comment by tmbo** [comment]
You are spot on. This is the clean separation I'd like to move to - just to many different configuration parameters have been added over time that are unrelated and serve different use cases.

**Comment by tmbo** [comment]
I'll close this issue in favor of the already existing #610

**Comment by Le-Fix** [comment]
For sure. I didn't see that there already is a similar issue.
