### ISSUE TITLE
CLA 2

### ISSUE THREAD

**Issue by amn41** [RasaHQ/rasa_nlu#863]
@jinhong-  could you please email dominik@rasa.com ? 

Thanks for your contributions in the early days of Rasa NLU :) 
We're just doing a bit of housekeeping and need you to sign the CLA for your contributions. 

@DominikRos @alexweidauer

**Comment by alexweidauer** [comment]
@jinhong- have you seen this? :)

**Comment by jinhong-** [comment]
Hey yes thanks for the reminder. Been running low on time lately. Will send out the email soon

**Comment by tmbo** [comment]
Thanks a lot :+1:
