### ISSUE TITLE
OSError: [Errno 13] at installation of rasa_nlu on Ubuntu with pip

### ISSUE THREAD

**Issue by jganseman** [RasaHQ/rasa_nlu#865]
**Rasa NLU version** : 0.11.3
**Used backend / pipeline** : spacy_sklearn
**Operating system** : Lubuntu (Ubuntu 16.04.3 LTS) in VirtualBox 5.2.2

**Issue**: This is a list of bumps that I encountered when following the tutorial at https://core.rasa.ai/tutorial_basics.html . It's not a real bug, but rather a gap in the installation documentation. Putting it on Github so others can hopefully be helped with these workarounds! I'm using a clean install on an Ubuntu based VM with pip, without virtualenv or conda (this VM is meant for rasa experiments only).

1. 

Problem: `pip install rasa_nlu[spacy]` leads to a stacktrace and subsequent error: `OSError: [Errno 13] Access denied: '/usr/local/lib/python2.7/dist-packages/pycrfsuite'`

Solution: use `pip install --user rasa_nlu[spacy]` (or sudo, but I hear sudo is discouraged.)

Remarks: If `python -m spacy validate` results in `No module named spacy`, on my machine these were caused by accidentally having installed 2 versions of pip : one with `apt-get` and one with `easy_install`, that apparently were conflicting. Uninstalling the apt-get one solved it for me.

2. 

Problem: `python -m spacy download en_core_web_md` results in an error `Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-1lsR8q-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-UDEume-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-1lsR8q-build/ `

Solution: use `sudo python -m spacy download en_core_web_md`

Remarks: the subsequent `python -m spacy link en_core_web_md en` did not require sudo on my machine.

3.

Problem: `python -m rasa_core.train -s data/stories.md -d domain.yml -o models/dialogue --epochs 300` leads to `/usr/bin/python: No module named rasa_core`

Solution: `pip install --user rasa_core` (the user flag to avoid the OSError described above)

Remarks: this problem was likely an offshoot of the multiple pips hiccup described in the first remark

**Comment by tmbo** [comment]
Thanks a lot for sharing these insights - search machines will hopefully make sure others find them.

I don't see anything we can improve there in the docs as I think the pip issues are system specific. Let me know if there is anything we can add / change (or even better: directly create a PR with the changes :) )
