### ISSUE TITLE
Handling of multiple sentences

### ISSUE THREAD

**Issue by ctrado18** [RasaHQ/rasa_nlu#866]
How does Rasa handles multiple sentences?

Is there a way to do intent classfication with more than one sentence or possible a text?

That's a typical problem for chatbots when a user gives more than one sentence as input.

**Comment by tmbo** [comment]
Right now one message gets assigned one intent. This means that the model takes all sentences into account and classifies the whole message as one intent. I think there is also an enhancement discussion to support splitting sentences into multiple messages to allow annotation of multiple intents
