### ISSUE TITLE
perhaps load_rasa_data method in converters.py file receives file name array that will be better for user to manage their train data.

### ISSUE THREAD

**Issue by terryKing1992** [RasaHQ/rasa_nlu#867]
this is just a feature. when I use rasa_nlu  module to train my ```nlu train data```, I assume there are several intents such as ```greet``` ```goodbye``` ```book_flight``` ```request_flight```. perhaps separate those intent train datas into different file will be better to manage. any idea?

**Comment by tmbo** [comment]
Yes that should be possible, if you pass in the directory instead of a single file it should use all files within that directory to train the model. At the moment there is no way to specify multiple files directly (either specify a folder or one file).

**Comment by terryKing1992** [comment]
thanks a lot for your reply! but in fact, if i pass in the directory, in the internal of load_data method, there is a return statement like as bellow ``` return load_rasa_data(files[0])```, so maybe now this framework can't support to use all files within the directory to train the model？ I don't know what i think is right？

**Comment by tmbo** [comment]
should be fixed as part of http://nlu.rasa.ai/config.html?highlight=multiple#data
