### ISSUE TITLE
NER with a list/gazetter

### ISSUE THREAD

**Issue by ctrado18** [RasaHQ/rasa_nlu#868]
I try to develop a domain specific chatbot and want to use rasa. 

What are the current possibilities/methods to use a customized list with entities or gazetters for NER?

That is for text like: "How much does [product XY] costs?
for a pharmaceutical product for example.

Is the current state of rasa only such that we need to copy all sentences for one entity replaced with all other entities? 

I thougt to use the intent classifier without NER and using a gazetter /list. So I would like to have an intent with entties found in some list.

I would really appreciate any help to handle properly NER in Rasa or where I can find any intersting similiar applications.

I know that a gazetter is not supported right now #773 .

But what are ways to handle such things in rasa? I mean such thing with NER are standard for chatbots for which RASA is the primary usage, right?

**Comment by poorni19** [comment]
@ctrado18 If my understanding is correct, 
"How much does[product xyz] costs ? " you are asking if you have 'n' different product names do we need to train the same sentence for all n product names like [xx,xy,yy,etc].

**Comment by ctrado18** [comment]
@poorni19  Yes thats right. What I am looking for is a way to work with gazetters. It has not to be a feature for the CRF. But just tag the name if it is in a list with the proper class (eg. after the ner_crf component).

Or, what are the best practices for stiff like that. I mean, thats a standard task for developing a chatbot like for ecommerce?

**Comment by tmbo** [comment]
@ctrado18 right now the system is more focusing on generalisation: So you do not need to list all possible entity values to get them trained, the ner should also recognize entities it has not seen during training in that specific sentence.

Nevertheless, this is a good use case and there is an open PR #822 that is working on supporting this better.

**Comment by tmbo** [comment]
More discussion on this topic can be found here as well:  #773
