### ISSUE TITLE
Relation between intents and entities

### ISSUE THREAD

**Issue by MariamMohamedFawzy** [RasaHQ/rasa_nlu#871]
**Rasa NLU version** `0.11.3`

**Used backend / pipeline** `mitie with sklearn`

**Operating system** (ubuntu):

I have noticed that the intent classifier is trained then the entities classifier is trained, but there may be a correlation/relation between some intents and entities, how is this case handled if both are trained separately?

**Comment by tmbo** [comment]
Currently, they are separate classifiers that do not share any information. More discussion about that can be found here #732
