### ISSUE TITLE
Allow adding custom class (Extractor / Classifier) to Pipeline from config.json

### ISSUE THREAD

**Issue by r-wheeler** [RasaHQ/rasa_nlu#873]
The issue [here](https://github.com/RasaHQ/rasa_nlu/issues/600)
mentions enabling the ability to add any class to the pipeline without having to modify the register.py file. This would be a very useful feature as rasa could be extended without needing to modify the source. 

Looking at [this](https://github.com/RasaHQ/rasa_nlu/blob/1bf2680cc8903c5c8bb0d9066552719923b74fcf/rasa_nlu/config.py#L94) line in the master branch: 

This does not seem possible. 

**Content of configuration file** (if used & relevant):
```json

```

**Comment by tmbo** [comment]
This line is only run when you pass in a predefined pipeline, e.g. `"pipeline": "spacy_sklearn"`. If you want to add custom components, you need to specify all the components an array, e.g. `"pipeline": ["nlp_spacy", "mycustom.component.MyComponent", "tokenizer_spacy", "intent_entity_featurizer_regex", "intent_featurizer_spacy", "ner_crf", "ner_synonyms",  "intent_classifier_sklearn"]`

where `mycustom.component.MyComponent` would be your component. You can place that anywhere in the pipeline (I mean depends a bit on what you depend and trying to do but in general).

**Comment by r-wheeler** [comment]
Ah missed they type check [here](https://github.com/RasaHQ/rasa_nlu/blob/1bf2680cc8903c5c8bb0d9066552719923b74fcf/rasa_nlu/config.py#L92)

and following all the methods gets me to 
https://github.com/RasaHQ/rasa_nlu/blob/1bf2680cc8903c5c8bb0d9066552719923b74fcf/rasa_nlu/registry.py#L127

Which sounds like it does exactly what I need. 

Thanks! 

Maybe adding a bit to the docs on this would help.

**Comment by ctrado18** [comment]
@tmbo If I just use "pipeline": "ner_crf" or "pipeline": ["nlp_spacy", "ner_crf", "ner_synonyms"]

ner_crf is not recognized as a component? How can I find out that ner_crf is been used? I use the developer version with also still gives this #846

**Comment by tmbo** [comment]
I don't think this is related to this issue, I think the original question has been answered.
