### ISSUE TITLE
Using fastText classification model

### ISSUE THREAD

**Issue by yfletberliac** [RasaHQ/rasa_nlu#876]
Hi, I would like to use [fasttext classification model](https://fasttext.cc/docs/en/supervised-tutorial.html) with `rasa_nlu.components.Component`, is the implementation of such a new component is already in the roadmap, or not?
Thanks,
Yannis

**Comment by tmbo** [comment]
Since spacy support loading fasttext vectors (and since we need a tokenizer anyway) - I don't think there is a need for a separate component. Idea is to add instructions to the docs explaining how to add fasttext vectory using spacy, but that didn't happen yet.

Explanations can be found here: #869

**Comment by omerarshad** [comment]
there is difference betweetn FASTTEXT classification models and fasttext vectors. Instead of SVM for intent classification what if i want to use fasttext as a classifier?

**Comment by yfletberliac** [comment]
Hi @tmbo, @omerarshad,
I took some time to create the component and what's needed for using FastText library **as a classifier** (and not as word embeddings), [here](https://github.com/RasaHQ/rasa_nlu/pull/926) is the link to the PR.
Please feel free to contribute to it 👍
