### ISSUE TITLE
Cannot import name load_data

### ISSUE THREAD

**Issue by arshidkv12** [RasaHQ/rasa_nlu#886]
**Python :Python 2.7.12**

**Rasa NLU version** ` 0.7.2`:

**Used backend / pipeline : `spacy_sklearn`**

**Operating system : Linux**

**Issue**:
` File "bot.py", line 70, in train_nlu
    from rasa_nlu.training_data import load_data
ImportError: cannot import name load_data
`

I tried with restaurant example bot. But I received following error.
**Error:-** 

 **code : -** 
`from rasa_nlu.converters import load_data
    from rasa_nlu.config import RasaNLUConfig
    from rasa_nlu.model import Trainer`

**Comment by wrathagom** [comment]
Are you really running Rasa 0.7.2? If so it appears you are running a really old version of Rasa NLU. Do you need to be running that version? If you install from pip today you would get 0.11.3 and can follow the tutorial here: http://rasa-nlu.readthedocs.io/en/stable/python.html
