### ISSUE TITLE
Rasa NLU ChatBot

### ISSUE THREAD

**Issue by hiringbees** [RasaHQ/rasa_nlu#887]
Is there any website uses ChatBot developed in RASA NLU?. Kindly reply with the link. Need to check the performance

**Comment by wrathagom** [comment]
@amn41 @tmbo do you know of any sites using Rasa NLU that someone can interact with?

@hiringbees why not follow the tutorial and run it locally for testing?

**Comment by tmbo** [comment]
Yes, but there is no list I can publicly share, but I think this is a great question for the gitter channel as there are a lot of developers there happy to share links to their publicly accessible bots.
