### ISSUE TITLE
How to set default response?

### ISSUE THREAD

**Issue by Selvaganapathi06** [RasaHQ/rasa_nlu#889]
This tutorial is awesome. I have a simple question? how to add default bot responses? example : i have set of intents and questions and answers, if user enter new questions i will send message "sorry, i cant understand". how to set default messages?.

**Comment by wrathagom** [comment]
@Selvaganapathi06 I replied to you on Gitter. This either sounds like a Rasa Core use case or you can look at the blog post I mentioned on Gitter. If you still have questions feel free to re-open this issue or create one on the Rasa Core repo.
