### ISSUE TITLE
Customized Pipeline "spacy_sklearn" + "ner_duckling"

### ISSUE THREAD

**Issue by pawan9489** [RasaHQ/rasa_nlu#892]
I am facing Java memory error while running with customized pipeline by adding "ner_duckling".
If I remove "ner_duckling" and just use "spacy_sklearn" it is working fine.

rasa-nlu==0.11.3
spacy==2.0.9
duckling==1.7.3

```
INFO:rasa_nlu.utils.spacy_utils:Trying to load spacy model with name 'en_core_web_lg'
INFO:rasa_nlu.components:Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en_core_web_lg'.
Java HotSpot(TM) 64-Bit Server VM warning: INFO: os::commit_memory(0x0000000089a00000, 32505856, 0) failed; error='The paging file is too small for this operation to complete' (DOS error/errno=1455)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 32505856 bytes for Failed to commit area from 0x0000000089a00000 to 0x000000008b900000 of length 32505856.
# An error report file with more information is saved as:
# S:\Learnings\Python\RASA_NLU\test\hs_err_pid16272.log

```
```
{
    "pipeline": ["nlp_spacy", "tokenizer_spacy", "intent_entity_featurizer_regex", "intent_featurizer_spacy", "ner_crf","ner_duckling", "ner_synonyms",  "intent_classifier_sklearn"],
    "path" : "./projects",
    "data" : "./data/my_intents",
    "spacy_model_name": "en_core_web_lg"
}
```
I need duckling since I deal with lot of date and time stamp related messages.
How to add "ner_duckling" at the end of "spacy_sklearn" pipeline?

**Comment by amn41** [comment]
I suspect your machine is running out of memory from loading a spaCy model (can be a couple Gb) plus booting a jvm at the same time. 
You might want to think about running the new haskell duckling in a docker container and using the `ner_duckling_http` component instead

**Comment by pawan9489** [comment]
@amn41 Thanks it worked. I just replaced "ner_duckling" with "ner_duckling_http" (haskell duckling).
When I saw the "D:\Program Files\Python36\Lib\site-packages\duckling\wrapper.py"

```
def __init__(self,
                 jvm_started=False,
                 parse_datetime=False,
                 language=Language.ENGLISH,
                 minimum_heap_size='128m',
                 maximum_heap_size='2048m'):
```

I changed the maximum head size to 6GB

```
def __init__(self,
                 jvm_started=False,
                 parse_datetime=False,
                 language=Language.ENGLISH,
                 minimum_heap_size='128m',
                 maximum_heap_size='6144m'):
```

Now I can use "ner_duckling" component without any issue.

My File pipeline is 

`"pipeline": ["nlp_spacy", "tokenizer_spacy", "intent_entity_featurizer_regex", "intent_featurizer_spacy","ner_crf", "ner_synonyms" , "ner_duckling", "intent_classifier_sklearn" ]`

**Comment by amn41** [comment]
http://nlu.rasa.ai/faq.html?highlight=warning#why-am-i-getting-an-undefinedmetricwarning

**Comment by pawan9489** [comment]
@amn41 Thanks a Lot.
