### ISSUE TITLE
How are the features created for the intent_sklearn classifier?

### ISSUE THREAD

**Issue by ctrado18** [RasaHQ/rasa_nlu#893]
Hey,

i asked this now many times on gitter for spacy and rasa, too. But I have no answer yet to this simple question.

As far as I have understood, the only position where the features are created in the code for the spacy featurizers is the following:

```
def features_for_doc(doc):

    """Feature vector for a single document / sentence."""

    # type: Doc -> np.ndarray

    return doc.vector
```

So, this doc.vector is the only thing which is used then for intent classification? What ML-Algorithms are used then in spacy to create this array of numbers?

**Comment by tmbo** [comment]
The doc vector is a trained embedding. There are different ways to train them and whcih one works best depends on the properties of the dataset (e.g. how many unique words). Common methods are word2vec, glove, fasttext. The vectors are fed into an SVM.

**Comment by ctrado18** [comment]
@tmbo Thank you! I was confused because I thought word vectosr should be continous and between 0 and 1...

**Comment by nggary** [comment]
@tmbo You said that there are different ways to train the doc vector, what way did rasa nul choose?

**Comment by akelad** [comment]
it depends which pipeline you use, spacy for example has GloVe vectors.
