### ISSUE TITLE
Question: How to include responses for small talk in training data?

### ISSUE THREAD

**Issue by pawan9489** [RasaHQ/rasa_nlu#896]
**Rasa NLU version**: 0.11.3

**Used backend / pipeline**: spacy_sklearn

**Operating system**: Windows

**Issue**:

**Content of configuration file** (if used & relevant):

In API.AI I can give multiple responses to each question of small talk.
In RASA is there any way to hard code responses for small talk in the training data itself?

I think it would be better if we can provide the response of some messages like small talk with in the response json of RASA_NLU.server calls, instead of having multiple if/else in the backend code to handle the intents.

**Comment by wrathagom** [comment]
Rasa NLU just handles intents/entities. If you want Dialogue you should take a look at [Rasa Core](https://github.com/RasaHQ/rasa_core)
