### ISSUE TITLE
Missing dependencies in setup of tutorial.

### ISSUE THREAD

**Issue by Johnz86** [RasaHQ/rasa_nlu#897]
**Rasa Core version**:
rasa-core (0.8.3)
rasa-nlu (0.11.3)

**Python version**: 
Python 3.6.4

**Operating system** (windows, osx, ...):
windows 7 64 bit

**Issue**:
I have tried to follow existing tutorial "https://nlu.rasa.ai/master/tutorial.html" and docs with virtualenv environment.  To get it working I needed to run following commands:

```
mkdir chatbot
cd chatbot
virtualenv CSMLSara
.\CSMLSara\Scripts\activate.bat
pip install --upgrade https://pypi.python.org/packages/56/7d/a0e3ae33e8034be8e7d6b99a7f512c6e71b2180603fc3e0cfb6047b7374f/tensorflow-1.6.0-cp36-cp36m-win_amd64.whl#md5=37cfe2299a761c874cc458e6f60cf45d
pip install rasa_core
pip install rasa_nlu
pip install rasa_nlu[spacy]
python -m spacy download en_core_web_md
python -m spacy link en_core_web_md en
python -m spacy validate
python -m rasa_nlu.train -c sample_configs/config_spacy.json
python -m rasa_nlu.server -c sample_configs/config_spacy.json
pip install pypiwin32
python -m rasa_nlu.server -c sample_configs/config_spacy.json
```
The sample files are from the repository https://github.com/RasaHQ/rasa_nlu.
 When I installed the dependencies the installation of core failed because tensorflow was missing.
Pypiwin32 was a required dependency but it was not installed along the modules.
Did I do anything wrong, or the docs require update?

**Comment by tmbo** [comment]
I think `Pypiwin32` is not related to rasa, but more to a proper setup of python on windows. The tensorflow issue occurs because for some reason they didn't release a version for windows, but there is already another open issue to upgrade the tensorflow dependency to fix this.

**Comment by tmbo** [comment]
If you feel the docs need some update in some places to make the installation easier, i'd happy to take a look at an improvement PR :)
