### ISSUE TITLE
Context Handling

### ISSUE THREAD

**Issue by Selvaganapathi06** [RasaHQ/rasa_nlu#901]
i have built in bot rasa NLU. Can you please explain how handle context in NLU? i am not used rasa core.

**Comment by tmbo** [comment]
Rasa NLU isn'T build to handle context. If you want to do that, you need to take a look at the tutorials of Rasa Core: https://core.rasa.com

**Comment by Selvaganapathi06** [comment]
Rasa Core: https://core.rasa.com the given link is not working, please check and confirm. Now i used rasa core only.  how to handle context? how to use tracker,slot in my custom chatbot? please share examples

**Comment by auzair92** [comment]
The Rasa Core documentation has several examples that explain terminology and usage of the framework. Check out the [Tracking Conversation State](http://core.rasa.com/state.html) section for details about tracking context.
