### ISSUE TITLE
how to know that cuda gpu is used while training?

### ISSUE THREAD

**Issue by nickppbd** [RasaHQ/rasa_nlu#910]
**Rasa NLU version** (e.g. `0.7.3`):0.11.3

**Used backend / pipeline** :spacy_sklearn

**Operating system** (windows, osx, ...):ubuntu 16.04

**Issue**:
how to know that cuda gpu is used while training?
I installed like below
```
pip install rasa_nlu
pip install rasa_nlu[spacy]
python -m spacy download en_core_web_lg
```
No need to `python -m spacy link en_core_web_lg en`(linking success message showed up, but I did it after a while. But linking success message was the same as not using `python -m spacy link en_core_web_lg en`

I read https://spacy.io/usage/#gpu
i did `python -c "import thinc.neural.gpu_ops"` and there is no messages.

Is it using my gpu supporting cuda 9.0 ?(for sure I did `CUDA9=1 pip install thinc==6.10.2`after a while ([link](https://github.com/explosion/thinc/releases))

How can I figure it out?

I used `nvidia-smi` , but training is too short to check.

Help me please.

**Comment by wrathagom** [comment]
None of the Rasa NLU pipeline components can utilize your GPU. CPU only.

**Comment by nickppbd** [comment]
Then, there is no chance to support GPU?

**Comment by wrathagom** [comment]
@tmbo that's a question for you, though my understanding is it's a no.

**Comment by tmbo** [comment]
Right now, there is no component that will benefit from a GPU. We are working on tensorflow / keras models though - training them can be speed up using GPU's, so stay tuned

**Comment by zahidirfan** [comment]
Can RASA use multiple cores? using tensorflow settings like op_inter_threads ? op_intra_threads?

**Comment by dhdez-blife** [comment]
It´s 2024 and there is no advence in the topic. We need tools to provide us to work using CUDA.
