### ISSUE TITLE
Special character in log file

### ISSUE THREAD

**Issue by lomkju** [RasaHQ/rasa_nlu#911]
**Rasa NLU version:**
12.01a

**Used backend / pipeline:**
mitie-sklearn

**Operating system** :
Ubuntu 17.10

**Issue**:
The log file seems to have a special character prefix for each request made to rasa nlu. The format seems to be trouble some when trying to parse the log file with fluentd.

**Log file content** :
{"user_input": {"entities": [{"start": 0, "extractor": "ner_mitie", "end": 11, "value": "create baba", "entity": "Action.Goobye"}], "intent": {"confidence": 0.5832902114274395, "name": "goodbye"}, "text": "create baba", "intent_ranking": [{"confidence": 0.5832902114274395, "name": "goodbye"}, {"confidence": 0.2710270896260183, "name": "affirm"}, {"confidence": 0.14568269894654243, "name": "greet"}]}, "log_namespace": "rasa_nlu.data_router", "log_level": {"__class_uuid__": "02e59486-f24d-46ad-8224-3acdf2a5732a", "name": "info"}, "log_source": null, "log_format": "json", "project": "techforce", "log_logger": {"unpersistable": true}, "model": "a1", "log_time": 1521182982.524715}
{"user_input": {"entities": [{"start": 0, "extractor": "ner_mitie", "end": 11, "value": "create baba", "entity": "Action.Goobye"}], "intent": {"confidence": 0.5832902114274395, "name": "goodbye"}, "text": "create baba", "intent_ranking": [{"confidence": 0.5832902114274395, "name": "goodbye"}, {"confidence": 0.2710270896260183, "name": "affirm"}, {"confidence": 0.14568269894654243, "name": "greet"}]}, "log_namespace": "rasa_nlu.data_router", "log_level": {"__class_uuid__": "02e59486-f24d-46ad-8224-3acdf2a5732a", "name": "info"}, "log_source": null, "log_format": "json", "project": "techforce", "log_logger": {"unpersistable": true}, "model": "a1", "log_time": 1521183744.458469}
{"user_input": {"entities": [{"start": 0, "extractor": "ner_mitie", "end": 11, "value": "create baba", "entity": "Action.Goobye"}], "intent": {"confidence": 0.5832902114274395, "name": "goodbye"}, "text": "create baba", "intent_ranking": [{"confidence": 0.5832902114274395, "name": "goodbye"}, {"confidence": 0.2710270896260183, "name": "affirm"}, {"confidence": 0.14568269894654243, "name": "greet"}]}, "log_namespace": "rasa_nlu.data_router", "log_level": {"__class_uuid__": "02e59486-f24d-46ad-8224-3acdf2a5732a", "name": "info"}, "log_source": null, "log_format": "json", "project": "techforce", "log_logger": {"unpersistable": true}, "model": "a1", "log_time": 1521183750.915352}

**UPDATE :** It is a record separator  mentioned by IETF in this draft https://tools.ietf.org/id/draft-hallambaker-jsonl-00.html

Currently fluentd cannot process the log file like this so we found out the twisted logger has an option to specify the record separator.

We made the change to data_router.py with the code below and it generated logs without the separator and so that it starts working with fluentd

`            query_logger = Logger(observer=jsonFileLogObserver(
                io.open(response_logfile, 'a', encoding='utf8'), recordSeparator=''),
                namespace='query-logger')`

Best,
Arjun

**Comment by tmbo** [comment]
I guess (and judging by the jsonl draft) a newline is fine as a separator. Do you mind creating a PR to change this?

**Comment by wrathagom** [comment]
Addressed by #957 thanks @lomkju
