### ISSUE TITLE
Misclassification: Right intent but wrong entity

### ISSUE THREAD

**Issue by ctrado18** [RasaHQ/rasa_nlu#914]
Hi,

I have some training examples for entity1 in form of [word]+[Mix of numbers and letters]
and for another entity2 just numbers like "12.4".

Now if I parse just "12.6" eg. it is recognized as entity1, though it should be entity2 of course!

How can I prevent these misclassifications for entities?

**Comment by tmbo** [comment]
You probably don't have enough training examples. Furthermore, do they occur in the same sentence structure? If so, this might be a reason why they get confused.
