### ISSUE TITLE
Haskell Duckling Bindings for python 

### ISSUE THREAD

**Issue by r-wheeler** [RasaHQ/rasa_nlu#915]
Found any interest in ditching JVM based duckling and using a python lib with C bindings to underlaying haskell code? I have a working concept for a few dimensions but not full API coverage.

**Comment by tmbo** [comment]
I think that's a great idea. I don't think we will keep the clojure / jvm version around for to long anymore. I mean there is the http one that works just fine with the haskell duckling, but I guess direct calls from python code would be nice as well.

**Comment by amn41** [comment]
so cool! can't wait to try it out :)

**Comment by wrathagom** [comment]
@souvikg10 did you get the http one working, as far as I am aware it's been on pypi for awhile now.

**Comment by souvikg10** [comment]
Oh yeah, I have http connection now. There were some issues but fixed 0.12.1 
Thanks

**Comment by parthsharma1996** [comment]
@r-wheeler Any updates on the python package?

**Comment by akelad** [comment]
@r-wheeler any updates?
