### ISSUE TITLE
where the logs conversion chat is stored for retraining?

### ISSUE THREAD

**Issue by DhruvMevada** [RasaHQ/rasa_nlu#917]
As mention in the docs https://nlu.rasa.ai/closeloop.html
where the log files of conversion are stores ?

**Comment by tmbo** [comment]
There is a configuration value where you can configure that, it is called `response_log`: https://nlu.rasa.com/config.html#response-log

**Comment by DhruvMevada** [comment]
Yes I tried that, but still log file of conversion is not generates.
configuration file:

{
  "pipeline": "spacy_sklearn",
  "path" : "./models/nlu",
  "data" : "./data/nlu.md",
  "language": "en",
  "response_log": "logs/",
  "log_level": "INFO",
  "log_file": "./logs"
}

**Comment by tmbo** [comment]
We changed the configuration in the latest master. Would be good if you could try there. Otherwise I'd suggest to remove the trailing slash from `response_log: 'logs/'`

**Comment by tmbo** [comment]
I'll close this for now, please let us know if you have any further questions.

**Comment by gauravbrills** [comment]
@tmbo  it would be great if we can have the server also push logs to the cloud say aws s3 like it does for models .

**Comment by mminchev** [comment]
Absolutely, pushing response logs to AWS S3 would be very useful.

**Comment by sandeepsuvit** [comment]
Hope this helps someone. If you run the server using the following command the logs file will be generated under the project root `logs` folder

```
python -m rasa_nlu.server --path projects --response_log logs
```
