### ISSUE TITLE
How to decrese false positive for  a particular intent ?

### ISSUE THREAD

**Issue by Sanjeev2487** [RasaHQ/rasa_nlu#919]
Hi, in my case all the text with digits gets classified into `settempreture` intent with very high confidence. I agree while training all sentences has digit available (`set temperature to <integer>`, `increse ac temp. by <twenty four>` etc.). How can I go about handling cases such as `one two three four` it detects `one two` and `three four` as two `temperature` entities with confidence 0.87 of `settemperature`. I'm using `spacy_sklean` as my pipeline.

**Comment by tmbo** [comment]
You should add a couple examples to the training data where numbers are present and not labeled with `settempreture` - your training data needs to reflect the data the model is supposed to handle later. If you don't provide any examples that are similar to these user messages, the model won't know how to classify them.

**Comment by akelad** [comment]
Hi @Sanjeev2487 
I'm not sure what you need a `None` intent for? Can you provide a bit more detail of the intents and entities you have in your bot

**Comment by Sanjeev2487** [comment]
Hi @akelad ,
A `None` entity was needed to decreases the number of false positives. As RASA always classifies any utterance in one of the intents which has been trained. When you test it with any out of domain text such as `any garbage  utterance` it will map it to one of the intents  which should not happen.

**Comment by akelad** [comment]
Can you please provide examples of your NLU data? (ideally in markdown format)

**Comment by Sanjeev2487** [comment]
Here are some of the examples:
1. `set the temperature of ac to twenty` > `setvalue`
2. `increase the ac by one degree` > `increasevalue`
3. `check one two three` > `None`
and when I will test it with utterance like similar utterances as one the confidence is not very good.

**Comment by akelad** [comment]
How many examples do you have per intent? Also, if your `None` intent is too similar (or any intents for that matter), then yes there will be intent confusion. Try running the evaluate script on your data to see which intents are getting confused etc.

**Comment by Sanjeev2487** [comment]
I understand that but what if intent confusion is unavoidable like I have 'TurnOn' and 'TurnOff' intent which has almost similar sentences.  Is there a standard way to handle such intents ?

**Comment by akelad** [comment]
I mean - have you run the evaluate script on your data to see how much intent confusion there is? I'd need some more examples of your training data to be able to give you more advice

**Comment by akelad** [comment]
I'm afraid that doesn't help much alone - I can see some intents are getting confused - the numbers 10 and 11. but generally seems to be doing well. In terms of general advice: if you have very similar intents, sometimes it's useful to merge them and distinguish between them with entities instead.

**Comment by Sanjeev2487** [comment]
I have modified my data somewhat for intents it was getting confused and no. of wrong classification decreased.  How ever now, after going through manually on some mis-classified utterances I see that sentences having word `closed` are classified to `Open` intent instead of `Close`.  That means it is not able to handle different forms of verb as such. My current pipeline is `spacy_sklearn`.  
I can always add `closed` to training data, but are there other pipelines or some custom pipelines I should  explore to handle more varieties of  verb ?

**Comment by akelad** [comment]
it is still able to compute the similarity between `close` and `closed`, but yes you might need to add some examples using this to your training data. it really depends on what sort of sentences you have in your training data for both intents.

**Comment by wrathagom** [comment]
@Sanjeev2487 were you able to resolve this? I may suggest trying the new tensorflow embedding pipeline.
