### ISSUE TITLE
supervised embeddings in Rasa NLU

### ISSUE THREAD

**Issue by amn41** [RasaHQ/rasa_nlu#920]
Use an embedding based algorithm, training the embedding on the NLU data, instead of pretrained word vectors. Allows for smaller models and customization (e.g. out of vocab words on standard dictionaries)

**Comment by Ghostvv** [comment]
https://github.com/RasaHQ/rasa_extensions/pull/49

**Comment by Ghostvv** [comment]
https://github.com/RasaHQ/rasa_nlu/pull/943
