### ISSUE TITLE
Rasa NLU is not recognising entities ? 

### ISSUE THREAD

**Issue by dilipbobby** [RasaHQ/rasa_nlu#923]
**Rasa NLU version** (e.g. `0.7.3`):

**Used backend / pipeline** (`["nlp_spacy", "tokenizer_spacy", "intent_featurizer_spacy", "ner_crf", "ner_synonyms",  "intent_classifier_sklearn", "ner_duckling"]):

**Operating system** (windows, osx, ...):

**Issue**:

text: The world's tallest restaurant in the **Burj Khalifa** offers what.
 intent : restaurant_search and 
entity should be  **Burj Khalifa**
I trained with single example with entity as Burj Khalifa many other examples tells the intent as restaurant_search.
I'm getting the correct intent but unable to identify the Burj Khalifa as the entity.do I need add more examples with the name Burj Khalifa as entity ? 
I'm making use of ner_crf in config with other pipelines mentioned above.

Please suggest me a way to identify the entities like  **Burj Khalifa** using rasa NLU 

thanks

**Comment by tmbo** [comment]
I don't know any statistics about your training data, but I guess you need a couple more examples to properly train the NER model. These don't necessarily need to contain this specific entity as a value, but a couple more examples with it won't hurt.

**Comment by dilipbobby** [comment]
thanks. I'm closing the ticket ! If any problem I will reopen it thanks

**Comment by dilipbobby** [comment]
I added examples like 1) 4 happy Christmas ,2) Christmas wishes to your family ... and trained the model  able to find the entity : festival : Christmas but when tried out a) happy x-mas or b) x-mas wishes to your family type examples, model I prepared is not recognising  x-mas as festival entity .Do need to add few more examples with x-mas and train the model ? Does it make any sense to do so ?

**Comment by dilipbobby** [comment]
https://stackoverflow.com/questions/46486418/my-model-cant-find-any-entities this linked 2 comment helped me :)

**Comment by akelad** [comment]
if there's no examples of "x-mas" as an entity, then yes you need to add some.

**Comment by dilipbobby** [comment]
Then what ever entities I trained rasa is able to identify only those entities. Is it Right ?

**Comment by wrathagom** [comment]
Rasa can generalize beyond provided examples, though the examples have to be representative of a wide spectrum of possibilities. but in this case `x-mas` is too different from `Christmas` for it to generalize.

Let us know if you are still having trouble.

**Comment by jainsaurav22** [comment]
The same problem is what i am facing, i am not able to look for the entities that are not in the training data.

**Comment by webdev-rohit** [comment]
Hi @jainsaurav22 , I have the same problem. I am not able to look for the entities that are not in the training data. Were you able to solve it?
