### ISSUE TITLE
Skype integration with RASA

### ISSUE THREAD

**Issue by Rahul6818** [RasaHQ/rasa_nlu#925]
Is there any way to integrate RASA with skype or any other communication channel like - facebook, telegram, kik...

**Comment by tmbo** [comment]
Rasa NLU doesn't provide implementations for the communication channels. NLU is only part of what you need to build a bot, so you can either take a look at using Rasa Core together with NLU (which will provide you with input channels for facebook and telegram and the possibility to create your own). Alternatively, I think there are other services out there that will allow you to connect to the input channel (e.g. botkit).
