### ISSUE TITLE
Text falling in multiple intents

### ISSUE THREAD

**Issue by anupam20sep** [RasaHQ/rasa_nlu#931]
I am building a chabot using Rasa NLU and Rasa core. The issue is how to proceed with the text which can have multiple intents. The text here is just a single word. Ill give a hypothetical example.

"text": "who is the approver of my item",
        "intent": "item_approver",
        "entities": []

    
"text": "$100",
        "intent": "item_approver",
        "entities": [
{
            "start": 0,
            "end": 4,
            "value": "$100",
            "entity": "item_value"
          }

]

"text": "Can I keep certain item ",
        "intent": "item_retain",
        "entities": []

  // I can give another instance of $100 as with another intent  
"text": "$100",
        "intent": "item_retain",
        "entities": [
{
            "start": 0,
            "end": 4,
            "value": "$100",
            "entity": "item_value"
          }

]

Whenever a follow up question is asked from user about value of item, user responds with let say $100. Now, this follow up question can be asked for both intents, and whole context gets changed if it is misclassified. SO my question is how to handle such cases.

**Comment by tmbo** [comment]
The message should always have the same intent, the dialogue system is able to figure out what to do even if the message has the same intent in different dialogue parts, as long as the context is different the model will be able to predict different follow up actions. Using different intents for the same message does not work, as you noticed, because the model will learn to predict either one of the labels but not both.

**Comment by anupam20sep** [comment]
Sorry but I couldn't make out much from your answer, may be I didn't formatted the question properly. However I'll try to be more explanatory here, consider following nlu training data snippet. please note I have just one intent to $100

"text": "who is the approver of my item",
"intent": "item_approver",
"entities": []

"text": "$100",
"intent": "item_retain",
"entities": [
{
"start": 0,
"end": 4,
"value": "$100",
"entity": "item_value"
}




As we know stories are driven by intents, suppose we have two intents item_approver and item_retain. Both intents needs a mandatory slot value called "item_value" which happens to be some $ value in message. Now here is how conversation goes with explanations in  square brackets

**user> who is the approver of item**** [intent:item_approver, entities:null]

**bot>what is the value of your item** [since item_value slot is missing, bot will ask a follow up question]

**user> $100** [user just gave a one word answer. now here when I give $100 in NLU training data as item_retain intent, this msg will get classified as item_retain intent, but user in earlier messages wanted to ask for item_approver. If I give $100 in NLU training under both intent will it work? and even if it works,is this the correct way ]

bot> [it will start acting on the basis of last intent, which got changed when user gave $100 message]

if this doesn't make sense let me quote the restaurant example  here. In nlu training data "British" is the cuisine and intent is inform. It makes sense coz we have only one task of finding restaurants so just one business intent...what if in same bot  we need to compare two restaurants also...now I need to add one more intent of restaurant_compare and slot values needed are two cuisines type. Now my question is, again if I give only "British" in msg will it classify as "inform" intent or "restaurant_compare" intent or it will be decided on the basis of current state, but as far as I understand NLU interpreter has no info about the current state of bot. So if user intends to compare restaurant, he will end up doing restaurant search after giving "British" as msg because we have trained intent of "British: as inform and not restaurant_compare 

sorry for any typos
Thanks

**Comment by AbdurRub** [comment]
I have this question too , I have trained my nlu data on the basis of user first message. but when in dialogue when user respond to the 1st question answer , it falls in other intent. 
How to tackle this issue. 
Do we have to train these single word in nlu too , that cause some serious issues in intent classification.

**Comment by akelad** [comment]
So I don't think you need two separate intents for your case. With entering the price for example, you can define one global intent called `enter_price` and then following that you can have a custom action that stores this in the appropriate slot (or if the entity is named the same as the slot it should get filled automatically). So e.g.: 
```
## item approver story
* item_approver
    - utter_value
* enter_price{"item_value":"$100"}
    - utter_approver_confirm

## item retain story
* item_retain
    - utter_retain
* enter_price{"item_value":"$100"}
    - utter_retain_confirm
```

**Comment by anupam20sep** [comment]
@akelad 

I dont think it will help. consider a scenario where users first message was classified as "item_approver" and I need to invoke some action for this intent with item_value in my slot. When user gave next message as item_value which got classified as enter_price, after which a custom action is invoked where i'll look for current intent which happens to be enter_price, but I needed item_approver. In short, my tracker will keep all intents in a stack and which contains item_approver and enter_price.  

One way out could be, get all the states of tracker and extract all last conversation intents and always consider the first intent. But in this case, I need to reset my tracker everytime my action gets completed. I am doing this using "tracker.update(Restarted())", but it is not restarting the conversation state.

**Comment by akelad** [comment]
@anupam20sep So the simplest solution to this is to have a seperate action for `retain` and `approver` and write appropriate stories for this. There's no need to check what the previous intent of an action was this way - that's what the stories are for. 

```
## item approver story
* item_approver
    - utter_value
* enter_price{"item_value":"$100"}
    - action_approver

## item retain story
* item_retain
    - utter_retain
* enter_price{"item_value":"$100"}
    - action_retain
```
Core knows that your initial intent was `item_approver` and so it will know to perform the appropriate action later

**Comment by anupam20sep** [comment]
I'll try out these methods... Thanks for help .... @akelad @tmbo
