### ISSUE TITLE
   "error": "Not all required packages are installed. To use this pipeline, you need to install the missing dependencies. Please install sklearn"

### ISSUE THREAD

**Issue by gauravjain024** [RasaHQ/rasa_nlu#932]
**Rasa NLU version** (e.g. `0.7.3`):

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...):  spacy-sklearn

**Operating system** :  windows 10

**Issue**:  Not all required packages are installed. To use this pipeline, you need to install the missing dependencies. Please install sklearn

**Content of configuration file** (if used & relevant):
```json

```

**Comment by tmbo** [comment]
Did you make sure to install all dependencies?

**Comment by gauravjain024** [comment]
![image](https://user-images.githubusercontent.com/12432506/37763682-c94111d2-2de5-11e8-8606-0dc6207f82d1.png)

Getting this error

**Comment by sharukh2308** [comment]
I had the same issue[please install sklearn], but mine got fixed when I installed scipy and scikit-learn whilst running pip install rasa_nlu[spacy]... scipy was one dependency that may have been missed.

**Comment by aj0271** [comment]
@sharukh2308 Hi I Am having the same issue, can you please provide the exact commands.
Thanks!!

**Comment by akelad** [comment]
`pip install rasa_nlu[spacy]` should work fine for this, if that's the pipeline you're using

**Comment by gauravjain024** [comment]
i run the following commands 
Commands                                                                                 Status
pip install rasa_nlu                                                                      ok
git clone https://github.com/RasaHQ/rasa_nlu.git                     ok
cd rasa_nlu
pip install -r requirements.txt                                                      ok
pip install -e .                                                                               ok
pip install rasa_nlu[spacy]                                                           Ok
pip install -r alt_requirements/requirements_full.txt                  Error 
![capture2](https://user-images.githubusercontent.com/12432506/38129843-46b73cc0-341e-11e8-8aa3-d688b6244da7.PNG)

**Comment by wrathagom** [comment]
Too much going on in this one issue to really help troubleshoot. 

The errors seems to be focused around MITIE, but MITIE support has been removed. Can you try a fresh clone into a fresh environment and see if the error persists?

**Comment by sharukh2308** [comment]
Steps i did to setup spacy and crf, when i knew sudo pip install rasa_nlu[spacy] didn't work for me, and i wanted the latest version anyway. P.S. I am trying to have GCS storage option:
	1. Create & upload 
		- upload ~/config.json,~/credentials.json (Service account credentials), ~/demo-data.json
	2. Install dependencies
		1. sudo apt-get install python-pip
		2. sudo apt-get install libfreetype6-dev libpng12-dev
		3. sudo apt-get install python-dev
		4. sudo pip install sklearn-crfsuite scikit-learn scipy
	3. pull rasa_nlu 
		- git clone https://github.com/RasaHQ/rasa_nlu.git
		- cd rasa_nlu
		- sudo pip install -r requirements.txt
		- sudo pip install -e .
	4. Install spacy 
		- sudo pip install spacy
		- sudo python -m spacy download en_core_web_md
		- sudo python -m spacy link en_core_web_md en
	5. Set GOOGLE_APPLICATION_CREDENTIALS
		- export GOOGLE_APPLICATION_CREDENTIALS=~/credentials.json
	6. Install Google Cloud Storage:
		- sudo pip install google-cloud-storage
	7. Run initial training of model:
		- python -m rasa_nlu.train -c ~/config.json

**Comment by wrathagom** [comment]
@gauravjain024 were you able to get everything running?
