### ISSUE TITLE
If duckling (clojure) throws and error the whole pipeline breaks

### ISSUE THREAD

**Issue by r-wheeler** [RasaHQ/rasa_nlu#933]
**Rasa NLU version** (e.g. `0.7.3`):
'0.12.0a1'

**Used backend / pipeline** (`spacy_sklearn`, ...):
pipeline": [
        "rasa_nlu.utils.spacy_utils.SpacyNLP",
        "rasa_nlu.tokenizers.spacy_tokenizer.SpacyTokenizer",
        "rasa_nlu.featurizers.spacy_featurizer.SpacyFeaturizer",
        "rasa_nlu.featurizers.regex_featurizer.RegexFeaturizer",
        "rasa_nlu.extractors.crf_entity_extractor.CRFEntityExtractor",
        "rasa_nlu.extractors.entity_synonyms.EntitySynonymMapper",
        "rasa_nlu.extractors.duckling_extractor.DucklingExtractor",
        "rasa_nlu.classifiers.sklearn_intent_classifier.SklearnIntentClassifier"

**Operating system** (windows, osx, ...):

**Issue**:

```
from rasa_nlu.model import Interpreter 
interpreter = Interpreter.load("model")
interperter.parse("3 cups of sugar").  # this is an example from duckling docs 
```
This line needs to wrapped in a try/ catch: 

https://github.com/RasaHQ/rasa_nlu/blob/master/rasa_nlu/extractors/duckling_extractor.py#L128

**Content of configuration file** (if used & relevant):
```json

```

**Comment by tmbo** [comment]
fixed by #934
