### ISSUE TITLE
I am working on rasa-nlu. Intents are not recognizing while I give the related sentences and even when the trained sentences with case sensitive. And I am using same entity values with different names for diffenent intents, is this the reason why it is not responding properly?

### ISSUE THREAD

**Issue by Ramprakashd1** [RasaHQ/rasa_nlu#936]
**Rasa NLU version** (e.g. `0.7.3`):

**Used backend / pipeline** (`spacy_sklearn`, ...):

**Operating system** (windows, osx, ...):

**Issue**:

**Content of configuration file** (if used & relevant):
```json

```

**Comment by tmbo** [comment]
Thanks for reaching out. Unfortunately, there isn't enough detail in the issue description to help you.
