### ISSUE TITLE
Taking lots of time to train the data and its not showing any messages or logs

### ISSUE THREAD

**Issue by ajumell** [RasaHQ/rasa_nlu#940]
**Rasa NLU version**: 0.11.4

**Used backend / pipeline**: spacy_sklearn

**Operating system**: osx

**Issue**:
Hi all,

I am new in to machine learning and chat bots. I have installed the installed rasa core and rasa nlu and read the tutorials. After experimenting with the basic examples, I started to create a new data set from scratch and experiment on that. The issue I am facing now is training time. 

I gave **35000+** examples with **3 indents** and **2 entities**.
It has been running for 8 hours continuously with **99% CPU** usage and **1 to 2GB RAM** Usage.

The data I generated is using **Chatito**
Is there anything I can do to increase the training performance.

**Content of configuration file** (if used & relevant):
```json
{
  "pipeline": "spacy_sklearn",
  "path": "./models",
  "data": "data.json"
}
```

**Comment by ajumell** [comment]
After one more hour the memory usage increased to **2.2 GB** and Compressed memory which was 0 earlier is now **1.88 GB**

**Comment by amn41** [comment]
That is a lot of training data! I would start with some small experiments, because I don't think you'll need that many examples for 3 intents and 2 entities. Start with 100 (should train in a few seconds) and work your way up!

**Comment by ajumell** [comment]
ok let me try.

**Comment by ajumell** [comment]
I tried with 200 data for 3 indents and 2 entities. But the entities are not extracting from the result. If i give the exact data as in the training set its working. In my case one of the entity is name  and second entity is amount. Both can be dynamic I cant train all the possible names. What will be appropriate method to train such data.

**Comment by ajumell** [comment]
I also tried with 800 data. No difference.

**Comment by akelad** [comment]
Could you post your training data in a zip file so we can take a look?

**Comment by ajumell** [comment]
I generated the data using Chatito, This is the DSL for generating the dataset.

```
%[initTransactionAmountBeneficiary]
    ~[can] ~[please]? ~[send] @[beneficary] ~[currency]? @[amount]
    ~[can] ~[please]? ~[send] @[beneficary] @[amount] ~[currency]?
    ~[can] ~[please]? ~[send] @[beneficary] @[amount]

    ~[please]? ~[send] @[beneficary] ~[currency]? @[amount]
    ~[please]? ~[send] @[beneficary] @[amount] ~[currency]?
    ~[please]? ~[send] @[beneficary] @[amount]

    ~[want]? ~[send] @[beneficary] ~[currency]? @[amount]
    ~[want]? ~[send] @[beneficary] @[amount] ~[currency]?
    ~[want]? ~[send] @[beneficary] @[amount]

    ~[can] ~[please]? ~[send] ~[currency]? @[amount] to @[beneficary] 
    ~[can] ~[please]? ~[send] @[amount] ~[currency]? to @[beneficary]
    ~[can] ~[please]? ~[send] @[amount] to @[beneficary]

    ~[please]? ~[send]  ~[currency]? @[amount] to @[beneficary]
    ~[please]? ~[send]  @[amount] ~[currency]? to @[beneficary]
    ~[please]? ~[send] @[amount] to @[beneficary] 

    ~[want]? ~[send] ~[currency]? @[amount] to @[beneficary] 
    ~[want]? ~[send] @[amount] ~[currency]? to @[beneficary]
    ~[want]? ~[send]  @[amount] to @[beneficary]

%[initTransactionAmount]
    ~[can] ~[please]? ~[send] ~[currency]? @[amount]
    ~[can] ~[please]? ~[send] @[amount] ~[currency]?
    ~[can] ~[please]? ~[send] @[amount]

    ~[please]? ~[send] ~[currency]? @[amount]
    ~[please]? ~[send] @[amount] ~[currency]?
    ~[please]? ~[send] @[amount]

    ~[want]? ~[send] ~[currency]? @[amount]
    ~[want]? ~[send] @[amount] ~[currency]?
    ~[want]? ~[send] @[amount]

    ~[can] ~[please]? ~[send] ~[currency]? @[amount]
    ~[can] ~[please]? ~[send] @[amount] ~[currency]?
    ~[can] ~[please]? ~[send] @[amount]

    ~[please]? ~[send]  ~[currency]? @[amount]
    ~[please]? ~[send]  @[amount] ~[currency]?
    ~[please]? ~[send] @[amount]

    ~[want]? ~[send] ~[currency]? @[amount]
    ~[want]? ~[send] @[amount] ~[currency]?
    ~[want]? ~[send]  @[amount]

%[initTransactionBeneficiary]
    ~[can] ~[please]? ~[send] @[beneficary]
    ~[please]? ~[send] @[beneficary]
    ~[want]? ~[send] @[beneficary]

~[want]
    i want to
    i need to 

~[send]
    send
    transfer
    give

~[please]
    pls
    please

~[can]
    can you

@[beneficary]
    neeraj
    neeraj das
    niju
    ebrahim k k
    ajumell
    dasbingo

~[currency]
    Rs
    Rupees
    INR

@[amount]
    100
    1000
    200
    2000
    thousand
    ten thousand
    one lakh two hundred

```

**Comment by ajumell** [comment]
When I updated the config the data named entity recognition works well. This is the new config file.

```
{
  "pipeline": [
    "nlp_spacy",
    "tokenizer_spacy",
    "intent_entity_featurizer_regex",
    "intent_featurizer_spacy",
    "ner_crf",
    "ner_spacy",
    "ner_synonyms",
    "intent_classifier_sklearn"
  ],
  "path": "./models-03",
  "data": "data-03.json"
}
```

**Comment by akelad** [comment]
looks like your issue is solved then right? that config file looks good to me. `ner_duckling` also works very well for numbers, if you're still having issues with that

**Comment by ajumell** [comment]
Thanks @akelad, I will try that also.
