### ISSUE TITLE
What is the start and end keywords

### ISSUE THREAD

**Issue by DhruvMevada** [RasaHQ/rasa_nlu#941]
**Issue**: what is the meaning of start & end keyword here? what is use of it?

**Content of configuration file** (if used & relevant):
```json
{
  "text": "show me chinese restaurants",
  "intent": "restaurant_search",
  "entities": [
    {
      "start": 8,
      "end": 15,
      "value": "chinese",
      "entity": "cuisine"
    }
  ]
}
```

**Comment by ajumell** [comment]
That's the index position of the value

The value chinese starts at index: 8 and ends at index: 15

8:c, 9:h, 10:i, 11:n, 12:e, 13:s, 14:e 

In python range the lower bound will be included and upper bound wont be included in the sequence. So the index 8 is included and 15 won't be included.

Hope this helps.

**Comment by DhruvMevada** [comment]
ya got it. thanks. 
Every time I need to count start & end index ? it can be done manually only?

**Comment by akelad** [comment]
So there's a bunch of open source tools to annotate your data that does this for you automatically, e.g. https://rasahq.github.io/rasa-nlu-trainer/

**Comment by DhruvMevada** [comment]
Thanks a lot @akelad
