### ISSUE TITLE
Sentiment Analysis is showing 0.0 in every result

### ISSUE THREAD

**Issue by AbdurRub** [RasaHQ/rasa_nlu#945]
**Rasa NLU version** : 0.11

**Used backend / pipeline** (`spacy_sklearn`, ...): Spacy_Sklearn

**Operating system** (windows, osx, ...): ubuntu 17.04

**Issue**:
Sentiment Analysis is showing 0.0 in every case. is this issue or it requires some other things to give sentiment analysis.

![sentiment](https://user-images.githubusercontent.com/29856813/37958056-eafd58e4-31c8-11e8-95aa-fc5046ef35ae.png)

**Comment by AbdurRub** [comment]
This is also showing error. so I modified it.  {sentence.sentiment.sentiment}

for sentence in blob.sentences:
        sentiment = sentiment + sentence.sentiment[1]
        subjectivity += sentence.sentiment.subjectivity

**Comment by akelad** [comment]
Yeah this was just something we experimented with a while ago, which is why it's also not merged into master :)

**Comment by AbdurRub** [comment]
should we expect it in 12.0 release?

**Comment by akelad** [comment]
No, this isn't something we're really focused on.
