### ISSUE TITLE
coloredlogs is imported but is missing in requirements.txt

### ISSUE THREAD

**Issue by nan0tube** [RasaHQ/rasa_nlu#947]
**Rasa NLU version** (e.g. `0.7.3`):
master
**Used backend / pipeline** (`spacy_sklearn`, ...):

**Operating system** (windows, osx, ...):

**Issue**:
`coloredlogs` is imported but is missing in `requirements.txt` and the latest docker image.
https://github.com/RasaHQ/rasa_nlu/blob/67d5be534eff6ffb227886fe2f10e6dd7475ee85/rasa_nlu/utils/__init__.py#L289

**Comment by amn41** [comment]
yeah that doesn't seem right! could you please create a PR?

**Comment by akelad** [comment]
PR #948 was merged
