### ISSUE TITLE
Entities Extraction Issue

### ISSUE THREAD

**Issue by AbdurRub** [RasaHQ/rasa_nlu#955]
**Rasa NLU version** (e.g. `0.7.3`):  0.11.4

**Used backend / pipeline** (`spacy_sklearn`, ...): Spacy_Sklear

**Operating system** (windows, osx, ...): Ubuntu 17.10

**Issue**:
Is there any word embeddings too for Entity Extraction , how it extract entities , I am facing difficulties in extracting entities.

It focuses on before and after words.
any guideline or any thumb of rule. how to cover this issue because it is very hard to do this for every entity and word.

**Comment by akelad** [comment]
Hi, could you post more details on what kind of entities you're trying to extract?

**Comment by AbdurRub** [comment]
I am trying to extract 
new or used vehicle type , car models , car makes , appointment scheduling , parts inquiry , parts name stuff.  
The problem is my sales department queries are pretty much same as parts department queries. 
I just observe entity is detected on basis of before and after word , if we change the sentence structure it will not detect it. 
how to tackle this issue. can we remove this before and after word dependency and it just focus on entity word. 
Plus
I want to know what is that ner_phrase matcher?

**Comment by akelad** [comment]
Have you tried using this tool for generating training data in different sentences? https://github.com/rodrigopivi/Chatito

**Comment by AbdurRub** [comment]
Yes @akelad. Its a great tool.  Waiting for phrase_matcher merge. @wrathagom

**Comment by akelad** [comment]
cool, i'll close this issue for now then :)
