### ISSUE TITLE
Support pt-br (brazilian portuguese)?

### ISSUE THREAD

**Issue by luisdemarchi** [RasaHQ/rasa_nlu#960]
**Rasa NLU version**:
0.12.0

**Used backend / pipeline**:
spacy_sklearn

**Operating system**:
osx

**Issue**:
All the documentation says that it supports the Portuguese language, but does not specify if it is portuguese of portugual or of Brazil. I did not find that question anywhere. Could anyone clarify which of the Portuguese versions is supported?

**Comment by akelad** [comment]
https://spacy.io/models/pt Spacy don't specify this either, but it's trained on Wikipedia. I assume that's a mix of both

**Comment by luisdemarchi** [comment]
@akelad  I did some initial tests and it seems to really work well on both types of Portuguese.
@znat Your comment is very valuable.

Thank you for your help.
