### ISSUE TITLE
RASA architecture

### ISSUE THREAD

**Issue by Rahul6818** [RasaHQ/rasa_nlu#961]
Can anyone explain the complete architecture of the RASA, from querying a query to outputing the response.

**Comment by wrathagom** [comment]
The website provides a good overview of the entire stack: https://rasa.com/products/rasa-stack/
The docs are an excellent place to glean this from: https://nlu.rasa.com

Do those not give you what you need?

**Comment by wrathagom** [comment]
Closing, let me know if the above didn't answer your questions.
