### ISSUE TITLE
Use config file params when training in with Python

### ISSUE THREAD

**Issue by danbeggan** [RasaHQ/rasa_nlu#962]
At the moment if you specify a fixed_model_name and project in your config file but train through python, the trainer will not use those variables when persisting.

Instead you have to pass them in as params to the persist method like so:
```
trainer = Trainer(RasaNLUConfig(config))
trainer.train(training_data)
self.model_directory = trainer.persist(path=path, project_name=project, fixed_model_name=fixed_model_name)
```

It would be more intuitive if you specified those variables in the config that the trainer would use them (like it does when training from command line).

**Comment by danbeggan** [comment]
I'm using version 0.11.4

My config file looks like this:

```
{
  "pipeline": ["nlp_spacy", "tokenizer_spacy", "ner_crf"],
  "fixed_model_name": "name_extractor",
  "project": "bot",
  "language": "de",
  "path" : "/models/",
  "data" : "/data/intent/state_name_with_entity.json"
}
```

This is the output of the trainer.persist when I don't pass in the params to the persist method:

```/models/default/model_20180406-080613```

This is the output of the trainer.persist when I pass in the params to the persist method (and what I expected without passing in the params):

```/models/bot/name_extractor```

**Comment by tmbo** [comment]
This has been fixed in the latest master. These parameters are not longer part of the configuration anymore (partly because of the reasons you mentioned: there were a number of inconsistencies with the configuration value use).

**Comment by wrathagom** [comment]
closing for the reasons @tmbo gave :)
