### ISSUE TITLE
Possibility for extracting entity with RegEx

### ISSUE THREAD

**Issue by Kaijiro** [RasaHQ/rasa_nlu#963]
I just checked the project history and it seems that someone wanted to create a component allowing the use of a RegEx to facilitate with this PR : [#417](https://github.com/RasaHQ/rasa_nlu/pull/417).

But this PR had its scope changed and the [actual documentation](https://github.com/RasaHQ/rasa_nlu/blob/master/docs/dataformat.rst#regular-expression-features) about the `intent_entity_featurizer_regex` clearly state that : 

> Regex features don't define entities nor intents! They simply provide patterns to help the classifier recognize entities and related intents. Hence, you still need to provide intent & entity examples as part of your training data!

So, is it possible to do such detection with just RegEx ?

**Comment by akelad** [comment]
So as that says, you need to provide intent & entity examples for these anyways, but adding regex features in your training data file can help recognise those.

**Comment by Kaijiro** [comment]
But I cannot base the entity recognition only on RegEx ?

**Comment by wrathagom** [comment]
No, from my reply on Gitter

>So as you saw Rasa doesn’t have just a straight regex parser/finder. The regex parser feeds the CRF for entity detection, but still as part of a model.

**Comment by Kaijiro** [comment]
spaCy can uses matchers with RegEx. Any chance for this to be implemented ?

**Comment by wrathagom** [comment]
@Kaijiro can I get a link to the docs for that feature? I am seeing stuff about regex flags, but they sound similar to what Rasa NLU is doing.

**Comment by Kaijiro** [comment]
You can found the doc [here](https://spacy.io/api/matcher) and a related issue : [#882](https://github.com/explosion/spaCy/issues/882)

We managed to create a pipeline with their [PhraseMatcher](https://spacy.io/api/phrasematcher) in order to locate cities in user input. However, it is dirty and may not be the smartest way to to do it.

```python
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

import json
import os

from spacy.matcher import PhraseMatcher
from typing import Any
from typing import Dict
from typing import Text

from rasa_nlu.extractors import EntityExtractor
from rasa_nlu.training_data import Message

MATCHER_MODEL_FILE_NAME = "matcher_model.json"

class SpacyMatcherEntityExtractor(EntityExtractor):
    name = "ner_matcher"

    provides = ["entities"]

    requires = ["spacy_nlp"]

    matcher = None

    rules = []

    def process(self, message, **kwargs):
        # type: (Message, **Any) -> None

        spacy_nlp = kwargs.get("spacy_nlp", None)
        doc = spacy_nlp(message.text.lower())
        extracted = self.add_extractor_name(self.extract_entities(spacy_nlp, doc))
        message.set("entities",
                    message.get("entities", []) + extracted,
                    add_to_output=True)

    def add_rule(self, name, *patterns):
        if self.matcher is not None:
            self.matcher.add(name, None, *patterns)
            self.rules.append({"name": name, "patterns": [p.text for p in patterns]})

    def init_matcher(self, spacy_nlp):
        self.matcher = PhraseMatcher(spacy_nlp.vocab)

    def train(self, training_data, config, **kwargs):
        spacy_nlp = kwargs.get("spacy_nlp", None)
        if self.matcher is None:
            self.init_matcher(spacy_nlp)

        for rule in training_data.matcher_examples:
            rule_patterns = [spacy_nlp(text) for text in rule['patterns']]
            self.add_rule(rule['name'], *rule_patterns)

    @classmethod
    def load(cls,
             model_dir=None,  # type: Text
             model_metadata=None,  # type: Metadata
             cached_component=None,  # type:
             **kwargs  # type: **Any
             ):

        extractor = SpacyMatcherEntityExtractor()
        with open(os.path.join(model_dir, MATCHER_MODEL_FILE_NAME), "r") as model:
            spacy_nlp = kwargs.get("spacy_nlp", None)
            extractor.init_matcher(spacy_nlp)
            rules = json.load(model)
            for rule in rules:
                patterns = [spacy_nlp(pattern) for pattern in rule["patterns"]]
                extractor.add_rule(rule["name"], *patterns)

        return extractor

    def persist(self, model_dir):
        # type: (Text) -> Optional[Dict[Text, Any]]

        with open(os.path.join(model_dir, MATCHER_MODEL_FILE_NAME), "w") as file:
            json.dump(self.rules, file)
        return {"matcher_file": MATCHER_MODEL_FILE_NAME}

    def extract_entities(self, spacy_nlp, doc):
        # type: (Nlp, Doc) -> List[Dict[Text, Any]]

        matches = self.matcher(doc)
        entities = []
        for match_id, start, end in matches:
            rule_id = spacy_nlp.vocab.strings[match_id]
            span = doc[start: end]
            entities.append({
                "entity": rule_id,
                "value": span.text,
                "start": start,
                "confidence": 1,
                "end": end
            })
        return entities
```

Maybe it can be a base to use in order to create / enhance the extraction system of Rasa NLU

**Comment by akelad** [comment]
I'm wondering how come you're using regex for city detection rather than the pretrained entity recogniser `ner_spacy`, which has the entity "GPE"?

**Comment by Kaijiro** [comment]
It doesn't match well on French cities on our last test (maybe did we do some bad things tho).

We worked directly with spaCy documentations and found something that maybe Rasa documentation should include : in order to create our own entities, it it very advised to create phrase templates and put data examples in those templates.
As we are making progress with those models, we do understand that RegEx matcher may be useless. What is your personnal point of vue ?

**Comment by tmbo** [comment]
How did you specify the matching regular expressions in the training data?

**Comment by Kaijiro** [comment]
We took the format from the regex featurizer.
