### ISSUE TITLE
Unable to detect entity if words are rearranged?

### ISSUE THREAD

**Issue by Sanjeev2487** [RasaHQ/rasa_nlu#971]
Hi,
My models sometime fails to detect entities in simple cases. I have an intent `Open` and a Entity 'Apparatus'   which can take value `window`, `door`. It detects entity `window` in `open window` and fails to detect the same in `window open`.

I was under the impression that sentence is nothing but the average of their word embedding vectors then how come changing the order is affecting the result ? And also if anyone can explain a bit about how entity detection is being done in RASA  and how to go about debugging that ?

**Content of configuration file** (if used & relevant):
```json

```

**Comment by znat** [comment]
vectors are used for intent classification, but not for entity extraction which is positional. It looks at the features of a window of words surrounding the entity. So you need to provide more examples with different positions

**Comment by wrathagom** [comment]
@Sanjeev2487 let us know if more training data didn't help. Another thing that may help would be to use a program to generate larger amounts of training data for oyu. The one that comes to mind given your examples is https://rodrigopivi.github.io/Chatito/

**Comment by Sanjeev2487** [comment]
Hi @wrathagom ,
That was indeed helpful. With more training data of rearranged words entities are getting detected correctly.
