### ISSUE TITLE
Automatic Learning

### ISSUE THREAD

**Issue by Harish0596** [RasaHQ/rasa_nlu#973]
**Rasa NLU version** : 0.12.0a2

**Used backend / pipeline** :spacy_sklearn

**Operating system** :windows 10

**Issue**: Not learning automatically, like if someone had a chat with the bot we expect the bot to train automatically from the conversation it had with the user but i don't think it's happening or if it is happening how can achieve it ?
Right now i am making a note of all the situations where it fails and appending some more data in data.md manually after the conversation and building some more stories to overcome those errors.

**Comment by akelad** [comment]
Are you talking about interactive learning? because the stories get automatically generated the way you corrected them and then you can add this to your training data and re-train your core model. It doesn't learn "automatically" as soon as you've corrected it.

**Comment by Harish0596** [comment]
@akelad No, I am not talking about interactive learning what I mean is the bot should be intelligent enough to learn on its own(from the user) without human(developer) intervention after sometime

**Comment by akelad** [comment]
That would be reinforcement learning, which we don't currently use.

**Comment by Harish0596** [comment]
@akelad  Yeah right now I am using interactive learning only but still, I need to  build the model, run the bot every time if I update anything also think of a scenario when I am running the bot in server serving multiple user requests, at that time it should learn automatically from conversations generated by every user and update itself rather than developer updating it daily based on the logs generated.
Does rasa platform contain Automatic learning I mean reinforcement learning?

**Comment by akelad** [comment]
No, the platform doesn't contain reinforcement learning. Reinforcement learning for conversational AI is still in the early stages of research. And it's not necessarily always a good thing - talking to real users and learning from them might also mean that the bot starts learning something completely different than you want it to.

I'm just wondering what's your use case for the bot, and how many stories do you have so far? Because at some point when you have enough stories it should be able to generalize to some unseen conversations at least.

**Comment by Harish0596** [comment]
stories are fine but I want to give the query entered by the user to the bot as the training data so that it can perform very well in intent classification and entity extraction.

**Comment by wrathagom** [comment]
Is this a Rasa Core request or Rasa NLU?

**Comment by akelad** [comment]
I'd say NLU. What you're requesting @Harish0596 is something the Platform does actually, as in all the unseen messages from your users get sent to an inbox where you can then add them to the training data or correct the labels. You can learn more about this here http://rasa.com/products/rasa-platform/ and if you're interested please contact our sales department

**Comment by Harish0596** [comment]
@akelad sure thanks

**Comment by ARORACHAITANYA** [comment]
@Harish0596 was just wondering if this feature is now available after 2 years ! 
If yes can someone link up the documentation ?
PS - I am just a newbie with RASA

**Comment by akelad** [comment]
Annotating new user messages is something you can do with Rasa X now - https://rasa.com/docs/rasa-x/
