### ISSUE TITLE
Unable to Use Trained model, always showing fallback/not available

### ISSUE THREAD

**Issue by roysoham** [RasaHQ/rasa_nlu#976]
**Rasa NLU version** (e.g. `0.7.3`): `0.10.4`

**Used backend / pipeline** : `"nlp_spacy", "tokenizer_spacy", "intent_featurizer_spacy", "intent_entity_featurizer_regex", "intent_classifier_sklearn", "ner_crf", "ner_synonyms"`

**Operating system** (windows, osx, ...): Ubuntu 16.04 Xenial

**Issue**: Unable to use model after successful training, attached is the screen shot 
![image](https://user-images.githubusercontent.com/9800004/38508989-3c99ba4c-3c3e-11e8-8b9e-a8ed87186ea6.png)

**Content of configuration file** (if used & relevant):
```{
  "pipeline": ["nlp_spacy", "tokenizer_spacy", "intent_featurizer_spacy", "intent_entity_featurizer_regex", "intent_classifier_sklearn", "ner_crf", "ner_synonyms"],
  "project": "invoice",
  "fixed_model_name": "findgst1",
  "mitie_file" : "./MITIE/MITIE-models/english/total_word_feature_extractor.dat",
  "path" : "./models/",
  "spacy_model_name": "en",
  "data" : "./data/findgst_7apr2018.json",
  "nlu_python_packages": "/usr/local/lib/python2.7/dist-packages",
  "language": "en",
  "max_training_processes": 1,
  "max_number_of_ngrams": 7,
  "ner_crf": {
    "BILOU_flag": true,
    "features": [
      ["low", "title", "upper", "pos", "pos2"],
      ["bias", "low", "word3", "word2", "upper", "title", "digit", "pos", "pos2", "pattern"],
      ["low", "title", "upper", "pos", "pos2"]],
    "max_iterations": 50,
    "L1_c": 1,
    "L2_c": 1e-3
  },
  "intent_classifier_sklearn": {
    "C": [1, 2, 5, 10, 20, 100],
    "kernel": "linear"
  }
  }


```

**Comment by wrathagom** [comment]
Are you training with the Command line or HTTP API?

What is the console output during training. To me it looks like the model isn't being saved.

**Comment by roysoham** [comment]
![image](https://user-images.githubusercontent.com/9800004/38561578-040977fe-3cf6-11e8-9085-1026505365fb.png)
Trained again, hope this is a successful training as stated

**Comment by roysoham** [comment]
Removed Fixed Model Name, its working now
