### ISSUE TITLE
Inconsistent confidence scores when synonym words are used

### ISSUE THREAD

**Issue by Sanjeev2487** [RasaHQ/rasa_nlu#977]
Hi,

In my database, I have `DecreaseValue` intent and in my `synosyms.json` I have synonyms for the word `decrease` ( `decrement | reduce | turn down | lower | crank down | drop` )
My training data have sentences with `decrease` word most of the time. But while testing it gives very poor confidence score for synonyms which it has not seen(like `decrement`).  I do not understand why that is happening when both are synonyms.

**Is it the observed behavior?  if I did not use one of the synonyms in training. If it is what is the use of synonyms then ?**

Again I understand that there are two methods to use synonyms :=

-  Add it in `synonyms.json`

- If it is an entity then , we can set 'value' field of that entity to synonyms.

**What is correct method to use synonyms ?**

**Comment by wrathagom** [comment]
Did you see the note in the docs about how synonyms are used? 
>Please note that adding synonyms using the above format does not improve the model’s classification of those entities. Entities must be properly classified before they can be replaced with the synonym value.

Essentially if you want your entity model to recognize all of those different words then you need to use a larger variety of them in your sentences so the model can generalize that those words are acceptable for that entity. Make sure Rasa is recognizing each one of them before you start trying to use Synonyms. Then when Rasa parses your request and finds the entity `lower` it will look into the synonyms and use the synonyms to replace `lower` with `decrease`...

This is one of those things we struggle to describe how it works :/

**Comment by Sanjeev2487** [comment]
Thanks @wrathagom ,
As per my understanding now, 
- Synonym words are helpful only if it is related to any entity not for any word like `decrease` per say in my above example.
-  Using synonyms doesn't improve the entity classification rather it just gives the result back in terms of familiar discrete words.

If my understanding is correct please go ahead and close the issue.

**Comment by wrathagom** [comment]
The second point in particular I think is the big take away of how Synonyms should be used with Rasa NLU! Looks like you've got it.
