### ISSUE TITLE
How to train with Regex, is Entity required for each regex

### ISSUE THREAD

**Issue by roysoham** [RasaHQ/rasa_nlu#979]
**Rasa NLU version** : `0.10.4`

**Used backend / pipeline** : `"nlp_spacy", "tokenizer_spacy", "intent_featurizer_spacy", "intent_entity_featurizer_regex", "intent_classifier_sklearn", "ner_crf", "ner_synonyms"`

**Operating system** (windows, osx, ...):

**Issue**: 

I have trained Regex as features in the training config. ` "regex_features": [
        "pattern": "[0-9]{2}/[0-9]{2}/[0-9]{4}", 
        "name": "date1"
      },]`
But after training I am unable to get any of the above pattern.

For each Regex, do I have to create a corresponding Entity (In this case I did not create)?
Let's say I have 4 different Regex, then do I have to create 4 different entities.

**Content of configuration file** (if used & relevant):
```json

```

**Comment by roysoham** [comment]
Can someone share a complete rasa training example, with uses Regex & Common examples both

**Comment by wrathagom** [comment]
From the docs:
> Regex features don’t define entities nor intents! They simply provide patterns to help the classifier recognize entities and related intents. Hence, you still need to provide intent & entity examples as part of your training data!

The `ner_crf` pipeline component is what does entity recognition in your pipeline. By default it looks at a set of [features](https://rasa-nlu.readthedocs.io/en/latest/config.html#features) to try to determine whether a word is an entity or not. Whenever `regex_features` are provided each token is checked against all regex patterns. If the token matches one of those regex patterns then the pattern name is added as a feature to the CRF...

All of that to say:
 - You still have to create all of the entities you need and label them in `common_examples`
 - Providing a regex pattern "Boosts" the ability of the CRF to recognize those entities
 - The Regex name doesn't have to match the entity name or anything like that.

Does that help?

**Comment by akelad** [comment]
"getting tagging words from unstructured data" - can you be more specific as to what type of entities you're exactly trying to extract?

**Comment by tmbo** [comment]
I'll close this for now, please let us know if you have any further questions.
