### ISSUE TITLE
Can I connect to DB and get the details or store the details given by user to bot  ?

### ISSUE THREAD

**Issue by dilipbobby** [RasaHQ/rasa_nlu#983]
**Issue**: It is possible to store the user details given details in a DB given to our chat bot ! if yes can I have any example of that ?

**Comment by akelad** [comment]
This is a question regarding the use of rasa core no? This would be done using a custom action to query your DB, which you can read more about here: https://core.rasa.com/domains.html#defining-custom-actions

**Comment by dilipbobby** [comment]
Sorry for asking in wrong place ! I will work on it ! Thank you :)
