### ISSUE TITLE
training data. same text with different entity names

### ISSUE THREAD

**Issue by hewei816** [RasaHQ/rasa_nlu#984]
**Rasa NLU version 0.12.0a1

**Used backend / pipeline** (`spacy_sklearn`, ...):

**Operating system osx 

**Issue**: 
training data. The same text with different entity names
 However, both of them were confused during the dialogue.
**Content of configuration file** (if used & relevant):
```json
  {
        "text": "shenzhen",
        "intent": "travel",
        "entities": [
          {
            "start": 0,
            "end": 8,
            "value": "shenzhen",
            "entity": "departureCity"
          }
        ]
      },
      {
        "text": "shenzhen",
        "intent": "travel",
        "entities": [
          {
            "start": 0,
            "end": 8,
            "value": "shenzhen",
            "entity": "terminusCity"
          }
        ]
      },
```

**Comment by akelad** [comment]
The reason for this is that those are just single words, there is no difference at all between the sentences and so you shouldn't label them as the same entities. If you want this distinction you have to provide sentence examples for both, like:

```
- I am going to [shenzhen](terminusCity)
- I am departing from [shenzhen](departureCity)
```
If you have just the text "shenzhen" then I would have a third entity called just `City` and just handle this accordingly in an action or your stories.

**Comment by hewei816** [comment]
thank you !
