### ISSUE TITLE
How to define custom entities in RasaNLU?

### ISSUE THREAD

**Issue by raypp** [RasaHQ/rasa_nlu#987]
**Rasa NLU version**: `0.11.4`

**Used backend / pipeline**: `[“nlp_mitie”, “tokenizer_jieba”, “ner_mitie”, “ner_synonyms”, “intent_classifier_mitie”]`

**Operating system**: `Linux`

**Issue**:

**Can I define custom entities like this?**:
```json
{
  "color": {
    "automatically_extensible": true,
    "use_synonyms": true,
    "data": [
      {
        "value": "white",
        "synonyms": []
      },
      {
        "value": "yellow",
        "synonyms": []
      },
      {
        "value": "pink",
        "synonyms": []
      },
      {
        "value": "blue",
        "synonyms": []
      }
    ]
  }
}
```

**Comment by raypp** [comment]
@akelad Thank you for the reply! I have read that doc page several times, but I only got `training data format` like following: 

```json
{
    "rasa_nlu_data": {
        "common_examples": [],
        "regex_features" : [],
        "entity_synonyms": []
    }
}
```

I can't define a custom entity like `color`, and define all values for this `color` entity. Just like the example in my post above. `Training data format` can only define some examples, not whole values.

**Comment by akelad** [comment]
what do you mean with "whole values"?
To define the custom entity `color` you just have to add various sentences with colors in them and label them accordingly, e.g. (this is markdown format, which is easier to read, but ofc the same can be done with json)
```
## intent:provide_colour
- I want the colour [red](colour)
- I like [blue](colour)
```

**Comment by raypp** [comment]
Got it, that's a solution any way.

Thank you! @akelad

**Comment by akelad** [comment]
no worries, i'll close this for now then
