### ISSUE TITLE
Increase debug output of training threads to troubleshoot brokenprocesspool

### ISSUE THREAD

**Issue by Huljo** [RasaHQ/rasa_nlu#992]
**Rasa NLU version** : 0.12.0a2

**Used backend / pipeline** : spacy_sklearn

**Operating system** : docker linux (hosted by Ubuntu 16.04.4)

**Issue**:
Trying to run a training after started a [docker](https://hub.docker.com/r/rasa/rasa_nlu/)(:latest-full / :0.12.2-spacy) container (-p 5000:5000) using this request : 
```
Method: POST
Data: {"rasa_nlu_data":{"common_examples":[{"intent":"intent1","text":"exp1","entities":[]},{"intent":"intent1","text":"exp2","entities":[]}]}}
Url: localhost:5000/train?name=test_20180414-211311&project=test
```

Server response :

```
rasa_nlu.data_router  - [Failure instance: Traceback (failure with no frames): <class 'concurrent.futures.process.BrokenProcessPool'>: A process in the process pool was terminated abruptly while the future was running or pending.
Unhandled Error
Traceback (most recent call last):
 File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 500, in errback
     self._startRunCallbacks(fail)
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 567, in _startRunCallbacks
     self._runCallbacks()
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
     current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1442, in gotResult
      _inlineCallbacks(r, g, deferred)
--- <exception caught here> ---
 File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python3.6/site-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
      return g.throw(self.type, self.value, self.tb)
    File "/app/rasa_nlu/server.py", line 299, in train
      data_file, project, RasaNLUModelConfig(model_config))
    File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
      current.result = callback(current.result, *args, **kw)
    File "/app/rasa_nlu/data_router.py", line 307, in training_errback
     failure.value.failed_target_project)
  builtins.AttributeError: 'BrokenProcessPool' object has no attribute 'failed_target_project'
```
**Machine** :
4gb ram 
40gb ssd
Ubuntu 16.04.4

**Content of configuration file** :
```yaml
language: "en"

pipeline: "spacy_sklearn"
```

**Comment by tmbo** [comment]
Mhm it seems like the process pool broke. Is this happening reliably for you?

**Comment by tmbo** [comment]
I mean you are using the same docker file on both machines, right? So maybe it is a memory issue - how much memory does the server with the failing container have?

**Comment by tmbo** [comment]
There is no real minimum requirement, it depends on the language model you are using. If you use the large english language model, that one is 1gb. That model gets loaded once for serving requests and once for training - so that is at least 2gb. We usually suggest a minimum of 4gb for training & serving models.

Does the error happen right with the first training? Are you sending any other requests to that server before the training one?

**Comment by Huljo** [comment]
Thank you for all the information about requirements.
I use english model so I guess 4gb is enough.
Yes the error happen with the first training. No request before or after.
I run the container then I send the request.

**Comment by Polarisation** [comment]
I had exactly the same error using the Docker image for a deployment. Increasing the memory fixed the issue for me.

**Comment by Huljo** [comment]
Hi @Polarisation, can you tell me how much memory you initially had and how much you added please ?
Did you use the English model ?

**Comment by Polarisation** [comment]
@Huljo Initially I had very little, maybe 128MB or 256MB. Raising this to 900MB got me past this error with training, but I had a further memory error when trying to query (that one was clearer as it included the term "MemoryError"). I'm now using 4GB and it seems to work fine.

I used the `rasa/rasa_nlu:0.12.2-spacy` docker image with the [default config.yml](https://github.com/RasaHQ/rasa_nlu/blob/master/sample_configs/config_spacy.yml), so yes it was the English model.

**Comment by DigitalDean** [comment]
I too am struggling with this same issue.

Running rasa_nlu across 4 machines and it's only failing with the same error: 

builtins.AttributeError: 'BrokenProcessPool' object has no attribute 'failed_target_project'

on one of them. All running the same packages and the only difference is the python versions.

Python 3.6.5 - error as above (24gb ram 2017 iMac i5)
Python 3.6.0 - works fine (16gb ram 2015 MacBook i7) 
Python 3.5.2 - works fine (AWS c4.xlarge)
Python 2.7.12 - works fine (AWS t2.medium)

Error thrown when training anything, from 3k intents down to 1 intent.

Parsing and every other rasa endpoint works as expected.

**Comment by Huljo** [comment]
@Polarisation  Thanks, I tried with `rasa/rasa_nlu:0.12.2-spacy` but process pool still broken 1 sec after I sent the first request.

````
> free -t -m
                    total        used        free      shared  buff/cache   available
Mem:           3924         329         743         207        2851        3264
Swap:           510          18           492
Total:           4435         348        1235
````
I still having 743Mb of free memory during the training.

**Comment by Huljo** [comment]
@DigitalDean have you tried to downgrade Python to 3.6.0 on your i5 ?

**Comment by wrathagom** [comment]
The automated tests only go to 3.6.3 at the moment, so if it is something really python related might not have seen it yet.

@DigitalDean are you running locally or with Docker on your Mac?

@Huljo you only have 743M before the process starts? and using which model? When the training process forks it loads another copy of the spaCy model into memory.

@milutz @PHLF just FYI in case there's something going on here in the code you're familiar with.

**Comment by DigitalDean** [comment]
@Huljo just tried downgrading to Python 3.6.0 on the i5 - same error.

All installs are using rasa_nlu version 0.12.0a1
All installs are the same from one git repository which was initially built on the MacBook using this installation process: https://nlu.rasa.com/installation.html

@wrathagom locally, Docker not used on any machines.

**Comment by PHLF** [comment]
@DigitalDean 
It looks like underlying process is terminating abruptly for some reason. It may not be related to the process pool.
Could you try to edit [data_router.py](https://github.com/RasaHQ/rasa_nlu/blob/master/rasa_nlu/data_router.py) as follow?

[L24](https://github.com/RasaHQ/rasa_nlu/blob/master/rasa_nlu/data_router.py#L24):

```python
from rasa_nlu.train import do_train_in_worker
```
becomes
```python
from rasa_nlu.train import do_train
```
and
[L319-323](https://github.com/RasaHQ/rasa_nlu/blob/master/rasa_nlu/data_router.py#L319-L323)

```python
        result = self.pool.submit(do_train_in_worker,
                                  train_config,
                                  data_file,
                                  path=self.project_dir,
                                  project=project)
```
becomes
```python
        result = do_train(train_config,
                          data_file,
                          path=self.project_dir,
                          project=project)
```

Yes these changes willl break your rasa_nlu server but may give some hints about your issue.

**Comment by wrathagom** [comment]
sorry @pradeepmvn, @PHLF is a busy guy, he seems to only come out of hiding when I call him out ;)

In all likelihood if we want to increase the debug output of the training threads we would have to mark this one as help wanted and hope that he or someone else has time to implement them.

Are you still suffering from this?

**Comment by Huljo** [comment]
Increasing the debug output of the training threads would be a really good thing.
Can we add the help tag ?
I still suffering from this.
