### ISSUE TITLE
Remove github pages publishing of docs

### ISSUE THREAD

**Issue by tmbo** [RasaHQ/rasa_nlu#998]
Currently, the documentation is published on two different servers. we should only keep `https://nlu.rasa.com` - we can't just redirect to the version hosted by ghpages, as it 
doesn't allow us to use SSL certificates at the moment.

@amn41 how is the documentation build on the nlu.rasa.com server, is it build from scratch, or is it using the documentation build by travis and pushed to the gh-pages branch?

**Comment by amn41** [comment]
the server just `git pull`s the gh-pages branch

**Comment by tmbo** [comment]
Alright, we need to make it pull from a branch with a different name, e.g docs - I’ll create a PR
